### ISSUE TITLE
Mandatory Fields Information

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#10]
Mandatory Fields Information
How are the mandatory fields distinguished when left empty (which prohibits data saving)?
atm you ca

a) talk about design, layout (empty, filled)
b) implement

**Comment by cadavre** [comment]
Already designed and in implementation for primary and secondary widgets. Also read-only state.

[Preview for primary](https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/108112/797371/JC0PYa2TqelU5CY/Zrzut%20ekranu%202016-08-29%20o%2012.07.23.png)
