### ISSUE TITLE
Actions missing in grid View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#100]
Actions missing in grid View.
When opening Grid View, the Actions must be shown and executable on the filtered OR selected rows. If none are selected, then action shall be done for the filtered rows. If selected then process executed on the selected rows.

![image](https://cloud.githubusercontent.com/assets/13365687/20481121/ddd5228e-afe5-11e6-82ef-00e749b96528.png)

**Comment by damianprzygodzki** [comment]
@cadavre it is colliding with assumption that after clicking outside table, selection dissapearing. There is no posibility to distinguish between Header->MenuOverlay and elsewhere. Should we leave select onBlur?

**Comment by teosarca** [comment]
hi guys, 
pls note that i've documented the new endpoints on https://github.com/metasfresh/metasfresh-webui/issues/50
