### ISSUE TITLE
row selection in picking

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1006]
### Type of issue
Bug 
### Current behavior
when you open picking, the first row is not preselected, but the last one, or random one
### Expected behavior
the first row should be preselected 
### Steps to reproduce
1. open picking terminal window https://w101.metasfresh.com:8443/window/540345?page=1&viewId=540345-1f834f70cf424fe1a28ff278e791b464
2. select a line and press on pick
(note that it happens randomly. You can choose for e.g. Futterkarotten)

**Window:** 540345

![picking](https://user-images.githubusercontent.com/16001666/28070576-12c3bde4-6656-11e7-92c7-bd9738b5f849.png)

**Comment by teosarca** [comment]
might be related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/998

**Comment by metas-lc** [comment]
IT
checked and each time, the first line is selected OK
