### ISSUE TITLE
eMail Icon in Action Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1007]
### Type of issue
Feature request
### Current behavior
Currently, the eMail Icon in Action Menu is a chat symbol.
### Expected behavior
Pls swap with an eMail @ or an envelope icon.

![image](https://user-images.githubusercontent.com/13365687/28078970-f0e1a766-6666-11e7-9c0b-0a916f971379.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

OK: The e-mail icon is now an envelope.
