### ISSUE TITLE
Breadcrumb Navigation broken for Document List

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1008]
### Type of issue
Bug
### Current behavior
Currently, when pressing on Breadcrumb Document List Navigation entry, an empty menu opens instead of showing the default document List.
### Expected behavior
Shall show the default document List again.
### Steps to reproduce
Open window/143. Open Detail View of a sales order. Press "Sales Order" breadcrumb Navigation.

![image](https://user-images.githubusercontent.com/13365687/28080508-8b6447d0-666c-11e7-80ec-9cfbca21330c.png)

**Comment by teosarca** [comment]
more info about the issue is provided on #979

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


The navigation list is no longer empty. It is correctly filled with the windows that can be clicked.
