### ISSUE TITLE
Window Name missing in Action Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1009]
### Type of issue
Bug
### Current behavior
The Window Name is missing in Action menu
### Expected behavior
Shall be shown again.
### Steps to reproduce
Open any window and the action menu.

![image](https://user-images.githubusercontent.com/13365687/28104995-fe6defbc-66dd-11e7-8e26-df8936b32ff0.png)

**Comment by teosarca** [comment]
pls take the caption from layout, i.e.

![image](https://user-images.githubusercontent.com/1244701/28107651-4f4298f8-66f1-11e7-8b0f-984094c104e3.png)

**Comment by cadavre** [comment]
API provides now no information about favourite. We can display only window name but I believe it is not sufficient. @metas-mk ?

@wiadev do you want to take care about this one too?

**Comment by Dunkat** [comment]
just simple name of window added, but to show favourite info we will need to have children 
![image](https://user-images.githubusercontent.com/21196151/28115765-7f54236c-6706-11e7-8573-2e188d65ad88.png)

**Comment by Dunkat** [comment]
i think back to nodePathRequest should fix it 
![image](https://user-images.githubusercontent.com/21196151/28115830-ba3e600a-6706-11e7-8049-d55dbf4a0cae.png)

**Comment by teosarca** [comment]
yes, basically the name and favorite star shall be rendered as follows:

![image](https://user-images.githubusercontent.com/1244701/28266232-6c3116ba-6afc-11e7-96ec-83f10fd00107.png)

**Comment by metas-mk** [comment]
@Dunkat, @cadavre I see that you assigned robi to this issue, but kasia was assigned already last week. Does this mean that you cannot do this implementation?

**Comment by Dunkat** [comment]
Suere, I can do it. Just needed to know if star should be rendered and if it's ok if I change  breadcrumbRequest back to nodePathRequest.

**Comment by Dunkat** [comment]
So I will fix it

**Comment by metas-mk** [comment]
@Dunkat great, thx

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
checked multiple windows => name is there. Same for the fav star, which lso works OK
