### ISSUE TITLE
Widget for Product Attributes missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#101]
Widget for Product Attributes missing. Pls implement.
Example see Shipment Scedule Window 500221

![image](https://cloud.githubusercontent.com/assets/13365687/20485286/2649e3e6-affb-11e6-9aa6-79c8c4098fb8.png)

**Comment by damianprzygodzki** [comment]
We are waiting here for API.

**Comment by teosarca** [comment]
UPDATE: API was already provided.
