### ISSUE TITLE
Action menu Window Name

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1010]
### Type of issue
Bug
### Current behavior
The Action Menu window name is cut off at the bottom. You can see for characters like which need more space at the bottom, e.g. g, p, q, j, y
### Expected behavior
Shall have enough space to present also these characters properly.
### Steps to reproduce
Open window window/540170/ in german language (see image)

![image](https://user-images.githubusercontent.com/13365687/28106233-5cf25172-66e3-11e7-85a0-1fc4db5a28e6.png)

**Comment by teosarca** [comment]
rolled to w101

**Comment by metas-lc** [comment]
IT
Opened window window/540170/ in german language => name is visible and fits OK
