### ISSUE TITLE
Provide simple docker image for API devs

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#1013]
### Type of issue
Feature request
### Current behavior

* Currently when developing against metasfresh-webui-api, 
one needs to install npm and node locally, in order to run the frontend.

### Expected behavior

I would like to kave a simple docker image which i can fire up locally or on a nearby machine.
I would like to pass the URL of the API as environment varibles.
The way i'd start up that container mignt look like this:

```
docker run -d -e API_URL=<url-of-my-dev-workstation>-p3000:3000
--name tobis-dev-webui-frontend metasfresh-webui-dev
```
The benefit would be that i can simply start the frontend either on my workstation or maybe on a dedicated linux box somewhere in the office. At any rate, as a java developer, i would not have to install npm and node.js on my local machine.

**Comment by cadavre** [comment]
We provide config for frontend with `config.js` file located in root, next to `index.html`. Unfortunately frontend JavaScript *cannot* read OS environment variables, so you will need some sh script to launch it while building Docker image that will generate `config.js` file for you from env vars.

**Comment by cadavre** [comment]
@metas-ts pls check gh1013-webui branch for Docker-enabled version. I made it unified to work with localhost and Docker – both.

**Comment by metas-ts** [comment]
@cadavre thx, I'll try it out
