### ISSUE TITLE
Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1015]
### Type of issue
Bug
### Current behavior
Currently, when vertical Scrollbar in Handling Unit Editor Window an error occurs.
### Expected behavior
Shall not have an error.
### Steps to reproduce
Open window/540189. Use the vertical Scrollbar.

![image](https://user-images.githubusercontent.com/13365687/28154762-bc8bbab0-67ab-11e7-9fb5-952a4a3bb6c0.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. go to Handling Unit Editor Window, use scrollbars => OK nu erros
