### ISSUE TITLE
Combined Filter Functionality

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1021]
### Type of issue
Feature request
### Current behavior
Currently, if there are different Filters in a Window, only 1 Filter can be used at a time. Setting the first filter and then recording the 2nd leads to an "initialization2 of the 1st one.
### Expected behavior
Allow the user to set different Filter criteria and filter the data by the combination of Filters.

Example test case for multi Filter window: https://w101.metasfresh.com:8443/window/143

![image](https://user-images.githubusercontent.com/13365687/28164442-af8b0c20-67cf-11e7-9e86-d291432e325e.png)

**Comment by wiadev** [comment]
@metas-mk Right now, it's done exactly as stated in issue. However technically no problem to make even more than 2 filters. If you want this - please create a new issue.

**Comment by wiadev** [comment]
I found an issue, though.
![screenshot at aug 22 19-26-36](https://user-images.githubusercontent.com/18234060/29578578-fd5d6c08-876f-11e7-9c60-dddefbed63ca.png)

Unde *Partner and Date ordered*, we have another Date filter and both of Date filter from 1st and 2nd filter are pointing same field.

at this point, I think we should remove the date filter from *Partner and Date ordered*.
FYI, date filter from *Partner and Date ordered* are returning from the backend config. you should remove it over there if you want.

**Comment by wiadev** [comment]
In fact I wanted to propose to extend this feature ever further

### my proposal as following:

1. we can have ONE button initally - filter which shows dropdown with all possible filters (of course when filters are already applied and we're refreshing the page - it will restore all applied filters)
2. when user selects one filter - we're making this button blue (indicating it's of active state) and add another filter button (which will have dropdown list of possible filtering options, except of already applied filter). This repeats until we have any filters left
3. to remove any of pieces from filter - you just click on blue button and then click "Clear filter" to remove this part

### benefits:

1. No need in two component - Frequent filters and Non-frequent, which are quite overlapping by code. So we can reduce amount of involved code
2. We will be able to have more than 2 filters applied simultaneously

**Comment by teosarca** [comment]
@wiadev  about "Partner and date" filter.

Quick checked and for me looks ok. See the screenshot below. Remark the value and valueTo fields.

Can you point me more precisely where is the error?


![image](https://user-images.githubusercontent.com/1244701/29607969-7912fa1c-87fb-11e7-940a-ccbcfa0f384d.png)

**Comment by wiadev** [comment]
@teosarca no, there is no error but we have 2 date filters in both of 1st(Filter by Date) and 2nd (Filter: Partner and Date ordered)

since we are using combined filter I don't think we need another date filter under Partner and Date ordered from 2nd Filter.

**Comment by metas-mk** [comment]
@wiadev 
> @metas-mk Right now, it's done exactly as stated in issue. However technically no problem to make even more than 2 filters. If you want this - please create a new issue.

No that's not right. The issue describes the initialization of the first set filter after using another second filter.
What is meant with filter? Filter Buttons (see the screenshot and the red arrows showing to them)

**Comment by teosarca** [comment]
> no, there is no error but we have 2 date filters in both of 1st(Filter by Date) and 2nd (Filter: Partner and Date ordered)
> 
> since we are using combined filter I don't think we need another date filter under Partner and Date ordered from 2nd Filter.

@wiadev ahhh, now i got it.
Yes, from a logical point of view, you are right but the thing is that those filters can be easily defined by a system admin. So in this case that filter is more a test case used to validate frontend.

**Comment by wiadev** [comment]
@teosarca this is already on branch:master. should I put the label and assign back to you?

**Comment by teosarca** [comment]
@wiadev  thx for reminder, just did it

**Comment by metas-lc** [comment]
IT
used Date filter and a filter from default (e.g. bpartner) and worked fine, together. OK
