### ISSUE TITLE
grid: Get rid of double scrollbar

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1026]
### Steps to reproduce
open https://w101.metasfresh.com:8443/window/540345 and see

![image](https://user-images.githubusercontent.com/1244701/28213111-551561c6-68ad-11e7-8126-d7bba7aea929.png)

**Comment by cadavre** [comment]
Attaching screenshots from where this difference comes from:

![zrzut_ekranu_2017-07-18_o_19_44_23](https://user-images.githubusercontent.com/461796/28331544-d2c8c1a2-6bf1-11e7-8920-104254ec8900.jpg)

![zrzut_ekranu_2017-07-18_o_19_44_35](https://user-images.githubusercontent.com/461796/28331549-d724921c-6bf1-11e7-900f-5f263671f214.jpg)

![zrzut_ekranu_2017-07-18_o_19_44_48](https://user-images.githubusercontent.com/461796/28331559-db403798-6bf1-11e7-8b55-ad23c234541f.jpg)

**Comment by metas-lc** [comment]
IT
there is only 1 scroll (the one from right) OK
