### ISSUE TITLE
Tooltip when hovering GridView Header

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1028]
### Type of issue
Feature request
### Current behavior
Currently, sometimes the Header Names are too long for the width of the columns in GridView and the User then can miss some important information.
### Expected behavior
When Hovering over the Header Column/ Name, show a tooltip with the complete Name, w/ similar behavior and look and feel like when hovering over field labels in advanced edit.

![image](https://user-images.githubusercontent.com/13365687/28217857-f7e85558-68b6-11e7-9e3e-12a034a76db6.png)

![image](https://user-images.githubusercontent.com/13365687/28217876-0578656e-68b7-11e7-925c-b2cee6678569.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

 Hovering over fields in gridview works as required. The tooltip is displayed both for the column headers in the main view and in the included tabs.
