### ISSUE TITLE
keyboard shortcut and tooltip for button in filters

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1029]
### Type of issue
Feature request

### Current behavior
there is no shortcut/tooltip in Apply button from Filters

### Expected behavior
Apply button from Filters should have ctrl+enter shortcut
also add a tooltip when it's hovered

### Steps to reproduce
go to a window with filters. E.g. Purchase order (181). Press on filter, default. See Apply button

**Window:** 181

**Comment by Dunkat** [comment]
translation for clear filter added:

``{"window.clearFilter.caption":"Clear filter"}``

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. go to a window which has filters, e.g. Billing candidates (540092)
2. select the filters, default. Hover over apply button
=> tooltip appears with ctrl+enter info OK
3. add a filter (e.g. business partner)
4. press ctrl+enter 
=> the filter is applied OK
