### ISSUE TITLE
Margin between primary background and Tabs too narrow

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#103]
Margin between primary background and Tabs too narrow
- Please reduce the margin beneath last primary field basement. goes to deep.

![image](https://cloud.githubusercontent.com/assets/13365687/20486971/f7e6d2a0-b001-11e6-90be-199046903ae5.png)

**Comment by damianprzygodzki** [comment]
To make sure if i understand, should i add a margin to Tab Wrapper (not reduce)?

And second question, could you provide window type for that screen? I can't reproduce because every window has 2rem margin above tab wrapper (even if the second column is empty).

**Comment by metas-mk** [comment]
@damianprzygodzki thanks for the info. checked in current rollout. is fixed now.
![image](https://cloud.githubusercontent.com/assets/13365687/20560523/17dbf2ba-b17a-11e6-9959-d7158668db61.png)
