### ISSUE TITLE
Directly display quick actions for the first row of a modal window

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1030]
### Type of issue
Bug
### Current behavior
* open picking window: https://w101.metasfresh.com:8443/window/540345
* select a line and press the "Pick" quick actions button
=> the picking modal is opened, the first line is selected, but the quick actions are not displayed for it:

![image](https://user-images.githubusercontent.com/16001442/28217974-c6087992-68bf-11e7-9adb-80a2fb46b967.png)

* For being able to access them, you have to click on the selected line first: 
![image](https://user-images.githubusercontent.com/16001442/28218012-e4e8bbec-68bf-11e7-9232-f81c226556cb.png)

### Expected behavior
* The quick actions for the selected line shall be available when the modal opens.
### Steps to reproduce
* Described above

**Comment by cadavre** [comment]
Fixed, but there's one more to follow: #1037 .

**Comment by metas-lc** [comment]
IT
1. opened picking window: https://w101.metasfresh.com:8443/window/540345
2. selected pick button => the picking modal is opened, with both views, the first line is selected, quick actions are displayed
