### ISSUE TITLE
Autoselect when doubleclick on included Tab Row Field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1031]
### Type of issue
Feature request
### Current behavior
When doubleclicking in Included Tab Grid on Field, then the cursor appears and the user can change the content in edit mode. To change the content completely the user must delete the content first or select completely to then overwrite.
### Expected behavior
When doubleclicking in such a field so that cursor appears, automatically select the whole content so the user can directly overwrite.

![image](https://user-images.githubusercontent.com/13365687/28218224-2b18b8f4-68b8-11e7-98ea-be77dbbf9d01.png)

**Comment by metas-mk** [comment]
Current Solution that works is doing a triple-click on the field you want to change. Waiting for Feedback from users first, if that solution is also fine.

**Comment by metas-mk** [comment]
Got feedback. Users want only double click as describes in requirement.

**Comment by metas-lc** [comment]
IT
double click works for fields in subtab to become editable. Also the content is selected OK
