### ISSUE TITLE
Quickaction button is displayed even if no selection is made

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#1037]
### Type of issue
Bug
### Current behavior
No selection is made in gridview, but quickaction button is visible.

### Expected behavior

@metas-mk shall we select 1st row of gridview by default (and thus display quickactions button) or hide quickactions button untill some selection is made?

### Steps to reproduce
Go to `/window/540345`. Even if no row is selected – quickactions button is visible:

<img width="1224" alt="zrzut ekranu 2017-07-17 o 14 52 31" src="https://user-images.githubusercontent.com/461796/28268732-a096e33c-6aff-11e7-88e7-427a813629c0.png">

**Comment by cadavre** [comment]
To handle this: backend shall not provide default quickactions which require selection.

**Comment by teosarca** [comment]
update: shall be OK now... the Pick action is there but disabled if there are no rows selected.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

If a window opens with no selected line, the actions are disabled until a line is selected: OK

Note that these tasks are also related: 
	
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1027
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1006

**Comment by metas-ts** [comment]
just verifies that the fix is already in the `release` branch
