### ISSUE TITLE
Flickering effect in Picking Terminal

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1038]
### Type of issue
Feature request
### Current behavior
Currently, when in window/540345, modal overlay "Picking", then switching through the product lines on the left side leads to a flickering effect on the right side.
### Expected behavior
Shall not flicker.

![image](https://user-images.githubusercontent.com/13365687/28268832-0cb3cc60-6b00-11e7-8a91-a0b8eaf92070.png)

**Comment by metas-lc** [comment]
IT
go to picking, select a product and use pick. Navigate on lines on left side => right side doesn't flicker. Only refreshes OK
