### ISSUE TITLE
Readonly field Contact looks editable

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1040]
### Type of issue
Bug 
### Current behavior
There is at least one window where the Contact looks editable in the included tab even if the entry is readonly.
### Expected behavior
I should be not able to edit anything in a readonly entry
### Steps to reproduce
* Open the window Outbound documents
* Go to the included tab (Log)
* Advance edit
* NOK: The Contact looks editable:
![image](https://user-images.githubusercontent.com/16001442/28273193-51cb231e-6b16-11e7-987f-be49444b9bf4.png)

* NOK: I can click on it, and some shadowed eligible entries are displayed

![image](https://user-images.githubusercontent.com/16001442/28273232-71df3e92-6b16-11e7-8f88-45aabf5ddee9.png)

* I can see an error if I select one of them

![image](https://user-images.githubusercontent.com/16001442/28273248-84ba6604-6b16-11e7-868e-9e08151e0b70.png)

* Afterwards it is no longer editable:

![image](https://user-images.githubusercontent.com/16001442/28273274-96990722-6b16-11e7-9a9f-d97e368b80e6.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

The Contact field is not completelyreadonly in the window Document Outbound.

I did  some regression tests on some other windows too. The readonly fields cannot be edited.
