### ISSUE TITLE
included tab: when zoom into the new window opens with error

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1041]
### Type of issue
Bug

### Steps to reproduce
* From price list: https://w101.metasfresh.com:8443/window/540321/2008396
* right click on second included row and zoom into Product prices:
![image](https://user-images.githubusercontent.com/1244701/28286017-75241784-6b3f-11e7-84ff-0c37e67a2024.png)

* and you will get:
![image](https://user-images.githubusercontent.com/1244701/28286052-8fd622d4-6b3f-11e7-858b-827c061c4f91.png)

### Expected behavior
I was checking it and the problem is refType and refId parameters from the query:
```
https://w101.metasfresh.com:8443/window/540325?refType=540321&refId=2008396
```

Problem is that in our case we shall reference the included row and not the header document.
That's why the backend cannot find a connection between those.

I think you shall also introduce refTabId and refRowId as parameters (for frontend),
and when creating the view please also provide the tabId and rowIds array, e.g.
```json
{
"documentType":"540325",
"viewType":"grid",

"referencing":{
  "documentType":"540321",
  "documentId":"2008396",
  "tabId":"1",
  "rowIds":["2002141"]
},
"filters":null
}
```
(remark the tabId and rowIds properties)
The support for those properties was introduced by https://github.com/metasfresh/metasfresh-webui-api/issues/506
Endpoint: http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/createViewUsingPOST

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
tested on w101 only
Product Prices opens with no errors OK
(to check: why i don't have this zoom in everywhere)

**Comment by teosarca** [comment]
@metas-lc  found out why you cannot zoom from price list version (PLV) to product prices.
It's because the M_ProductPrice.M_PriceList_Version_ID column has AllowZoomTo=N.

query used to find out:
```sql
select t.TableName, c.ColumnName
from AD_Column c
inner join AD_Table t on (t.AD_Table_ID=c.AD_Table_ID)
where AllowZoomTo='Y'
```

**Comment by metas-lc** [comment]
IT
checked again. Still not visible on mf15

**Comment by teosarca** [comment]
check again and it seems to work on w101:
![image](https://user-images.githubusercontent.com/1244701/30322430-1ce3df96-97c2-11e7-8891-eccf041a7123.png)

**Comment by teosarca** [comment]
update: found the issue. The AD_Table.AD_Window_ID was wrong on mf15. Just on w101 was correct.

The AD_Table.AD_Window_ID shall be 540325;"Produkt Preise".

Query to check
```sql
select AD_Window_ID from AD_Table where TableName='M_ProductPrice'
```

**Comment by metas-lc** [comment]
IT
window id is 540325 OK
still not visible in zoom in

**Comment by metas-lc** [comment]
IT
repeated the testcase above => works fine: you can zoom in 
OK
