### ISSUE TITLE
Double instantiation of DocList component after full page reload

### ISSUE THREAD

**Issue by wiadev** [metasfresh/metasfresh-webui-frontend#1044]
### Type of issue
Bug 

### Current behavior
Seems we found important issue (not a blocker right now, though).

### Steps to reproduce
1. Open dev tools
2. Navigate to window/260
3. You'll be immediately redirected to window/260?viewId=260-bcdb0d6dd76547b1b9dc46bbbb3bac18&page=1
4. In Network tab you'll see many requests doubled (please take into account that some requests are OPTIONS method, which doesn't matter to us in scope of this issue). In particular we can see doubled following requests - messsages (retrive locale strings), /documentView/260/layout, documentView/260

![screen_shot](https://user-images.githubusercontent.com/18234060/28304945-d12edab0-6bd4-11e7-84b9-959db19905e6.png)

Probably root cause for this - incorrect implementation in router.

Need to optimize router to properly handle such cases and avoid re-creating components during internal redirects, which shouldn't cause actual data reload.

**Comment by teosarca** [comment]
Hi @wiadev 
I saw that u added branch:master label but there is no commit related to this task. Wondering if u forgot to push?

**Comment by wiadev** [comment]
@teosarca no, what I meant by is that the issues is available in branch:master.

**Comment by teosarca** [comment]
@wiadev  understand. In that case i will remove the "branch:master" and move it back to TODO.

We use the "branch:master" flag those tasks which were integrated.
The label is assigned first time when it's integrated and never removed after even if the IT was failed and the dev needs to re-work it.
In this way we quickly know what's integrated in master.
