### ISSUE TITLE
POST .../documentView/{windowId} is called twice when opening a view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1048]
### Type of issue
Bug

### Steps to reproduce
* open a view, e.g. sales order: https://w101.metasfresh.com:8443/window/143
* remark that the "POST documentView/{windowId}" is called twice => so the view is called twice

### Expected behavior
the view shall be created only once

![image](https://user-images.githubusercontent.com/1244701/28310781-32f9f0aa-6bb6-11e7-9f88-f5655ee157b0.png)

**Comment by Dunkat** [comment]
it seems like react-router-redux problem
https://github.com/reactjs/react-router-redux/issues/197

**Comment by teosarca** [comment]
shall we upgrade the react-router-redux to latest stable version?

**Comment by Dunkat** [comment]
we already using the latest version. I made research and found reason of this behavior.

**Comment by metas-lc** [comment]
IT
checked several windows, including 143. View is called once OK
