### ISSUE TITLE
Cut-Off Header names

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1051]
### Type of issue
Feature request
### Current behavior
Currently, it happens in header names that the columns are sometimes too narrow so be shown completely and then are cut off, which looks untidy.
### Expected behavior
In case a header label does not fit properly, show '...' instead. Now w/ the new Mouse Over/ Hover and Full Label tooltip Functionality the user can still see the whole name if needed.

Thanks @metas-rc for the idea/ trigger.

![image](https://user-images.githubusercontent.com/13365687/28323406-fa22b3ac-6bd8-11e7-93f2-94d44b41a852.png)

**Comment by Dunkat** [comment]
I agree with '...' columns will be looks tidy, but it can be annoying for users because always needs hover label to see name. Now user can see part of title and know what there is.

**Comment by teosarca** [comment]
@Dunkat  yes, but i think those are complementary, i.e.
1. in case the column caption's is shorten by "..." when hovering user will have the opportunity to see the full name (which sometimes it's important when looking at captions which all start with the same text)
2. i agree that we shall improve our column captions and use abbreviations or something to make the names shorter but obvious.

**Comment by metas-mk** [comment]
I had some interesting talks about this topic in the last weeks w/ different users. Most of them said "If the name does not fit into the header but I can hover it and see completely then great! Perhaps I as a user will have to hover a few times before knowing the field content. But after a few times, I will know whats in there and don't have to hover anymore".
--> That's the reason why I think that '...' is more beneficially than 2 additional characters.
Additionally, I agree that we can find some shorter header names, but have to find a balance using the fields in GridView AND detailed view (without using different names!)

**Comment by teosarca** [comment]
IMHO this task can be started.

**Comment by metas-mk** [comment]
Tested. 
1. ellipses are shown for header names when too long. OK
2. Order by triangle is not shown anymore. NOK
3. Now w/ elipses the gap between end of first columnname to beginning of next column name is too large. Please Reduce. The reductions should also allow more Names to be shown w/o ellipses. NOK
@Dunkat can u please take care about 2 and 3.

![image](https://user-images.githubusercontent.com/13365687/28622198-f8b9756e-7213-11e7-8d0e-1da2ddbba2aa.png)

**Comment by cadavre** [comment]
Ad. 2.) As we discussed on Skype – this is version without arrows ("to see how it looks"). Adding them will cut off more text which makes it completely unreadable. :/ Your decision what to do.
Ad. 3.) It is a cell margin, I believe that reducing it will drastically decrease readability of data. What we can thing about is making margins smaller in table header row. Wdyt?

**Comment by cadavre** [comment]
Update: changed `padding-right` to smaller.

**Comment by metasnw** [comment]
results from IT:
OK: header in windows 
NOK: headers in tabs are not working as requested
Creating follow up: #1117
