### ISSUE TITLE
Breadcrumb of "Sales Opportunities"  board is incorrect

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1052]
### Type of issue
* Bug
### Current behavior
* When opening the Sales Opportunities board, the breadcrumb in inspection is not correct

![image](https://user-images.githubusercontent.com/16001442/28324442-157646ea-6be4-11e7-9813-7e28369e1593.png)

* It contains the word "window"  instead of "board" 

Request URL is: 

https://w101.metasfresh.com:8443/rest/api/menu/elementPath?type=window&elementId=540000&inclusive=true

instead of 

Request URL:https://w101.metasfresh.com:8443/rest/api/menu/elementPath?type=board&elementId=540000&inclusive=true
### Expected behavior

* The endpoint shall be respected.

### Steps to reproduce
* As above

**Comment by metas-mk** [comment]
Additional Info:
![image](https://user-images.githubusercontent.com/13365687/28354315-bf6ee730-6c5f-11e7-8a18-ec23dbdf13a2.png)

**Comment by metas-lc** [comment]
IT
checked inspection. Type = board OK
