### ISSUE TITLE
Locale viewing and editing in User Interface

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1060]
### Type of issue
Feature request
### Current behavior
Currently, switching the Locale in Avatar does not affect the formatting in User Interface. 
For example in amount widget:
de_DE: 1.000,00 (tsd seperator '.' decimal sign ','
de_CH: 1'000.00(tsd seperator ''' decimal sign '.' 
en_US: 1,000.00(tsd seperator ',' decimal sign '.' 
and so on.
### Expected behavior
The locale set in Avatar shall respect the locale in User Interface too, so viewing and editing in locale is allowed and possible.

**Comment by metas-mk** [comment]
Belongs to https://github.com/metasfresh/metasfresh/issues/2025

**Comment by wiadev** [comment]
we format amount and costprice fields only
if you need more types - let me know
currently we have 4 locales hard-coded - de_DE, de_CH, nl_NL, nl_BE
formats taken from https://lh.2xlibre.net/locale/de_CH/

**Comment by metas-lc** [comment]
IT
created a purchase order and added a big qty and price. Changed language and checked line net amt 
de_DE
3.273,60
de_CH
3'273.60
en_US
3,273.60

OK
