### ISSUE TITLE
Larger Avatar Menu Photo

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1061]
### Type of issue
Feature request
### Current behavior
Currently, the Avatar Photo is shown too. Especially for users working in rough environments that want work w/ more then 1 user on 1 hardware want to recognize via Avatar if they are seeing their environment.
### Expected behavior
Make the Avatar pictogram larger (see proposal Screenshot). WDYT?

![image](https://user-images.githubusercontent.com/13365687/28410175-1d414eec-6d3d-11e7-9936-02f234d24fc6.png)

**Comment by metas-lc** [comment]
IT
avatar is as big as in picture above OK
