### ISSUE TITLE
Avatar Foto stretches when not Square

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1062]
### Type of issue
Bug
### Current behavior
When uploading a Photo/ Taking a Photo from Camera for Avatar, and the dimensions are not square, then the Avatar Pictogram is stretched into Circle/ Square Format.
### Expected behavior
Shall not be stretched.

**Comment by metas-lc** [comment]
IT
used a long picture (not square) => picture didn't stretch. Only a part of it was shown OK
