### ISSUE TITLE
moving 1 TU from one LU to another

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1064]
### Type of issue
Bug
### Current behavior
when you are moving 1 TU from one LU to another the modal does not refresh
### Expected behavior
modal should refresh
### Steps to reproduce
1. go to receipt candidates 
https://w101.metasfresh.com:8443/window/540196?viewId=540196-0bf5581daad64a82b36a29a16b770efb&page=1
and select a line, open it with Receive HUs: qty TU 4, qty LU 2
2. select a TU line and press transform
3. use move TU on another existing LU, set qty 1, ok
=> nothing happens NOK (you should see the TU moved)
4. use transform again, for the same line, but , for e.g. move TU to a new LU, qty 1
=> the TU is move on a new LU, but you can also see that the TU from step 3 is moved to the other LU OK

**Comment by teosarca** [comment]
backend issue: https://github.com/metasfresh/metasfresh-webui-api/issues/516
