### ISSUE TITLE
Window title wrong for windows in deeper menu hierarchy

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1065]
### Type of issue
Bug
### Current behavior
Currently, when opening windows in the 2nd folder hierarchy, the window title shows the folder name instead of the window name.
### Expected behavior
Shall show the window name.

![image](https://user-images.githubusercontent.com/13365687/28491203-1fdbf948-6eed-11e7-80b8-157db3510408.png)

**Comment by metas-lc** [comment]
IT
checked several windows, in 1st and 2nd folder hierarchy => windows title shows windows name OK
