### ISSUE TITLE
board: when adding a new card, the card does not vanish from new cards view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1066]
### Type of issue
Bug

### Steps to reproduce
* open a board, e.g. https://w101.metasfresh.com:8443/board/540000
* click "Add new" and drag a card to a lane

=> card added to lane => OK
=> card didn't vanish from "newCardsView" => NOK
That's happening because the the websocket invalidation event for that view was not handled.

IMPORTANT: Also please make sure you subscribe to view's websocket endpoint when the "Add new" is displayed and you unsubscribe from websocket endpoint when the view is no longer displayed.

Btw, the websocket endpoint is "/view/{viewId}"... but it shall be somewhere in the frontend code.

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/511.

**Comment by metas-lc** [comment]
IT
open board, drag card  => card vanished from "newCardsView" OK
