### ISSUE TITLE
board: add new: don't show the loading icon after data is loaded

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1067]
### Type of issue
Bug

### Current behavior
When the "Add new" list is short or empty a rotating gear icon is displayed and looks ugly.
![image](https://user-images.githubusercontent.com/1244701/28494734-e64fd8d6-6f3f-11e7-9421-4e6ad75ed163.png)

### Expected behavior
The loading icon (rotating gear) shall not be displayed after data was loaded.

### Steps to reproduce
Atm https://w101.metasfresh.com:8443/board/540000 has a lot of data but you can "mock" it programatically and limit the number of returned cards to couple of cards or even no cards.

**Comment by metas-lc** [comment]
IT
opened an "add new" empty list. Gear is not there and you have the following message "There are no detail rows. You can create them in this window." OK
