### ISSUE TITLE
board: when there are no new cards show the empty result text/hint

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1068]
### Type of issue
Bug

### Expected behavior
![image](https://user-images.githubusercontent.com/1244701/28494765-d2c04476-6f40-11e7-9bc2-d4c7de853cff.png)

The empty result text/hint can be found in layout: http://w101.metasfresh.com:8081/swagger-ui.html#!/board-rest-controller/getNewCardsViewLayoutUsingGET

### Steps to reproduce
Because https://w101.metasfresh.com:8443/board/540000 has a lot of data, pls try to mock it.
If not possible pls let me know.

**Comment by metas-lc** [comment]
IT 
empty list:
"There are no detail rows. You can create them in this window."
