### ISSUE TITLE
Fix frontend  memory leaks

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1071]
### Steps to reproduce
It seems the frontend consumes quite a lot of memory (might be some memory leaks?).
My test case was:
* open a window, e.g. receipt schedules https://w101.metasfresh.com:8443/window/540196
* open chrome task manager (in  windows that's shift-ESC)
* refresh the frontend page couple of times (e.g. 10 times)
* observe how the memory consumption is rising

### Expected behavior
Identify the fix the memory leaks.

Thanks @wiadev for bringing this up.

**Comment by wiadev** [comment]
Yes, memory does leaking in application.

Possible places (not limited to):
1. Trace Redux reducers for optimal state updates
2. Check for components referring when not needed to large objects (and arrays) don't allowing to be freed by garbage collector
3. Make sure to optimize re-creating of components when not needed

Major memory wasters:
1. DocumentList
2. Forms

**Comment by wiadev** [comment]
please keep in mind that this is needed, but risky change

**Comment by wiadev** [comment]
this story will result large impact on many areas on site. So needs to be carefully checked both on dev and QA ends. QA phase might take significant time.

**Comment by cadavre** [comment]
Tested on Chrome, macOS.

Page with `/window/540196` takes regularly ~270MB.
This page (GH issue) takes ~210MB in comparison.

After refreshing page once or 20x it grows to ~310MB but never more.

Might be OS GC issue?

**Comment by wiadev** [comment]
Try to switch between forms and document lists for example.
Not refreshing single page.
Otherwise figures aren't quite correct

**Comment by cadavre** [comment]
Made around 15 switches between one list and different document:
![zrzut ekranu 2017-07-28 o 12 35 12](https://user-images.githubusercontent.com/461796/28713912-63414f32-7391-11e7-9a5b-266f56c70ce8.png)

In task manager never more than 360MB. On chart you can see that memory levels are on almost-initial level at the end.

Could you provide yours chart for comparison?

**Comment by metas-lc** [comment]
IT
tested the case above -> works fine
