### ISSUE TITLE
Bug in Advanced edit of Purchase order

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1073]
### Type of issue
Bug 
### Current behavior
Sometimes the Advanced edit cannot be opened for a purchase order. I get an error in the console: 

![image](https://user-images.githubusercontent.com/16001442/28532936-0baeddba-70a4-11e7-9012-7b72940b8b57.png)

### Expected behavior
* Please check why it's not working
### Steps to reproduce
* Open purchase order https://w101.metasfresh.com:8443/window/181/1005766

**Window:** enter window ID or Navigation menu step-by-step.
181
**Entity:** enter document ID or steps to reproduce environment.
1005766
/or/

**Link:** link to w101.
 https://w101.metasfresh.com:8443/window/181/1005766

**Comment by teosarca** [comment]
Btw, if you think that (at least) a part of the problem is on backend side, pls let me know about the details.

**Comment by Dunkat** [comment]
this is because field from layout missing in data

![image](https://user-images.githubusercontent.com/21196151/28560147-d25ab0e0-7119-11e7-95c8-f49ff5b0fc36.png)


but I guess it's not a backend issue, I will fix it to not show error

**Comment by Dunkat** [comment]
but I see now backend provide "DropShip_Location_ID" and it seems work

**Comment by metas-lc** [comment]
IT
checked the link above and also created new order => no errors when using advanced edit. OK
