### ISSUE TITLE
Sitemap Navigation [arrow-up] not working

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1077]
### Type of issue
Bug
### Current behavior
Currently, in filtered Sitemap Navigation the [arrow-up] does not work anymore.
### Expected behavior
Filter Sitemap. [arrow-down], then try [arrow-up].
### Steps to reproduce
Shall work.

![image](https://user-images.githubusercontent.com/13365687/28564912-d6bb70b4-712a-11e7-8f7a-f037ec5316db.png)

**Comment by metas-lc** [comment]
IT
1. go to sitemap, filter, use arrows (up and down) to navigate => works OK
2. go to sitemap, don't filter, use arrows (up and down) to navigate => works OK
