### ISSUE TITLE
Wrong quickActions call when opening HU editor

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1078]
### Type of issue
Bug

### Current behavior
When the HU editor is opened from receipt candidate, the frontend performs 2 quickActions calls:
1. one call which is using the viewId=<HU's viewId> but selectedIds=<receipt candidate's id> => the wrong one
2. one call which is using viewId=<HU's viewId> and selectedIds=<current selected row> => the CORRECT one

### Expected behavior
the quickActions call (1) shall not be performed because:
* it's wrong anyways (the viewId and selectedIds not matching)
* not needed
* sometimes the result of that wrong call is displayed in the quickActions button

### Steps to reproduce
* open receipt schedules, e.g. https://w101.metasfresh.com:8443/window/540196
* select a line where u can receive (i.e. the quick action button will show something like "4 G1 x 10Kg"
* click on it => the HU editor modal is displayed, the first line is selected but the quickActions are wrong.
![image](https://user-images.githubusercontent.com/1244701/28523636-f9e7986a-7085-11e7-9b24-2401b13f3bd3.png)

**Comment by wiadev** [comment]
FYI, the viewId is wrong as well.
![screenshot_1](https://user-images.githubusercontent.com/18234060/28571948-0d63686a-7180-11e7-9240-a734b07a749b.png)

**Comment by wiadev** [comment]
During fixing story I found that we don't destroy modals when they closed.

Apart of leading to memory consumption it also didn't allowed to re-open the modal in the same view. Not all, but modals with documentList only.

Obviously they're quite heavy leading to quick memory waste.

=> needs to be fixed in #1071

**Comment by metas-lc** [comment]
IT
repeated the testcase above and checked the quickactions selectedIDs => the id is the one from HU OK
