### ISSUE TITLE
Change print endpoint to more user friendly

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#108]
Change print endpoint:
`metasfreshhost.com/rest/api/window/documentPrint?type=123&id=1233333`
to something like
`metasfreshhost.com/documentPrint?type=123&id=1233333`

/or/

Add ProxyPass to your server configuration for pretty `metasfreshhost.com/print/123-1233333` or something.

**Comment by teosarca** [comment]
i would not like the ProxyPass approach because that means the logic will be in 2 places:
* server/proxy configuration
* webui frontend (or backend, depends on how we are doing it) shall also know about this 

I would prefer to have everything in one place.

**Comment by teosarca** [comment]
I am thinking to have the endpoint something like:
/api/window/143/1000001/print/nice_file_name.pdf

In this way, when user will try to save it, it will automatically get a nice file name and not "documentPrint.pdf" or similar which is totally annoying when you have documentPrint.pdf, documentPrint(1).pdf ... documentPrint(99).pdf in your downloads folder.


wdyt?

**Comment by cadavre** [comment]
I was about to write it. :) `.pdf` is +100!

**Comment by teosarca** [comment]
UPDATE: on next rollout you will have the new print endpoint, i.e.
` /window/{type}/{id}/print/{filename}`

you will be able to call it like: 
http://w101.metasfresh.com:8080/rest/api/window/143/1000815/print/my_report.pdf

now, the only thing that u will have to solve it is the "filename".
The backend does not care about the filename but the filename would be useful for browser, when user press Save.

So, for filename, i would suggest to build it something like: <WindowName>_<DocumentNo>.pdf
wdyt?

**Comment by cadavre** [comment]
Browsers are in most cases figuring out filenames by itself. You can always use `filename` attribute for header:
`Content-Disposition: inline; filename="filename.jpg"`
We cannot do anything else about it.

**Comment by cadavre** [comment]
@teosarca Was this deployed? If yes – what is the usage?
