### ISSUE TITLE
Sitemap and Menu Navigation refactor

### ISSUE THREAD

**Issue by Dunkat** [metasfresh/metasfresh-webui-frontend#1081]
### Type of issue
Feature request
### Current behavior
Now Sitemap and Menu Navigation are separate component so navigation for them also works separate/different
### Expected behavior
Make Sitemap and Menu Navigation as component with one/ the same navigation because structure of menu items are identically

**Comment by metas-mk** [comment]
Seems to be a duplicate https://github.com/metasfresh/metasfresh-webui-frontend/issues/930 which is closed.

**Comment by teosarca** [comment]
we can do this when somebody will have to touch the menu again.
