### ISSUE TITLE
Handle websocket document stale event

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1084]
### Type of issue
Feature request

### Current behavior / Expected behavior
Atm frontend reacts to websocket events which are about stale tabs.
It was implemented in https://github.com/metasfresh/metasfresh-webui-frontend/issues/795.

In that message, now we introduced another property called "stale" (boolean).
If that property is set and it's true, the fontend shall refresh that document (only the header and not the included tabs, if that's not mentioned in the event).

So, the JSON which is sent via websocket might look something like:
```
{
	"windowId":540354
	"id":2156425
	"stale":true
}
```

### Steps to reproduce
* login with user "it" (important)
* open following "Businesspartner B2C": https://w101.metasfresh.com:8443/window/540354/2156732
* Actions -> Create request:
![image](https://user-images.githubusercontent.com/1244701/28619557-9b6bfc80-7211-11e7-8391-402c0e7959b8.png)

* Fill the request (see screenshot, those highlight are important)
![image](https://user-images.githubusercontent.com/1244701/28619609-d2109e12-7211-11e7-9a7f-8aadb775bf24.png)

When the request is saved (it should be already) an websocket event will be send to refresh the bpartner.
After refreshing the BPartner, you will remark that the date you filled in request is now in BPartner:
![image](https://user-images.githubusercontent.com/1244701/28619639-011a9726-7212-11e7-86c3-b675a0a539d5.png)

----
required for https://github.com/metasfresh/metasfresh/issues/2066

**Comment by Dunkat** [comment]
@teosarca could you provide password fot user "it". Needed for

> login with user "it" (important)

**Comment by teosarca** [comment]
@Dunkat  provided privately

**Comment by metas-lc** [comment]
IT
1. Businesspartner B2C -> actions -> create request
2. set summary and date, ok
=> bpartner was directly updated with that date (didn't have to refresh) OK
