### ISSUE TITLE
Avatar Tooltip opens and stays open after selecting Avatar Settings

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1089]
### Type of issue
Bug
### Current behavior
When selecting Avatar and Settings, then the tooltip opens and stays open although the mouse is not hovering above the avatar.
### Expected behavior
Shall only show when hovering after defined and known time interval.

![image](https://user-images.githubusercontent.com/13365687/28636594-ee965c48-723e-11e7-9d0f-237006207b4d.png)

**Comment by metasnw** [comment]
IT ok.
