### ISSUE TITLE
Sometimes wrong actions and references are displayed in menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#109]
Test case:
* open a document (e.g. a particular sales order)
* press the menu to trigger the document actions & references loading
* go to another document or grid view
* press the menu to see the actions and references
* for a while you will see the old ones (from previous document)

Usually this is obvious on slow connections where the document actions and references endpoints have delays.

How it shall be: when user presses Menu button
* clear document actions and references
* display an indicator (text or some other rotating shit) that the documents are currently loading
* populate when you got them

**Comment by damianprzygodzki** [comment]
@cadavre 
TODO: indicator for document actions & referenced documents in subheader

**Comment by teosarca** [comment]
And btw, i think we shall have exactly the same approach on ALL OTHER things which are lazy/just in time loaded.

**Comment by damianprzygodzki** [comment]
Definetely we should provide one the same loader for all of lazy elements.

**Comment by teosarca** [comment]
About lazy loading, i've created a new issue to gather ideas: https://github.com/metasfresh/metasfresh-webui-frontend/issues/130

**Comment by teosarca** [comment]
Might be related with https://github.com/metasfresh/metasfresh-webui-frontend/issues/130
