### ISSUE TITLE
Error on document websocket event

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1094]
### Type of issue
Bug

### Steps to reproduce
(NOTE: currently not on master!!!)

* open the bpartner B2C window: https://w101.metasfresh.com:8443/window/540354
* attach a document (i.e. drag it from your computer and drop it on that window)
* the document is attached => OK
* but the backend also sends a websocket notification to refresh one on document's tab which fails

![image](https://user-images.githubusercontent.com/1244701/28715393-63cc2e36-73a0-11e7-9f8a-e70dc01ead6a.png)

Required for https://github.com/metasfresh/metasfresh/issues/2074

**Comment by metas-rc** [comment]
Results of IT

* When attaching a file to an entry (e.g. to a B2C Businesspartner)  the document is attached without any errr in inspection.  The websocket notification is no longer sent by the backend
