### ISSUE TITLE
Show progress when uploading big files

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1097]
### Type of issue
Feature request

### Current behavior
progress is not displayed

![image](https://user-images.githubusercontent.com/16079655/28724581-d638df36-73ba-11e7-8781-e3dc52196431.png)

### Expected behavior
show constant progress bar while uploading files

### Steps to reproduce
1. have a file with 10 MB and upload it to e.g. partner window
1. do other stuff while uploading it

**Comment by metas-lc** [comment]
IT
1. go to bpartner window and upload a big file
=> there is a constant progress bar while uploading files
2. modify some data
=> progress bar is still there, loading
3. add a new address 
=> progress bar is above the modal, covering the OK button (have to see if that's wanted. You can close the modal with ctrl+enter)

**Comment by metasnw** [comment]
its ok how it is now. if we want to address modals we need to create a new issue
