### ISSUE TITLE
Cant select last entry in dropdown list 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1098]
### Type of issue
Bug 

### Current behavior
if you click on the last entry the entry above gets selected

### Expected behavior
clicked entry is selected

### Steps to reproduce
1. open https://w101.metasfresh.com:8443/window/123/2156481
1. go to tab Customer
1. click into field Price System 
1. try to scroll down and select the last entry in the list
1. NOK: with mouse not possible:

![image](https://user-images.githubusercontent.com/16079655/28745186-10fa1974-7473-11e7-95f9-d774483583f1.png)

**Comment by metasnw** [comment]
tested on w101 and behaviour is still the same

**Comment by metasnw** [comment]
now you can select the last entry but you still can not scroll down to it and have to select it blindly.
![image](https://user-images.githubusercontent.com/16079655/28863920-0899b1a4-776b-11e7-9847-60b808c2aa20.png)

**Comment by metasnw** [comment]
was fixed allegedly by #1111

**Comment by metasnw** [comment]
IT was successfull

**Comment by metas-ts** [comment]
cherry-picked the fix into the `release`-branch, see https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/213/
