### ISSUE TITLE
Browse whole tree is not translated in DE

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1099]
### Type of issue
Bug

### Current behavior
window.sitemap.callToAction: 'Browse whole tree' is not translated

![image](https://user-images.githubusercontent.com/16079655/28745219-e73835f2-7473-11e7-8e07-7d5caee3a7e2.png)

### Expected behavior
according to  #924 it should be translatable so its caption should be "Gesamter Baum" or similar

### Steps to reproduce
1. open webui
1. switch language to de_DE
1. open menu

**Comment by cadavre** [comment]
Translation for this text is `window.browseTree.caption`.

**Comment by metas-lc** [comment]
sitemap is now missing

![sitemap](https://user-images.githubusercontent.com/16001666/29075906-9046639a-7c5c-11e7-9738-252f18f2838a.png)

**Comment by metas-lc** [comment]
IT
browse the whole tree is now translated OK
