### ISSUE TITLE
Don't fetch the side list when it's not needed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#110]
Test case: open a particular sales order
=> the side list is fetched even though is not displayed and it might be never displayed

![image](https://cloud.githubusercontent.com/assets/1244701/20570213/6c77e8de-b1ab-11e6-903e-1d6f57d87c49.png)

**Comment by damianprzygodzki** [comment]
@teosarca We have to init here.This is because sideList is just regular gridView, that has to fetch for example layout at the init.  Check also that is one and only call for sidelist - to avoid fetching so much data each time you open and close sidelist again.

This way of thinking is for dropdowns/lookups okay, whole views not okay.

**Comment by teosarca** [comment]
@damianprzygodzki  yes Damian, but why fetching it when user clicks first time on it.
I am saying this because in a lot of cases, when u navigate through documents, you as a user, you will not open the side list at all.

**Comment by damianprzygodzki** [comment]
Okay, i see likely solution, but still, im not sure that is okay for views. Lazy loading is not always good from UX perspective. If we can do something in background, and forestall user behavior and let him do not wait for something. Seeing everywhere loaders giving for an user feeling of slow app.
@cadavre could you correct me? Should we put everywhere lazy loading?

**Comment by cadavre** [comment]
We gonna probably change sidebar behaviour in some close future, as discussed with @metas-mk. We shall postpone this.

**Comment by teosarca** [comment]
About lazy loading, i've created a new issue to gather ideas: https://github.com/metasfresh/metasfresh-webui-frontend/issues/130

**Comment by damianprzygodzki** [comment]
I think we can close that issue and process it farther in #267 issue about sidelist rebuild.

**Comment by metas-lc** [comment]
IT
sidelist not fetched anymore OK
