### ISSUE TITLE
In grid view, when there is one document selected then show the referenced documents

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#111]
Case:
* open Sales order
* select one of them
* click on Menu
=> no document references are displayed

In this case we shall display those for that particular document.

![image](https://cloud.githubusercontent.com/assets/1244701/20571500/5983bf28-b1b0-11e6-8bcc-456c68b407f7.png)

**Comment by cadavre** [comment]
That's new. If we generate Referenced documents just when user clicks Actions menu we can make it.
