### ISSUE TITLE
Lookup Selection Lists not shown in Sequence anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1111]
### Type of issue
Bug (probably introduced w/ https://github.com/metasfresh/metasfresh-webui-frontend/issues/1000 )
### Current behavior
Currently, the Lookup Selection Lists don't appear anymore in included Field Sequence.
### Expected behavior
In Lookup Fields all included Fields Selection Lists shall be "opened" in sequence after filling/ selecting each the predecessor. The default value shall always be preselected. Only Exception: If only 0 or 1 entry exists then don't show the selection list and take the value as the entry. Jump to the next. If it's the last included field in a row the focus remains on the last included field after selection. Only if the user [TAB] the focus jumps to next field.
Example:
Open Window https://w101.metasfresh.com:8443/window/143/ and create a new Record. The cursor is on "Business Partner" Field Subfield "Business Partner". Type "Krake" [enter]. The next Focus should be on Business Partner Field Subfield "Location". A Selection List with all Location shall appear. After selecting the Location w/ [enter] the next included Subfield "Contact/User" shall open its Selection List. Selecting an entry w/ [enter] shall lead to selection. The focus remains on that field because it's the last Subfield in the Lookup Field. [TAB] brings the user to next Field  "Invoice Partner".
### Steps to reproduce
Open Window https://w101.metasfresh.com:8443/window/143/ and create a new Record. The cursor is on "Business Partner" Field Subfield "Business Partner". Type "Krake" [enter]. The Location entry is selected automatically and the Focus is on next Field "Invoice Partner".

**Comment by wiadev** [comment]
Confirmed. Wrong flow for requesting dropdown contents and focusing it.

**Comment by metas-rc** [comment]
Results of IT

* OK: The lookup selections list is shown now, when needed.
* OK: If there is one option only, it is directly set
* OK: If there are more than one option, the list opens, I can select, and what I selected is set int the field
