### ISSUE TITLE
caught in an empties loop when opened from material receipt candidates

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1114]
### Type of issue
Bug

### Current behavior
caught in an empties loop when opened from material receipt candidates
### Steps to reproduce
1. open https://w101.metasfresh.com:8443/window/540196?viewId=540196-c8eb110628f740659bfc6da0cb998539&page=1
1. pick any record
1. go to actions menu and open "empties return"
1. empties return window opens
1. try to open dashboard or another window
1. NOK: empties return window opens again
1. NOK: another empties return record is created

**Comment by metas-lc** [comment]
IT
1. open receipt candidates window https://w101.metasfresh.com:8443/window/540196?viewId=540196-c8eb110628f740659bfc6da0cb998539&page=1
2. pick any record
3. go to actions menu and open "empties return"
=> empties return window opens
4.1 (you can ship this step. Use 4.2 instead) try to open dashboard or another window
=> dasboard opens OK 
4.2 use the back button (to get back to receipt candidates window)
=> new empties is created and if you use back button again, 2 more are generated

note: from the start, it seems, that it's making 2 empties. I used "empties return" i got new one with id "1004387" and i press back and the id is "1004386", i press back again and i see quickly "1004388" and then "1004389" opens

**Comment by wiadev** [comment]
@metas-lc is this still IT-failed?

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

retested the case above:

* no additional empties returns are created when using back button: OK
* no additional empties returns are created when jumping through menu: OK
