### ISSUE TITLE
Cut-Off Header Names in Subtabs

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1117]
### Type of issue
Feature

### Current behavior
in subtabs header names are cut-off and no tooltip is displayed when you hover over them

https://w101.metasfresh.com:8443/window/111/1000000
![image](https://user-images.githubusercontent.com/16079655/28973439-79a770c4-7933-11e7-97d1-df3389a5d72b.png)

### Expected behavior
works like with header names in windows:
https://w101.metasfresh.com:8443/window/111?viewId=111-87a06785338e476cba0e3a33a70c8700&page=1

### Steps to reproduce
open https://w101.metasfresh.com:8443/window/111/1000000 and hover over tab column names that are cut off

**Comment by metas-lc** [comment]
IT
header names in subtabs have tooltips OK
