### ISSUE TITLE
On login page, deactivate the fields while logging in

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#112]
Case:
* login page
* type user and password
* press enter or click the Login button

It takes couple of seconds to actually login and show the dashboard.
In this period of time:
* the username and password fields are editable
* there is NO indicator that something is happening

I would like @metas-mk 's input but IMHO we shall at least deactivate the fields and the Login button.
In case the login failed, we shall activate them again.

I also think some sort of "logging in..." indicator would be nice.

**Comment by damianprzygodzki** [comment]
@cadavre 
TODO: indicator for login form

**Comment by cadavre** [comment]
Gonna forward this to Mirek.

**Comment by cadavre** [comment]
Or on the other hand we can just simple disabled="disabled" the inputs while loading. @damianprzygodzki ?

**Comment by damianprzygodzki** [comment]
@cadavre sure we can, but if we are introducing loader, let's put it everywhere

**Comment by cadavre** [comment]
Roger, then we go with loaders. Task is already made for Mirek for next iteration.

**Comment by teosarca** [comment]
Quick checked. Pls also disable the "Login" button.

**Comment by metas-mk** [comment]
Tested. Login Fields are now read-only/ deactivated when pressing "Login", so cannot be changed during Login processing anymore. Works nicely.
