### ISSUE TITLE
Localize remaining static elements

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#1121]
### Type of issue
Bug
### Current behavior

As of #924 all static elements should be localized

But currently, .e.g 'Attachment' is not.
Also the notifications about 
* completion
* failed upload

are not yet localized

### Expected behavior

All "static" strings that sre shown to the user should be localized such that we can translate them via `AD_Message`

**Comment by wiadev** [comment]
please make appropriate changes on server end which stores translated strings as per following key-value map:

```
window.attachment.title = Attachment

window.attachment.uploading = Uploading attachment

window.attachment.upload.success = Uploading attachment succeeded.

window.attachment.upload.error = Uploading attachment error.
```

@metasnw

**Comment by metas-lc** [comment]
IT
checked the Attachment part - it's translated. OK
