### ISSUE TITLE
Complete Keyboard navigation for WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#113]
Complete Keyboard navigation for WebUI
- everything must be possible with Keyboard only
- visibility/ transparency to see what keys are needed for what, so that the user has the change to read and learn easily (Tooltip?)

**Comment by cadavre** [comment]
This is something we will need to work together with API. We shall introduce:
- tabindex for inputs
- keyboard flows for widget types
- define global shortcuts
- define local shortcuts (per docType) [maybe / maybe not]
- design keyboard suggestion tooltips for shortcuted functions

**Comment by cadavre** [comment]
1. Per widget:
a) What happens on focus
b) What happens on arrow use
c) What happens on tab/shift+tab
d) What happens on Enter
e) Where focus goes to after Enter

2. tabindex (natural order?)

3. Global shortcuts (mf guys – please define)
I.e. what happens on "S" click

4. Tooltips as suggestions for defined shortcuts

5. Navigation on tables (tabbed, gridview, sidelist)

**Comment by cadavre** [comment]
Ad 2a) Focus first widget of first primary group.

**Comment by teosarca** [comment]
NOTE: when implementing this, pls store all shortcuts in some global config map because it might be that we will change them several times... so we would need a easy way to configure.

**Comment by cadavre** [comment]
```
Global context
==============
Mod + 1                 - open Actions menu
Mod + 2                 - open Navigtion menu
Mod + 3                 - open Inbox
Mod + 4                 - open Sidebar [in document context]
```

```
Documents list context
======================

Global
------
Mod + N                 - new

Selection
---------
Mod + M                 - open selected in new tabs
Del | Cmd+backspace     - remove selected items
```

```
Document context
================

Global
------
Mod + D                 - delete currently opened document
Mod + P                 - open generated raport to print in new tab
Mod + E                 - open Advanced edit modal
Mod + Q                 - move focus to Fast-line entry

Selection
---------
Del | Cmd+backspace     - remove selected items
```

And some additional functional shortcuts:

```
Any table elements selection
============================
Mod + C                 - copy line details
```

**Comment by cadavre** [comment]
New things to be accomplished for milestone:

1. Rename to official topbar element names:
Action menu (ctrl+1)
Navigation menu [or simply Navigation] (ctrl+2)
Inbox (ctrl+3)
Side list (ctrl+4)

2. Add shortcuts for:
- "Expand"/"Collapse" in bottom tab (ctrl+?)
- "Open batch entry"/"Close batch entry" in bottom tab (ctrl+?)

3. Fastline keyboard vs focus
- After click "Open batch entry" or "Expand" – auto-focus on first input in fastline.
- Tab goes to next input in fastline.
- Enter in fastline to add line.
- After adding new line, automatically focus again on first input.

**Comment by damianprzygodzki** [comment]
Update from my side
```
Table context
==============
Mod + q                 - toggle quick input
Mod + l                  - expand/collapse
```
