### ISSUE TITLE
Browse Whole Tree Caption not refreshed

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1135]
### Type of issue
Bug
### Current behavior
Currently, the Link for "Browse whole Tree" is not translated directly after Language Change in Avatar Settings. This also happens for other static Elements in Action menu, Sidelist Menu.
### Expected behavior
When switching the Language in Avatar Settings then the Sitemap and other Menus shall be translated directly.
### Steps to reproduce
Open Avatar Settings. Change Language. Open Sitemap Menu. "Browse whole Tree" is not translated. Press Browser refresh. Open Sitemap Menu. "Browse whole Tree" is translated.

![image](https://user-images.githubusercontent.com/13365687/29270765-8cb43590-80f8-11e7-8f4d-d71e4c32b0f2.png)

![image](https://user-images.githubusercontent.com/13365687/29271383-67b615da-80fb-11e7-932e-fef5150cf44b.png)

**Comment by metas-lc** [comment]
IT
change language and then look for browse the whole tree (without refreshing the page)
=> OK: it is there, and atranslated
