### ISSUE TITLE
Ellipses when breadcrumb too long & Tooltip

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1139]
### Type of issue
Feature request
### Current behavior
Currently, it happens that the Breadcrumbs get too long and it's overwriting the metasfresh Logo.
### Expected behavior
If the Breadcrumb menu gets too long, then the menu shall be shown w/ ellipses. When hovering over the Breadcrumb name then show a Tooltip (like when hovering over Labels, w/ same delay) which has the full name. This Tooltip shall be shown also when not shortened w/ ellipses.

![image](https://user-images.githubusercontent.com/13365687/29320714-6d2cbf54-81d8-11e7-95e2-4d01d81da55f.png)

**Comment by metas-lc** [comment]
IT
go to material tracking and open a line. Make the window a bit smaller so the breadcrumb would get over metasfresh logo => the breadcrumb is shortened with ellipses OK 
hover over breadcrumb => you can see the whole name in a tooltip OK
hover even if a breadcrumb is small enough to fit => tooltip still shown OK
