### ISSUE TITLE
Error when running a report:  pdf does not open

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#114]
Steps to reproduce:

* Go to Partner, select a row
* Open the available processes
* Run the process "Preisliste"
* Run the report without setting any parameter
 => NOK: the pdf is not opened
 => NOK: when inspecting we get: 
              * reportContentType: "application/pdf"
              * reportData: only an encripted text

**Comment by teosarca** [comment]
NOTE: now we have the /rest/api/process/instance/{pinstanceId}/print/{filename:.*} to fetch the report file.

Also, the /rest/api/process/instance/{pinstanceId}/start endpoint's result was change a bit.
We provide "reportContentType", "reportFilename".
If "reportFilename" field are filled, you shall call the "print" endpoint in a new tab.
