### ISSUE TITLE
Lookup Workflow for Batch Entry not correct

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1140]
### Type of issue
Bug
### Current behavior
Currently, when using the Batch Entry [ctrl]+space in Documents (i.e. Sales Order) then the Workflow is not correct. After selecting the Product via autocomplete Dropdown [enter] the cursor remains in the Product section.
### Expected behavior
The cursor shall be in the next included Lookup segment after [enter] selection.

![image](https://user-images.githubusercontent.com/13365687/29326062-65ffa34c-81ea-11e7-9292-2ab27dea8682.png)

**Comment by metas-mk** [comment]
This one works like wanted:
![image](https://user-images.githubusercontent.com/13365687/29364578-339d3874-8294-11e7-852e-8a8d6c3d210b.png)

This one does not work like wanted. Take "Krake AG" as Businesspartner. Then open Batchentry via [ctrl]+space. Then Type "conv" as product. Select w/ [enter]. Error happens. (does not happen when using [ctrl]+q):
![image](https://user-images.githubusercontent.com/13365687/29364682-9876c8fa-8294-11e7-8e1a-47c7d02812c7.png)

**Comment by metas-mk** [comment]
@wiadev Checked the example from above again. There is no difference between [ctrl]+q and [ctrl]+space. It just looked like it, because the cursor is not visible in [ctrl]+q for the "conv" case,, because the name content is longer as the field and the cursor is outside the visible area.

About the issue: Let's have a screen session and I can show whats happening/ shall happen.

**Comment by wiadev** [comment]
![screenshot2](https://user-images.githubusercontent.com/18234060/29526021-beb4883c-8694-11e7-90b7-1192eaf26691.png)

This is PATCH request sent when parent field gets changed. Dependent field gets default value from this response

so UI changes ONE specific field (and all request parameters are correct):
[{op: "replace", path: "M_Product_ID", value: {2005577: "Convenience salad 250g_123456789_P002737"}}]

For some reason server response returns "M_HU_PI_Item_Product_ID" field with newly set value. That's perfectly fine, when items are available and selectable. But in this case returned data seems to be incorrect.

It seems like bug on backend, I didn't found any signs that something wrong on UI end
I've applied some additional checks to cover potentially wrong cases, but reported test case doesn' t look like UI related issue

**Comment by teosarca** [comment]
If the M_HU_PI_Item_Product_ID value that was set is not present in the dropdown/typeahead values provided by backend for that field.... then, yes, it's a bug. It might be https://github.com/metasfresh/metasfresh-webui-api/issues/128

**Comment by teosarca** [comment]
update: quick tested now and have follow issue: in case the dropdown has only one item, the dropdown shall not be shown

![image](https://user-images.githubusercontent.com/1244701/29533043-aa8b539e-86b8-11e7-923f-3ade44ad0b5e.png)

**Comment by metas-lc** [comment]
IT
tested with a product having 1 TU and with a product having 2 TUs (using both ctrl + q and ctrl+space)
=> after you set the product, the HU is added, or a dropdown appears to select it in case of multiple HUs. 
after selecting the hu, press tab and it gets you to qty OK

**Comment by teosarca** [comment]
@metas-lc Note to IT:
* please make sure we have the lookup testing documented in our test catalog
* from now on, each time the lookup code is touched we need to perform full regression testing on lookups will all cases

**Comment by metas-mk** [comment]
Tested quickly in Sales Order https://w101.metasfresh.com:8443/window/143/1005914
Lookups are broken:
a) The Workflow in BusinessPartner entry does not work anymore (no dropdown lists when entering the BusinessPartner -> Location -> User ...)
b) Batchentry w/ product "Holz" (no Packing Material/ Gebinde) Cursor stays in Product after enter instead of beeing in empty next field (Gebinde).

**Comment by metas-mk** [comment]
Quick Test done on w101. Works nicely now in Sales Order Business Partner AND in Batch Entry Mode. Further Tests needed.

**Comment by metas-ts** [comment]
Cherry-picked into branches `release` (i.e. RC for 5.25) and into `r5.24`.
See https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/221/ and https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/222/

**Comment by metas-rc** [comment]
Results of IT

* Stress-tested in several windows. 
* Multiple options are all displayed when available 
* if there is a single option it is set by default
* Problem found with mandatory elements of the composed fields: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1253
