### ISSUE TITLE
Sort indicator triangle missing in Grid Header

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1141]
### Type of issue
Bug
### Current behavior
Currently, the sort indicator triangle is missing in Grid Views. Seems to have been vanished since ellipses implementation.
### Expected behavior
The sorting shall be indicated by up/down triangle again.
### Steps to reproduce
Open any grid view and press on column header. The sorting happens but no indicator is shown.

**Comment by metas-mk** [comment]
Tested quickly. Works nicely.
Looks mostly nice, but not for cases w/ ellipses:

![image](https://user-images.githubusercontent.com/13365687/29411212-209d3e84-8354-11e7-8bf3-dabc4060fc0c.png)

**Comment by metas-lc** [comment]
IT
checked multiple windows - grid view and also subtabs in doc view
=> Sort indicator triangle is written after the field's name or after ellipses. OK
=> ellipses are also at the same height as the field OK
