### ISSUE TITLE
Error when starting a report without parameters

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#115]
![image](https://cloud.githubusercontent.com/assets/16001442/20675430/e2001eea-b594-11e6-860a-75c896659c0d.png)

Steps to reproduce:

* Go to Shipments, select a row
* Open the available processes
* Run the first report from Actions ( as shown in the picture) 
 => NOK: PDF not opened
 => NOK: when inspecting, you see there is no layout request
The only thing from the console is this: http://pastebin.com/LXuJwLRn

**Comment by teosarca** [comment]
UPDATE: basically, in case the process has NO parameters, it won't be started at all => NOK

**Comment by damianprzygodzki** [comment]
I've checked that issue - when parameters has no parameters front end is throwing exception, process i canceled and the modal is not displayed - is it wrong?

**Comment by teosarca** [comment]
yes it is... having a process without parameters is completely normal.

**Comment by teosarca** [comment]
and in this case, i think u could start the process directly. wdyt?

**Comment by damianprzygodzki** [comment]
Without calling layout right? So if we have no params i should just start process?

**Comment by damianprzygodzki** [comment]
Okay, so for the moment, when we have params we are opening standard window with process. When we have no params, we are starting the process and in response:

- if reportFilename exist frontend calling print endpoint
- if summary exist frontend showing 'primary' notification with summary displayed

Are there other cases to handle?

**Comment by teosarca** [comment]
for the time being it's fine... other cases will go in other tasks.
