### ISSUE TITLE
find a new shortcut for CTRL + X 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1152]
### Type of issue
Bug

### Current behavior
if you use CTRL + X in webUI on windows a new mail is created because the windows standard shortcut is also used by metasfresh to send an email

### Expected behavior
find a new, free shortcut

### Steps to reproduce
1. open https://w101.metasfresh.com:8443/window/123/2156488
1. go into any text field and mark text
1. press CTRL+X
1. NOK: text is not cut to clipboard
1. NOK: metasfresh tries to create an email

**Comment by metas-lc** [comment]
IT
repeated the testcase above: went to bpartner window and selected a text field, used ctrl+x => text was cut (i could paste it after) OK
used ctrl+x randomly (not while being on a field) => nothing happened OK
