### ISSUE TITLE
Offline message is no longer displayed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1156]
### Type of issue
Bug

### Current behavior
If the server is down, the frontend screen is grayed out (OK) but there is no message displayed.

### Expected behavior
The offline mode message shall be displayed.

See also / might be related to:
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1045
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1049

**Comment by wiadev** [comment]
@teosarca  This works fine UNTIL we reload the page (while staying offline).

If we try to refresh page without connection established (e.g. being offline) - localized messages doesn't load as well, thus nothing to display.

If your server is down, it's very unlikely to get anything in response to API i18n/messages request.

Then we're getting empty list of localized messages, thus when component displays error message (expecting localized strings) it couldn't display anything.

I will add english fallback message if locale isn't loaded.

**Comment by wiadev** [comment]
@teosarca 
This is optional, but might help for some cases. There are no any guarantees from browser that such requests will be surely cached. It could put into cache or not. Imagine the case when user turned it off (cache). Or no free disk space. Yes, these cases are not that often, but it could happen so browser will not use cache anymore.

**Comment by teosarca** [comment]
Thanks for input @wiadev . 
But still, we can have this caching (I will implement sometime in the future) and ALSO have the fallback message on frontend side (which will be implemented by you in this task).

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* correct msg displayed when Server is down (e.g. during rollout), not just grayed out screen: OK
