### ISSUE TITLE
Delete User Notifications

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1157]
### Type of issue
Feature request
### Current behavior
Currently, there is no possibility for the user to delete the own User Notifications.
### Expected behavior
The User shall have the possibility to select and delete the own User Notifications.

Important: Before Implementing, wait for this Issue to be done first.
https://github.com/metasfresh/metasfresh-webui-api/issues/546

**Comment by teosarca** [comment]
API available.
* to delete on notification: http://w101.metasfresh.com:8081/swagger-ui.html#!/notification-rest-controller/deleteByIdUsingDELETE
* to delete several notifications, specified as comma separated IDs: http://w101.metasfresh.com:8081/swagger-ui.html#!/notification-rest-controller/deleteByIdsUsingDELETE

**Comment by metas-rc** [comment]
Results of IT

* OK: The notifications can be deleted
* OK: The same number of notifications are displayed before and after cache reset.
