### ISSUE TITLE
Larger fontsize in Yes/ No Popups

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#116]
Larger fontsize in Yes/ No Popups
Size should be similar to table header in the background. wdyt?

![image](https://cloud.githubusercontent.com/assets/13365687/20701141/9f8dbb80-b611-11e6-98bc-531d1c6d466c.png)

**Comment by cadavre** [comment]
I would suggest to change text size to system's default (what can be seen in the background, as said) and set popup content container height to fit content (width is ok).

**Comment by metas-mk** [comment]
+1
