### ISSUE TITLE
frontend: document cloning

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1164]
### Type of issue
Feature request

### Steps to reproduce
* browsing a single document (e.g. a purchase order)
* the "Clone" (i18n!) shall be available in menu
* when user presses on it, the http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/duplicateUsingPOST endpoint shall be called. That endpoint will clone given document and it will return the newly created one
* the frontend shall switch to new document.

![image](https://user-images.githubusercontent.com/1244701/29816267-26a6bb90-8cbc-11e7-92a0-0f37ee279735.png)

Backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/54

**Comment by wiadev** [comment]
Please add following entry into i18n table (which is sent as response to /api/i18n/messages API call) for default locale and feel free to translate to other languages:

window.clone.caption="Clone" @teosarca

**Comment by teosarca** [comment]
@wiadev  done, see http://w101.metasfresh.com:8081/rest/api/i18n/messages?filter=window.clone.caption

**Comment by metas-lc** [comment]
IT
I. Sales order: OK
1. create a new sales order, add all mandatory fields
2. change all the dates, so it won't be today
3. set a reference, a dropshipment bpartner
4. add 2 products, set an attribute for one and for the other one let it empty, set HU for one and the other one "no packing item", change the price for one and the other one leave it like it is
5. complete the order
6. go to actions, select Clone
=> new sales order opens on the same tab
=> status draft, with 2 lines of product (no TU line)
=> all the fields were copied (bpartner, products, attributes, dropship, packages) besides: dates (all set on today), reference (empty), price (was taken from pricelist) 

II. purchase order

**Comment by wiadev** [comment]
@metas-lc is this IT-failed?

**Comment by teosarca** [comment]
@wiadev  they are backend issues, Lili (@metas-lc) will move them to backend task.

**Comment by metas-lc** [comment]
I'll keep this task on me so i can retest it when the backend is done

**Comment by teosarca** [comment]
IMHO the frontend task can be closed because it's working OK.
All the failing cases are on backend side.
