### ISSUE TITLE
Edit Fields in Main Grid View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1167]
### Type of issue
Feature request
### Current behavior
Currently, it is not possible in Main Grid Views to edit fields directly in there.
### Expected behavior
It shall be possible. It's mostly missed in Product Price maintenance, where the user has to change a lot of Prices in a short time. The solution could be, to add an edit selection via right mouse, OR to have a "table edit mode switch" in window action that switches the window to an edit mode like in included tabs. WDYT?

![image](https://user-images.githubusercontent.com/13365687/29857881-2833841c-8d5b-11e7-9d2c-c2c952029909.png)

**Comment by teosarca** [comment]
Found following issues on last PR:

1. Issue when going from one view to another:
* open sales order view, e.g. http://localhost:3000/window/143?viewId=143-13ecd47b5c014ba4ae510d8b9a7d33bb&page=1
* open menu, type "product prices" and click to go to that view
* only the table header is changed but nothing else: data is not queried, table content is not queried, view is not created (remark that there is no viewId in URL)

![image](https://user-images.githubusercontent.com/1244701/30546654-efe7f40e-9c95-11e7-85b7-dccf464bb7fe.png)
![image](https://user-images.githubusercontent.com/1244701/30546727-0e848698-9c96-11e7-9d7b-c9a50d06e3c3.png)
![image](https://user-images.githubusercontent.com/1244701/30546757-2a068baa-9c96-11e7-9495-cd794df66e17.png)

**Comment by teosarca** [comment]
another issue,

2. Editing does not work
* go to Product Prices view: http://localhost:3000/window/540325
* right click on some Price field and click "Edit field value"
* no editing component is shown

![image](https://user-images.githubusercontent.com/1244701/30546833-58ad44f8-9c96-11e7-8aa5-562fc4e89bb6.png)
![image](https://user-images.githubusercontent.com/1244701/30546905-988e9108-9c96-11e7-8708-58aa720ce0c0.png)

**Comment by teosarca** [comment]
3. the "Edit field value" is not translated,
* switch your language to german
* go to product prices and right click on some price cell
* the "Edit field value" is still in english

**Comment by metas-lc** [comment]
IT
1. navigating from a window to another (e.g. Sales order to Product prices) works fine. The content changed OK
2. go to product price, grid view, try to edit a price: it works, you can use up and down arrow to change price, or directly the keyboard
NOK: if you click too fast on the arrows, the document view is opening. It shall not open if you click there
3. switched to german language, "Edit field value" is still in english NOK

created follow-up https://github.com/metasfresh/metasfresh-webui-frontend/issues/1274
