### ISSUE TITLE
Edit Account Lookup Fields in GridView not possible

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1170]
### Type of issue
Bug
### Current behavior
When editing the Account in Grid View then the selection is not saved to record. It falls back to the initial state.
### Expected behavior
Shall take and save the selection.

![image](https://user-images.githubusercontent.com/13365687/29995223-d3cb4306-8fe4-11e7-87c8-a2307da1992e.png)

**Comment by metas-lc** [comment]
IT
product window, accounting included tab, change some fields there, directly in grid view (like accet, expense) => ok, you can change it. It's not set back to he initial one OK
