### ISSUE TITLE
filtering is not working in picking

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1172]
### Type of issue
Bug
### Current behavior
filtering is not working in picking
### Expected behavior
filter should work (see step ...)
### Steps to reproduce
1. open picking: https://w101.metasfresh.com:8443/window/540345?viewId=540345-eb9a8c886e994a19aaf8c23a0d77dfc4&page=1
2. select a product you know it has HUs (e.g. Topinambour)
3. pick
![picking_filter](https://user-images.githubusercontent.com/16001666/30028504-0366d968-918e-11e7-8f0e-029cc6858481.png)
4. open hu selection window 
![2017-09-04 16_21_43-metasfresh](https://user-images.githubusercontent.com/16001666/30028525-19db2870-918e-11e7-910f-789966f9161c.png)

5. filter for barcode or HU value
=> nothing was found
![picking_filter_3](https://user-images.githubusercontent.com/16001666/30028541-299e3d7e-918e-11e7-88f5-d02328a5e6b5.png)

![picking_filter_4](https://user-images.githubusercontent.com/16001666/30028547-312a4c86-918e-11e7-8777-eb0dfca42bf2.png)

NOTE: if you go to barcode filter again (the HU value is already written) and you just press enter it works!

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15

* filtering for HU with Barcode / Value: working fine at first try (see testing step above): OK
* works only for top level HUs, not e.g. TU on LU, but LU, free TU & CU: OK for now
