### ISSUE TITLE
picking: weird issues with included view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1174]
### Type of issue
Bug

### Steps to reproduce
* open picking terminal: https://w101.metasfresh.com:8443/window/540345
* select a line and call "Pick": now on left side you have the lines you can pick and on right side you have the picking slots view.
* let the first line selected and press the "Open HU selection..." buton:
![image](https://user-images.githubusercontent.com/1244701/30035629-dbe2c312-91b4-11e7-81d5-5ff3a304114f.png)
* on the right side, the  "Handling Units(HUs) to pick" included view is displayed:
![image](https://user-images.githubusercontent.com/1244701/30035668-3f4eca04-91b5-11e7-9ca1-dc28655b09a8.png)
* now press "Done" to get back to initial view:
![image](https://user-images.githubusercontent.com/1244701/30035696-7bf03722-91b5-11e7-87dd-bf6d79e0f7da.png)

* here select a different line and call "Pick" action again
Remark:
* in the modal which is opened, the right side view is EXACTLY the one which was displayed on previous selected line => NOK
![image](https://user-images.githubusercontent.com/1244701/30035730-da66aff2-91b5-11e7-964b-c4418afed7f1.png)

### Expected behavior
Fix the issue.
Make sure the state is **trashed** when the modal is closed.

**Comment by metas-ts** [comment]
Please IT asap and ping me for CPing after the test was OK.

**Comment by metas-lc** [comment]
IT
repeated the testcase above => after picking a different line, you get the view from your new line OK

**Comment by metas-ts** [comment]
cherry-picked into the `release` branch
