### ISSUE TITLE
[ctrl]+enter does not save changes before

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1179]
### Type of issue
Bug
### Current behavior
When using [ctrl]+enter in action parm modal overlay, then the last changes are not saved. Using the mouse instead, pressing "start" does the save.
### Expected behavior
[ctrl]+enter shall also save changes before.
### Steps to reproduce
Go to window window/540196. Select a line. Open Action dropdown. Press HU's annehmen. In modal overlay change the qtyLU to other number. Still in field press [ctrl]+enter. The changed qty is not taken. The previous number is used instead. Do the same w/ mouse instead, you can see that a "save" is triggered first (green save indicator).

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15 & mfreleasetest

1. Open material receipt candidates, select a line
2. Select HUs annehmen in Actions
3. Change qty LU, and press [ctrl]+enter while still in field!
 * changes for qty LU are saved, green save indicator is displayed: OK
 * HU Editor opens with the qty LU you set before: OK
4. Go back to first window, select CU annehmen mit Menge
5. Change qty CU, and press [ctrl]+enter while still in field!
 * changes for qty CU are saved, green save indicator is displayed: OK
 * HU Editor opens with the qty CU you set before: OK
