### ISSUE TITLE
Copy-paste behaviour for document and lists

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#118]
Today exporting list data works in this particular case:
http://www.screencast.com/t/sbj2LsEbvC

Aim of this issue is to extend it to more cases and also using the keyboard:

Case # 1
1. open order window
2. click anywhere in the line to highlight it 
3. press CTRL+C
4. open notepad
5. press CTRL+V
6. Expectation: All highlighted lines are copied 

Case # 2 - last line is dropped
1. open order window
2. click left of c_doctype in the first line to highlight it 
3. click somewhere in the second line pressing SHIFT to highlight it as well
3. press CTRL+C
4. open notepad
5. press CTRL+V
6. OK: Text of first line is inserted 
7. NOK: second line is missing totally

Case # 3 - copy depends on where you click
1. open order window
2. click right of c_doctype in the first line to highlight it 
3. click somewhere in the second line pressing SHIFT to highlight it as well
3. press CTRL+C
4. open notepad
5. press CTRL+V
6. NOK: Text of first line is inserted but first value comes at the end

**Comment by cadavre** [comment]
Please rename "problem" to define it as new functionality – because it is one. :)

**Comment by metasnw** [comment]
so my expectation is wrong that copy and paste from grid should work ?

**Comment by cadavre** [comment]
Yes.

**Comment by metasnw** [comment]
ok :-)
should dragging instead of CTRL + C/V should work ?

**Comment by metasnw** [comment]
ok, I found a way how it works:
when I click left from Standardauftrag and then drag all text is copied

**Comment by cadavre** [comment]
Nope. ;)

You are defining whole new set of functionalities. If it is your expectation – please describe all expected behaviours and define it as a set of new features. :)

**Comment by metasnw** [comment]
so its just a coincidence that it is working fine in that case?

**Comment by cadavre** [comment]
What you are facing is default select behaviour for different HTML elements. We never defined custom selection behaviour so right now it's rather... random.

**Comment by metasnw** [comment]
got it to work if you do like this:
http://www.screencast.com/t/sbj2LsEbvC

and therefore thought its a builtin feature.

**Comment by metasnw** [comment]
I will change the task to reflect that this is actually a feature request

**Comment by metasnw** [comment]
changed it. Is it OK with you how it is now ?

**Comment by damianprzygodzki** [comment]
Tested and prepared for cases like:

1) Master document window:

For single selected row:
```
Line No,Product,Attribute Set Instance,Trading Unit Quantity,Trading Unit,Quantity,UOM,Price,Price Unit,Quantity in Price Unit,Discount %,Unit Price,Line Amount,Tax,Vertragsbedingungen
10,P002737_Convenience salad 250g,---,2,IFCO 6410 x 8 Stk,16,Each,1.36,Each,16,0,1.36,21.76,Reduzierter Steuersatz 7% (Deutschland),
```

For multiple selection:

```
Line No,Product,Attribute Set Instance,Trading Unit Quantity,Trading Unit,Quantity,UOM,Price,Price Unit,Quantity in Price Unit,Discount %,Unit Price,Line Amount,Tax,Vertragsbedingungen
10,P002737_Convenience salad 250g,---,2,IFCO 6410 x 8 Stk,16,Each,1.36,Each,16,0,1.36,21.76,Reduzierter Steuersatz 7% (Deutschland),
20,P002737_Convenience salad 250g,---,2,IFCO 6410 x 8 Stk,16,Each,1.36,Each,16,0,1.36,21.76,Reduzierter Steuersatz 7% (Deutschland),
```

2) Documents list

Single selection
```
Target Document Type,Document No,Date Ordered,Document Status,Business Partner ,Order Reference,Grand Total,Currency,Date Promised,Date of Provisioning,Organization
Sales Order,1714,2017-03-28T00:00:00.000+02:00,Drafted,metasfreshTest,,46.57,EUR,2017-03-28T23:59:59.000+02:00,2017-03-28T23:59:59.000+02:00,metasfresh AG
```

Multiple selection
```
Target Document Type,Document No,Date Ordered,Document Status,Business Partner ,Order Reference,Grand Total,Currency,Date Promised,Date of Provisioning,Organization
Sales Order,1714,2017-03-28T00:00:00.000+02:00,Drafted,metasfreshTest,,46.57,EUR,2017-03-28T23:59:59.000+02:00,2017-03-28T23:59:59.000+02:00,metasfresh AG
Sales Order,1713,2017-03-28T00:00:00.000+02:00,Drafted,metasfreshTest,,51.15,EUR,2017-03-28T23:59:59.000+02:00,2017-03-28T23:59:59.000+02:00,metasfresh AG
Sales Order,1712,2017-03-28T00:00:00.000+02:00,Drafted,metasfreshTest,,0.00,EUR,2017-03-28T23:59:59.000+02:00,2017-03-28T23:59:59.000+02:00,metasfresh AG
```

**Comment by teosarca** [comment]
Pls ask @metasnw if this one was tested.

**Comment by metasnw** [comment]
tested all cases and it works fine :+1:
