### ISSUE TITLE
Initial Sort indicator not shown in Included Tabs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1181]
### Type of issue
Bug
### Current behavior
Currently, the initial Sorting is not shown in included tabs.
### Expected behavior
Shall be shown.
### Steps to reproduce
Open Window https://w101.metasfresh.com:8443/window/540321/2008396
The Initial Sorting in included Tab is on "ValidFrom". No Indicator is shown.

![image](https://user-images.githubusercontent.com/13365687/30113598-84531d24-9315-11e7-9c7d-38072023d770.png)

**Comment by teosarca** [comment]
duplicate of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1147
