### ISSUE TITLE
purchase order: screen is scrolling when i am trying to type in Delivery from field

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1183]
### Type of issue
Bug

### Steps to reproduce
* go to purchase orders: https://w101.metasfresh.com:8443/window/181
* press New to create a new one
* the cursor is in "Delivery from" field => OK
* start typing => the screen is scrolled up in a very weird way => NOK
Remove this part if feature request.

### Expected behavior
Don't scroll the screen.

**Comment by teosarca** [comment]
not sure, but might be that it was introduced by one of the last PRs, maybe https://github.com/metasfresh/metasfresh-webui-frontend/pull/1182 ?

**Comment by metas-ts** [comment]
cherry-picked into branch `2017-09-12`

**Comment by metas-ts** [comment]
cherry-picked to the branches `release`and `2017-09-12`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15releasetest

tested with steps described above, no scrolling of the screen was visible: OK
