### ISSUE TITLE
get rid of deprecated view row attributes API

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1184]
### Type of issue
Feature request

### Current behavior
At the moment, the frontend is using APIs from http://w101.metasfresh.com:8081/swagger-ui.html#/view-row-attributes-rest-controller-_-old .

### Expected behavior
Use exclusively the API from http://w101.metasfresh.com:8081/swagger-ui.html#/view-row-attributes-rest-controller .

The http://w101.metasfresh.com:8081/swagger-ui.html#/view-row-attributes-rest-controller-_-old is scheduled to be dropped as soon as this task is done.

**Comment by wiadev** [comment]
@teosarca where to find such requests?
I see http://w101.metasfresh.com:8081/swagger-ui.html#/window-rest-controller requests only

**Comment by teosarca** [comment]
![image](https://user-images.githubusercontent.com/1244701/30207285-a7d88b0c-9497-11e7-841c-6dd3fc222ce9.png)


i.e. don't use any of the API endpoints listed under "view-row-attributes-rest-controller-_-old : View Row Attributes Rest Controller _ OLD".

Replace them with the API calls listed under "view-row-attributes-rest-controller : View Row Attributes Rest Controller".

Basically, if you compare those 2 versions, you will see that we have introduced "../attributes/.." in endpoint names.

**Comment by teosarca** [comment]
@wiadev  closing this one because now i saw that i've created another one. see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1357
