### ISSUE TITLE
Home and End button move caret in text fields

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1188]
### Type of issue
Bug

### Steps to reproduce
* open material receipt candidates: https://w101.metasfresh.com:8443/window/540196
* select a line and receive, e.g.
![image](https://user-images.githubusercontent.com/1244701/30204491-5407e490-948e-11e7-9752-05b38c4b3a92.png)
![image](https://user-images.githubusercontent.com/1244701/30204505-64a7d18e-948e-11e7-9501-81114e17da54.png)

* select the HU (e.g. first line) and call a process which has parameters, e.g. Materialentnahme (partial)
![image](https://user-images.githubusercontent.com/1244701/30204568-97bf4c78-948e-11e7-8ae3-630929097954.png)

* the cursor is inside the "Menge TU" field (i.e. the one and only text field).
Now press "HOME" or "END" keyboard buttons to move your cursor to be beginning or to en END, but nothing happens. Instead, the key press is intercepted by the underlying view and the frontend tries to navigate it forward/backward.
![image](https://user-images.githubusercontent.com/1244701/30204707-1a5cddda-948f-11e7-8474-701e6c4e6711.png)

### Expected behavior
When the cursor is inside a text field, the HOME and END keys shall work.
Regression: make sure, when browsing a view, the HOME and END key will navigate you to first/last page.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested in material receipt cands, with processes for labels (e.g. IFCO) where there was only 1 text field (since Materialentnahme was not available):
* nothing happened when pressing `Home` or `End` key: NOK
* console:

```
Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at t.value [as setCaretPosition] (https://mf15cloudit/bundle-e706e0fad24580059f8f-git-a648a51.js:70:439457)
    at TEXT_START (https://mf15cloudit/bundle-e706e0fad24580059f8f-git-a648a51.js:70:439182)
    at t.value [as fireHandlers] (https://mf15cloudit/bundle-e706e0fad24580059f8f-git-a648a51.js:77:231074)
    at HTMLDocument.value (https://mf15cloudit/bundle-e706e0fad24580059f8f-git-a648a51.js:77:231662)
```

* `Home` and `End` key worked fine for navigating to first / last page: OK

**Comment by siemiatj** [comment]
oh, looks like a browser thing. Checking.

**Comment by siemiatj** [comment]
@metas-dh can you give link-share screen ? I can't find any item editable in material receipt candidates and everywhere else I'm trying this things seem to work fine.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* pressing `Home` or `End` key working in fields with text inputs: OK (checked in e.g. order reference / MHD attribute in material receipt cands)
* `Home` and `End` key worked fine for navigating to first / last page: OK
