### ISSUE TITLE
Cannot set product's packing material

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#119]
Test case:
* create a new sales order line
* pick the product
* UI is not asking me to pick the packing material => NOK

That field shall work similar with BPartner/Location/Contact.

![image](https://cloud.githubusercontent.com/assets/1244701/20723802/a2b78382-b674-11e6-846c-aaace6677276.png)

**Comment by damianprzygodzki** [comment]
The lookup field is not asking about the property when there is only one available choice. As i tested it, always i get one entity.

And i think it was assumed at the beginning. Should i always show dropdown?

**Comment by teosarca** [comment]
If it's only one then pls don't show the popup....

But AFAIR, it's wasn't only one.

I shall check it but i can also debug & call the /dropdown method to see if there are more then one....
Btw, try with the problem from my test case.

**Comment by damianprzygodzki** [comment]
I have tried each of product visible here. Always what i am getting is `[{3010006: "No Handling Unit"}]`. Please, provide any example product with more than one packing.

**Comment by damianprzygodzki** [comment]
What's more, when i send commit that is clearing field, in response i am getting `M_HU_PI_Item_Product_ID","value":{"101":"VirtualPI"}`. So the API setting this value.

**Comment by teosarca** [comment]
Thanks for checking!
It looks like i have to check it on backend side too.

**Comment by teosarca** [comment]
nail it!

u are not providing tabid and rowId when u are calling the dropdown API!

![image](https://cloud.githubusercontent.com/assets/1244701/20759881/ffb9954a-b726-11e6-9881-d7cdd237a7d6.png)
