### ISSUE TITLE
grid values are cut off if column size is too small

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1192]
### Type of issue
feature

### Current behavior
cant see the complete value of a grid field if column is too small

### Expected behavior
mouse over to show full value

### Steps to reproduce
https://w101.metasfresh.com:8443/window/540334?viewId=540334-be746342b9284645bbbf0a7b2ca60b5c&page=1

![image](https://user-images.githubusercontent.com/16079655/30268896-790d40ae-96e7-11e7-9c21-49e63b7569a2.png)

**Comment by metas-lc** [comment]
IT
opened Material Schedule window, hover over a product => can see the whole name OK
