### ISSUE TITLE
Use API to fetch the locale

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1194]
This is a follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1060,
where the locale were hardcoded.

In this task we want to get rid of hardcoded stuff and use the server's API to fetch the locale info.
Check http://w101.metasfresh.com:8081/rest/api/userSession .

backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/581

**Comment by teosarca** [comment]
NOTE: when developing this task, pls also check my comments from https://github.com/metasfresh/metasfresh-webui-frontend/pull/1193#discussion_r138067920 where i've explained what's not OK with #1060.

**Comment by metas-lc** [comment]
tested  in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1060
