### ISSUE TITLE
Render only provided document standard actions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1195]
### Type of issue
Feature request

### Current behavior
At the moment the standard document's actions are hardcoded on frontend side,
i.e. i am talking about those ones

![image](https://user-images.githubusercontent.com/1244701/30316302-797fa2ac-97af-11e7-9049-ba2e3ef93aee.png)

### Expected behavior
Frontend display ONLY those actions which are available on that list.

For now, pls hardcode that list.

### Steps to reproduce
Any document

The backend task is: https://github.com/metasfresh/metasfresh-webui-api/issues/583

**Comment by teosarca** [comment]
update: API ready on w101

**Comment by metas-rc** [comment]
Results of IT

* I checked in several windows and only the provided standard actions are rendered
