### ISSUE TITLE
frontend: Letters feature

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1196]
### Type of issue
Feature request

### Expected behavior
1. open a document, e.g. a sales order - https://w101.metasfresh.com:8443/window/143/1000257
2. click on Menu -> Letter (note: the Letter menu item shall be displayed if provided, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1195 )
![image](https://user-images.githubusercontent.com/1244701/30363298-47db7f82-9868-11e7-86ac-29220eaf5135.png)

3. A letter modal is opening which is very similar with the Menu->Email modal, but much more simple:
![image](https://user-images.githubusercontent.com/1244701/30363363-82bea034-9868-11e7-90db-fc4a2b17021b.png)
i.e.
* there is no "To" and "Topic" fields
* there are no attachments
* we still have the the templates dropdown (top right corner) which shall work like in the Email modal but instead of "/mail/*" APIs, the "/letter/*" APIs shall be used
* on the left side of templates dropdown we have a print preview icon (button) which when pressed it shall call /letter/{letterId}/printPreview
* on bottom we have the "Create" button. When pressed the /letter/{letterId}/complete API shall be called and if successful, the modal shall be closed
![image](https://user-images.githubusercontent.com/1244701/30363520-325263be-9869-11e7-9cf2-cd131aa82978.png)

#### Notes and observations
* all texts & messages shall be acquired via /i18n/messages
* the letters API is described here: http://w101.metasfresh.com:8081/swagger-ui.html#/letter-rest-controller which is very similar with Mail API which is described here: http://w101.metasfresh.com:8081/swagger-ui.html#/mail-rest-controller

**Comment by teosarca** [comment]
The backend task is https://github.com/metasfresh/metasfresh-webui-api/issues/178

**Comment by PabloSichert** [comment]
Should there be a hotkey for this feature? If yes, which one?

**Comment by metas-mk** [comment]
> Should there be a hotkey for this feature? If yes, which one?
@PabloSichert No thanks. Not needed atm.

**Comment by teosarca** [comment]
btw, @PabloSichert  the Letter menu item shall be visible only if is provided in document's standardActions, i.e.

![image](https://user-images.githubusercontent.com/1244701/30600195-7bab54d2-9d67-11e7-8748-1e8f722faabf.png)

**Comment by PabloSichert** [comment]
@metas-mk Ok. I think the hotkeys could use some refactoring as well. For example I think `mod + n`would be more intuitive for "New document" instead of `mod + m`. But that also depends how accustomed users are to the existing hotkeys.
 
@teosarca I put a [comment](https://github.com/metasfresh/metasfresh-webui-frontend/pull/1207#issue-258857110) on the PR regarding that. I think it would be easier to leave it hardcoded in this PR and then refactor it altogether in #1195.

**Comment by teosarca** [comment]
hi @PabloSichert , thanks for the PR.

Did a quick test and found following issues.

1. (cosmetics) until we find an icon for Letter menu item i would suggest to keep the space empty and have the menu item texts aligned:
![image](https://user-images.githubusercontent.com/1244701/30606703-4029ed6a-9d7b-11e7-9646-129608301c6b.png)

**Comment by teosarca** [comment]
2. The text templates dropdown is missing:
![image](https://user-images.githubusercontent.com/1244701/30606840-b624689c-9d7b-11e7-91b2-b847ea1eae33.png)

It shall look and work exactly like in Email panel:
![image](https://user-images.githubusercontent.com/1244701/30606887-dd2eefd4-9d7b-11e7-90ab-3ae0cde9bd84.png)

**Comment by PabloSichert** [comment]
The dropdown should be visible when the endpoints returns a set of templates

**Comment by PabloSichert** [comment]
Thanks for checking out the changes. I'll align the text accordingly.

The dropdown should be visible when the endpoint returns a set of templates.

![image](https://user-images.githubusercontent.com/4450694/30607499-872acee2-9d75-11e7-853d-b74b61da4ccc.png)

Can you confirm that this is the right endpoint, but it doesn't return templates yet or is the URL wrong?

**Comment by teosarca** [comment]
shit, right :)

I forgot to add that method. I just added now and it will be available on next build/rollout.

Btw, after selecting a template, i got following warning in console. Not sure if it's OK?!
![image](https://user-images.githubusercontent.com/1244701/30608380-c73f39d6-9d80-11e7-92e4-a6325516a257.png)

**Comment by PabloSichert** [comment]
Np 😄 I'll look into it. Also fixing the margin between print preview button and dropdown at the top.

**Comment by teosarca** [comment]
done, API available: http://w101.metasfresh.com:8081/swagger-ui.html#!/letter-rest-controller/getTemplatesUsingGET

**Comment by metas-rc** [comment]
Results of IT

* OK: The letter funtionality works well. See resultsof https://github.com/metasfresh/metasfresh-webui-api/issues/178 for information

* The letter window closes after print preview. Followup created: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1227
