### ISSUE TITLE
Date/Date picker is broken

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#120]
![image](https://cloud.githubusercontent.com/assets/1244701/20727394/0130fbca-b682-11e6-96da-04dfd5c3e92f.png)

**Comment by damianprzygodzki** [comment]
@teosarca Could you provide more info? How did it happen? I tried to create a new doc, open yours (but it is deleted), tested few existing and can't reproduce that.

Is good to know what value in fields caused that issue.

**Comment by teosarca** [comment]
@damianprzygodzki  just create a new sales order and play a bit with Date Ordered, Date Promised.
You will see that after u pick a date, for a second the field is displaying our internal format and then it's displayed the right format. But sometimes stays with the internal format and sometimes you get that invalid date.

**Comment by teosarca** [comment]
UPDATE: no i have the same issue in process panel too

![image](https://cloud.githubusercontent.com/assets/1244701/20759510/c6f3d212-b725-11e6-818f-fc01dd86a420.png)

**Comment by damianprzygodzki** [comment]
It looks like the moment can't parse null object. I have to investigate that.

**Comment by teosarca** [comment]
Yes pls. This was broken in the last iteration.
