### ISSUE TITLE
Can't open any process while on Dashboard

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1205]
### Type of issue
Bug 
### Current behavior
can't open any process while on Dashboard
### Expected behavior
process shall open
### Steps to reproduce
1. open https://w101.metasfresh.com:8443/
2. go to navigation
3. start a process (any process). e.g. Initial Setup Wizard
=> nothing happens

**Comment by metas-ts** [comment]
cherry-picked to `release` branch

**Comment by metas-lc** [comment]
IT
repeated the testcase above => works fine
also tried with opening a process from other window or from sitemap => the process starts OK
