### ISSUE TITLE
Use automatic code style enforcement

### ISSUE THREAD

**Issue by PabloSichert** [metasfresh/metasfresh-webui-frontend#1206]
### Type of issue
Feature request

### Current behavior
Files are linted but corrections are not automatically enforced / not fixable with the current configuration of ESLint.

### Expected behavior
Automatically transform code to match the code styling rules. Helps a lot with productivity and consistency: unused variables are removed, lines wider than 80 characters are wrapped, all indentation is done automatically, etc. I'm thinking of configuring this tool https://github.com/prettier/prettier with the existing ESLint config. It's the "JS version of gofmt", if someone's familiar with that.

Interested on what you think about that!

**Comment by teosarca** [comment]
note to IT: pls check the overall stability. e2e would be OK for this task to pass.
