### ISSUE TITLE
Fix after login javascript errors

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1211]
### Type of issue
Bug

### Steps to reproduce
Login and check javascript console:
![image](https://user-images.githubusercontent.com/1244701/30681106-6d340a2a-9eac-11e7-9d64-abc28ea72898.png)

**Comment by PabloSichert** [comment]
That is actually the cause of, and resolved with https://github.com/metasfresh/metasfresh-webui-frontend/issues/1205.

**Comment by teosarca** [comment]
thanks @PabloSichert . 
Then I am moving forward this task....

**Comment by teosarca** [comment]
quick checked and it's OK.
