### ISSUE TITLE
Selection using SHIFT does not work in Handling unit Editor

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1212]
### Type of issue
Bug

### Current behavior
http://docs.metasfresh.org/webui_collection/EN/RecordSelection.html
using SHIFT to select multiple lines does not work for window Handling Unit Editor
it does work in other windows

workaround: use CTRL or the link "select all from page"

### Expected behavior
should work like in any other window

### Steps to reproduce
https://w101.metasfresh.com:8443/window/540189
follow http://docs.metasfresh.org/webui_collection/EN/RecordSelection.html
to select multiple lines

**Comment by teosarca** [comment]
thanks! 
quick tested, works.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

using SHIFT to select multiple lines working in Handling Unit Editor: OK
