### ISSUE TITLE
Included tab actions: error when no line is selected

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1215]
### Type of issue
Bug

### Steps to reproduce
(important to do precisely those steps and navigate as I described)
* go to sales orders grid view, i.e. https://w101.metasfresh.com:8443/window/143
* from that list select an order (hope to have lines and hope that the line ID is not the same as the header ID, by coincidence) and double click it to open it
* pls DO NOT select any order line
* just press the Menu button 
* check the network inspector and javascript console:
** remark that the "actions" endpoint is called for the document header which is OK, e.g. http://localhost:8080/rest/api/window/143/1000013/actions
** remark that the "actions" endpoint is called also for included tab, even though there was NO line selected. But when the endpoint it's called, it's using the header document ID for included document ID, e.g. http://localhost:8080/rest/api/window/143/1000013/1/1000013/actions

![image](https://user-images.githubusercontent.com/1244701/30746822-cb82fbd8-9fb3-11e7-92cb-4e692fdda4d3.png)

### Expected behavior
If there is no line selected the actions endpoint for included document shall not be called.

NOTE:
* this is a follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/982#issuecomment-319711388

**Comment by ottosichert** [comment]
I cannot reproduce this issue with current master a676f2932973d6e63c60b8614bba74a19e8e7b29.

Furthermore both issues seem to be resolved:
1. Go to https://w101.metasfresh.com:8443/window/143
2. (Open dev tools to monitor network requests)
3. Double click line
4. If the selected sales order has no order lines, go to 3.
5. Verify order ID and order line ID are not equal (with react devtools). in my case `1000153` for order ID and `1000186` for order line ID **=> OK**
6. No line selected yet
7. Click menu button
8. See network request to http://w101.metasfresh.com:8081/rest/api/window/143/1000153/actions?disabled=true **=> OK**
9. No other network request to `/actions` **=> OK**
10. Close menu
11. Select order line
12. Click menu button
13. See network request to http://w101.metasfresh.com:8081/rest/api/window/143/1000153/actions?disabled=true&selectedTabId=1&selectedRowIds=1000186 **=> OK**
14. No other network request to `/actions` **=> OK**

**Comment by teosarca** [comment]
yup, i think this was already fixed.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

repeated testcase above, not happening anymore: OK
