### ISSUE TITLE
QtyPicked not updated after picking

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1217]
### Type of issue
Bug 
### Current behavior
QtyPicked is not updated after picking
### Expected behavior
QtyPicked shall be updated correctly
### Steps to reproduce
**Window:** 540345
1. Do picking in modal window (pick any matching HU)
2. QtyPicked in modal window: not updated, still 0: NOK
3. Close modal window, check QtyPicked in main window: not updated, still 0: NOK
4. Refresh window: QtyPicked is updated now
5. Open modal window again: QtyPicked is updated now

**Comment by ottosichert** [comment]
I can reproduce this issue. Re-fetching the data from frontend is not the right way to do it, so could you @teosarca push the websocket messages from backend?

Solution approach:
- Open https://w101.metasfresh.com:8443/window/540345
- [x] websocket connection **(1)** to `/view/540345-fbcaf146e03745a4b7f9c9a665441093` is established
- Select line
- Click quick action **Pick**
- [x] websocket connection **(2)** to `/view/540350-1cb121a3c07d48dbbee380c78aff3bc2` is established
- Click quick action in included view **Open HU selection window**
- [x] websocket connection **(3)** to `/view/pickingSlot-1cb121a3c07d48dbbee380c78aff3bc2-1000002` is established
- Click drop down quick action in included view **Pick HU**
- [x] network requests of quick action are sent
  - `POST http://w101.metasfresh.com:8081/rest/api/process/ADP_540811`
    <details>
      <summary>Request data</summary>

      ```json
      {
        "processId": "ADP_540811",
        "viewId": "540189-bf196a9190e945ca8402e9ec77d07600",
        "viewDocumentIds": [
          "1000543"
        ]
      }
      ```
    </details>
    <details>
      <summary>Response data</summary>

      ```json
      {
        "pinstanceId": "1077084",
        "fieldsByName": {}
      }
      ```
    </details>
  - `GET http://w101.metasfresh.com:8081/rest/api/process/ADP_540811/1077084/start`
    <details>
      <summary>Response data</summary>

      ```json
      {
        "pinstanceId": "1077084",
        "error": false,
        "action": {
          "windowId": "pickingSlot",
          "viewId": "pickingSlot-1cb121a3c07d48dbbee380c78aff3bc2-1000002",
          "viewType": "includedView",
          "type": "openIncludedView"
        }
      }
      ```
    </details>
- [x] websocket connection **(3)** is closed
- [ ] **TODO 1.1**: Send updated `QtyPicked` to websocket **(1)** from backend
- [ ] **TODO 1.2**: Display updated data in frontend (might work already)
- [ ] **TODO 2.1**: Send updated `QtyPicked` to websocket **(2)** from backend
- [ ] **TODO 2.2**: Display updated data in frontend (might work already)

What do you think @teosarca?

**Comment by teosarca** [comment]
hi guys,

will check but this one looks like a pure backend issue.

**Comment by ottosichert** [comment]
I did a quick check and the issue still persists

@teosarca is there a backend issue for this or is there anything left we can do on frontend side?

**Comment by metas-lc** [comment]
created a frontend task; https://github.com/metasfresh/metasfresh-webui-api/issues/810

**Comment by teosarca** [comment]
pure backend issue
