### ISSUE TITLE
Cannot add role for user if password has less than 8 characters

### ISSUE THREAD

**Issue by farens** [metasfresh/metasfresh-webui-frontend#1218]
### Type of issue
Feature request
### Current behavior
If i create a new user with a password less than 8 characters, i won't be able to add the role WebUI to the user and the won't be able to login. The reason for the missing button isn't obvious in the web ui.
![button-for-adding-roles-is-missing](https://user-images.githubusercontent.com/896735/30815414-69c18a06-a213-11e7-8dfa-7ae242ed3c79.png)
### Expected behavior
The web ui should visualize that the entered password is too short/not valid.

**Comment by metas-mk** [comment]
@farens Thanks for the issue description. Good point. We'll do an adjustment to that behavior.

**Comment by teosarca** [comment]
closing this one. shall be solved on backend side. See https://github.com/metasfresh/metasfresh-webui-api/issues/610

**Comment by teosarca** [comment]
update: actually shall be solved by https://github.com/metasfresh/metasfresh/issues/2212, thanks @metasnw
