### ISSUE TITLE
Show mandatory fields not in blue but in red to match user expectation

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1219]
### Type of issue
Feature request

### Current behavior
mandatory fields are displayed in blue

### Expected behavior
user are looking for red marking as they know it from other system and do not recognize the blue color indicating the mandatory field

### Steps to reproduce
1. have sales order with empty price system

**Comment by teosarca** [comment]
reverted, as discussed with @metas-mk
