### ISSUE TITLE
Create Widget Type/ Editor for Location recording

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#122]
Create Widget Type/ Editor for Location recording

- will be called for example in Location Field in Businesspartner Location included Tab.

**Comment by cadavre** [comment]
What are we actually talking about here? Can you provide some screenshot or simple mockup?

**Comment by teosarca** [comment]
See http://w101.metasfresh.com:8081/swagger-ui.html#/address-rest-controller

**Comment by teosarca** [comment]
It's similar with product attributes endpoint

**Comment by damianprzygodzki** [comment]
So we are gonna use the same design, right?

**Comment by teosarca** [comment]
as, talked on skype: yes pls, and the API is quite similar
