### ISSUE TITLE
Handling Unit Editor "Select all rows" missing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1221]
### Type of issue
Bug
### Current behavior
Currently, the "Select all x rows" Button in missing in Handling Unit Editor.
### Expected behavior
Shall work. Please also check the x items selected (shouldn't there be the number of selected items there?)
### Steps to reproduce
Open the Handling Unit Editor. Select all from Page. No Button for "Select all x rows".

![image](https://user-images.githubusercontent.com/13365687/31071371-18183398-a764-11e7-91ca-76819d136406.png)

**Comment by metas-rc** [comment]
Results of IT

* OK: The option " Select x rows"  is available in Hanlding Units editor after pressing Select all on page
* OK: I can switch between the 2 options multiple times without problems
* NOK (detail) : The  option " Select x rows"  shall not be available when there is only 1 page of elements. Followup created:  option " Select x rows"
