### ISSUE TITLE
Keyboard Shortcut for "Select all"/ "Select all x rows"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1222]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, there is no keyboard shortcut in Grid View mode to "select all rows"/ "select all x rows" via keyboard.
#### Which are the steps to reproduce?
Open and try.
### What is the expected or desired behavior?
Implement a shortcut for this (can be the identical one for both because of toggle function). Add tooltip like for other shortcuts.

**Comment by wiadev** [comment]
key: ctrl + a

**Comment by metas-lc** [comment]
IT
go to a grid window. e.g. sales order
use alt+a => all rows for this page are selected OK
use alt+a again => all rows from all pages selected OK

i don't see the tooltip on "Select all on this page" or where it shall be? NOK?

**Comment by teosarca** [comment]
is it supposed to have a tooltip there?
@wiadev  can u pls check it
@metas-mk  wdyt?

**Comment by wiadev** [comment]
@teosarca no, there wasn't a tooltip.

**Comment by metas-lc** [comment]
created follow-up for the tooltip: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1485
