### ISSUE TITLE
Scrollbar missing in Handling Unit Editor after "Internal Usage Action"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1223]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Scrollbar vanishes in Handling Unit after the usage of Quickaction "Internal Usage".
#### Which are the steps to reproduce?
Open the Handling Unit Editor. Select a line. Open Quick action dropdown. Select Materialentnahme/ Internal Usage. Scrollbar disappears.
### What is the expected or desired behavior?
The scrollbar shall remain.

![image](https://user-images.githubusercontent.com/13365687/31073725-5cf6da10-a76d-11e7-9ffb-2f3de2ecc4de.png)

**Comment by PabloSichert** [comment]
I can't find an entry where `Materialentnahme` is not grayed out. Could you tell me which one I need to click? It says `Nur mit oberste HU-Ebene`, but that doesn't seem to be working. Is that a bug?

**Comment by metas-mk** [comment]
@PabloSichert sry, there was a step missing in description above.
after opening the Handling Unit Editor, please filter the entries by "Active" Packing status first.
![image](https://user-images.githubusercontent.com/13365687/31480171-903d012c-af1c-11e7-9694-866a91f92a39.png)
Only active Handling Unity will now be shown.

After that select one of the lines, open the Quickaction dropdown. Then "Materialentnahme" (Internal Usage) shall be shown.
![image](https://user-images.githubusercontent.com/13365687/31480223-e48ff658-af1c-11e7-846a-a914ed2ab3f9.png)

**Comment by PabloSichert** [comment]
Apparently this calls e.g. http://w101.metasfresh.com:8081/rest/api/process/ADP_540541/1036589/start, and the backend returns `500`. Do you have some insight into this error, @teosarca?

**Comment by teosarca** [comment]
@PabloSichert  i think it does not matter.
The thing is, for some reason the process/action fails.
But the frontend shall recover nicely, i.e. don't take my scrollbars away! :((
:)

**Comment by PabloSichert** [comment]
That, that would generally be a nice thing 😄

**Comment by metas-lc** [comment]
IT
checked without warehouse config => Materialentnahme throws error => the scrollbar is still there OK
checked with warehouse config => Materialentnahme works => the scrollbar is still there OK
