### ISSUE TITLE
HUs from issue are not updated

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1225]
### Is this a bug or feature request?
bug
### What is the current behavior?
HUs from issue are not updated when you issue a TU from an LU
#### Which are the steps to reproduce?
1. create a new sales order with product "Radiesli" on at least 2 TUs, or use this one: https://w101.metasfresh.com:8443/window/181/1000040 and go directly to step 2
2. go to reference documents (ctrl 6) and select Material Receipt Candidates
3. select the line choose the action: Receive CU with Qty
4. set qty 20, start
5. select the CU line and use transform:
6. Aktion "CU on new TUs", packvorschrift: G2, Menge CU 20, START
7.  select 1 TU and use transform: Aktion "TU on new LU", packvorschrift: palette, Menge TU 1, START
8.  select the 2nd TU and use transform: Aktion "TU on existing LU", LU: palette, Menge TU 1, START
9. select your LU and create material receipt
10. go to Manufacturing Order and create a new one, or use https://w101.metasfresh.com:8443/window/53009/1000006 (you have to be in gridview: https://w101.metasfresh.com:8443/window/53009)
11. select action Issue/Receipt
12. select the line with Radiesli, then select action Issue
13. select 1 TU from the LU and press on issue HUs:

![issue1](https://user-images.githubusercontent.com/16001666/31077918-fb16875c-a788-11e7-92c0-3783fdf126af.png)
 
=> NOK: the right part doesn't update (TU is still there)
![issue2](https://user-images.githubusercontent.com/16001666/31077983-26bb75de-a789-11e7-93dc-723d583c1557.png)

### What is the expected or desired behavior?
left part shall update: the TU shall not be there anymore

**Comment by ottosichert** [comment]
I could not reproduce this issue on step 9. no matter if i try to **Create material receipt** with `LU`s, `TU`s or `CU`s:
> <details open>
>  <summary>Error Processing Document</summary>
>
> document: Produktanlieferung 1000030
> Belegverarbeitung: CO
> Cause: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
> Bitte leiten Sie diese Meldung an metas weiter:
>
> Error: Unable to convert from currency € (purchase order 820477) to currency $ (accounting schema UN / USD),  (AdempiereException)
> </details>
I tried setting the language to `Deutsch (DE)` and `English (US)` but with both languages the problem persists.

@teosarca do you know if there was any change in the backend regarding **Create material receipt**?

**Comment by teosarca** [comment]
@ottosichert  @metas-lc  AFAIR that's no longer possible. If u want to partially issue a TU from an LU, you need to use "Issue included TUs" action.

Moving the task back to Test.

**Comment by metas-lc** [comment]
IT
checked the testcase again. Since "Issue included TUs" change, it works fine. Both left and right side are updated OK
