### ISSUE TITLE
The Letter window dissapears after Print Preview

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1227]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* If I select print preview for a letter I can see how the pdf looks like. But after I close the print preview, the letter also closes and it is lost.
#### Which are the steps to reproduce?
* Create a letter  for a sales order
* write some text in it
* print preview
* close print preview
* => NOK: THe window with the letter also closes.
### What is the expected or desired behavior?
* The letter window shall stay open after the print preview is closed.

**Comment by metas-lc** [comment]
IT

1. open a sales order, go to actions, select letter
=> modal for writing a letter opens 
2. write some text in it
3. print preview
=> you get a pdf in a new tab with the letter
4. close print preview
=> OK: The modal window with the letter is still open
