### ISSUE TITLE
Provide session ID cookie when calling /availableLanguages

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#123]
When calling /availableLanguages endpoint please also provide the session ID cookie because else you are asking the server to create a new session each time.

![image](https://cloud.githubusercontent.com/assets/1244701/20762936/cec0a56e-b730-11e6-8ee0-8c46cf194eca.png)

**Comment by teosarca** [comment]
Also, pls tell me when this endpoint is called?

**Comment by damianprzygodzki** [comment]
@teosarca I am fetching available lang each time success login. Shouldn't i ?

Available lang endpoint is creating new session?

**Comment by teosarca** [comment]
You are calling this endpoint from time to time, not only on login.
So i would suggest, if u have the SESSION ID, just provide it to avoid creating new short living sessions.

> I remember that you said, that this endpoint is out of login scope, and i can use that without session.

True, you can call that endpoint whenever you are logged or not, or you have a session or not.
But the session is created first time when u call the API and not after login.

**Comment by damianprzygodzki** [comment]
> You are calling this endpoint from time to time, not only on login.

Not from time to time, it is fetching on app init - it has to be done when everything is setting up, for example locale in momentjs.

And what i see, the `/login/availableLanguages` is called as first thing at all! So there is no possibility to set session id.

`/userSession/language` is called after login to set lang that we have in user settings.
