### ISSUE TITLE
Labels widget: keyboard support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1232]
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1138

### Is this a bug or feature request?
FR

### What is the current behavior?
The Labels widget does not support keyboard navigation.

#### Which are the steps to reproduce?
open Business Partner window and check.

### What is the expected or desired behavior?
* pressing DOWN key shall let me navigate the list.
* pressing BACKSPACE is deleting the last label => OK
* nice to have: pressing LEFT / RIGHT would be nice to navigate between labels and then pressing BACKSPACE i would delete the one i want.
* pressing TAB shall take me to next field. pressing shift-TAB shall take be to previous field
* when having the cursor in previous field (i.e. VAT ID), pressing tab shall take me to this labels field.

NOTE: our users are have keyboard users, so working entirely with the keyboard it's a must.

![image](https://user-images.githubusercontent.com/1244701/31203338-566a6c44-a96f-11e7-8996-26577d7891f2.png)

**Comment by PabloSichert** [comment]
Note: `TAB/SHIFT-TAB` and `LEFT/RIGHT` navigation is not implemented yet.

**Comment by teosarca** [comment]
Ok. Then i would prefer to create a follow-up of this task, because this one is already in release notes and in release branch.

**Comment by metas-lc** [comment]
IT
1. up and down key lets me navigate. OK
2. backspace lets me remove the attributes i set. OK
3. "nice to have: pressing LEFT / RIGHT would be nice to navigate between labels and then pressing BACKSPACE i would delete the one i want." not working atm. OK??
4. "pressing TAB shall take me to next field. pressing shift-TAB shall take be to previous field" - will be implemented in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1266
5. " when having the cursor in previous field (i.e. VAT ID), pressing tab shall take me to this labels field." - i have to press TAB multiple times to get there. OK??
