### ISSUE TITLE
Included views are not working in non-modal windows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1239]
### Is this a bug or feature request?
Bug

### Which are the steps to reproduce?
* Open picking slots window: http://localhost:3000/window/540206
* click on some line
=> NOK: nothing happens.

### What is the expected or desired behavior?
It shall open the included view because:

* layout says so:
![image](https://user-images.githubusercontent.com/1244701/31280900-919d7e62-aab6-11e7-95c7-12884813b181.png)

* retrieved rows have the includedView property set:
![image](https://user-images.githubusercontent.com/1244701/31280972-c3633392-aab6-11e7-94e6-a2edbdb6761c.png)

### Modal version, for comparison
![image](https://user-images.githubusercontent.com/1244701/31281083-1679ff34-aab7-11e7-8235-6a3940f70dbc.png)

![image](https://user-images.githubusercontent.com/1244701/31281160-55f34f9e-aab7-11e7-8c55-b9751ae1fff1.png)

**Comment by teosarca** [comment]
required for https://github.com/metasfresh/metasfresh/issues/518

**Comment by ottosichert** [comment]
I created a PR for this (https://github.com/metasfresh/metasfresh-webui-frontend/pull/1241). Looks like it didn't work because it was never implemented for non-modals.

The code for the `includedView` `DocumentList` is mostly repeated in modals and non-modals, so maybe a refactoring of `includedView` into `DocumentList` itself could be the next step.

**Note**: As this PR changes the behaviour of the `Table` and `DocumentList` component (thus most views in WebUI) I recommend thorough testing

**Comment by teosarca** [comment]
Hi @ottosichert . Thanks for the quick fix.
I've integrated the task but i would like to ask u to fix following layout issue:

![image](https://user-images.githubusercontent.com/1244701/31329553-608e51dc-ace3-11e7-984a-9fafd04f8238.png)


basically it shall look like the modal one:
![image](https://user-images.githubusercontent.com/1244701/31329579-7aa06038-ace3-11e7-8291-f96fed691ce4.png)

**Comment by ottosichert** [comment]
@teosarca I will submit a second PR this evening (german time) fixing the layout issue. Can you tell me how I can open the modal view so I can compare the results?

**Comment by teosarca** [comment]
@ottosichert 

>  I will submit a second PR this evening (german time) fixing the layout issue. 

danke

> Can you tell me how I can open the modal view so I can compare the results?

now shall be available on w101

**Comment by ottosichert** [comment]
@teosarca See the PR #1245

I can not find the `Browse picking slots` button on w101 (https://w101.metasfresh.com:8443/window/540206?viewId=540206-3c8d679a206c4e4f8553756ecae616f7&page=1) or on master, do you know why? I logged in as user `metasfresh`

**Comment by teosarca** [comment]
@ottosichert  

about the button... it might be that user has no privileges to that action.
But i think it's not so important... (in meantime i've already deleted that action because we don't need it).
The layout shall just be divided in half and have the attributes panel hidden.
I think you already did that on PR https://github.com/metasfresh/metasfresh-webui-frontend/pull/1245 .
But before i can integrate it can u pls check and resolve the conflict on DocList.js file.

Thanks.

**Comment by ottosichert** [comment]
@teosarca I resolved the merge conflict in #1245 and rebased the branch with master

**Comment by teosarca** [comment]
thanks, integrated

**Comment by metas-rc** [comment]
Results of IT

* I went to Picking Tray window and clicked on one line there.
* OK: The included view was opened
* Then I clicked the home button and got to another window (e.g. Request)
* NOK: The included view from the picking remains open.

**Comment by metas-rc** [comment]
![image](https://user-images.githubusercontent.com/16001442/31494207-f61ba4ba-af5a-11e7-8dfa-703edf9c5542.png)


![image](https://user-images.githubusercontent.com/16001442/31494222-05f05980-af5b-11e7-982e-8152035a05ba.png)



![image](https://user-images.githubusercontent.com/16001442/31494240-163d165c-af5b-11e7-93ff-9a470be00fbe.png)

**Comment by metas-rc** [comment]
Results of IT

* OK: Now the included view dissapears when I open another menu entry.
