### ISSUE TITLE
included view: wrong selectedIds when calling quickActions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1248]
### Is this a bug or feature request?
bug

### Which are the steps to reproduce?
* open Picking Tray window: https://w101.metasfresh.com:8443/window/540206
* select a row and remark the quickActions call
![image](https://user-images.githubusercontent.com/1244701/31437008-78714e8a-ae8c-11e7-8337-fd757151f722.png)

### What is the expected or desired behavior?
quickActions shall be called using the selectedIds of it's corresponding view and not the other one.
In the example above the quickActions from right side view was called using the selectedIds of the left side view.

Required for https://github.com/metasfresh/metasfresh/issues/518

**Comment by PabloSichert** [comment]
How can I create entries for the right side? Do you have a link where the right side is populated?

**Comment by ottosichert** [comment]
**Note**: This feature was implemented for #1239 by PRs #1241, #1244 and #1245.
There is no information about the right side though in this issue / PRs

**Comment by PabloSichert** [comment]
Do you want to take that issue, since it's related to your recent changes?

If so, just assign yourself 😄

**Comment by metas-lc** [comment]
IT
the new window is 540371
after "afterPickingHUs" we have "quick actions" for the ones in dropdown. "quickactions?slectedIDs"didn't appear anymore OK
