### ISSUE TITLE
Add new Business Partner functionality in search Field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#126]
New Business Partner functionality in search field
- User will type the name to be searched. Autocomplete jumps in and shows the found data. Show a button at the bottom of dropdown (suggestion) which allows to record a new Busines Partner + Location + User (could be a modal popup with all neeeded data in 1 widget)
- What we could do too is to take what the user already recorded for search and show the button with the string in search and concatenated "(new Business Partner)"

![image](https://cloud.githubusercontent.com/assets/13365687/20827024/59219562-b86f-11e6-8600-bec6dae07a71.png)

**Comment by damianprzygodzki** [comment]
@teosarca here we need to get the windowType for property that we want to add. So for example here we need in widgetData despite the name of the field (B_Partner_CI), the windowType of that field (126)

**Comment by damianprzygodzki** [comment]
To be more precise - it is already implemented but lack of windowType in fields objects from API is blocking functionality.

**Comment by damianprzygodzki** [comment]
It can be in layout, but when i am fetching layout you have already document type.

**Comment by teosarca** [comment]
just to be clear: i am talking about to provide the "windowType" somewhere in element/field layout and NOT about providing the whole layout for "new bpartner" there...

**Comment by metas-mk** [comment]
talked to @teosarca about first (quick) solution
* in the search box "new ..." shall open the generic window belonging to the main field ID. Ger for example will be the BPartner_ID Field and then new will open the BPartner window. For Product_ID Field, the "new ..." will open the Product Window
* window shall be opened in modal overlay
* after pressing done, the new _ID shall be transferred back into the initial search field.

**Comment by teosarca** [comment]
Hi guys,
In element field layout i've introduced 2 new fields:
* newRecordWindowId
* newRecordCaption

If newRecordWindowId is present, the frontend shall display the "newRecordCaption" in lookup dropdown.
When the "new record" option is clicked, the frontend shall open the modal window identified by newRecordWindowId and a new record shall be ready to be filled in by the user.

When user presses Done, the frontend shall use the ID of the new record and it shall patch the field from were we are coming form.
Don't bother about sending "{ key : name }" format. The backend shall accept the ID as is and shall automatically convert it to "{ key : name }" which will be available in response.


![image](https://cloud.githubusercontent.com/assets/1244701/23473406/cf0bb2be-feb8-11e6-9a95-cad29141183f.png)

**Comment by metas-mk** [comment]
@teosarca here the fields we need in that bpartner-create overlay
Name
Name 2
isCompany Y/N
Company Name
BPartner Group
Language

isCustomer
Paymentterm
Pricesystem

isVendor Y/N
PO Paymentterm
PO Pricesystem

Firstname
Lastname
eMail
Phone No.

Location Editor Button OR
Address 1-4
Postal
City
Country ...

**Comment by teosarca** [comment]
Update: backend is ready

The only thing that changed for frontend is: after user edited the fields in new modal window, when he is pressing Done, the frontend shall call http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/processRecordUsingGET .

That endpoint will actually create the required record and it will return it's ID.
Using that ID, you have to patch the field from initial document.

**Comment by metasnw** [comment]
@teosarca 
will it be possible to configure which fields are displayed?
I am asking because e.g. vendor fields would not be needed
I am just asking ;-)

**Comment by teosarca** [comment]
@metasnw yes, underthehood it's just a regular window using a new table name.
For BPartner case (the only one atm) we introduced C_BPartner_QuickInput table.
There the user input is captured and when done, a new BPartner/Location/Contact is created based on that.
Ofc, if you want to customize some field, the field shall be there and shall be supported.
Btw, in meantime @metas-mk is taking care of the layout, here: https://github.com/metasfresh/metasfresh/issues/1113

**Comment by teosarca** [comment]
@damianprzygodzki  removed the Name field. shall work now

**Comment by metas-mk** [comment]
Tested. Works as currently required. Closing.
