### ISSUE TITLE
Row not selected and no actions after closing the modal view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1263]
### Which are the steps to reproduce?
* open picking terminal: https://w101.metasfresh.com:8443/window/540345
* make sure a row is selected (e.g. first one) and call "Pick" action
* => the modal is opened
* close the modal and remark: previously selected row is no longer selected

See:
![image](https://user-images.githubusercontent.com/1244701/31612784-9bd7c448-b289-11e7-8035-88c08aa771f5.png)

There are to quickActions calls:
1. http://localhost:8080/rest/api/documentView/540345/540345-3d89b700e6974ceea1dbb44d0ce6ef32/quickActions
2. http://localhost:8080/rest/api/documentView/540350/540350-a1efd47ecb3e4d728b5d1f5a6fd43cf6/quickActions?selectedIds=1000000

The first one has the correct WindowId but it has no selection because there is no row selected.
The second one is for the modal view we just closed. That one shall not be called.

### What is the expected or desired behavior?
After closing the modal view, previous selected row or rows shall be preserved.
Correct actions for current selection shall be displayed.

**Comment by ottosichert** [comment]
This will conflict with https://github.com/metasfresh/metasfresh-webui-frontend/pull/1264, so I will wait until it is reviewed and merged

**Comment by metas-lc** [comment]
IT
1. go to picking terminal: https://mf15cloudit/window/540345?page=1&viewId=540345-9c1fc7e4e85b49bf8bc8d5e4218d4ab8
2. select a line, pick
3. don't do anything, just press done
=> your line is still selected OK 
=> but quickactions don't appear in Network NOK 
![picking_no_quickactions](https://user-images.githubusercontent.com/16001666/31819944-9ea5cd20-b5a7-11e7-8f14-6da40812ab39.png)
4. select the other line, and select your line again 
=> quickactions appear OK
![picking_quickactions](https://user-images.githubusercontent.com/16001666/31819977-c28c93b8-b5a7-11e7-8fe6-ee444312b47f.png)

we want step 3 to have quickaktions shown like in step 4 (for the selected line)

**Comment by teosarca** [comment]
i.e. after closing the modal we have to re-query the quick actions because they might be changed.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

repeated testcase from IT above:
* previous selected row is preserved after closing modal view: OK
* correct actions are displayed for the selected line: OK
