### ISSUE TITLE
Labels widget: tab and shift-tab support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1266]
Follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1232.

In this task we shall implement the TAB and SHIFT-TAB support as described in #1232.

**Comment by metas-lc** [comment]
please also implement:
- "nice to have: pressing LEFT / RIGHT would be nice to navigate between labels and then pressing BACKSPACE i would delete the one i want." 
- " when having the cursor in previous field (i.e. VAT ID), pressing tab shall take me to this labels field." - i have to press TAB multiple times to get there.

**Comment by siemiatj** [comment]
Related to #1617

**Comment by metas-lc** [comment]
IT
1. pressing LEFT / RIGHT => navigates between labels OK
2. pressing BACKSPACE => deletes the one i want OK
3.  have the cursor in previous field (i.e. VAT ID), press tab => i get to labels field. OK
.
4. if i am in label fields, select a label and press enter multiple times, that label is set again, each time NOK
follow-up: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1832
