### ISSUE TITLE
Grid view in Material Dispostion shows 0E-16 instead of 0

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1267]
### Is this a bug or feature request?
FR?
### What is the current behavior?
Data for stock demand / supply in a warehouse, in material disposition, shows qty: 0E-16 in grid view, in single view it's 0. 0E-16 is basically correct, but confusing for the user.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Grid view should show 0 as well, like single view.

**Comment by ottosichert** [comment]
@metas-dh Can you give us a link to to a view with this issue?

**Comment by metas-dh** [comment]
@ottosichert: i can't give you the link to my testcase since i tested on customer's db; i hope pics will do:


![2017-10-18 16_33_15-metasfresh](https://user-images.githubusercontent.com/18696715/31725044-a86aaaae-b423-11e7-9d99-8ff4aace9baa.png)

![2017-10-18 16_34_00-metasfresh](https://user-images.githubusercontent.com/18696715/31725054-aefb0fb2-b423-11e7-993a-8c8b67d1a918.png)

**Comment by teosarca** [comment]
@metas-dh  @ottosichert  i think it's backend (have to check) because AFAIR in views, the frontend is showing the numbers as it gets them.

**Comment by ottosichert** [comment]
@teosarca you are right:
![bildschirmfoto vom 2017-10-18 18-35-16](https://user-images.githubusercontent.com/1255508/31730734-2109fffa-b433-11e7-821a-61559870600a.png)

@metas-dh the exact link is not needed, in this case `/window/540334` is sufficient. Or you always can navigate to this window on https://w101.metasfresh.com:8443/ and then paste the full link here

**Comment by ottosichert** [comment]
@teosarca should we handle this case in frontend or fix the error in backend?

**Comment by siemiatj** [comment]
@teosarca is it still relevant ? I don't see 0E-16 anywhere.

**Comment by metas-dh** [comment]
@teosarca no, have not seen this for a while; closing the issue.
