### ISSUE TITLE
Add new Product functionality in search Field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#127]
Add new Product functionality in search Field
- User will type the Product to be searched. For example in Quickentry Form. Autocomplete jumps in and shows the found data. Show a button at the bottom of dropdown (suggestion) which allows to record a new Product and Packing Material combination (could be a modal popup with all needed data in 1 widget)
- What we could do too is to take what the user already recorded for search and show the button with the string in search and concatenated "(new Product)"

**Comment by damianprzygodzki** [comment]
Im closing this, because case is the same. #126
