### ISSUE TITLE
Edit Fields in Main Grid View Improvements

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1274]
### Is this a bug or feature request?
bug
### What is the current behavior?
when editing a field in gridview too fast, you get in doc view
"Edit field value" is not translatable
#### Which are the steps to reproduce?
1. go to product prices https://w101.metasfresh.com:8443/window/540325?viewId=540325-15af6474154241b7bde70a5020b8f43d&page=1
2. press on "Edit field value" on a random price field (btw this is currently not working on w101 so it can be fixed here)
=> editing component opens
3. use up or down error with the mouse, multiple times
=> document view opens NOK
4. switch to de_DE language, right click on a price field 
=> still in en NOK 
### What is the expected or desired behavior?
Docview should not open if you click on up/down arrows on "Edit field value"
"Edit field value" should be translatable
step 2 used to work and it seems to be broke now. It should open the editing component

**Comment by teosarca** [comment]
shall be fixed in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1358
