### ISSUE TITLE
Scrolling in Modal window throws errors

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1275]
### Is this a bug or feature request?
Bug

### Which are the steps to reproduce?
* create a new sales order or use https://w101.metasfresh.com:8443/window/143/1000045
* add a new order line
* when the modal is displayed drag the scroll bar up and down and you will get:
```
Uncaught TypeError: Cannot read property 'scrollTop' of undefined
    at HTMLDivElement.value (Modal.js:232)
```
![image](https://user-images.githubusercontent.com/1244701/31725548-4ca9e720-b42d-11e7-8f30-b97fd2edd657.png)

![image](https://user-images.githubusercontent.com/1244701/31725600-69cf81b6-b42d-11e7-82c6-724c34c1454a.png)

**Comment by metas-lc** [comment]
IT
dragged the scroll bar up and down = > no errors OK
