### ISSUE TITLE
Shortcuts for New, Batch and Expand are broken

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1278]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Shortcuts for are broken
#### Which are the steps to reproduce?
Create a new Sales Order, type Customer, Select Location and Contact. Callouts kick in. Press [ctrl]+space (expand) or [ctrl]+q (batch) or other lines new. Nothing happens.
### What is the expected or desired behavior?
Please Fix.

**Comment by metas-lc** [comment]
IT
ctrl+q - opens batch OK
ctrl+apace - expands lines OK
ctrl+m - new order OK
