### ISSUE TITLE
menu actions for included row broken

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1279]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* open a Price List, e.g. https://w101.metasfresh.com:8443/window/540321/2001003
* select a row in the included tab (Preislisten Version)
* press on the Action Menu
=> NOK actions are not displayed for the included row

### What is the expected or desired behavior?
Shall work as it was implemented in https://github.com/metasfresh/metasfresh-webui-frontend/issues/982 .

i.e.
![image](https://user-images.githubusercontent.com/1244701/31767487-f6a5713a-b4d3-11e7-9c82-fec340314b79.png)

See
* header document actions: http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_1
* included row actions: http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_2

In the example above, this one should be also called: http://w101.metasfresh.com:8081/rest/api/window/540321/2001003/1/2000749/actions

**Comment by teosarca** [comment]
@PabloSichert  thx for PR.
While quick reviewing/testing i saw following UI mini-issue:
![image](https://user-images.githubusercontent.com/1244701/32430050-1daa50a6-c2d6-11e7-915c-ae842c357226.png)


Would it be possible to hide the separator line between header actions and child actions when one of the groups are missing?

**Comment by PabloSichert** [comment]
@teosarca it was supposed to do that, but I made a mistake - fixed with https://github.com/metasfresh/metasfresh-webui-frontend/commit/30a13272b836458e7e3ea6e6099afde945032975 😄

**Comment by teosarca** [comment]
10x, integrated

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15, sp80

menu actions for included row displayed in Action Menu:
* Price List and included tab Preislistenversion: menu actions for included tab are displayed when row in Preislistenversion is selected: OK
* Product and included tab Zugeordnetes Produkt: menu actions for main window and the included tab are  displayed when row in Zugeordnetes Produkt is selected: OK
* separator line between header actions and child actions is hidden when one of them is missing: OK
