### ISSUE TITLE
Date widget not correctly loaded from event

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#128]
Test case:
* have a completed sales order
* try to reactivate
* the date fields like DateOrdered becomes null => NOK

reason/suggestion to fix: when loading the widget from event, don't touch the value if the value was not provided! (IMPORANT: value=null it's a different case).
See screenshot...

![image](https://cloud.githubusercontent.com/assets/1244701/20860507/68578aaa-b982-11e6-815b-aab5fd460e90.png)

**Comment by damianprzygodzki** [comment]
It is really old issue that we talked about it. There is no possibility to have widget without value.

**Comment by cadavre** [comment]
Summary: it's not about *changing* widgets `value` param. It's about a change that was made on other param – here: `readonly` (from `true` to `false`).

**Comment by teosarca** [comment]
exactly, as I said:

> reason/suggestion to fix: when loading the widget from event, don't touch the value if the value was not provided! (IMPORANT: value=null it's a different case).

**Comment by teosarca** [comment]
update: did a quick test, WORKS!

thanks guys!
