### ISSUE TITLE
Translations of Photo Widget in User Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1281]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Translations of photo widget are not taken from messages.
#### Which are the steps to reproduce?
Open the User/ Avatar Window Settings. Switch Language to de_DE. The Photo Widget Buttons remain untranslated.
### What is the expected or desired behavior?
Shall be Translated

![image](https://user-images.githubusercontent.com/13365687/31772521-43bc856a-b4e0-11e7-9cb1-5c3a955f88c9.png)

![image](https://user-images.githubusercontent.com/13365687/31772594-7fdcf124-b4e0-11e7-99e4-5f569a357ea4.png)

**Comment by metas-lc** [comment]
IT
logged in with de_De, opened user => fields from Avatar are translated OK
