### ISSUE TITLE
Revise shortcut handling

### ISSUE THREAD

**Issue by PabloSichert** [metasfresh/metasfresh-webui-frontend#1283]
### Is this a bug or feature request?

Code restructuring

### What is the current behavior?

Shortcuts somehow work and break sometimes

#### Which are the steps to reproduce?

Use any shortcut in the application

### What is the expected or desired behavior?

Shortcuts should work reliably all the time

https://github.com/metasfresh/metasfresh-webui-frontend/commit/992d2324f2e08a4120a95f70bb9bf830e356c343 fixed an issue by setting some `global` prop. Although ideally, there should be a straightforward hierarchy of shortcut handlers, without needing to (seemingly randomly) set props and globally overwrite each other.

### Note to IT
* when testing shortcuts like CTRL+1,2,3 etc pls make sure you have more tabs opened because chrome is also binding those shortcuts for "go to first tab", "go to second tab" etc.

**Comment by metas-ts** [comment]
cherry-picked to `2017-11`

**Comment by teosarca** [comment]
quick checked and found several problems. will document them below.
-----
application crashes:
![image](https://user-images.githubusercontent.com/1244701/32895344-65f84722-cae8-11e7-99e2-0fafca560106.png)

![image](https://user-images.githubusercontent.com/1244701/32895375-81566314-cae8-11e7-943b-e6ed9d7a2b71.png)

**Comment by teosarca** [comment]
another issue: CTRL+1,2,3... shortcuts are working very wierd, i.e.
* sometimes they are not working (might be because it depends on which compenent has the focus?)
* pressing CTRL+1 and then pressing CTRL+1 again will lead you to first browser tab. Same, CTRL+2 will lead you to second tab etc

**Comment by PabloSichert** [comment]
@teosarca reason for that second behavior was, that I reset the whole "key combo" when one key was going up: https://github.com/metasfresh/metasfresh-webui-frontend/blob/5c194e4af4b344c912b5aeaf49e107a373a86848/src/components/Shortcuts/ShortcutProvider.js#L74-L77

What happened:

1. Hit `CTRL` // Combo is `[CTRL]`
2. Hit `1` // Combo is `[CTRL, 1]` - `CTRL+1` fires
3. Release `1` // Combo is `[]`
4. Hit `2` // Combo is `[2]` - No combo for `2`

What should have happened:

1. Hit `CTRL` // Combo is `[CTRL]`
2. Hit `1` // Combo is `[CTRL, 1]` - `CTRL+1` fires
3. Release `1` // Combo is `[CTRL]`
4. Hit `2` // Combo is `[CTRL, 2]` - `CTRL+2` fires

Going to fix that

**Comment by PabloSichert** [comment]
There shouldn't be any focus issues any more, since all hotkeys are handled from one place and all listeners are registered on the top level `document` element

**Comment by teosarca** [comment]
note to IT: all shortcuts where changed from CTRL+ to ALT+.

**Comment by teosarca** [comment]
it seems that some shortcuts are duplicated. see below (javascript console).
thanks @wiadev  for reporting it.

![image](https://user-images.githubusercontent.com/1244701/33116689-5c7c535c-cf6e-11e7-8dba-791d6aab3c94.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

checked shortcuts from here: http://docs.metasfresh.org/webui_collection/EN/Keyboard_shortcuts_reference.html

* select all rows: now [alt]+a: OK
* Letter, [alt]+r: not working, Handler defined for key sequence "ALT+R" is not a function. 
* Clone, [alt]+rw not working, Handler defined for key sequence "ALT+W" is not a function.

=> follow-up: #1410
