### ISSUE TITLE
viewDocumentIds not set when running a process from view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1292]
### Is this a bug or feature request?
bug

### Which are the steps to reproduce?
* open billing candidates: https://w101.metasfresh.com:8443/window/540092
* select some rows 
* run "generate invoices" process
* NOK: process throws "No Selection" because when the "POST /process/<processId>" endpoint was called, the viewDocumentIds were not filled
![image](https://user-images.githubusercontent.com/1244701/31889176-7ff56e78-b807-11e7-8791-0281443134a1.png)

### What is the expected or desired behavior?
"viewDocumentIds" shall be populated with all selected row ids.
If ALL rows from all pages are selected, the viewDocumentIds shall have one item called "all".

**Comment by metas-ts** [comment]
I just integrated PR #1300 into master
@metas-mk @metasnw @teosarca please consider @PabloSichert 's question from the [PR description](https://github.com/metasfresh/metasfresh-webui-frontend/pull/1300#issue-268555207)

> Follow-up question: Does the creation of a process always depend on what is selected on the parent window and never accounts for what is selected in the modal itself?

I would say "yes" for the 3-dots-menu, and "dunno, maybe" for the rest..

**Comment by teosarca** [comment]
@PabloSichert the viewDocumentIds  shall be the selected IDs of the view where u are in now.
If the action is in the modal window, included view (e.g. right side) the viewDocumentIds  shall be of the included view (right side).
If the action is in the modal window, main view (e.g. left side or whole modal screen) the viewDocumentIds  shall be of the main view (left side).

Btw, @PabloSichert , if u have doubts pls ping me and i can explain it verbally.

**Comment by metas-ts** [comment]
@PabloSichert @ottosichert 
hi guys, we are lucky that you did this issue on short notice in the middle of the night, 
but pleease remember to always reference the respective issue in your commits :-)
otherwise we can run into problems with the cherry-picking

**Comment by PabloSichert** [comment]
@metas-ts I assumed you only want to have the commits tagged when it's a hotfix.

Should we reference its respective issue from every commit?

**Comment by PabloSichert** [comment]
@teosarca Ok, makes sense. The code for creating a process looked a bit like the selection always comes from the main view.

Would it be possible to get a list of cases (where the selection is on the main view, and where the selection is in a modal for example) along with their URLs so I can review them?

**Comment by teosarca** [comment]
@PabloSichert  

* main view: Handling units window - https://w101.metasfresh.com:8443/window/540189
![image](https://user-images.githubusercontent.com/1244701/32142538-ef7f6de0-bca1-11e7-8d5e-bf1d03b517e5.png)

* modal with main view: Manufacturing order - https://w101.metasfresh.com:8443/window/53009 select a line and press Issue/Receipt
![image](https://user-images.githubusercontent.com/1244701/32142549-454640f0-bca2-11e7-8d6c-75ed12ab7065.png)


* modal included view: https://w101.metasfresh.com:8443/window/540345, select a line and press Pick
![image](https://user-images.githubusercontent.com/1244701/32142560-798af914-bca2-11e7-8af2-fd5bb9983ab2.png)



* non-modal included view:  https://w101.metasfresh.com:8443/window/540371
![image](https://user-images.githubusercontent.com/1244701/32142565-960a23e4-bca2-11e7-89af-c19bfce3706a.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

checked all cases above: viewDocumentIds are the selected IDs of the view where user is in: OK
