### ISSUE TITLE
Cannot scroll down in a filter with lots of parameters

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1293]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you open a filter with lots of parameters, you cannot scroll down to the Apply button, you have to use tab.
#### Which are the steps to reproduce?
1. Open e.g. invoice candidates, https://w101.metasfresh.com:8443/window/540092?
2. Click Filter, Default
3. Try scrolling down to the Apply button: not working, NOK
### What is the expected or desired behavior?
Please add a scroll bar to the Filter dropdown for the cases when it gets longer than the screen size.
![image](https://user-images.githubusercontent.com/13365687/32943921-07fe9616-cb8e-11e7-93e0-b666699aa257.png)

**Comment by teosarca** [comment]
@metas-dh  @metas-lc @wiadev   while doing other stuffs i've stumbled on this issue and I observed there is an flickering effect if u keep ur mouse on the apply button, i.e. the scrollbar appears and disappears on an on.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 & weekly e2e

* scrolling down in a filter with lots of parameters works: OK

>while doing other stuffs i've stumbled on this issue and I observed there is an flickering effect if u keep ur mouse on the apply button, i.e. the scrollbar appears and disappears on an on.

@teosarca i noticed that too sometimes, do we have an issue for that?
