### ISSUE TITLE
window actions shall respect the "disabled" flag

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1294]
### Is this a bug or feature request?
FR

### What is the current behavior?
When calling for window actions (e.g. http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_1 ), 
the "disabled" flag is not respected.

#### Which are the steps to reproduce?
check for example 

### What is the expected or desired behavior?
if an action is disabled,
* it shall be grayed out
* the disabledReason (if available) shall be displayed beneath

![image](https://user-images.githubusercontent.com/1244701/31898995-2a22b020-b823-11e7-9b1f-f4cf2cc32938.png)

**Comment by teosarca** [comment]
note to dev: it might be that the disabled processes are not returned by /actions endpoint.
See https://github.com/metasfresh/metasfresh-webui-api/issues/644

**Comment by ottosichert** [comment]
@teosarca I saw your comment on https://github.com/metasfresh/metasfresh-webui-api/issues/644#issuecomment-338713218 and it confused me a little bit.

In the view https://w101.metasfresh.com:8443/window/143/<insert_id> there are no actions with a `disabled` and `disabledReason` property as you stated in your comment that these actions will not be returned at all.

Are there any views left with `disabled` actions?

**Comment by teosarca** [comment]
@ottosichert  yes they are, but u need to call the /actions endpoint using disabled=true param, which advises the API to return the disabled actions too...
e.g.
http://w101.metasfresh.com:8081/rest/api/window/143/1000139/actions?disabled=true

**Comment by ottosichert** [comment]
Okay now I understand your comment I mentioned.

I added it in https://github.com/metasfresh/metasfresh-webui-frontend/pull/1305/commits/ad6dd2daf2bf60eb4249c393fc654616820e3b40 to https://github.com/metasfresh/metasfresh-webui-frontend/pull/1305

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* disabled action is grayed out: OK
* the disabledReason (if available) is displayed beneath: OK
