### ISSUE TITLE
processes: provide current selected tab and rows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1295]
### Is this a bug or feature request?
FR

### What is the current behavior?
Consider a single document window (e.g. one sales order - https://w101.metasfresh.com:8443/window/143/1000111).
When pressing on Actions menu, the actions for current document are queried (see http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_1 ).
Also, the actions for current selected included row from current selected tab where queried, but at the moment of writing this, that feature is broken and shall be fixed by #1279. But that's not in the scope of this task.

![image](https://user-images.githubusercontent.com/1244701/31930714-62b24460-b8a9-11e7-8505-5cf3d7366059.png)

#### Provide selectedTabId and selectedRowIds when querying for document actions
When calling the [/rest/api/window/{windowId}/{documentId}/actions](http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentActionsUsingGET_1) also provide following query (URL) params:
* selectedTabId - which is the currently selected tab Id. e.g. in the case of a Sales order if the Order Line is the selected tab then selectedTabId=1
* selectedRowIds - which are the currently selected row Ids in the "selectedTabId".

#### Provide "selectedTab" info when creating a new process instance
When creating a new process instrance, i.e. calling [POST /rest/api/process/{processId}](http://w101.metasfresh.com:8081/swagger-ui.html#!/process-rest-controller/createInstanceFromRequestUsingPOST), please also provide currently selected tab and rows informations if available.

i.e. the request body shall also contain:
```json
  "selectedTab": {
    "tabId": "currently selected tab ID",
    "rowIds": [ "currently selected rowIds from currently selected tabId" ]
```

### References
The backend was implemented by https://github.com/metasfresh/metasfresh-webui-api/issues/645
Required for https://github.com/metasfresh/metasfresh/issues/2564.

**Comment by PabloSichert** [comment]
`tabId` and `rowId` are sent to `POST /rest/api/process/{processId}`, but only when `viewId` is not set. Is this wrong?
https://github.com/metasfresh/metasfresh-webui-frontend/blob/01284ed9992c323b7592ba4a6fc96dc4ee2bc87e/src/actions/WindowActions.js#L833-L843

**Comment by PabloSichert** [comment]
Ok, I see from your swagger link that `selectedTab` is a dedicated entry with its own `tabId` and `rowIds`.

**Comment by PabloSichert** [comment]
Currently `selectedIds` is passed as query parameter, but it's not documented in the swagger API.

https://github.com/metasfresh/metasfresh-webui-frontend/blob/01284ed9992c323b7592ba4a6fc96dc4ee2bc87e/src/actions/GenericActions.js#L229

Can you confirm that there currently is a mismatch between `selectedIds` and `selectedRowIds` and `selectedIds` should be discontinued?

**Comment by teosarca** [comment]
@PabloSichert 

> tabId and rowId are sent to POST /rest/api/process/{processId}, but only when viewId is not set. Is this wrong?

I would say that it's not wrong, in case the process is called from single document window.
e.g. one particular sales order - https://w101.metasfresh.com:8443/window/143/1000139
In that case you don't know which is the view id.

For the case when the process is called from a view the viewId shall be set.

**Comment by teosarca** [comment]
> Currently selectedIds is passed as query parameter, but it's not documented in the swagger API.

Yes, they are in swagger, see http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/getDocumentActionsUsingGET

> Can you confirm that there currently is a mismatch between selectedIds and selectedRowIds and selectedIds should be discontinued?

Nop. They are different things.
First of all, "selectedIds" is used only in /actions endpoint.

About creating a new process instance (i.e. http://w101.metasfresh.com:8081/swagger-ui.html#!/process-rest-controller/createInstanceFromRequestUsingPOST ),
there we have:
* viewId, viewDocumentIds - (only when the process/action is executed from a view) contains which were the selected rows in that view
* selectedTab (with tabId and rowIds) - (only when the process/action is executed from a single document, e.g. a precise sales order) contains current document's currently selected tab and currently selected rows from that tab.

If u need to clarifications, pls ping me.

**Comment by teosarca** [comment]
i think the "Provide "selectedTab" info when creating a new process instance" part is not implemented.
Moving it to development.

**Comment by metas-lc** [comment]
IT
1. open a window e.g. sales order
2. while in gridview, select actions 
=> actions?disabled=true OK
3. select an action, check headers:
=> there is no selectedTabId OK
4. open a document, select actions
=> actions?disabled=true OK
5. select an action, check headers:
=> selectedTab:{tabId: "1", rowIds: []}
6. select at least 2 rows in the subtab, select actions
=> actions?disabled=true&selectedTabId=1&selectedRowIds=1000031,1000032 OK
7. select an action, check headers:
=> selectedTab:{tabId: "1", rowIds: ["1000031", "1000032"]} OK
