### ISSUE TITLE
Add storybook for isolated visual component testing

### ISSUE THREAD

**Issue by PabloSichert** [metasfresh/metasfresh-webui-frontend#1296]
### Is this a bug or feature request?

Feature request

### What is the current behavior?

Components can't be tested for functionality in isolation. The app can only be tested in integration, so it's hard to pin down the exact reason why a component broke

### What is the expected or desired behavior?

Use a visual [storybook](https://github.com/storybooks/storybook). Have a look at the [examples](https://storybook.js.org/examples/). 🌞

That way QA can test isolated components with constructed test cases

**Comment by teosarca** [comment]
note to IT: u cannot test it
