### ISSUE TITLE
Save indicator

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#13]
A small indicator showing user that this document is saved or save is in progress. Important to make user more comfortable with auto-save.

**Comment by teosarca** [comment]
atm this information is provided in /commit and /data responses but it's not machine friendly. e.g.

* save-status : "DocumentSaveStatus{hasChangesToBeSaved=true, error=false, reason=Invalid status: DocumentValidStatus{valid=false, reason=Mandatory field not filled: C_PaymentTerm_ID}}"

* valid-status : "DocumentValidStatus{valid=false, reason=Mandatory field not filled: C_PaymentTerm_ID}"

We need to make it machine friendly, i.e. one field with some simple well known statuses.

**Comment by cadavre** [comment]
Right now we will focus on simple showing save progress indicator when network will be in progress and showing "ok tick" when response was `2xx` and "error tick" when response was `4xx` or `5xx`.

But after we make this `*-status` more machine-readable we can improve it, good to have it.

PS What will happen if user will create new document but it will never get from temp ID to regular ID document? I.e. when user changed only one field and there are some mandatory still left but not filled.

**Comment by teosarca** [comment]
> PS What will happen if user will create new document but it will never get from temp ID to regular ID document? I.e. when user changed only one field and there are some mandatory still left but not filled.

I think we would need to display an error somehow in that case.

**Comment by cadavre** [comment]
Yeah, but... it's not an error. ;) User just regularly started to create document, but he ended before you could "turn it into" a full-blown document. From a user perspective – it's already a full-blown doc, it's saved (with temp ID, but it's not a huge deifference). I think we could introduce new document state for this – like real "Draft".

BTW What's current document status flow?

**Comment by cadavre** [comment]
Implemented in first version.
