### ISSUE TITLE
Lazy loading concept

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#130]
I am creating this task to gather ideas, info etc about lazy loading approach which is so needed in several places.

**Comment by teosarca** [comment]
IMHO the lazy loading shall work something like this:
* is data visible to user => load it now
* data for a component which is not currently visible for user, but from UX perspective it shall instantly available as soon as user clicks:
** schedule a background task to load the data
** if user clicks to see the data and the data is not yet loaded, prioritize that task and wait to finish
* data for a component which si not currently visible and user can wait => load it just in time



About loading data in background, i found a very interesting feature, called "requestIdleCallback" which is able to run non-essential code when browser is idle.
At the moment is not supported by all browsers but it's supported by chrome and i think we shall use it when possible.
See also: http://caniuse.com/#search=requestIdleCallback

**Comment by cadavre** [comment]
Can we build a complete list of lazy-loading elements?

1. Single tab
2. Menu for navigation
3. Document actions
4. Referenced documents
5. ...

**Comment by damianprzygodzki** [comment]
Do we have any more? All of them are now lazy loaded.

**Comment by cadavre** [comment]
Is no 2 also covered? If so – we have a issue to close. :)

**Comment by damianprzygodzki** [comment]
You are right, so we should switch in home menu to a lazy loading.
