### ISSUE TITLE
Closing a document with changes shall discard those changes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1308]
### Is this a bug or feature request?
FR

#### Case 1 - Included tab #####
* Pick a Business Partner, e.g. https://w101.metasfresh.com:8443/window/123/2156447
* go to location tab and click "Add new" => the location modal is displayed
* directly click on "Done" button (top-right corner)
* u are asked if u want to leave
* press OK =>
** modal is closed
** a new red line appears in the locations tab
![image](https://user-images.githubusercontent.com/1244701/32178654-ef82583a-bd95-11e7-91d0-96a4c49f8c16.png)
![image](https://user-images.githubusercontent.com/1244701/32178678-02a39712-bd96-11e7-8b2f-9fd1aef71911.png)

#### Case 2 ####
* Go to Business Partners window, https://w101.metasfresh.com:8443/window/123/
* From menu, press New to create a new BP
* Don't fill anything but try to close the tab or try to navigate to something else
* you are asked if you want to leave
* press OK
![image](https://user-images.githubusercontent.com/1244701/32178837-6fad5c08-bd96-11e7-80b6-210951cdd061.png)

### What is the expected or desired behavior?
Everytime when the confirmation popup is displayed and user presses OK (Leave), frontend shall call the "POST .../discardChanges" endpoint.

### References:
* backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/651
* triggered by: https://github.com/metasfresh/metasfresh-webui-api/issues/460

**Comment by teosarca** [comment]
NOTE: When /discardChanges endpoint is called it will fire a websocket document stale event on document's websocket endpoint.
e.g. something like this:
![image](https://user-images.githubusercontent.com/1244701/32180801-9ca4f702-bd9b-11e7-81fd-e73e8bf857a5.png)


Please make sure they are intercepted and handled.

**Comment by ottosichert** [comment]
@teosarca

1. Searching the codebase for `window.confirm('Do you really want to leave?')` yields another result besides Modal and MasterWindow: https://github.com/metasfresh/metasfresh-webui-frontend/blob/master/src/components/widget/Attributes/Attributes.js#L123
   Have these changes to be discarded as well?

2. Regarding websockets:
   In Modal the websocket event is received and the item disappears. Is this the correct behaviour?
   In MasterWindow the websocket connection is closed right after `POST`ing to `/discardChanges`, thus no event is received. Is this correct?

**Comment by teosarca** [comment]
> in modal window (e.g. new location in bpartner window): discardChanges endpoint is called, BUT the red line appears for a sec in location tab, then disappears: is that OK? shouldn't it not be displayed at all?

yup, that would be awesome.
@ottosichert  can u pls check it if is a quick fix?

**Comment by ottosichert** [comment]
It actually is a previously implemented feature.

For example when you create a new location for a business partner (https://w101.metasfresh.com:8443/window/123/2156423) and leave the modal in an uncontrollable way such as pulling the plug on your PC or simply closing your browser, you can resume editing this new location.

When you click on **Add new** the red line is already created. When you leave the modal and confirm you really want to leave, I delete this line by calling the `/discardChanges` endpoint.

If you really want me to delete this feature, I can go ahead.

**Comment by teosarca** [comment]
@ottosichert  thanks for explaining. Now sounds different from when i've read it first time :)
I would say we can leave it as it is.

@metas-mk  wdyt?

**Comment by ottosichert** [comment]
@metas-mk can we close this issue?
