### ISSUE TITLE
Wrong process call

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1312]
### Is this a bug or feature request?
Bug

### Which are the steps to reproduce?
* open a bpartner, e.g. https://w101.metasfresh.com:8443/window/123/2156425
* from document references jump to handling units window (btw, u can reproduce it by jumping to any other window)
* in handling units window, just select a row and call first action (does not matter which one, just call one)
![image](https://user-images.githubusercontent.com/1244701/32247777-1fa95562-be8c-11e7-901b-00bac3c1d0b2.png)
![image](https://user-images.githubusercontent.com/1244701/32247815-44c83110-be8c-11e7-97c7-1e0dac9dbe1c.png)
![image](https://user-images.githubusercontent.com/1244701/32247910-93a3c63c-be8c-11e7-98ca-3a689ab3e721.png)

### What is the expected or desired behavior?
Don't provide the selectedTab because there is no selectedTab here. I think that one somehow remained in memory from previous window?!?

More, there is no point to provide selectedTab if not providing windowId and documentId.

**Comment by teosarca** [comment]
note to IT:
Now we are also avoiding this issue on backend side. So pls just make sure the frontend is not sending the "selectedTab" without sending the "windowId" and "documentId".

**Comment by metas-lc** [comment]
IT
1. repeated the testcase above => works fine: there is only "viewDocumentIds"
2. tested another case: order -> shipment disposition -> create shipment => ok, no errors, there is only "viewDocumentIds"
