### ISSUE TITLE
ctrl+enter not working in modal window

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1314]
### Is this a bug or feature request?
bug
### What is the current behavior?
nothing happens when you press ctrl+enter in modal window 
#### Which are the steps to reproduce?
1. open any modal window. Let's say HU Editor in receipt candidates (https://w101.metasfresh.com:8443/window/540196 - green button)
2. notice there is a "Done" button. If you hover it says "ctrl+enter"
3. press ctrl+enter => nothing happens NOK
it should close the modal
### What is the expected or desired behavior?
ctrl+enter (or what you see on hover) shall be the shortcut for the button

**Comment by siemiatj** [comment]
Not sure if this is the button we're talking about : 

![screen shot 2018-07-03 at 12 34 57](https://user-images.githubusercontent.com/513460/42215035-8b6cddd6-7ebd-11e8-9612-1035445e60fb.png)

it is now assigned to `[Alt]+[Enter]` and this seems to be working fine.

**Comment by metas-lc** [comment]
yup. working fine (alt+enter). closing this one
