### ISSUE TITLE
Process is started twice when using ctrl-u shortcut

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1324]
### Is this a bug or feature request?
Bug

### Which are the steps to reproduce?
e.g.
* open receipt candidates
* select a line and press ctrl-u to open the HU editor (i.e. run the current quick action)
* press ctrl-u again to receive
=> you get some weird backend error, but if u inspect the Network tab you can see that /start endpoint is called twice
![image](https://user-images.githubusercontent.com/1244701/32452576-9f802992-c322-11e7-8d65-20c8f88d28cd.png)

NOTE: if you would press the button (using mouse), the /start endpoint would be called only once

### What is the expected or desired behavior?
/start endpoint shall be called only once.

**Comment by metas-ts** [comment]
cherry-picked to `2017-11`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

/start endpoint only called once when using [ctrl]+u shortcut:
* in receipt candidates, to create material receipt: OK
* in picking terminal, to set HU as source HU: OK
* in shipment schedules, to change the delivery date (was set as main action): OK

**Comment by metas-ts** [comment]
cherry-picked to `release`
