### ISSUE TITLE
frontend: Change the JSONLookupValue format

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1327]
See https://github.com/metasfresh/metasfresh-webui-api/issues/666

**Comment by teosarca** [comment]
After integrating the PR, this is the only issue (so far) which i found:
![image](https://user-images.githubusercontent.com/1244701/32595497-d14b4a0c-c538-11e7-9a19-35da847cedc3.png)

**Comment by teosarca** [comment]
another issue: lookup widgets are not displaying the correct caption.
IMPORTANT: you shall transmit back the object EXACTLY as you get it because in some cases, the typeahead/dropdown will provide items which have more than key and caption attributes.... and backend expects them back.


![image](https://user-images.githubusercontent.com/1244701/32599035-f89c5bcc-c543-11e7-811d-67f5777dc0cf.png)

**Comment by metas-mk** [comment]
Error: Open Handling Unit Editor. https://w101.metasfresh.com:8443/window/540189
Press Filter>>Standard/ Default. Select dropdown for "Gebinde Status/ HU Status". Error see Image.
![image](https://user-images.githubusercontent.com/13365687/32609270-7253734a-c55f-11e7-90f1-a9e3cfd68ca8.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

checked all the reported  lookup problems: 
* docstatus: OK
* dropdown product name: OK
* dropdown Gebinde Status in HU Editor filter: OK, no error
* language change user: OK
* PP_Order status: OK
* drropdowns in contract term: OK
* ceation of new bpartner in order: OK
