### ISSUE TITLE
Date recording w/ wrong date Error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1328]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When recording a Date that not exists via keyboard, then it leads to a blank screen and error in console.
#### Which are the steps to reproduce?
Go to Window https://w101.metasfresh.com:8443/window/143/1000013. Edit the Date field and add a date that does not exist. An empty screen appears.
### What is the expected or desired behavior?
Shall return a proper info for the user that the date recorded is not correct.

![image](https://user-images.githubusercontent.com/13365687/32540518-3c5c1faa-c46d-11e7-9a82-109678e10ac6.png)

**Comment by metas-lc** [comment]
IT
1. create a new sales order, add wrong date using keyboard: 33/13/2017
=> error message appears:
DateOrdered
DateOrdered has an invalid date. 
OK
2. refresh the page
=> date changes back to how it was before change: 11/13/2017 OK

3. update the date again to a wrong one (33/13/2017)
4. add a product, complete
=>  date changes back to how it was before change: 11/13/2017 OK
