### ISSUE TITLE
view: Edit field value is broken

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1332]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* open Product Prices: https://w101.metasfresh.com:8443/window/540325
* right click on an numeric cell, e.g. Price List
* click on Edit field value 
=> NOK: nothing happens

![image](https://user-images.githubusercontent.com/1244701/32613139-b158f71e-c572-11e7-9f25-89b077a2d107.png)

### What is the expected or desired behavior?
I should be able to edit that value directly

**Comment by teosarca** [comment]
when fixing this one pls also keep in mind https://github.com/metasfresh/metasfresh-webui-frontend/issues/1335

**Comment by wiadev** [comment]
@teosarca `viewEditorRenderMode` field is not coming from the api.
can you check it, please?

Also, fixed editor is broken issue.

Regarding updating the view from viewEditorRenderMode, can you create an new issue and track over there?

**Comment by teosarca** [comment]
> viewEditorRenderMode field is not coming from the api.
> can you check it, please?

yup... it seems i will have to do another rollout

> Regarding updating the view from viewEditorRenderMode, can you create an new issue and track over there?

isn't that #1335 ?

**Comment by metas-lc** [comment]
IT
Edit field value works as before. OK
 Note we still have a pending task, about:
- field not being translated to DE
- if you click the arrows multiple times, the document opens
 https://github.com/metasfresh/metasfresh-webui-frontend/issues/1274
