### ISSUE TITLE
Process panel is closed even if /start failed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1333]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
e.g.
* https://w101.metasfresh.com:8443/window/540196
* select a line
* call "Receive HUs"
* remove some mandatory params or fill some params wrongly
* Start the process
=> the error message from server is displayed => OK
=> the process params panel is closed => NOK

![image](https://user-images.githubusercontent.com/1244701/32647907-3c5af54a-c5fc-11e7-8e73-0e1a0a6efb04.png)

### What is the expected or desired behavior?
The process params panel shall stay there while the /start endpoint is running. This is how it worked. Additionally, it would be nice to disable all fields while process is running.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* process params panel shall stay while the /start endpoint is running: panel does not close anymore after process error, OK
* disable all fields while process is running: all fields are read-only while process is running, can only be edited again after process is finished: OK
