### ISSUE TITLE
views: backend shall specify which columns are editable and how to render the editor (frontend)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1335]
See https://github.com/metasfresh/metasfresh-webui-api/issues/670

### Related tasks:
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/1332

**Comment by teosarca** [comment]
Please also consider the issues reported here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1274

**Comment by teosarca** [comment]
### Use case for viewEditorRenderMode:"always"
* have a sales order with at least one order line (u can use existing ones)
* select the order lines and call the "Create purchase orders" action
* check the layout of the fetched modal view, the QtyToPurchase and DatePromised shall render an field editor for each row.

In my example, i was using https://w101.metasfresh.com:8443/window/143/1000039
![image](https://user-images.githubusercontent.com/1244701/32724881-a83dcdf6-c87b-11e7-9380-848b393c19a9.png)
![image](https://user-images.githubusercontent.com/1244701/32724890-abdcc458-c87b-11e7-8469-8b88dfafed5d.png)

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/670 OK

**Comment by teosarca** [comment]
Found following issues:
-----
Editor patching endpoint is not correctly called.
Steps to reproduce:
* pick a draft order
* select it's order lines
* and from action menu call Create purchase orders
* try edit the QtyToPurchase from second row
=> ERROR, the endpoint is not correctly called.
Remark the URL: https://w101.metasfresh.com:8443/rest/api/window/SO2OLCand/1000114_2156423
Between "/window/" and "/SO2OLCand" we shall have the viewId.
See http://w101.metasfresh.com:8081/swagger-ui.html#!/view-row-edit-rest-controller/patchRowUsingPATCH

![image](https://user-images.githubusercontent.com/1244701/32904002-17c856de-caff-11e7-9084-fba50252c0b9.png)

![image](https://user-images.githubusercontent.com/1244701/32904017-1e09035e-caff-11e7-83ac-b78565d3a7fc.png)

**Comment by teosarca** [comment]
Another issue: while editing the number:
* if I press enter, the patch is not sent to server => NOK
* if i press on component's arrow up/down to increment/decrement the number, the patch is not sent => NOK

**Comment by wiadev** [comment]
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1351

**Comment by wiadev** [comment]
created new issue for handling wrong api call for view grid edit

**Comment by teosarca** [comment]
10x, closing this one.

**Comment by teosarca** [comment]
note to IT: pls test:
> if I press enter, the patch is not sent to server => NOK"

**Comment by teosarca** [comment]
closing it because everything which did not work was moved to individual tasks.

even
> if I press enter, the patch is not sent to server => NOK"

which is kind of not working, shall be fixed on #1358
