### ISSUE TITLE
All values of Dropdown list are highlighted

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1337]
### Is this a bug or feature request?
bug

### What is the current behavior?
![image](https://user-images.githubusercontent.com/16079655/32691835-35b4048a-c70e-11e7-9763-409c5d9641eb.png)

#### Which are the steps to reproduce?
login with a user that has got more than one role

### What is the expected or desired behavior?
entries should not be highlighted

**Comment by metas-dh** [comment]
Results of IT1
tested in sp80

entries in dropdown are not highlighted: OK
