### ISSUE TITLE
Breadcrumb record identifier for included Tab expansion

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#134]
Clear Breadcrumb-Title for included Tab expansion
In Task #125 Expan Button we want to allow the full screen expansion of included tabs for better fast line recording. If we do that the user will only see the included tabs including fast line entry and the header section. For this situation we need a clear breadcrumb record identifier, For Sales order this would be Order Document No and of Businesspartner name + location.

wdyt?

![image](https://cloud.githubusercontent.com/assets/13365687/20927375/9b3c17a6-bbc1-11e6-84b8-f87318adc667.png)

**Comment by cadavre** [comment]
Why clear that? Without it user won't know for which entity he's editing the tabbed table entries. Imagine few documents opened with tabs in expanded mode in browser tabs – he will be lost.

**Comment by metas-mk** [comment]
Clear = have a clearly record identifier ;-)
I don't want to erase that. It shall be fully and clearly readable by the user.

**Comment by cadavre** [comment]
Oh, misunderstood. :)

**Comment by metas-mk** [comment]
seems to be fixed already. will check again after todays rollout.

**Comment by cadavre** [comment]
@metas-mk re-checked?

**Comment by teosarca** [comment]
Checked again. The header is preserved while tab is expanded.
![image](https://cloud.githubusercontent.com/assets/1244701/23108170/e4631ed0-f711-11e6-974b-d3f7a99f4f31.png)
