### ISSUE TITLE
Invalid date was used on dateTime tablecell

### ISSUE THREAD

**Issue by wiadev** [metasfresh/metasfresh-webui-frontend#1345]
### Is this a bug or feature request?
bug
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1335

### What is the current behavior?
Invalid date was used on dateTime table cell.

![screenshot at nov 16 10-43-42](https://user-images.githubusercontent.com/18234060/32884572-1706c832-cabb-11e7-87d7-109793edc82a.png)

#### Which are the steps to reproduce?

1. http://localhost:3000/window/143/1000039
2. select a order line
3. action: Create a purchase orders

### What is the expected or desired behavior?

datetime should be formatted properly.

**Comment by wiadev** [comment]
@teosarca 
Also, I found another issue on this modal.
everytime I try to change the datetime, it sends a request to backend. (i.e. http://w101.metasfresh.com:8081/rest/api/window/SO2OLCand/2b8b1943-8575-4741-ad62-09e91c728c1d)

but it responds with 404 error.

![screenshot at nov 16 10-47-29](https://user-images.githubusercontent.com/18234060/32884732-9960eb0a-cabb-11e7-9f9e-e8ac5eaaf957.png)

**Comment by teosarca** [comment]
@wiadev  

> Also, I found another issue on this modal.
> everytime I try to change the datetime, it sends a request to backend. (i.e. 
 http://w101.metasfresh.com:8081/rest/api/window/SO2OLCand/2b8b1943-8575-4741-ad62-09e91c728c1d)

ok, thanks, will check.

----
About the issue from this task, how shall we solve it?
Does backend needs to provide something or it can be solved entirely on frontend side?

**Comment by wiadev** [comment]
@teosarca backend is returning widgetType correctly.
I bet, this is pure front-end issue.

**Comment by teosarca** [comment]
@wiadev  10x for update.

**Comment by wiadev** [comment]
@teosarca 
from the following api, it doesn't return widgetType for fields. (i.e. datePromise)
GET http://w101.metasfresh.com:8081/rest/api/documentView/SO2OLCand/SO2OLCand-8864f4095f384a0393596b14e6e28905?firstRow=0&pageLength=20

![screenshot at nov 18 22-47-03](https://user-images.githubusercontent.com/18234060/32985082-75d7a4aa-ccb2-11e7-859f-e531ec50b3b5.png)

**Comment by teosarca** [comment]
i know.
I was asking you if you need it, or you can get it from view's layout, where is already provided?
I would prefer to get it from layout because it would avoid sending redundant data.
If it's too complicate to do it like that, pls let me know and I will provide it on each row (for now...).

**Comment by wiadev** [comment]
@teosarca right now, we are not keeping documentView layout fieds in the store.
Also, only for this purpose, keeping all fields is not a good idea, I think and better off you send fields again.

**Comment by teosarca** [comment]
@wiadev  ok, i will.

**Comment by metas-lc** [comment]
IT
date promised has the correct format: DateTime OK
