### ISSUE TITLE
Dropdown in Grid view needs two-time click if value in list is more than one

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1347]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?

1. have one completed flatrate condition
1. open sales order https://w101.metasfresh.com:8443/window/143/1000039
1. add a sales order line
1. got to column "contract condition" and select a condition
![image](https://user-images.githubusercontent.com/16079655/32891259-2f10a4b8-cad2-11e7-89b2-9b975ed4e937.png)
1. OK: value is selected when clicked
1. create another completed flatrate condition
1. add new sales order line
1. got to column "contract condition" 
1. you should see two conditions here
1. select one condition
1. NOK: value is not stored
1. NOK: no request towards API is sent
![image](https://user-images.githubusercontent.com/16079655/32891380-a06f8f2a-cad2-11e7-9329-07839d129514.png)

1. workaround: try again and it works

### What is the expected or desired behavior?
should always work first time

**Comment by metas-ts** [comment]
Cherry-Picked this fix toi the `release` branch

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 & weekly e2e

Dropdown in Grid view: one-time click works fine also if value in list is more than one
