### ISSUE TITLE
List order page problem

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#135]
Steps to reproduce: 
* Open the sales orders
* Go to page 4
* Order by documentNo ( or anything else) 
* NOK: The cursor moves to page 1 but everything else is for page 4 (see picture) :

![list order pages problem](https://cloud.githubusercontent.com/assets/16001442/20928732/d448a420-bbcf-11e6-908f-2aedd01b5fb7.png)

**Comment by metas-rc** [comment]
Note: It also happens if the list is opened from the top-right button (see picture) :

![order page problem 2](https://cloud.githubusercontent.com/assets/16001442/20929129/79f8cb06-bbd1-11e6-9724-2cf3fd1885db.png)

**Comment by metas-rc** [comment]
Found another bug that is probably related: 

* Open Sales Order from menu, go to page 5

![so page 5](https://cloud.githubusercontent.com/assets/16001442/20974305/67fbc01a-bca4-11e6-9774-e9d34b97db6e.png)


* Now go to home, then open Lieferdispo ( currently the problem in https://github.com/metasfresh/metasfresh-webui-frontend/issues/137 will make it impossible to get to the lieferdispos directly)

=> NOK: You also see the page 5 of lieferdispos

![shipment schedule pag 5](https://cloud.githubusercontent.com/assets/16001442/20974448/dd106252-bca4-11e6-8455-dd5bfeb1c4dc.png)

**Comment by Dunkat** [comment]
fixed
