### ISSUE TITLE
wrong backend api call for grid view editing

### ISSUE THREAD

**Issue by wiadev** [metasfresh/metasfresh-webui-frontend#1351]
### Is this a bug or feature request?
bug

### What is the current behavior?
Editor patching endpoint is not correctly called.

#### Which are the steps to reproduce?
* pick a draft order
* select it's order lines
* and from action menu call Create purchase orders
* try edit the QtyToPurchase from second row
=> ERROR, the endpoint is not correctly called.
Remark the URL: https://w101.metasfresh.com:8443/rest/api/window/SO2OLCand/1000114_2156423
Between "/window/" and "/SO2OLCand" we shall have the viewId.
See http://w101.metasfresh.com:8081/swagger-ui.html#!/view-row-edit-rest-controller/patchRowUsingPATCH

### What is the expected or desired behavior?
needs to update the current api call with the following.

http://w101.metasfresh.com:8081/swagger-ui.html#!/view-row-edit-rest-controller/patchRowUsingPATCH

**Comment by teosarca** [comment]
note: backend API was implemented in https://github.com/metasfresh/metasfresh-webui-api/issues/577

**Comment by wiadev** [comment]
@teosarca 

I found 2 errors on the backend side while I'm testing.
 - http://w101.metasfresh.com:8081/rest/api/documentView/SO2OLCand/SO2OLCand-c519579eafb84f92b01ecd4b6df4a62e/1000091_2156423

The above api is not working while http://w101.metasfresh.com:8081/rest/api/documentView/SO2OLCand/SO2OLCand-c519579eafb84f92b01ecd4b6df4a62e/1000091_2156423/edit works fine.

![screenshot at nov 18 21-08-40](https://user-images.githubusercontent.com/18234060/32984326-ca3b56da-cca4-11e7-85a0-db4c9cce6840.png)

- for rowId: 1000091, the following api is not working (got 500 internal server error) while rowId:1000091_2156423 works fine.

http://w101.metasfresh.com:8081/rest/api/documentView/SO2OLCand/SO2OLCand-c519579eafb84f92b01ecd4b6df4a62e/1000091/edit

![screenshot at nov 18 21-10-57](https://user-images.githubusercontent.com/18234060/32984338-14e09470-cca5-11e7-8cfd-6408788caf92.png)




-

**Comment by teosarca** [comment]
hi @wiadev 

> http://w101.metasfresh.com:8081/rest/api/documentView/SO2OLCand/SO2OLCand-c519579eafb84f92b01ecd4b6df4a62e/1000091_2156423
> The above api is not working while 

agree. the URL is not correct. It shall end with "/edit"... see http://w101.metasfresh.com:8081/swagger-ui.html#/view-row-edit-rest-controller


> for rowId: 1000091, the following api is not working (got 500 internal server error) while 
> rowId:1000091_2156423 works fine.

agree. grouping rows are not editable. Only the included ones.
We shall be able to also override the "viewEditorRenderMode" on row level too.
I will create a frontend task to have this feature.

**Comment by wiadev** [comment]
@teosarca sorry, my first comments is wrong. /edit works file but after edit, we are sending getData() request which is for http://w101.metasfresh.com:8081/swagger-ui.html#!/view-row-attributes-rest-controller-_-old/getDataUsingGET_1 but it's not working. they are separate api calls.

let me know if it doesn't make sense.

**Comment by teosarca** [comment]
@wiadev  not sure if i understand... but that controller was replaced by http://w101.metasfresh.com:8081/swagger-ui.html#/view-row-attributes-rest-controller ,
exactly because
```
GET /rest/api/documentView/{windowId}/{viewId}/{rowId}
```
Was too confusing. It's about getting the row attributes (those which are displayed on the right side of the view, see https://w101.metasfresh.com:8443/window/540189 for example).
But the name of the endpoint is not revealing that intention. You were tempt to believe that it's about fetching the row.

In the current API we are using
```
GET /rest/api/documentView/{windowId}/{viewId}/{rowId}/attributes
```
----
But I believe you are not asking about fetching the attributes but about fetching a particular row.
We don't have this endpoint, but if it's needed we can provide it.
Might be that we need to replace the functionality of that old endpoint.... and in that case you shall make sure the frontend is no longer using the legacy API.

**Comment by metas-lc** [comment]
IT
looks like this, and there are no errors
rest/api/documentView/SO2PO/SO2PO-37c4dbaff61447b69bc7f14f49e83332/1000059_2156425/edit
