### ISSUE TITLE
Cannot clear dropdown fields

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1352]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* create a sales order
* add a sales order line
* advanced edit that order line
* try setting Packing Item field to "none".
=> ERROR because frontend is sending wrong patch value:
```json
[{"op":"replace","path":"M_HU_PI_Item_Product_ID","value":{"key":"empty","caption":"none"}}]
```

Btw, for checking u can use any other draft order, or any other document where u have drop down which is not mandatory.

![image](https://user-images.githubusercontent.com/1244701/32957540-a3753f24-cbc4-11e7-90af-b579866beed4.png)

### What is the expected or desired behavior?
it should be
```json
[{"op":"replace","path":"M_HU_PI_Item_Product_ID","value":null}]
```

**Comment by teosarca** [comment]
issue introduced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1327

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no error when setting Packing Item field to "none": OK

* after setting the Packing Item field to "none": in purchase order, you cannot select the original packing item again (works fine in sales order): don't think this is OK, but i'm not sure it was introduced by this task or is a config thing? 
=> in sales order, after selecting the product in quick entry, you have to click tab twice to get to the quantity field, confirming the packing item too, whereas in purchase order, you get to the quantity field after clicking tab only once, no need to confirm the packing item there
