### ISSUE TITLE
DateTimeRangePicker default Time from/to in Filter and Process Parms

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1354]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when opening a DateTimeRangePicker in Filter and Process Parms, the initial date is set. The initial from-time and to-time is set to now().
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
When opening the DateTimeRangePicker in Filter and Process Parms and no previous data was set by the user, then don't set the from-time and to-time to now, set it to 0:00/12:00AM and 23:59/11:59PM instead.

![image](https://user-images.githubusercontent.com/13365687/32977769-4e8b25b2-cc34-11e7-8df7-a6d2d1a8c0a3.png)

**Comment by wiadev** [comment]
@metas-mk what is `Process Parms` and where can I find it?

**Comment by metas-mk** [comment]
@wiadev ProcessParms can be found in Action Menu>>Actions. Here an example for Daterange in Contract Window>>Pause Contract.
![image](https://user-images.githubusercontent.com/13365687/33010636-7f8020b6-cddb-11e7-89d8-062b6c442949.png)

**Comment by metas-lc** [comment]
IT
checked date filter from picking terminal => time was set to 0:00/12:00AM and 23:59/11:59PM OK
checked pause contract in contract window => date range - today (without time) OK

this might be backend: when i first open "Pause contract" for a really short time, the field is red. I saw in preview that the value was null (have to check)
![image](https://user-images.githubusercontent.com/16001666/33842336-ec84513c-dea2-11e7-9446-b1881518173b.png)
