### ISSUE TITLE
View field editor: number field is behaving weird when using keyboard

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1358]
### Is this a bug or feature request?
Bug

follow up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1335

#### Which are the steps to reproduce?
* open a draft sales order, e.g. https://w101.metasfresh.com:8443/window/143/1000096
* select the order lines and call the Create purchase order action
* click to edit QtyToPurchase of an included line

Remark:
1. click left/right to move your cursor inside the number field => not working
2. DEL, BACKSPACE not working
3. CTRL+A not working
4. press arrow UP/DOWN. Sometimes the number is incremented and sometimes the current selected row is changed. When the current selected row is changed (e.g. press UP and the row above is now the current selected row) the editor value is not sent back to backend.

NOTE: sometimes works sometimes not.... play a bit with them.

![image](https://user-images.githubusercontent.com/1244701/33021546-df7e59fe-ce0a-11e7-8371-12f04ba129b5.png)

### What is the expected or desired behavior?
All the points above shall work.

**Comment by teosarca** [comment]
@wiadev  about sending all edited values when user presses Done, we have a similar issue on process parameters: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1331#issuecomment-343506811

**Comment by teosarca** [comment]
@wiadev  also pls consider the problems described here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1274

**Comment by metas-lc** [comment]
IT
1. each time you modify something you get "Row does not support attributes" error in Preview and console (for the view) - will create a task
2. click left/right to move your cursor inside the number field => click works OK
3. DEL, BACKSPACE - working OK but if i use them the last number appears back - will create a task
4. CTRL+A not working - changed to alt a - not working (probably not related with this task?) "WindowId cannot be converted to int: SO2PO"
5. press arrow UP/DOWN. - only the current selected row is changed OK

**Comment by wiadev** [comment]
@teosarca regarding #10 which is related with #7, right now, under table hierarchy, they do have all handleKeyword methods and one of them is handling 'enter', as well and blocking the other 'enter' key strokes.

and moreover, there is no watcher for 'enter' hit on input number field ( of RawWidget ) and which should be implemented newly.

I suggest to create new follow-up task for this, as well.

**Comment by teosarca** [comment]
@wiadev  can u pls that follow-up task and extract there the issues enumerated by @metas-lc  (Lili) which were not delivered here?

**Comment by wiadev** [comment]
> if I press enter, the patch is not sent to server => NOK
(noticed that tab works)

follow-up - #1396

**Comment by teosarca** [comment]
i guess everything was delivered on this task.

**Comment by metas-lc** [comment]
IT
checked again the testcase above
1. "Row does not support attributes" error is now gone OK
2. still working OK
3. delete and backspace still shows the number NOK https://github.com/metasfresh/metasfresh-webui-frontend/issues/1462
4. alt+a works OK
5. press arrow UP/DOWN - same issue, you can change the row if you are in date field NOK
probably shall be fixed by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1429
6. OK
7. we have task https://github.com/metasfresh/metasfresh-webui-frontend/issues/1430
8. and 9. have task, rest is ok https://github.com/metasfresh/metasfresh-webui-frontend/issues/1384
10. i'll update the task from step 9. shall be fixed there
