### ISSUE TITLE
Delete button not reachable for Order orderLine

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#136]
* Create a purchase order with a line
*Try to delete the line
* NOK: Delete button not reachable: 

![delete button](https://cloud.githubusercontent.com/assets/16001442/20930924/f396ff36-bbd7-11e6-8491-2faf2bda432b.png)

(tested both on Chrome and Firefox)

**Comment by metas-rc** [comment]
Update: It is also not reachable from Sales Order if I have more than 7 lines: 

![sales order delete button](https://cloud.githubusercontent.com/assets/16001442/20931843/39220336-bbdb-11e6-84a9-0a2961c3dbb0.png)

**Comment by metas-lc** [comment]
![lieferdispo](https://cloud.githubusercontent.com/assets/16001666/20972970/6e3aa0fe-bc9f-11e6-9bc3-d7fdd61dd6bc.png)
it happens everywhere if the page margins are reached
