### ISSUE TITLE
View field editor: override viewEditorRenderMode on row level

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1360]
### Is this a bug or feature request?
FR 
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1335

### What is the current behavior?
The viewEditorRenderMode it's specified in view layout, per column and frontend considers it.
But now, in some cases, the backend is providing viewEditorRenderMode  per view row-field.

#### Which are the steps to reproduce?
* open a draft sales order, e.g. https://w101.metasfresh.com:8443/window/143/1000096
* select the order lines and call the Create purchase order action
In the example above the QtyToPurchase and DatePromised shall be editable only in included rows.
![image](https://user-images.githubusercontent.com/1244701/33022773-ee1b29b6-ce0e-11e7-8bf6-ae701bd61a5d.png)

### What is the expected or desired behavior?
When the viewEditorRenderMode   property is specified per row-field, it shall override the value specified in layout.

**Comment by wiadev** [comment]
@teosarca @metas-lc can you provide me the example which has multi includedDocuments? I wanna go through several use cases.

**Comment by teosarca** [comment]
@wiadev  just configured 2 more vendors to that Salat product:

![image](https://user-images.githubusercontent.com/1244701/33229801-ddd764ec-d1de-11e7-8e14-b9d9597e5a33.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. open e.g. window 123, select tab location
2. click Add new: modal does not open, but you get question if you want to leave the page:

![2017-11-27 16_15_34-metasfresh](https://user-images.githubusercontent.com/18696715/33273817-b0e07d3c-d38e-11e7-842d-ea8517001b40.png)

3. Click cancel twice, so the small window disappears: window is completely empty:

![2017-11-27 16_20_38-metasfresh](https://user-images.githubusercontent.com/18696715/33273914-f79f0b6c-d38e-11e7-98e4-ed4313a08a82.png)

4. Refresh the window: a new entry was created for location, but it's empty and the line is red:

![2017-11-27 16_16_20-metasfresh](https://user-images.githubusercontent.com/18696715/33273940-0e31e9ee-d38f-11e7-9d5f-7ced54e989b7.png)

**Comment by wiadev** [comment]
@metas-dh I'm testing on w101 and I don't have `Add new` button.

![screenshot at nov 28 14-05-44](https://user-images.githubusercontent.com/18234060/33321265-5ddc3056-d445-11e7-9ad2-38b7e81b6174.png)

**Comment by metas-dh** [comment]
@wiadev sorry, i thought it was called "Add new" in the english version; it's "Neu hinzufügen"

i mean this one:

![2017-11-28 15_11_53-metasfresh](https://user-images.githubusercontent.com/18696715/33324051-aa00a8c8-d44e-11e7-888e-d35dfaeb1f80.png)

(btw, there is no button in the first tab in bpartner window bc you create new entries only with Action menu - Create Request, afaik)

**Comment by wiadev** [comment]
@metas-dh 
I've fixed the issue of not showing `Add New` modal and played around a little.

but when I've put the name on `Add New` modal and hit `Done`, nothing was added in the table. am I missing something?

![screenshot at nov 28 16-37-59](https://user-images.githubusercontent.com/18234060/33328583-acd679f4-d45a-11e7-850f-f1081f0b07f2.png)

**Comment by metas-dh** [comment]
@wiadev 
the country field in address is mandatory, so without setting that no new entry will be created (sorry for not mentioning that earlier).
so, you have to
1. click Edit for Address
2. Set the country
3. When that's saved, click Done => new entry shall be created

![2017-11-28 17_08_20-metasfresh](https://user-images.githubusercontent.com/18696715/33330499-4f6967c2-d45f-11e7-9e7d-d8147dedb843.png)

**Comment by wiadev** [comment]
@metas-dh Thanks for clarification.
I've followed your steps and it works. you can start testing after @teosarca merge #1388 .

**Comment by metas-dh** [comment]
@wiadev thanks for the info

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* View field editor: override viewEditorRenderMode on row level: OK  (QtyToPurchase and DatePromised are editable only in included rows
* problem with new entry for included tab fixed as well
