### ISSUE TITLE
View field editor: make sure the field value is sent to backend before the view is deleted

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1361]
### Is this a bug or feature request?
Bug
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1335
part of https://github.com/metasfresh/metasfresh-webui-api/issues/664

#### Which are the steps to reproduce?* open a draft sales order, e.g. https://w101.metasfresh.com:8443/window/143/1000096
* select the order lines and call the Create purchase order action
* edit a field value and directly press "Done" to close the modal
=> NOK: error because the field is patched after the view is deleted.

![image](https://user-images.githubusercontent.com/1244701/33028774-6fb9132e-ce1f-11e7-888f-766602992fab.png)

### What is the expected or desired behavior?
Shall work.

If there is a chance, even if it's small, to not send back some fields then I highly suggest, on Done,
please also consider sending ALL edited fields.
It's super important to have 100% correct and up2date values.

Another thing, if, for some reason the "DELETE view" endpoint which is called on Done fails, please don't close the modal.

**Comment by metas-lc** [comment]
IT
i don't really have a clear testcase for this, but i managed to reproduce after trying the same thing several times (and notice edit appears several times. Don't know if it's wanted or not)
go to https://w101.metasfresh.com:8443/window/143/1000096
e.g. select the first line, go to actions - create purchase orders
update a qty using keyboard then press done => works
select the first line and  go to actions - create purchase orders
update the qty again using keyboard then press done => error
(you might need to do this 2 or 3 times...)
![image](https://user-images.githubusercontent.com/16001666/33551030-acbea39a-d8f8-11e7-825d-e69442e4fe0a.png)

**Comment by metas-lc** [comment]
IT
repeated the testcase above. Works fine: error doesn't appear in that case. Also those edits don't appear OK
still, there is a case when that error pops up: when you change a qty in "Create purchase orders" and pressing done directly. Created follow-up https://github.com/metasfresh/metasfresh-webui-frontend/issues/1518
