### ISSUE TITLE
Error with alt+space for expand

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1365]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, alt+space menu open collides with expand functionality. The Browser Menu opens.
#### Which are the steps to reproduce?
Open Sales Order Window. Add Businesspartner and mandatory fields. Press alt+space for expand.
### What is the expected or desired behavior?
Alt+space shall not open the browser menu. Shall expand/ compress (toggle) the lines View.

![image](https://user-images.githubusercontent.com/13365687/33067314-08ff0f1e-ceae-11e7-88dc-56b064d7f430.png)

**Comment by PabloSichert** [comment]
Looks like it is impossible to intercept `Alt+Spacebar` for Windows, since control is taken away from the browser before I can handle that key.

Would it be possible to take another combination?

**Comment by PabloSichert** [comment]
New hotkey is `Alt`+`+`

**Comment by metas-lc** [comment]
IT
1. open new sales order, add a bpartner and press alt++
=> lines view expands OK
2. press alt++ again
=>  lines view compress OK
