### ISSUE TITLE
Error in Quickentry dropdown List

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1366]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the filter results in Quickentry dropdown List are not correct.
#### Which are the steps to reproduce?
Type "conv" in Product Field and check the results in frontend compared to api response.
### What is the expected or desired behavior?
Shall only show correct filter results.

![image](https://user-images.githubusercontent.com/13365687/33068323-296cb906-ceb1-11e7-828e-beb2a93fc126.png)

**Comment by teosarca** [comment]
@PabloSichert  pls make sure the result is not cached at all

**Comment by teosarca** [comment]
@PabloSichert  not sure but might be related with https://github.com/metasfresh/metasfresh-webui-frontend/issues/1165 ...

**Comment by PabloSichert** [comment]
It was related to #1327

**Comment by metas-lc** [comment]
IT
repeated the testcase above => only salad is shown (as i see in values) OK
to test the caching, i opened another tab, added to this pricelist another product price for a product that was not found before(e.g. frisee). Came back to the first tab and started writing the new product's name => was found OK
