### ISSUE TITLE
view attributes shall be refreshed when the current selected row is refreshed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1367]
### Is this a bug or feature request?
bug
issue required for https://github.com/metasfresh/metasfresh-webui-api/issues/696

#### Which are the steps to reproduce?
* go to material receipt candidates: https://w101.metasfresh.com:8443/window/540196
* click on default receive action (e.g. 24 IFCO 6410 x 10 Stk)
* the HU modal is opened
* remark that first row is selected and the attributes on the right side are editable => OK
* call the "Create material receipt" action
* the HU is processed and turns to gray (not editable) => OK
* but the attributes are still editable => NOK => they shall be refreshed (see below)

![image](https://user-images.githubusercontent.com/1244701/33076992-2439014e-ced7-11e7-89bb-c2ac69c8d20e.png)
![image](https://user-images.githubusercontent.com/1244701/33077040-52d73cfa-ced7-11e7-9327-134f0cb9f129.png)
![image](https://user-images.githubusercontent.com/1244701/33077049-56ac1c24-ced7-11e7-9619-0e6192799443.png)

### What is the expected or desired behavior?
Whenever:
1) the whole view is refreshed because of a websocket event (but not necessary) and there is a row selected and that row has attributes => refresh the attributes too
2) if some rows are refreshed because of websocket event or not and one of those rows is actually the current selected row which has attributes => refresh the attributes too

When developing this, please also consider https://github.com/metasfresh/metasfresh-webui-frontend/issues/1357

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

attributes are correctly refreshed
* attribute is correctly updated in TU when set for the LU: OK
* attributes are read-only after the material receipt was created (HU is read-only): OK
