### ISSUE TITLE
ViewId remains the same even if I open different windows

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#137]
Steps to reproduce: 
* Open the window Merkmale, check the ViewId ( URL like http://w101.metasfresh.com:8090/window/260?viewId=a02b1c0c-764c-411e-b9ac-5b8313b72aac )

![attributes](https://cloud.githubusercontent.com/assets/16001442/20934583/51597f84-bbe4-11e6-9a7c-beb48d4aac90.png)

* Open Stucklisten, check the viewId 
 => NOK: ViewID is the same.
 URL = http://w101.metasfresh.com:8090/window/53006?viewId=a02b1c0c-764c-411e-b9ac-5b8313b72aac
 => NOK: The content is the one from Merkmal (M_Attribute) 

![stucklisten](https://cloud.githubusercontent.com/assets/16001442/20934592/5b76bac2-bbe4-11e6-8b5c-c1feb5580b94.png)

* Open Preise, check the viewId
=> NOK: ViewID is the same.
URL = http://w101.metasfresh.com:8090/window/146?viewId=a02b1c0c-764c-411e-b9ac-5b8313b72aac

 =>NOK: The content is also the one form Merkmal

![prices](https://cloud.githubusercontent.com/assets/16001442/20934638/7d7c019a-bbe4-11e6-8faf-c03de8718807.png)

**Comment by teosarca** [comment]
Might be related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/79

**Comment by metas-rc** [comment]
It happens also for Sales Order and Purchase Order.
URLS:
http://w101.metasfresh.com:8090/window/143?viewId=7d974047-7fe8-4cc0-9602-7bb91656eace
http://w101.metasfresh.com:8090/window/181?viewId=7d974047-7fe8-4cc0-9602-7bb91656eace

**Comment by teosarca** [comment]
UPDATE: reproduced today too
