### ISSUE TITLE
view: collapsing rows works weird 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1373]
### Is this a bug or feature request?
Bug

required for https://github.com/metasfresh/metasfresh-webui-api/issues/689

#### Which are the steps to reproduce?
* open picking terminal: https://w101.metasfresh.com:8443/window/540345
* select line and call "Pick" => the picking modal is displayed
* suppose you have an HU on one of the picking slots from the right side. If not, add one or ask somebody to add one for you
* try to expand that HU => first time does nothing (**NOK**), second time it is actually expanded
![image](https://user-images.githubusercontent.com/1244701/33126301-ac62e99e-cf8c-11e7-8e2e-f71bb9322245.png)

* now try to collapse the included HU => instead of collapsing just that one, frontend is actually collapsing all nodes until the "expandedDepth" that was provided in view layout (**NOK**)
![image](https://user-images.githubusercontent.com/1244701/33126396-05ebff46-cf8d-11e7-9654-aefe68b1bc4a.png)
![image](https://user-images.githubusercontent.com/1244701/33126428-1eab1cce-cf8d-11e7-83fa-4740b4b8ca13.png)

### What is the expected or desired behavior?
Shall work nice and natural.
Also please pay attention to the "-" and "+" icons. They are not always correct (sometimes the "-" icon is displayed instead of "+").

**Comment by wiadev** [comment]
@teosarca we have an issue with duplicated ids. please, take a look at this.
![screenshot at dec 06 09-20-25](https://user-images.githubusercontent.com/18234060/33652313-3d2e77c2-da69-11e7-8761-ccf84c21dc04.png)

**Comment by teosarca** [comment]
> we have an issue with duplicated ids. please, take a look at this.

@wiadev  shall be fixed by https://github.com/metasfresh/metasfresh-webui-api/issues/722 ,
on next rollout.

**Comment by teosarca** [comment]
now seems to work ok. moving the task to Test.

**Comment by metas-lc** [comment]
IT
1. opened picking terminal and selected a line
2. pressed pick
3. made sure i have an HU on a slot then i used + and - to expand / collapse
=> + always means expand and - always collapse OK
=> on slot level: - collapses all, + expands to LU OK
=> on LU level: - collapses TU and CU, + expands to TU OK
=> on TU level: - collapses CU, + expands to CU OK
