### ISSUE TITLE
Keyboard alt+u in Sales Order

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1374]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when in Sales Order using alt+u to complete order, then nothing happens.
#### Which are the steps to reproduce?
Try above and see.
### What is the expected or desired behavior?
Complete the document when pressing alt+u.

![image](https://user-images.githubusercontent.com/13365687/33130331-467c4c68-cf93-11e7-9f46-13082f52a868.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

alt+u completes the Sales Order (same in Purchase Order): OK
