### ISSUE TITLE
Navigation Menu arrow down directly scrolls menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1375]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
When using the Navigation menu and pressing arrow down, then the navigation menu directly scrolls down. Also when using search on right side and arrow down for selection.
#### Which are the steps to reproduce?
Open and try.
### What is the expected or desired behavior?
Start the scrolling later and not directly after first arrow down.

![image](https://user-images.githubusercontent.com/13365687/33131504-042fc87c-cf97-11e7-9fd2-9eb8b99592a3.png)

**Comment by metas-lc** [comment]
IT
1. used down arrow in navigation menu from a window, e.g. Sales order
- press down arrow directly: the scrollbar didn't move, until i got to a lower data and it had to OK
- press down arrow after you write something in search field => scrollbar didn't move at all. It stopped on the last entry OK? (for me ok)

2. used down arrow in navigation menu from sitemap
=> right at first time pressing down arrow, the scrollbar moved a bit (both cases: before and after writing in search) - probably not in task's scope? might need to create task
