### ISSUE TITLE
Static Elements Translation for Date Range Picker

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1378]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the date Range Picker is not Translated when selecting a different Language.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please mak the static elements in date range picker translateable static elements.

![image](https://user-images.githubusercontent.com/13365687/33170639-4616157c-d049-11e7-8d4c-3124f1b359d2.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The date range picker translates as soon as the language is changed.
