### ISSUE TITLE
Provide referencing document when calling /rest/api/documentView/

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#138]
The POST /rest/api/documentView/ API changed as follows
* Method: use POST instead of PUT
* Body: we also require "referencing" property to be filled when calling from document references:
```
 "referencing": {
    "documentType": "string",
    "documentId": "string"
  },
```

See http://w101.metasfresh.com:8081/swagger-ui.html#!/document-view-rest-controller/createViewUsingPOST

![image](https://cloud.githubusercontent.com/assets/1244701/20947465/f6da0680-bc17-11e6-9dd6-8879efc1e249.png)

**Comment by teosarca** [comment]
NOTE: this task was created as a consequence of https://github.com/metasfresh/metasfresh/issues/663

**Comment by damianprzygodzki** [comment]
Should we change endpoint structure (the new one working only with slash)?

**Comment by teosarca** [comment]
I think this one was solved.
