### ISSUE TITLE
Shortcut for new document

### ISSUE THREAD

**Issue by PabloSichert** [metasfresh/metasfresh-webui-frontend#1380]
### Is this a bug or feature request?

Feature request.

### What is the current behavior? / Which are the steps to reproduce?

Shortcut for new document is `Alt`+`M`.

### What is the expected or desired behavior?

Previously, shortcuts combinations started with `Control` and `Control`+`N` was blocked for default browser behavior (new window).

New shortcut for new document `Alt`+`N` would be more intuitive.

**Comment by metas-lc** [comment]
IT
go to different document windows and use alt+n while in grid view, as well while on doc view 
=> new document appears OK
