### ISSUE TITLE
don't requerry closed view

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1384]
### Is this a bug or feature request?
bug
### What is the current behavior?
when you close "create purchase orders" you get an error in preview and console
#### Which are the steps to reproduce?
1. go to sales order and create a new one. Add a product
2. select th eline with the product and go to actions
3. create purchase orders
4. set a qty to purchase and press done directly
=>
error:"Not Found"
exception:"de.metas.ui.web.exceptions.EntityNotFoundException"
message:"No view found for viewId=ViewId(windowId=SO2PO, viewId=SO2PO-7cf27cceb536433f886ad11aa1761856, parts=[SO2PO, 7cf27cceb536433f886ad11aa1761856])"
path:"/rest/api/documentView/SO2PO/SO2PO-7cf27cceb536433f886ad11aa1761856/1000036_2156423"

also please check case number 10 from https://github.com/metasfresh/metasfresh-webui-frontend/issues/1358
![patch](https://user-images.githubusercontent.com/16001666/33211572-d7c5ede2-d127-11e7-92f3-2dc110f09098.png)

Chrome version: 60.0.3112.113 (Official Build) (64-bit)
the qty send was not the correct one
please make sure that when you press done, to send everything that needs to be send

If it's not related, please create a task

**Comment by siemiatj** [comment]
@metas-lc I'm not sure if it's working properly as some of the fields are in German and I'm not sure if I'm clicking tho correct ones, but I don't see any errors ;)

**Comment by metas-dh** [comment]
works fine, see https://github.com/metasfresh/metasfresh/issues/4172#issuecomment-407336400
