### ISSUE TITLE
[alt]+a in main Grid View opens Advanced edit mode

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1389]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when selecting a row in grid view, and pressing [alt]+a then the advanced edit opens.
#### Which are the steps to reproduce?
Open sales order window, select a row, press [alt]+a.
### What is the expected or desired behavior?
Advanced edit shall only e available via [alt]+e (in grid and main view)

![image](https://user-images.githubusercontent.com/13365687/33330700-db465624-d45f-11e7-9aeb-a45246d5bb90.png)

**Comment by metas-ts** [comment]
CPed to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* [alt]+a: does not open Advanced Edit, but selects all rows: OK
* [alt]+e: opens Advanced Edit (in grid and main view)
