### ISSUE TITLE
View attributes: consider row's supportAttributes property before querying for attributes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1393]
### Is this a bug or feature request?
bug

### What is the current behavior?
If view layout has supportAttributes:true then frontend is always querying for attributes.

#### Which are the steps to reproduce?
See https://github.com/metasfresh/metasfresh-webui-frontend/issues/1357#issuecomment-347906196

![image](https://user-images.githubusercontent.com/1244701/33389122-85e0820a-d53a-11e7-8433-5c6a2e71049a.png)

### What is the expected or desired behavior?
Querying for view attributes if 
* layout has supportAttributes:true (as it is now)
* **AND** the row does NOT have supportAttributes:false. If is true or missing, it shall be ignored.

**Comment by teosarca** [comment]
got following issue while playing in picking.
Steps are something like:
* picking https://w101.metasfresh.com:8443/window/540345
* select some lines and call Pick
* make sure on left side you have several lines
* pick on first line, select some picking slot, "open HUs to pick"
* on left side, select the second line
=> sometimes, when you do things like this, application crashes and the screen remains blank.
In console i got:

![image](https://user-images.githubusercontent.com/1244701/33576451-8c2c2bb6-d948-11e7-9b6f-fa132fa4cd4e.png)

NOTE: i am on it

**Comment by teosarca** [comment]
fixed.
@wiadev  can u pls review: https://github.com/metasfresh/metasfresh-webui-frontend/commit/5eace2655ac4dc6031e202a158593b1d0771f409

**Comment by metas-lc** [comment]
IT
1. hu editor
=> open it only with CUs - supportAttributes:true, attributes are queried OK
=> open it with TUs and/or LUs 
TU only - supportAttributes:true, attributes are queried OK
TU and LU -supportAttributes:false, attributes are not queried OK
(actually in case the HUs are aggregated, supportAttributes will be false on CU level)

2. tried the picking testcase above several times - no errors OK

3. tested step 1 in manufacturing as well. => works the same OK
