### ISSUE TITLE
View field editor: Patch request isn't sent after hit enter

### ISSUE THREAD

**Issue by wiadev** [metasfresh/metasfresh-webui-frontend#1396]
### Is this a bug or feature request?

Bug
follow-up of #1358 

### What is expected:

Needs to send a Patch request after hit enter

**Comment by teosarca** [comment]
note to IT:
test how pressing enter in various text/number fields is behaving

**Comment by metas-lc** [comment]
IT

I. normal vindow

A. grid view
1. open e.g. product price window

2. edit a price field, press enter 
(for now only numeric fields are editable in grid view)
=> patch request sent. OK 
=> the cursor is still in that field. OK

3. edit a numeric field, press enter, then edit it again without leaving the field
=> patch is sent OK 

B. Document vew

1. open e.g. product price window and select a line - open doc view

2. start editing a search field, press enter 
=> patch sent OK

3. same, edit numeric, dropdown and text fields
=> patch sent OK

4. edit a numeric field, press enter, then edit it again without leaving the field
=> patch is not sent NOK 
(if you refresh the page you will see the last value that was set. Not the new one)

5. edit a date field, press enter
=> patch is not sent NOK

C. Included tab

1. go to e.g. sales order, create a new one and add a line

2. edit numeric, dropdown fields, press enter
=> patch sent OK

3. edit a numeric field, press enter, then edit it again without leaving the field
=> patch is not sent NOK

4. edit a date field, press enter (e.g. Product windoww, cu-tu allocation tab)
=> patch is not sent NOK

II. modal window

A. Process

1. create a sales order, add a line, select the line

2. go to actions, run "Create Purchase Orders"

3. edit qty
=> patch is sent OK

4. edit date
=> patch is not sent NOK

5. edit a numeric field, press enter, then edit it again without leaving the field
=> patch is sent OK 


B. Advanced Edit

1. product sales order window, open advanced edit

2. edit a numeric field or a text field, press enter, then edit it again without leaving the field
=> patch is not sent NOK 

3. edit a date field, press enter
=> patch is not sent NOK 

Created follow-up for the NOKs: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1430
