### ISSUE TITLE
Buttons for triggering modal popup layouts

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#14]
To be used with:
- advanced edit
- generic "add new"

Need this to be provided from API. TODO: Agree on API format for this.

**Comment by cadavre** [comment]
"Advanced edit" is now in:
1) Top overlay menu (to be generated from API)
2) Mouse right-click context menu (to be generated from API)

With "Add new" can we assume there always gonna be a possibility of adding new document in every tab? If no maybe we can introduce additional flag to `tabs: []`? Or maybe go little bit more robust and we shall introduce API for generating tab top elements (Add new, Delete, Select all, Filter input) etc.?

**Comment by teosarca** [comment]
> With "Add new" can we assume there always gonna be a possibility of adding new document in every tab? 

Actually no. And more, in some cases the tab becomes readwrite/readonly dynamically, when u for example edit something in the header.

So i think we would ALSO need to extend the /commit & /data responses to provide this information (i.e. tab become RW/RO).

**Comment by cadavre** [comment]
How you gonna provide API for menu overlay and right mouse click in tables? Maybe we should put it in some separate `/api/endpoint`. `/commit` and `/data` are growing too big.

**Comment by teosarca** [comment]
I would suggest to hardcode it for this iteration. In meantime i would think how to provide this info. Also, if u have any idea, pls let me know.

> Maybe we should put it in some separate /api/endpoint. /commit and /data are growing too big.

Hmmm... Yes and no. Think to following case: you changed a field in header and a consequence one of the tabs become readonly or invisibile.
In this case, i think, at least some "signaling" shall happen in /commit response.
Wdyt?

**Comment by damianprzygodzki** [comment]
The new one is the batch entry disable property (what about we talked today), i think it is related.
