### ISSUE TITLE
Fix grid-view line editing

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#140]
After creating a line in a document ( for instance, sales order), there are several problems if you want to edit it in grid view ( without advanced editing)
1. If you want to modify the product, you can only delete the name of the old product and start writing the name of the new one, and it looks very ugly: 

![product editing start](https://cloud.githubusercontent.com/assets/16001442/20962056/71a9127c-bc70-11e6-8bcd-08233b04178e.png)

![product editing](https://cloud.githubusercontent.com/assets/16001442/20963244/5014559a-bc75-11e6-8f26-6695e1233722.png)

2. You cannot change the trading unit: 

![trading unit](https://cloud.githubusercontent.com/assets/16001442/20962150/ce0b3d88-bc70-11e6-8d74-66206bb3a46c.png)

3.  If you change the product in a line the trading unit remains the same  in grid but in the advanced editor it is changed: 

![cherry tomato grid](https://cloud.githubusercontent.com/assets/16001442/20962404/d6ce832a-bc71-11e6-8c70-6e4579e190f4.png)

![cherry tomato advanced](https://cloud.githubusercontent.com/assets/16001442/20962466/1191c42c-bc72-11e6-90ca-7aaf92e566d1.png)

 If you create a shipment without completing it, you can also edit its line. 
* Same problem with Product as in point 1
* Same problem with trading unit as in point 2, 3

4. If you click on "diff Product" the field is not aligned: 

![shipment diff product](https://cloud.githubusercontent.com/assets/16001442/20962833/a112b984-bc73-11e6-8870-98200d4a7af9.png)

Update: The same happens if I click on "Sales Order Line"

![sales order line select](https://cloud.githubusercontent.com/assets/16001442/20969104/36ecf868-bc90-11e6-9575-dec45df9e005.png)

5. In shipment, if you click on Activity from grid view, you see "none" even if the values are correct in inspection. In advanced editing you can select activity: 

![grid activity](https://cloud.githubusercontent.com/assets/16001442/20962929/1666a3bc-bc74-11e6-9d72-beb74e64d6d8.png)

![advanced activity](https://cloud.githubusercontent.com/assets/16001442/20962933/1a7426be-bc74-11e6-90ef-6b23330416fc.png)

**Comment by Dunkat** [comment]
1. "If you want to modify the product, you can only delete the name of the old product and start writing the name of the new one" - it's normall behaviour of lookup widget, you need delete previous name and write new name. Horizontal scroll was removed, I guess now it's look nicer.
2,3,4,5 - fixed. We changed a bit dropdowns. Now under table is place to show dropdowns.
