### ISSUE TITLE
login form selects 2 items from roles dropdown

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1404]
### Is this a bug or feature request?
Bug
backend: https://github.com/metasfresh/metasfresh-webui-api/issues/714

#### Which are the steps to reproduce?
on w101,
* login using "metasfresh" user
* take a look at roles dropdown and try to hover one of the Admin items => both Admin items are selected
![image](https://user-images.githubusercontent.com/1244701/33545001-7e99f1f8-d8e5-11e7-9c45-f67c6cf28c0c.png)

### What is the expected or desired behavior?
Only the items I hover shall be selected

**Comment by metas-lc** [comment]
IT
config: added a new org, made Admin role webui user
logged in with metasfresh 
=> i have both Admin with metasfresh and with test
=> only the one i hover is selected
=> i can login with each
OK
