### ISSUE TITLE
Lookup dropdown not Closing after selection w/ [enter/CR]

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1405]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently when selecting a row in lookup widget (arrows top/down, confirming w/ enter/cr), then the dropdown list is not closed. It only closes when clicked on entry per mouse.
#### Which are the steps to reproduce?
Try whats described above in Purchase Order. Select "Test Lieferant". The drop-down fro contact is opened and shows the behavior.
### What is the expected or desired behavior?
Shall work (close the dropdown list after keyboard selection w/ [enter/cr]

![image](https://user-images.githubusercontent.com/13365687/33549173-ec55e1bc-d8e9-11e7-97fd-c2a7773b7f55.png)

**Comment by ottosichert** [comment]
After playing around a little bit with https://w101.metasfresh.com:8443/window/181/1000203 I am getting another issue:

- Open link (see above)
- Click name (e.g. `Fritzen, Fritz`) of **Delivery from**
- Drop down list opens **=> OK**
- Click another name (e.g. `Testensen, Test`)
- Nothing happens! **=> NOK**

I will resolve https://github.com/metasfresh/metasfresh-webui-frontend/issues/1405#issue-278952194 before I will further investigate this

**Comment by metas-mk** [comment]
moin @ottosichert checked what you described above (info: haven't merged yet)
I cannot reproduce.

a) select contact in Sales order delivery from (OK)
![image](https://user-images.githubusercontent.com/13365687/33591361-7ae78c64-d985-11e7-88ab-5e0a8c1c54ea.png)

b) select another contact, dropdown opens and contact is selectable
![image](https://user-images.githubusercontent.com/13365687/33591380-98b73fe6-d985-11e7-872d-95b849f8fc5f.png)
![image](https://user-images.githubusercontent.com/13365687/33591387-9e581600-d985-11e7-8406-1c08af8c8813.png)

**Comment by metas-ts** [comment]
cherry-picked to `2017-12` and `release`

**Comment by metas-dh** [comment]
Results of IT1

* Lookup dropdown closes after selection w/ [enter/CR] : OK
* selecting another contact in dropdown: OK

**Comment by ottosichert** [comment]
I submitted a new issue regarding my comment above https://github.com/metasfresh/metasfresh-webui-frontend/issues/1405#issuecomment-349138619: see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1418
