### ISSUE TITLE
Can not enter "-" into any text field

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1406]
### Is this a bug or feature request?
bug

### What is the current behavior?
when you enter "-" into a text field (single or multiline) nothing happens

#### Which are the steps to reproduce?
1. open partner window https://w101.metasfresh.com:8443/window/123/2156425
1. type "-" into any text field. e.g. description

**Comment by teosarca** [comment]
also, if there is some limited set of characters allowed, pls document which are those.

**Comment by metas-mk** [comment]
@metasnw works on w101

**Comment by wiadev** [comment]
@teosarca @metas-mk 
Could you explain me about the use case of COLLAPSE_INDENT & EXPAND_INDENT shortkeys?
Where can I check them?

**Comment by teosarca** [comment]
@wiadev  have no idea what are those :)
can u explain a bit what are those supposed to do?

**Comment by wiadev** [comment]
@teosarca 
we are listening COLLAPSE_INDENT('-') and EXPAND_INDENT('+') shortkeys on document level and it's preventing keydown events on text fields.

```
/* POS context */
    SELECT_ALL_LEAFS: `${mod}+S`,
    EXPAND_INDENT: '+',
    COLLAPSE_INDENT: '-',
```

Not sure what ``POST context`` is for. 
if possible, we should update to Alt+'+/-' but wanna make sure what these are for, first.

**Comment by teosarca** [comment]
ahhh, ok, those are for expanding/collapsing nodes in tree views like this one:
![image](https://user-images.githubusercontent.com/1244701/33654110-c958fe44-da77-11e7-9d88-27f01ac3bb0d.png)

which is broken for some reason. If it's easy/hotfixable, pls do it in this task.

About number/text fields: they should allow typing "+"/"-" characters without being intercepted on upper levels.

Hope I've answered your concerns.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* "-" can be entered in a number/text field: OK
* "-" & "+" working for expanding/collapsing nodes in tree views: OK
