### ISSUE TITLE
process result: open included view: handle profileId property

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1407]
### Is this a bug or feature request?
FR
required for https://github.com/metasfresh/metasfresh-webui-api/issues/717
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

### What is the current behavior?
After executing a process, the process could return the "openIncludedView" action.
That action has following parameters:
* windowId
* viewId

#### Which are the steps to reproduce?
Check the backend task, there is the use case which is using this feature.

### What is the expected or desired behavior?
The backend can also return the "profileId" string parameter.
In case it's provided, it shall be used when the view layout is fetched.

**Comment by teosarca** [comment]
note to it:
* regression on views: open, close, filter etc

**Comment by metas-lc** [comment]
IT
tested some views - opening, cloning, filtering inside the views - works fine OK
