### ISSUE TITLE
Process panel - mandatory flag is not respected

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#141]
Test case:
* try running a process which have mandatory parameters

NOTE:
* mandatory parameters are NOT marked in a way, so user have no idea what's mandatory and what not
* mandatory parameters are not validated so basically when user presses "Start" it relies on backend to throw an exception because one of the mandatory params were not set

e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/20963106/ba8616f8-bc74-11e6-9868-4e32e21bedfc.png)

**Comment by damianprzygodzki** [comment]
Mandatory fields are marked in a way. How do you want to marked them? We assumed that mandatory fields has blue outline.

**Comment by teosarca** [comment]
ahhh, forgot... but on the other hand seems that it wan't intuitive for me :))

Ok, we have just to solve the second part. How shall we deal with mandatory fields.
Atm, frontend it's just asking the backend the start the process and the backend throws an exception.
But from UX it would be nice if the user would notified in a nicer way...
wdyt?

**Comment by damianprzygodzki** [comment]
1) I can just avoid to sending call if all mandatory fields are not filled (that's how we handle now most of mandatory fields)
2) Displaying notifications with errors is one possible way for now to display errors in forms/widgets because we never talked about handling errors by widgets.

**Comment by teosarca** [comment]
@damianprzygodzki  you are right. I think we shall improve the backend as described here: https://github.com/metasfresh/metasfresh-webui/issues/88

wdyt?

**Comment by teosarca** [comment]
UPDATE: for any field we are providing now 2 more properties:
* valid : true | false
* validReason: "string" // reason why field is not valid

**Comment by damianprzygodzki** [comment]
#253 Check this related issue, and i think we should apply it for every widget (i am describing this particular case). Before implementation, we need assumption here, or there.

**Comment by cadavre** [comment]
@teosarca can you please verify if this issue is still up-to-date?

**Comment by teosarca** [comment]
quick checked, the "validStatus" is still not considered.

**Comment by teosarca** [comment]
not sure if the backend shall provide something more....

**Comment by cadavre** [comment]
AFAIK "when user presses "Start" it relies on backend to throw an exception" is what we all agreed on as front-end is *not* made for data validation – backend is responsible for it. In this perspective this issue is not valid.

**Comment by teosarca** [comment]
yup, ofc, the backend is validating it. let's close it for now.
