### ISSUE TITLE
Shortcuts for Clone & Letter not working

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1410]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Shortcuts for Clone & Letter are not working. Home button for jumping to 1st page also doesn't work.
#### Which are the steps to reproduce?
Try [alt]+w ( [alt]+r, in e.g. window 143:

![2017-12-05 11_49_29-metasfresh](https://user-images.githubusercontent.com/18696715/33605902-daabdbc4-d9bb-11e7-8dd2-3f448843fd2a.png)

### What is the expected or desired behavior?
Shortcuts shall work.

**Comment by metas-dh** [comment]
Update:
```Pos1``` (Home button) working fine, see #1663

**Comment by metas-lc** [comment]
IT
checked Try [alt]+w and [alt]+r => they work fine  OK
(checked on new and existing documents, in sales order)
also checked if home button is still working OK
