### ISSUE TITLE
view: don't allow user to sort by a given column if layout says so

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1414]
### Is this a bug or feature request?
FR
required for https://github.com/metasfresh/metasfresh-webui-api/issues/717
follow-up of https://github.com/metasfresh/metasfresh/issues/3078

### What is the current behavior?
Frontend allows user to sort by any column.

#### Which are the steps to reproduce?
* open handling units view: https://w101.metasfresh.com:8443/window/540189
* check the layout:
![image](https://user-images.githubusercontent.com/1244701/33637201-4a96c0fe-da28-11e7-9902-79d1a054e3e9.png)

### What is the expected or desired behavior?
If sortable:false the user shall not be able to click/sort on that column.

**Comment by teosarca** [comment]
@wiadev  thank's for PR. I've integrated, but i found following "visual" issue:
![image](https://user-images.githubusercontent.com/1244701/33721672-54d35822-db70-11e7-9151-f5d76cd40447.png)


If the column is not sortable:
* don't show that mouse icon
* don't change it's color or font when hover. 
Just keep the same aspect like when it's not hovered.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* if sortable:false the user shall not be able to click/sort on that column: OK
*if sortable:false don't show that mouse icon: OK
* if sortable:false don't change it's color or font when hover: OK
