### ISSUE TITLE
view: singleOverlayField filters are half broken

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1415]
### Is this a bug or feature request?
bug
required for https://github.com/metasfresh/metasfresh-webui-api/issues/721
https://github.com/metasfresh/metasfresh/issues/3078

#### Which are the steps to reproduce?
* open handling units view: https://w101.metasfresh.com:8443/window/540189
* open filter by barcode:
![image](https://user-images.githubusercontent.com/1244701/33653921-2cfdead2-da77-11e7-8708-37b434d56f15.png)
* write there one of the HU Code you can see on background, on a top level row (e.g. 1000040):
![image](https://user-images.githubusercontent.com/1244701/33653990-6aaa382c-da77-11e7-8b6b-059ec66fb724.png)
* press enter => the view is filtered so now only that HU is there
* remark: the filter button is blue which means we have an active filter there => OK
* press on filter button again and the Barcode single overlay field is displayed again but with following issues:
** the textbox is empty => instead the current param value shall be displayed AND the text shall be all selected so it would be convenient for user to replace it (i.e. to scan it using barcode scanner)
** make sure that in case of singleOverlayField filters, if the param value is empty/null the filter is taken out => atm this is not happening all the time
![image](https://user-images.githubusercontent.com/1244701/33655039-a87dcd8c-da7a-11e7-8c57-e18b21925496.png)

### What is the expected or desired behavior?
Fix those 2 issues reported above.

**Comment by teosarca** [comment]
> ** make sure that in case of singleOverlayField filters, if the param value is empty/null the filter is taken out => atm this is not happening all the time

Here is how to reproduce that one.
So after you filtered by some barcode, press on the filter button.
The overlay is displayed and the field is empty
* in case you press enter directly=> filter is not taken out (NOK!)
* write something in that field and then delete it, so the text box is empty and then press enter => filter is taken out (OK)

**Comment by teosarca** [comment]
@ottosichert  integrated the pull request.
For "frequent" filters is working (note frequest filter is a filter which is diplayed directly on main layout and not in the "Filters" dropdown).
But for those which are not frequent it still has to be fixed.

NOTE: in the task example the screenshots were made when the HU barcode was not a frequent filter, but by mistake i've made it frequent filter.
Now i am changing it back and will do a rollout to be able to test it.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* pressing filter button again after filtering for Barcode: textbox is not empty, but the Barcode entered earlier is still displayed and the full text is selected: OK
* pressing Enter again: same filter is applied: OK
* delete the textbow and press Enter directly after:  filter is taken out: OK
