### ISSUE TITLE
Shortcuts for delete modal window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1417]
### Is this a bug or feature request?
FR
### What is the current behavior?
In modal window for Delete, you cannot use Esc for Cancel or [alt]+Enter for Delete, you have to use the mouse.
#### Which are the steps to reproduce?
Try deleting e.g. a sales order or an orderline.
### What is the expected or desired behavior?
Shortcuts in modal window for Delete should work:
* Esc for Cancel
* [alt]+Enter for Delete

**Comment by siemiatj** [comment]
@metas-dh What modal windows should this work in, any examples ?

**Comment by metas-dh** [comment]
@siemiatj  i mean this one, in general:

![2018-06-06 09_15_38-metasfresh](https://user-images.githubusercontent.com/18696715/41022554-3e1aba8e-696a-11e8-9638-446b51d5b4ae.png)

=> When you want to work fast, using mainly shortcuts, you can't do that when trying to delete sth, you have to switch to mouse.
Btw, this is just nice-to-have.

**Comment by metas-lc** [comment]
IT
1. create a new sales order, add a line
2. select the line, press alt+Y
=> delete confirmation appears for the line OK
3. press Esc (to cancel it)
=> it closes, line is not deleted OK
4. press alt+Y again, press alt+enter (for delete) 
=>  it closes, line is deleted OK
5. press alt+D
=> delete confirmation appears for the order OK
6. press Esc (to cancel it)
=> it closes, document is not deleted OK
7. press alt+D again, press alt+enter (to delete) 
=>  it closes, document is deleted OK
