### ISSUE TITLE
Clicking on lookup list row does not update value in Firefox

### ISSUE THREAD

**Issue by ottosichert** [metasfresh/metasfresh-webui-frontend#1418]
### Is this a bug or feature request?

Bug

### What is the current behavior?

When clicking on one the attributes of a lookup list and then clicking one of the results the value is not updated **in Firefox**. (See https://github.com/metasfresh/metasfresh-webui-frontend/issues/1405#issuecomment-349138619)

#### Which are the steps to reproduce?

1.  Open https://w101.metasfresh.com:8443/window/181/1000203 in Firefox 58.0b9 (64-Bit)
2.  Click on _Delivery from_ `Fritzen, Fritz` (or on any other name of the last attribute)
3.  Lookup list opens => OK
4.  Navigate with arrow keys (top / down) to `Testensen, Test`
5.  Press enter
6.  Lookup list closes => OK
7.  Value is updated => OK
8.  Click on _Delivery from_ `Testensen, Test`
9.  Lookup list opens again
10. Click on `Ruthensen, Ruth`
11. Lookup list closes => OK
12. Value is not updated **=> NOK**

### What is the expected or desired behavior?

12. Value should be updated as well when clicking on lookup list row with mouse in Firefox

![image](https://user-images.githubusercontent.com/13365687/33549173-ec55e1bc-d8e9-11e7-97fd-c2a7773b7f55.png)

**Comment by siemiatj** [comment]
Just tested with 60 and seems to be working fine.
