### ISSUE TITLE
Favicon for PDF Tab

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#142]
metasfresh Favicon for PDF Tab needed. atm there is a favicon with a leaf.
![image](https://cloud.githubusercontent.com/assets/13365687/20963621/752039b4-bc6e-11e6-97da-9f2e262a330b.png)

**Comment by cadavre** [comment]
Print endpoints are on your servers (w101 in this case), so it's up to you to select favicon. :)

<img width="554" alt="zrzut ekranu 2016-12-07 o 11 19 12" src="https://cloud.githubusercontent.com/assets/461796/20963748/0125ebfc-bc6f-11e6-8b2f-e2610c5767f4.png">

**Comment by metas-mk** [comment]
ok, great. thx.

**Comment by metas-mk** [comment]
moved issue to webui backend
https://github.com/metasfresh/metasfresh-webui/issues/81
