### ISSUE TITLE
Connection lost displayed when unchecking a checkbox in Filter

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1426]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When unchecking a checkbox in Filter, and hitting Apply, the screen shows Connection lost.
#### Which are the steps to reproduce?
1. Open e.g. Handling Unit Editor
2. Click Filter, Default
3. Check "Included in other HU" checkbox, Apply
4. Open Filter again, uncheck "Included in other HU", Apply again: screen shows Connection lost, NOK

![image pasted at 2017-12-8 13-57](https://user-images.githubusercontent.com/18696715/33765090-a1ce0f12-dc17-11e7-8356-cafd3a09233a.png)

![image pasted at 2017-12-8 13-58](https://user-images.githubusercontent.com/18696715/33765100-ac331cea-dc17-11e7-9cb0-4f785f086fb3.png)

![image pasted at 2017-12-8 13-58](https://user-images.githubusercontent.com/18696715/33765132-ccc902c6-dc17-11e7-977e-788a814a9801.png)

### What is the expected or desired behavior?
Normal filtering

**Comment by metas-lc** [comment]
IT
repeated the testcase above => works fine, connection is not lost anymore, and the filter is applied OK
