### ISSUE TITLE
d3 errors on dashboard

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1427]
### Is this a bug or feature request?
bug
### What is the current behavior?
you get flooded with errors in console when you open the dashboard
#### Which are the steps to reproduce?
open https://w101.metasfresh.com:8443/ see console
![image](https://user-images.githubusercontent.com/16001666/33765427-7112af90-dc21-11e7-8c69-f8eb132743d1.png)

### What is the expected or desired behavior?
no errors

**Comment by wiadev** [comment]
@teosarca @metas-lc 
can't reproduce the error anymore.

Also, I found another issue while I'm playing around.

![screenshot at dec 09 21-16-43](https://user-images.githubusercontent.com/18234060/33799169-747ba974-dd26-11e7-89ae-d3f24852fb37.png)

**Comment by wiadev** [comment]
@teosarca the reason for this is we are getting negative values (less than 0) from the backend.
![screenshot at dec 13 17-40-43](https://user-images.githubusercontent.com/18234060/33950653-3a47c134-e02d-11e7-80e6-7f0a408f69f3.png)

How does it work? are we supposed to have negative values, as well?

**Comment by teosarca** [comment]
@wiadev  10x. I think this shall be handled on backend side and in case of pie charts always send positive numbers.

**Comment by wiadev** [comment]
@teosarca cool
FYI, it's not pie charts but bar charts are causing the issues.

**Comment by teosarca** [comment]
@wiadev  hmm, but on bar charts we shall be able to display negative numbers, isn't it?

**Comment by wiadev** [comment]
@teosarca we can draw negative values below the x-axis but at the moment, negative values are setting for heights.
height should be positive and y(position) should be changed.

do you want me to check?
and my question was if we were supposed to get negative values for bar charts.(e.g products)

**Comment by teosarca** [comment]
> do you want me to check?

yes pls

> and my question was if we were supposed to get negative values for bar charts.(e.g products)

depends on each bar chart, but i don't see why not.

**Comment by metas-ts** [comment]
i can also see a number of interesting cases for negative bar charts (scnr)

**Comment by wiadev** [comment]
@teosarca 
![screenshot at dec 15 01-07-59](https://user-images.githubusercontent.com/18234060/34030957-d2a039b8-e134-11e7-9503-05cb56e9e7e0.png)
you can hardly see it because the offset(negative number) -6.9 vs 64000(max).

FYI, I've added additional x-axis at y:0 if there is a negative value to make it more visible.

**Comment by teosarca** [comment]
did a quick test: open the dashboard and look at that barchat with negative numbers.
Each time it's refreshed (atm it's configured each second) the barchart is animated, even there was NO change => NOK

![image](https://user-images.githubusercontent.com/1244701/34069680-65e237b0-e25e-11e7-870a-0ed83904c386.png)

![image](https://user-images.githubusercontent.com/1244701/34069675-4cd40f6e-e25e-11e7-9c3b-2a2b4b75db1a.png)

**Comment by wiadev** [comment]
@teosarca is it refreshed every second? on my end, it's refreshed very occasionally. 
Also, we set the animation in d3 library and we are not keeping the previous data. so we don't know if data was changed or not.

**Comment by teosarca** [comment]
@wiadev  but it's weird that only for this one is happening. All the others, AFAIK, are moving nicely when data is changed.

**Comment by metas-mk** [comment]
Quick test before merge
![image](https://user-images.githubusercontent.com/13365687/34483546-9718e95a-efbf-11e7-94c1-5bd0d7a606c7.png)

**Comment by teosarca** [comment]
@metas-mk  we need a barchart with negative values in order to test the feature.

note to IT: try to create some negative sales orders or something just to have an negative revenue for some of those products.

**Comment by metas-lc** [comment]
IT
created/completed a sales order with qty -100
checked dashboard: looks like this (NOK)
![image](https://user-images.githubusercontent.com/16001666/34721729-8f4a86ec-f54c-11e7-993d-013c880644f8.png)
rest is ok: no refreshing and no errors (OK)

**Comment by wiadev** [comment]
@metas-lc confirmed on w101. leave the negative values as it is while I'm working, please.

**Comment by metas-lc** [comment]
@wiadev btw i think on w101 the task is not rolled out. I was testing somewhere else. I won't change the values on w101. Let me know if you need rollout

**Comment by wiadev** [comment]
@metas-lc even though you didn't roll out, you updated the w101 DB to have negative values to test, right?

**Comment by metas-lc** [comment]
@wiadev yes, i wanted to confirm it's a bug. But then i noticed it doesn't look like it was rolled out. You can remove the order i did: https://w101.metasfresh.com:8443/window/143/1000297
from now on, i won't change numbers :)

**Comment by wiadev** [comment]
@metas-lc no I need those numbers so I can reproduce on my end, as well. :) all good. leave them, please.

**Comment by wiadev** [comment]
@metas-lc can you roll out this on w101 and test again?

**Comment by metas-lc** [comment]
IT
checked again, looks fine and there are no errors
