### ISSUE TITLE
Cases when Patch request isn't sent after hit enter

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1430]
### Is this a bug or feature request?
bug
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1396
### What is the current behavior?
there are cases where patch req. is sent when you hit enter, and sometimes not
#### Which are the steps to reproduce?
you can see the whole testcase here: follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1396

Example of cases when it works: 
1. sales order - create purchase orders action - qty field
=> you can edit it and press enter as many times as you want. the patch is sent OK
![image](https://user-images.githubusercontent.com/16001666/33767572-c707b7fc-dc2a-11e7-9ef5-4b44e5ee77ab.png)

same for grid view: (works)
![image](https://user-images.githubusercontent.com/16001666/33767547-aece6424-dc2a-11e7-9e28-52ba65ed6d3d.png)

Example of cases where doesn't work:
edit+enter:
1. sales order - create purchase orders action - date field
=> you can edit it and press enter => the patch is not sent NOK
![image](https://user-images.githubusercontent.com/16001666/33767431-31bfbcd0-dc2a-11e7-85ba-92062375fb47.png)

2. same happens for date in document view, included tab, advanced edit:
![image](https://user-images.githubusercontent.com/16001666/33768048-30c5f314-dc2d-11e7-92c9-3d21e2cb623e.png)

![image](https://user-images.githubusercontent.com/16001666/33768104-5746cd06-dc2d-11e7-9303-ebe960f80d85.png)

edit+enter 2 times:
1. see document view, included tab and advanced edit, when you edit a field of type text or numeric, where your cursor remains there after enter, if you edit AGAIN, the patch is not sent. E.g.
![image](https://user-images.githubusercontent.com/16001666/33768234-e9c1ef9e-dc2d-11e7-85d7-35c0541877dd.png)

### What is the expected or desired behavior?
press enter after edit on any fields - send patch
edit - enter - edit and enter again - send patch each time

**Comment by siemiatj** [comment]
@metas-lc  For some fields this was changed that patch is now sent when field is edited, and then tabbed away (table cells, date input). Not sure if this solves the problem well enough.

**Comment by metas-lc** [comment]
checked again
Date fields in docview, included tab and advanced edit (in order and product cu-tu alloc) => works now (both enter and tab) OK
also edit - enter - edit and enter again => patch is sent each time OK

create purchase order process from sales order - a patch is sent after you press enter.OK
