### ISSUE TITLE
Problem regarding multiple filters

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#1435]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The problem should be visible in this screenshot:
![image](https://user-images.githubusercontent.com/1264789/33831172-44370356-de77-11e7-9311-ed39fc6c978d.png)

* The first filter with id `materialCockpitDateOnlyFilter` seems OK, but in the sencond filter, the parameter `ProductName = "Conv"` is not poperly displayed.
* instead, it looks as if the first filter's value is somehow used in the second filter.

@teosarca said that this problem might be related to view: singleOverlayField filters are half broken #1415

in case it helps: this is the filters layout info
```json
"filters": [{
		"filterId": "materialCockpitDateOnlyFilter",
		"caption": "Datum",
		"frequent": true,
		"parametersLayoutType": "panel",
		"parameters": [{
			"caption": "DateGeneral",
			"parameterName": "DateGeneral",
			"widgetType": "Date",
			"range": false,
			"mandatory": true,
			"displayed": true,
			"readonly": false,
			"type": "primary",
			"showIncrementDecrementButtons": true
		}]
	},
	{
		"filterId": "materialCockpitAllParamsFilter",
		"caption": "Produkt",
		"frequent": true,
		"parametersLayoutType": "panel",
		"parameters": [{
			"caption": "ProductName",
			"parameterName": "ProductName",
			"widgetType": "Text",
			"range": false,
			"mandatory": false,
			"displayed": true,
			"readonly": false,
			"type": "primary"
		},
		{
			"caption": "Value",
			"parameterName": "Value",
			"widgetType": "Text",
			"range": false,
			"mandatory": false,
			"displayed": true,
			"readonly": false,
			"type": "primary"
		}]
	}]
```

#### Which are the steps to reproduce?

I get this ierror in the task branches of issue metasfresh/metasfresh-webui-api#706, so you can't yet reproduce *this* problem in `master` ..but maybe it also happens in other multipfilter-scenarios..

I'm working towards a WI for issue metasfresh/metasfresh-webui-api#706, so we also get this in `master`..but maybe you can already take a look?

**Comment by ottosichert** [comment]
See my PR #1439 which fills the filter values to the dropdown widgets.

I believe it was introduced by #1419 or #1423 (regarding #1415) but I could not narrow it down to either one.

@metas-ts Can you provide me a similar setup where I can debug your exact issue if #1439 does not fully resolve this?

**Comment by metas-lc** [comment]
IT
opened window Material cockpit 540376
used both filters
=> 
Date: 19.12.2017
Filter by: &Product
OK
(& you see there is backend. Created task: https://github.com/metasfresh/metasfresh-webui-api/issues/765)
