### ISSUE TITLE
Language bug: The language in Settings is not respected

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1437]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* When opening the webui with a certain language selected in setting, sometimes thi language is not respected. 
* Checked in inspection.
* => NOK: Accept-Language:key

![image](https://user-images.githubusercontent.com/16001442/33838933-82fd230a-de99-11e7-9de1-8935eaccf0b5.png)

* The info is correct from the backend: 

![image](https://user-images.githubusercontent.com/16001442/33838975-9f8ed3b0-de99-11e7-983e-46f99eb2a3e8.png)

#### Which are the steps to reproduce?
* Select a language in settings, close the app, open it again. Check the language of the menu.
### What is the expected or desired behavior?
* The language that was selected in settings shall always be respected as soon as it ws set.

**Comment by teosarca** [comment]
frontend issues were fixed but there are some backend issues too.
Test it when https://github.com/metasfresh/metasfresh-webui-api/issues/713 is integrated.

**Comment by metas-lc** [comment]
IT
had language english, logout, login => Accept-Language:en_US OK
changed language to german, logout, login => Accept-Language:de_DE OK
