### ISSUE TITLE
Typo in URL for rowId

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#144]
See steps to reproduce and url in task https://github.com/metasfresh/metasfresh-webui/issues/82

Problem is that in this URL : http://w101.metasfresh.com:8081/rest/api/window/data?type=181&advanced=true&id=1002853&tabid=1&rowid=1002891 
there should be "rowId" with Capital "I" ( because it's case sensitive)

**Comment by teosarca** [comment]
i think that shall be solved when we will use the new REST API, i.e. http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDataUsingGET

**Comment by teosarca** [comment]
i think this one was solved. Can somebody confirm that?

**Comment by damianprzygodzki** [comment]
I can't reproduce.
