### ISSUE TITLE
Dropdown in Grid view needs two-time click again 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1440]
### Is this a bug or feature request?
Bug
### What is the current behavior?
If there are >1 values in dropdown list, you need to click two times for selection.
#### Which are the steps to reproduce?
see #1347: was already fixed there, but is happening again
### What is the expected or desired behavior?
Should work the first time.

**Comment by PabloSichert** [comment]
This has most likely been reintroduced by https://github.com/metasfresh/metasfresh-webui-frontend/pull/1432

**Comment by PabloSichert** [comment]
Note to IT:
- Make sure https://github.com/metasfresh/metasfresh-webui-frontend/issues/1421 did not break with this change

**Comment by metas-mk** [comment]
@PabloSichert quick test. the fix breaks #1421 again
![image](https://user-images.githubusercontent.com/13365687/34042389-c9ce8c3c-e19c-11e7-9823-29836dc9918c.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in last weekly release e2e

* Dropdown in Grid view: selection works the first time: OK
* Dropdown lists do not remain displayed after losing focus: OK

**Comment by metas-dh** [comment]
Update: also worked fine in this week's e2e.
