### ISSUE TITLE
Attributes are empty in material receipt candidate

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1444]
### Is this a bug or feature request?
Bug
### What is the current behavior?
All attributes are empty/null in material receipt candidate, therefore weighing cannot be done correctly 
#### Which are the steps to reproduce?
1. Have a material receipt candidate with UOM:kg
2. Open HU Editor, with e.g. 1LU/1TU config: weight gross: empty, all other attributes are empty/null: NOK

![2017-12-13 13_46_12-metasfresh](https://user-images.githubusercontent.com/18696715/33940235-83f638e8-e00e-11e7-9900-9fc4735e1e36.png)

3. Set a weight, check the qty in the HUs: no change, NOK

![2017-12-13 13_47_49-metasfresh](https://user-images.githubusercontent.com/18696715/33940250-8e40af72-e00e-11e7-85c4-48a4b615daf3.png)

4. Select the TU: weight gross: empty, NOK

5. Select the LU again: weight gross: empty again, NOK

6. Create the receipt: only now you can see the weight that was set

![2017-12-13 13_49_15-metasfresh](https://user-images.githubusercontent.com/18696715/33940267-9e162fb2-e00e-11e7-8efd-fd656f78459d.png)

### What is the expected or desired behavior?
Attributes shall be displayed as provided by API.

**Comment by metas-dh** [comment]
shall be fixed by #1441

**Comment by teosarca** [comment]
looks like it's fixed

**Comment by metas-lc** [comment]
IT
weights are set OK
changing gross weight updates the net weight  OK
