### ISSUE TITLE
Tab in purchase order batch entry not working correctly

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1446]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Tab is not working correctly in batch entry of purchase order
#### Which are the steps to reproduce?
Case I:
1. Have a product with a packing item set in CU-TU Allocation, for purchase
2. Create a purchase order
3. In batch entry, start writing the product name: product is displayed
4. Select the product with mouse: the packing item is set, OK
5. Press Tab, to get to qty field: nothing happens: NOK
6. Press Tab again: cursor is in price system: NOK

Case II:
1. Have a product with a packing item set in CU-TU Allocation, for purchase
2. Create a purchase order
3. In batch entry, start writing the product name: product is displayed
4. Select the product using Enter: the packing item is set, OK
5. Press Tab, to get to qty field: nothing happens: NOK
6. Press Tab again:  cursor is in qty field, but packing item is now empty: NOK

**Comment by metas-dh** [comment]
update:
in weekly e2e, Case II worked fine, but Case I was still NOK

**Comment by siemiatj** [comment]
Seems to be related to #1675 . Worth re-testing after #1695 is merged.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

retested both cases, case II: works fine now as well (in both sales & purchase order): OK
