### ISSUE TITLE
Batch entry: cursor jumps directly to HU

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1451]
### Is this a bug or feature request?
bug
### What is the current behavior?
when you press on batch entry (alt+q) the cursor jumps directly to HU
#### Which are the steps to reproduce?
1. create a new order (e.g. sales order https://w101.metasfresh.com:8443/window/143/1000243)
2. press on batch entry (or use alt+q)
=> notice the cursor is on the second field NOK
![image](https://user-images.githubusercontent.com/16001666/33992306-b8f2dbce-e0da-11e7-9494-225a3732da86.png)

### What is the expected or desired behavior?
cursor shall be on first field, on product

**Comment by metas-mk** [comment]
Important: Please also check [alt]++. Same behavior there.

![image](https://user-images.githubusercontent.com/13365687/33992514-3b6824c2-e0d3-11e7-9d7a-358a7635f836.png)

**Comment by teosarca** [comment]
pls do not cherry pick this week !

**Comment by teosarca** [comment]
note to IT: pls test it together with https://github.com/metasfresh/metasfresh-webui-frontend/issues/1433.

**Comment by metas-lc** [comment]
IT
repeated the testcase above, with click, alt+q and alt++ => cursor is on the first field (product field) OK
