### ISSUE TITLE
Refactor dropdown component

### ISSUE THREAD

**Issue by PabloSichert** [metasfresh/metasfresh-webui-frontend#1459]
### Is this a bug or feature request?

Bug

### What is the current behavior?

Currently the dropdown component exists of two large files [RawList.js](https://github.com/metasfresh/metasfresh-webui-frontend/blob/master/src/components/widget/List/RawList.js) and [List.js](https://github.com/metasfresh/metasfresh-webui-frontend/blob/master/src/components/widget/List/List.js) which don't have test coverage and carry a lot of complexity. They have been patched around and the same issues keep coming up again, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1347 / https://github.com/metasfresh/metasfresh-webui-frontend/issues/1440 for example.

### What is the expected or desired behavior?

Create a new dropdown component that works predictably and has maintainable, easy to understand code.

**Comment by siemiatj** [comment]
Dropdown was already refactored to a separate component `SelectionDropdown`. Closing this one.
