### ISSUE TITLE
Header issues after last rollout (Breadcrumb Menu & Space, Notification pill)

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#146]
Header issues after last rollout (Breadcrumb Menu & Space, Notification pill).
Pls fix directly.
![image](https://cloud.githubusercontent.com/assets/13365687/21140291/75dc02fc-c137-11e6-80af-5999c8bd9ebb.png)

**Comment by metas-mk** [comment]
Fixed in current rollout with this commit
https://github.com/metasfresh/metasfresh-webui-frontend/commit/3c0b0fdd844e66914a7a37147078df06f75c3673

**Comment by teosarca** [comment]
10x mark for documenting
