### ISSUE TITLE
frontend: Processes: when calling a process frontend shall provide which are the selected rows in the left/right view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1465]
### Is this a bug or feature request?
FR
backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/755
part of https://github.com/metasfresh/metasfresh/issues/3190

### What is the current behavior?
When calling a process from a view, or when we ask for actions or quickActions,
frontend provides the current selected row IDs (i.e. viewDocumentIds).

### What is the expected or desired behavior?
Frontend shall also provide informations about the view child or parent view and what rows are selected there.

i.e.
![image](https://user-images.githubusercontent.com/1244701/34072459-81f4628e-e290-11e7-9fba-bc4b77dc48cb.png)

Affected endpoints are:
* [GET /rest/api/documentView/{windowId}/{viewId}/actions](http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/getDocumentActionsUsingGET)
* [GET /rest/api/documentView/{windowId}/{viewId}/quickActions](http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/getDocumentQuickActionsUsingGET)
* [POST /rest/api/process/{processId}](http://w101.metasfresh.com:8081/swagger-ui.html#!/process-rest-controller/createInstanceFromRequestUsingPOST)

Things to consider:
* when i am changing the selection on the right side view (the child view) we need to update the quick actions of the left side view (parent) because the childViewSelectedIds changed
* same for other properties, basically the quick actions needs to be updated when any of the variables on which depends is changed.

#### How to dev-test it
* open Picking Tray clearing: https://w101.metasfresh.com:8443/window/540371
* select something on left side view and (maybe?) something on right side
* observe the WEBUI_TestParentChildParams action; the caption will show in parenthesis if parent or child selected rows were provided 
* call it; the action will return a string which tells if parent/child rows were provided.
![image](https://user-images.githubusercontent.com/1244701/34108018-19e9c7ce-e407-11e7-8826-800d06b19c7d.png)

**Comment by ottosichert** [comment]
@teosarca Thanks for the excellent dev-test action :+1:

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/758
