### ISSUE TITLE
Filters: clicking on scrollbar removes what is written in field

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1466]
### Is this a bug or feature request?
bug
### What is the current behavior?
Filters: if you start writing something in a search filter, and you click on the scrollbar to go lower to see all your options, what you wrote in the filter is gone
#### Which are the steps to reproduce?
here is the task where the scroll bar was added https://github.com/metasfresh/metasfresh-webui-frontend/issues/1293 might help
1. go to picking tray clearing
https://w101.metasfresh.com:8443/window/540371
2. select filter by business partner
3. start writing smth like "test"
![image](https://user-images.githubusercontent.com/16001666/34114036-4cdf1478-e41a-11e7-8ebb-05a0996d77d0.png)

=> you get more results and you want to see all
4. click on the scrollbar to move lower
=> the field is empty

(note: it works if you are using the scroll from the mouse. But not if you click the scrollbar)

### What is the expected or desired behavior?
it shall not remove what i wrote if i click on the scrollbar

**Comment by siemiatj** [comment]
@metas-lc  It's not really reproducible anymore, as the dropdown is outside of the filter panel now, so the scrollbar doesn't ever show up. It just needs to wait for #11724 to be merged first as it fixes some related console errors.

**Comment by metas-lc** [comment]
checked and the dropdown is outside as you said. Managed to find a similar case, where we have dropdown in filters and search field (see bill candidates window), and it works: you can use the scrollbar and the dropdown is not closing (note that it wasn't needed to use the scroll because the whole dropdown was visible) OK

**Comment by metas-lc** [comment]
i see #1724 was merged so i 'm closing this task
