### ISSUE TITLE
Advanced Edit shortcut not working correctly

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1467]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Advanced Edit shortcut does not work after you changed sth / clicked somewhere in the resp. window.
#### Which are the steps to reproduce?
1. Open a window, use [alt]+e directly: Advanced Edit view opens, OK
2. Open another window, change sth or just click somewhere in the window
3. Use [alt]+e again: Advanced Edit view does not open, you have to use Actions to get there: NOK
### What is the expected or desired behavior?
Shortfut [alt]+e shall always open Advanced Edit view.

**Comment by metas-lc** [comment]
IT
1. open a window, press alt+E => advanced edit opens OK
2 .open a document, select a line, press alt+e => advanced edit opens for the line OK
3. open another window, do some changes /clicks, press alt+e => advanced edit opens OK
4. do some changes in a line, select that line, press alt+e => advanced edit opens OK
