### ISSUE TITLE
changing an attribute from none to none

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1468]
### Is this a bug or feature request?
bug
### What is the current behavior?
error when you change a label from null into null 
#### Which are the steps to reproduce?
go to receipt candidates (window id 540196), select a line and open hu editor
set an attribute , e.g. label Bio
then set it to none 
then set it to none again

![image](https://user-images.githubusercontent.com/16001666/34165320-956aee18-e4e4-11e7-8c2c-f5965b3af1b1.png)

=> you get error in console NOK

### What is the expected or desired behavior?
should not get any error

**Comment by wiadev** [comment]
@metas-lc I can't reproduce it anymore. check it, please.

**Comment by metas-lc** [comment]
@wiadev i can still reproduce it. Try to set an attribute like label, from none to none. Seems only when using "none" happens. If i set it from Bio to Bio it works.

**Comment by siemiatj** [comment]
I don't get this error anymore @metas-lc .

**Comment by metas-lc** [comment]
i'm assigning this task on me, in IT. I'll retest it after https://github.com/metasfresh/metasfresh-webui-frontend/issues/1669 is done

**Comment by metas-lc** [comment]
checked it. Works now. No errors OK
