### ISSUE TITLE
Bug in long texts with new line

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1470]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* When inserting text in a long text field and press enter, I have to press it twice so it gets to the next line. Only what I inserted before the enter is saved.

#### Which are the steps to reproduce?
After the first enter: 

![image](https://user-images.githubusercontent.com/16001442/34250313-26385c62-e645-11e7-9649-dc7ef98348c8.png)

After I insert more lines, they are not sent to be saved

![image](https://user-images.githubusercontent.com/16001442/34250400-67d4b86e-e645-11e7-99be-2aaf9c46f9c5.png)

If I close and open again, only the first line is saved

![image](https://user-images.githubusercontent.com/16001442/34250440-84a1961a-e645-11e7-9828-bc9336d33198.png)

### What is the expected or desired behavior?
The whole text should be saved

**Comment by metas-rc** [comment]
Note: This bug is affecting this high prio task: https://github.com/metasfresh/metasfresh/issues/3209

**Comment by metas-mk** [comment]
Quick check. It seems as if the request takes too long (+25s). After the request is done the entries are also saved.
![image](https://user-images.githubusercontent.com/13365687/34640803-025af338-f2fa-11e7-8d4e-aea7501562bd.png)

**Comment by metas-mk** [comment]
Further topic. When moving the mouse over such a textarea field, it gets patched with every move.
![image](https://user-images.githubusercontent.com/13365687/34640814-300f227c-f2fa-11e7-8fb6-aa5aba651d7e.png)

**Comment by metas-mk** [comment]
Issue Description:
In LongText Fields it happens that the user presses "Enter" to create a LF/ CR. This KeyDown event trggered a patch. After patching the value was reset to a value without a trailing LF/ CR.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The long text fields now support inserting multiple rows with Enter. The text I inserted is fully saved.
