### ISSUE TITLE
Hover showing Element Content for flags wrongly

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1475]
### Is this a bug or feature request?
Feature Requests
### What is the current behavior?
Currently, when hovering over Switches (e.f. Active Flag) or YesNo Checkboxes in Grid View, the tooltip not shown properly. It shows [object Object].
#### Which are the steps to reproduce?
Open any Window in Grid View and hover over a Flag Column Element.
### What is the expected or desired behavior?
Don't show a tooltip when it's a Switch/ YesNo Widget.

![image](https://user-images.githubusercontent.com/13365687/34513287-e73ac28e-f067-11e7-8edf-1acbbbfbed90.png)

**Comment by metas-lc** [comment]
IT
checked several windows in grid view and hovered over a flag => no tooltip
hovered over other type like text, date, numeric => tooltip appeared OK
