### ISSUE TITLE
Finetune eMail Editor: To Field show Name instead of key

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1477]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the eMail Editor needs some detailed adjustments. The To: Field shows the user keys (instead of User Names.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Improve the eMail Editor Window and show the User Names in Result and in autocomplete.

**Comment by teosarca** [comment]
fixed in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1529
