### ISSUE TITLE
Attachment in eMail Editor: Show File name/ caption instead of key.

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1478]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Attachment key is shown in the email editor.
#### Which are the steps to reproduce?
Open and see.
### What is the expected or desired behavior?
Improve the eMail Editor Window and show the Attachment filename instead of the key.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: All the attachments I put in email were displayed with their file name. I tried with pdf, npng and txt files.
