### ISSUE TITLE
Tooltip for for "Select all"/ "Select all x rows"

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1485]
### Is this a bug or feature request?
fr
### What is the current behavior?
there is no tooltip on select all
#### Which are the steps to reproduce?
see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1222
### What is the expected or desired behavior?
tooltip shall be there for alt + a

**Comment by metas-rc** [comment]
Results if IT

Tested on webui

* OK: The tooltip "Alt + A" is displayed for both "Selet all on this page" and "Select all X elements"
