### ISSUE TITLE
editable views: sometimes the view's editable fields are PATCHed after the view was DELETEd

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1486]
#### Which are the steps to reproduce?
* open sales order: 
* select some lines and call "Create purchase order"
* press OK
When pressing OK, the frontend shall send back all the changed fields and then it shall delete the view.

Sometimes (NOT always!) this happens in reversed order (i.e. first the view is deleted) which ofc will trigger an issue on backend side.

### What is the expected or desired behavior?
ALWAYS, do the view patching BEFORE deleting the view.

**Comment by teosarca** [comment]
i think this one was fixed somewhere.....

**Comment by PabloSichert** [comment]
Is this the same as https://github.com/metasfresh/metasfresh-webui-frontend/issues/1361?

**Comment by teosarca** [comment]
totally.
Thanks Pablo.
closing it.
