### ISSUE TITLE
Rerunning process for the same selection is broken

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1487]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Rerunning the process transform for the same selected LU doesn't work.
#### Which are the steps to reproduce?
* Go in Handling Units Editor 
* Select a top level LU
* Go to its actions, click on transform
* => The viewDocumentIds in request is like this:  ["1000036"] (as a list of one element)
![image](https://user-images.githubusercontent.com/16001442/34719466-a346d686-f543-11e7-89be-c819ccde1154.png)
* Start the process (there is only one option for it, select it and press ok)
* When the process is done, we are back to the selected LU, and have the same actions available
![image](https://user-images.githubusercontent.com/16001442/34719613-1cd2391e-f544-11e7-89d3-f84dd821d4dc.png)
* Click on Transform again
* => NOK: Error: 
```
"Bad Request"
exception
:
"org.springframework.http.converter.HttpMessageNotReadableException"
message
:
"Could not read JSON document: Can not deserialize instance of java.util.HashSet out of VALUE_STRING token↵ at [Source: java.io.PushbackInputStream@7c52a210; line: 1, column: 96] (through reference chain: de.metas.ui.web.process.json.JSONCreateProcessInstanceRequest["viewDocumentIds"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.HashSet out of VALUE_STRING token↵ at [Source: java.io.PushbackInputStream@7c52a210; line: 1, column: 96] (through reference chain: de.metas.ui.web.process.json.JSONCreateProcessInstanceRequest["viewDocumentIds"])"
path
:
"/rest/api/process/ADP_540763"
status
:
400
timestamp
:
1515498672148
```

* Now the documentViewIds is like this: "1000036" (as a single element. The list is no more)
![image](https://user-images.githubusercontent.com/16001442/34719667-48f34b8c-f544-11e7-9a5b-382c914e114d.png)

### What is the expected or desired behavior?
* The process should work fine the second time we run it, too.
* The viewDocumentIds shall be considered list also after one process was already run.

**Comment by metas-lc** [comment]
i wanted to check if another task solved this issue, but now, after i do transform and come back to the HU Editor, the actions are not sent by the frontend anymore
(i tested it for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1481 )
![image](https://user-images.githubusercontent.com/16001666/34777972-9e01514c-f624-11e7-826c-1959e936fd92.png)

**Comment by metas-rc** [comment]
Another example for the quickactions not being sent: 
Task https://github.com/metasfresh/metasfresh/issues/3209

* Select a CU with serial number
* Give it another serial number
* After the process is done, the CU is still selected but there are no actions available because quickActions are not sent by the frontend.

**Comment by metas-rc** [comment]
The serial number bug seems to be fixed

**Comment by metas-rc** [comment]
The initial transform problem also looks fixed

**Comment by metas-rc** [comment]
And also the one from #1481
