### ISSUE TITLE
Avoid browser hard refresh on each rollout

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#149]

**Comment by cadavre** [comment]
How this is gonna be achieved @damianprzygodzki ?

**Comment by teosarca** [comment]
i guess the commits were:
* https://github.com/metasfresh/metasfresh-webui-frontend/commit/d92d78a40a420d03f2f9102fe8e9001f2c043134
* https://github.com/metasfresh/metasfresh-webui-frontend/commit/7da26394d163229dea8fe546632f8896910a4185

**Comment by teosarca** [comment]
reopening because it's not working when build with NPM. the webpage is empty because the bundle[hash].js was not found.

**Comment by damianprzygodzki** [comment]
Quick fixed.
