### ISSUE TITLE
Automated Javascript and React Testing with Jest

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1501]
### Is this a bug or feature request?
Evaluation
### What is the current behavior?
The Testing Framework used by Facebook to Test Javascript and React applications is Jest. Check out further Information her https://facebook.github.io/jest/
It seems easy to setup and has a cool feature called snapshots, which allow to ease the creation of valid results for the tests, in environments with fast changing and variable data. This could be a nice feature that we need for our automated testing based on data that can change in database in a short timeframe.
Additionally its said that Jest is 3 times faster than Mocha in Test execution.
#### Which are the steps to reproduce?
None.
### What is the expected or desired behavior?
Check and evaluate jest for the testing of metasfresh-webui-frontend.

Install Jest in metasfresh-webui-frontend:
```yarn add -D jest```

Run Jest in watch mode:
```yarn jest --watch```
then start test run for all current tests with ```a```

**Comment by metas-mk** [comment]
https://github.com/metasfresh/metasfresh-webui-frontend/pull/1569

**Comment by metas-rc** [comment]
Nothing to test. Moving to done.
