### ISSUE TITLE
Make a difference between internal date format (ISO) and user friendly locale date

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1504]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the date for patch (and sent to api) and the date presented to user are the same. This is not nice because the user wants a friendly looking date format.
#### Which are the steps to reproduce?
Open a date+time filter and check after selecting/ patching the date.
### What is the expected or desired behavior?
Distinguish between date that is used internally in api communication and the date that is presented to the user.

**Comment by metas-mk** [comment]
This the date looks like after selecting a date in date picker. NOK
![image](https://user-images.githubusercontent.com/13365687/35139619-336bb576-fcf4-11e7-9dcb-0507f49f8c65.png)

This is how the localized dates look like in DateRange Picker after selection. OK
![image](https://user-images.githubusercontent.com/13365687/35139660-6746929e-fcf4-11e7-9328-74772e5b51f8.png)

Please show a localized date to the user and only use the ISO formatted date for the API communication.

**Comment by metas-mk** [comment]
Quickly checked. Works nicely. Integrating.

**Comment by metas-rc** [comment]
I noticed each time I try to set a value in filters, my value is either ignored and not set or transformed into a date. I think this is because this change: 
![date bug](https://user-images.githubusercontent.com/16001442/35281866-a926f2c4-005c-11e8-96f1-40ee6ec1b009.png)

I checked the sources and this was not modified. That if that was splitting dates from everything else is still lost.

**Comment by metas-lc** [comment]
IT (not done yet)
1. about date issues on filters that are type text
![image](https://user-images.githubusercontent.com/16001666/35281926-d1ca8ede-005c-11e8-9f33-f5f52e1c98e8.png)

**Comment by wiadev** [comment]
@teosarca Can you add `widgetType` property under filters in the following API?
```
http://w101.metasfresh.com:8081/rest/api/documentView/143/143-e884ba61e1984beab6dd6b118fd15718?firstRow=0&pageLength=20
```

![screenshot at jan 24 20-17-52](https://user-images.githubusercontent.com/18234060/35367441-e53e2f38-0143-11e8-97ec-ce1570705af0.png)

**Comment by teosarca** [comment]
@wiadev  that might be tricky... 
* why is needed?
* the info is available in view's layout. why not fetching it from there?

**Comment by teosarca** [comment]
another issue, Email window - Templates dropdown is not working either.
I think the whole dropdown component is affected.

![image](https://user-images.githubusercontent.com/1244701/35386512-f683abce-01d4-11e8-8f17-a6ba8f5cfae1.png)

**Comment by wiadev** [comment]
@teosarca right now, the logic is parsing the filter values based on widgetType.

for table rows, since columns are returned all together, it works fine but for filters, we are missing widgetType so it failed parsing data.

**Comment by metas-mk** [comment]
@wiadev Found after latest PR. Hint: Does not occur w/ locale de_DE. Reproducible w/ en_US
![image](https://user-images.githubusercontent.com/13365687/35391490-2981945a-01df-11e8-9ead-3f11836f4828.png)

**Comment by teosarca** [comment]
found another issue, goto http://localhost:3000/window/540189 and click on Barcode fiter

![image](https://user-images.githubusercontent.com/1244701/35439314-da2a49dc-02a2-11e8-9af8-ff599fc13210.png)

![image](https://user-images.githubusercontent.com/1244701/35439325-e156df7c-02a2-11e8-86c3-860b729770e6.png)

**Comment by teosarca** [comment]
found another issue, goto sales orders view, filter by DocStatus (i.e. anything else but let the date fields empty)

![image](https://user-images.githubusercontent.com/1244701/35439416-5300b846-02a3-11e8-90a6-01506d46d159.png)

![image](https://user-images.githubusercontent.com/1244701/35439431-60be9b88-02a3-11e8-9974-62ee09a3b94d.png)

**Comment by metas-lc** [comment]
IT 
Please check no 4!


retested the cases above:
1. promised date filter looks nice - after you set it and after you open the filter again OK

2. checked other filter types - works now OK
(also the barcode OK)

3. promised date filter keeps the date i set each time you open it OK

4. attributes in hu editor: when i want to set a Date filter, when i am selecting a date, the calendar disappears and the HU line gets deselected, so i can't set it NOK
(rest filters types are working)

5. selecting template in email works OK

6. normal date filter works fine OK

**Comment by metas-lc** [comment]
i am getting an error in console when i add bpartner in new sales order
![image](https://user-images.githubusercontent.com/16001666/35442163-eb6fec54-02ae-11e8-8ac1-96c9fe805cdc.png)

**Comment by metas-lc** [comment]
IT
repeated all testcases above: 
all work fine besides: 
hu editor - set a date attribute => it sets the day before the one you set

![image](https://user-images.githubusercontent.com/16001666/35567394-9be35050-05cd-11e8-8c6a-127ae051e9e9.png)

![image](https://user-images.githubusercontent.com/16001666/35567410-aa8352cc-05cd-11e8-8ee1-993f89d88cdf.png)

**Comment by metas-lc** [comment]
about date problems we have, there are some new ones described here: https://github.com/metasfresh/metasfresh-webui-api/issues/789 and seem related with timezone

**Comment by siemiatj** [comment]
Yup, I removed the TZ when saving date as we don't care about time here. This way we are sure the correct day is saved in the db.

**Comment by metas-lc** [comment]
IT
1. filters are working fine, and they remember what you set OK
2. attributes in HU editor work fine. Date is correctly set OK
3. when you change date+time field the hour updates with -1 and grid view looks different from docview, - shall be solved by https://github.com/metasfresh/metasfresh-webui-api/issues/789
