### ISSUE TITLE
Colapse bpartner/lookup when blur

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1505]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
(please perform precisely the steps described below)
* create purchase order
* fill the bpartner field => remark the dropdown is opened to select the contact => IGNORE it
* press batch entry, add some product
* press ALT-U => order completed but the screen looks "not cool":

![image](https://user-images.githubusercontent.com/1244701/34989154-1ef1c698-faca-11e7-9ec7-1afc86eb7565.png)

### What is the expected or desired behavior?
the dropdown shall collapse when the bpartner's lookup field focus lost.

**Comment by teosarca** [comment]
note: same thing happens with ANY lookup dropdown.

**Comment by siemiatj** [comment]
@teosarca Is it still happening ? I got lost at `press batch entry`.

**Comment by teosarca** [comment]
nop, it's not. thanks for checking.
