### ISSUE TITLE
Scrollbar in Filter when hovering apply Button

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1508]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when using the Filter and hovering over the Apply Button, then a scrollbar appears. The reason is, that a tooltip opens underneath the apply button.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
In cases where the space underneath the button is not enough, show the Tooltip above the button. Aim is to avoid the scrollbar in such cases.

![image](https://user-images.githubusercontent.com/13365687/35082843-3545298c-fc1c-11e7-943e-36b1aa104a49.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* hovering over the Apply Button: no scrollbar appears, tooltip is displayed underneath the Apply Button, covering the filter fram: OK

![2018-01-19 14_59_06-2018-01-19 14_54_24-metasfresh - windows-fotoanzeige](https://user-images.githubusercontent.com/18696715/35154364-4d87ff7e-fd2a-11e7-9c61-0de8c195e36d.png)

* scrollbar only shown if needed for filter itself, bc of many parameters, e.g. invoicing candidates: OK
