### ISSUE TITLE
Follow-up of Picking window broken

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1510]
### Is this a bug or feature request?
bug
### What is the current behavior?
Picking window is not broken anymore, but we have to make sure the frontend works fine

#### Which are the steps to reproduce?
see task https://github.com/metasfresh/metasfresh-webui-frontend/issues/1447

### What is the expected or desired behavior?
see comments in 1447

**Comment by metas-lc** [comment]
case that is not working: 
1. go in picking terminal. E.g. https://w101.metasfresh.com:8443/window/540345?refId=1000421&refType=143&viewId=540345-71eddbb858fd4ded8b68d24c25140d02&page=1

2. select the line and press on open hu selection window: 
![image](https://user-images.githubusercontent.com/16001666/36149104-3200fcaa-10c7-11e8-8926-1e78c54949dc.png)

3. select the second page and select an HU, run pick HU
![image](https://user-images.githubusercontent.com/16001666/36149185-7732943c-10c7-11e8-89d8-aae97e492241.png)

=>
there are no details rows instead of the picking slots NOK
![image](https://user-images.githubusercontent.com/16001666/36149302-e7ccb02e-10c7-11e8-8387-d97cd5bfec16.png)

**Comment by siemiatj** [comment]
@metas-lc How can I reproduce this with the current state of `/window/540345` ?

**Comment by siemiatj** [comment]
Tried testing this again and seems to be working just fine.

**Comment by metas-lc** [comment]
started to happen again... i'm opening it back.
![image](https://user-images.githubusercontent.com/16001666/38666021-9c993904-3e46-11e8-928c-2426dad397b9.png)

**Comment by siemiatj** [comment]
@teosarca I'm not sure what should happen here. I tried the steps given by Lili to repro, and browser hits this url `https://w101.metasfresh.com:8443/rest/api/documentView/pickingSlot/pickingSlot-64bc3ef62da84b77b07a815be4d0da4b-1004513?firstRow=20&pageLength=20` which returns an empty list. Is not what we expect ? Are the params incorrect, or are we missing some request here ?

**Comment by teosarca** [comment]
@siemiatj  looks like it's a backend issue.

**Comment by metas-lc** [comment]
closing this one. Shall be solved in https://github.com/metasfresh/metasfresh-webui-api/issues/939
