### ISSUE TITLE
Discard changes in modal window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1517]
### Is this a bug or feature request?
Bug
### What is the current behavior?
A new, empty entry for e.g. address is created when the modal window is closed, entry is marked red bc mandatory data is missing.
Also see #1308, where this was done already.
#### Which are the steps to reproduce?
Pls see steps & pics in #1308.
### What is the expected or desired behavior?
Changes in modal window shall be discarded when modal gets closed.

**Comment by metas-ts** [comment]
cherry-picked to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* no new entry is created , changes are discarded when modal window is closed: OK
