### ISSUE TITLE
Typeahead error in new Label Filter

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1520]
### Is this a bug or feature request?
Bug
follow-up of https://github.com/metasfresh/metasfresh-webui-api/issues/788

### What is the current behavior?
Currently, it's not possible to Typeahead search in the new filter for Labels.
#### Which are the steps to reproduce?
Open window/123, try and see.
### What is the expected or desired behavior?
Shall work.

![image](https://user-images.githubusercontent.com/13365687/35225883-c6b52d8e-ff89-11e7-814d-9fac45e130d2.png)

**Comment by teosarca** [comment]
note to IT:
regression: dropdown and typeahead for Labels shall work in regular single document
