### ISSUE TITLE
Email To field does not work correctly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1529]
### Is this a bug or feature request?
Bug
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1327

#### Which are the steps to reproduce?
* open an order
* from menu, call Email => email modal is displayed
Now remark To field:
* shows some weird number (i.e. the userId instead of user name)
* start typing something => show weird suggestions 

### What is the expected or desired behavior?
show display user names

**Comment by metas-lc** [comment]
IT
suggestions are ok, 
it showed the last name, first name of my bpartner OK
