### ISSUE TITLE
Cannot set attributes in orderline

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1536]
### Is this a bug or feature request?
bug
### What is the current behavior?
Cannot set attributes in orderline
#### Which are the steps to reproduce?
1. open sales order (window 143)
2. create a new one, add a product 
3. set attribute 

![image](https://user-images.githubusercontent.com/16001666/35442241-35ba9e12-02af-11e8-8360-c2fbda2ba3bb.png)
![image](https://user-images.githubusercontent.com/16001666/35442313-7a4a0af4-02af-11e8-83de-14f0370bea07.png)

=> 
"No product attributes found for asiId=N8"

### What is the expected or desired behavior?
as i understood, it's because N8 came after complete
asi shall be set and remembered

**Comment by PabloSichert** [comment]
My exact steps:
- Open http://localhost:3000/window/143
- Press `Alt + N` => New document
- Focus `Business Partner`, press `Spacebar`, select `G0001345a0_Test Kunde 1`
- Select `.test`
- Click `Add new` in `Order Line` section
- Focus `Product`, press `Spacebar`, select `P002737_Convenience Salat 250g`
- Press `Alt + Enter` => Close modal
- Double click into first row, column `Attribute Set Instance`
- Click on `---`, dropdown opens
- Click on `none` from `Label` selection, dropdown opens
- Click on `Bio`

Is timing relevant for this issue? As in, how quickly I execute those steps in succession.

My network tab looks like this:

![image](https://user-images.githubusercontent.com/4450694/35485937-e9024ade-0466-11e8-935a-b513606e6faf.png)

I can't spot any "`N8`" requests. Did I miss something?

**Comment by PabloSichert** [comment]
Thanks for checking again. The attribute won't save for me as well, so I'm going to fix that first regardless of the other error

**Comment by teosarca** [comment]
hi guys,

It's a timing problem. The PATCHing happens after the ASI is completed, i.e.
* PATCH: http://w101.metasfresh.com:8081/swagger-ui.html#!/asi-rest-controller/processChangesUsingPATCH_1
* http://w101.metasfresh.com:8081/swagger-ui.html#!/asi-rest-controller/completeUsingPOST_1

When complete endpoint is called that instance is deleted. So that's why when u try to patch u get 404 not found.

@PabloSichert  remember how you fixed the "Create purchase order from sales order" modal view.... The problem is similar here.

**Comment by siemiatj** [comment]
Ok so I tried reproducing this and here's what I've found. First of all, when I created this new Sales Order and product, tried clicking the `Attribute Set Instance` field. Got an error in the console, but the edit button showed up. I can't select `Bio` as there are no options showing up, but setting anything else also produces the error described in the ticket.


![screen shot 2018-02-01 at 12 53 39 pm](https://user-images.githubusercontent.com/513460/35677431-d5f789ae-074f-11e8-9aed-d4cf6d48c758.png)

![screen shot 2018-02-01 at 12 49 20 pm](https://user-images.githubusercontent.com/513460/35677440-d9ae565e-074f-11e8-8fd6-025edcaa6873.png)



@teosarca @PabloSichert so from what I understand, requests are not called in the correct order ? I'm getting a POST->OPTIONS->PATCH->PATCH(404)->GET

![screen shot 2018-02-01 at 1 03 02 pm](https://user-images.githubusercontent.com/513460/35677550-5a1f32c2-0750-11e8-81de-0f97fa10abd1.png)

POST data : `{key: "1001041", caption: ""}`
PATCH data : 
```json
[{
  windowId: "143",
  id: "1000366",
  tabId: "1",
  tabid: "1",
  rowId: "1000600",
  fieldsByName: {
    _AttributeSetInstance_ID : {
      field: "M_AttributeSetInstance_ID",
      value: {key: "1001041", caption: ""},
      validStatus: {valid: true, initialValue: true, fieldName: "M_AttributeSetInstance_ID"}
      widgetType: "ProductAttributes"
    }
  }
}]
```

**Comment by teosarca** [comment]
@siemiatj yup... complete shall be called last. always !
because after calling complete, that resource is discarded

**Comment by teosarca** [comment]
(i am talkinh about that N8 resource)

**Comment by metas-mk** [comment]
testing Quickly. 1st created orderline does not save all attributes in first cycle. 2nd line does.

**Comment by metas-lc** [comment]
IT
1. repeated the testcase above => works fine, the attributes are set, no errors OK
2. added attributes using advanced edit or add new => works fine, the attributes are set, no errors OK
3. added product price with attributes for HU => line was added directly with attributes OK
4. added attributes in doc view (like product price and bill of material windows) => attributes were set correctly OK

note: couldn't reproduce the problem from the comment above.
