### ISSUE TITLE
Date Fields not patched

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1538]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Date field is not patches, e.g. in Sales Order Window "Date Ordered"
![image](https://user-images.githubusercontent.com/13365687/35451385-4e60f3c6-02c3-11e8-97e1-fe627556031e.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Pls fix.

@teosarca found this so far

![image](https://user-images.githubusercontent.com/13365687/35451412-700d66ee-02c3-11e8-9f06-6d900683b7c6.png)

**Comment by metas-lc** [comment]
IT
checked date ordered and date promised in sales order
=> patch was sent OK
