### ISSUE TITLE
eMail Editor mailTo List not showing selected entry

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1539]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
In eMail Editor when searching w/ autocomplete, the list of possible entries are shown, but not shown as selected in the dropdown list.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Show the selected items w/ similar look&feel to all other list items when selected (Lookup widget, List drop-down)

![image](https://user-images.githubusercontent.com/13365687/35502220-93cd146a-04dc-11e8-8ca5-4b9065f89b34.png)

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


NOK: This problem was not solved


![image](https://user-images.githubusercontent.com/16001442/38562339-07d9fb8c-3ce3-11e8-9d7a-80c60c9fcb79.png)

**Comment by teosarca** [comment]
@metas-rc  @metas-mk  @siemiatj  I think this task can be closed because we have https://github.com/metasfresh/metasfresh-webui-frontend/issues/1740.
wdyt?

**Comment by metas-mk** [comment]
Yes, we created that follow up for this remaining stuff. Thanks. Closing.
