### ISSUE TITLE
Address editor timing(?) error

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#154]
Test:
* quick and continuous click on address button over and over again
* you will get and error because the /complete endpoint was called without ID (i.e. the ID is "undefined").. see the screenshot

IMHO this is somehow related with what i've described in https://github.com/metasfresh/metasfresh-webui-frontend/issues/143.
I think the fix shall be the same:

> What SHALL happen:
> 
> don't open the popup until u know that u have something to show inside, so call the "create" API first and see if u get something
> in case the "create" fails, don't show the popup, don't call the "complete"

![image](https://cloud.githubusercontent.com/assets/1244701/21225413/684e2f68-c2d9-11e6-8ac3-7a7fc68672f7.png)

**Comment by teosarca** [comment]
NOTE: ofc the user usually won't click as hell on that button, but this test case reveals a timing issue.

**Comment by damianprzygodzki** [comment]
Fixed by 25f8c96f3516fdc9f8117d6e3fd0b63cb244b948
