### ISSUE TITLE
Shortcut Alt++ not working on non German Keyboard Layout

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1540]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the shortcut Alt+Shift++ (expand) is not working anymore
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please fix.

![image](https://user-images.githubusercontent.com/13365687/35511025-ba01a614-04fa-11e8-89cc-63627100a1e6.png)

**Comment by metas-mk** [comment]
Tested on Laptop. Works there. Switched Keyboard encoding between languages back/ forth. Works now. Closing.

**Comment by metas-mk** [comment]
On English Keyboard Layout Alt++ is on Alt+Shift++. Does not expand then. Also Alt+(+ numpad) does not work.

**Comment by siemiatj** [comment]
Might be related to #1756

**Comment by metas-lc** [comment]
IT
alt++ , alt+shift++, alt++ (numpad) works: expands /collapses tab OK
