### ISSUE TITLE
Console error when grid view updates 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1542]
### Is this a bug or feature request?
bug
### What is the current behavior?
Console error when grid view updates TypeError: Cannot read property 'ID' of undefined
#### Which are the steps to reproduce?
1. open settings:
https://w101.metasfresh.com:8443/window/53100/2188223
2. new tab: open user window in grid view (this is page no. 2 because there was my user from settings)
https://w101.metasfresh.com:8443/window/108?page=2&viewId=108-934e04bf3a09430ba73fe8bd159d302e

3. go back to settings tab and change email address
4. go back to user tab, see console
=> ViewActions.js:153 Uncaught (in promise) TypeError: Cannot read property 'ID' of undefined
    at Object.values.map.viewRowField (ViewActions.js:153)
    at Array.map (<anonymous>)
    at mergeColumnInfosIntoViewRow (ViewActions.js:153)
    at toRows.map.row (ViewActions.js:196)
    at Array.map (<anonymous>)
    at mergeRows (ViewActions.js:196)
    at then.response (DocumentList.js:229)
    at <anonymous>
=> also you need to refresh to see the change NOK

### What is the expected or desired behavior?
no errors, and the change shall appear without refreshing

**Comment by siemiatj** [comment]
@metas-lc  Tested with latest master. I don't get the error. 
@teosarca When I changed my email address in one tab, in the users list tab I got this:

![screen shot 2018-03-29 at 8 04 28 pm](https://user-images.githubusercontent.com/513460/38105500-85c7d7cc-338c-11e8-99ce-c3ec7c75a028.png)

No idea if the list should get updated, or what are the requirements here.

**Comment by teosarca** [comment]
did a quick check, it seems a backend bug. On it.

**Comment by metas-lc** [comment]
IT
repeated the testcase above => works fine, no errors and the field is updated without using refresh OK
