### ISSUE TITLE
Sales Order window Purchase Order modal overlay broken again

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1543]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Purchase Order modal overlay is broken again. It does not open when starting the action "Create Purchase Orders".
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall work.
![image](https://user-images.githubusercontent.com/13365687/35573448-79bdc082-05d7-11e8-8bb6-8f62925ee8c6.png)

![image](https://user-images.githubusercontent.com/13365687/35573474-878f59f0-05d7-11e8-8358-46919b7f46c4.png)

**Comment by teosarca** [comment]
issue was introduced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1538,
i.e. https://github.com/metasfresh/metasfresh-webui-frontend/pull/1541/commits/e465037d0abcde45ab81d6b5c1c1c7544bd556a1

**Comment by metas-lc** [comment]
IT
1. create purchase orders opens OK
but each time you change promised date, the hour changes with -1 
![image](https://user-images.githubusercontent.com/16001666/35635476-0d92b6d4-06b7-11e8-8a83-c0d92e8552aa.png)
everytime you open " create purchase orders" promised date is reset. OK?

2. sales order - the patch for date is still sent OK
but each time you change the date (in date + time field) the hour changes with -1
and grid view and document view look different + have different hours: e.g. 19:59:59 vs 6:59 PM
