### ISSUE TITLE
List Widget does not scroll down with arrow-down

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1544]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the List widget does not scroll down when using the arrow-down. 
#### Which are the steps to reproduce?
- Open window/540321
- Open Filter
- Select Country and try to scroll down with arrow-down, to the bottom of the list.
### What is the expected or desired behavior?
Shall work.

![image](https://user-images.githubusercontent.com/13365687/35608375-296881bc-0659-11e8-85b9-6bef8513a9ca.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui



* OK: The dropdown list works well with up and down arrows.
* NOK: If I click on the dropdown and the mouse cursor stays somewhere in that list, I can use the arrow down and the entries are highlighted as selected one by one. But  if I stop pressing the arrow, the highlighted item will be the one from where the cursor is. Followup created: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1666
