### ISSUE TITLE
Date and Time fields: hour changes on each update

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1547]
### Is this a bug or feature request?
bug
### What is the current behavior?
when you update a date+time field, hour changes each time with -1h
#### Which are the steps to reproduce?
1. open a sales order e.g. https://w101.metasfresh.com:8443/window/143/1000364
2. change date promised 
(e.g. from 01/26/2018 10:59 PM to 01/16/2018)
3. notice date promised now
=> 01/16/2018 9:59 PM - hour changed as well NOK 
### What is the expected or desired behavior?
hour shall not change

**Comment by siemiatj** [comment]
99% positive this is a TZ issue again. Should be a quick fix once I'll find where the date is saved.

**Comment by siemiatj** [comment]
@metas-lc can you retest this one ? Seem that my fix for other issue might've fixed this too.

**Comment by teosarca** [comment]
@siemiatj Talked with @metas-mk  and we think this issue shall be solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/1933.
