### ISSUE TITLE
Offline mode is not detected

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#155]
Test:
* webui server is down
* trying to open the frontend in a browser tab
* i get no info about the fact that i am offline

![image](https://cloud.githubusercontent.com/assets/1244701/21225669/965e1b10-c2da-11e6-8644-c18597a82445.png)

**Comment by metas-dh** [comment]
Results of IT1

tested (accidentally) on w101:
* webui server is down, user gets an according info: "Connection lost.
There are some connection issues. Check connection and try to refresh the page.": OK
