### ISSUE TITLE
Selecting country in dropdown with mouse click not possible

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1552]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Selecting a country with mouse click in the dropdown is not possible.
#### Which are the steps to reproduce?
1. Try setting the country in a bpartner location: start writing e.g. "deut"
=> Deutschland is displayed in the Dropdown
2. Try selecting it with mouse click:
=> not possible, you're asked if you want to leave the page: NOK
(working fine using Enter though)
### What is the expected or desired behavior?
Should work.

**Comment by metas-lc** [comment]
IT
repeated the testcase above: works fine. You can add the country with mouse click (also tried using the keyboard)
it isn't asking me if i want to leave the page, only if i leave the country empty OK

short regression: checked other search fields in docview and subtabs => you can select them with mouse OK
