### ISSUE TITLE
Action Parm modal Overlay focus missing n 1st Field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1554]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Modal Overlays for Process/ Action Parms don't have the focus on the first recordable field. See example in Picking Terminal described below.
#### Which are the steps to reproduce?
- Open https://w101.metasfresh.com:8443/window/540345
- select 1st line Ananas and start "Pick" Action
- Action "Pick to new HU"
- Press ```tab``` multiple times. No focus recognizable.
### What is the expected or desired behavior?
The focus shall always be on 1st recordable fields in Process/ Action Pam modal overlays.

![image](https://user-images.githubusercontent.com/13365687/35738784-28f4b9f2-0830-11e8-9e2c-b769b13fab63.png)

**Comment by siemiatj** [comment]
Tested my PR changes as described in the issue + on `/window/143/1000386`.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

focus shall always be on 1st recordable fields in Process/ Action Pam modal overlays:

* repeated testcase above: focus is in the 1st field: OK
* checked other Process/ Action Pam modal overlays as well (in picking, manufacturing, material receipt etc.): focus is in the 1st recordable field: OK
