### ISSUE TITLE
Can not enter "-" into any search field

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1555]
### Is this a bug or feature request?
bug
### What is the current behavior?
when you enter "-" or "=" into a search field nothing happens
#### Which are the steps to reproduce?
there was the same problem for text fields https://github.com/metasfresh/metasfresh-webui-frontend/issues/1406

open sales order and create a new one. Try to write - on bpartner field (or = )
=> nothing happens
(worked with "-" from numpad)
### What is the expected or desired behavior?
should be able to write - and =

**Comment by teosarca** [comment]
IMHO anything from keyboard shall be allowed.... letters, digits, symbols.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* enter "-" into any search field: worked fine, OK
* checked entering "-", in other fields as well, worked everywhere except for dropdown (which is not working correctly atm anyway): OK
