### ISSUE TITLE
Errors in the console when opening HU Editor

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1559]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When opening HU Editor window, there are errors in the console.
#### Which are the steps to reproduce?
Open any HU Editor window (or go to http://localhost:3000/window/540189). Errors should be immediately visible. Clicking on the table rows produces more errors.

![image pasted at 2018-2-5 18-46](https://user-images.githubusercontent.com/513460/35851372-2a3e95bc-0b28-11e8-9de1-8b88ed0ae468.png)

console : 
```
Uncaught (in promise) TypeError: Cannot read property 'fieldsByName' of undefined
at then.response (bundled7794b0f8da2e8536f50.js:50132)
at <anonymous>
```

### What is the expected or desired behavior?
No errors in the console being thrown.

**Comment by metas-mk** [comment]
@siemiatj is this issue needed for this weeks release? if not I would propose to leave it in our master branch this week and it will be automatically in next week's release.

**Comment by siemiatj** [comment]
Not sure. Depends on @metas-dh probably ?

**Comment by teosarca** [comment]
agree.
btw, we use "branch:release" to signal that the task was integrated/cherry-picked(CPed) to release branch.
That usually happens after integration testing (IT).
If you want to tell to testing team/release manager that a certain task shall be part of next release then use `branch:release-TODO` or `branch:release-TODO-after-IT`.

Similarly, we use "branch:master" to to tag those issues which were integrated to master branch (i.e. PR was merged).

**Comment by metas-dh** [comment]
imho we don't need it for this week's release; since the error's only popping up in console and not bothering the user in any way, i guess it's ok to have it in next week's release.

**Comment by metas-lc** [comment]
IT
checked window Handling Unit Editor, selected some HUs => no errors OK
checked HU editor from receipt candidates. Selected some HU lines => no errors OK
