### ISSUE TITLE
Menu search results are not correctly rendered

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#156]
![image](https://cloud.githubusercontent.com/assets/1244701/21238190/bf425674-c30a-11e6-82be-2f0279f18c6a.png)

**Comment by cadavre** [comment]
And how should they be rendered?

**Comment by cadavre** [comment]
OK, reviewed.

From this call: http://w101.metasfresh.com:8081/rest/api/menu/queryPaths?nameQuery=ges&childrenLimit=9

Let's display results:
Neuer Geschäftspartner (newRecord)
Geschäftspartner (window)
Geschäftspartnergruppen (window)
Umsatzreport Geschäftspartner (report)

**Comment by damianprzygodzki** [comment]
To fill full functionality:
https://github.com/metasfresh/metasfresh-webui/issues/107,
https://github.com/metasfresh/metasfresh-webui/issues/106
