### ISSUE TITLE
Some fields are not patched after you change them twice

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1564]
### Is this a bug or feature request?
bug
### What is the current behavior?
you are in a field (like Text or Quantity). You modify it - it saves. You modify it again (important: without leaving the field) => nothing happens
#### Which are the steps to reproduce?
Case I
1. go to sales order, create a new one or use this one https://w101.metasfresh.com:8443/window/143/1000401
2. write something in order reference and press enter
=> you have a patch and a get
![image](https://user-images.githubusercontent.com/16001666/35860954-ba9ab6ce-0b4e-11e8-93cc-bd914d6ff028.png) 
OK

3. change that text without taking out the cursor from that field, press enter
=> nothing happens NOK

Case II
1. go to invoice candidates. You can pick this one https://w101.metasfresh.com:8443/window/540092/1000000
2. update Qty Invoice before Q..., press enter
=> at first, Recompute is on Y and then:
=> Qty to Invoice eff. updates OK
=> Total of Order updates OK
(1 patch and 3 get)
![image](https://user-images.githubusercontent.com/16001666/35861239-9ed44d32-0b4f-11e8-8f41-c6fff4a44a3c.png)

3. change that qty without taking out the cursor from that field, press enter
=> nothing happens NOK
### What is the expected or desired behavior?
if you changed the text/qty shall patch each time you press enter or tab..or leaving that field using mouse (focus out)

**Comment by metas-lc** [comment]
IT
1. checked again the qty and text fields => works fine. It patches each time you press enter/tab/click outside OK
2. as a regression i checked search, date and dropdown fields => works fine. After they are selected there is a patch OK
3. another regression: create purchase order: change the qty and press done directly => cndidate created with my qty OK

**Comment by metas-ts** [comment]
Cherry-picked to `release`
