### ISSUE TITLE
Subtab Data not shown when clicked first time

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1566]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when opening a Subtab, the data is not shown when the first time called/ clicked.
#### Which are the steps to reproduce?
- Open window/123 for Business partner "Machine Parts Ltd"
- Click on Subtab Customer: empty
- Click on Subtab Vendor: empty
- Click back on Subtab Customer: filled now
### What is the expected or desired behavior?
The Subtab Data shall be filled already when called/ clicked the first time and has data.

![image](https://user-images.githubusercontent.com/13365687/35868610-4d0f82d8-0b5d-11e8-8fab-037f0e7207d4.png)

**Comment by metas-mk** [comment]
Was broken with this PR https://github.com/metasfresh/metasfresh-webui-frontend/pull/1551

**Comment by siemiatj** [comment]
Ok, this will be my first thing for tomorrow.

**Comment by metas-ts** [comment]
cherry-picked into `release`

**Comment by metas-lc** [comment]
IT
checked subtabs in business partner, order, shipment schedules
=> data is shown OK
