### ISSUE TITLE
Create purchase orders: Date promised format

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1567]
### Is this a bug or feature request?
bug
### What is the current behavior?
dates pattern are different from one line to another
#### Which are the steps to reproduce?
1. open sales order window. Create a new one or use this one https://w101.metasfresh.com:8443/window/143/1000404
2. select the product line and go to actions. Run Create purchase orders
=> notice date on the first line and second line
![image](https://user-images.githubusercontent.com/16001666/35914661-bb18805e-0c0c-11e8-845f-7e50fe96715c.png)

### What is the expected or desired behavior?
both dates should have the same format. As far as i know, it's defined by the language from login

**Comment by metas-lc** [comment]
IT
both lines have dates in this format: 23.02.2018 00:00:00 OK
changed languages to DE and EN => in both cases dates have the same format OK?
(if i set language to DE => other date fields are like 23.02.2018 00:00
if i set language to EN => other date fields are like 02/23/2018 12:00 AM )

**Comment by siemiatj** [comment]
@metas-mk @metas-ts @teosarca I guess we need to formalize this, as it's causing a bit of a mess. Right now in some places we use the default locale format provided by the `Moment.js` library, but in others we use some hardcoded format. How do we want to handle this ? Force our format everywhere no matter the language, or use the locale format everywhere, or some hybrid solution (but then it'd be best to have it written down somewhere).

**Comment by teosarca** [comment]
IMHO we shall use locale's format, in case that will work smooth.
Because while, Europeans like to write dates like `DD.MM.YYYY`, Americans like `MM/DD/YYYY` which shall be perfectly OK.

@metas-mk  wdyt?

**Comment by metas-lc** [comment]
talked with @metas-mk and shall be use locale's format (like Teo said)

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: The dates are now identical on the first row and in the next rows.
