### ISSUE TITLE
Chrome is remembering wrong password

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#157]
Test case:
* i've logged in with user "it" and password "metasfresh"
* Chrome suggests (and if i agree it really stores) to remember password "meta" .. wtf?!

![image](https://cloud.githubusercontent.com/assets/1244701/21263498/dbd5d51e-c39f-11e6-906b-94be66aa5fbd.png)

**Comment by damianprzygodzki** [comment]
Ive tested it, our login form saves password properly, so this is not to fix by us.

Btw. credentials it/metasfresh doesnt work `@UserOrPasswordInvalid@`
