### ISSUE TITLE
Applied filter params sometimes not displayed in filter

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1578]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The applied filter params are sometimes not displayed in the filter button.
#### Which are the steps to reproduce?
Open Procurement Planning (window/540285), set filter with e.g.
* date: last 7 days, apply: filter button shows "Invalid date", not the date period selected: NOK
* filter: select a bpartner, apply: filter button shows "Default", not bpartner selected: NOK
### What is the expected or desired behavior?
Filter should display the params that were set.

**Comment by metas-dh** [comment]
Update:
* date filter shows the applied filter params: OK
* filter: same as before, see above

**Comment by siemiatj** [comment]
I was thinking maybe we can use the names of the applied filters here, ie : 

![screen shot 2018-08-21 at 02 05 35](https://user-images.githubusercontent.com/513460/44372948-cc310c80-a4e6-11e8-9336-5286ed4e6d8c.png)

and just limit the max-width of this field.

What I've found while testing this though is the fact, that apparently only one param can be used at once in this filter widget. Selecting more does not affect anything and they're not even added to the request. I wonder if it's a regression or was it always like that ?

**Comment by siemiatj** [comment]
Related issue #1927

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 (and recent e2es)

* date filter shows the applied filter params: OK
* filter shows the applied params (e.g. order no., doctype etc.): OK
* filter results are ok as well, also when there are >1 params applied: OK
