### ISSUE TITLE
Action button disappears after selecting all HUs in >1 page

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1579]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you select all HUs in >1 page, e.g. in material receipt candidates, the Action button disappears, so you cannot create 1 material receipt for all HUs, but you have to create 2 receipts, 1 per page.
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Action button must not disappear after selecting all HUs in >1 page.

**Comment by teosarca** [comment]
IMHO this is a webui backend task

**Comment by metas-dh** [comment]
thx, created https://github.com/metasfresh/metasfresh-webui-api/issues/861
