### ISSUE TITLE
Selection not possible in dropdown

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1580]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In window HU Editor, 540189, when using action MoveToAnotherWarehouse, you cannot select any warehouse from the dropdown:
* mouse-click: you get back to the 1st entry of the dropdown
* Enter: nothing happens
#### Which are the steps to reproduce?
This is happening in customer db, and i only found it in this window, could not reproduce in mf15cloudit!
### What is the expected or desired behavior?
Should work.

**Comment by siemiatj** [comment]
@metas-dh Can you give me a list of steps how I can get to this window ?

**Comment by metas-dh** [comment]
@siemiatj : checked again, in customer db: working fine now, was probably fixed by a rollout since i last tested. closing this task.
