### ISSUE TITLE
Date recording with keys leads to error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1585]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When recording a date with the keyboard, instead of clicking it with the mouse in date widget, then an error occurs and a blank screen occurs. 
#### Which are the steps to reproduce?
- Open window/143
- Click on a date widget field and start typing the date.
### What is the expected or desired behavior?
Shall also work with the keyboard.

![image](https://user-images.githubusercontent.com/13365687/36097847-f212d08e-0ffc-11e8-99b8-b96c187908f7.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* date recording with keys: no error, no blank screen: OK
* date recording with keys is not saved everytime: 
  * when entering e.g. date of provisioning in window/143 with keys the first time, the date is saved
  * but when changing the date with keys, the changes are not saved, no progress bar after Enter or clicking somewhere else; when you jump back to previous window and back to window/143, you see the date as it was first set, changes are lost: NOK

**Comment by siemiatj** [comment]
@metas-dh any ideas if this second case is a new thing or something that slipped through testing before ?

**Comment by metas-dh** [comment]
@siemiatj tbh i'm not sure; i think it's a new thing but i wouldn't bet on it.

**Comment by metas-dh** [comment]
checked again w/ metas-mk: changes w/ keys are saved when pressing Tab, now also saved when clicking somewhere else: OK.
