### ISSUE TITLE
Screen aliginment Improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1586]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
The field label/content alignments are not very nice on screens at the moment.
#### Which are the steps to reproduce?
Open window/143 and see.
### What is the expected or desired behavior?
Align the field label/ content in a proper way.

Here a Screenshot with a few examples:
![image](https://user-images.githubusercontent.com/13365687/36098370-fece989c-0ffe-11e8-906a-19a129a34d2a.png)

**Comment by metas-rc** [comment]
Results of IT


Tested on wbeui

* OK: The main view in sales order seems perfectly alligned. I dragged some right lines to check: 

![image](https://user-images.githubusercontent.com/16001442/38198349-100b503e-3695-11e8-8a7a-0f6d47461f63.png)




Regression: 


* Advanced edit also looks fine: 

![image](https://user-images.githubusercontent.com/16001442/38198458-9b921098-3695-11e8-88bd-b09a9f1045f1.png)

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: All looks nice now, including attributes and IsActive buttons

![image](https://user-images.githubusercontent.com/16001442/38369038-7d4f284e-38ef-11e8-8b72-660a46691690.png)

![image](https://user-images.githubusercontent.com/16001442/38369139-b92d9594-38ef-11e8-970b-1ed6bdd89977.png)
