### ISSUE TITLE
Zoom Into is not working

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1588]
### Is this a bug or feature request?
bug
### What is the current behavior?
Zoom Into is not working
#### Which are the steps to reproduce?
1. go to any window. E.g. sales order, open a document https://w101.metasfresh.com:8443/window/143/1000421
2. click on business partner (see pic)

![image](https://user-images.githubusercontent.com/16001666/36150132-4cae6ca0-10cb-11e8-8b24-8f832acf378e.png)

=> business partner window does not open, error in console:
`createStore.js:165` Uncaught Error: Actions must be plain objects. Use custom middleware for async actions.
    at dispatch (createStore.js:165)
    at middleware.js:22
    at index.js:14
    at bindActionCreators.js:7
    at value (MasterWidget.js:200)
    at onClick (RawWidget.js:895)
    at Object.Ja (react-dom.production.min.js:26)
    at Object.invokeGuardedCallback (react-dom.production.min.js:25)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:25)
    at Za (react-dom.production.min.js:30) `

### What is the expected or desired behavior?
window should open , no errors

**Comment by metas-ts** [comment]
CPed to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Zoom into:
* click on e.g. business partner in sales order, or product category in product window: new tab opens with business partner / product category window opens, OK
* no error in console: OK
* Zoom into with right mouse click, in e.g. orderline, also still working fine: OK
