### ISSUE TITLE
included tab: when refreshing via websocket event the sort/order is not preserved

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1589]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* have a sales order with 2 lines, e.g. https://w101.metasfresh.com:8443/window/143/1000424
* sort the included order lines by `Line No` descending:
![image](https://user-images.githubusercontent.com/1244701/36151993-184fbbe2-10d2-11e8-87e6-8a78c11d021a.png)
(remark: the sort indicator is wrong but that shall be solved in another task)

* now open that sales order in another browser tab and go an modify on of the order lines (e.g. change the quantity)

* check back the first tab and you will see something like (note: the screenshot below is from localhost but you will get the point):
![image](https://user-images.githubusercontent.com/1244701/36152138-97645b7c-10d2-11e8-829f-2a9d23a52a7a.png)

### What is the expected or desired behavior?
refreshing on websocket event shall respect current sort/order.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

repeated testcase above (with 2 and more orderlines), also ordered by e.g. packing item:
* refreshing on websocket event shall respect current sort/order: OK
* "orderBy" correctly displayed as well with the resp. value: OK
