### ISSUE TITLE
Included tabs sorting

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1590]
### Is this a bug or feature request?
bug
### What is the current behavior?
you can sort included tab only once and the arrow is not updating
#### Which are the steps to reproduce?
1. open sales order, create a new one and add 2 lines
(you can use this one https://w101.metasfresh.com:8443/window/143/1000425)
2. select Line No. to sort
=> rows are sorted OK
=> arrow is still up NOK
3. sort by Line No. again
=> nothing happens NOK 
### What is the expected or desired behavior?
each time you sort shall work
the arrow should update as well

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

sorting in included tabs:
* rows are sorted: OK
* arrow is updated correctly: OK
* sorting works correctly as often as tried: OK

**Comment by metas-ts** [comment]
cherry-picked to `release`
