### ISSUE TITLE
Changes in location not always saved

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1598]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you add a location, and you add the country, then click e.g. street and then outside of the address modal window, the address is not saved; and when you close the modal you get a new, red line in location subtab (disappears after refresh).  You have to click outside of the modal window directly after setting the country or add e.g. street to have your changes saved.
#### Which are the steps to reproduce?
1. Set a country, click in street and then next to the address modal: 

![2018-02-14 18_02_52-metasfresh](https://user-images.githubusercontent.com/18696715/36217380-8fc717f8-11b1-11e8-9ff7-0c6913aaa890.png)

2. Close the modal with Done, OK:

![2018-02-14 17_47_24-metasfresh](https://user-images.githubusercontent.com/18696715/36217191-19b5963e-11b1-11e8-9c98-318273bcf16a.png)

3. Set country, click directly outside the modal:

![2018-02-14 17_51_27-metasfresh](https://user-images.githubusercontent.com/18696715/36217451-c143c8f8-11b1-11e8-9fa6-693f98336cd9.png)

### What is the expected or desired behavior?
Changes shall be saved.

**Comment by metas-ts** [comment]
:cherries: to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in weekly e2e check

location is always saved, no matter where you click or in which order, after setting the country: OK
