### ISSUE TITLE
Discuss batch operations

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#16]
Important for select doc lines.

**Comment by teosarca** [comment]
Not sure which are all use cases, but in case of deleting multiple lines, i think we shall change the "/delete" API and allow the "rowId" to be a comma separated list of IDs.
e.g. /delete?type=143&id=123&tabId=1&rowId=1,2,3,4

wdyt?

**Comment by cadavre** [comment]
+1 for comma-separated query params.

**Comment by teosarca** [comment]
See https://github.com/metasfresh/metasfresh-webui/issues/3
