### ISSUE TITLE
Cannot edit product attributes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#160]
![image](https://cloud.githubusercontent.com/assets/1244701/21319894/b1f67f1c-c617-11e6-8104-2c18602b446a.png)

**Comment by damianprzygodzki** [comment]
@teosarca When i try to get instance of pattribute (POST http://w101.metasfresh.com:8081/rest/api/pattribute) with payload:

```
{
 "templateId":"1000686",
 "source": {
  "documentType":"143",
  "documentId":1002773,
  "tabid":"1", 
  "rowId":"1002726", 
  "fieldName":"M_AttributeSetInstance_ID"
}}
```

Im gettin weird error : `
"No TableName defined for DocumentEntityDescriptor{fields.count=2}"

There is no information about TableName property in swagger. Did something changed?

**Comment by teosarca** [comment]
hi guys,

did a quick check using the latest webui frontend code, but i got following issue... it seems the dropdown endpoint is not called correctly.

![image](https://cloud.githubusercontent.com/assets/1244701/21714130/128f9cd6-d406-11e6-9f45-1aec2109ad9f.png)

**Comment by teosarca** [comment]
btw, about:

> 
> Im gettin weird error : "No TableName defined for DocumentEntityDescriptor{fields.count=2}"
> 
> There is no information about TableName property in swagger. Did something changed?
> 
> 

i cannot reproduce.... but nevertheless this sounds like an webui server internal issue...
