### ISSUE TITLE
Date Range Picker shows wrong day of the week

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1604]
### Is this a bug or feature request?
bug

### What is the current behavior?
![image](https://user-images.githubusercontent.com/16079655/36297573-c6c6ff1e-12f3-11e8-9cfa-066c2f865d27.png)

#### Which are the steps to reproduce?
1. open any date ranger picker
1. compare week day 

https://w101.metasfresh.com:8443/window/232

**Comment by metas-rc** [comment]
Results of IT

Tested on webui


* OK: The day of week in date anges is correct in each case I tried: 
** Fielters
** Fields in single view
** Fields in grid view
** Fields in included tabs
