### ISSUE TITLE
Scrolling in dropdown fields

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1605]
### Is this a bug or feature request?
bug
### What is the current behavior?
scrolling with mouse click (dragging the scrollbar) and with keyboard's arrows is not working well
#### Which are the steps to reproduce?
1. in this window we have lots of data in dropdowns so it's easier
https://w101.metasfresh.com:8443/window/540173/1000002
2. select the dropdown of Document Base Type field
3. use down key => notice that the scrollbar remains in it's place.  NOK
4. try to select the dropdown with the mouse click => the whole dropdown is gone NOK
### What is the expected or desired behavior?
step 3 Shall go down with your current selections
step 4 scrollbar shall move as you drag it. Shall not close

**Comment by PabloSichert** [comment]
Part of this issue (arrow keys) is covered in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1544

**Comment by metas-lc** [comment]
IT
repeated the testcase above
3. goes down with my current selections OK
4. scrollbar moves as i drag it OK
