### ISSUE TITLE
Searching in dropdown fields

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1606]
### Is this a bug or feature request?
fr
### What is the current behavior?
we can't write anything in dropdown fields. Like e.g. want to search for something that starts with M , you have to scroll 
#### Which are the steps to reproduce?
1. open e.g. https://w101.metasfresh.com:8443/window/540173/1000002
2. select document base type
3. start writing M
=> you cannot write
### What is the expected or desired behavior?
if you write M, scrollbar (and selection) shall go to the word that starts with M "Maintenence order" in this case. If you write "Mat" => Match invoice

**Comment by metasnw** [comment]
you also can not use the scroll icon as a workaround because once you click on it the dropwdown closes

![image](https://user-images.githubusercontent.com/16079655/36395737-ed52d1c0-15ba-11e8-82cc-42854d85a32a.png)

**Comment by metas-lc** [comment]
note: we have a separate task for scrolling in dropdown: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1605

**Comment by metas-lc** [comment]
1. repeated the testcase above: pressed on M in document base type
=> i was sent to the first entry starting with M. Pressing M multiple times, would move to next ones starting with M
2. pressed other letters => the entries starting with those letters were selected OK
(for me it's fine how is working atm. Just to make sure: don't we want to be able to write stuff like "Mat"?)
3. if i click on the scrollbar from the dropdown, it closes NOK

**Comment by siemiatj** [comment]
That's how it's implemented in the code. I think if we wanted to support longer text, we would have to show some input with the typed text.

**Comment by metas-lc** [comment]
ok, if it will be needed i'll create another task for typing in dropdown fields

**Comment by metas-lc** [comment]
IT
checked scrolling by clicking on scrollbar in dropdowns: header, filter, modal, gridview - the view is not closing anymore OK
