### ISSUE TITLE
reload /i18n/messages in case the language changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1616]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Atm, the default language is German.
After user logs in, user's language is used.
Suppose your user language is not German, let's say it's English.
After you log in the static messages (those which are fetched using [/i18n/messages](http://w101.metasfresh.com:8081/swagger-ui.html#!/i-18-n-rest-controller/getMessagesUsingGET) endpoint) are still in German.

#### Which are the steps to reproduce?
Suppose your user's language is English (check your user profile).
Do login and inspect Chrome-Network tab.
![image](https://user-images.githubusercontent.com/1244701/36504013-c6abfa1c-1757-11e8-8213-61b66b01d623.png)
![image](https://user-images.githubusercontent.com/1244701/36504133-23819d5a-1758-11e8-8b09-29003c112075.png)

Below are some of the places where static messages are used (just to quickly check which language is currently used):
![image](https://user-images.githubusercontent.com/1244701/36504186-4d863f5c-1758-11e8-8c9e-f51b76302831.png)
![image](https://user-images.githubusercontent.com/1244701/36504209-63521626-1758-11e8-8a0b-00301aa6ff1f.png)
![image](https://user-images.githubusercontent.com/1244701/36504268-9bdbe7ce-1758-11e8-8a1a-7d8b03e67910.png)

etc etc etc

### What is the expected or desired behavior?
Static messages shall be in user's language.

**Comment by metas-lc** [comment]
IT
logged in while user had en language
=> static messages are in EN OK
logged in while user had de language
=> static messages are in DE OK

note: after login, the language of jasper is always DE. Created task: https://github.com/metasfresh/metasfresh-webui-api/issues/980

**Comment by metas-ts** [comment]
:cherries: picked to release
