### ISSUE TITLE
Label component doesn't hide after clicking tab

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1617]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When a Label component is selected, it won't hide after clicking tab. Clicking away with mouse works though.
#### Which are the steps to reproduce?
->Go to any business partner in `window/123`
->Select attributes
->Click tab
### What is the expected or desired behavior?
Widget should hide

![repro](https://user-images.githubusercontent.com/513460/36528869-e2ca5a0e-17b6-11e8-8bdf-ecce2400fb09.gif)

**Comment by metas-lc** [comment]
IT
repeated the testcase above
=> works fine: pressing tab and shift tab while you are selecting attributes, hides the widget and takes you to next field or to the previous one OK
