### ISSUE TITLE
Dropdown List Widget - first entry at top shall be selected entry

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1621]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when pressing ```arrow-down``` on a focused list widget, the drop-down list opens and the selected line is "somewhere".
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Opening a list widget drop-down list shall show
- the first item selected
- if the field already had a selected content, then the first item at the top shall be the selected item.

**Comment by siemiatj** [comment]
Related #1550

**Comment by siemiatj** [comment]
In case there's a default/selected value -> move it to the top

**Comment by metas-ts** [comment]
Hi @siemiatj 
as talked: at least in process parameter dialogs, mandatory list fileds are not marked as mandatory.
to reproduce, you can go to 
https://w101.metasfresh.com:8443/window/540359 and do the "Create new procurement contract" process. All the list fields are actually mandatory, but they are not marked blue'ish (pls ignore the red arrow etc on the screenshot): 
![image pasted at 2018-3-1 13-00](https://user-images.githubusercontent.com/1264789/36892661-bb9df35a-1e05-11e8-9850-31aa24811b18.png)
That means that an infrequent user of that process might press start and get an error message four times (fo each one of the list fields that have no default value

)

**Comment by metas-rc** [comment]
Results of  IT


Tested on webui


* OK: When I open a list, the first item on the list is selected
* OK: If there is a default item, that item is initially selected and displayed at the top of the list
* OK: If there are no default items and there is a none option, the none option is selected and at the top of the list
* OK: If there is no default item and no none option, the fist item (in alphanumeric order) is selected and displayed at the top of the list.
