### ISSUE TITLE
List widget with only 1 entry shall still show the drop-down

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1622]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, when pressing ```arrow-down``` on a focused list widget and the list has only 1 entry, then there is no drop-down list shown.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
If the drop-down list has only 1 entry, then show this one entry selected when opened.

**Comment by metas-dh** [comment]
Results of IT1
tested in m15

* list field with only 1 entry shows the drop-down when pressing ```arrow-down```: OK
=> shows the 1 entry and "empty" where empty is optional, and only the 1 entry where it is not: OK
