### ISSUE TITLE
Attributes not shown in Material Receipt Candidates

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1623]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when opening the Material Receipt Candidates HU Editor with action "Receive CUs", then the Attributes for a selected line are not shown.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
The Attributes shall be visible for selected Customer units.

![image](https://user-images.githubusercontent.com/13365687/36631197-10ca676e-1974-11e8-8a23-ae76f44d903e.png)

**Comment by metas-lc** [comment]
IT
tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1625 OK
