### ISSUE TITLE
Show Attribute Editor for selected CU Level HU

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1625]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the Handling Unit Editor does not show the Attribute Editor when opening the Handling Unit editor with a selected Customer Unit (without box, palette)
#### Which are the steps to reproduce?

- Open Material Receipt Window https://w101.metasfresh.com:8443/window/540196
- Select a line and action "Receive CU's". HU Editor opens and the Attribute Editor is empty.
![image](https://user-images.githubusercontent.com/13365687/36654864-7d07acd8-1abf-11e8-9eb6-1affebbd594b.png)

When doing the same with 2 selected lines in step 1, and you switch between both lines in HU Editor, then the Attribute Editor appears after first switch.
![image](https://user-images.githubusercontent.com/13365687/36654880-9f178ca8-1abf-11e8-9a92-95cecbba5b1e.png)

### What is the expected or desired behavior?
The Attribute Editor shall be shown initially in Handling Unit Editor when a row (left view) is selected.

**Comment by metas-lc** [comment]
IT
1. open hu editor with 1 CU line
=> attributes are visible OK

Regression
2. open hu editor with LU-TU-CU 
=> attributes are visible OK
3. open hu editor with TU-CU 
=> attributes are visible OK

**Comment by metas-ts** [comment]
:cherries: to `release`
