### ISSUE TITLE
Clicking in field w/ 1 value in dropdown sets the value directly

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1628]
### Is this a bug or feature request?
Bug, i think
### What is the current behavior?
If you have a dropdown w/ only 1 value in a field, e.g. pricelist in bpartner window, then clicking or double clicking in that field just sets the value, the dropdown does not open and you cannot properly select the value. Likewise, you cannot set the value back, since you don't get the "empty" option from dropdown.
#### Which are the steps to reproduce?
1. Open bpartner window
2. Select a bpartner that is not customer yet, make sure you have only 1 customer pricelist
3. Set customer=Y in the resp. tab, and double click in pricelist field:
=> customer pricelist is set directly, no dropdown opens for you to select
4. Try setting the value back to no pricelist: 
=> not possible, dropdown does not open
### What is the expected or desired behavior?
Value shall be set after selecting it from dropdown, setting it back shall be possible.

**Comment by siemiatj** [comment]
Related task #1622

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

I  repeated the test case from the issue and it works fine: 
* OK: The pricelist is set directly, but I can change it
* OK: I have the none option
* OK: I can change between the pricelist and the none option as many times I tried.
* OK: The entry is saved correctly when I set the pricelist and when I set no pricelist.

**Comment by metas-ts** [comment]
:cherries:  to `release`

**Comment by metas-rc** [comment]
* Checked briefly in other windows. It seems to work well there, too.

**Comment by metas-rc** [comment]
Some other problems found while testing
* deleting selected value is not possible. Followup: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1648

* Scrollbar doesnt'work with mouse: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1605
