### ISSUE TITLE
Setting attributes in orderline not working

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1630]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you set an attribute in orderline, you can select it, but is not set and saved in the orderline.
#### Which are the steps to reproduce?
1. Create an orderline (purchase or sales side) w/ a product that has asi set
2. Open the window for attribute selection
3. Select e.g. AdR from the dropdown
4. Click somewhere else to have your change saved: nothing happens
5. When you refresh the page, the attribute is gone

![2018-02-26 17_24_11-metasfresh](https://user-images.githubusercontent.com/18696715/36681915-2e0d300c-1b1a-11e8-8977-58e7a4924530.png)

### What is the expected or desired behavior?
Attribute shall be set in orderline as selected.

**Comment by siemiatj** [comment]
Fix ready, will push after doing more tests in other parts of the application.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* OK: The attributes can be set and are correctly saved in the db.
