### ISSUE TITLE
Attributes not displayed for first line in material receipt candidate HU Editor

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1631]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you open the HU Editor for material receipt candidates, the first line is selected, but the attributes on the right side are not shown. You have to select the 2nd line and then the 1st line again to have the attributes displayed, clicking on the 1st line or clicking somewhere else in the window and then selecting the 1st line again has no effect=> when you have only 1 line, i.e. when you receive only CUs, you cannot set attributes!

![2018-02-26 17_28_17-metasfresh](https://user-images.githubusercontent.com/18696715/36682302-08a0875a-1b1b-11e8-872e-a1ed7d2254cc.png)

![2018-02-26 17_28_37-metasfresh](https://user-images.githubusercontent.com/18696715/36682312-10382ac2-1b1b-11e8-95f6-f3f22d44ba32.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Attributes on the right side shall be displayed right away.

**Comment by metas-ts** [comment]
:cherries: to `release` (as #1625 )
