### ISSUE TITLE
Collapsible lines in Create Purchase Order modal

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1637]
### Is this a bug or feature request?
bug
### What is the current behavior?
when you select an included line in Create Purchase Order modal, the first line uncollapses
#### Which are the steps to reproduce?
1. go to sales order and create a new one or use https://w101.metasfresh.com:8443/window/143/1000493
2. select the line(s) and go to actions -> Create purchase orders
=> modal appears, with 1 line (or depends how many lines you selected in sales order). Readonly and collapsible
3. collapse the first line
=> included documents appear 
4. try to select one, or collapse further
=> it uncollapses back NOK

![image](https://user-images.githubusercontent.com/16001666/36787127-a8badf48-1c91-11e8-961e-08abac017d0c.png)

### What is the expected or desired behavior?
selecting included lines shall not uncollapse

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: when clicking on the line for creating purchase order the included lines are opened
* OK: I can click on the editable qty and the line does not collapses back
* OK: I can introduce the wanted qty
* OK: If I click somewhere else, the line collapses back
* OK: The qty I entered is saved in the line even after I closed it
* OK: If I press done the purchase order created.
