### ISSUE TITLE
Lookup Widget drop-down list scroll behavior

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1642]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Lookup widget scroll behavior in long lists is somehow exhausting for the user's eyes. In long drop-down lists with scrollbar, and using the ```arrow-down``` the list directly starts to scroll.
#### Which are the steps to reproduce?
- Open Sales Order. 
- Go to batch entry mode for lines. Focus on Product Batch entry.
- Press ```spacebar```, press ```arrow-down```.
-> the whole list starts scrolling (instead of moving the cursor to the middle of the list height and scrolling then)
### What is the expected or desired behavior?
Change the behavior, so the curser runs down to the middle and then the lists shall start scrolling.

![image](https://user-images.githubusercontent.com/13365687/36845818-7c6b6972-1d58-11e8-99f7-c74a0bf5d96a.png)

**Comment by PabloSichert** [comment]
Hey @metas-mk, could you explain how to enter the batch entry mode?

It's either not there or I can't find it

**Comment by metas-ts** [comment]
@metas-dh :cherries: picked to branch `2018-12`
