### ISSUE TITLE
Mandatory List Widget

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1645]
### Is this a bug or feature request?
Bug

**Comment by metas-ts** [comment]
merged it all to  `release`

**Comment by siemiatj** [comment]
This task was about adding blue borders around mandatory list fields.

**Comment by metas-lc** [comment]
IT
mandatory list fields:
1. documents headers (e.g. document type) => blue borders OK
2. modals (e.g. HU Editor - transform action) => mandatory field "Aktion" is blue OK
created a follow-up for a field which is mandatory but not set as mandatory https://github.com/metasfresh/metasfresh-webui-api/issues/962
3. grid view (e.g. bpartner window, credit limit tab, Type field) => you can double click on it, remove the type and then the border is blue => OK
