### ISSUE TITLE
List dropdown improvements

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1646]
### Is this a bug or feature request?
Bug

### What is the current behavior?
1. When lookup dropdown is displayed, it's possible to have two fields selected.
2. Wrong field selected in the dropdown when hovered with mouse and closed the field. It persists after closing the field.

Both issues can be seen on the attached gif.

![wyu9ejum3z](https://user-images.githubusercontent.com/513460/36896890-9bf5aa34-1e14-11e8-9e83-af3647047ca5.gif)

#### Which are the steps to reproduce?

1. Open field with lookup dropdown and hover over an option with the mouse.
2. Open field with normal list dropdown and hover over an option (that is not selected) without selecting it. Then click away and reopen this widget.

### What is the expected or desired behavior?

1. We should deselect the first field when mouse hover is detected
2. We should reset selection after closing the dropdown field.

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

I did some stress test on the fropdown fields for C_BPartner and was not able to reproduce the described errors => OK
