### ISSUE TITLE
Inbox and Sidelist shall not be opened at the same time

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#165]
Proposal: Inbox and Sidelist shall not be opened at the same time
When using keyboard shortcuts for inbox and sildelist components, then the "old" compontent always closes before the "new" one opens. I like this. Shouldn't we also have this behavior when using mouse?
wdyt?

![image](https://cloud.githubusercontent.com/assets/13365687/21380063/c5d51b56-c752-11e6-9808-97350b0a22bd.png)

**Comment by cadavre** [comment]
It's a bug – already reported.

**Comment by metas-mk** [comment]
ok, thx.
