### ISSUE TITLE
Edit mode in grid view when focus lost

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1650]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, when editing a field in grid view, then leaving the field with ```TAB```, the edit modus remains in that field. Double-clicking Outside in the same row works. Double-clicking outside in other rows does not work.
#### Which are the steps to reproduce?
Open, try and see. Go to contact Tab in https://w101.metasfresh.com:8443/window/123/2156438.
### What is the expected or desired behavior?
When leaving a field in edit modus, then the field shall be switched to non-edit modus again automatically.
![image](https://user-images.githubusercontent.com/13365687/36969270-4fc9c408-2065-11e8-9148-6f8837972359.png)

**Comment by metasnw** [comment]
tested on master 
https://w101.metasfresh.com:8443/window/123/2156431
![image](https://user-images.githubusercontent.com/16079655/37092110-cf483eca-220a-11e8-982f-dcadf0fdfc2e.png)

- change a field in grid view and click somewhere else
- NOK: edit mode remains 

also tested on a branch system with latest master 5.48.1-8734+master

**Comment by metasnw** [comment]
@siemiatj also on latest master the edit view is not going back to normal when you click in another line or somehwere else

**Comment by siemiatj** [comment]
@metasnw I can't reproduce this. Any tips ?

![pm6mibhf2g](https://user-images.githubusercontent.com/513460/37126301-ad0ae1bc-2270-11e8-8076-8c10ba2d030d.gif)

**Comment by metasnw** [comment]
@siemiatj use the partner window and edit the string fields of the contacts there

**Comment by siemiatj** [comment]
@metasnw I think something's wrong with the deployment again. It does work locally on master (in the same window), but it's broken on w101.

**Comment by metasnw** [comment]
@siemiatj I can confirm. It works on a docker branch test system :-) 
but not on w101

**Comment by siemiatj** [comment]
@metasnw so is this finally working, or not ?

**Comment by metas-mk** [comment]
@siemiatj checked on w101, yes, works on w101. moved to rollout so it can be tested further.

**Comment by metas-lc** [comment]
IT
started to edit a field in included tab grid view
=> pressed on another row: field is not in edit mode anymore OK
=> pressed on same row, different field: field is not in edit mode anymore OK
=> pressed somewhere outside the tab: field is not in edit mode anymore OK
