### ISSUE TITLE
Multi Line Text Field ist not patched when text is removed

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1651]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
1. have a window with a multi line text field
1. put text into the field
1. OK: content is saved
1. remove the text
1. NOK: nothing happens

easy example:
https://w101.metasfresh.com:8443/window/540026/1000001

### What is the expected or desired behavior?
should save the empty field

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: The multiline text is saved
* OK: The multiline text is deleted
* OK: If I want to delet it all, I can do it either by selecting it all with the mouse or with ctrl A,  then pressing delete, or ctrl+x, or right click->cut etc. It works every time
* OK: Whatever I change in the text is saved.
