### ISSUE TITLE
Provide support for time widgets

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1654]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, the time widgets are not supported. 
#### Which are the steps to reproduce?
* For example, go to the window Tourversion (https://mf15cloudit/window/540333) and try to set PreparationTime fields.
=> date is also included
### What is the expected or desired behavior?
* Please, implement the logic to support Time Widgets

**Comment by metas-rc** [comment]
Backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/892

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* Tested in TOurverion window

![image](https://user-images.githubusercontent.com/16001442/38196098-c6724136-3689-11e8-8906-14938a47d784.png)


* OK: The Time widget contains only time no dates
![image](https://user-images.githubusercontent.com/16001442/38196110-d79fa3e0-3689-11e8-9753-a2c858e6e809.png)

* NOK: The hour gets decremented when saved ( when clicking somewhere else)

![image](https://user-images.githubusercontent.com/16001442/38196160-19532492-368a-11e8-9794-2071cc5836e0.png)


This is probably related with the timezone and shall be covered in this task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1547

**Comment by metas-rc** [comment]
Results of IT 2

* NOK: The time is still decremented when saved. TO be solved in  #1547

* OK: If I click on the time widget without changing the suggested time, then click somewhere else, the suggested time is saved.
* OK: If I delete an already set time, it is really deleted.

**Comment by siemiatj** [comment]
@metas-rc Since this one problem will be handled by a separate issue, can we close this one ?

**Comment by teosarca** [comment]
@siemiatj  @metas-rc  yup, let's close it.
