### ISSUE TITLE
Single Date Field not patched in some cases

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1660]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
https://www.useloom.com/share/722de4078a334c71baca2bbf741ed2e9

- click into date field
- wait for the date picker
- go one digit left with the mouse to select the "8"
- use keyboard to change it to 7
- click somehwere to leave the field
- NOK: not saved

### What is the expected or desired behavior?
should accept users data always in all cases

Workaround:
use tab to leave the field

**Comment by metas-lc** [comment]
IT
repeated the testcase above => works fine: the document is saved after you click outside OK
