### ISSUE TITLE
Pos1 does not jump to page 1 anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1663]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Pos1 key to control pagination page 1, does not work anymore.
#### Which are the steps to reproduce?
Open any main grid view and press ```end``` (goes to last page), then press ```pos1```. Nothing happens (should jump to page 1.
### What is the expected or desired behavior?
Please fix.

**Comment by siemiatj** [comment]
What is `pos1` ?

**Comment by metas-mk** [comment]
Home button.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* ```pos1``` does jump to page 1: OK
* ```pageup```, ```pagedown``` and ```end``` also still working fine: OK
