### ISSUE TITLE
List Widget selection with arrow ignored when cursor is on the list

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1666]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* If I click on the dropdown and the mouse cursor stays somewhere in that list, I can use the arrow down and the entries are highlighted as selected one by one.
* If I stop pressing the arrow, before I got to the bottom of the list, the highlighted is the one I got to with the arrow down
* But if I go lower with the list with the arrow down, when I stop, the selected item will be the one from where the cursor is.
Please check my gif below: 

![Alt Text](http://g.recordit.co/MjcUuDyuzr.gif)

#### Which are the steps to reproduce?
* Try and see
### What is the expected or desired behavior?
* If I select with the arrow, the cursor shall be ignored if it doesn't move.

**Comment by siemiatj** [comment]
@PabloSichert related to your last changes, or mine ?

**Comment by PabloSichert** [comment]
@siemiatj it was implemented like that in https://github.com/metasfresh/metasfresh-webui-frontend/pull/1657.

Maybe we should block the one entry the mouse in hovering over from getting focus after releasing the arrow keys

**Comment by metas-rc** [comment]
I noticed this bug cannot be reproduced any more. I am moving it to done.
