### ISSUE TITLE
Location dropdown opens again when opening the batch entry

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1672]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you create e.g. a sales order and set the location from dropdown, then use [alt+q to open batch entry, the location dropdown opens once more.
#### Which are the steps to reproduce?
1. Create a sales order, set the bpartner: 
=> dropdown for location opens: OK
2. Set the locations, either w/ mouse or by using Enter:
=> location is set, OK
3. Use [alt]+q to open batch entry:
=> batch entry opens, OK
=> location dorpdown opens again: NOK

### What is the expected or desired behavior?
The location dropdown shall only open again when user clicks there, not somewhere else.

**Comment by siemiatj** [comment]
Can you maybe try recording this ? It doesn't seem to be happening for me. Testing on w101. By `location dropdown` you mean the dropdown in `Business Partner` field ?

**Comment by metas-dh** [comment]
@siemiatj http://recordit.co/qxQYHuOPiY

i noticed this only happens still when
* the bpartner has >1 location to select from
* you don't use ```Enter``` or mouse click to select the location, but just use ```Tab```

**Comment by siemiatj** [comment]
Ok so I think there are two separate things here : 
1. Clicking tab once just toggles list dropdowns. You need to tab a second time to move to the next field. This was changed intentionally a while ago.
2. Quickinputs didn't get the initial focus after opening. This will be fixed with a PR.

Otherwise the rest seems to be working fine to me.

**Comment by metas-lc** [comment]
IT
1. make sure you have a bpartner with multiple locations
2. create a new sales order with this bpartner: add bpartner's name
=> address field is prefilled. Dropdown doesn't open anymore. Task: (?)
3. select another location for your bpartner, press tab (or use enter, or mouse click) then alt+q 
=> batch entry opens OK
=> address dropdown remains closed OK
.
There is a case that is not working nice: 
1. i have 3 locations. loc1, loc2 and loc3
2. select locations dropdown, make sure you are on loc3. open it again, hover the last one in the list, leave it open. 
3. press alt+q
=> dropdown is still selected
3. add a product, press enter
=> in address, loc1 selected and added NOK 
http://recordit.co/diqir4eEh2

**Comment by siemiatj** [comment]
@metas-lc Can you create a separate issue for this last case you described ? It's not really related to what caused other problems here.
