### ISSUE TITLE
Improve User Interface for tablet media size

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1673]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the User Interface for Tablet Size does not look very good and wastes a lot of space.
#### Which are the steps to reproduce?
The following windows/ modal overlays are in the current focus of this issue:
- Handling unit editor https://w101.metasfresh.com:8443/window/540189
- Picking Tray Clearing https://w101.metasfresh.com:8443/window/540371
- Distributions editor modal overlay https://w101.metasfresh.com:8443/window/540373
- Material Receipt Candidates modal overlay https://w101.metasfresh.com:8443/window/540196

Also needed but no UI changes currently needed:
- Physical Inventory https://w101.metasfresh.com:8443/window/168
- Transportation Order https://w101.metasfresh.com:8443/window/540020

### What is the expected or desired behavior?
Please consider the following adjustments for mobile devices/ tablets (! look&feel shall remain untouched for desktop machines !):
- Browser Full-screen mode?
- Top Bar smaller
- Bottom Bar out
- No pagination. Only lines down.
- Filter label out
- Action Label out
- Improvement of collapsible Icons (out) and space (flatter hierarchy indicator)
- Green button + list shall be shown always (not cut off)
- Rows height (a bit smaller) but still large enough for finger navigation

Example for modal overlay:

![image](https://user-images.githubusercontent.com/13365687/37351559-a6bb3acc-26db-11e8-9493-6a768604b042.png)

**Comment by teosarca** [comment]
About media sizes, used to determine when a column to be shown, please see https://github.com/metasfresh/metasfresh-webui-api/issues/901#issuecomment-373345758

**Comment by metas-dh** [comment]
checked with metas-mk: OK, already have follow ups for further changes & improvements, so moving it to done.
