### ISSUE TITLE
Date field change not saved when editing from grid

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1678]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
1. open /window/540321/2008396
1. change valid from to any other date
1. NOK: change is not saved
1. Workaround: use advanced edit instead

**Comment by siemiatj** [comment]
Tested locally with latest master and can't reproduce.

**Comment by metasnw** [comment]
tested on 5.49.1_1145_master and also could not reproduce
