### ISSUE TITLE
Layout bug with resolution 1920x1200

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1679]
### Is this a bug or feature request?
bug

### What is the current behavior?
when using  resolution 1920x1200 the field layout is smalle as more fields are displayed and the widget size is ignored
![image](https://user-images.githubusercontent.com/16079655/37408894-5b084332-279d-11e8-944f-e7e69fb928df.png)

e.g. /window/143/1000537

once you change something (e.g. double click on qty) in the line the layout switches and the product field gets to the same size as with resolution 1920x1080:
![image](https://user-images.githubusercontent.com/16079655/37409173-edc95d3c-279d-11e8-8f96-3eb2902c8b41.png)

**Comment by metasnw** [comment]
also saw it on 5.47 with resolution 1920x1080

**Comment by siemiatj** [comment]
What should I be looking for here ? Screenshot from latest master and 1920x1200 in dev tools responsive mode :
 
![screen shot 2018-03-20 at 1 16 57 am](https://user-images.githubusercontent.com/513460/37628993-74fc0790-2bdc-11e8-9d36-c1124737d519.png)

**Comment by siemiatj** [comment]
For ITs : it's enough to have the browser window at least 1200px wide to test this.

**Comment by metas-lc** [comment]
checked product field from order window in my browser's resolution, in 1920x1200 and 1920x1080
=> the field has the same size and doesn't change if you make something in the lines. OK
other thing i notice that it's probably related (even though it happens in any resolution) : open contract window, see No. field: it's small at beginning and then, if you e.g. sort fields, it gets bigger
https://w101.metasfresh.com:8443/window/540359?viewId=540359-ff00c02322c74bb780dc318931b27a05&page=1
shall i create a new task?

**Comment by metasnw** [comment]
> open contract window, see No. field: it's small at beginning and then, if you e.g. sort fields, it gets bigger

that is exactly the behavior I would have expected to be fixed in this issue

**Comment by siemiatj** [comment]
In order to completely get rid of that, we need to set columns to a fixed widths.

**Comment by metas-lc** [comment]
IT
1. the field still gets a bit larger when you use zoom in (110%)- zoom out (100%), but is not that visible and the product;s name fits OK?
2. checked No. field from contracts window => big enough, not affected by sorting OK
