### ISSUE TITLE
Tooltip overlays action menu entry "new"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#168]
Tooltip overlays action menu entry "new"
- tooltip for home menu missing "false"
- also different behavior between action menu and notification tooltip
a) home menu hover --> minimal pause + then tooltip opens (but wrong design) + click --> tooltip dissappears
b) notification hover --> tooltip on + click --> tooltip dissappears
c) action menu hover + tooltip on + click --> tooltip remains
--> I prefer a) behavior + correct tooltip design

wdyt?

**Comment by teosarca** [comment]
definitely, +1 for a)
