### ISSUE TITLE
Camera Barcode workflow improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1680]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, we have a new functionality in metasfresh that allows the usage of webcams/ cameras for barcode scanning. The scanning and number confirmation takes several clicks. The webcam stays active also after scanning has been finished.
#### Which are the steps to reproduce?
Open try and see in the following windows:
- window/540189
- window/540371
- window/540345
### What is the expected or desired behavior?
Switch off the camera as soon scanning has happened.
Allow the following workflow when scanning a barcode
- press button for scan filter
- show the camera scanning directly in fullscreen/ larger (info shall be provided by backend?)
- as soon as the barcode is identified and decrypted, add as criteria to the initial filter (without the need to press any further buttons).

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Switch off the camera as soon scanning has happened: OK
* as soon as the barcode is identified and decrypted, add as criteria to the initial filter (without the need to press any further buttons): tested this in window/540373:
   * field Lagerort was set after barcode was identified: OK
   * no need for further actions: OK
* i could stop the camera with pressing the X, but the modal remained, i had to refresh the page to leave: NOK i think

**Comment by metas-dh** [comment]
Update:
* stopping the camera by pressing the X works fine now, see #1681
