### ISSUE TITLE
Data Entry via barcode scan in Action Parms

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1681]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, a new feature was built that allows the barcode scanning via webcam/ camera. This does not work in action parms/ process parameters.
#### Which are the steps to reproduce?
Open, try and see.
- Window https://w101.metasfresh.com:8443/window/540373
- Action Move HU
- Allow the scan of "Locator To"
### What is the expected or desired behavior?
Possibility to trigger a barcode scan via camera when focussed in a parameter.

![image](https://user-images.githubusercontent.com/13365687/37473609-cbc884d4-286e-11e8-9433-8be83054baaa.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Possibility to trigger a barcode scan via camera when focussed in a parameter:
* barcode scan worked fine (used barcode from SSCC label): OK
* i still had to set the HU manually, and could select HUs which were not the ones my barcode was taken from: NOK i think, but not sure if this is relevant in this issue? @metas-mk wdyt?
* i could stop the camera with using ```X```, but the modal remained, i had to refresh the page to leave: NOK imho

**Comment by siemiatj** [comment]
I don't have real barcodes to test this, and there was nothing about automatically selecting HU's or limiting the options in the ticket.

For the last point, I'll have a PR in a few.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15:

 * stopping the camera by pressing the X worked fine: OK

**Comment by metas-dh** [comment]
>i still had to set the HU manually, and could select HUs which were not the ones my barcode was taken from: NOK i think, but not sure if this is relevant in this issue? 

checked w/ metas-mk: OK, HU selection will be done before scanning
