### ISSUE TITLE
Combine dropdown list of <List> and <Lookup> component

### ISSUE THREAD

**Issue by PabloSichert** [metasfresh/metasfresh-webui-frontend#1684]
### Is this a bug or feature request?
Issue combining multiple bugs: #1544, #1605, #1641

### What is the current behavior?
Both `<List>` and `<Lookup>` widgets implement their own dropdown lists. Behaviour is not consistent and both of them have their own set of bugs.

### What is the expected or desired behavior?
Merge functionality by sharing the same dropdown component and have it work as intended

**Comment by metas-rc** [comment]
Results of IT


* #1641 IT OK
* #1544 IT OK
* #1605 IT OK - exception: The scrollbar is still not working but it will be covered in #1606
