### ISSUE TITLE
API login for cypress

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1686]
### Is this a bug or feature request?

Feature

### What is the current behavior?

Right now it's not possible to authenticate a user without going through the whole login form flow, as we're setting some variables in the internal state on form response.

#### Which are the steps to reproduce?

Try using `loginByForm` custom command.

### What is the expected or desired behavior?

We should be able to login without using the login form.

**Comment by siemiatj** [comment]
@metas-lc I think we can close this one since there's nothing to test here.

**Comment by metas-lc** [comment]
@siemiatj Thanks. Closing it
