### ISSUE TITLE
tab does not trigger saving number field

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1699]
### Is this a bug or feature request?
bug

### What is the current behavior?
found on master and 5.49 release candidate:
when you enter quantity in order line and leave the field with TAB the field qty is not patched and therefore the api does not recalculate sum, etc.

workaround: use mouse click instead.

#### Which are the steps to reproduce?
video: http://recordit.co/or3AuGKXVp

**Comment by metasnw** [comment]
IT on branch test system was good

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* tab triggers saving number field in orderline: OK
* also tested text field, date field etc., w/ tab / mouseclick: OK
(checked in latest RC as well, all worked fine)
