### ISSUE TITLE
System information texts

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#17]
How will we get system information texts like:

* text for info about empty dataset in table (i.e. no order lines)

**Comment by teosarca** [comment]
I see 2 options, and i think we shall have both of them, depending on the case.
1. have a service which provides those messages in user's language
2. in case of "empty dataset in a table", thinking to provide something like "fields-empty-msg" in response JSON.

wdyt?

**Comment by cadavre** [comment]
Ad 2) Generally introducing "empty-message" is a good idea. Right now we have "(none)" for placeholders widgets hardcoded but it's good idea to provide them from API (as "none" is not a best solution for other languages than EN :p).

How does your translations engine works like now? Do you have "trans_id: Translation" mapping per language?

**Comment by teosarca** [comment]
> How does your translations engine works like now? Do you have "trans_id: Translation" mapping per language?

Yes we have it per language and we have it on different levels (e.g. window, tab, field, column and also we have general messages).
Basically it's a big database with translations and it would not be realistic to send it to frontend.
That's why i am thinking to, additionally, have this messages service as a fallback.

About, 2. i am thinking to provide those message, once, in the layout.

**Comment by cadavre** [comment]
I suggest to keep one way of doing it, so if you provide already-translated captions – we should do the same with placeholders for each element. We may think about generalizing into single property ofc.

**Comment by teosarca** [comment]
Ofc we will do it like that, whenever is possible, they will be provided in layout.

But in some cases i suspect this won't be enough... and when we will get to those cases we might think to some messages service or some reduced properties file....

**Comment by teosarca** [comment]
mr @cadavre , i think we can close this one, right?
