### ISSUE TITLE
attribute filter fields are shrinked 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1700]
### Is this a bug or feature request?
bug

### What is the current behavior?
attribute filter fields are shrinked look like:
![image](https://user-images.githubusercontent.com/16079655/37761685-a90fdb3a-2dba-11e8-9586-372965012c4a.png)

#### Which are the steps to reproduce?
found on 5.49RC and latest master

1. go to /window/123
1. click filter

### What is the expected or desired behavior?
frame should be so big that the text fits in

**Comment by metas-lc** [comment]
IT
checked attribute filter - it's big and the text fits in
