### ISSUE TITLE
View is not deleted when modal view is closed

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1703]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When closing a modal view, the frontend shall delete the view, which is not happening atm, therefore feautres like purchase order from sales order or rack system are not working as before.
#### Which are the steps to reproduce?
See e.g. https://github.com/metasfresh/metasfresh/issues/3723
### What is the expected or desired behavior?
Frontend shall delete the view.

**Comment by siemiatj** [comment]
This was fixed in this commit https://github.com/metasfresh/metasfresh-webui-frontend/commit/141b8dc3b58c7ee74fa0374f3c2d21bbb2dba5bf#diff-f00342e6ab4dd4d3cf8dbbd8dcf0d639 . What version is being tested @metas-dh ?

**Comment by metas-dh** [comment]
@siemiatj happened in version 5.49.2-586+release
=> checked current version 5.50.1-9081+master, where it's working again (tested rack system in picking), so i guess when #1689 is CPed to release it will work there as well.

**Comment by metas-dh** [comment]
rack system worked fine in RC as well, closing this one.
