### ISSUE TITLE
Barcode Scan leaved Webcam switched on

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1705]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When using the new Barcode Scan functionality with webcam, then the webcam does not switch off after scanning (tested in action parm scanning)
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
After scanning (and confirm) the webcam shall switch off.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* tested for action parm, in window/540373: webcam switched off after scanning: OK
