### ISSUE TITLE
Red line is missing when a document was not saved

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1707]
### Is this a bug or feature request?
bug
#### Which are the steps to reproduce?
e.g. go to invoice window and create 2 new, same bpartner, document type and document number
![image](https://user-images.githubusercontent.com/16001666/37837258-6feda1c6-2ebd-11e8-874d-dd6ebd1e5f38.png)

=> a red line indicating the invoice wasn't saved is missing
### What is the expected or desired behavior?
add red line when a document is not saved (same can happen in modal windows)

**Comment by siemiatj** [comment]
Soo we don't get the info on invalid fields, but we do get an error message. So I decided to show what we have : 

![screen shot 2018-08-13 at 18 57 20](https://user-images.githubusercontent.com/513460/44046169-f3e0656c-9f2a-11e8-9e7e-a4e7467a95d8.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

red line is shown when a document was not saved:
* re-tested the case above: red line is displayed, OK
* error msg (with resp. info for the problem which prevents saving): displayed as well, OK

* in case the document cannot be saved yet bc mandatory fields are not yet filled: red line is shown, OK, but: info about the mandatory field not yet filled is shown as well, so if you have sev. mandatory fields in a document (e.g. manufacturing order: 6), then there are more and more errors popping up as you go filling the mandatory fields, which imho is a weird user experience:
http://recordit.co/7um0O2SPNG

@metas-mk @siemiatj wdyt?
