### ISSUE TITLE
File upload label not translated anymore

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1708]
### Is this a bug or feature request?
bug

### What is the current behavior?
![image](https://user-images.githubusercontent.com/16079655/37850176-8c8b301a-2eda-11e8-98eb-d7bd99d78172.png)

#### Which are the steps to reproduce?
http://docs.metasfresh.org/webui_collection/EN/File_handling.html

**Comment by PabloSichert** [comment]
See https://github.com/metasfresh/metasfresh-webui-frontend/issues/1640#issuecomment-372043227 for which keys need to be added

**Comment by metasnw** [comment]
thx @PabloSichert 
I notice there is already a followup here: https://github.com/metasfresh/metasfresh/issues/3664
