### ISSUE TITLE
Harmonize Border Look&Feel between Lookup and List widget

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1709]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the List widgets don't look the same as Lookup widgets.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Harmonize the Look&Feel (height, rounded corners) between List and Lookup widgets (besides the focus indicator, that shall remain as they are in each).

![image](https://user-images.githubusercontent.com/13365687/37862285-a6b1c5a6-2f4a-11e8-894b-f87a6e0a45c4.png)

**Comment by metas-lc** [comment]
IT

1. checked a dropdown field in document
=> same as Lookup widgets, the corners are rounded, same height OK
2. checked the same in process and modals
=> same as Lookup widgets, the corners are rounded, same height OK

don't know if it shall be changed or not: noticed that focused dropdowns have now a bit of curve
![image](https://user-images.githubusercontent.com/16001666/38366614-009b63a4-38e9-11e8-9175-a8c2fa330594.png)
this is how it was before:
![image](https://user-images.githubusercontent.com/16001666/38366624-0c2951b8-38e9-11e8-969f-1b896a91ecd9.png)

**Comment by metas-rc** [comment]
Results of IT



Tested on webui



* OK: The lists and lookups are all nicely curvet at the corners.
* OK: dropdowns are not curved

* NOK: Date and text references are still a bit curved at the bottom margins. Followup created: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1749
