### ISSUE TITLE
Dropdown list in grid view does not open with mouse click

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1712]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Dropdown list in grid view, in subtab, does not open with mouse click.
#### Which are the steps to reproduce?
1. Open sales order, window/143
2. Create an orderline
3. Double Click on field Terms & Conditions
4. Click on the field again:
=> dropdown list does not open, but field on the right of Terms & Conditions is selected: NOK
=> dropdown opens when using ```arrow-down```, OK

### What is the expected or desired behavior?
Dropdown list shall open with mouse click.

**Comment by siemiatj** [comment]
@metas-dh  I'm not sure if I'm testing the right thing, but this `Terms & Conditions` form seems to be working fine on current master.

![dropdowns](https://user-images.githubusercontent.com/513460/37978230-e0b3290a-31e5-11e8-842e-c68dea79faf4.gif)

**Comment by metas-dh** [comment]
@siemiatj i mean the terms & conditions field, in sales order, orderline grid view:

http://recordit.co/P3ehBwqKbQ

dropdown for the available terms  does not open when using mouse click, 1st & 3rd time, only when using ```arrow-down``` (2nd time)

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-lc** [comment]
IT
repeated the testcase above => works fine: you can select the entries with mouse click (also with keyboard) OK
did some regression. We are still missing req from this task: 
https://github.com/metasfresh/metasfresh-webui-frontend/issues/1606
