### ISSUE TITLE
Typing in dropdown fields

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1722]
### Is this a bug or feature request?
fr
and follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1606
### What is the current behavior?
currently you cannot type anything in dropdown fields. We need to be able to type so we can search for a specific word. Right now you can press on a letter and the first entry starting with that letter is selected. 
#### Which are the steps to reproduce?
open e.g. https://w101.metasfresh.com:8443/window/540173/1000002
select document base type
try to write "Mat"
=> you cannot write

### What is the expected or desired behavior?
if you write M, scrollbar (and selection) shall go to the word that starts with M "Maintenence order" in this case. If you write "Mat" => Match invoice

**Comment by metas-lc** [comment]
IT
talked with @metas-mk . We need to rollback because it's a bit more difficult to search for e.g. all words that contain or start with "order". 
In future, if we have dropdowns that aree too long, we should switch them to search fields.

**Comment by siemiatj** [comment]
Sure. Once you'll figure out how you'd like this to work let me know.

**Comment by metas-mk** [comment]
IT: Pls check the initial search Feature (toggle through first character in dropdown list).

**Comment by metas-lc** [comment]
IT
checked dropdown fields from headers, filters, gridviews and modals 
=> they work as before
=> cannot write in it
=> if you write e.g. M - you get to the first word starting with M. Pressing M multiple times sends you to the next words starting with M and so on. When you reach the end it comes back to beginning. OK
