### ISSUE TITLE
Error in console when typing in search field

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1723]
### Is this a bug or feature request?
bug
### What is the current behavior?
there is an error in console when you start typing in search fields
#### Which are the steps to reproduce?
1. go to e.g. purchase order (window 181)
2. create a new one and start writing in bpartner field
=> error in console 
(note that this error appears in console and adding a bpartner works fine)

![image](https://user-images.githubusercontent.com/16001666/38245610-7ac2497a-3747-11e8-8327-60a3b724725c.png)

same for product
![image](https://user-images.githubusercontent.com/16001666/38245612-80fce57a-3747-11e8-9a02-c8cb02aa4ecb.png)

### What is the expected or desired behavior?
no errors

**Comment by siemiatj** [comment]
@metas-lc  This thing was released already as far as I know, so ready to run through IT's.

**Comment by teosarca** [comment]
@siemiatj  right

moved it to Rollout.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


OK: No error message in console when writing in search fields in purchase order, neither in main view, included tab, advanced edit, nor filters.
