### ISSUE TITLE
Tab not working in address modal window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1725]
### Is this a bug or feature request?
Bug
### What is the current behavior?
```Tab``` does not work in the address modal window.
#### Which are the steps to reproduce?
1. Open bpartner window/123
2. In tab location, Add new
3. Press Address Edit: in modal window, start writing in field Adress 1, then use ```Tab```: nothing happens, NOK
4. Use ```Tab``` a few times: at some point a field in the background is highlighted
### What is the expected or desired behavior?
Shall work.

**Comment by metas-dh** [comment]
maybe related to #1675

**Comment by siemiatj** [comment]
Not related, but similar. My fix won't fix it unfortunately.

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* ```Tab``` works as before in address modal window: OK
* quickly checked ```Tab``` in e.g. orderline, text field or date field: worked fine, OK
