### ISSUE TITLE
Create purchase orders process - fields collapse

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1730]
### Is this a bug or feature request?
bug
### What is the current behavior?
when you update a field in Create purchase orders process, the fields collapse
#### Which are the steps to reproduce?
1. go to sales order and create a new one (or use an existing one https://w101.metasfresh.com:8443/window/143/1000598)
2. select the product line and run action " Create purchase orders "
![image](https://user-images.githubusercontent.com/16001666/38306330-e3ad870c-3818-11e8-9674-9f1595ce393e.png)
3. expand the line (to have lines there you have to go to your product, bpartner tab, and add a bpartner there)
4. set a qty, press enter or tab or move to another field somehow
=> the lines collapse
![image](https://user-images.githubusercontent.com/16001666/38306206-79fb1a36-3818-11e8-9717-a891c9a7a37d.png)

### What is the expected or desired behavior?
lines should not collapse after setting values in fields

**Comment by metas-rc** [comment]
Results of IT


Tested on webui



NOK: The fields still collapses after I set the qty and then press tab, of I press enter, or I click on another field

**Comment by siemiatj** [comment]
New PR ready.

**Comment by metas-lc** [comment]
IT
repeated the testcase above
=> if you press tab/enter/ another field, the rows do not collapse OK
=> it expands/collapse only if you press on that +/- button OK
