### ISSUE TITLE
Picking Terminal opens with all rows uncollapsed

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1734]
### Is this a bug or feature request?

Bug' caused by fix to #1730 

### What is the current behavior?

When user goes to the picking terminal it will open with all rows uncollapsed which seriously impacts the performance. If the app has some data already (either by opening other windows first or in cache), it will load properly.

#### Which are the steps to reproduce?

Go to `/window/540189` and then change the url to `/window/540345` and load the picking terminal.

### What is the expected or desired behavior?

Terminal should load with fields collapsed.

**Comment by metas-rc** [comment]
Results of IT


Tested on webui


* OK: Now, fields are opened as collapsed.
