### ISSUE TITLE
email Editor Adress Lookup behavior

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1740]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Follow-Up for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1539.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Harmonize the behavior if this Adress Lookup to the dropdowns of Lookup Widget/ List Widget (Mouse, Keyboard Behavior, initially selected item)

**Comment by teosarca** [comment]
@oliviupis  pls document what was fixed here. thanks

**Comment by oliviupis** [comment]
@teosarca keyboard behavior was fixed and selected item is shown in dropdown if selected. mouse behavior was working.
