### ISSUE TITLE
Table doesn't take the full available height

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1744]
### Is this a bug or feature request?

Bug

### What is the current behavior?

Regression. If table doesn't have enough data, the pagination is positioned directly under the data rows.

#### Which are the steps to reproduce?

Go to `/window/232`. Notice the position of the table pagination. 

### What is the expected or desired behavior?

It should look like this : 

![screen shot 2018-04-10 at 12 57 48](https://user-images.githubusercontent.com/513460/38553202-c2637750-3cbe-11e8-9f90-1b6e37369519.png)

**Comment by metas-ts** [comment]
:cherries:picked to `release`

**Comment by metas-dh** [comment]
Results fo IT1
tested in RC

* Table takes the full available height again: OK
* checked layout overall for changes / problems: all looked fine
