### ISSUE TITLE
Tab not working in Manufacturing Order, Receive HUs modal window

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1747]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you use Receive HUs action in manufacturing order, window/53009, ```Tab``` is not working in the modal window.
#### Which are the steps to reproduce?
1. Create a manufacturing order, open the modal for Issue/Receipt
2. Select the first line, choose Action "Receive HUs"
3. Select a packing item and an LU type
4. In the fields for qty CU, qty TU and qty LU use ```Tab```: not working, NOK
### What is the expected or desired behavior?
Shall work.

**Comment by siemiatj** [comment]
@PabloSichert any ideas if it's related to previous changes to tab handling ? I've also noticed this in KPI's config modal.

**Comment by siemiatj** [comment]
Seems to be related to #1675

**Comment by metas-dh** [comment]
Update:
this worked fine in this week's e2e, so i would close this issue for now. @siemiatj wdyt?
