### ISSUE TITLE
X not available for field invoice partner when first setting the partner in order

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1748]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you first set a partner in an order, the partner is also set in field invoice partner, but there is no X available to delete that partner, only the magnifying glass. After refresh the X appears.
#### Which are the steps to reproduce?
1. Create a new order, sales or purchase
2. Set a partner in order partner field: => same partner is set in field invoice partner: OK
3. No X for deleting the invoice partner in the field, only the magnifying glass, location is readonly and cannot be changed, same as invoice contact: NOK
4. When you refresh the page or press only the magnifying glass, then the X appears
### What is the expected or desired behavior?
Shall be available right away, as in order partner field.

**Comment by metasnw** [comment]
IT OK
- OK: field is prefilled and does show an X
- OK: clicking removes its content
- OK: after removing you can put another partner

**Comment by metas-ts** [comment]
:cherries: picked to `release`
