### ISSUE TITLE
Text and Date fields are a bit curved at the bottom margins

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1749]
Followup for https://github.com/metasfresh/metasfresh-webui-frontend/issues/1709

### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently, the Text and Date fields are a bit curved at the bottom margins

![image](https://user-images.githubusercontent.com/16001442/38565509-2b5d4ecc-3cea-11e8-86b3-4130af8a4046.png)

#### Which are the steps to reproduce?
* Open and see
### What is the expected or desired behavior?
* Please, make those margins straight

**Comment by siemiatj** [comment]
Fixed with #2222
