### ISSUE TITLE
Shortcuts not working on Mac

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1752]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Keyboard shortcuts are not working. Probably due to the fact, that `Alt` on Mac is `Option/Alt`.
#### Which are the steps to reproduce?
Try any of the shortcuts when running on Mac.
### What is the expected or desired behavior?
Shortcuts should work.

**Comment by siemiatj** [comment]
Yeah, but I think we should have a separate ticket for this. On OSX shortcuts don't work at all.

**Comment by metas-dh** [comment]
Results of IT1
tested in OS X 10.11.6

shortcuts working acc. to http://docs.metasfresh.org/webui_collection/EN/Keyboard_shortcuts_reference.html:

* not working are ```⌥ alt + W``` for Clone and ```⌥ alt + R``` for Letter, but those have not been working at all for a while, see #1410
* the rest work fine: OK

**Comment by metas-ts** [comment]
:cherries: picked to `release`
