### ISSUE TITLE
date field does not recognize changes on double click

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1755]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
broken case:
1. open request window: window/232/1000000
1. create new request
1. put a reminder date with double clicking on the date
1. click somewhere else outside the field
1. NOK: its not saved

working case:
1. open request window
1. create new request
1. put a reminder date with single clicking on the date
1. click somewhere else outside the field
1. OK: its saved

### What is the expected or desired behavior?
1. case should work for both single and double click
1. automated test for that as it was already broken several times

**Comment by metas-ts** [comment]
:cherries: picked to `release`
