### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1758]
### Is this a bug or feature request?
Bug?
### What is the current behavior?
Atm the performance is not very good for some actions, e.g. when processing a manufacturing order (took ca. 10 sec. in last e2e) or adding serial no.s for CUs in HU Editor (usually took about 5 sec., took ca. 9 sec. in last e2e).
#### Which are the steps to reproduce?
Open HU Editor, select a CU line and start action "Adding Serial No.".

**Comment by teosarca** [comment]
@metas-dh  why do you think it's a frontend issue?

**Comment by siemiatj** [comment]
I'd check if it's not the requests. Sometimes loading quickactions takes forever : 

![screen shot 2018-06-27 at 23 27 55](https://user-images.githubusercontent.com/513460/42000707-d56d0b0a-7a61-11e8-9c5e-b1a673de243d.png)
