### ISSUE TITLE
Cloning document throws error

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1768]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Cloning document throws backend error.
#### Which are the steps to reproduce?
Use the shortcut to clone a document (for instance any Sales Order). Testable after #1766 is merged as right now the shortcut doesn't work.
### What is the expected or desired behavior?
Cloning document should work.

**Comment by metas-lc** [comment]
IT
checked different documents => no errors when you clone when you use shortcut. Document cloned OK
