### ISSUE TITLE
Dropdown widget shall NOT cache the result

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1769]
### Is this a bug or feature request?
FR/Bug
Required for https://github.com/metasfresh/metasfresh-webui-api/issues/954

### What is the current behavior?
Dropdown widget is caching the result.

#### Which are the steps to reproduce?
e.g.
* open sales orde, e.g. https://w101.metasfresh.com:8443/window/143/1000832
* open Warehouse field's dropdown => remark: the dropdown endpoint is called to fetch the data
![image](https://user-images.githubusercontent.com/1244701/39400858-38d8b216-4b41-11e8-8c25-1518d1c58335.png)

* try to open it again => NOK: dropdown endpoint is not called anymore. The result is served from some cache.

### What is the expected or desired behavior?
Don't cache the dropdown data.
Ask backend eachtime.

**Comment by siemiatj** [comment]
@teosarca I guess we can close this one, right ?

**Comment by teosarca** [comment]
exactly. thanks.
