### ISSUE TITLE
Date Field Content not aligned 1px

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1771]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The COntent of Date Fields is not aligned with other Fields
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Align the content of Date Fields with other Field Content

![image](https://user-images.githubusercontent.com/13365687/39470465-394a4dbe-4d3e-11e8-8b00-472e4fad1c20.png)

**Comment by metas-lc** [comment]
IT
checked window 53005
=> date fields are aligned OK
