### ISSUE TITLE
Harmonize List widget Icon Look&Feel when not empty

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1772]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the List Widget shows 2 Icons next to each other when it is not empty.
- circle X Icon (for content delete)
- triangle Icon as Dropdown identifier
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Harmonize the List widget Icon with Lookup Widget when not empty and only show the circled X in these cases. If the Field is empty then show the triangle as already is.

![image](https://user-images.githubusercontent.com/13365687/39470677-42f20b08-4d3f-11e8-9760-710826928bc2.png)

**Comment by metas-lc** [comment]
IT
checked List widget Icon in headers, gridview, modal and filters
=> when is set only x icon appears, when is empty only down triangle appears OK
