### ISSUE TITLE
Cursor changing to "restricted"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#178]
Cursor changing to resticted. Why?
If not needed, please fix. Example see /window/143/1002815

![image](https://cloud.githubusercontent.com/assets/13365687/21774699/926f2c8e-d693-11e6-80ea-7e3e60ee78e9.png)

**Comment by damianprzygodzki** [comment]
It is because field is disabled. We are using Bootstrap, CSS framework and it is changing cursor for disabled fields like checkbox or radio button to 'not-allowed'.
