### ISSUE TITLE
Search fields in filters are not working

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1784]
### Is this a bug or feature request?
bug
follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1765
### What is the current behavior?
cannot use search fields in filters
#### Which are the steps to reproduce?
1. open a window that has search filters, e.g. material receipt candidates /540196
2. try to write something in search filter 
=> error String document IDs cannot be converted to int: 540092-I
### What is the expected or desired behavior?
should work, no errors

**Comment by metas-lc** [comment]
it seems that adding a product in a sales/ purchase order, using batch entry or add new - is not working. Checking if it's related with prcelist or something.

**Comment by siemiatj** [comment]
This looks like a backend thing.

**Comment by teosarca** [comment]
nop, the typeahead URL when filtering views is wrong.

**Comment by teosarca** [comment]
i.e. this endpoint shall be used: http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/getFilterParameterTypeaheadUsingGET_1

**Comment by metas-lc** [comment]
this is used atm path:"/rest/api/documentView/540196/540196-Dl/540196-Dl/edit/C_BPartner_ID/typeahead"

**Comment by siemiatj** [comment]
Got it, looks like it's using the url that should be used in modals.

**Comment by metas-lc** [comment]
IT
1. search fields in filters work OK
regression:
2. doc headers OK
3. batch entry OK
4. pricing conditions OK
5. advanced edit OK
6. hu editor OK
