### ISSUE TITLE
Fields too short for documentno in Breadcrumbs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#179]
Fields too short for documentno in Breadcrumbs
Please adjust to fitting width.

![image](https://cloud.githubusercontent.com/assets/13365687/21775493/a53c9fe2-d696-11e6-9a42-ff2f44d732f1.png)

**Comment by damianprzygodzki** [comment]
What is the "fitting width"? I think that we cannot make input content-driven, furthermore we have after that field, one more label, that is whole name of document with date.

**Comment by metas-mk** [comment]
@damianprzygodzki please adjust the documentsNo field to a fixed width of 8 char (would allow 6 digits + 2 brackets
