### ISSUE TITLE
modal view editing issues

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1794]
### Is this a bug or feature request?
Bug
required for https://github.com/metasfresh/metasfresh/issues/3925

#### Which are the steps to reproduce?
* open sales order: https://w101.metasfresh.com:8443/window/143/1000892
* select first order line and call `Pricing Conditions` action
![image](https://user-images.githubusercontent.com/1244701/40130539-05387aec-5940-11e8-9e36-d2ff7d09b85f.png)

##### Issue 1. /dropdown endpoint has incorrect URL
On first row, the editable one, click on `Type` field to open it's dropdown => ERROR because the endpoint URL is not correct
![image](https://user-images.githubusercontent.com/1244701/40130691-77e4cd34-5940-11e8-9879-11f79e4a2a09.png)

It shall be http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/getFilterParameterDropdownUsingGET_1

##### Issue 2. After PATCHing, the `viewEditorRenderMode` is not considered
Suppose Issue 1. is fixed. Now you will be able to patch the `priceType` field.
Based on the `priceType` value some of the fields are editable.
e.g. In case the price type is `Pricing System` then the `basePricingSystem` and `basePriceAddAmt` fields will be editable.
Because of that, the API will send back `viewEditorRenderMode: true` for those 2 fields.
But unfortunately that's ignored by frontend.

The fix shall be: 
* after patching, the frontend shall consider the `viewEditorRenderMode` value for each field which was returned in the result.
* if `viewEditorRenderMode` is missing for a field from result, the value provided in layout shall be used
* based on `viewEditorRenderMode` effective value frontend shall decide if it will render an editor, or it will be an editor on demand or it won't be an editor at all.

If more details/explanations are needed pls ping me.

### What is the expected or desired behavior?
See above.

**Comment by siemiatj** [comment]
@teosarca are you sure this is the correct endpoint ? I seem to be missing a lot of data to be able to do this request. Also I don't think this is a filter ? I remember you mentioning this endpoint in some earlier ticket : http://w101.metasfresh.com:8081/swagger-ui.html#!/view-row-edit-rest-controller/getFieldDropdownUsingGET . This one seems to be working fine.

**Comment by teosarca** [comment]
@siemiatj  😊  ... u're right. That's the right endpoint:

**Comment by teosarca** [comment]
@siemiatj  thanks for the PR. I've integrated it (https://github.com/metasfresh/metasfresh-webui-frontend/pull/1809).

Below i will document what's still pending.

### Base Pricing System field is still readonly
see https://github.com/metasfresh/metasfresh-webui-frontend/pull/1803#issuecomment-391247760

### Double clicking on Price field makes the price disapear
![image](https://user-images.githubusercontent.com/1244701/40531304-a78f76c2-6004-11e8-864e-b436edd3576b.png)
![image](https://user-images.githubusercontent.com/1244701/40531311-ab64ee8a-6004-11e8-92f2-87e4f76f0d65.png)

**Comment by siemiatj** [comment]
@teosarca in the response there's nothing that would tell me that field is readonly. Not even mentioning that the way we set the readonly flag in the code is super vague right now :/

![screen shot 2018-05-25 at 12 34 04](https://user-images.githubusercontent.com/513460/40540328-00b3666a-6018-11e8-8d71-2cb36a6580d2.png)

**Comment by siemiatj** [comment]
@teosarca then I guess you need to change the `viewEditorRenderMode` for the `PriceType` field, as otherwise it will be readonly : 

![screen shot 2018-05-25 at 16 46 40](https://user-images.githubusercontent.com/513460/40550710-2cfb5b92-603b-11e8-84f6-84b30bf1c312.png)

**Comment by metas-ts** [comment]
:cherries: picked to `release`.

**Comment by siemiatj** [comment]
Can we get this tested ?
