### ISSUE TITLE
Material Receipt Candidate: first line is not pre-selected and no action button available when opening HU Editor 

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1800]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you open the HU Editor in material receipt candidates (window/540196), the first line is not pre-selected anymore and the action button is not available. You have to use the mouse to select the line, therefore you cannot work quickly. only using shortcuts.

![2018-05-22 16_18_02-metasfresh](https://user-images.githubusercontent.com/18696715/40368300-c3f979aa-5ddb-11e8-90c1-3d3c494a7bf1.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
First line shall be selected and action button shown when opening HU Editor in the window.

**Comment by teosarca** [comment]
btw, if is easy, i would suggest to also create an automated test for this case.

**Comment by teosarca** [comment]
note to IT: pls also test https://github.com/metasfresh/metasfresh-webui-frontend/pull/1804#issuecomment-391299722

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* first line is pre-selected when opening the HU Editor in material receipt candidates: OK
* the action button is available directly (and working fine): OK
* selection does not jump from your line to first line, when changing an attribute in another line than the first (see #1751): OK
* https://github.com/metasfresh/metasfresh-webui-frontend/pull/1804#issuecomment-391299722 this was still happening for me: NOK
![2018-05-25 09_19_36-metasfresh](https://user-images.githubusercontent.com/18696715/40531792-a9d1ebd8-5ffd-11e8-964d-9b7c44618e23.png)

**Comment by teosarca** [comment]
@metas-dh about https://github.com/metasfresh/metasfresh-webui-frontend/pull/1804#issuecomment-391299722

We decided that if u click on breadcrumb link:
* the view is refreshed
* selection is cleared
* `/quickActions` shall be called (without `?selectedIds=` parameter... because there are no rows selected)

If it works like that, then it's OK.

**Comment by metas-dh** [comment]
@teosarca 
but the first row is still selected or at least looks like it is selected, after clicking on breadcrumb, see pic above (when i use the action button i get to the Emtpies Return modal, btw), is that OK? imho the first row should not be marked as selected, like the rest; or is that another problem?

**Comment by teosarca** [comment]
@metas-dh if the first row is still selected, than it's not OK.
Weird it is that, for me, on w101 it works. wtf?!

**Comment by siemiatj** [comment]
For me it works both on w101 and locally.

**Comment by teosarca** [comment]
wondering if for @metas-dh  happens because of https://github.com/metasfresh/metasfresh-webui-frontend/issues/1311 .

Remark the screenshot she posted. The "Disable cache" checkbox is not set (which ofc, it's how a regular user will use the application).

**Comment by siemiatj** [comment]
@metas-dh is it still a thing ?

**Comment by metas-dh** [comment]
@siemiatj  checked again: works fine the first time i tried, but at the 2nd time i clicked the breadcrumb after selecting the first row, the row seems to be still selected, while the Action button shows "Empties" action:

![2018-06-13 08_40_20-metasfresh](https://user-images.githubusercontent.com/18696715/41334353-a11bbd92-6ee5-11e8-9abc-41c016af2f59.png)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* original problem still fixed: OK
* https://github.com/metasfresh/metasfresh-webui-frontend/pull/1804#issuecomment-391299722 this is also working fine now, for 1st time and every time after i switched from selected line to breadcrumbs: OK
