### ISSUE TITLE
Multi Line Text fields are displayed infinitely

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1805]
### Is this a bug or feature request?
bug

### What is the current behavior?
on current dev master multi line text fields are displayed infinitely in grid views
before their size was limited

#### Which are the steps to reproduce?
1. have multi line text field in grid view
1. have more text in it than can be shown

https://w101.metasfresh.com:8443/window/540354/2156426

**Comment by metasnw** [comment]
@metas-mk @siemiatj how is the fixed width working with the different widget sizes that are today used to configure the width?
So lets say I set a multi line text field to small. Will it still be 350px max?

**Comment by siemiatj** [comment]
style-wise it should work like that, but can you somehow create a field like that so that we can test it ?

**Comment by metas-dh** [comment]
Results from IT1
tested in weekly e2e

multi line text field in grid view:
* Businesspartner B2C window, tab Request: looks fine, text field is not displayed infinitely; when you hover over the field you get the text displayed with line breaks: OK

![2018-05-28 16_50_22-metasfresh](https://user-images.githubusercontent.com/18696715/40619998-824823ec-6297-11e8-9638-5a8a1a024629.png)

* Businesspartner B2C window, tab History:  text field is still displayed infinitely, with long scrollbar to the right: NOK i think

![2018-05-28 16_51_33-metasfresh](https://user-images.githubusercontent.com/18696715/40620021-909580b6-6297-11e8-9c0c-85619fc2d0ef.png)

**Comment by siemiatj** [comment]
This is due to the fact, that field has wrong widget type. @metasnw is this the same field we were talking about ?
