### ISSUE TITLE
Shortcuts for inbox, menu and sidelist

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1808]
### Is this a bug or feature request?
bug
### What is the current behavior?
alt+3, alt+4, alt+5, alt+6 and alt+7 when are pressed twice, should close the lists. Now is just refreshing them
#### Which are the steps to reproduce?
e.g. open order window, press alt+3 (inbox), alt+4 (menu), alt+5 (doc list), alt+6 (ref docus) or alt+7 (attachments) twice
=> the menus are not closing, but refreshing

### What is the expected or desired behavior?
when pressed twice, shall close

**Comment by metas-lc** [comment]
please also check how the following shall work: 
when you are in e.g. letter (alt+r) and press alt+d, delete popup appears in the background OK?

**Comment by PabloSichert** [comment]
> when you are in e.g. letter (alt+r) and press alt+d, delete popup appears in the background OK?

I'd say it's fine. Otherwise one could confuse the dialog with deleting the letter only, when it actually deletes the whole order.

**Comment by metas-lc** [comment]
IT
alt+3, alt+4, alt+5, alt+6 and alt+7 when are pressed twice, close the lists OK
