### ISSUE TITLE
Fields are set on null when you press tab too fast

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1811]
### Is this a bug or feature request?
bug
### What is the current behavior?
Fields are set on null when you press tab too fast
#### Which are the steps to reproduce?
1. create a new sales order, set all mandatory fields
2. keep pressing tab
=> lots of fields are set on null
![image](https://user-images.githubusercontent.com/16001666/40546556-404b96d8-6038-11e8-9051-6052b57c120b.png)

### What is the expected or desired behavior?
fields should stay set

**Comment by siemiatj** [comment]
Can you record how should I be reproducing this ? In my case `Target Document` and `Warehouse` fields are pre-filled. Also what should be the expected behaviour ?

**Comment by metas-lc** [comment]
http://recordit.co/W4TWj7JRcO

on last step i set my cursor in bpartner, then i pressed tab longer

**Comment by metas-lc** [comment]
IT
repeated the testcase in sales order and bpartner window => pressing tab long, or fast multiple times, doesn't update fields anymore OK
