### ISSUE TITLE
Cannot set attribute in orderline grid view

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1813]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you try to set an attribute in orderline grid view, modal just closes, no attribute is set.
#### Which are the steps to reproduce?
1. Create orderline, sales or purchase 
2. Select a product that has attribute instance set
3. Try setting an attribute in grid view:
* attribute modal opens, OK
* select an attribute: not working, modal window closes: NOK
(got no error in console, or in inspect)
4. Try setting the attribute in advanced edit: working fine
### What is the expected or desired behavior?
Shall work.

**Comment by siemiatj** [comment]
Looks like this is related to #1794 so will be fixed with the same PR.

**Comment by metas-ts** [comment]
:cherries: picked to `release`.

**Comment by metas-lc** [comment]
IT
1. grid view: works
2. advanced edit: works OK
3. header (e.g. manufacturing window): works OK
4. process (e.g. revenue report): works OK
5. HU attributes: work OK
