### ISSUE TITLE
Action button is too large

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1814]
### Is this a bug or feature request?
bug
might be related with https://github.com/metasfresh/metasfresh-webui-frontend/pull/1754
### What is the current behavior?
action button is too large
#### Which are the steps to reproduce?
1. open bpartner pharma window and see (id 540409)
![image](https://user-images.githubusercontent.com/16001666/40660506-d76b2014-6359-11e8-8f60-8c4af8d885b1.png)

### What is the expected or desired behavior?
buttons should not expand if the title is too long

**Comment by metas-mk** [comment]
For IT: Please also check the Batch Entry Layout in Sales Order/ Purchase Order if ok.

**Comment by metas-mk** [comment]
for IT: PR https://github.com/metasfresh/metasfresh-webui-frontend/pull/1818 is now merged

**Comment by metas-lc** [comment]
IT
1. button doesn't expand anymore (you can hover to see the whole name) OK
2. Batch Entry Layout in Sales Order/ Purchase Order - OK
