### ISSUE TITLE
Searchresults are missing in Navigation menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#182]
Searchresults are missing in Navigation menu

![image](https://cloud.githubusercontent.com/assets/13365687/21808230/9fa02d04-d742-11e6-91f9-902a4c852738.png)

**Comment by damianprzygodzki** [comment]
https://github.com/metasfresh/metasfresh-webui-frontend/issues/156 Related, tested, to implementation.

**Comment by cadavre** [comment]
I'm closing this due to duplicate of #156 .
