### ISSUE TITLE
Search in Full Navigation sometimes omits character when typing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#183]
Search in Full Navigation sometimes omits character when typing
In the case below I typed "rech". In some cases when u hit the right timing (it seems so when you type at the same time when "refresh" is done) then the character "c" is omited. typing faster it can also be the 4th or 5th character where it happens.

![image](https://cloud.githubusercontent.com/assets/13365687/21811918/9a83fa9e-d751-11e6-8d79-7365dd7a2ca8.png)

**Comment by damianprzygodzki** [comment]
@Dunkat i think it is because that `<DebounceInput...` plugin component. Could you check that?

**Comment by Dunkat** [comment]
Thanks, I will check

**Comment by cadavre** [comment]
Any input here?

**Comment by Dunkat** [comment]
fixed
