### ISSUE TITLE
Empty login page after logout

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1830]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you logout, the login page remains empty. You have to refresh the page to get the login window to be displayed correctly to login again.

![2018-06-04 16_47_23-metasfresh](https://user-images.githubusercontent.com/18696715/40924273-1db0e27c-6817-11e8-8a7e-294eb4f0884f.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
The login shall be displayed correctly after logout.

(Not sure this is a frontend issue or not)

**Comment by siemiatj** [comment]
Already fixed in #1823

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

login is displayed correctly after logout: OK
