### ISSUE TITLE
Fields in modal window are copied to the one in the back

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1831]
### Is this a bug or feature request?
bug
### What is the current behavior?
if you have fields that are called the same in a process and in a normal window, and you set them in the process, then they are set in the normal window as well
#### Which are the steps to reproduce?
1. create a new manufacturing order, like this one https://w101.metasfresh.com:8443/window/53009/1000044
2. take a look on attributes field
=> there are only 3 you can set. Leave them for now
![image](https://user-images.githubusercontent.com/16001666/40924717-ab370db6-6820-11e8-87f2-d2b5160306ca.png)

3. in the same tab, open "Business Partner Revenue" process
4. set a product (a different one that you have in your order) and some attributes (like country)
5. cancel the process
6. see product and the attributes from your manufacturing order
=> product and attributes are from the process
=> instead of 3 attributes you see all
![image](https://user-images.githubusercontent.com/16001666/40924674-8edd6f20-6820-11e8-9f67-ff613543e541.png)

**Comment by siemiatj** [comment]
The way it works now, is we're updating fields with the same name both in the modal and master view. I think it's for the cases, when user is for instance editing some products displayed in the table. 

```javascript
export function updatePropertyValue(property, value, tabid, rowid, isModal) {
  return dispatch => {
    if (tabid && rowid) {
      dispatch(
        updateRowFieldProperty(property, { value }, tabid, rowid, 'master')
      );
      if (isModal) {
        dispatch(updateDataFieldProperty(property, { value }, 'modal'));
      }
    } else {
      dispatch(updateDataFieldProperty(property, { value }, getScope(isModal)));
      if (isModal) {
        //update the master field too if exist
        dispatch(updateDataFieldProperty(property, { value }, 'master'));
      }
    }
  };
}
```

this `Business Partner Revenue` seems to be an edge-case, so I need to figure out how to handle that.

**Comment by siemiatj** [comment]
@teosarca to be able to fix that we'd need a flag for windows that open in modals, but are not related to content beneath them (so for instance the aforementioned `Business Partner Revenue` is completely separate from whathever it's displayed over vs editing Address on Business Partner page). Or fields would need completely unique names.

**Comment by teosarca** [comment]
@siemiatj  i think we don't need a flag. we can just have some rules, e.g.
* process parameters panel shall never influence the document behind
* to check if we are talking about same document we just need to compare the windowId and documentId
wdyt?

**Comment by metas-lc** [comment]
IT
repeated the testcase above
=> product and attributes were not copied OK
