### ISSUE TITLE
404 error shall be centered

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1840]
### Is this a bug or feature request?
bug

### What is the current behavior?
When u access a document which does not exist, the "404 Document type not found." is diplayed in the top left corner.

#### Which are the steps to reproduce?
Try https://w101.metasfresh.com:8443/window/1 for example.
![image](https://user-images.githubusercontent.com/1244701/41296591-f52cba2e-6e65-11e8-94f9-8480b67b99c9.png)

### What is the expected or desired behavior?
That message shall be in the center of the page (as it was some while ago).

**Comment by metas-lc** [comment]
IT
1. e.g. window/1
=> center, center OK
![image](https://user-images.githubusercontent.com/16001666/41469299-5681ae32-70b5-11e8-91c4-14a7e0071dc1.png)

2. e.g. /window/123/1
=> top center NOK
![image](https://user-images.githubusercontent.com/16001666/41469370-8c716bcc-70b5-11e8-905f-ad19df04a77c.png)

**Comment by metas-lc** [comment]
IT
repeated the testcase => both are aligned to center/center OK

created a task for the messages to be translated in de_DE: https://github.com/metasfresh/metasfresh/issues/4262
