### ISSUE TITLE
Auto Search dropdown opens empty when field focus

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#185]
Auto Search dropdown opens empty when field focus.
I think it should only open when at least 1 char has been written. wdyt?

![image](https://cloud.githubusercontent.com/assets/13365687/21840734/5a833020-d7df-11e6-9608-dcced98324df.png)

**Comment by cadavre** [comment]
"it should only open when at least 1 char has been written" – I'm +1 for this.
 We can always show dropdown only on 1st char added/removed.

**Comment by damianprzygodzki** [comment]
Just to make sure, are we talking about behavior in whole app?

**Comment by cadavre** [comment]
Yes.
