### ISSUE TITLE
Initial Setup Wizard window's layout is distorted

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1850]
### Is this a bug or feature request?
Bug

### What is the current behavior?
![initial setup wizard window](https://user-images.githubusercontent.com/29163573/41507959-fcab45ec-723c-11e8-94a8-301f86cd6770.png)

#### Which are the steps to reproduce?
Open Initial Setup Wizard from the menu.
(http://docs.metasfresh.org/webui_collection/EN/InitialSetupWizard.html)

### What is the expected or desired behavior?
Should look tidy like this:

![initialsetupwizard](https://user-images.githubusercontent.com/29163573/41507971-3bc0e5b6-723d-11e8-80b2-4801a5da50ec.png)

**Comment by siemiatj** [comment]
@teosarca @metas-dh looks like this is caused by the backend, as the image id received with the layout is invalid : 

![screen shot 2018-06-25 at 11 25 57](https://user-images.githubusercontent.com/513460/41842469-2c16b454-786b-11e8-848f-1c50a104b0ed.png)


![screen shot 2018-06-25 at 11 29 40](https://user-images.githubusercontent.com/513460/41842475-33c41868-786b-11e8-8199-136b03b0049c.png)

**Comment by teosarca** [comment]
@siemiatj  yes, we can improve it and instead of returning "-1" when the image is missing we should return something like null/missing.
But nevertheless, imho, the image placeholder the text shall not overlap

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* layout is not distorted anymore: OK
* server error shown in window (without further info), afais it's related to the error described here https://github.com/metasfresh/metasfresh-webui-api/issues/438 

![2018-07-06 09_14_48-metasfresh](https://user-images.githubusercontent.com/18696715/42366559-c2c0863e-8101-11e8-8288-ca18a2d12149.png)

**Comment by metas-dh** [comment]
created new issue for the server error now popping up in the window, https://github.com/metasfresh/metasfresh-webui-api/issues/1003

closing this one since the laylout of the SetUp Wizard looks fine now.
