### ISSUE TITLE
Inline rendering filter parameters

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1859]
### Is this a bug or feature request?
Follow-up of  https://github.com/metasfresh/metasfresh/issues/4238

### What is the current behavior?
When a filter is flagged as `frequent`, frontend is rendering a button with the name of the filter. When the button is pressed, a parameters panel pops.

#### Which are the steps to reproduce?
Check https://w101.metasfresh.com:8443/window/123.

### What is the expected or desired behavior?
We introduced a new property in our layout filter definition.
It's called `inlineRenderMode` and defines how the filter shall be rendered when it's `frequent`.
* button - same as it is now, i.e. just a button with the filter name. When pressed the filter parameters panel pops.
* inline-parameters - render the parameters directly on that lane where the filter it is, instead of rendering the button. When user presses enter in a param field then the filter shall be applied.

**Comment by siemiatj** [comment]
@teosarca can you share link to a view which has this new property for filters ? It's not available for `window/123` yet.

![screen shot 2018-06-28 at 21 05 39](https://user-images.githubusercontent.com/513460/42055326-17d4c68a-7b17-11e8-84a7-d7191b7aefb6.png)

**Comment by teosarca** [comment]
@siemiatj  did a rollout and now it's available
![image](https://user-images.githubusercontent.com/1244701/42155965-7257dac4-7df2-11e8-84d7-0a86e751e4bc.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. bpartner window: new property in layout filter definition:

* inlineRenderMode: "inline-parameters", for filterId: "full-text-search", frequent: true: OK
* inlineRenderMode: "button", for filterId: "default", frequent: false: OK

![2018-07-17 14_50_36-metasfresh](https://user-images.githubusercontent.com/18696715/42818340-e71b62ce-89d0-11e8-8696-4d73ee55ce1e.png)

2. Filter usage:
* inline-parameters: When user presses enter in a param field then the filter shall be applied: entered e.g. "Test" in the param field and pressed Enter: filter is applied directly: OK
* button: When pressed the filter parameters panel pops up: "Default" pops up, and when clicking that the filter params you can set: OK
