### ISSUE TITLE
Save Indicator bar not consitent in docaction area

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#186]
Save Indicator bar not consitent in docaction area. Is a pixel slimmer than elsewhere. Please adjust.
Info: appears for green indicator and for grey one.

![image](https://cloud.githubusercontent.com/assets/13365687/21841084/f34f46da-d7e0-11e6-8d6d-3298540d6a8b.png)

**Comment by cadavre** [comment]
Not UX, but GUI bug. Loader line should not be inconsistent.
