### ISSUE TITLE
Patch not sent when you delete a text in grid view

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1865]
### Is this a bug or feature request?
bug
### What is the current behavior?
Patch not sent when you delete a text in grid view and press enter
#### Which are the steps to reproduce?
1. go to e.g. Bill of material window and select an entry https://w101.metasfresh.com:8443/window/53006/2002873
2. go to lines, write smth in CU Label Qty
![image](https://user-images.githubusercontent.com/16001666/42089597-9ee48180-7ba6-11e8-9c11-a4d49e74c1b9.png)

3. press enter - patch in sent OK
4. directly remove what you wrote, press enter -  patch in sent OK
5. write something again, press enter, select another field, go back, remove what you wrote, press enter
=> patch not sent NOK

note:  also notice that the field is blue. usually the fields are blue when a field is mandatory, right? 
![image](https://user-images.githubusercontent.com/16001666/42089661-f1082ee4-7ba6-11e8-96e8-3469f7965d5a.png)

if this is also NOK, please either fix here, or create a new task
### What is the expected or desired behavior?
patch should be sent
(please check about the blue field)

**Comment by metas-lc** [comment]
IT
1. repeated the testcase above
=> patch is sent when you remove what you wrote OK

(have to check about the blue field)

**Comment by siemiatj** [comment]
@metas-lc I can't see any fields with blue border there. Any tips what should I click/edit ?

**Comment by metas-lc** [comment]
Bill of material (window/53006) -> included tab -> double click e.g. CU Label Qty
(but note i don't know if it's wanted or not... maybe it appears just to be more visible)

**Comment by metas-lc** [comment]
created new task for the blue fields: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1887
closing this one
