### ISSUE TITLE
CTRL-l leads to expand & focus in URL bar

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#187]
CTRL-l leads to expand & focus in URL bar, so that further keyboard shortcuts navigate in browser context and not in metasfresh context anymore. For example ctrl+l expands, using ctrl-1 after that goes to first tab of chrome browser. Focus after ctrl-l should be on quickentry product.

**Comment by cadavre** [comment]
Right now Ctrl+L is triggering expanded mode (expand/collapse) and Ctrl+1 works. Everything as expected and described above (no browser context).

I believe it's a matter of OS+browser behaviour.
On MacOS + Chrome all works good.

Please report about your browser.

**Comment by metas-mk** [comment]
hmmmmm ... does not make me happy ;-)
to be more precise. i believe strongly that in my environment windows + chrome the keystroke <ctrl> + l is already used by chrome to give the focus to url-bar.
thats the reason why we are then in browser context after pressing that.
solution: please provide another shortcut for expanding.

**Comment by damianprzygodzki** [comment]
Changed to `mod + K`
