### ISSUE TITLE
[alt]+u not working as before

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1872]
### Is this a bug or feature request?
Bug
### What is the current behavior?
[alt]+```u``` is not working as it used to:

**Material Receipt Candidates**, window/540196:
1. [alt]+```u``` when calling receive action, **for CUs only**: => material receipt candidate is marked as processed, QtyReceived & QtyOrdered are not correct, and the HUs that were received are inactive (not Gebinde Status inactive, but the HU itself):

![2018-07-09 14_01_49-metasfresh](https://user-images.githubusercontent.com/18696715/42492999-6e484a02-841b-11e8-96c1-b5383d886e86.png)

2.  [alt]+```u``` when calling receive action, **for HUs (e.g. LU with TU & CUs)**:  => error, see below, and planned HUs have status: Destroyed

<details/>
{timestamp: 1531204292890, status: 500, error: "Internal Server Error",…}
error
:
"Internal Server Error"
exception
:
"org.adempiere.exceptions.AdempiereException"
exceptionAttributes
:
{,…}
message
:
"saveUpdate failed↵Additional parameters:↵ po: X_M_ReceiptSchedule_Alloc[M_ReceiptSchedule_Alloc_ID=1000099, trxName=TrxRun_149c5711-e21a-45da-98c9-7c8ebfef9fa0]"
path
:
"/rest/api/process/ADP_540750/1001877/start"
status
:
500
timestamp
:
1531204292890
trace
:
["org.adempiere.exceptions.AdempiereException: saveUpdate failed", "Additional parameters:",…]
[0 … 99]
0
:
"org.adempiere.exceptions.AdempiereException: saveUpdate failed"
1
:
"Additional parameters:"
2
:
" po: X_M_ReceiptSchedule_Alloc[M_ReceiptSchedule_Alloc_ID=1000099, trxName=TrxRun_149c5711-e21a-45da-98c9-7c8ebfef9fa0]"
3
:
"	at org.compiere.model.PO.save0(PO.java:2841)"
4
:
"	at org.compiere.model.PO.access$100(PO.java:139)"
5
:
"	at org.compiere.model.PO$1.run(PO.java:2733)"
6
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)"
7
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)"
8
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
9
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
10
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
11
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
12
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)"
13
:
"	at org.compiere.model.PO.saveEx(PO.java:2727)"
14
:
"	at org.adempiere.model.POWrapper.save(POWrapper.java:799)"
15
:
"	at org.adempiere.model.InterfaceWrapperHelper.save(InterfaceWrapperHelper.java:595)"
16
:
"	at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.unassignHU(InOutProducerFromReceiptScheduleHU.java:749)"
17
:
"	at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.transferHandlingUnits(InOutProducerFromReceiptScheduleHU.java:628)"
18
:
"	at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.createReceiptLines(InOutProducerFromReceiptScheduleHU.java:232)"
19
:
"	at de.metas.inoutcandidate.spi.impl.InOutProducerFromReceiptScheduleHU.createCurrentReceiptLines(InOutProducerFromReceiptScheduleHU.java:195)"
20
:
"	at de.metas.inoutcandidate.api.impl.InOutProducer.process(InOutProducer.java:169)"
21
:
"	at de.metas.inoutcandidate.api.impl.InOutProducer.process(InOutProducer.java:72)"
22
:
"	at org.adempiere.ad.trx.processor.api.impl.TrxItemChunkProcessorExecutor.processItem(TrxItemChunkProcessorExecutor.java:260)"
23
:
"	at org.adempiere.ad.trx.processor.api.impl.TrxItemChunkProcessorExecutor.execute(TrxItemChunkProcessorExecutor.java:157)"
24
:
"	at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.processReceiptSchedules0(HUReceiptScheduleBL.java:380)"
25
:
"	at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.lambda$processReceiptSchedules$0(HUReceiptScheduleBL.java:298)"
26
:
"	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$5.call(TrxCallableWrappers.java:222)"
27
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)"
28
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)"
29
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)"
30
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)"
31
:
"	at de.metas.handlingunits.receiptschedule.impl.HUReceiptScheduleBL.processReceiptSchedules(HUReceiptScheduleBL.java:298)"
32
:
"	at de.metas.ui.web.handlingunits.process.WEBUI_M_HU_CreateMaterialReceipt.doIt(WEBUI_M_HU_CreateMaterialReceipt.java:80)"
33
:
"	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:276)"
34
:
"	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)"
35
:
"	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)"
36
:
"	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)"
37
:
"	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)"
38
:
"	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.runOutOfTransaction(AbstractTrxManager.java:934)"
39
:
"	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:282)"
40
:
"	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)"
41
:
"	at de.metas.process.ProcessExecutor.access$1100(ProcessExecutor.java:50)"
42
:
"	at de.metas.process.ProcessExecutor$Builder.executeSync(ProcessExecutor.java:651)"
43
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:285)"
44
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)"
45
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
46
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
47
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
48
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
49
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
50
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
51
:
"	at sun.reflect.GeneratedMethodAccessor357.invoke(Unknown Source)"
52
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
53
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
54
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
55
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
56
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
57
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
58
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
59
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
60
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
61
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
62
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
63
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
64
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
65
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
66
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
68
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
69
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
70
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
71
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
72
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
73
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
74
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
75
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
76
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
77
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
78
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
79
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
80
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
81
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
82
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
83
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
84
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
85
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
86
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
87
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
88
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
89
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
90
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
91
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
92
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
93
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
94
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
95
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
96
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
97
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
98
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
99
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
[100 … 129]
100
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
101
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
102
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
103
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
104
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
105
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
106
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
107
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
108
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
109
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
110
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
111
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
112
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
113
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
114
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
115
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
116
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
117
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
118
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
119
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
120
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
121
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
122
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
123
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
124
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
125
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
126
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
127
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
128
:
"	at java.lang.Thread.run(Thread.java:748)"
129
:
""
</details>

3. [alt]+```u``` when calling transform action, after selecting an aggregated CU: modal window for transform action pens for a split sec and then closes again, all planned HUs have status: Destroyed

<details/>
{timestamp: 1531204591123, status: 404, error: "Not Found",…}
error
:
"Not Found"
exception
:
"de.metas.ui.web.exceptions.EntityNotFoundException"
message
:
"No document found for rowId=1000102"
path
:
"/rest/api/documentView/husToReceive/husToReceive-D0/1000102/attributes/layout"
status
:
404
timestamp
:
1531204591123
trace
:
["de.metas.ui.web.exceptions.EntityNotFoundException: No document found for rowId=1000102",…]
0
:
"de.metas.ui.web.exceptions.EntityNotFoundException: No document found for rowId=1000102"
1
:
"	at de.metas.ui.web.handlingunits.HUEditorViewBuffer_FullyCached$IndexedHUEditorRows.getById(HUEditorViewBuffer_FullyCached.java:289)"
2
:
"	at de.metas.ui.web.handlingunits.HUEditorViewBuffer_FullyCached.getById(HUEditorViewBuffer_FullyCached.java:201)"
3
:
"	at de.metas.ui.web.handlingunits.HUEditorView.getById(HUEditorView.java:229)"
4
:
"	at de.metas.ui.web.handlingunits.HUEditorView.getById(HUEditorView.java:69)"
5
:
"	at de.metas.ui.web.view.ViewRowAttributesRestController.getAttributesLayout(ViewRowAttributesRestController.java:79)"
6
:
"	at sun.reflect.GeneratedMethodAccessor381.invoke(Unknown Source)"
7
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
8
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
9
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
10
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
11
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
12
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
13
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
14
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
15
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
16
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
17
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
18
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
19
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
20
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
21
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"
22
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)"
23
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
24
:
"	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)"
25
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
26
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
27
:
"	at org.springframework.boot.web.filter.ApplicationContextHeaderFilter.doFilterInternal(ApplicationContextHeaderFilter.java:55)"
28
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
29
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
30
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
31
:
"	at de.metas.ui.web.config.WebConfig$1.doFilter(WebConfig.java:82)"
32
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
33
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
34
:
"	at de.metas.ui.web.config.ServletLoggingFilter.doFilter(ServletLoggingFilter.java:89)"
35
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
36
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
37
:
"	at de.metas.ui.web.config.CORSFilter.doFilter(CORSFilter.java:85)"
38
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
39
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
40
:
"	at org.springframework.boot.actuate.trace.WebRequestTraceFilter.doFilterInternal(WebRequestTraceFilter.java:110)"
41
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
42
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
43
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
44
:
"	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)"
45
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
46
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
47
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
48
:
"	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)"
49
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
50
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
51
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
52
:
"	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)"
53
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
54
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
55
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
56
:
"	at org.springframework.session.web.http.SessionRepositoryFilter.doFilterInternal(SessionRepositoryFilter.java:167)"
57
:
"	at org.springframework.session.web.http.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:80)"
58
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
59
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
60
:
"	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)"
61
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
62
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
63
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
64
:
"	at org.springframework.boot.actuate.autoconfigure.MetricsFilter.doFilterInternal(MetricsFilter.java:106)"
65
:
"	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)"
66
:
"	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)"
67
:
"	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)"
68
:
"	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)"
69
:
"	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)"
70
:
"	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)"
71
:
"	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)"
72
:
"	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)"
73
:
"	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)"
74
:
"	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)"
75
:
"	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)"
76
:
"	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)"
77
:
"	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:861)"
78
:
"	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)"
79
:
"	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)"
80
:
"	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)"
81
:
"	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)"
82
:
"	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)"
83
:
"	at java.lang.Thread.run(Thread.java:748)"
84
:
""
</details>

**Manufacturing Order**, window/53009:
=> [alt]+```u``` when trying to call Pick action: the modal window opens for a split sec and then closes again

=> clicking the action button with mouse works fine!

(checking for more examples)
#### Which are the steps to reproduce?
Try and see.

**Comment by siemiatj** [comment]
1. I'm not sure I understand what's the problem here as there seem to be some inconsistencies. First of all first screen shows window 540189. Is this what I'm supposed to use to replicate this ? Anyway, neither in 540189 nor 540196 I can see the `Receive` action as the default.

2. Error seems to be exactly the same no matter if keyboard or mouse used. I don't have the mentioned `paramsIn` defined anywhere on the client so I'd need @teosarca to give me some insights as to what might be causing this : 

![screen shot 2018-07-11 at 00 39 40](https://user-images.githubusercontent.com/513460/42541522-e854f69c-84a2-11e8-9560-4cc90c5c2256.png)


3. In window 53009 I only have two actions available : `Issue/Receipt` and `Issue/Receipt (barcode)` which both seem to work exactly the same no matter if shortcut or mouse used : 

![case3](https://user-images.githubusercontent.com/513460/42541380-677d85b6-84a2-11e8-8af1-05a4d7ceeb32.gif)

**Comment by metas-dh** [comment]
> 1. Anyway, neither in 540189 nor 540196 I can see the ```Receive``` action as the default.

* ```Receive``` action is default when you have the HU Editor open, in window 540156, for a material receipt cand:
![2018-07-11 09_04_06-notificationsform](https://user-images.githubusercontent.com/18696715/42556316-7d17c3c0-84eb-11e8-9ce8-70205697aa88.png)


* calling the default action creates the receipt and the HU Editor closes, but here the whole candidate is marked as processed:

![2018-07-11 09_04_53-notificationsform](https://user-images.githubusercontent.com/18696715/42556028-919f012e-84ea-11e8-9420-0b8ff36caf1f.png)

* the HU i received is now set as inactive:

![2018-07-11 09_05_16-notificationsform](https://user-images.githubusercontent.com/18696715/42556037-96cb9144-84ea-11e8-8d33-7514a38b4759.png)

> 2. Error seems to be exactly the same no matter if keyboard or mouse used. 

seems to be the same in cloudit; in releasetest it worked fine when mouse was used. will check again

> 3. In window 53009 I only have two actions available

the ```Pick``` action is default after you have received some product and processed the order:

![2018-07-11 09_13_33-notificationsform](https://user-images.githubusercontent.com/18696715/42556241-4113f45c-84eb-11e8-8007-129215e5e592.png)

**Comment by siemiatj** [comment]
Problems 3 & 4 are fixed with my PR. As for the rest I can't really tell. Correct action seems to be called, but backend is returning some messages which I'm not sure if are right or wrong.

![screen shot 2018-08-13 at 14 40 04](https://user-images.githubusercontent.com/513460/44032313-07d8c470-9f07-11e8-8147-fa2510b951a4.png)

If this doesn't fix it, I'd comment out what's already working os they don't seem to be related.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

**Material Receipt Candidates**, window/540196:
1. [alt]+`u` when calling receive action, **for CUs only**: => material receipt is created correctly, HUs have status: Active: OK

2.  [alt]+`u` when calling receive action, **for HUs (e.g. LU with TU & CUs)**:  => material receipt is created correctly, HUs have status: Active: OK

3. [alt]+`u`  when calling transform action, after selecting an aggregated CU: modal overlay for setting the Transform action and resp. qties opens: OK

**Manufacturing Order**, window/53009:
4. => [alt]+`u`  when trying to call Pick action: the modal  overlay for selecting the shipement schedule and the picking slot opens: OK

=> i noticed there is no hint anymore for the [alt]+`u`  shortcut, when the mouse hovers over the action button (still shown when overing over e.g. the notification bell or the button for toggling the list of actions available): #1931
