### ISSUE TITLE
HU Editor in manufacturing order not updated correctly after issueing / receiving / picking

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1873]
### Is this a bug or feature request?
Bug
### What is the current behavior?
In Manufacturing order, window/53009, the HU Editor is not updated correctly after the first time you issue / receive / or pick a HU, you have to refresh the window.
#### Which are the steps to reproduce?
1. Have a manufacturing order, and HUs you can issue for a component
2. Issue 1 HU: => HU is not displayed in the left window of the HU Editor, NOK
3. Refresh the page: => issued HU is now displayed in the left window of the HU Editor underneath the component, OK
4. Issue another HU: also displayed in the left window of the HU Editor underneath the component, OK
5. Receive some qty: => no HUs for the received product are displayed in the HU Editor, NOK
 6.  Refresh the page: => received HU is now displayed in  the HU Editor underneath the product that'S produced, OK
### What is the expected or desired behavior?
HU Editor shall be updated correctly after the resp. action.

**Comment by siemiatj** [comment]
I will need a live video of this one as I have no idea how to reproduce this and how it should work.

**Comment by metas-dh** [comment]
@siemiatj  checked in releasetest & cloudit, to record a video of the problem, and this time it all worked fine, the HU Editor was updated right away; i'll check again when the next RC is build and if it's working fine there too, i'll close this issue.

**Comment by metas-dh** [comment]
http://recordit.co/BzOIr6woPn

@siemiatj worked like in the video a few times, usually the first time i issued or received sth, but it worked fine most of the times overall.

**Comment by metas-dh** [comment]
worked fine in this week's e2e again, closing this task.
