### ISSUE TITLE
Cannot complete documents

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#1880]
### Is this a bug or feature request?
bug
### What is the current behavior?
Cannot complete/void documents
#### Which are the steps to reproduce?
1. create a new sales order, add a line, complete it (alt+i, complete)
=> nothing happens 
(same for any other action from doc status. In swing works)
### What is the expected or desired behavior?
updating doc status should work again

**Comment by metas-lc** [comment]
IT
complete/reactivate/void following documents:
1. sales order - works OK
2. purchase order - works OK 
(cannot reactivate atm because of other bug: https://github.com/metasfresh/metasfresh/issues/4369)
3. purchase inout - works OK
4. purchase invoice - cannot complete NOK (works in swing)
5. sales inout - works OK
6. sales invoice - works OK
7. manufacturing order - cannot complete NOK (works in swing)
8. transportation order - cannot complete NOK (works in swing)
9. empties receive - works OK
10. empties return - works OK
11. distribution order - works OK

**Comment by metas-lc** [comment]
IT
1. transportation order - still cannot complete NOK
go to transportation order window (540020)
alt+i , complete
=> nothing happens
(you shall get an error message that there are no lines to complete. Or if you have lines, shall complete)
2. rest are working fine - OK

**Comment by siemiatj** [comment]
@metas-rc  This doesn't seem to work if I'm clicking with mouse either. 

![screen shot 2018-07-27 at 13 02 45](https://user-images.githubusercontent.com/513460/43317539-79414ac8-919d-11e8-87e5-d84652c0e578.png)

**Comment by metas-lc** [comment]
@siemiatj yes.. it's not working at all. Same problem like we used to have with the other ones

**Comment by siemiatj** [comment]
@teosarca @metas-ts  Does data for transportation order's action widget has to be so weird ? I'm not really sure what to do with what I have. Looks like placeholders :)

![screen shot 2018-07-27 at 16 55 33](https://user-images.githubusercontent.com/513460/43328506-74c8a11e-91be-11e8-8051-94166fd7c3af.png)

vs sales order

![screen shot 2018-07-27 at 16 56 59](https://user-images.githubusercontent.com/513460/43328525-80495b28-91be-11e8-8a99-fd2d25ea5089.png)

**Comment by metas-mk** [comment]
@siemiatj @metas-lc could be an issue in backend. should check that first.

**Comment by metas-ts** [comment]
hi @siemiatj @teosarca @metas-mk 
afair transportation orders might be a "corner case", docaction-wise...
I'm going to take a look this week

**Comment by metas-lc** [comment]
IT
completing transportation order works OK
also checked to be sure usual documents and manufacturing. works OK
