### ISSUE TITLE
POS/HU: topic #1 – included rows

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#189]
Extends #171 .

@teosarca update progress here please. When can we expect API (or just endpoints draft) and how about mock responses?

**Comment by teosarca** [comment]
First of all, the http://w101.metasfresh.com:8081/swagger-ui.html#!/document-view-rest-controller/getViewLayoutUsingGET endpoints provide a new boolean property called "supportTree". If that's true, the rows might have included rows.
Use it if you needed (optimisations ?).

In case the view supports included rows, the documents returned by http://w101.metasfresh.com:8081/swagger-ui.html#!/document-view-rest-controller/getViewDataUsingGET will contain "includedDocuments" property which will be an array of documents.
The property will be set only that particular document (i.e. row) has included documents (rows).

e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/21932174/e3331c90-d9a7-11e6-89a7-b576a75b9d39.png)

**Comment by damianprzygodzki** [comment]
Can we add this flag to the swagger?

**Comment by damianprzygodzki** [comment]
Good morning.

One update.

Now im working on product & packing tree. I am gonna choose icon of row based on HU TYPE property. So:

LU - is pallete
HU - is packing
V - is product

**Comment by teosarca** [comment]
Morning Damian,

Yes, I think it's ok for the start. In future we shall provide some property which advises the frontend about which icon (if any) to pick.
