### ISSUE TITLE
Applying filter params with [alt]+Enter not working in modal windows

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1890]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Trying to apply filter params with `[alt]+Enter` is not working in modal windows, the whole HU Editor is closed.
#### Which are the steps to reproduce?
1. Open picking terminal, window/540345
2. Select a line, call `Pick`, and select a line on the left side of the HU Editor
3. Select a line, and open the HU Editor for selection
4. Select the filter for considering attributes, check the checkbox `Consider attributes`
5. Press `[alt]+Enter `:  the whole HU Editor for picking closed, NOK

Works fine when using mouse.
=> also happens when setting a HU value in the HU Editor when searching for specific HU you want to issue in manufacturing order, window/53009.
### What is the expected or desired behavior?
Filter parameters shall be applied correctly.

**Comment by siemiatj** [comment]
Can you give me a more detailed description how can I repro this behavior in 53009 window ?

**Comment by metas-lc** [comment]
IT
Picking terminal (540345): 
if you use consider attributes filter and press alt+enter then the filter applies OK
but if you use other filter like: default filter, search key, press alt+enter => picking closes NOK
![image](https://user-images.githubusercontent.com/16001666/43584196-6c42d27a-966a-11e8-91f3-8398ac9e370e.png)
(i'll have to create a task for the filter to fit)

Same for manufacturing order (53009): create a new one with salad, complete. Go in grid view, select your line and run issue/receipt. Select a co-product, green button, filter - default - alt+enter. HU editor closes NOK

**Comment by siemiatj** [comment]
With 53009 I don't see any filtering anywhere. Tried clicking everything but to no avail.

![screen shot 2018-08-02 at 19 29 32](https://user-images.githubusercontent.com/513460/43600348-adba88a4-968a-11e8-951e-1b3665179a95.png)

**Comment by metas-dh** [comment]
@siemiatj 
in 53009 you can filter in the HU Editor, for the HUs of the components (you need existing HUs of one of the components available for issueing):

![2018-08-03 10_58_37-](https://user-images.githubusercontent.com/18696715/43634440-5d3e9be0-970c-11e8-9b35-c066599879e6.png)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

apply filter params with `[alt]+Enter`:
* picking terminal, consider attributes filter: OK
* picking terminal, using default filter (e.g. search key, warehouse etc.): OK
* manufacturing, using default filter and search key: OK

(Barcode filter also working fine again, see https://github.com/metasfresh/metasfresh-webui-frontend/pull/1916)
