### ISSUE TITLE
sitemap no longer working on current master

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1891]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
Open sitemap and you will get the error
![image](https://user-images.githubusercontent.com/1244701/43194199-83c8c4a6-900a-11e8-950a-40f782f54ee5.png)

### What is the expected or desired behavior?
shall work

**Comment by metas-ts** [comment]
:cherries:picked to `release`

**Comment by metas-lc** [comment]
open sitemap => no errors, menu is shown OK
