### ISSUE TITLE
closing address editor after entering only the country is not possible

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#1895]
### Is this a bug or feature request?
FR/bug

### What is the current behavior?
when you add a new address and enter the country
you can not leave the address editor unless you click into another field like street, etc.
to the user it appears to be not working

#### Which are the steps to reproduce?
1. add a new address
1. just fill country
1. try to click outside the addresss box 
![image](https://user-images.githubusercontent.com/16079655/43277386-2d63e772-9108-11e8-9051-aee93287b0fd.png)

workaround: use enter instead of mouse

### What is the expected or desired behavior?
should save the address and close the address editor

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested the case above: still the same: NOK

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

tested again, with new build (after frontend build including the fix was successful): 
* setting country, clicking outside the address box: location is saved: OK
* setting country, clicking inside the address box: location is not saved: OK

**Comment by metas-ts** [comment]
:cherries: picked to `release`
https://jenkins.metasfresh.com/job/ops/job/cherry-pick-issue-script/357/
