### ISSUE TITLE
No results when clicking on the looking glass button

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#1898]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* If I go  e.g. to the window Product, substab Parnter Product and I try to create a new entry, I get nothing when I want to select a partner from the list using the looking glass button: 

![image](https://user-images.githubusercontent.com/16001442/43315978-5f83e336-91a0-11e8-9b9d-b0d1ef49ad95.png)

* Same problem when clicking space.

* If I write 3 letters from the partner's name it works.
#### Which are the steps to reproduce?
* Check and see
### What is the expected or desired behavior?
* in this particular case, all the partners from the org and from org 0 shall be eligible and displayed to be chosen when clicking on the looking glass.

**Comment by siemiatj** [comment]
Not much I can do about it. Backend is not returning any results. Once you'll type more text, results are starting to pop up.

![screen shot 2018-07-31 at 16 59 25](https://user-images.githubusercontent.com/513460/43467941-1e0124aa-94e3-11e8-953d-515f4614986e.png)

**Comment by siemiatj** [comment]
Assigning to @teosarca . If we don't want to change this, then I guess we can close this one.

**Comment by teosarca** [comment]
@siemiatj @metas-rc  Agree, we have to do some changes on backend side too.
But, we also have to do changes on frontend side.
Atm, if u just press the "glass" button, nothing happens. There is no API call.
I would suggest to call the typeahead endpoint with `query=`.
That will return an empty array, but that's a thing we can change in backend.

wdyt?

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* cursor over looking glass icon: now the standard arrow icon, not the hand icon: OK
* hand icon still shown where clicking causes a result, e.g. arrow down icon: OK
