### ISSUE TITLE
Container without children shouldn't be rendered.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#19]
Container without children shouldn't be rendered.

**Comment by damianprzygodzki** [comment]
So, elements line won't be rendered if has no element and elementsGroup won't be rendered if has no elements line.

Should i prevent rendering empty columns or is it solving issues?

**Comment by teosarca** [comment]
Nice.

> Should i prevent rendering empty columns or is it solving issue?
Atm i would say no. I am afraid this will "shift" the columns too much in case the one of them becomes invisible because all of the fields become invisible.
