### ISSUE TITLE
Make it possible set date columns in cypress tests

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#1905]
### Is this a bug or feature request?
FR
### What is the current behavior?

![image](https://user-images.githubusercontent.com/1264789/43508835-48273006-9571-11e8-9ac1-62b336b163a8.png)

The URL from the chat is https://docs.cypress.io/api/commands/type.html#Month-Inputs

**Comment by siemiatj** [comment]
Just typing the date in a correct form  `01/01/2018{enter}` fixes this. Read the errors Luke :)

![screen shot 2018-08-01 at 13 38 54](https://user-images.githubusercontent.com/513460/43519574-437df1a6-9590-11e8-835d-ab3405041e38.png)
