### ISSUE TITLE
POS/HU: topic #3 – actions

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#191]
Extends #171 .

Available actions: http://w101.metasfresh.com:8081/swagger-ui.html#!/document-view-rest-controller/getDocumentQuickActionsUsingGET

Important! 1st retunred action is main action with it's own button, rest is under dropdown next to it.

**Comment by teosarca** [comment]
agree

**Comment by teosarca** [comment]
IMPORTANT: in order to work really really nice, pls:
* **always** provide "selectedIds" parameter when calling that endpoint
* each time the user selection is changed, pls query that endpoint again

**Comment by teosarca** [comment]
Another thing, 
in response i've introduced 2 more fields for each action: 
* "disabled" : true | <not present>
* "disabledReason" : string

If the action is flagged as disabled then:
* it shall be grayed out
* not clickable / runnable
* the "disabledReason" shall be displayed somewhere beneath action name (ask the designed). That string will provide valueable informations about why the action cannot be executed.

**Comment by metas-mk** [comment]
perfect. +1

**Comment by damianprzygodzki** [comment]
@teosarca always means even if there is no selected items?

**Comment by teosarca** [comment]
@damianprzygodzki  yes, always.

we can decide on server side if there are any eligible actions.

**Comment by cadavre** [comment]
@teosarca can you provide some examples of "disabledReason"? It's hard to put reason text next to action so we need to plan a place in UI for that and I don't know what can be the lengths. Like 3-4 words max, or 10 words max, or it might be SQL error stacktrace dump (:p)?

**Comment by teosarca** [comment]
@cadavre Nop, the disabled reason is not about an stacktrace or some other internal error.
It's just a user friendly message about why that action is not available.

Background story behind this:
Sometimes, we are deciding which actions to display based on some complex logics which might be not obvious for user.
In that case, instead of letting the user wondering why the fuck the action is not there, we would like to provide an nice reason message.

**Comment by cadavre** [comment]
Still – would be great to have some single example. :)


dnia 1 lutego 2017 o 12:50:38, Teo Sarca (notifications@github.com) napisał:

@cadavre <https://github.com/cadavre> Nop, the disabled reason is not about
an stacktrace or some other internal error.
It's just a user friendly message about why that action is not available.

Background story behind this:
Sometimes, we are deciding which actions to display based on some complex
logics which might be not obvious for user.
In that case, instead of letting the user wondering why the fuck the action
is not there, we would like to provide an nice reason message.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/metasfresh/metasfresh-webui-frontend/issues/191#issuecomment-276638679>,
or mute the thread

**Comment by teosarca** [comment]
e.g.
* no rows selected
* only single row selection allowed
* etc

**Comment by cadavre** [comment]
Thank you!


dnia 1 lutego 2017 o 12:56:07, Teo Sarca (notifications@github.com) napisał:

e.g.

   - no rows selected
   - only single row selection allowed
   - etc

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/metasfresh/metasfresh-webui-frontend/issues/191#issuecomment-276639772>,
or mute the thread

**Comment by damianprzygodzki** [comment]
@teosarca 
> @damianprzygodzki yes, always.

so the call for the empty selection should looks like this?
```
http://w101.metasfresh.com:8081/rest/api/documentView/540196/055d41d1-a97c-4efd-884c-79a17e775fd7/quickActions?selectedIds=
```
I don't think it is good to leave it in that form.
Despite, i am getting now (i think) good response with 3 actions.

**Comment by teosarca** [comment]
@damianprzygodzki 
not specifying the "selectedIds" is same as "selectedIds=".

e.g. http://w101.metasfresh.com:8081/rest/api/documentView/540196/055d41d1-a97c-4efd-884c-79a17e775fd7/quickActions

**Comment by damianprzygodzki** [comment]
You said 
> always provide "selectedIds" parameter when calling that endpoint

That is why i was asking, if we should provide that query parameter even without items.

**Comment by teosarca** [comment]
if there are no selected items, than it's fine.
