### ISSUE TITLE
POS/HU: topic #4 – selection attributes

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#192]
Extends #171 .

Available attributes: http://w101.metasfresh.com:8081/swagger-ui.html#/document-view-attributes-rest-controller

@teosarca selection can be also multiselect. When or how are we providing attributes? Only for single-selection elements?

**Comment by teosarca** [comment]
The attributes are available only for a single line. There is no other way.

I would suggest to display the attributes for the selected line in case the selection contains only one line.
If the selection contains more lines, don't display the attributes at all.
Other ideas? ( @metas-mk  )

**Comment by teosarca** [comment]
NOTE: the http://w101.metasfresh.com:8081/swagger-ui.html#!/document-view-rest-controller/getViewLayoutUsingGET endpoints provide a new boolean property called "supportAttributes".

If that's true, the frontend shall use it to make room for attributes widget.
And also, ONLY in case it's true the document view attributes related REST endpoints are available.

**Comment by damianprzygodzki** [comment]
Good morning.

We have case, that i see for the moment is unreachable.

When you are in Handling Unit (.../540189), with selected some of the item (1000388) and than you are using action "Create material receipt". The process is passing by with no error, but only with status OK.

```
error:false
pinstanceId:1218482
summary:"OK"
```

How to process farther this case? Should i refresh whole tree to get "disabled" rows?

**Comment by damianprzygodzki** [comment]
And the 2nd issue. I've noticed that you @teosarca are providing ids of some item like `Fooo#123#123`. The `#` in http is a fragment identifier. It is special char for identifying part of the document. So i see that all endpoints that rely on selected item ids it will be not working properly. So it think it is major issue.

```
At this point, the fragment identifier:
- is not part of the URI
```
And a little quote from w3.org

**Comment by teosarca** [comment]
i think u can encode them (i.e. %23).

**Comment by damianprzygodzki** [comment]
```
error
:
"Bad Request"
exception
:
"org.springframework.web.method.annotation.MethodArgumentTypeMismatchException"
message
:
"Failed to convert value of type [java.lang.String] to required type [int]; nested exception is java.lang.NumberFormatException: For input string: "M_HU_Storage#1000392#2005573""
path
:
"/rest/api/documentView/540189/99a9a629-fe82-4ae1-b30b-0912718b5f37/M_HU_Storage%231000392%232005573/layout"
```
