### ISSUE TITLE
[alt]+q for opening batch entry not working as before

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1920]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you use [alt]+q for opening batch entry in order, you cannot continue with creating orderlines anymore.
#### Which are the steps to reproduce?
1. Start creating a new sales order, set the bpartner
2. use  [alt]+q: the batch entry opens, OK
3. start writing sth: 
=> the entry in bpartner field is changed: NOK
4. Create another sales order, set the bpartner
5. Open the batch entry by clicking the resp. field
6. start writing:
=> product field in batch entry, OK

**Comment by siemiatj** [comment]
So the shortcut is working, but focus is in the wrong spot.

**Comment by metas-dh** [comment]
sorry, i believed having the focus in the right spot goes hand in hand with opening the batch entry with shortcut,  maybe i should have named the issue differently then.

> First of all I need to set the price system to be able to add anything.

No, you don't, if a pricelist is set for the bpartner then that should be set automatically when you select the bpartner. 

The focus was still in bpartner field for me, after setting the bpartner and clicking [alt]+q this morning:

http://recordit.co/1Uoir4hTqR

(But i noticed if you just mouse over the batch entry fields, the focus is set to the first field.)

**Comment by siemiatj** [comment]
hmm I wonder if my changes made it to wherever you're testing. Both locally and on w101 this seems to be working fine. I think this PR fixed this https://github.com/metasfresh/metasfresh-webui-frontend/pull/1917 . Maybe it got stuck again somewhere and was never rolled out properly ?

**Comment by metas-dh** [comment]
worked fine in this week's e2e, so i guess the fix is now included. closing this task.
