### ISSUE TITLE
Make window tabs cypress friendly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1926]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
When generating window included tabs, use the "internalName" from layout as widget/element/div IDs.
Or something similar, just to be able to identify those tabs in cypress by their "internalName".

Backend task: https://github.com/metasfresh/metasfresh/issues/4491
The concept was described in https://github.com/metasfresh/metasfresh-webui-api/issues/1023

**Comment by teosarca** [comment]
@metas-ts  feel free to add more to the concept.

**Comment by metas-ts** [comment]
I think over time the API might return `InternalName`s for a range of different things..like (Doc)Actions, Fields, MenuItems etc
therefore it would be nice to come up with a schema that makes sure we don't need to find a different  spot for the respective InternalName string each time.

Also, the InternalName is unique among all tabs of the current window. But might not be unique among all process-actions, menu-tree-items, fields, tabs etc on the respective page.

therefor i suggest to embedd not just the internal name, but someting like `tab_<internal-name>`.

**Comment by metas-dh** [comment]
Results of IT1
tested in dev120

1. created cypress test to open tab "Location" in window bpartner, using the internal name, resp. ID: tab_Window-123-222
2. ran test on dev120: tab "Location" was opened correctly: OK
