### ISSUE TITLE
Hint for shortcut [alt]+u not displayed anymore when hovering over the resp. button

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1931]
### Is this a bug or feature request?
Bug
### What is the current behavior?
 There is no hint anymore for the [alt]+u shortcut, when the mouse hovers over the action button (still shown when overing over e.g. the notification bell or the button for toggling the list of actions available): 
http://recordit.co/7wbuMT5rvp
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Hint for shortcut [alt]+u shall be displayed.

**Comment by siemiatj** [comment]
Looking at the code I don't think there ever was such a tooltip. I've checked till the beginning of 2018 and can't see anything related to that. I'll add that anyways.
