### ISSUE TITLE
Frontend shall ALWAYS use server's time zone

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1933]
### Is this a bug or feature request?
FR
backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/1064

### What is the current behavior?
Frontend is using browser's timezone

### What is the expected or desired behavior?
Frontend shall use server's time zone.

Server's timezone is provided by [/rest/api/userSession](http://w101.metasfresh.com:8080/swagger-ui.html#!/user-session-rest-controller/getAllUsingGET) endpoint.
e.g.
```
{
....
"timeZone": "+02:00",
...
}
```

**Comment by teosarca** [comment]
@siemiatj  playing around i got OOM

![image](https://user-images.githubusercontent.com/1244701/47299275-d60ae500-d5e7-11e8-8e03-e6cb8d43d1b6.png)

**Comment by teosarca** [comment]
update: i think it was some buggy chrome plugin i've used to change my timezone.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

pls see IT for https://github.com/metasfresh/metasfresh-webui-api/issues/1064#issuecomment-432213324: NOK

**Comment by metas-rc** [comment]
I found the same problem in Date filters.




![image](https://user-images.githubusercontent.com/16001442/48062363-778a5d00-e1ca-11e8-9d76-cec03d9d8648.png)


![image](https://user-images.githubusercontent.com/16001442/48062438-bcae8f00-e1ca-11e8-98f2-d28d143193b8.png)


![image](https://user-images.githubusercontent.com/16001442/48062465-d2bc4f80-e1ca-11e8-8f13-e9ce41a4f956.png)

![image](https://user-images.githubusercontent.com/16001442/48062499-f41d3b80-e1ca-11e8-90aa-3e5073d8f06e.png)

![image](https://user-images.githubusercontent.com/16001442/48062568-1a42db80-e1cb-11e8-863f-cf51b12cd66a.png)


![image](https://user-images.githubusercontent.com/16001442/48062610-334b8c80-e1cb-11e8-93c3-a8700b1c776f.png)


![image](https://user-images.githubusercontent.com/16001442/48062725-80c7f980-e1cb-11e8-8639-46a1c230cea3.png)

**Comment by metas-rc** [comment]
Case 2) 

![image](https://user-images.githubusercontent.com/16001442/48062844-e0260980-e1cb-11e8-8104-d6e1bbb62486.png)


![image](https://user-images.githubusercontent.com/16001442/48062879-0055c880-e1cc-11e8-923a-d0873bb60434.png)

* Note the value and valueTo have different time zones. Probably from the daylight saving: 
![image](https://user-images.githubusercontent.com/16001442/48062914-20858780-e1cc-11e8-99e5-c6a5d36cf6fc.png)

![image](https://user-images.githubusercontent.com/16001442/48062987-588cca80-e1cc-11e8-9445-0a51b0a61261.png)

**Comment by siemiatj** [comment]
Can you record a video or give info what's happening, what data did you send and what did you get from the server ? The initial problem was that dates had different TZ locally and on the server. Server is +1 and I switched to Romanian TZ (+2). Before my changes time would change here to be an hour earlier. Now it's not happening anymore. So if it's not fixed I need to have a test case, expected outcome and so on : 

http://recordit.co/hjmJAIW3m2

**Comment by metas-rc** [comment]
Hi. I recorded a video with what happens on my side. The problem seems to be that the frotend first send the date with timezone +00:00 and only afterwards it's changed to +01:00.

http://recordit.co/KdzMzSXyop

**Comment by siemiatj** [comment]
Might be related to #2202

**Comment by siemiatj** [comment]
Related to #2219
