### ISSUE TITLE
Cannot run processes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1934]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Running processes with parameters is no longer possible.

#### Which are the steps to reproduce?
1. go to Billing candidates, e.g. http://localhost:3000/window/540092
2. select some of them (e.g. first 2 rows) and then call `generate invoices` process

![image](https://user-images.githubusercontent.com/1244701/44649836-b2fbf480-a9ed-11e8-9166-3d4d52e40598.png)
![image](https://user-images.githubusercontent.com/1244701/44649841-b68f7b80-a9ed-11e8-9f34-4d2f21e77ac9.png)

### What is the expected or desired behavior?
🌈 :unicorn:

**Comment by teosarca** [comment]
@siemiatj  after running the process i get following warning in console. Do you think it might be some possible issue? Wondering if we could get rid of it....


![image](https://user-images.githubusercontent.com/1244701/44659987-ce2b2c00-aa0e-11e8-84fc-99a3fa1a6dca.png)

**Comment by metas-ts** [comment]
:cherries: picked to `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in release

1. SetUp Wizard running fine again: OK
2. Transform action in HU Editor, e.g. in Material Receipt Cands, window/540196:
nothing happening, window with overlay freezes, nothing in console: have to use refresh to get back to material receipt cands: NOK
http://recordit.co/SXyzQtmxFU
3. Labels in HU Editor, in Material Receipt Cands, window/540196, e.g.  IFCO: same problem, window with overlay freezes: NOK

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* invoice or shipment creation working fine, also when e.g. setting different params: OK
* transform action workng fine: OK
* labels are created correctly: OK
* Receive action in manufacturing order working fine: OK
* all other tested processes worked fine: OK
