### ISSUE TITLE
Open views from process execution result

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#194]
After running a process, if the process result returned by API has "viewWindowId" and "viewId" fields set we shall open that view.

For the start i would suggest to open it in the same browser tab.

Use case:
* open Wareneingangsdisposition window - http://w101.metasfresh.com:8090/window/540196
* select a line with a regular product (i.e. not packing material product)
* call "Receive HUs" process
* that process will return an viewId/viewWindowId.
* frontend shall open that view

![image](https://cloud.githubusercontent.com/assets/1244701/21931690/780b1fb4-d9a5-11e6-8a10-b85a1eabfbfa.png)

Required for https://github.com/metasfresh/metasfresh-webui-frontend/issues/171

**Comment by metas-ts** [comment]
@metas-mk @metas-dh  did we already test this one? I.e. can it remain closed or shall be reopen it until it was tested?

**Comment by metas-lc** [comment]
IT OK https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23194.md
