### ISSUE TITLE
HU Editor for selecting HUs in Picking Terminal shows HU that is already picked

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#1941]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you open the HU Editor for selecting a HU for picking, the HU which is picked already is also displayed there (but cannot be picked anymore). 
http://recordit.co/MNN5LXJhrn
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
A HU that was already picked shall not be displayed in the HU Editor for selection anymore.

**Comment by siemiatj** [comment]
I'm not that familiar with HU Editor. I see the selected item in data returned from the server. What should happen here ? @teosarca @metas-dh 

http://recordit.co/OhszS7GvsJ

**Comment by metas-dh** [comment]
the selected (= picked) HU shall not be displayed anymore when you open the HU Editor for selection after it was picked, since it's now in the picking slot and shall not be available for picking anymore
@teosarca do u think it's a backend issue?

**Comment by metas-dh** [comment]
thx, created https://github.com/metasfresh/metasfresh/issues/4571. closing this one.
