### ISSUE TITLE
Filter for attributes in picking terminal is not set on Y altough should be

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh-webui-frontend#1944]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Atm the filter for attribute in picking terminal is Y by default, but in the window is shown as N.
![image](https://user-images.githubusercontent.com/15378036/44781306-aeba0d80-ab8c-11e8-9ee7-b01f1e1c924c.png)
![image](https://user-images.githubusercontent.com/15378036/44781351-ce513600-ab8c-11e8-8a1c-6417fe9d1b40.png)

#### Which are the steps to reproduce?
Open and see
### What is the expected or desired behavior?
Should be set on Y

**Comment by metas-dh** [comment]
pls check https://github.com/metasfresh/metasfresh/issues/4498 again when ITing this task.

**Comment by metas-dh** [comment]
e2e from 10.09: Default filter IsActive was not set in bpartner Window/123, but in businesspartner B2C window/540354: check again when the fixes from this task are all integrated!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. Have HUs with and without attribute: Bio in HU available for picking
2. Create sales order, for the same product, with and without attribute: Bio
3. Open Picking Terminal and select the line where attribute: Bio was set for the product
4. Open HU Editor for selection:
* check filter: attribute filter is set: Y by default: OK
* check HUs: all HUs are displayed, not just the the ones with the resp. attribute set: NOK, if it is set as default should be applied as well
* apply filter for attribute: white page, console:

```
index.js:9 Uncaught TypeError: o is not a function
    at index.js:9
    at t.<anonymous> (daterangepicker.js:12)
    at _r (react-dom.production.min.js:13)
    at commitLifeCycles (react-dom.production.min.js:13)
    at t (react-dom.production.min.js:13)
    at k (react-dom.production.min.js:13)
    at w (react-dom.production.min.js:13)
    at batchedUpdates (react-dom.production.min.js:13)
    at ut (react-dom.production.min.js:13)
    at $t (react-dom.production.min.js:13)
(anonymous) @ index.js:9
(anonymous) @ daterangepicker.js:12
_r @ react-dom.production.min.js:13
commitLifeCycles @ react-dom.production.min.js:13
t @ react-dom.production.min.js:13
k @ react-dom.production.min.js:13
w @ react-dom.production.min.js:13
batchedUpdates @ react-dom.production.min.js:13
ut @ react-dom.production.min.js:13
$t @ react-dom.production.min.js:13
```

http://recordit.co/c0B1WpkHSo

**Comment by metas-dh** [comment]
fyi: also get white page and that output in console when i use the date filter in sales order window

**Comment by siemiatj** [comment]
Just for the record - the default filter is only applied after clicking `Apply`, not initially on load.

**Comment by teosarca** [comment]
found some more issues,

material cockpit: https://w101.metasfresh.com:8443/window/540376, click on date filter which is set by default. Then click on `Clear filter`. You get following in console:
```
Uncaught TypeError: i is not a function
    at t.value [as handleClear] (index.js:9)
    at onClick (index.js:9)
    at Object.P (react-dom.production.min.js:13)
    at Object.invokeGuardedCallback (react-dom.production.min.js:13)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:13)
    at K (react-dom.production.min.js:13)
    at ee (react-dom.production.min.js:13)
    at ne (react-dom.production.min.js:13)
    at Array.forEach (<anonymous>)
    at Z (react-dom.production.min.js:13)
value @ index.js:9
onClick @ index.js:9
P @ react-dom.production.min.js:13
invokeGuardedCallback @ react-dom.production.min.js:13
invokeGuardedCallbackAndCatchFirstError @ react-dom.production.min.js:13
K @ react-dom.production.min.js:13
ee @ react-dom.production.min.js:13
ne @ react-dom.production.min.js:13
Z @ react-dom.production.min.js:13
se @ react-dom.production.min.js:13
Vt @ react-dom.production.min.js:13
Gt @ react-dom.production.min.js:13
batchedUpdates @ react-dom.production.min.js:13
ut @ react-dom.production.min.js:13
$t @ react-dom.production.min.js:13
```

![image](https://user-images.githubusercontent.com/1244701/45423756-eb155f80-b69c-11e8-86a9-0ceb35ceefe6.png)

**Comment by teosarca** [comment]
found another one, in my customized database. 
(Pls ping me if u cannot fix it without test case)

![image](https://user-images.githubusercontent.com/1244701/45423834-30399180-b69d-11e8-9d4b-67109d96116a.png)

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

1. checked different filters/ default filters, did not get any of the issues described above anymore (warnings / errors in console, white page): OK

2.  > Just for the record - the default filter is only applied after clicking `Apply`, not initially on load.

=> i'm wondering why? if it's only applied after clicking `Apply`, then why is it a Default filter in the first place? 
=> if this is the wanted behaviour, why aren't all Default filters working like this? e.g. the Default filter for considering attributes in picking terminal, for HU selection, needs to be applied by the user, but the IsActive filter for bpartners in B2C bpartner or the date filter in material cockpit, are applied already on load when you open the windows.

@teosarca @metas-mk  wdyt?

**Comment by metas-dh** [comment]
Update:
in latest e2e, the user defined filters in printing queue did not work, when trying to apply them nothing happens and you get this in console:

<details>

```
daterangepicker.js:12 Uncaught TypeError: Cannot read property 'isActive' of null
    at value (daterangepicker.js:12)
    at value (index.js:9)
    at Object.I (react-dom.production.min.js:13)
    at Object.invokeGuardedCallback (react-dom.production.min.js:13)
    at Object.invokeGuardedCallbackAndCatchFirstError (react-dom.production.min.js:13)
    at K (react-dom.production.min.js:13)
    at ee (react-dom.production.min.js:13)
    at ne (react-dom.production.min.js:13)
    at Array.forEach (<anonymous>)
    at $ (react-dom.production.min.js:13)

```
</details>

**Comment by siemiatj** [comment]
> Results of IT2
> tested in mf15
> 
> 1. checked different filters/ default filters, did not get any of the issues described above anymore (warnings / errors in console, white page): OK
> 2. > Just for the record - the default filter is only applied after clicking `Apply`, not initially on load.
> 
> => i'm wondering why? if it's only applied after clicking `Apply`, then why is it a Default filter in the first place?

No idea tbh. According to Teo, default filters should be treated more like initial values in most cases, as they're not actualy filters but just defaultValues for filters...

> => if this is the wanted behaviour, why aren't all Default filters working like this? e.g. the Default filter for considering attributes in picking terminal, for HU selection, needs to be applied by the user, but the IsActive filter for bpartners in B2C bpartner or the date filter in material cockpit, are applied already on load when you open the windows.

... and in some cases they're already applied and sent via the api as active.

**Comment by siemiatj** [comment]
> Update:
> in latest e2e, the user defined filters in printing queue did not work, when trying to apply them nothing happens and you get this in console:

Reproduced. I was assuming all filters had to have parameters, but apparently that's not the case.

**Comment by metas-rc** [comment]
Talked with Kuba and fund out this was solved in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1972
Closing
