### ISSUE TITLE
"About" action in webui

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1945]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to see creator/ updater infos for records in webui.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Create an Action in Action Menu "? About". After starting the action a modal overlay is shown with the following infos:

- created, created by, updated, updateby of main record
- created, created by, updated, updateby of selected sub record (if selected)
- if more than 1 subrecord is selected only show result of main record

![image](https://user-images.githubusercontent.com/13365687/44852605-f790c580-ac63-11e8-9ac2-b7aa43c69f86.png)

**Comment by teosarca** [comment]
update: Backend API is ready.

You can use following endpoints to fetch the info:

* main record: [GET /rest/api/window/{windowId}/{documentId}/changeLog](http://w101.metasfresh.com:8080/swagger-ui.html#!/window-rest-controller/getDocumentChangeLogUsingGET)

* included record: [GET /rest/api/window/{windowId}/{documentId}/{tabId}/{rowId}/changeLog](http://w101.metasfresh.com:8080/swagger-ui.html#!/window-rest-controller/getDocumentChangeLogUsingGET_1)

**Comment by siemiatj** [comment]
@teosarca we need 5 translations to be added :

 * window.About
* created on
* created by
* modified on
* modified by

**Comment by metas-ts** [comment]
> @teosarca we need 5 translations to be added :

=> https://github.com/metasfresh/metasfresh-webui-frontend/issues/1945#ref-pullrequest-400256234

**Comment by siemiatj** [comment]
We need to decide what should be displayed in case multiple rows are selected.

**Comment by metas-ts** [comment]
> We need to decide what should be displayed in case multiple rows are selected.

@siemiatj @metas-mk we might also disable the "about" item in the menu, similar to disabled actions

**Comment by metas-dh** [comment]
see IT dokus in me03 tasks: OK
