### ISSUE TITLE
Filter Attribute Label not set properly

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1948]
### Is this a bug or feature request?
Bugfix
### What is the current behavior?
Currently, the Filter Label in Button is not set properly.
#### Which are the steps to reproduce?
Open, try and see. /window/123
### What is the expected or desired behavior?
Shall be set properly.

![image](https://user-images.githubusercontent.com/13365687/44904246-ff597400-ad0e-11e8-91fc-19a49378c549.png)

**Comment by metas-ts** [comment]
:cherries: picked commit 45fca75825781a4a4e333655320f85a6ba03a940 to `release`

**Comment by metas-dh** [comment]
Results from e2e
tested in release

1. filter for name: "test" in bpartner window: OK
![2018-09-03 17_15_43-notificationsform](https://user-images.githubusercontent.com/18696715/44994058-2c22bb00-af9d-11e8-8f83-38153c0fd611.png)

2. filter for order bpartner "test" in sales order window: NOK i think
![2018-09-03 17_16_21-notificationsform](https://user-images.githubusercontent.com/18696715/44994062-32b13280-af9d-11e8-984d-1bd9a86ae69f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Filter Attribute Label set properly:

1. bpartner window: set Filter e.g. 
* Manufacturer: Y: filter label: Manufacturer: **OK**
* add Customer: Y: filter label: Kunde, Manufacturer: **OK**
* add Name: test: filter label: test, Kunde, Manufacturer: **OK**
* filter results matching: **OK**

2. shipment window: set Filter e.g.
* shipment to: Test Kunde, document status: Completed, org: metasfresh AG: filter label: Test Kunde 1_G0001, Fertiggestellt, ...: OK; mouse over filter label: all params are displayed: **OK**
* filter results matching: **OK**

3. Default filter, e.g. "Aktiv" set in bpartner B2C window (main window): 
* filter label shows "Aktiv": **OK**
* filter results matching: **OK**

4. Default filter, e.g. attribute filter, in modal overlay (=> picking terminal, HU selection window):
* filter label shows "Attribute berücksichtigen", but not like it is set (although it is set: **NOK**

![2018-09-12 10_57_33-notificationsform](https://user-images.githubusercontent.com/18696715/45414162-10917180-b67b-11e8-9d93-9299c3402f81.png)


![2018-09-12 10_59_22-notificationsform](https://user-images.githubusercontent.com/18696715/45414168-15562580-b67b-11e8-9e9a-ffe21e8bc25d.png)

5. Date filter, e.g. in sales order window: label does not show the params set, not working either: : **NOK**, alsosee IT https://github.com/metasfresh/metasfresh-webui-frontend/issues/1944#issuecomment-420554282

6. Filter label does not show when a parameter is set to N: e.g. set Customer=Y in bpartner window, and then set it to N (=> checkbox is not filled anymore, only framed): Filter label is empty:

![2018-09-12 11_04_17-notificationsform](https://user-images.githubusercontent.com/18696715/45414478-c230a280-b67b-11e8-8868-35626bc339dc.png)

(filter results are matching though)

=> was not part of this task, new issue: #1962

**Comment by siemiatj** [comment]
what is `Attribute berücksichtigen` responsible for and how's this option called in English ?

**Comment by siemiatj** [comment]
Ok, I hope the data comes filtered from the backend and it's not a special case for default values we're talking here... Checking

**Comment by siemiatj** [comment]
Ok so this is intentional. Mark wanted to show filters with defaultValue as active only if user explicitly clicked the `Apply` button. Unless this is some special case.

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

4. Default filter, e.g. attribute filter, in modal overlay (=> picking terminal, HU selection window):

> Ok so this is intentional. Mark wanted to show filters with defaultValue as active only if user explicitly clicked the `Apply` button. Unless this is some special case.

* commented in https://github.com/metasfresh/metasfresh-webui-frontend/issues/1944#issuecomment-421304629
* when filter is applied, then the filter label is correct: **OK**

5. Date filter, e.g. in sales order window: label shows the params as set: **OK** (also working fine, see IT2 in #1944)

=> closing this one since the filter labels when applied were all displayed correctly in my test.
