### ISSUE TITLE
On password reset, show the error message

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1957]
### What is the current behavior?
Atm when you try setting a new PW, in Forgot PW feature, and it does not match the criteria, e.g. is too short, then you just get "Verbindungsproblem" displayed, but no info about the PW being too short.

#### Which are the steps to reproduce?
Try and see.

### What is the expected or desired behavior?
Show the error message instead of `Verbindungsproblem`:

![image](https://user-images.githubusercontent.com/1244701/45252490-da44b100-b35f-11e8-8a55-95fdb0c26537.png)

**Comment by siemiatj** [comment]
Sholud we even show this Verbindungsproblem, or only the message ?

**Comment by metas-dh** [comment]
Results of IT1
tested in release, e2e

correct error msg shown on password reset:
* PW too short: correct error msg, OK
* 2nd PW entry not matching the 1st one: correct error msg, OK
* "Verbindungsproblem" not shown anymore: OK

=> some msgs were shown in de_DE, some in en_US: #1958
