### ISSUE TITLE
Support active indication for filters without parameters

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1972]
### Is this a bug or feature request?

Bug

### What is the current behavior?

Filters without parameters are not properly indicated as active.

#### Which are the steps to reproduce?

Find any filter without parameters and click Apply.

### What is the expected or desired behavior?

Filter button should show active state and filter name/caption.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

filters without parameters working fine: e.g. user queries in printing queue:
* filter works fine when applied, results are correct: OK
* filter is labeled correctly (e.g. Abrechnung_offen_normal, as it is selectable): OK

**Comment by metas-ts** [comment]
:cherries: picked https://github.com/metasfresh/metasfresh-webui-frontend/issues/1972 to `release`
