### ISSUE TITLE
Process with parameters cannot be started

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#198]
Case:
* http://w101.metasfresh.com:8090/window/500221
* try to run Auswahl Fakturieren => nothing happens, process panel is not displayed

e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/22012923/115ae64e-dc9f-11e6-9cd6-41987d4a535c.png)

**Comment by teosarca** [comment]
it might be that the bug was introduced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/115

**Comment by damianprzygodzki** [comment]
Please, update app. 

Issue before handling process response. Process modal is opening. Additional fixes applied to MasterWidgets inside process modal.

**Comment by damianprzygodzki** [comment]
What's more. Ive found that after starting process for `Auswahl liefern` im getting error "No selection" is it on my side?

**Comment by teosarca** [comment]
as talked on skype, no, i don't think that's a frontend issue.
