### ISSUE TITLE
Height of date fields is off

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1983]
### Is this a bug or feature request?
Bug

### What is the current behavior?
Date fields with datepicker are too tall.

#### Which are the steps to reproduce?
Check any view with date fields.

### What is the expected or desired behavior?
Fileds should have the correct height.

**Comment by siemiatj** [comment]
This was caused by changes in Bootstrap 4.1.3 - https://github.com/twbs/bootstrap/releases/tag/v4.1.3

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

height of date fields with datepicker is correct again: OK (compared with a pic i took on 26.09., when it was off)
