### ISSUE TITLE
Adjustments to tooltip widget

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#1987]
### Is this a bug or feature request?
Feature
### What is the current behavior?
Tooltip widget's font size is too small. Also in case of table fields widget's icon could be visible even if there was no value defined for the field.

#### Which are the steps to reproduce?
Check `window/143`

### What is the expected or desired behavior?
Font should be bigger, icon should not be visible if there's nothing to show.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* Font should be bigger in tooltip widget: OK
* the icon is not visible if there's no value defined for the field: OK
