### ISSUE TITLE
Hourglass Overlay for pending Posts

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1989]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently. when filtering in windows with a large amount of date, it sometimes takes a while for the result. The post is pending. After a short while the user believes that the filtering "apply" did not work and tries again.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Add an Hourglass overlay feature for posts that are pending longer than for example 3secs. This shall show the user that something is happening,

**Comment by metas-dh** [comment]
Results of IT1
tested in sp80 e2e

* Spinner pops up when filtering takes a while (>2 sec.): OK
* Spinner also pops up diretly when filtering in windows with **lots** of data (OLCands): afais that's OK

**Comment by metas-ts** [comment]
:cherries: picked  https://github.com/metasfresh/metasfresh-webui-frontend/issues/1989 into branch `5.76_hf1`
