### ISSUE TITLE
Fastlane Login without Dashboard

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#199]
Fastlane Login without Dashboard
Possibility to show an empty dashboard (only the gray background and header area) after login.
Additionally show a larger Logo of metasfresh centered in the gray area.
This solution will be switchable in backend. and uses until the d3js implementations are finished for live usage.
Here is the metasfresh API Task:
https://github.com/metasfresh/metasfresh-webui/issues/60

**Comment by cadavre** [comment]
Please don't report low-priority, new feature tasks for milestone while in the middle of milestone!

**Comment by metas-mk** [comment]
Task was added shortly after yesterday's meeting and needed for webUI launch to avoid half-baked D3JS and un performant iframe with kibana. please check what the effort would be first.

**Comment by cadavre** [comment]
Roger, with story behind it make much more sense.

@teosarca how would you provide flag to inform frontend about which dashboard shall User see? Response from /session or dedicated endpoint?

**Comment by teosarca** [comment]
IMHO i would provide "GET /rest/api/dashboard/enabled" endpoint which returns "true" or "false".
wdyt?

**Comment by metas-rc** [comment]
Results of IT 1: 
Tested on http://w101.metasfresh.com:8090
Whenlogging into webui, one does not  directly see the darboard options, but only the metasfresh logo. For seeing the dashboard, the Home button must be pressed.
