### ISSUE TITLE
QR code support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1990]
### Is this a bug or feature request?
FR
required for https://github.com/metasfresh/metasfresh/issues/4577

### What is the current behavior?
QR code is not supported

#### Which are the steps to reproduce?
e.g.
* open Manufacturing Orders view: https://w101.metasfresh.com:8443/window/53009
* click on Issue/Receipt (barcode) action
* try to scan an QR code => it shall be recognized. NOTE: i don't care if that order# does exist.

### What is the expected or desired behavior?
The barcode reading functionality shall seamless support regular 1D barcodes (EAN etc) and QR codes too.

**Comment by teosarca** [comment]
Test case to be validated:
* call `Run QR Code Action` process from menu
* scan a QR code 

If the QR code is not a valid action you will get an error but that's not relevant for now.
We just want to validate that
* a QR code can be scanned with that process
* that process can be called and works no matter from where is called (e.g. open an sales order and that call that process from menu)

![image](https://user-images.githubusercontent.com/1244701/46717613-39ecef80-cc71-11e8-84f9-8c0236475f13.png)

![image](https://user-images.githubusercontent.com/1244701/46717635-496c3880-cc71-11e8-9fa9-1d43ec41078a.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

=> tested with the QR code created in IT for #1999 

1. Use Issue/Receipt (barcode) action in manufacturing order, try to scan an QR code => it shall be recognized: OK (see pic below)

2. Run QR Code Action process from menu, scan a QR code:  OK (see pic below)

3. hat process can be called and works no matter from where is called (e.g. open an sales order and then call that process from menu): OK


=> QR code value set after scanning: 
![2018-10-15 11_22_34-metasfresh](https://user-images.githubusercontent.com/18696715/46942551-df3b0580-d06d-11e8-8ebf-8714baeefbb0.png)
