### ISSUE TITLE
Ugly double border when editing in Date Fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1992]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When editing in a Date Field that is mandatory, a double border appears.

![image](https://user-images.githubusercontent.com/13365687/46483552-3a603300-c7f8-11e8-842a-a3da2b233c74.png)

#### Which are the steps to reproduce?
Open, try and see in Sales Order for example.
### What is the expected or desired behavior?
Shall not have that inner border.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

no double border when editing in Date Fields: OK

![2018-10-15 10_18_36-metasfresh](https://user-images.githubusercontent.com/18696715/46938360-dcd3ae00-d063-11e8-8a06-634637a734eb.png)
