### ISSUE TITLE
Date Icon moved few pixels to left for mandatory

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1993]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, the icons of Date Fields have a 2px jump left/ right depending on if the mandatory border is shown (blue, red).

![image](https://user-images.githubusercontent.com/13365687/46483959-18b37b80-c7f9-11e8-8ea2-b2ca51a20b3c.png)

#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Keep the Icons in the same alignment, no matter if Field has a mandatory border or now.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Date icons have the same alignment, no matter if Field has a mandatory border or now: OK

![2018-10-15 14_27_19-metasfresh](https://user-images.githubusercontent.com/18696715/46951095-3dc0ad80-d087-11e8-8f6d-b56dbc6f8329.png)
