### ISSUE TITLE
Cypress Test: Manufacturing Order Test fails

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1995]
### Is this a bug or feature request?
Test
### What is the current behavior?
Currently, the Manufacturing Order Test fails because of 

> CypressError: Timed out retrying: Expected to find element: '#quickAction_ADP_540788', but never found it.

The Quick  Action `ADP_540788` is not found.

#### Which are the steps to reproduce?
Open, try and see.

### What is the expected or desired behavior?
Fix the Test.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

ran cypress test on mf15: worked fine, quickaction for Barcode was called correctly: OK
