### ISSUE TITLE
Cypress: Product set Documentnote Test fails

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#1997]
### What is the current behavior?
Currently, the Product Set Documentnote Test fails because of

> CypressError: Timed out retrying: Expected to find element: '.form-field-DocumentNote', but never found it.

#### Which are the steps to reproduce?
Start the Cypress Test and see.

### What is the expected or desired behavior?
Fix the Test.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

test works fine, document note is set for the resp. product, no errors: OK
