### ISSUE TITLE
Open view process action shall support profileId (frontend)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1998]
### Is this a bug or feature request?
required for https://github.com/metasfresh/metasfresh/issues/4577

**Comment by siemiatj** [comment]
Looks good to me

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

tested in metasfresh/metasfresh#4577: opening the Reviewer view when scanning QR Code: same view as Picker, but with different profile: OK
