### ISSUE TITLE
Process execution result action: render QR code

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#1999]
### Is this a bug or feature request?
FR
required for https://github.com/metasfresh/metasfresh/issues/4577

#### Which are the steps to reproduce?
* open the new picking terminal: https://w101.metasfresh.com:8443/window/540485
* select a line to pick
* call the Pick action
* the modal view with "what to pick" is displayed
* make sure all lines are picked (i.e. select all and call Pick action)
* after that you shall see the `4Eyes Review` action => call it and check the process response.

![image](https://user-images.githubusercontent.com/1244701/46717056-f4c7be00-cc6e-11e8-92c3-d90ad04238e0.png)
![image](https://user-images.githubusercontent.com/1244701/46717088-25a7f300-cc6f-11e8-8247-cd8ee60ede37.png)
![image](https://user-images.githubusercontent.com/1244701/46717144-67d13480-cc6f-11e8-9a84-f7c6e0256a2a.png)

### What is the expected or desired behavior?
If the process response action is `displayQRCode` then the frontend shall render a QR code in the middle of the screen.
That QR code shall be big enough that somebody else with some other tablet could scan it (see https://github.com/metasfresh/metasfresh-webui-frontend/issues/1990 ).

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

 * a QR code is rendered by the frontend, in the middle of the screen, when process response action is `displayQRCode`: OK

* QR code shall be big enough that somebody else with some other tablet could scan it: OK, see pic

![2018-10-15 10_58_32-metasfresh](https://user-images.githubusercontent.com/18696715/46940693-9d0fc500-d069-11e8-87b9-8524c0abace7.png)
