### ISSUE TITLE
Include .htaccess to src/

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#20]
RewriteEngine On  
  # If an existing asset or directory is requested go to it as it is
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -f [OR]
  RewriteCond %{DOCUMENT_ROOT}%{REQUEST_URI} -d
  RewriteRule ^ - [L]

  # If the requested resource doesn't exist, use index.html
  RewriteRule ^ /index.html

**Comment by damianprzygodzki** [comment]
It already exists.
https://github.com/metasfresh/metasfresh-webui-frontend/blob/dev/.htaccess

**Comment by teosarca** [comment]
thanks
