### ISSUE TITLE
Modal view shall query the quick actions initially

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2000]
### Is this a bug or feature request?
Bug
required for https://github.com/metasfresh/metasfresh/issues/4577

#### Which are the steps to reproduce?
You can apply the same steps like here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1999

i.e.
* open the new picking terminal: https://w101.metasfresh.com:8443/window/540485
* select a line to pick
* call the Pick action
* the modal view with "what to pick" is displayed

Remark that no quick Actions were queried/displayed.
![image](https://user-images.githubusercontent.com/1244701/46717404-7cfa9300-cc70-11e8-81a3-aa05a922445c.png)

### What is the expected or desired behavior?
* quick actions shall be queried and displayed when the view modal opens
* quick actions shall be queried and displayed on any row selection change. IMPORTANT: they have to be queried even if the row selection is empty!

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

quick actions shall be queried in new picking terminal:

* when first opening modal, with existing row selection: OK

![2018-10-15 10_28_54-metasfresh](https://user-images.githubusercontent.com/18696715/46939168-e78f4280-d065-11e8-804d-e72d46019667.png)

* when first opening modal, with row selection empty: OK

![2018-10-15 10_30_46-metasfresh](https://user-images.githubusercontent.com/18696715/46939196-f83fb880-d065-11e8-83d0-869fd8690008.png)

* when change in row selection: OK

![2018-10-15 10_31_07-metasfresh](https://user-images.githubusercontent.com/18696715/46939221-08f02e80-d066-11e8-8ef6-9ea46f950170.png)
