### ISSUE TITLE
Allow decimal comma in Qty Fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2005]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, only a decimal point is allowed to be used in Qty fields.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Also allow the usage of decimal comma.

Example in Sales Order Batch entry:
![image](https://user-images.githubusercontent.com/13365687/46951253-bc1d4f80-d087-11e8-9c48-c5bbb8210d18.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* decimal comma in Qty Fields is allowed as well: OK
* decimal comma is displayed as decimal point (=> inspect): is that OK?

![2018-10-19 14_05_49-metasfresh](https://user-images.githubusercontent.com/18696715/47223539-ce65f900-d3b9-11e8-884a-5dc5944a15e8.png)

**Comment by teosarca** [comment]
@metas-dh IMHO it's OK. Btw, was your order line created with the correct qty?

**Comment by metas-dh** [comment]
thx; good thing you asked, bc i tested that a bit more:

* when i had no Packing Item and the UOM was Kg, then the order line had the correct qty, as set (decimal): OK
* when i had no Packing Item and the UOM was PCE, then the qty in ther order line was rounded, either up or down: is that OK?
* when i had a Packing Item (both UOM Kg & PCE), then the qty in ther order line was rounded, but always down (=> 1 TU if i set 1,8 or 1,9): is that OK?
* also, the qty in the order line is always displayed with decimal point, no matter if i used decimal point or comma in Qty Entry

**Comment by teosarca** [comment]
@metas-dh 
I think they are rounded because of the UOM precision or something like that.
But those are (if they are) metasfresh issues and not frontend.
