### ISSUE TITLE
Views: Automatically remove view rows if GET /byIds it's not returning the row(s) frontend asked for

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2009]
### Is this a bug or feature request?
FR

required for https://github.com/metasfresh/metasfresh/issues/4577

### What is the current behavior?
In some cases, the backend is sending websocket events about which view rows where changed.
On it's turn, the frontend is calling [GET /rest/api/documentView/{windowId}/{viewId}/byIds](http://w101.metasfresh.com:8080/swagger-ui.html#!/view-rest-controller/getByIdsUsingGET) to fetch then.
The result is an array of all rows which were found for given IDs.
If, for some reason, some of the rows are missing they won't be returned.

In that case, at the moment, the frontend is simply ignore that and keeps those missing rows in current view page.

#### Which are the steps to reproduce?
One of the easiest ways to do it is to simulate it using http://w101.metasfresh.com:8080/swagger-ui.html#/debug-rest-controller tools.

There you shall have `POST /rest/api/debug/view/{viewId}/deleteRows` which is deleting rows from a view. After it's deleting them, it is sending a websocket notification.

e.g.
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' 'http://localhost:8080/rest/api/debug/view/123-B/deleteRows?ids=2156426'
```

### What is the expected or desired behavior?
If some rows were not returned by `GET /byIds` then the frontend shall remove them from current view page.

**Comment by siemiatj** [comment]
I think we need a flag on the websocket message to differentiate between events that updated rows and removed them. Otherwise I won't know if the row should be removed or merged with existing data.

![screen shot 2018-10-18 at 00 53 59](https://user-images.githubusercontent.com/513460/47120868-a61eb300-d270-11e8-83ee-e026e223405a.png)

**Comment by teosarca** [comment]
quick tested. works OK.
