### ISSUE TITLE
Modal view's title is not set when opened from process

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2012]
### Is this a bug or feature request?
bug

required for https://github.com/metasfresh/metasfresh/issues/4577

#### Which are the steps to reproduce?
1. open a new Sales Orders window and remember it's ID
For example, i've opened https://w101.metasfresh.com:8443/window/143 and i got forwarded to https://w101.metasfresh.com:8443/window/143?viewId=143-C&page=1. So my viewId is `143-C`

2. From menu, run `Run QR Code Action`
3. In the barcode field write `open-view#<your viewId>` and press enter. In my example, i've used `open-view#143-C`
4. The sales order view is opened as modal but remark that the title is `Modal` => NOK
It shall be the open provided in the layout.
![image](https://user-images.githubusercontent.com/1244701/47090446-9df05480-d22b-11e8-9152-c64509ac1170.png)

### What is the expected or desired behavior?
see above.

**Comment by siemiatj** [comment]
Looks like this might get fixed with #2036 🤞

**Comment by metas-dh** [comment]
Results of IT1
tested in release

modal opens with the correct name, as provided in layout, e.g. Sales Order, Product or Price System: OK
