### ISSUE TITLE
Views: refresh `quickActions` after `GET /byIds`

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2014]
### Is this a bug or feature request?
FR
related to
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/2009
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/2000

required for https://github.com/metasfresh/metasfresh/issues/4577

### What is the current behavior?
* when some rows are changed, backend sends refresh requests via websockets
* frontend is re-quering those rows by calling `GET /byIds` endpoint

* but the quickActions are not refreshed. They should because in some cases we would have different quick actions just because the rows were changed.

### What is the expected or desired behavior?
always refresh quickActions after refreshing the rows.

**Comment by teosarca** [comment]
### Note to IT:
can be tested in new Picking Terminal.
As Reviewer, confirm all Qtys, so all lines will be Approved.
Automatically you shall see the "Process" quick actions

Before this task, you shall change the row selection (e.g. select nothing) in order to force the frontend to re-query the quick actions.

**Comment by teosarca** [comment]
update: as discussed with @siemiatj , we have to fix the case when the removed row was selected. In that case the frontend was refreshing the quickActions using `?selectedIds=<already removed row id>`

**Comment by teosarca** [comment]
Quick tested:

1. Deleted a row which is not selected => OK


2. Selected one row and then i've deleted it
* quickActions (without any selectedIds was called) => OK
* quickActions was called twice => NOK (@siemiatj  can u pls check it if is a quick fix?)

3. Selected 3 rows and then i've deleted one of them
* quickActions was called with selectedIds=<all 3 rows> => NOK, 
![image](https://user-images.githubusercontent.com/1244701/47401952-f8b60e80-d74b-11e8-85c7-7b3719c5dd7e.png)

**Comment by siemiatj** [comment]
I'm pretty sure this double call is not a quick fix as it'll be related to the whole mumbo jumbo mess in the widget/table click handlers. Without a specification this thing won't be fixable in a proper way anywhere in the near future.

**Comment by teosarca** [comment]
@siemiatj  thanks for explaining.
Pls fix only 3. for now.

**Comment by teosarca** [comment]
quickly tested, works nice.
