### ISSUE TITLE
Indicator bar not visible

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2016]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The indicator bar no longer shows saving state properly.
#### Which are the steps to reproduce?
Load any business partner/sales order, or modify them.
### What is the expected or desired behavior?
Indicator bar should properly display the state and outcome of the operation.

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* load data when opening a window, e.g. bpartner: indicator bar displayed correctly: OK
* modify / create new data: indicator bar displayed correctly: OK
