### ISSUE TITLE
View quickActions timing issue

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2029]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
Open http://localhost:3000/window/540345

Remark:
* first line is selected
* 2 quickActions calls were issued. First without any selectedIds and second with the right selectedIds
* instead of updating the "QuickActions" widget with the result of the second quickActions call, the first one was used.
![image](https://user-images.githubusercontent.com/1244701/47565561-8c94ff80-d931-11e8-85bd-712b82ee6d1d.png)

### What is the expected or desired behavior?
QuickActions widget shall be updated with latest quickActions call result.

**Comment by metas-ts** [comment]
seems to have soem issues, details will follow

**Comment by metas-dh** [comment]
Results of IT1
tested in release

quick actions were updated & displayed correctly in latest e2e:
* when opening a new window, e.g. material receipt candidates, 1st window: OK
* when selecting differet rows, e.g. in material receipt candidates, where default actions are different: OK
* after a process, e.g. after material receipt / processing manufaturing: OK
