### ISSUE TITLE
Window ViewID does not match expected one error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#203]
**High Prio**
Window ViewID does not match expected one error
how to reproduce: Happens when you switch from one window to another via navigation and grid view + double click.
![image](https://cloud.githubusercontent.com/assets/13365687/22058284/b3617bc8-dd68-11e6-9e95-2f4e4ad42fb5.png)

**Comment by damianprzygodzki** [comment]
* open a completed Auftrag
* references => pick shipment schedules
* shipment schedules window opens
* double click on one of them
* that particular shipment schedule opens
* hit browser back => expect to see the shipment schedules grid view
* hit browser back => expect to see that Auftrag
NOTE: while doing this, along the way you will get several errors

**Comment by damianprzygodzki** [comment]
* navigation open. select "aufträge"
* double click on a row to open detail view --> error
* navigationopen. select "Vorgänge"
* double click on a row to open detail view --> error

**Comment by metas-dh** [comment]
Results of IT1:

tested on w101:
* switched from one window to another via navigation (e.g. sales order - shipment schedule, and invoice candidates - invoice) and used grid view + double click, as well as back button: no more error: "Window ViewID does not match expected one": OK
