### ISSUE TITLE
Can not complete Order

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#204]
![image](https://cloud.githubusercontent.com/assets/16079655/22059964/42126ea8-dd6f-11e6-84e0-415f49d405af.png)

**Comment by damianprzygodzki** [comment]
It will be better to provide more info about issue. At least what is the endpoint, that request you are showing.

I am suspecting that you are achieve this after clicking on document status dropdown, and selecting Complete, right?

**Comment by metas-mk** [comment]
@damianprzygodzki yes
![image](https://cloud.githubusercontent.com/assets/13365687/22060384/cbc57450-dd70-11e6-87bc-e12559ce36e2.png)
after clicking "fertigstellen" the error happens.

**Comment by damianprzygodzki** [comment]
Try now, please.

**Comment by metas-mk** [comment]
works now on dev-server. thanks.
will check on integration server after new rollout here too.

**Comment by metas-mk** [comment]
confirmed on integration server. works now.

**Comment by teosarca** [comment]
fixed by https://github.com/metasfresh/metasfresh-webui-frontend/commit/bd05e199dd26b700154d3efb744e943356f9f54b
