### ISSUE TITLE
Run QR code action: sometimes ESC does not work

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2047]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* call `Run QR Code Action` process
* write some wrong barcode and press enter (e.g. "dsdfawre")
* you get an error => OK
* try pressing ESC
=> nothing happens => NOK
In console you get:
> Handler defined for key sequence "ESCAPE" is not a function.
value @ ShortcutProvider.js:177

### What is the expected or desired behavior?
Shall work. ESC shall close the process overlay.

See picture below.
If you click outside of that marked region, pls close the process overlay too.
![image](https://user-images.githubusercontent.com/1244701/47983913-847d5280-e0dd-11e8-8f32-cae67ead373b.png)

### Note to IT
make sure tablet works.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 (normal PC & tablet mode)

pressing `Esc` to close the process overlay:
* did not work with 1st `Esc` , had to click on the page first and then `Esc`  closed the overlay 
(=> noticed that the `Esc`  did not work when the search menu i used was still displayed in the background, when i clicked on the page first the search menu disappeared and then the `Esc`  worked fine)
* nothing in console: OK

**Comment by metas-dh** [comment]
checked again in release  (normal PC & tablet mode):
=> using `Esc`  at first try now closed the QR Barcode overlay: OK (additional search menu dropdown is not displayed anymore, not sure this was related)
