### ISSUE TITLE
View: clicking outside of table does not unselect the current selected lines

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2048]
### Is this a bug or feature request?
Bug

I think it was introduced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/2018

#### Which are the steps to reproduce?
* open a regular view, e.g. sales order
* select some rows
* click somewhere outside of table (e.g. see picture below)
=> rows are not unselected => NOK
![image](https://user-images.githubusercontent.com/1244701/47984578-af68a600-e0df-11e8-8957-3ec54d9dad62.png)

### What is the expected or desired behavior?
Rows shall get unselected

### Note to IT
* make sure https://github.com/metasfresh/metasfresh-webui-frontend/issues/2018 is still working
* tablet shall work

**Comment by siemiatj** [comment]
Looks like some parts of the view still don't unselect the rows

![2018-11-23 14_48_54-metasfresh](https://user-images.githubusercontent.com/513460/48947080-387d3b00-ef30-11e8-924e-0273e54d2c3f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in release:

deselecting by clicking in some areas outside of the table does not work, see pic above: shall be fixed in #2075, OK for this week's release.
