### ISSUE TITLE
quick actions: not refreshed on selection changed in tablet/mobile mode

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2049]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* make sure u are in tablet/mobile mode
* open any view
* click on rows to select/deselect them
* remark: the /quickActions endpoint is not called with current selection => NOK

### What is the expected or desired behavior?
shall work

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

quick actions are correctly refreshed on selection changed in tablet/mobile mode: 
* e.g. material receipt schedule, different quick actions for schedule for CU only / packing item / no selection: selecting different schedules => quick actions are refreshed correctly: OK

* deselection did not really work (not just in tablet/mobile mode, but in general):  
=> material receipt schedule: clicking at the top of the window does not deselect the row, you have to reload the page (and even then the row previously selected still is marked as selected, but the quick action was updated)
http://recordit.co/s0kDCoB6cY

not sure this is the same problem as in https://github.com/metasfresh/metasfresh-webui-frontend/issues/2058? @teosarca wdyt?

**Comment by metas-dh** [comment]
problem of deselection: #2048
