### ISSUE TITLE
Batch entry Dropdown for Handling Unit Missing in Workflow

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#205]
Batch entry Dropdown for Handling Unit Missing in Workflow
* type product, dropdown appears, select, enter -> jumps directly to Quantity but should show dropdown for handling unit if no default handling unit is set.
![image](https://cloud.githubusercontent.com/assets/13365687/22060810/a42207ae-dd72-11e6-97e3-2db2329b1966.png)

**Comment by Dunkat** [comment]
Type and select product, see dropdown request response

![image](https://cloud.githubusercontent.com/assets/21196151/22199597/fcb756a2-e15b-11e6-9c37-a06b62de417e.png)

There is only 'No Handling Unit' to select.

**Comment by metas-mk** [comment]
@Dunkat thx for the info. iI checked in rows if there are any HU_PI Items there and assumed they are missing. will talk to @teosarca about that.
![image](https://cloud.githubusercontent.com/assets/13365687/22204039/399108d4-e170-11e6-80d5-1fd4c22e89e5.png)

**Comment by teosarca** [comment]
good morning @Dunkat 

that's happening because the dropdown is queried BEFORE the selected product is communicated to backend.

Taking your screenshot, this is what happens:
![image](https://cloud.githubusercontent.com/assets/1244701/22204389/6a9596f2-e17a-11e6-976b-dda64a194e9f.png)

**Comment by cadavre** [comment]
Now you can use Products lookup as regular. Going to Amount with [Tab] due to fact that [Enter] is now reserved for HU selection.
