### ISSUE TITLE
Views: refresh `quickActions` after `GET /byIds` shall consider current selected rows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2050]
### Is this a bug or feature request?
Bug
It was already fixed on https://github.com/metasfresh/metasfresh-webui-frontend/issues/2014, but it seems it's back.

#### Which are the steps to reproduce?
* tab1: create a draft order 
* tab2: in another tab, open sales order view (http://localhost:3000/window/143)
* tab2: make sure your draft order is selected in that view
* tab1: go back to first tab and complete the draft order
* tab2: check the Network tab, and remark:
** /byIds was called with that sales order id => OK
** /quickActions was called, BUT without any selectedIds => NOK; the selectedIds shall be provided

### What is the expected or desired behavior?
when /quickActions are called, they shall be called with latest selectedIds.

**Comment by siemiatj** [comment]
It's a bit different case than #2014 so it's not a regression. Nonetheless it's a bug.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* retested the case above: /quickActions were called with latest selectedIds: OK
