### ISSUE TITLE
Deleting Batch entry product with "X" only deletes Product not Handling unit

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#206]
Deleting Batch entry product with "X" only deletes Product not Handling unit
![image](https://cloud.githubusercontent.com/assets/13365687/22061003/57e16460-dd73-11e6-8481-eeede1b55481.png)

**Comment by cadavre** [comment]
To be done together with #205

**Comment by cadavre** [comment]
Fixed. Right now we also save few API calls with merging multiple PATCH operations into one.
