### ISSUE TITLE
Cannot untick filter checkbox

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2061]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* open business partner window
* open Default filters
* tick IsCustomer => the checkbox is ticked => OK
* tick again isCustomer => the checkbox remains ticked => NOK
* click on `(clear)` => the checkbox remains ticked => NOK

### What is the expected or desired behavior?
shall work

**Comment by teosarca** [comment]
@siemiatj  pls review/improve

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

(Default) Filter with checkbox (e.g. in bpartner window, Businesspartner B2C):
* tick filter: checkbox: checkbox is ticked: OK 
* untick filter checkbox: checkbox is not ticked anymore, just framed (=> `N`): OK
* click `(clear)`: checkbox is not ticked / framed anymore: OK

(filter results not always correct when playing with different params: => https://github.com/metasfresh/metasfresh-webui-frontend/issues/2040)
