### ISSUE TITLE
"x" not working anymore in order batch entry

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2063]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The `x` in order batch entry does not work anymore, nothing happens when clicking it.
![2018-11-07 13_35_21-metasfresh](https://user-images.githubusercontent.com/18696715/48132013-5e4ce380-e292-11e8-922b-dda77cd5752f.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Shall work.

**Comment by teosarca** [comment]
works for me, can u pls try it again?

![image](https://user-images.githubusercontent.com/1244701/48181148-087a4900-e32f-11e8-9039-9d0c62489976.png)
![image](https://user-images.githubusercontent.com/1244701/48181162-1af48280-e32f-11e8-92bf-a6041b7a0372.png)

field was cleared, value was PATCHED (i.e. M_Product_ID and M_HU_PI_Item_Product_ID were set to null)
![image](https://user-images.githubusercontent.com/1244701/48181220-4b3c2100-e32f-11e8-8d32-40f565aeb320.png)

**Comment by metas-dh** [comment]
checked: working fine again. closing this issue.
