### ISSUE TITLE
Dropdown in bpartner field in order sometimes remains displayed after selecting bpartner

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2067]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Dropdown in bpartner field in order remains displayed after the bpartner is selected.
#### Which are the steps to reproduce?
1. Create a new order
2. In bpartner field, start writing e.g. "Test" => dropdown opens with matching bpartners
3. Select a bpartner with mouse click: bpartner is set, but the dropdown remains displayed; you have to click again for it to disappear:

http://recordit.co/YJEc7JB0vs

=> works fine when you use `Enter`, see vid
### What is the expected or desired behavior?
Dropdown shall disappear after selecting the bpartner.

**Comment by siemiatj** [comment]
This seems to be the cause to #2069

**Comment by metas-dh** [comment]
Results of IT1
tested in release:

* dropdown disappears after selecting bpartner, no matter if with mouse click or using `Enter`: OK
