### ISSUE TITLE
Number Inserting in Order Quick Input 

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#2069]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* If I want to create an orderline using the Quick Input functionality, nothing happens after I insert the product name and number and press enter. The line is not created
* Workaround: it works after I reset cache (ctrl + shift + r) but then it happens again at the next order.
#### Which are the steps to reproduce?
* Create an order
* go to quick input
* Select a product
* select a qty
* Press enter
* => NOK: The  order line is not created.

* I get this in the console 

![image](https://user-images.githubusercontent.com/16001442/48772673-c3123000-eccd-11e8-9c66-a8dcf51d8a78.png)

### What is the expected or desired behavior?
* The order line shall be created when I press enter

**Comment by metas-rc** [comment]
![image](https://user-images.githubusercontent.com/16001442/48772934-914d9900-ecce-11e8-8535-275bbf30ec6a.png)


![image](https://user-images.githubusercontent.com/16001442/48772945-9b6f9780-ecce-11e8-9b27-d939f55a9a9f.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in release:

* orderline is created correctly, with product & qty, after pressing `Enter`: OK
* no error in console: OK
