### ISSUE TITLE
Search result not identical with Swing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#207]
Search result not identical with Swing
Example Product search for "frisee" shall also show products called "frisée"
![image](https://cloud.githubusercontent.com/assets/13365687/22061432/31bafc72-dd75-11e6-9785-81ad3e7b61bb.png)

**Comment by damianprzygodzki** [comment]
Is it really frontend issue? I believe it is a case to be done by the API side. It is regular expression issue, not on our side.

**Comment by teosarca** [comment]
Nop, it's a backend issue.
