### ISSUE TITLE
Number changing in order line grid view

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#2070]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Order lines in grid view
* Go to the qty field, double click it
* Up and Down arrows appear to increase and decrease the number
* Click on the arros => the number is changed
* Click somewhere else
* => NOK: Ignored by frotend.
* refresh => the number is the same it was at the begining
* When pressing enter, it works
* When using the arrows in single mode and clicking somewhere else it also works.

http://recordit.co/9KSBARoVqc
#### Which are the steps to reproduce?
* As above
### What is the expected or desired behavior?
* the number should be really changed when I click somewhere else

**Comment by siemiatj** [comment]
Related to #2066

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

repeated the testcases above:
*changing qty / qty TU in orderline using the arrows also works fine: patched after `Tab`, clicking somewhere else, and after `Enter:` OK
* both in single and grid view: OK

**Comment by teosarca** [comment]
note to IT: pressing enter in quick input, qty field was doing nothing. That was fixed by last PR.

**Comment by metas-dh** [comment]
Results of IT2
tested in release

* pressing enter in quick input, qty field: working fine, the change is patched: OK
* tests from IT1 still working fine: OK
