### ISSUE TITLE
Failing cypress tests

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2073]
### Is this a bug or feature request?
Bug

Related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/1981

### What is the current behavior?
Tests utilising the `writeIntoCompositeLookupField` fail.

#### Which are the steps to reproduce?
Run `sales_order_spec.js` test suite.

### What is the expected or desired behavior?
Tests should pass.

**Comment by metas-ts** [comment]
note to IT: you can see it in action in `purchase_order_spec.js`

**Comment by siemiatj** [comment]
@metas-ts I think we can close this one, right ?
