### ISSUE TITLE
Text Fields "smiling" shall not

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2078]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Text Fields are smiling again (see pixels up left and right on text fields). Also Date Fields (pls also check if others are involved).
![image](https://user-images.githubusercontent.com/13365687/49007654-461f0480-f16c-11e8-9d50-b2ab17cf534e.png)
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Shall not have those pixels shown on text fields.

**Comment by siemiatj** [comment]
Are you sure it wasn't like that before ? I don't remember ever removing padding for the fields, and in the styles we have them deliberately set. There were only tasks related to aligning them correctly.

So this is how you want this to look ?

![screen shot 2018-11-26 at 16 51 53](https://user-images.githubusercontent.com/513460/49025342-b42ef000-f19b-11e8-810c-6241e1bf9829.png)

**Comment by siemiatj** [comment]
This was fixed in single entry changes #2222
