### ISSUE TITLE
Show tab description as tool tip

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#2082]
### Is this a bug or feature request?
FR
Analog to https://github.com/metasfresh/metasfresh-webui-frontend/issues/1953

### What is the current behavior?

![image](https://user-images.githubusercontent.com/1264789/49065102-4d521b00-f21d-11e8-9f9b-736455d901c2.png)

#### Which are the steps to reproduce?

* Hover over a tab whose `AD_Tab` does have a description in our application dictionary

### What is the expected or desired behavior?

The description should be shown

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15


* if there is a  tab description, this is shown as tool tip: OK
* if there is no tab description, the tab's caption is shown: OK
* description / caption shown acc. to menu language: OK
