### ISSUE TITLE
Individual Logo shall not have hashsequence added to name

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2086]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it happens that the Logo metasfresh_logo_green_thumb.png used in metasfresh header and empty dashbord has a hash sequence added to the name when built. This needs a manual interaction after build to add an individual logo with the needed hash sequence.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Don't add the hash sequence to the logo.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15 / release (for comparison)

1. metasfresh Logo in Dashboard / Header: 
* mf15: metasfresh_logo_green_thumb.png: OK
* release (task not included yet): metasfresh_logo_green_thumb.e26dea1a43fd27e4a60d60309ff5adb1.png

2. Individual Logo (after setting it in SetUP Wizard):
* have to check the name
* logo set in SetUP Wizard looks ok in reports: OK
* logo set correctly in client: OK
