### ISSUE TITLE
Lookup and Dropdown: Empty list entry for non mandatory

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2097]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, in Lookup widgets, there is not empty option for non mandatory fields.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Provide an empty option for mandatory: false fields.

![image](https://user-images.githubusercontent.com/13365687/49650521-b4957980-fa2c-11e8-951f-97f2775274a6.png)

**Comment by siemiatj** [comment]
Related to #1253

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* empty option for mandatory: false fields (e.g. AD_User_ID, Bill_User_ID in sales order): OK
* no empty option for mandatory: true fields (e.g. AD_Client_ID, C_DocTypeTarget_ID in sales order): OK
