### ISSUE TITLE
Implement a way to browse existing documents

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#21]
Suggestion:
* current URL looks like this: http://.../window/143
* we shall change it to http://.../window/143/documentId

wdyt?

**Comment by damianprzygodzki** [comment]
It is already done. 

If you request `/window/143` then is created new document.
If you request `/window/143/documentId` then presented is existing document.

**Comment by damianprzygodzki** [comment]
Should we change it?

**Comment by cadavre** [comment]
I think it's about appending documentId into URL as soon as ID is received. Am I right @teosarca ?

**Comment by teosarca** [comment]
@cadavre yes, that would be nice if the effort is not too big.

NOTE: initially when i've created this task i wasn't aware that we already have this feature at all.

**Comment by cadavre** [comment]
Done.
