### ISSUE TITLE
Cannot create a new BPartner

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#210]
![image](https://cloud.githubusercontent.com/assets/1244701/22098648/2c2fabfc-de30-11e6-9a0b-c35bf6c76df9.png)

**Comment by teosarca** [comment]
NOTE: the error happens when u are trying to set the bpartner code (at the top)

**Comment by teosarca** [comment]
Might be related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/209

**Comment by damianprzygodzki** [comment]
Not related. 1st note, it looks like you have really old instance of app (this crashed breadcrumb); 2nd note, it is fixed in #203
