### ISSUE TITLE
Changing qty in batch entry using arrows: increase / decrease only in decimal value

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2101]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you change the qty in batch entry, in order, the change is only done in decimal value: e.g. when qty: 2 is set and you use the up arrow => qty: 2.1 ; shall be 3.
#### Which are the steps to reproduce?
Try and see.

**Comment by siemiatj** [comment]
But this was a requested change, so I'm puzzled.
