### ISSUE TITLE
Handle grid view on websocket notifications

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#211]
We introduced following websocket endpoint: /view/<viewId>.
e.g. /view/c10edf64-88e7-4ce3-bde5-2ffd901ed0c1

All change notifications related to a given viewId will be sent to that endpoint.

TODOs:
* when opening a view, connect to it's websocket endpoint too
* when closing a view, disconnect from that endpoint
* handle received events 

Current view change event has following format:
```
{
	"viewId": "the view id",
	"windowId": the_window_id,
	"fullyChanged": true|false|missing
}

```

where:
* fullyChanged - if set and it's true, the frontend has to fully reload the data 

Future:
In future we will introduce more options to be able able to partially stale a data etc

**Comment by cadavre** [comment]
If `fullyChanged`=true shall we generate new viewId or just get data for existing one?

Could you please add Swagger documentation for this?

**Comment by teosarca** [comment]
> If fullyChanged=true shall we generate new viewId or just get data for existing one?

just get data for existing one (IMPORTANT)

**Comment by cadavre** [comment]
I'm thinking... While we reload data for existing viewId we can keep same page opened and same ordering – it's all fine. But I guess that if user have selection it will be gone (i.e. due to changed elements on page he's looking at). Maybe we should provide notification with info "There are new/updated documents in this view. Click here to reload." and reload on user-click instead of immediately. I'm little bit concerned about making user feel lost on "magic" reloads. As an example take Twitter.

**Comment by cadavre** [comment]
`ws://{hostname}/view/{viewId}` is the endpoint to connect WebSockets to.

**Comment by teosarca** [comment]
NOTE: as discussed on skype, for now is OK just to automatically reload the data (using the save viewId!).

about user selection, what u can do is:
* before refreshing, memorize the selected documentIds
* actual refresh
* after refreshing: check the documentIds and select as much as possible.


About the notification: yes, that would be another use case. For now, we just need this one.

**Comment by cadavre** [comment]
It's not good idea for selection... or... you will ensure that user won't have his current view rows different. Imagine situation when user selects first and last row. Notification comes and view is reloaded with 3 new rows added. Then selection for previously selected last row won't be possible (it is not visible on grid anymore).

**Comment by teosarca** [comment]
i would suggest to keep what you can.
