### ISSUE TITLE
Overlays open in narrow window on latest Chrome

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2112]
### Is this a bug or feature request?

Bug

### What is the current behavior?

![2018-12-14 12_35_50-metasfresh](https://user-images.githubusercontent.com/513460/50008123-74e20b00-ffb3-11e8-9dc2-3741d7c96ff5.png)

#### Which are the steps to reproduce?

Add new location in BPartner window.

### What is the expected or desired behavior?

Modal should take the same width as before.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

=> overlays open with normal size again in latest Chrome: OK
