### ISSUE TITLE
Barcode scanner looks bad in filters

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2117]
### Is this a bug or feature request?

Bug

### What is the current behavior?

![screen shot 2018-12-17 at 17 18 57](https://user-images.githubusercontent.com/513460/50100057-cdb5db80-021f-11e9-99fe-981a47c20015.png)

#### Which are the steps to reproduce?
Try barcode scanner within a filter menu.

![screen shot 2018-12-17 at 17 17 34](https://user-images.githubusercontent.com/513460/50100063-d3132600-021f-11e9-860f-e839405ae3ff.png)

### What is the expected or desired behavior?

![screen shot 2018-12-17 at 17 13 57](https://user-images.githubusercontent.com/513460/50099887-71eb5280-021f-11e9-8bbe-281290af6109.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Barcode scanner looks as before, see expectation: OK
