### ISSUE TITLE
Quick actions dropdown covered by pagination in modals

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2122]
### Is this a bug or feature request?

Bug

### What is the current behavior?

![screen shot 2018-12-18 at 19 50 54](https://user-images.githubusercontent.com/513460/50175974-73d81300-02fe-11e9-9f8b-a0d9d76626ea.png)

#### Which are the steps to reproduce?

Open modal with pagination and a long list of actions (or decrease the viewport by resizing browser window).

### What is the expected or desired behavior?

Quick actions dropdown shouldn't be covered by anything.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Quick actions dropdown isn't covered by anything: OK

![2019-01-10 16_44_38-metasfresh](https://user-images.githubusercontent.com/18696715/50979672-48a8a400-14f7-11e9-849b-e39596cbd0c0.png)
