### ISSUE TITLE
Do not focus fields "in background" when in Expanded view

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#213]
Expanded Batch entry <TAB> usage behavior
- Reproduce: Order Window. <crtl> + space for batch entry. Trying to get out of Batch entry pressing <TAB> multiple times. At some point, focus comes into URL Field. further <TAB> gets back into application and then Fields from non-overlay are focussed, through the Overlay.

![image](https://cloud.githubusercontent.com/assets/13365687/22174416/35dd808e-dfde-11e6-923d-8fbcbe3dc973.png)

**Comment by metas-mk** [comment]
Info: Just checked in window Lieferdisposition (500221) too. Same weird behavior when being in overlay and able to get "under" the overlay with <TAB>

**Comment by cadavre** [comment]
Elements under overlay will always be focusable because they are part of DOM tree. What we can do is explicitly check it or close overlay when something outside of overlay is being focused.

**Comment by cadavre** [comment]
Renamed to "Do not focus fields "in background" when in Expanded view".

We cannot focus background elements (like BPartner etc.) while in Expanded mode.

ONLY visible elements shall get possibility to be focused IN GENERAL.
