### ISSUE TITLE
Display value description when hovering over field

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#2133]
### Is this a bug or feature request?
FR, follow-up to https://github.com/metasfresh/metasfresh/issues/4798

### What is the current behavior?

As of issue https://github.com/metasfresh/metasfresh/issues/4798 we now can have a description property in the field value JSON.
The frontend should display that description when hovering over the respective value in the UI.
Currently that is not yet implemented
Example:
![image](https://user-images.githubusercontent.com/1264789/50709076-f1be4d00-1066-11e9-9aae-6455c02a864c.png)

### What is the expected or desired behavior?

The description (*if* that property is present in the value JSON) should be shown when hovering over the field value; similar to the way we already show the help text when hovering over the field name.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

value description is displayed when hovering over field: OK

**Comment by metas-dh** [comment]
Results of IT2
tested in dev229

value description is displayed when hovering over field:

* when creating a new flatrate term condition: description of the term condition is displayed, OK
* when hovering over field after condition is completed: OK (for both flatrate condition "Rückvergütung" and the spec. type of latrate condition, e.g. "Gestaffelte Rückvergütung")
