### ISSUE TITLE
string field is reset in mid-typing

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#2134]
### Is this a bug or feature request?
Bug
### What is the current behavior?

If you check out the viedo at https://dashboard.cypress.io/#/projects/5yp4q1/runs/33/specs during 0:10
Cypress is trying to enter "Vendor <some-timestamp>" into the Firmenname (companyname) field, but after "Vendo", the field is reset.

Afair I once saw, that this is related to an empty-valued patch that was send to the API fpr some reason, which subsequently resets the field via a websocket event.

Note: here i attached the video I was talking about:
[purchase_create_vendor_spec.js.zip](https://github.com/metasfresh/metasfresh-webui-frontend/files/2732476/purchase_create_vendor_spec.js.zip)

#### Which are the steps to reproduce?

It happens rarely when the typing is done manually, but frequently in cypress tests specs

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

string field is not reset in mid-typing:

* in cypress test purchase create vendor: OK
* when adding e.g. a new price system manually and typing fast: OK

=> will check again next e2e, where it sometimes happens when creating new data

**Comment by metas-dh** [comment]
worked fine in this week's e2e as well, closing.
