### ISSUE TITLE
Global shortcuts are not working when focused in inputs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#214]
Fast User Experience when recording Sales Order
This Issue shall describe the expectations of data recordings in Order window (without Mouse).
- New Order. Window opens. Automatically focussed on first Field.
- After recording the first Field and BPartner Name (others are filled automatically), the user shall be able to fastest press <ctrl> space to open the Batch entry.
- After recording in Batch Entry, the user shall be able to fastest collapse the Batch entry with <ctrl> space.
OR
- Directly fastest possibility to press <ctrl> + i to allow completion.

**Comment by cadavre** [comment]
Batch entry is right now under ctrl+space, is this fine?

What is missing here I believe is that global shortcut listener is not listening for keys while is Lookup. This shall be fixed!

Also afair we can now put focus in first input thanks to #185 .

**Comment by cadavre** [comment]
Renamed to "Global shortcuts are not working when focused in inputs" because it's a "UX-bug" that global shortcuts are disable when in inputs. 

While in Lookup or Date or Text – we still need to use shortcuts like ctrl+1 or ctrl+space.

**Comment by cadavre** [comment]
Pending for action from library's author in https://github.com/avocode/react-shortcuts/issues/10 .

If no response we will workaround.

**Comment by teosarca** [comment]
why guys, what's the status of this task?
i see commits but @damianprzygodzki  closed it.

**Comment by teosarca** [comment]
re-opening until we clarify the status...

**Comment by damianprzygodzki** [comment]
We decided to close this, because it was fixed and merged, and we are only waiting here to clarify the mergin path to the main library -> #307

**Comment by teosarca** [comment]
Ok, so basically i can move this task to testing, right?

**Comment by damianprzygodzki** [comment]
yes

**Comment by metas-mk** [comment]
Tested. Works as required.
