### ISSUE TITLE
Model view: row no longer refreshed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2145]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
* open a sales order, e.g. https://w101.metasfresh.com:8443/window/143/1001301
* select first order line and call "Create purchase orders" action
![image](https://user-images.githubusercontent.com/1244701/51172639-5629a980-18bc-11e9-919b-517c3f2e5517.png)

* edit the qty on some line, then press enter or focus out.
![image](https://user-images.githubusercontent.com/1244701/51172698-7c4f4980-18bc-11e9-8bd2-54ed6b6e2904.png)

* an websocket notification is sent to refresh the first row, the frontend is querying it but it does not update it on screen
![image](https://user-images.githubusercontent.com/1244701/51172817-bcaec780-18bc-11e9-9983-09df3d6ffbb8.png)

### What is the expected or desired behavior?
the queried row shall be updated on screen

**Comment by metas-ts** [comment]
@siemiatj i believe i meanwhile fixed that problem on w101..let me do a rollout..

**Comment by metas-ts** [comment]
@siemiatj works now, as checked with https://w101.metasfresh.com:8443/window/143/1001301

**Comment by siemiatj** [comment]
Related to #1734

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

could not test this bc of https://github.com/metasfresh/metasfresh-webui-frontend/issues/2160#issuecomment-463573388

**Comment by metas-ts** [comment]
@metas-dh the fix to https://github.com/metasfresh/me03/issues/1056#issuecomment-471984562 is now integrated into `master`

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

* first row in modal is refreshed and qty displayed correctly after setting qty in QtyToPurchase below: OK
* first row in modal is updated and qty displayed correctly after changing qty in QtyToPurchase below again: OK
* qties are set/updated correctly in Purchase candidate as well: OK
