### ISSUE TITLE
Display process descriptions that are provided by the API

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#2147]
### Is this a bug or feature request?
FR

![image](https://user-images.githubusercontent.com/1264789/51234630-972dc680-196d-11e9-8987-85d967eb3366.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* process descriptions displayed in modal when set in API: OK

* if no description is set in the API, nothing is displayed: OK

* for the parameter fields, the description is displayed if set in API / the fieldname is displayed if not set in the API (regression): OK
