### ISSUE TITLE
Decimal value .00 not added to product price at first

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2149]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you add a product price and just set e.g. 2, the decimal value .00 is not added at first. After closing the modal overlay, the .00 is added to the price.

When setting the price:
![2019-01-16 14_00_05-notificationsform](https://user-images.githubusercontent.com/18696715/51250695-7f6b3800-1997-11e9-8545-e1afc172e2c8.png)

After closing and reopening the overlay:
![2019-01-16 14_02_26-notificationsform](https://user-images.githubusercontent.com/18696715/51250702-84c88280-1997-11e9-9e14-0cfde6e87a80.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Decimal value shall be added directly after setting the price.

(not sure if this is only a frontend issue)

**Comment by siemiatj** [comment]
@oliviupis let me know in case it turns out to be a backend thing

**Comment by metas-dh** [comment]
IT successful, see me03 issue.
