### ISSUE TITLE
Shortcut for direct Document Action <complete>

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#215]
Shortcut for direct Document Action <complete>
- This will allow to let the user directly complete a document without using <ctrl> + i and cursor.

**Comment by cadavre** [comment]
It is 'ctrl+i' and 'enter' now if "Complete" is default action. You'd prefer to have another, dedicated shortcut for "Complete"?

**Comment by cadavre** [comment]
@metas-mk need input here about shortcut, because we will use same in HU editor for main action.

**Comment by cadavre** [comment]
Please use [Ctrl]+[U] – same as for "Primary quick action" in POS.

**Comment by metas-mk** [comment]
Test in /window/143/1003740
<ctrl> works somehow when done twice. always opens sourceview window in windows/ chrome environment.
![image](https://cloud.githubusercontent.com/assets/13365687/23031625/f3c9e8ba-f471-11e6-909a-bcd3440191c1.png)

**Comment by chmieludaniel** [comment]
The referenced commit should do the trick.

Note: you should clear cache before testing, or open it in incognito mode

**Comment by metas-mk** [comment]
Tested. Cleared Browser Cache. Open Sales Order Window. Focus on Field Quick Batch Entry Product. <ctrl> + u pressed. --> source view editor opens.
--> IT failed. reopened the issue.
Info: We had such kind of issues now already a few times. Can someone please make sure that the shortcuts work on chrome/ windows combination best and reliable.

**Comment by metas-mk** [comment]
Tested. Works nicely now. Moving to done.
