### ISSUE TITLE
frontend: Document included tab: pluggable actions to start a process

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2157]
### Is this a bug or feature request?
FR
backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/1134

### What is the expected or desired behavior?

![image](https://user-images.githubusercontent.com/1244701/51607440-4e51b100-1f1d-11e9-8bee-f3f75e1872d5.png)

**Comment by siemiatj** [comment]
Related to [#1009])https://github.com/metasfresh/me03/issues/1009)

**Comment by teosarca** [comment]
quick tested, works
i.e. Open/Create a new sales order. In the order line tabs you shall have the `Products proposal` button.
Press on it, the products proposal modal shall be opened.
![image](https://user-images.githubusercontent.com/1244701/52690934-ed3f5b00-2f67-11e9-8de1-d2cd8a644ae3.png)

![image](https://user-images.githubusercontent.com/1244701/52690942-f8928680-2f67-11e9-9267-e106056eaffa.png)

**Comment by teosarca** [comment]
found following issue:
* open sales order
* on lines tab, click on Products Proposal button => works!
* select one of the order lines
* click again on Products Proposal button => does nothing => NOK

**Comment by siemiatj** [comment]
Looks like I've introduced an error trying to fix something else. Should the row selection influence the products proposal modal in any way ? Cause no matter which row I select I'm always getting the same results. Data sent with the request looks fine though.

![screen shot 2019-02-13 at 17 45 38](https://user-images.githubusercontent.com/513460/52728395-834ea200-2fb7-11e9-9328-6e7dbff77c6e.png)

**Comment by teosarca** [comment]
> Should the row selection influence the products proposal modal in any way ?

Nop, in that case not. "More products..." shall be shown no matter what rows are selected.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Sales order:

* `Products proposal` button: 
    * not in actions anymoreress on it, but order line tabs: OK
    * the products proposal modal is opened when clicking the button: OK
* the products proposal modal is opened:
    * when 1 orderline is selected: OK
    * when >1 orderline is selected: OK
    * when no orderline is selected: OK (i guess)
    * every time when the button is clicked: OK
* actions in the `Products proposal` modal: `More products` (no matter which line in the modal is selected): OK
