### ISSUE TITLE
Modal view: Cancel button support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2158]
### Is this a bug or feature request?
FR

### What is the expected or desired behavior?
If provided by backend, the frontend shall render and support a Cancel button for modal views.
e.g.
![image](https://user-images.githubusercontent.com/1244701/51608831-4136c100-1f21-11e9-8420-18d60afbbe98.png)

**Comment by siemiatj** [comment]
Which response will have the info required to render this new button ?

**Comment by teosarca** [comment]
@siemiatj  preparing the concept + backend changes; will ping you

**Comment by teosarca** [comment]
## Concept update

Take following example on w101.
Have a draft sales order, e.g. https://w101.metasfresh.com:8443/window/143/1001308 .
Call the `Products Proposal` action.
![image](https://user-images.githubusercontent.com/1244701/51688580-90eaba80-1ffd-11e9-91cd-a0f7525677a5.png)

Check the `/layout` endpoint response.
It was a (new) property called `allowedCloseActions` which is an array that can contain CANCEL, DONE strings.
Based on that array, we shall display the corresponding buttons.

![image](https://user-images.githubusercontent.com/1244701/51688754-ede67080-1ffd-11e9-8bfe-f358155921b7.png)

When the user is pressing Done or Cancel the http://w101.metasfresh.com:8080/swagger-ui.html#/view-rest-controller/closeViewUsingDELETE endpoint is called.
Remark the new query param that we introduced there, the `action`.
When Done button is pressed, the DELETE endpoint shall be called with action=DONE.
When Cancel button is pressed, the DELETE endpoint shall be called with action=CANCEL.

**IMPORTANT** If the DELETE endpoint call fails, make sure the modal view is not closed!!!

**Comment by teosarca** [comment]
@siemiatj  check the concept above

**Comment by siemiatj** [comment]
Awesome, everything seems clear.

**Comment by siemiatj** [comment]
Related to #1003

**Comment by teosarca** [comment]
Hi @siemiatj,

Found following issue. In case the `allowedCloseActions` is an empty array then the DONE button is rendered. That's not OK, it shall NO button be rendered.
![image](https://user-images.githubusercontent.com/1244701/52550752-17671080-2de2-11e9-8c74-97a722f80b4a.png)


PS: atm of writting this, the case is not in master but in my branch. Pls let me know if u cannot fix it "blindly".

**Comment by teosarca** [comment]
@siemiatj 

Steps to reproduce (now) on w101:
* https://w101.metasfresh.com:8443/window/143/1001327

![image](https://user-images.githubusercontent.com/1244701/52648399-22f42d80-2eef-11e9-8a9f-8091d5e5e2d2.png)

![image](https://user-images.githubusercontent.com/1244701/52648424-31424980-2eef-11e9-85b3-98ec054070e9.png)

![image](https://user-images.githubusercontent.com/1244701/52648488-53d46280-2eef-11e9-8063-833784c0caee.png)

**Comment by metas-dh** [comment]
Results of IT2

* testcase described in https://github.com/metasfresh/metasfresh-webui-frontend/issues/2158#issuecomment-462241247: fixed, no button is rendered in that case: OK
* shortcut `Esc` not working: not necessary right now, but needed soon: #2180
