### ISSUE TITLE
Button <record_id> does not open according window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#216]
Button <record_id> does not open according window
- does not open any window. here example in "Lieferdisposition"

![image](https://cloud.githubusercontent.com/assets/13365687/22174610/cc03a44a-dfe2-11e6-9a53-e69d0e6b7ce4.png)

**Comment by cadavre** [comment]
Where can this be found? In "Lieferdisposition" I can't see any button like this.

**Comment by metas-mk** [comment]
Yes, took it out of the layout as long it does not work. Can include back in advanced edit if you need.

**Comment by damianprzygodzki** [comment]
I don't think that we ever support that kind of processing buttons onClick. Buttons are just sending to api patches like every widget. It may be related to #250 and imo is enhancement.

**Comment by teosarca** [comment]
Update:  introduced another widget type, called "ZoomIntoButton".
In shall be rendered as a button.
When user clicks on it, the frontend shall do exactly what's described on https://github.com/metasfresh/metasfresh-webui-frontend/issues/720 .

To test, you can use https://w101.metasfresh.com:8443/window/193/1000042

![image](https://cloud.githubusercontent.com/assets/1244701/25909892/3cdb7330-35b7-11e7-894d-d23ab64863af.png)


Backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/354

**Comment by metas-lc** [comment]
IT
1. open window 193, select a line (open single document)
2. select record id button => new tab opens with window 53064 and the corresponding document (single view)
