### ISSUE TITLE
Selected row not always correctly recognized

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2160]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Sometimes in details view row is selected, but header doesn't react to that and row-specific actions are still disabled.

![screen shot 2019-01-25 at 01 40 06](https://user-images.githubusercontent.com/513460/51718194-7d167700-2044-11e9-8fd4-8cd47ff19837.png)

#### Which are the steps to reproduce?

Go to sales order and refresh the view clearing cache.

### What is the expected or desired behavior?

After selecting rows, actions should be immediately available.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* actions immediately available after selecting rows (e.g. in sales order): OK
* calling an action for a selected line: nothing happened for me, e.g. `Create purchase orders` (SetUp was OK): nothing happening, just an error in console:

```
numeral.js:11 Uncaught (in promise) TypeError: _.last is not a function
    at Modal.<anonymous> (numeral.js:11)
    at w (react.production.min.js:10)
    at Generator._invoke (react.production.min.js:10)
    at Generator.e.(anonymous function) [as next] (https://mf15cloudit/bundle-3d67939f7264a1d2f26f-git-87c153d.js:149:11411)
    at asyncGeneratorStep (numeral.js:11)
    at a (numeral.js:11)
    at numeral.js:11
    at new Promise (<anonymous>)
    at Modal.init (numeral.js:11)
    at Modal.<anonymous> (numeral.js:11)

```

* other problem: i had all actions available also when there was no row selected, e.g. in sales order, no orderline was selected and i could select the `Multigroup lines` action: => nothing happens, same error in console

**Comment by siemiatj** [comment]
This can be re-tested

**Comment by metas-dh** [comment]
Results of IT2
tested in mf15

tested with sales order:
* actions immediately available after selecting rows: OK
* calling an action for a selected line: correct modal opens (e.g. Create purchase order, or Pricing Conditions): OK
* only the suitable actions are available for the selection:
   * 1 line selected: all actions (in sales order) for orderline available: OK
   * >1 line selected: correct actions available (e.g. Create purchase order, Grouping, but not Pricing Conditions): OK
   * no line selected: correct actions available (e.g. Purchase order from sales order, but not  Pricing Conditions): OK
