### ISSUE TITLE
View quick actions shall not display scrollbar

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2162]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
![image](https://user-images.githubusercontent.com/1244701/51759712-8568c380-20d1-11e9-999f-6ee1a218cd99.png)

### What is the expected or desired behavior?
don't show scrollbars

**Comment by siemiatj** [comment]
Looks like this is only happening on Windows. #herewegoagain

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

scrollbar not displayed anymore in quick actions: OK
