### ISSUE TITLE
Host google fonts locally

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2169]
### Is this a bug or feature request?

Feature

### What is the current behavior?

Roboto font is loaded from google fonts.

#### Which are the steps to reproduce?

.

### What is the expected or desired behavior?

We should load google fonts locally.

**Comment by metas-ts** [comment]
"Dev-Test": https://github.com/metasfresh/metasfresh-webui-frontend/pull/2170#issuecomment-460206821

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

Fonts are hosted locally: OK
