### ISSUE TITLE
Changes in bpartner fields in order not always patched

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2172]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When you change sth in the bpartner fields in e.g. sales order, these changes are not always patched:

1. Location from bpartner relation selectable:
![2019-02-04 16_46_46-metasfresh](https://user-images.githubusercontent.com/18696715/52277326-c3c57480-2954-11e9-9440-9a6612de2aee.png)

![2019-02-04 16_46_23-metasfresh](https://user-images.githubusercontent.com/18696715/52277338-cb851900-2954-11e9-8b94-79f9ee22d65a.png)

2. Different locations and contacts for bpartner selectable:
http://recordit.co/eR28tmJalq

#### Which are the steps to reproduce?
1. Location from bpartner relation selectable:
* Have a bpartner relation, so that partner B can be invoice partner for orders of partner A
* Set bpartner A in sales order, as bpartner => invoice partner is set as well, for partner A
* Set partner B as invoice partner, check the locations: location of partner A selectable: NOK

2. Different locations and contacts for bpartner selectable:
=> have different locations and contacts for the same bpartner, play with selecting them in the bpartner field / invoice partner field in order
=> i tried with `Enter`, selecting with mouse click and also `Tab`, nothing really worked properly (i also tried waiting a little after setting the location / contact, same result)
### What is the expected or desired behavior?
1. Only the resp. location of the bpartner shall be selectable
2. The location / contact selected shall be set properly, dropdown shall not open again

**Comment by siemiatj** [comment]
Maybe related to #2234 ?

**Comment by metas-dh** [comment]
Results of IT1
tested in release

1. Location from bpartner relation selectable:
* only the location for the resp. bpartner was selectable, not the one from relation: **OK**
* in case of several locations for 1 bpartner, all were correctly displayed and selectable: **OK**

2. Different locations and contacts for bpartner selectable:
* locations and contacts were set correctly after selecting them: **OK**
* dropdown did not open anymore after setting a field, only when called again: **OK**
* worked fine with `Tab`, `Enter` and clicking somewhere: **OK**
