### ISSUE TITLE
Support single entry view mode for Tabs

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2177]
### Is this a bug or feature request?

Feature

### What is the current behavior?

Right now tabs will always display items in tables.

#### Which are the steps to reproduce?

Open any tab with a single entry in the table.

### What is the expected or desired behavior?

For single entries hidden behind a new flag we want tabs to support showing records in a detailed view, without the table and `add new record` button.

**Comment by metas-ts** [comment]
Hi @siemiatj 
I'm in the process of providing you with a def instance.
Here is what you will get from the API:
![image](https://user-images.githubusercontent.com/1264789/52663641-6064b500-2f07-11e9-8a9e-fffc0307b684.png)

Notes this tab
* has `singleRowDetailView`
  * for "normal" tabs (`singleRowDetailView==false`) the API omits the property altogether; let me know if it should harather be explicitly provided by the API in both cases
* does not have a list of `elements` (let me know if you instead want an explicitly empty list)
* has a list of `sections`, just like the window's main part

**Comment by metas-ts** [comment]
this close "by me" was accidental, by me merging https://github.com/metasfresh/metasfresh-webui-frontend/commit/93afbcb5fa9fae42e631e36d6059e95921a72dd7
