### ISSUE TITLE
TAB shall not open the Notifications popup

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2178]
### Is this a bug or feature request?
Bug

#### Which are the steps to reproduce?
Open a window, e,g. Business Partner.
Select the last included tab.
Press tab couple of times.
The Notifications popup is opened (number 3 in the example below) => NOK
![image](https://user-images.githubusercontent.com/1244701/52617457-96bd1880-2ea4-11e9-879f-717d27a53570.png)

### What is the expected or desired behavior?
The notifications popup shall NOT be included in the TAB sequence.

**Comment by siemiatj** [comment]
Tab should never open notifications dropdown or only in this specific case ?

**Comment by teosarca** [comment]
Exactly, the Tab should NEVER open the notifications dropdown.

**Comment by metas-dh** [comment]
IT documented in me03 task: **OK**
