### ISSUE TITLE
Reduce Gap Height between Layout Sections

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#218]
Reduce Gap Height between Layout Sections. Can be reduced to height of Gaps between Element Groups.

![image](https://cloud.githubusercontent.com/assets/13365687/22175807/ff2b6082-dffc-11e6-9d5c-69f1f6d74544.png)

**Comment by cadavre** [comment]
Reduced by 1rem. Left margin as is now (at dev branch) for different cases like two primary groups one after another (we need spacing there).
