### ISSUE TITLE
Back button for modals

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2182]
### Is this a bug or feature request?

Feature

### What is the current behavior?

Modals have no back button functionality

#### Which are the steps to reproduce?

Open any modal and see.

### What is the expected or desired behavior?

Modals should have a back button, that uses `parentWindowId` and `parentViewId` to navigate back.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* `Back` button in modal view, `More products...`: OK
* pressing the `Back` button closes the `More products...`, user gets back to `Products Proposal`: OK
* `Back` option in quick actions: shall be taken out in https://github.com/metasfresh/metasfresh-webui-api/issues/1154
