### ISSUE TITLE
Calendar icon of date fields should be clickable

### ISSUE THREAD

**Issue by brawer** [metasfresh/metasfresh-webui-frontend#2186]
UX improvement: In a date field, currently nothing happens when clicking on the calendar icon to the field’s right. This isn’t dramatic: eventually, one figures out that the place to click is the blank line and not the icon. But to increase usability, it would be nice if the calender pop-up was also shown when clicking the calendar icon.

To reproduce, go to user settings and click the calendar icon (marked in image below). Expected: Calendar popup. Observed: Nothing.

![image](https://user-images.githubusercontent.com/1527880/52994183-0ab46f00-3417-11e9-98d7-bd32b5cb4c70.png)

**Comment by siemiatj** [comment]
Duplicate of #2274
