### ISSUE TITLE
QR Code sometimes not visible

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2190]
### Is this a bug or feature request?

Bug

### What is the current behavior?

When a modal is displayed and user wants to show QR code, it stays hidden behind the modal.

#### Which are the steps to reproduce?

Open a modal and run QR Code action

### What is the expected or desired behavior?

QR Code should be on top

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* QR code is displayed when 4Eyes Review action is called: OK
(code can also still be found in inspect, for testing w/o scanner: OK)
