### ISSUE TITLE
Tab top actions: use provided shortcut if any

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2195]
### Is this a bug or feature request?
FR

backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/1155

#### Which are the steps to reproduce?
![image](https://user-images.githubusercontent.com/1244701/53267667-94e92580-36ec-11e9-8ca3-018c19d483af.png)

### What is the expected or desired behavior?
If shortcut is provided, frontend shall use it and shall react to it,
i.e. when pressed it shall start the process.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* provided shortcut `Alt` + `z` for opening product proposal working fine: OK

=> missing: hint for the shortcut when hovering over the button: created #2252
