### ISSUE TITLE
Don't show input field for QR reader on mobile

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2197]
### Is this a bug or feature request?

Enhancement

### What is the current behaviour?

Right now when running `scan QR` action, user gets the modal overlay first and has to click `Scan` button to open the actual scanner.

#### Which are the steps to reproduce?

Select `Run QR Code action` from the subheader on a mobile device.

### What is the expected or desired behavior?

User should immediately get the camera scanner window.

**Comment by metas-dh** [comment]
checked quickly in customer db, working fine.
