### ISSUE TITLE
Fix sending tab data when creating process modal

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2199]
### Is this a bug or feature request?

Bug

### What is the current behavior?

TabID is not sent with the request.

#### Which are the steps to reproduce?
* create a new sales order
* add some line(s)
* select some lines and call `Group Lines` action
* remark that the selected lines from the included tab are not transmitted when the process instance is created => NOK

![image](https://user-images.githubusercontent.com/1244701/53632176-ec235480-3c1c-11e9-96ad-5beeff5e6da5.png)

### What is the expected or desired behavior?

tabId should be sent

**Comment by metas-dh** [comment]
checked again with metas-tsa: works fine in master (mf15), grouping works as well, but not yet in release => needs to be CPed

**Comment by metas-ts** [comment]
🍒 picked the 3 commits of PR https://github.com/metasfresh/metasfresh-webui-frontend/pull/2200 into the `release` branch
