### ISSUE TITLE
Implement side list panel

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#22]
Implement side list panel to be able to browse existing documents

**Comment by cadavre** [comment]
Actually first we need to create whole dedicated page with list of existing documents.

**Comment by damianprzygodzki** [comment]
Side list is already implemented. We should think here about how it should be generate by API, and from could i get list of them.

**Comment by teosarca** [comment]
Great. Then, we just need to define two /api/endpoints and we can link them:
* fetching the layout (i.e. the elements which shall be displayed in side list)
* fetching the data (with or without query param; initially we will do it without)

**Comment by cadavre** [comment]
Hold on with this, I'll prepare you mocks to visualize the new flow for metasfresh document selection. We already discussed it with Mark.

**Comment by teosarca** [comment]
UPDATE: Working prototype API is ready. See:
* GET /rest/api/window/sideListLayout
* PUT /rest/api/window/sideListData
