### ISSUE TITLE
Attributes panel is not displayed in HU Editor

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2201]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The attributes are not displayed anymore in HU Editor (e.g. HU Editor window/540189, material receipt candidates window/540196, so you cannot set / change attributes anymore: NOK.

![2019-03-04 16_32_32-metasfresh](https://user-images.githubusercontent.com/18696715/53809382-e303f180-3f54-11e9-9f74-173f3350cda8.png)

#### Which are the steps to reproduce?
Check and see.
### What is the expected or desired behavior?
Show the attribute panel on the right side in HU Editor.

**Comment by metas-ts** [comment]
🍒 picked commit https://github.com/metasfresh/metasfresh-webui-frontend/commit/28b74f11a552d03013356109e702a8d31ccb4b33 into branch `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in weekly e2e

* attribute panel displayed correctly (material receipt cands, HU Editor window etc.): OK
* attributes displayed as set & can be changed / set (in material receipt cands): OK
