### ISSUE TITLE
The date is shown wrong in single mode

### ISSUE THREAD

**Issue by cristinamghita** [metasfresh/metasfresh-webui-frontend#2202]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The date is shown with day behind in single mode.
The value is set correctly in the field, but is displayed wrong:
```
DateOrdered: {field: "DateOrdered", value: "2018-09-21T00:00:00.000+03:00", readonly: true, mandatory: true,…}
displayed: true
field: "DateOrdered"
mandatory: true
readonly: true
validStatus: {valid: true, initialValue: true, fieldName: "DateOrdered"}
value: "2018-09-21T00:00:00.000+03:00"
viewEditorRenderMode: "never"
widgetType: "Date"
```
But the html code generated is:
```
<input type="text" placeholder="none" disabled="" tabindex="-1" class="form-control" value="09/20/2018">
```

#### Which are the steps to reproduce?
* Open a sales order and check the date order in grid mode
![image](https://user-images.githubusercontent.com/15378036/53814605-8f9b9e80-3f68-11e9-9263-8986c68e38e3.png)
* Now, same order, in single mode
![image](https://user-images.githubusercontent.com/15378036/53814662-b0fc8a80-3f68-11e9-9854-c98dda2888f8.png)
### What is the expected or desired behavior?
The date should be the same in grid mode or single mode.

**Comment by cristinamghita** [comment]
Looks the problem can be reproducible in sales order only with older values.
If I create a new order, is fine
And, in dev tools, for DateOrdered from older order we have: value: "2018-09-21T00:00:00.000+03:00"
but for a new order, we have : value: "2019-03-03T00:00:00.000+02:00"
Notice +03 instead of +02.
But in db, both are saved:
"2018-09-21 00:00:00"
"2019-03-03 00:00:00"

**Comment by siemiatj** [comment]
So as far as I understand date that comes from the API is wrong for older sales orders. Either I'm missing something or it's not a frontend issue.

**Comment by metas-dh** [comment]
this worked fine in this week's e2e, as did #2219; will check again next week and close if it's fine then too.
