### ISSUE TITLE
input field value sometimes swallowed

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#2214]
### Is this a bug or feature request?
bug

**Comment by metas-ts** [comment]
the problem is reproduced in https://jenkins.metasfresh.com/job/metasfresh-e2e/job/dev-2214/
see the spec added in commit https://github.com/metasfresh/metasfresh-e2e/commit/d3aea3ecd93d00173ad07e8e816b443a6758a9f4#diff-8affdebf35cc9f48e60c29c19597b77e
please do the fix in branch `dev-2214`.

**Comment by siemiatj** [comment]
As far as I can tell this is only reproducible in cypress tests. Two things I've changed are:
* to NOT reset widgets when field is blurred as it caused multiple unnecessary requests to the server even if value haven't changed
* prevent default action on all inputs

So when testing we should just check if nothing looks out of place and behaves incorrectly when editing/updating fields.
