### ISSUE TITLE
Console flooded with error "Cannot read property 'getInstance' of null"

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2217]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Console in releasetest is flooded with error "Cannot read property 'getInstance' of null", popping up when you just click somewhere: http://recordit.co/tsJBPSkKFr
(not happening in cloudit!)
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
No error in console.

(Not sure if this just a frontend issue; also, it doesn't seem to affect any action etc.)

**Comment by siemiatj** [comment]
Is this still happening ? I've never seen this issue.

**Comment by metas-dh** [comment]
was not happening anymore in this week's e2e, will check again next week, and close the issue if still fine.

**Comment by metas-dh** [comment]
worked fine in this week's e2e:

* could reproduce the error at one point
* console was not flooded anymore with that
