### ISSUE TITLE
If there is any error while setting a document field then the widget value shall be reverted

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#222]
e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/22258942/154e2a5e-e26c-11e6-9307-0ea53ff99b06.png)

**Comment by Dunkat** [comment]
Hi, after error I am getting all data again to set in widget. But maybe is it possible to get data only from this one widget which should be reverted?

**Comment by teosarca** [comment]
Hi,

You have 2 options.

option 1.
* Pls memorize the value before changing it.
* call the PATCH endpoint to set it
* if PATCH failed, set the field value to memorized value
* if PATCH succeeded, you will have the field value in the patch response.

**NOTE: i would really prefer this option because it's efficient**


option 2. You can get a field value anytime.
e.g. http://w101.metasfresh.com:8081/rest/api/window/143/1003486?fields=C_BPartner_ID
See http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDataUsingGET_3
