### ISSUE TITLE
Display time fields with no seconds in gridview

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#2221]
### Is this a bug or feature request?
* FR
### What is the current behavior?
* Currently the time fields are displayed with only hour and minutes

![image](https://user-images.githubusercontent.com/16001442/54680286-22643d80-4b12-11e9-859f-e88628f375cc.png)

* In gridview, on the other hand, they are displayed with seconds. 
![image](https://user-images.githubusercontent.com/16001442/54680415-70794100-4b12-11e9-8774-4e6c36ea74e3.png)

#### Which are the steps to reproduce?
* Open any window with a time field in grid and single view.

### What is the expected or desired behavior?
* We don't need to see the seconds in grid view. Please, only display hour and minutes, too.

**Comment by teosarca** [comment]
# Note to IT
See my comment here https://github.com/metasfresh/metasfresh-webui-frontend/pull/2227#issuecomment-476780896

i.e.
* grid view: make sure the "seconds" are not displayed
* single document layout (widget): make sure the "seconds" are not displayed
* super IMPORTANT for our customers: If the Locale is using 24h time format, we have to respect that. i.e. switch to German language and try it.

**Comment by metas-dh** [comment]
see IT for Display time fields with no seconds in gridview #1326

for the future: https://github.com/metasfresh/metasfresh-webui-api/issues/1185
