### ISSUE TITLE
Errors thrown by typeahead endpoints shall be rendered into the dropdown box.

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#223]
Case:
* new order
* in BPartner field press <space>
* typeahead endpoint fails with "Invalid filter" error

IMHO that error shall be rendered in the dropdown box instead of "global errors".

![image](https://cloud.githubusercontent.com/assets/1244701/22259153/ee2f4ac4-e26c-11e6-83b6-9681ad1b7b5f.png)

**Comment by cadavre** [comment]
Covered by #650 .
