### ISSUE TITLE
Comma does not work in Attribute value

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2235]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The comma (decimal sign) does no work in Attribute value for Number field.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Please, fix.

![image](https://user-images.githubusercontent.com/13365687/55304730-3cc0e400-544d-11e9-8558-6d83def3d596.png)

**Comment by teosarca** [comment]
@metas-mk  are you talking preciselly about that string (which is built by backend) or are you also talking about editing that numeric attribute?

**Comment by siemiatj** [comment]
@teosarca editing works and I think it's about the string that comes from the backend. Commented on that in the me03 issue.

**Comment by siemiatj** [comment]
Closing as it's a backend task.
