### ISSUE TITLE
Scrollbars missing in modal overlays

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2237]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The scrollbars are missing in modal overlays, e.g. in manufacturing order:

![2019-04-01 16_54_34-Metasfresh](https://user-images.githubusercontent.com/18696715/55380296-14ee8080-5520-11e9-8ae2-2e3030ebfced.png)

#### Which are the steps to reproduce?
Check (in releasetest).

**Comment by siemiatj** [comment]
Deployed to https://dev388.metasfresh.com

**Comment by metas-ts** [comment]
🍒 picked commit https://github.com/metasfresh/metasfresh-webui-frontend/commit/f74a94ed3cd50b5d35491d59b685b9c2712a86a4 to branch `release`

**Comment by metas-dh** [comment]
Results of IT1
tested in release

* scrollbars are displayed again in modal overlays, e.g. in material receipt cands, or PP_Order, and work fine: OK
* scrollbars are displayed as usual in windows. e.g. shipment schedule, product, and work fine: OK
