### ISSUE TITLE
Fix tabbing

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2244]
### Is this a bug or feature request?

Bug

### What is the current behavior?

In some cases tabbing out of the field doesn't work.

#### Which are the steps to reproduce?

Create a new product. Focus gets stuck in the first field.

### What is the expected or desired behavior?

Tab should work.

**Comment by ionut-movila** [comment]
@siemiatj: This looks like it's working now. Maybe it was fixed with related commits and this issue was not updated?

The blue outline is just a sing that field is required, not that focus is in that field.

**Comment by siemiatj** [comment]
Well the fix is in place, so I'd hope this works :)
