### ISSUE TITLE
build frontend on CI infrastructure

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#225]
use jenkins and nexus for building and deploying as we do with the rest of the stack

**Comment by metas-ts** [comment]
* there is a jenkins plugin (should already be installed) to manage npm..i.e. jenkins will take that that npm is already installed then the build job runs
* i guess that we can mostly use the script we already have
* nexus can act as an npm repo, but we need to check how it's done..i imagine that there is some npm-deploy-to-repo command, or that we can use curl or something. at any rate, jenkins can manage the credentials and provide them to the script in a save manner

**Comment by cadavre** [comment]
Done by #283 .
