### ISSUE TITLE
Attributes panel displayed only after blurring button

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2251]
### Is this a bug or feature request?

Bug

### What is the current behavior?

http://recordit.co/OV6TqeqnsJ

#### Which are the steps to reproduce?

Click attributes button and keep mouse over the button.

### What is the expected or desired behavior?

Attributes panel should load no matter where the cursor is.

**Comment by metas-ts** [comment]
@siemiatj @metas-dh 
* FYI, i think serialletter/serialletter.js is a good indicator of whether this issue is fixed
* here is a failing test on the cypress-dashboard: https://dashboard.cypress.io/#/projects/5yp4q1/runs/92/failures/368198a9-f5a5-482b-9384-90e7f062bfae

**Comment by metas-ts** [comment]
@metas-dh @siemiatj 
maybe the same problem also can be observed on the login-page: 
![image](https://user-images.githubusercontent.com/1264789/56942785-b9161800-6b1c-11e9-8242-e5cb4d9556ed.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* attribute panel opens normally again (orderline, setting an attribute manually): OK
* address panel works fine again in cypress test, see IT for #1570 
* serialletter/serialletter.js test also ran successfully: OK
* login-page also looking fine: OK
