### ISSUE TITLE
Make it easier to work with checkboxes in cypress

### ISSUE THREAD

**Issue by siemiatj** [metasfresh/metasfresh-webui-frontend#2256]
### Is this a bug or feature request?

Feature

### What is the current behavior?

It's hard to check if checkbox is checked or not, because the `checked` property is not properly updated.

#### Which are the steps to reproduce?

Query for any checked checkbox.

### What is the expected or desired behavior?

There should be a `checked` class added.

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

test for creating pricelist, and checking if
* checkbox IsSOPriceList is checked: OK
* tick checkbox EnforcePriceLimit, check if it's checked: OK
* tick checkbox EnforcePriceLimit again, check if it's not checked: OK
