### ISSUE TITLE
Implement document field device support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#226]
Take following example of an element layout definition:

```
{
      "caption": "WeightGross",
      "description": "",
      "widgetType": "Number",
      "fields": [
        {
          "field": "WeightGross",
          "emptyText": "none",
          "devices": [
            {
              "deviceId": "mettler-MOCKED-WeightGross-GetGrossWeighRequest",
              "caption": "m",
              "websocketEndpoint": "/devices/mettler-MOCKED-WeightGross-GetGrossWeighRequest"
            }
          ]
        }
      ]
}

```

Remark the "devices" entry. There can be an array of "device" definitions.
For each each "device" we shall render a small button on the right side of our widget.

The frontend shall subscribe to given "websocketEndpoint" to fetch the device current value. Details about this will come later.

When the user presses on the button, the correct PATCH method shall be called in order to set the device's value to corresponding field (in the example above the field is WeightGross").

About device's websocket endpoint: when somebody is subscribing to a device endpoint, that endpoint will continuously serve the current device value, using following format, e.g.

```
{
	"deviceId":"mettler-MOCKED-WeightGross-GetGrossWeighRequest",
	"value":"463.00",
	"timestampMillis":1485542915186
}

```

**Comment by cadavre** [comment]
This will be implemented after "POS: Selection attributes" is done.

**Comment by teosarca** [comment]
Hi guys,

Checked with one device and looks awesome!

... but when i've tried with 2 devices, the layout it does not look nice....
![image](https://cloud.githubusercontent.com/assets/1244701/22698452/3d340ae2-ed5d-11e6-887e-6e99a5c024c6.png)
