### ISSUE TITLE
Scrollbar missing in modal overlays

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2262]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Scrollbar is missing in modal overlays, on the right, so you cannot scroll down in attributes / to see all HUs when there are more than fit the initial view.

material receipt cands:

![2019-05-14 09_18_16-Metasfresh](https://user-images.githubusercontent.com/18696715/57678589-d7563a80-7629-11e9-881f-4819d0083773.png)

manufacturing order:

![2019-05-14 09_18_50-Metasfresh](https://user-images.githubusercontent.com/18696715/57678598-dc1aee80-7629-11e9-954e-9280fe45a0f1.png)

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Show the scrollbar.

**Comment by metas-Kay** [comment]
also missing in product proposal overlay:
![scroll bar missing](https://user-images.githubusercontent.com/29163573/57772780-a43da500-7716-11e9-9e5c-e4f98a0e6397.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in release

Scrollbar displayed correctly, in e.g. material receipt cands, manufacturing order, product proposal etc.: **OK**
