### ISSUE TITLE
HU Panel too small in material receipt candidates' modal overlay

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2263]
### Is this a bug or feature request?
The HU Panel is too small in the material receipt candidates' modal overlay.
### What is the current behavior?
The modal overlay opens with correct panel size, then it reduces after a second. When you click on the CU line, the panel gets the correct size (see vid in me03 task).

#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
The panel shall be displayed properly at all times.

**Comment by ionut-movila** [comment]
@metas-dh Can you please link the video with the bug here? 
This should help new team members easier locate the problem.

**Comment by metas-dh** [comment]
@ionut-movila here u go: http://recordit.co/75QSlHrCdF

**Comment by metas-dh** [comment]
Results of IT1
tested in release

1. Panel size is back to normal in material receipt cands overlay: **OK**
2. Scrollbar and selection option underneath the panel are missing: **NOK**

http://recordit.co/8JbU7NeDua

@oliviupis can u fix this in this task?

**Comment by metas-dh** [comment]
@oliviupis @ionut-movila 

about 
2. Scrollbar and selection option underneath the panel are missing: NOK
http://recordit.co/8JbU7NeDua

can u fix this in this task or shall i create a new one?

**Comment by metas-dh** [comment]
this was fixed by a recent task when the 2nd scrollbars were corrected.
