### ISSUE TITLE
Notifications and user menu will not close

### ISSUE THREAD

**Issue by ionut-movila** [metasfresh/metasfresh-webui-frontend#2265]
### Is this a bug or feature request?
bug
### What is the current behavior?
In attached screenshot I was able to open both notifications and user menu and they will not close unless you select an item in that menu.
#### Which are the steps to reproduce?
Click on either notifications or user buttons top right (or even both) and the popover menus will remain open until a selecting an item.
### What is the expected or desired behavior?
Two possible solutions:
1. Close these menus with a click on the corresponding menu button
2. Close these menus with a click outside the menu. In this case we should have an overlay to show these menus have modal behaviour.
![Both menus open can't close](https://user-images.githubusercontent.com/8195140/57758454-69307700-7700-11e9-8984-af16d4f91b63.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

1. notifications and user menu cannot be opened at the same time: **OK**
2. notifications and user menu close when clicking outside of them, without selecting an item: **OK**
3. correct document is opened when clicking on the notification (e.g. shipment): : **OK**
4. user menu or logout when clicking on the resp. user menu entry: : **OK**

**Comment by metas-ts** [comment]
🍒 picked issue https://github.com/metasfresh/metasfresh-webui-frontend/issues/2265 to branch ´release`
