### ISSUE TITLE
WEBUI: action menu not correctly positioned 

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2268]
### Is this a bug or feature request?
bug

#### Which are the steps to reproduce?
* click on Action menu, in any window u are
* the Action menu popup is displayed over the action menu button

### What is the expected or desired behavior?
It shall displayed right below, like Inbox, User menu etc.

![image](https://user-images.githubusercontent.com/1244701/57830277-495d8980-77ba-11e9-8cd5-79b0dc47bc17.png)

![image](https://user-images.githubusercontent.com/1244701/57830312-685c1b80-77ba-11e9-837c-8eb6e318c21e.png)

**Comment by siemiatj** [comment]
I don't think this will work as the menu can have different heights depending on the content.

**Comment by metas-dh** [comment]
IT documented in me03.
