### ISSUE TITLE
Fix decimal comma in Qty Fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2278]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Currently, it does not work typing comma in decimal value numeric fields. Only period works, no matter which language is set.
#### Which are the steps to reproduce?
Open window /window/540325 and try to edit numeric value in price values with comma.
![image](https://user-images.githubusercontent.com/13365687/58257111-8bfe0380-7d70-11e9-8324-5d87eff76af4.png)
### What is the expected or desired behavior?
Shall work with comma and period.

**Comment by ionut-movila** [comment]
@metas-mk Can you please check the problem one more time? Looks to be fixed when we tested today running from master branch. See [here](http://recordit.co/75Kz3wSOXK) video.

**Comment by metas-mk** [comment]
@ionut-movila can u pls always show the url bar in pics/ videos so I can check,

**Comment by oliviupis** [comment]
@metas-mk .../window/540325/540025

**Comment by metas-mk** [comment]
@oliviupis here a screenshot of what I see on https://w101.metasfresh.com:8443/window/540325/540025

![image](https://user-images.githubusercontent.com/13365687/58869313-44577000-86be-11e9-824e-4f0c0294d22b.png)

No comma allowed. Onlly decimal points.
