### ISSUE TITLE
Make OpenViewAction open data in a new browser tab

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2284]
### Is this a bug or feature request?
FR

### What is the current behavior?
When calling a action/process  which in return tells the frontend to open a given view,
frontend is always opening the view in a modal overlay.

#### Which are the steps to reproduce?
Steps to reproduce:
* pick a partner, e.g. https://w101.metasfresh.com:8443/window/123/2156425
* select the "Locations" tab and select one of it's locations:
![image](https://user-images.githubusercontent.com/1244701/58490071-25645580-8175-11e9-91cc-bc03487c9e41.png)

* from the action menu call the "Area search" action:
![image](https://user-images.githubusercontent.com/1244701/58490141-45941480-8175-11e9-91b7-5ba717797135.png)

* write something into Distance field and start the action (we are also calling it process):
![image](https://user-images.githubusercontent.com/1244701/58490210-68262d80-8175-11e9-8043-86757023a299.png)

* check the result: remark that backend adviced the frontend to open a new view:
![image](https://user-images.githubusercontent.com/1244701/58490335-a3c0f780-8175-11e9-876e-aa03b7ac5577.png)

All good, but now we introduced the "modalOverlay" property which means:
* when `true`: open the view in a modal overlay (exactly how it is in that screenshot)
* when `false`: open the view in another browser tab

### What is the expected or desired behavior?
the newly introduced `modalOverlay` property shall be respected.

**Comment by metas-dh** [comment]
for IT see me03 task.
