### ISSUE TITLE
Pressing new line on Order tax tab is creating a new line in order lines

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#23]
Expectation: it shall throw exception because the tab is readonly and the API is throwing exception.

![image](https://cloud.githubusercontent.com/assets/1244701/18194453/5c8a5de2-70ee-11e6-9213-0c1897b40d55.png)

**Comment by damianprzygodzki** [comment]
We agreed at the end of last iteration to provide mocked (because there is no method to render it from API) button to only add New Order Lines, to let you work with Order Lines.
