### ISSUE TITLE
Dropdown Layout for narrow columns

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#230]
Dropdown Layout for narrow columns
- we need a general solution for these things

![image](https://cloud.githubusercontent.com/assets/13365687/22397968/36cdcdfa-e57e-11e6-91f5-7024e5f6c782.png)

**Comment by cadavre** [comment]
Probably best would be to use primary-group-like inputs with labels above, not on side. Wdyt?

**Comment by metas-mk** [comment]
+1
