### ISSUE TITLE
Date Field "Birthday" in BPartner/Contact Tab error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#231]
Date Field "Birthday" in BPartner/Contact Tab error
- same for Grid view in the main window. Shows "invalid date" when Birthday is left empty.

![image](https://cloud.githubusercontent.com/assets/13365687/22398046/8793d3be-e57f-11e6-8656-7437a540bc68.png)

**Comment by teosarca** [comment]
Hints to reproduce:
* make sure the Birthday field is empty/null
* then click on it => the date picker opens
* click away (like u changed ur mind) => error pops because the frontend is sending "Invalid date" string to backend.

**Comment by teosarca** [comment]
might be related to https://github.com/metasfresh/metasfresh-webui-frontend/issues/234

**Comment by Dunkat** [comment]
hello @teosarca, where I can add birthday date? When clicking on 'Add new' everything is disabled

**Comment by teosarca** [comment]
you are right... but take a look:
![image](https://cloud.githubusercontent.com/assets/1244701/22468271/56ca3806-e7d0-11e6-9ada-e4ba8c0e2082.png)
