### ISSUE TITLE
Date/Time widgets fixes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2317]
### What is the current behavior?
Different date and time widgets are handling dates in a weird/incorrect way, so in some cases 
* we have differences between the dates displayed in grid view and single document layout
* dates are displayed in wrong timezone

### What is the expected or desired behavior?
Expectation: 
* dates are displayed identically and correctly, no matter if in grid mode or in single document layout
* dates are displayed in correct timezone
* frontend is aware and handles dates without timezone and dates with time zone

To accomplish the requirements above, we changed the date/time widget types and also their formats as follows

#### WidgetType: Date
Local date, without time, without timezone.

Format:  yyyy-MM-dd

Example: 2019-04-12

#### WidgetType: Time
Local time

Format: HH:mm

Example: 13:14

#### WidgetType: ZonedDateTime
Date+time in a given timezone

Format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

Important:
* visually we shall display from year to minutes (no seconds, no timezone)
* Frontend shall always use user session's timezone, see http://w101.metasfresh.com:8080/rest/api/userSession, `timeZone` property.

#### WidgetType: Timestamp
Same as ZonedDateTime but this widget is used to display timestamps.

Format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX

#### Widget: DateTime
No longer present.

**Comment by teosarca** [comment]
### note to developer
To disable the legacy date/time widgets and formats, pls call http://w101.metasfresh.com:8080/rest/api/debug/legacyDateTimeWidgets?enable=false

**Comment by siemiatj** [comment]
@teosarca the `DateWidget` still shows up on w101.

**Comment by teosarca** [comment]
@siemiatj  true,

seems i forgot to rename them, so consider
* Date - it's the local date (day, month, year)
* Time - it's the local time (hour:minute)

**Comment by teosarca** [comment]
and btw, on frontend side it would be nice to have those widget types defined as constants.
Here is the complete list: https://github.com/metasfresh/metasfresh-webui-api/blob/master/src/main/java/de/metas/ui/web/window/datatypes/json/JSONLayoutWidgetType.java

**Comment by siemiatj** [comment]
@teosarca as constants in what way and what for ?

1. I still have `DateTime` coming from the API even though I've hit this endpoint mentioned https://github.com/metasfresh/metasfresh-webui-frontend/issues/2317#issuecomment-511758878 . Should I consider `DateTime` as something that's staying, but is not having TZ defined ?

2. Is `Timestamp` a widget to edit the timestamp value, or it's only for presentational purposes ? Where can I test that ?

**Comment by teosarca** [comment]
@siemiatj  ping me when u are back.

In meantime i did a quick check

----
about 1.

* http://w101.metasfresh.com:8080/rest/api/debug/legacyDateTimeWidgets?enable=false
* then checked https://w101.metasfresh.com:8443/rest/api/window/143/layout
![image](https://user-images.githubusercontent.com/1244701/62857771-18311e80-bd01-11e9-9b36-4f3022d89fb7.png)


----
about 2.

See https://w101.metasfresh.com:8443/rest/api/window/540163/layout, `Created` field
![image](https://user-images.githubusercontent.com/1244701/62858032-e40a2d80-bd01-11e9-99d7-a9f339909842.png)


Atm we don't have an editable example but we need to evaluate how much effort would be needed.
As a workaround we just need to allow editing from year to minute and  just keep the seconds and millis.
