### ISSUE TITLE
Keyboard usage in Navigation Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#232]
Keyboard usage in Navigation Window
- Would be intuitive to search > see search results and then same as autocomplete be able to directly go down via <arrow down> and select with <enter>. WDYT?

![image](https://cloud.githubusercontent.com/assets/13365687/22398090/68ed7af4-e580-11e6-99d9-d10e3b7227ef.png)

**Comment by cadavre** [comment]
True. After input is entered, [Tab] should move to first search result and then as already.
