### ISSUE TITLE
Menu: when menu is opened give focus to search field

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#233]
![image](https://cloud.githubusercontent.com/assets/1244701/22398314/7097c422-e58e-11e6-8fe4-3d39d861c9fb.png)

**Comment by teosarca** [comment]
Suggestion: because we want to be uber keyboard friendly, i think, whatever is opened, we shall focus on a field (e.g. the first one). wdyt?

**Comment by cadavre** [comment]
We can do one of two:
1. Focus search input on menu open,
/or/
2. Keep as is and you can use arrows to select menu elements.

You can have one of above. #2 is currently implemented.

**Comment by metas-mk** [comment]
@cadavre Can u please describe how No. 2 works. I tried with arrow up, down, right, left but never get to the input field.

**Comment by cadavre** [comment]
Probably best to provide [Tab] when Navigation opened to switch to search input. Wdyt?

**Comment by teosarca** [comment]
fine for me
