### ISSUE TITLE
Websocket shall use SESSION_ID

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#237]
Important for us in order to secure the websocket endpoint.
Required by task: https://github.com/metasfresh/metasfresh-webui/issues/113

**Comment by teosarca** [comment]
NOTE: if it's not a quickfix please ping me before starting to work on this

**Comment by chmieludaniel** [comment]
when the ws connection is established, regular XHR is sent, which has cookie already set. So it should work out of the box.
<img width="1479" alt="secket_session" src="https://cloud.githubusercontent.com/assets/11337870/22466271/dc50048a-e7bf-11e6-9ce5-6c99037c12df.png">

**Comment by teosarca** [comment]
10x. agree.
