### ISSUE TITLE
Border radius disturbing on Lookup Fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2385]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The Border is missing on Lookup widget fields. Only when marked as blue mandatory field it's shown.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
Fix it, so that the border is shown again.

![image](https://user-images.githubusercontent.com/13365687/65719580-61b5ad00-e0a6-11e9-8cc3-3412bf23d80d.png)

**Comment by metas-mk** [comment]
Just get rid of the "smiling" effect.
![image](https://user-images.githubusercontent.com/13365687/65720509-64190680-e0a8-11e9-9771-763256c8556d.png)

**Comment by siemiatj** [comment]
No border is not a bug as it was never there by design as far as I know :)
