### ISSUE TITLE
Sales Order Line: fix batch entry layout

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#2393]
### Is this a bug or feature request?
bug

### What is the current behavior?
the fields layout is quite shitty.

#### Which are the steps to reproduce?
open and see

### What is the expected or desired behavior?
![image](https://user-images.githubusercontent.com/1244701/66038608-48d05000-e51b-11e9-9ded-f2bc30d69b9d.png)

(order i've used: https://w101.metasfresh.com:8443/window/143/1001523)

**Comment by siemiatj** [comment]
Well the biggest problem is we have too many elements over there and it's really cramped over there. I think we should redesign this part with some nicer UI. In the meantime I'll fix what I can, but most of those things are limited by our css grid.
