### ISSUE TITLE
Got a /commit error when loading an existing document

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#24]
![image](https://cloud.githubusercontent.com/assets/1244701/18198907/b553c572-7106-11e6-9343-7b7311ffbf54.png)

**Comment by cadavre** [comment]
Just opened /143/1000001 and this error popped out?

**Comment by damianprzygodzki** [comment]
@teosarca  Could you provide more information? For me is 404 from API, `@NotFound@ DocumentKey{AD_Window_ID=143, documentId=100001}"` and in other docs didnt occur.

**Comment by teosarca** [comment]
The case is:
* opened an already completed document
* in case of completed documents you are NOT allowed to change any field (with some exceptions)
* the frontend is mistakenly sending a /commit to "change" the C_BPartner_ID
* i am quite sure the frontend is sending the value it got it before from /data (so no real change) but the backend is failing early if u are trying to change a field which is readonly.

Suggested solution:
Make sure you are not sending /commit when there was no change.
