### ISSUE TITLE
Focus when "new" works - but does not let you unfocus anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#240]
Focus when "new" works - but does not let you unfocus anymore
- Tries with Business partner Window and Product. Create New. The Focus is on first field. Not able to get our that field anymore, nor with Mouse nor with keyboard.
- Same for not new Records. Open a record from Grid View. Try to focus with mouse on second field. Not possible.

**Please fix quickly w/ highest prio. Cannot test w/ this bug.**

![image](https://cloud.githubusercontent.com/assets/13365687/22468886/575be202-e7ca-11e6-802c-6af059dc57ab.png)

**Comment by teosarca** [comment]
i have the feeling is related with https://github.com/metasfresh/metasfresh-webui-frontend/issues/239
