### ISSUE TITLE
Allow Editing the window layout from WebUI

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#2413]
Requirements Doublette of an already created issue back in 2017 https://github.com/metasfresh/metasfresh-webui-frontend/issues/888. Moving this issue to that issue and proceeding there.

### Is this a bug or feature request?
FR

### What is the current behavior?
you need to configure the layout on the backend

### What is the expected or desired behavior?

Support various edit types:
1. rename existing fields
1. hide existing fields
1. drag and drop existing fields to existing UI groups
1. add new fields from a list selection

Notes:
- Support Edits only on header level - single view for the first iteration (later we will also support editing other areas)
- Write back layout changes to a new REST endpoint that backend team will provide
- Separate the new Edit-Code from the existing code to avoid breaking existing functionality either using our plugin mechanism, separate components or methods (to be discussed)

![image](https://user-images.githubusercontent.com/16079655/66846838-b1371c80-ef72-11e9-9c9d-555694d46c85.png)

**Comment by siemiatj** [comment]
@metasnw  what's `Support Edits only on header level` ?

**Comment by metasnw** [comment]
> @metasnw what's `Support Edits only on header level` ?

It is what you see on the screenshot. I wrote this to exclude the various grids we also have. We take them on later.

**Comment by teosarca** [comment]
@metasnw  we will have to prepare some backend API for that too/first ... but this is a fucking awesome task

**Comment by metas-mk** [comment]
closed this issue and moved the stuff to the initial issue created here https://github.com/metasfresh/metasfresh-webui-frontend/issues/888.
