### ISSUE TITLE
Add Field Names/ UI Element Names to content area/ value area for combined fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#2440]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, combined fields e.g. Business Partner in Sales order window, only show the name of the combined field as label. The user does not know that it is a combined field before trying out. The user also does not know initially that it is a combined field.
#### Which are the steps to reproduce?
Open try and see for window Sales Order (as example). Combined Field Field Business Partner.
### What is the expected or desired behavior?
Example combined field now:
![image](https://user-images.githubusercontent.com/13365687/68365850-1e813c00-0132-11ea-8884-faf6b0b0e7f1.png)

Required solution (show the UI Element Names/ Field Names in each combined field element instead of "none":
![image](https://user-images.githubusercontent.com/13365687/68366157-e2021000-0132-11ea-9242-cefb306c1dbc.png)

API shall return combined field element Names (similar to labels) for combined field elements.

![image](https://user-images.githubusercontent.com/13365687/68366487-ba5f7780-0133-11ea-8ecb-ceab0f0ab55f.png)

**Comment by petrican** [comment]
<img width="1535" alt="ruxi" src="https://user-images.githubusercontent.com/1708561/72075669-e696a080-32fc-11ea-8817-d3d21c1de80c.png">
Attached the image with the final result

**Comment by teosarca** [comment]
@petrican  Checked batch entry with latest master but NOK
![image](https://user-images.githubusercontent.com/1244701/72185605-de715a80-33fb-11ea-90eb-fc87774ebae2.png)

**Comment by petrican** [comment]
Fixed that https://www.loom.com/share/afc9db43009b422c8e9112543d17cb47
