### ISSUE TITLE
Keyboard shortcuts for next page/ previous page

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#247]
Keyboard shortcuts for next page/ previous page
- Can this be done with roll-up/ roll-down? Same then for  Pos1/ End (first/ last page)?
WDYT?

![image](https://cloud.githubusercontent.com/assets/13365687/22545389/daac3656-e938-11e6-9e2c-0b8161250cc4.png)

**Comment by cadavre** [comment]
I think we can introduce: [PgUp]/[PgDown] to switch pages -1/+1 and [Home]/[End] to first/last. That shortcuts shall be active when selection is active on table – by user clicked once on any row or user navigated with [Tab] to table. This way we will have full keyboard navigation through table: arrow up/down, pgup/pgdown, home/end.
