### ISSUE TITLE
Handle Password Fields in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#248]
Handle Password Fields in WebUI
- Dont't show the password in Password fields. Cloak with dots.

**Comment by cadavre** [comment]
Could you provide single link to where we can find any widget of this type?

**Comment by damianprzygodzki** [comment]
We do not have implementation of password type input, there is only "text" type. One password type input is in login form, hardcoded.

**Comment by damianprzygodzki** [comment]
Is it still frontend issue? Can we do something with it?

**Comment by metas-mk** [comment]
@damianprzygodzki we took out the pwd fields as workaround. I added it back for you in dev environment so you can implement now.
i prepared the following testcase for you. /window/108/2188328

**Comment by metas-lc** [comment]
IT
tested it here https://github.com/metasfresh/metasfresh-webui-api/issues/316 OK
