### ISSUE TITLE
Wrong API call when fetching included tab's field's dropdown values

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#249]
i.e. the tabId is missing.

See the attached screenshot.
The right URL shall be http://localhost:8080/rest/api/window/140/2005602/**1**/2767037/attribute/M_PriceList_Version_ID/dropdown

![image](https://cloud.githubusercontent.com/assets/1244701/22593427/0c99f9d4-ea27-11e6-88e7-e3d81b33a581.png)

**Comment by Dunkat** [comment]
it's already fixed 
![image](https://cloud.githubusercontent.com/assets/21196151/22594021/93758b36-ea21-11e6-91c6-f3ec0429628d.png)

**Comment by teosarca** [comment]
quick tested, works
