### ISSUE TITLE
Tree dots click triggers console error/warning

### ISSUE THREAD

**Issue by petrican** [metasfresh/metasfresh-webui-frontend#2514]
### Is this a bug or feature request?

Bug

### What is the current behavior?

Being authenticated when you click on the three dots in the console a warning/error is shown. No major impact on UI rendering.

#### Which are the steps to reproduce?

Clicking on the three dots triggers an error/warning in the console

### What is the expected or desired behavior?

There should be no error in console and the case flagged by the error should be considered

**Comment by siemiatj** [comment]
This looks like a good `easy win` so feel free to grab it whenever you'll get blocked on other things or in between the tasks.

**Comment by petrican** [comment]
<img width="923" alt="Screenshot 2020-02-26 at 16 48 51" src="https://user-images.githubusercontent.com/1708561/75355942-ead04a80-58b7-11ea-80e3-aeae7fc8ce4b.png">
DOC
