### ISSUE TITLE
Add keyboard handling in POS

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#252]
1. On HU editor loaded – automatically select first row.
2. Arrow keys in table shall change selection up/down.
3. [Tab] shall move focus from table to Selection attributes first widget and then 2nd, 3rd etc. If last input in Sel attrib focused and [Tab] – go back to table, first element auto-focused.
4. Add shortcut [ctrl]+[s] for "Select all leafs" while on particular row.
5. Add shortcut for main quick action. Shall be same as introduced in #215 .
6. Add shortcut to move to "device button" while in particular input w/ this buttons.

**Comment by metas-mk** [comment]
Tested. Please fix:
6. Add shortcut to move to "device button" while in particular input w/ this buttons.
--> <enter> does not confirm the weight and move weight to input, but shall

Further: Currently 3 <tabs> are needed to get to initially get to first weighing device.
1) is on modal element allows to scroll up/ down
2) is one weight input
3) is on first device
4) is on second device
--> please eliminate the 1)

**Comment by metas-mk** [comment]
Tested weighing device selection.
Works nicely now. Devices can now we tabbed w/ 2 tabs and selected w/ <enter>.
