### ISSUE TITLE
Low prio: implement document attachments

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#256]
Use case:
* open any document, e.g. http://w101.metasfresh.com:8090/window/143/1003511
* pick a file from your file system, drag it and drop it in that window
* the file shall be uploaded

Use the endpoint documented here: https://github.com/metasfresh/metasfresh-webui/issues/118#issuecomment-278275162

**Comment by teosarca** [comment]
doesn't seem to work, or i don't know how to test it.
Can u pls let me know how to test it?

**Comment by damianprzygodzki** [comment]
I saw that there was some issues after merge of two features. Try now, just grab a file, drag over the "sections" part of document window. there should be overlay displayed and if you drop file it should be uploaded.

**Comment by metas-mk** [comment]
Test done. Works nicely with file > 0byte. With empty file gets divided by zero error. Error will be handled in backend task https://github.com/metasfresh/metasfresh-webui/issues/118

**Comment by metas-mk** [comment]
Added to release 4.56.55 (2017-07)
