### ISSUE TITLE
User defined filters in printing queue not working anymore

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#2571]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The user defined filters in printing queue window/540165 are not working anymore; running them has no effect.
https://recordit.co/j7dPCwPRF9
#### Which are the steps to reproduce?
Try and see.
### What is the expected or desired behavior?
Should work.

**Comment by siemiatj** [comment]
Regression from #2532
