### ISSUE TITLE
Changing pages of a window does not update the table content

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh-webui-frontend#2572]
### Is this a bug or feature request?
bug

### What is the current behavior?
- clicking a page, to view different records (ie there are 10000 records and only 20 visible per page) does not update the records

#### Which are the steps to reproduce?

- go to product window (there are multiple pages)
- click page 2, page 3, page 4, etc.

### What is the expected or desired behavior?
- content of a window changes

By pages i refer to this: 
![image](https://user-images.githubusercontent.com/4482210/73746246-6f1e2a80-475d-11ea-8732-cc5af16bf86c.png)

**Comment by cristinamghita** [comment]
@petrican Filtter is buggy as well; not sure if related.
![image](https://user-images.githubusercontent.com/15378036/73762184-80c0fb80-4778-11ea-8fbf-72e471825671.png)
