### ISSUE TITLE
Grid view attributes layout shall respect the Layout and not the Data

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#258]
Follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/192

i.e. shall render all the fields provided in Layout and not only those which were provided when data was fetched.

![image](https://cloud.githubusercontent.com/assets/1244701/22743116/df115972-ee21-11e6-8b55-97f45f0d178b.png)

**Comment by damianprzygodzki** [comment]
Assumption made on start of project. There is no posibility to render "connected to API" widgets without data.
