### ISSUE TITLE
Grid view selection lost when trying to use the scroll bar

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#259]
![image](https://cloud.githubusercontent.com/assets/1244701/22743312/7d115d48-ee22-11e6-87a5-5f855d6f039e.png)

**Comment by teosarca** [comment]
More, the selection is changed even if i am clicking somewhere in the page.... that shall be fixed too

**Comment by damianprzygodzki** [comment]
Scroll bar looks like a bug, or changes in the browser behavior. But selection is always disappearing when we click outside the table.

**Comment by cadavre** [comment]
"click outside the table" is always expected action. It is pattern also used everywhere else in metasfresh. It only shouldn't de-select on moving into Selection attributes or when pressing one of Quick actions (which is obvious).

But scrollbar shouldn't deselect – that's true.

**Comment by chmieludaniel** [comment]
It seems that in modern browsers scrollbar is not visible by default, it's shown only when the user scrolls (at least on OSX). For the browser clicking a few pixels from right edge, is equal to clicking on scrollbar. This makes detecting of click on scrollbar impossible, as it is just an area, very close to right side.

Another thing is that scrollbar of the whole content is not always the same as scrollbar of the table. We'd need to detect clicking on scrollbar on every container.

imho, metasfresh is keyboard navigation friendly, isn't it? What's the point of scrolling down with mouse click, while there is far better way to do it. E.g. using arrows, or scrolling with mouse scroll.

wdyt

**Comment by teosarca** [comment]
Suggestion: as discussed last week, deselect the row only when clicking in the parent container.
I am open on any other suggestion which would have a similar effect (i.e. don't deselect on scrollbar).


@chmieludaniel 

> imho, metasfresh is keyboard navigation friendly, isn't it? What's the point of scrolling down with mouse click, while there is far better way to do it. E.g. using arrows, or scrolling with mouse scroll.

IMHO that would be a big usability drawback. 
Scrollbars are also a conventional indicator that there is more to see...

**Comment by metas-ts** [comment]
@teosarca @metas-lc if you move a task to test *or* if you pick up a task for testing please cheack and make sure that the task is in the release notes.
i'm adding this one now

**Comment by metas-lc** [comment]
Where do i have to select so my line would get unselected?
![modal](https://cloud.githubusercontent.com/assets/16001666/23136030/8045c352-f7a3-11e6-8c37-5a559e179d15.png)

**Comment by damianprzygodzki** [comment]
@Dunkat ?

**Comment by metas-lc** [comment]
was the fix integrated? I didn't notice any difference

**Comment by metas-lc** [comment]
if there was a way to unselect the lines, i would expect to click somewhere in the white space. Maybe i am wrong

**Comment by Dunkat** [comment]
something broke, maybe in another merge, need to check

**Comment by Dunkat** [comment]
Should work now. Just click outside table in the white space.

**Comment by metas-lc** [comment]
IT
* select the line and then select white space => line is deselected OK
* select the line and then change attributes => line is still selected OK
* select the line and then select the vertical scrollbar => line is deselected NOK
* select the line and then select the horizontal scrollbar => line is deselected NOK

**Comment by metas-mk** [comment]
Tested. Works nicely as required.
Retested these cases:
* select the line and then select the vertical scrollbar => line stays selected OK
* select the line and then select the horizontal scrollbar => line stays selected OK
