### ISSUE TITLE
Url gets wrong after pressing New again

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#26]
![image](https://cloud.githubusercontent.com/assets/1244701/18205644/c0ca4f00-712b-11e6-91e4-a7c42e91f523.png)

**Comment by cadavre** [comment]
It's just a static menu, not yet implemented in any matter from API. Hard to call bug something that's far from being even done. :) @teosarca when can we have a conversation about API menu(s) generation. PS Mark will talk to you about our menu idea. :)

**Comment by teosarca** [comment]
ping me on skype chat and we can have it whenever suits you.

**Comment by damianprzygodzki** [comment]
So this should be closed, right? @teosarca could you?

**Comment by teosarca** [comment]
@damianprzygodzki  IMHO no. It shall be closed when it's fixed or when it's implement.

**Comment by cadavre** [comment]
Implemented.
