### ISSUE TITLE
Quick actions were not refreshed after i press browser's back button

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#260]
Test case:
* Wareneingangdispo. => select something
* execute "Receive" quick actions => HU editor grid view is opened
* press browser's Back
* the quick actions were not refreshed and now it's showing quick actions of HU editor

![image](https://cloud.githubusercontent.com/assets/1244701/22743484/f8f77604-ee22-11e6-827a-76b4e0fcdf28.png)

**Comment by teosarca** [comment]
Found another case: the quick actions are not refreshed after the view was refreshed, i.e.
* in HU editor, call "Created material receipt"
* then on same line, call "Reverse"
* an "view fully changed" event was sent to websocket and the view was refreshed
* as a result there are no HUs now
* but the quick actions are displaying the "Reverse" action => NOK => the quick actions shall be refreshed because the selection was changed


![image](https://cloud.githubusercontent.com/assets/1244701/22745878/abb3bc24-ee2a-11e6-9ed1-9d8cb288f660.png)

**Comment by damianprzygodzki** [comment]
Should be fixed with refactor of documentList / modals / filters.

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23260.md
