### ISSUE TITLE
When the attribute is readonly don't show the Device button(s)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#261]
![image](https://cloud.githubusercontent.com/assets/1244701/22744296/ac281560-ee25-11e6-9ef7-abc483e642ff.png)

**Comment by damianprzygodzki** [comment]
Definitely quick fix. To implement.

**Comment by metas-mk** [comment]
Tested. Works. If processed weighing devices are not shown anymore when read-only.

**Comment by metas-mk** [comment]
Release Notes added for 4.56.55
