### ISSUE TITLE
Grid view attributes were queried when there are no rows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#263]
Test case:
* open Wareneingangdispo (receipt schedules)
* select a receipt schedule and receive an HU
* the HUs grid view is opened showing u that one HU
* select the HU and receive it => OK
* select the HU that u just received => now the default action is "Reverse"
* Reverse it
* the HU vanishes from the grid view (leaving the grid view empty) => OK
* but checking the "Network" tab, remark that the frontend is asking about the attributes of that HU which was already vanished => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/22776893/205b4698-eeba-11e6-998b-aef0ae5dfbd6.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* HUs are still displayed after reverse in the grid view, created https://github.com/metasfresh/metasfresh-webui-frontend/issues/330

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090
After reversing the HUs the frontend no longer asks for attributes. See picture below

![network ok after hu reversal](https://cloud.githubusercontent.com/assets/16001442/23106733/7bbbf576-f6fa-11e6-9402-adce35f92d5b.png)

But if there are 2 HUs and I only create material receipt for one of them and then reverse it, I get this in network: 

> layout : 
> {timestamp: 1487539464108, status: 404, error: "Not Found",…}
> error
> :
> "Not Found"
> exception
> :
> "de.metas.ui.web.exceptions.EntityNotFoundException"
> message
> :
> "No document found for documentId=1003000"
> path
> :
> "/rest/api/documentView/540189/4b67ea8b-be78-48f1-88e7-1e82cd44d599/1003000/layout"
> status
> :
> 404
> timestamp
> :
> 1487539464108


This is not OK, right?

**Comment by teosarca** [comment]
> This is not OK, right?

nop, it's not. Frontend was querying for attributes layout of the record which just vanished.

**Comment by teosarca** [comment]
Repeated the test and it's not ok.
Also pls remark on the screenshot below:
* data was loaded, 1 record, id=1002183
* quickActions was called with wrong/not existing selectedIds
* layout was called for non existing record

![image](https://cloud.githubusercontent.com/assets/1244701/23107414/9f83cec4-f705-11e6-98ca-873550063fee.png)

**Comment by metas-rc** [comment]
Results of IT2.

Tested on http://w101.metasfresh.com:8090/

The problem Teo made a screenshot for still persists.


![2 hus step 1](https://cloud.githubusercontent.com/assets/16001442/23174495/3cc766ea-f865-11e6-873e-0c94138e9272.png)

![2 hus step 2 - create material receipt](https://cloud.githubusercontent.com/assets/16001442/23174493/3cbb2c5e-f865-11e6-9c15-4d647c514f4a.png)

![2 hus step 3 - after reverse](https://cloud.githubusercontent.com/assets/16001442/23174494/3cc0f440-f865-11e6-89be-2db3a692acc6.png)


Please check the answer from https://github.com/metasfresh/metasfresh-webui-frontend/issues/377
Maybe it also applies here.

**Comment by damianprzygodzki** [comment]
It seems like fixed by #377

**Comment by metas-rc** [comment]
Based on the comment in https://github.com/metasfresh/metasfresh-webui-frontend/issues/377#issuecomment-281668152:

" No ID should be selected." But here, the already destroyed HU's ID is selected. Please, fix.

**Comment by metas-rc** [comment]
Results of IT3

Tested on https://w101.metasfresh.com:8443

* I wasn't able to reproduce the problem any more. IMO it was fixed.

OK
