### ISSUE TITLE
Included tabs layout is broken

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#264]
![image](https://cloud.githubusercontent.com/assets/1244701/22778681/7ff834c0-eec0-11e6-8857-4fd117231594.png)

**Comment by cadavre** [comment]
Add ellipsis.

**Comment by teosarca** [comment]
... or make sure that tabs like Price or Accounting does not look so "suspended"  :)

**Comment by metas-mk** [comment]
Tested with different Screen dimensions. Works nicely now.

**Comment by metas-mk** [comment]
Add to Release Notes for 4.56.55 (2017-07)
