### ISSUE TITLE
Handling Unit Editor -> Barcode Filtering: should submit with ENTER and TAB

### ISSUE THREAD

**Issue by TheBestPessimist** [metasfresh/metasfresh-webui-frontend#2646]
### Is this a bug or feature request?
FR

### What is the current behavior?

Handling Unit Editor -> Barcode Filtering: can only submit with ENTER.

#### Which are the steps to reproduce?

perform a filter by barcode
press tab: the modal is not submitted (the active element is changed instead)
press enter: the modal is submitted as expected

![image](https://user-images.githubusercontent.com/4482210/76861789-cab3fb80-6865-11ea-84e1-7d3ed8ee540d.png)
![image](https://user-images.githubusercontent.com/4482210/76861832-dc959e80-6865-11ea-9784-709b2e250c8a.png)

### What is the expected or desired behavior?

Tab should also submit this barcode filtering, just like enter does.

**Comment by siemiatj** [comment]
So `press tab: the modal is not submitted (the active element is changed instead)` means it should jump in the barcode input ?

**Comment by TheBestPessimist** [comment]
What i want is pressing tab should be like pressing enter: both tab and enter submit that modal (and the dialog is filtered by the barcode typed there).

what happens right now: tab works like normal tab, ie. it jumps from one html element to the next.
