### ISSUE TITLE
Sidelist refactor

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#267]
Pagination, sorting and filters should be cached.

After huge refactor of document list that was made in need by displaying HU in modals, way of working changed a lot. The sidelist now is the exeptional case of document list and it has to be rebuild too a bit.

The regular functionalities are kept but some of them will be fixed soon.

**Comment by cadavre** [comment]
Sidelist is scheduled for rebuilt. We can add "Pending" here.

**Comment by damianprzygodzki** [comment]
As on #110, remember to fetch sidelist only when opened.

**Comment by cadavre** [comment]
As I'm going to mock Manufacturing process, I'll try to prepare some initial ideas also for sidelist rebuild.

**Comment by damianprzygodzki** [comment]
#88 and #98 looks influencing the new version of that (at least that area of window)

**Comment by metas-mk** [comment]
@cadavre @cadavre thanks. looks nice.
Tested quickly. Please add keyboard control (arrow down, arrow up) for navigation in entries too.

![image](https://cloud.githubusercontent.com/assets/13365687/24975436/ee96d7e8-1fc5-11e7-9d4c-7ec79afeb6b4.png)

**Comment by metas-lc** [comment]
IT
go to reference documents (ctrl+5) use up and down arrows  => you can navigate OK
go to attachments (ctrl+6)  use up and down arrows => you can navigate OK
go to document list (ctrl+4) use up and down arrows => you can't navigate NOK

**Comment by damianprzygodzki** [comment]
@metas-lc it was discussed already with @metas-mk. The ctrl-4 gridview is regular gridview, in gridview we use tab instead of arrows.

**Comment by teosarca** [comment]
if it's a quickfix i would really like to be able to go to first row by pressing DOWN button.
It will be homogenous and will not require user to think about technical stuff like "ahh that's a regular gridview, i shall press tab instead of DOWN".
wdyt?

**Comment by metas-lc** [comment]
quickly checked. Tab is leaving the ctrl-4 menu bar. It selects document-actions

**Comment by metas-mk** [comment]
Checked latest status and test results.
Works as required. Remaining topic arrow down in sidelist grid view will be adressed later. Moving to done.
