### ISSUE TITLE
Wrong viewId when starting the process

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#268]
![image](https://cloud.githubusercontent.com/assets/1244701/22836958/39507200-efc7-11e6-853e-71d4f5607c80.png)

**Comment by metas-mk** [comment]
Tested. Works nicely. Checked with the following case. ViewID is now the needed viewID from Handling Unit editor selection.
![image](https://cloud.githubusercontent.com/assets/13365687/22963088/2b3fa0ea-f351-11e6-83c3-2a3edf076654.png)

**Comment by metas-mk** [comment]
Added to release Notes for 4.56.55
