### ISSUE TITLE
Change frontend URL policy

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#27]
`/window/143/new` - new 143 doc type form
`/window/143/{id}` - open 143 doc type {id} form
`/window/143` - list of 143 doc type

**Comment by teosarca** [comment]
> /window/143/new

yes, but as soon as u get the ID you shall replace the url with /window/143/{id}.
And basically you get the ID right after first commit, so user will see the "/window/143/new" url just for a couple of seconds...

**Comment by damianprzygodzki** [comment]
So theres two possible solutions:
- we just append parameter to url, without changing state (it would be the fastest solution)
- or we should keep consistency in app behaviour, and endpoint `.../new` would be only for create new window, and redirect to `/window/143/{id}` - but then i have to know for 100% that there will be no case, when we want to create new document i.e. in modal, and it will be one and only case when we are able to create new doc.

**Comment by damianprzygodzki** [comment]
> /window/143/new - new 143 doc type form
> /window/143/{id} - open 143 doc type {id} form
> /window/143 - list of 143 doc type

Implemented.
