### ISSUE TITLE
Browser Full-screen initially shows scrollbar

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#270]
Browser Full-screen initially shows scrollbar
Should be enough space for subtabs and 100% height so not show the scrollbar.
Reproduced on Chrome/ windows

![image](https://cloud.githubusercontent.com/assets/13365687/22854016/3d356838-f064-11e6-8ea4-cb92ea32e017.png)

**Comment by cadavre** [comment]
Isn't it browser-related behaviour?

@chmieludaniel needed research.

**Comment by chmieludaniel** [comment]
It is both, browser and platform related. I never see scrollbar on any page by default - even when it is longer than screen - as I use Chrome on OSX
