### ISSUE TITLE
Field selection not re-selectable without loosing focus first

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#271]
Field selection not re-selectable without loosing focus first
Szanario: Window Sales Order. Press on triangle (mouse) to select dropdown for pricesystm. Select an entry. Press triangle again. --> not possible. First the field has to loose focus to be able to be selectable again.

![image](https://cloud.githubusercontent.com/assets/13365687/22854033/db268608-f064-11e6-9bf3-c5ba1eb0a859.png)

**Comment by cadavre** [comment]
@chmieludaniel Going into this?

**Comment by chmieludaniel** [comment]
Cannot reproduce. I think this one is already done. Need confirmation from you @metas-mk

**Comment by teosarca** [comment]
cannot reproduce.
