### ISSUE TITLE
Selected Line visibility in Grid View

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#272]
Selected Line visibility in Grid View
Scenario: New Sales Order. Recording. Saved. Press breadcrumb for Grid View of the Sales order.
When entering grid view it would be great if the detail record that was just left is now visibly selected in grid view.

**Comment by cadavre** [comment]
Breadcrumb doesn't apply previous state (page, ordering, filters), but browsers "Back" shall keep it selected.

**Comment by damianprzygodzki** [comment]
@cadavre imho it is a case when the new item is created, and after that we should select (and here is my question) last opened document? or only last created document?

**Comment by cadavre** [comment]
I re-read @metas-mk comment – you're right @damianprzygodzki .

We might then select **latest** new document. "Latest" because of "what if user created more than one document before going back to gridview".

**Comment by metas-lc** [comment]
IT
(tested on both sales and purchase)
New Order. Recording. Saved. Press breadcrumb for Grid View of the Sales order 
=>the detail record that was just left is now visibly selected in grid view (line is gray) 
OK
