### ISSUE TITLE
Navigation menu vs. Browse complete Tree differences

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#273]
Navigation menu vs. Browse complete Tree differences
Why are entries missing in Navigation dropdown?

![image](https://cloud.githubusercontent.com/assets/13365687/22855505/a6f765a6-f081-11e6-8014-dd44f533a394.png)

**Comment by cadavre** [comment]
AFAIR we had assumption that we don't oversize menu and if there are more than 6 elements – you should separate it into another section.

AFAIK we have max 6 elements displayed.

**Comment by damianprzygodzki** [comment]
Yes, this was limited (property 'childrenLimit' in API URI), because there was assumption to pack the navigation in 2 columns.

We have set 6 as a children limit for this request.

**Comment by teosarca** [comment]
i think we need @metas-mk 's input...

**Comment by metas-mk** [comment]
> AFAIK we have max 6 elements displayed.
Thanks for the explanation. Closing this issue for now, until we tackle the "most used" functionality.
