### ISSUE TITLE
Double open gridview (window | modal) generates double quick actions fetch.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#274]
If gridview open, quick actions fetching should be disabled on select change.

**Comment by metas-rc** [comment]
Results of IT1

I don't know what the initial problem was and how to reproduce it.

But as far as I saw while testing other tasks, the Action handling was correct in http://w101.metasfresh.com:8090 from both single and grid view so I will move this task in done.
