### ISSUE TITLE
None of the menus could be opened when in full screen mode

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#275]
![image](https://cloud.githubusercontent.com/assets/1244701/22879060/db037c86-f1e4-11e6-8447-d281fcfdd692.png)

**Comment by cadavre** [comment]
@Dunkat

**Comment by metas-mk** [comment]
Tested. Works nicely now. Issue solved.

**Comment by metas-mk** [comment]
Added to ReleaseNotes.
