### ISSUE TITLE
Wrong timing when completing a quick input entry

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#276]
Check the screenshot below: remark that PATCHING the values and completing the quick input happens almost at the same time.
This sometimes leads to wrong data because at the "complete" some of the values are not up2date.

Suggestion: pls call the "complete" endpoint AFTER patching the values.

![image](https://cloud.githubusercontent.com/assets/1244701/22880783/3a2d2958-f1ec-11e6-9c0c-7ce6615a4c22.png)

**Comment by metas-mk** [comment]
Quick Test to catch up Queue. Works nicely.

**Comment by metas-mk** [comment]
Created Release Notes.
