### ISSUE TITLE
Processed HU in Material Receipt Workflow

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#277]
### Is this a bug or feature request?
Feature Request.
### What is the current behavior?
When a Handling Unit is processed, this is not visible in HU Hierarchy window.
#### Which are the steps to reproduce?
Open Material Receipt Candidates. Do a material Receipt for an HU. The look and feel of the HU in Grid are same as before.
### What is the expected or desired behavior?
Make it visible that a Handling Unit is processed already (light gray background, boundary between HU?)

**Comment by cadavre** [comment]
Waiting for API.

**Comment by teosarca** [comment]
Backend was implemented. For more info check the backend issue.
NOTE: will be available on next rollout!

**Comment by damianprzygodzki** [comment]
Just loud thinking. Shouldn't we name that property more complex, like `disabled` to be able in future without context disable some row?

**Comment by metas-rc** [comment]
Results of IT1:

Tested on http://w101.metasfresh.com:8090

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23277.md : OK
