### ISSUE TITLE
Don't PATCH when field is readonly (the null case)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#278]
Sometimes the frontend tries to PATCH a document field which is readonly.
When i've observed is that it happens for some lookups which are null.

See the screenshots.
![image](https://cloud.githubusercontent.com/assets/1244701/22899931/4316972c-f235-11e6-9b3b-e64649486387.png)

![image](https://cloud.githubusercontent.com/assets/1244701/22899971/6352edec-f235-11e6-8137-5f13d5efe687.png)

**Comment by metas-lc** [comment]
IT. OK
