### ISSUE TITLE
Breadcrumb and Pencil Field (Value, Documentno) Layout

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#28]
a) "Pencil Field" Should be in same Line as breadcrumb.
b) The Fon size of breadcrumbs is a bit too small. Design had same size as Labels Fontsize.

**Comment by cadavre** [comment]
We already had this discussed. It gonna be changed while implementing menu.

**Comment by metas-mk** [comment]
Yes. Just saw that I didn't create an issue at that time and now created one to have it in mind.

**Comment by cadavre** [comment]
Good. Same with "precision" in numeric fields. It is a few-weeks-back now when it was on our minds and we almost forget it.
