### ISSUE TITLE
Open a single document after process is executed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#280]
At the moment, after a process is executed, me might get following result:
```
{
	"pinstanceId":1232077
	,"error":false
	,"viewWindowId":540189
	,"viewId":"759aadd0-8706-4636-a90b-ae747dc1be85"
}
```
(see http://w101.metasfresh.com:8081/swagger-ui.html#!/process-rest-controller/startProcessUsingGET )

which means, that frondend shall open the view identified by viewId and viewWindowId.

All good. Now here it comes the change.
We want to be able to also open a single document in some cases, so i suggest to change the response JSON as follows:
* introduce following properties for opening a single document:
** openDocumentWindowId
** openDocumentId
* rename following properties to be consistent:
** viewWindowId - rename it to "openViewWindowId"
** viewId - rename it to "openViewId".

e.g. of single document opening
```
{
	"pinstanceId":1209386,
	"error":false,
	"openDocumentWindowId":540323,
	"openDocumentId":"1001349"
}

```
e.g. of view opening (remark that we kept viewWindowId and viewId for now, but those are deprecated!)
```
{
	"pinstanceId":1209387,"error":false,
	"viewWindowId":540189,
	"viewId":"8bf5ad72-ce04-4ad7-9198-4bf0a1646319",
	"openViewWindowId":540189,
	"openViewId":"8bf5ad72-ce04-4ad7-9198-4bf0a1646319"
}

```

**Comment by teosarca** [comment]
required by https://github.com/metasfresh/metasfresh-webui/issues/121

**Comment by teosarca** [comment]
NOTE: atm the API is not rolled out on w101

**Comment by damianprzygodzki** [comment]
@teosarca should i pull it to master? or wait on API rollout?

**Comment by teosarca** [comment]
hmmm, good question!
let the pull request open for now.
Btw, when needed, can i also merge it to master?

**Comment by damianprzygodzki** [comment]
Can we stay with single responsibility? I have anything against you doing merges, but in developing and investigating it is good to be always conscious, aware and sure "what i did" with master :)

**Comment by teosarca** [comment]
yup, u are right. i will ping you when i will have the API

**Comment by metas-lc** [comment]
this task was tested with https://github.com/metasfresh/metasfresh-webui/issues/121. 
OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23121.md
