### ISSUE TITLE
Remove margin from wrapper modal to make 0-padding inside

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#281]
### Is this a bug or feature request?

Enhancement.

### What is the current behavior?

Around 30px of unnecessary margin on left and right in f.e. "HU editor".

#### Which are the steps to reproduce?

Go to Wareneingangdisposition, open HU modal.

### What is the expected or desired behavior?

No margin.

**Comment by cadavre** [comment]
Also adjust "select all" and pagination margin to fit "filters" and "quick action".

**Comment by metas-mk** [comment]
The test is done. HU Editor is now marginless. Added to Release Notes.
