### ISSUE TITLE
Implement attachments list in Actions menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#282]
![image](https://cloud.githubusercontent.com/assets/1244701/22925788/b2495800-f2b2-11e6-9fd0-16477498697e.png)

**Comment by teosarca** [comment]
NOTE: more documentation about endpoints will come

**Comment by teosarca** [comment]
The endpoints are:
* get all attachments: http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getAttachmentsUsingGET

* delete one attachment: http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/deleteAttachmentByIdUsingDELETE

* download one attachment: http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getAttachmentByIdUsingGET

* upload an attachment (already existing): http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/attachFileUsingPOST

**Comment by metas-rc** [comment]
Results of IT1
* Attached documents can be uploaded, deleted, and are all displayed when the document is maximized.
* NOK: The attached documents are not displayed at all in gridview, when we have the same document selected.

**Comment by metas-rc** [comment]
There are still problems with the attachments in grid view:

The attachments can be seen, opened and deleted from single view. I have 3 pics attached to the document.
Went to gridview, selected the same document, checked attachments.
1. They are visible now: OK

![attachments visible from grid view](https://cloud.githubusercontent.com/assets/16001442/23095468/d62dd4fe-f612-11e6-9e27-7abb3a9fe1ca.png)


2. But when I try to delete one I get:
![attachment error on delete](https://cloud.githubusercontent.com/assets/16001442/23095473/eaaabdac-f612-11e6-8989-2ab9d59219d6.png)


3.And when I try to open one I get:

![tryin to open attachment from gridview](https://cloud.githubusercontent.com/assets/16001442/23095480/feec0fbe-f612-11e6-85d0-7eaae02b3313.png)

**Comment by metas-rc** [comment]
Results of IT 3:

* Delete attachment from drig view works now. OK
* Open attachments from grid view still doesn't work. Same error : http://w101.metasfresh.com:8081/rest/api/documentView/143/undefined/attachments/3

**Comment by metas-rc** [comment]
Results of IT4

Tested on http://w101.metasfresh.com:8090


* All the attachments are displayed, they can be deleted and can be opened both from single view and grid view. OK
