### ISSUE TITLE
provide build and version info for metasfresh-webui-frontend

### ISSUE THREAD

**Issue by metas-ts** [metasfresh/metasfresh-webui-frontend#292]
### Is this a bug or feature request?

It's a feature request: We need an easy way to display version info in the webui-frontend.

The reason is that we ran into problems with a wrong version being deployed. It took us some time to notice this.

### What is the current behavior?

We already have something similar in the metasfresh-api server, but it's not enough:

when you call `http://metasfresh-webui-api:8080/info` you currently get:
```json
{
  "build": {
    "ciBuildNo": "17",
    "ciBuildTag": "jenkins-metasfresh-webui-gh942-metasfresh-17",
    "ciBuildUrl": "https://jenkins.metasfresh.com/job/metasfresh-webui/job/gh942-metasfresh/17/",
    "ciJobName": "metasfresh-webui/gh942-metasfresh"
  }
}
```
This information was put into the webui-api by jenkins

### What is the expected or desired behavior?

what i think we should have is

**to be implemented in the metasfresh-webui-api**

extend the result returned by `http://metasfresh-webui-api:8080/info` to look like this
```json
{
	"metasfresh-backend": {
		"ciBuildNo": "1234",
		"ciBuildTag": "jenkins-metasfresh-mastet-metasfresh-1234",
		"ciBuildUrl": "https://jenkins.metasfresh.com/job/metasfresh/job/master/1234/",
		"ciJobName": "metasfresh/master"
		...possible further key-value pairs (just string:string)
	},
	"metasfresh-api": {
		"ciBuildNo": "17",
		"ciBuildTag": "jenkins-metasfresh-webui-gh942-metasfresh-17",
		"ciBuildUrl": "https://jenkins.metasfresh.com/job/metasfresh-webui/job/gh942-metasfresh/17/",
		"ciJobName": "metasfresh-webui/gh942-metasfresh"
		...possible further key-value pairs (just string:string)
	  }
}
```

**to be implemented in the metasfresh-webui-frontend**

If the "info"-URL is invoked on the webui-frontend, then show a nice window that gets the json from the webui-api and displays it grouped like this:

* metasfresh-backend
  * ciBuildNo: 1234
  * ciBuildTag: jenkins-metasfresh-master-metasfresh-1234
  * ciBuildUrl: https://jenkins.metasfresh.com/job/metasfresh/job/master/1234/
  * ciJobName: metasfresh/master
  * ...possible further key-value pairs

* metasfresh-api
  * ciBuildNo: 17
  * ciBuildTag: jenkins-metasfresh-webui-gh942-metasfresh-17
  * ciBuildUrl: https://jenkins.metasfresh.com/job/metasfresh-webui/job/gh942-metasfresh/17/
  * ciJobName: metasfresh-webui/gh942-metasfresh
  * ...possible further key-value pairs

**plus** show similar information for the **metasfresh-frontend** itself.
This additional information will be placed in the frontend by jenkins. 
Please let us know how it needs to look like.
Sugestion: e.g. we could let jenkins create a txt file such as "version.info" with key-value pairs, e.g.
```
ciBuildNo: 9876
ciBuildTag: jenkins-metasfresh-master-metasfresh-webui-frontend-1234
...possible further key-value pairs
```
..and you would need to read the file and insert the result line-by-line
But feel free to tell us how it should look like.

Note that you could start already, even before we don't succeed to make the "metasfresh-webui-api" changes in `http://metasfresh-webui-api:8080/info`. It would (just) mean that the info in the window would look like

* build
  * ciBuildNo: 17
  * ciBuildTag: jenkins-metasfresh-webui-gh942-metasfresh-17
  * ciBuildUrl: https://jenkins.metasfresh.com/job/metasfresh-webui/job/gh942-metasfresh/17/
  * ciJobName: metasfresh-webui/gh942-metasfresh

* metasfresh-webui-frontend
  * ciBuildNo: 9876
  * ciBuildTag: jenkins-metasfresh-master-metasfresh-webui-frontend-1234
  * ...possible further key-value pairs which jenkins baked into the "version.info" file

**Comment by teosarca** [comment]
@metas-ts a quick solution would be:
* let jenkins create dist/version.json (which shall contain the frontend version infos)
* change the .htaccess to not forward request in case of this file

wdyt?

**Comment by metas-ts** [comment]
i guess that would be fine..idk enough about the frontend, but i could put such a file inside the frontend dist

**Comment by teosarca** [comment]
that would be great.
from there i can sort it out, alone or with some help. we just need to do a small change to .htaccess to not forward requests of version.json to index.html

**Comment by metas-ts** [comment]
@teosarca we now hava a file info.json in the dist tar.gz which resembles the spring boot `/info`json

**Comment by teosarca** [comment]
@metas-ts thanks

**Comment by cadavre** [comment]
Closing due to internal resolving.

**Comment by teosarca** [comment]
@metas-ts  wdyt, can we close this one?

**Comment by metas-ts** [comment]
@teosarca i don't see why

**Comment by metas-ts** [comment]
@teosarca aah ok..yes..i was hoping for a window that also shows the other components' versions, but you are right, that's not what the issue is about.
