### ISSUE TITLE
Enforce a bigger minimum width for attributes panel

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#293]
NOTE: my screen resolution is 1600x900

![image](https://cloud.githubusercontent.com/assets/1244701/22942301/a42a8bd8-f2f1-11e6-8a3e-091961cadca9.png)

**Comment by teosarca** [comment]
UPDATE: pls take care of it only if quick fix

**Comment by teosarca** [comment]
another thing: this is how it looks when selecting a line without attributes.
I think the attributes panel shall keep the same size.

![image](https://cloud.githubusercontent.com/assets/1244701/22942416/29dfc55e-f2f2-11e6-8fc5-25e0e53cd256.png)

**Comment by damianprzygodzki** [comment]
I am closing it because of duplicate #295
