### ISSUE TITLE
Leave Location editor with no entry

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#294]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
One cannot leave the Location editor without entering data and leaving the Location untouched.
#### Which are the steps to reproduce?
Press on Location "Edit" Button. Press next to Dropdown to collapse it or press <esc>. Error pops up.
### What is the expected or desired behavior?
Be able to leave the Editor without entering data.
![image](https://cloud.githubusercontent.com/assets/13365687/22945204/a9791fbc-f2f3-11e6-9192-6c60aeb0de4a.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101 & cloudit:
* Press Edit button in Location, press Edit button again or Done to leave Location editor: Error pops up, NOK

**Comment by chmieludaniel** [comment]
@metas-dh, I cannot reproduce this error. Could you please provide particular view (window, document)

**Comment by damianprzygodzki** [comment]
@chmieludaniel check issue from reference. Window 540196, document 1000003, field M_AttributeSetInstance_ID.

It is problem with:
```
Uncaught TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
```
Attributes.js:125

**Comment by metas-mk** [comment]
Tested. Is now possible to leave the location editor w/o editing anything and pressing <esc> or clicking mouse outside the location editor or pressing editor button. BUT ...
... once you've clicked inside the location editor you don't get out anymore w/ mouse click, outside the editor, nor the button. You have to focus in a field and then cam press <esc> to get out again. 
--> Not solved. reopening.

**Comment by teosarca** [comment]
@chmieludaniel  why the "integrated" label was removed?

NOTE: the "integrated" label shall be sticky. once integrated, nobody shall take it out.

**Comment by chmieludaniel** [comment]
Correct me if I'm wrong:

The 1st solution was integrated, but then other bug was found, so the issue was reopened. Hnce, the bug is not solved - not integrated.

**Comment by teosarca** [comment]
if that's the case, and there were reasons to postpone the TODO part,
i think it's better to create a follow-up task and close this one mentioning what was delivered here.
wdyt?

but, nevertheless, pls don't remove the "integrated" label because that's the only way for us to check if a task was "partially" integrated.

**Comment by metas-mk** [comment]
Tested. Works nicely now, like required. Closing.
