### ISSUE TITLE
Scroll Up/ Down in Pagination is swapped

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#296]
### Is this a bug or feature request?
Bug ... but some say so, others say so ;-)
### What is the current behavior?
In Grid View if you use keyboard to "turn the pages" you may opress page-up/ page-down. Currently page-up is to get to the next higher page in number. This is counter intuitive. It should be similar to scrolling-down to get next- further information.
#### Which are the steps to reproduce?
Try it in any Grid View with more than 1 page.
### What is the expected or desired behavior?
Swap the next page (page-down) and previous page (page-up) keyboard shortcuts.
![image](https://cloud.githubusercontent.com/assets/13365687/22964284/175797f2-f358-11e6-84c6-f88bbaafc5c7.png)

**Comment by damianprzygodzki** [comment]
@Dunkat

**Comment by metas-dh** [comment]
Results of IT

tested on w101: page-up/ page-down with keyboard in grid view
* page-up => newt lower page in number (like scrolling up): OK
* page-down => newt higher page in number (like scrolling down): OK
