### ISSUE TITLE
Wrong viewDocumentIds provided when calling a process from quick actions

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#299]
See the screenshot.
Note that I even don't know from where that viewDocumentId is coming....

![image](https://cloud.githubusercontent.com/assets/1244701/22969424/219baad6-f377-11e6-94b9-50bf1792e2d3.png)

**Comment by metas-rc** [comment]
Results of IT1
Tested on http://w101.metasfresh.com:8090
The ViewDocumentIDs were correct for all documents I checked.
