### ISSUE TITLE
"Saved" element next to sidelist button

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#30]
What is this element for? Did not see that in design yet. Is this only for development purpose?

**Comment by cadavre** [comment]
It is new. As we don't have regular "Save" button anywhere and auto-save is default behavior we need to indicate to user that his/her work is being saved. It would be critical error to not provide such information. Also if API call will get delayed it will animate as 'saving' and as soon as API call will be finished it will pop up as "Saved" again. We need to keep users comfortable while they're working. :)

**Comment by teosarca** [comment]
this task relates with #13
