### ISSUE TITLE
Move https://github.com/Dunkat/react-shortcuts to metasfresh

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#307]
agreed with @cadavre to:
* wait 1-2 weeks until our pull requests are integrated to master
* if not, move the repo to metasfresh

**Comment by cadavre** [comment]
Sorry, removing "High prio" label as it it false.

**Comment by cadavre** [comment]
Looks like we have PR accepted:
https://github.com/avocode/react-shortcuts/commits/master

**Comment by teosarca** [comment]
nice!

**Comment by Dunkat** [comment]
change in shortcut library accepted, please make npm install before run project

**Comment by teosarca** [comment]
Checked, fixed.
