### ISSUE TITLE
Disable process parameters while "start" endpoint is called

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#310]
Case:
* start a process with parameters
* fill the params
* Press Start: this can take a while and to avoid confusion and other issues:
** disable all process fields
** disable the "Start" button
** let the "Cancel" button enabled, so we would allow user to cancel it

**Comment by cadavre** [comment]
Sounds resonable. Aren't you just affraid about active "Cancel"? `Request` may go to server, it may be processed but when user will cancel in the middle of `Response` from the server – it won't be actually canceled – it may extremely confuse user.

**Comment by teosarca** [comment]
agree... let's disable the cancel too,
and later figure out how to actually cancel it.

**Comment by cadavre** [comment]
@teosarca when we will switch to async processes – it will resolve by itself, because it will be easier to manage process state. :)

**Comment by teosarca** [comment]
nailed it! :)

**Comment by metas-rc** [comment]
Results of IT1

Tested on http://w101.metasfresh.com:8090/

When starting a process, all its parameters and its OK and Cancel buttons are read-only : OK
