### ISSUE TITLE
Scrollbar missing on LU/ TU Level in HU Editor

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#313]
### Is this a bug or feature request?
Bug
### What is the current behavior?
The LU-TU-CU Editor panel is not visible (scroll bar is out of screen) horizontally scrollable when LU or TU Level selected.
#### Which are the steps to reproduce?
Open HU Editor in Material receipt workflow. Select the LU Level. No Scrollbar to move table right.
### What is the expected or desired behavior?
Show the scrollbar in "100% height" modal screen, still at bottom but visible. Move the scrollbar from CU level to bottom but visible too)

![image](https://cloud.githubusercontent.com/assets/13365687/23012145/fbbe315e-f424-11e6-8b2d-a3546429d86c.png)

![image](https://cloud.githubusercontent.com/assets/13365687/23012175/262fc498-f425-11e6-8ca4-91e8358f9ff5.png)

**Comment by teosarca** [comment]
i think this one is related to #311

**Comment by metas-mk** [comment]
Tested. The scrollbar is now visible in modal window w/o modal window scroll down.
