### ISSUE TITLE
Quick action button layout is broken on smaller resolution

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#315]
Pls "glue" those 2 "sub components" together and make sure they are not wrapped.

NOTE: pls ping me if is not a hotfix.

![image](https://cloud.githubusercontent.com/assets/1244701/23014703/b6ee1846-f438-11e6-87fc-865df9786bcb.png)

**Comment by teosarca** [comment]
Reopening because now the button is to small.
If possible,
* pls allow it to be bigger in order to have the whole text displayed.
* don't fix the width, but enforce some bigger maximum

![image](https://cloud.githubusercontent.com/assets/1244701/23059144/b3b69a90-f500-11e6-9b6d-edb248f1d7b4.png)

**Comment by cadavre** [comment]
Ellipsis looks like a good solution here, we also don't want 500px buttons (even if theres place) because it simply looks ugly. Couldn't you possibly shorten then texts? I believe "EUR" instead of "EUR-Tauschpalette Holz" will work.

I also think we can remove 'tick' icon to give more space. This icon is saying nothing here.

**Comment by teosarca** [comment]
sorry but yes we want, the most important part of that text is after ellipsis.
user shall see on one eye shot, precisely what he will receive.

I think @metas-mk will totally agree with me on this.

**Comment by metas-mk** [comment]
agree, but what we could do is
a) take out the tick icon (as sew suggested)
b) have 2 rows on button with small font top line "receive to" and second line same fon as currently.
wdyt?

**Comment by cadavre** [comment]
1. Remove tick icon.
2. Remove "Receive to ..." and leave just "To: ...".
3. Shorten "EUR-..." to "EUR".

Wdyt?

**Comment by metas-mk** [comment]
1. ok
2. ok.
3. the "EUR-Tauschpalette" is the name of the packing material. this name is choosen by the user company and is variable. we cannot shorten that.

**Comment by metas-mk** [comment]
OK. Let's do the following to shorten the button.
Drop the name of LU Packing material. Example:
Instead of: Receive to EUR-Tauschpalette Holz x 46 G2 x 20 kg
have: 46 G2 x 20 kg

in 95% of all cases, the LU Packing Material is always the same.

**Comment by teosarca** [comment]
agree for now

**Comment by teosarca** [comment]
Changed the caption and took out the LU packing info, as discussed above.

@Dunkat  pls just take out that icon:
![image](https://cloud.githubusercontent.com/assets/1244701/23065628/2a7dd4cc-f51f-11e6-8e96-7d35a722b042.png)

**Comment by metas-mk** [comment]
Tested. Works nicely. Add to Release Notes.
