### ISSUE TITLE
Quick actions are not refreshed when opening the modal HU editor

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#317]
Case:
* Receive some HUs
** the modal HU editor opens
** default action is "Create material receipt" 
** Call "create material receipt"
** HUs are refreshed, their state changed from Planning to Active
** The default action displayed is "Reverse" => OK!
** close the modal HU editor

* now u are back to receipt schedules grid view
* for the same line, receive some HUs again
** **HU editor opens but the default action displayed is 'Reverse' which is NOK.**
** click on second line and then back to first line => the default quick action changed to "Create material receipt" which is OK

NOTE:
* it does not happen all the time
* it seems that in some cases the quick actions were not requeried or they were queried with wrong params

![image](https://cloud.githubusercontent.com/assets/1244701/23015352/2094de40-f43b-11e6-9d65-02eb87bfb142.png)

**Comment by metas-rc** [comment]
Results of IT 
Tested on http://w101.metasfresh.com:8090

https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23317.md OK

**Comment by metas-rc** [comment]
I stress tested this with several schedules and several times with the same schedule. The actions were always correctly updated.
