### ISSUE TITLE
Product window - Subtab Prices

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#32]
M_Product_ID content and isActive Flagnot shown in data row.

**Comment by cadavre** [comment]
Can you provide more details:

* Which window ID?
* Are this fields received in browser from API?

**Comment by metas-mk** [comment]
Is in all true-false/ yes-no fields in grid/ table view.

**Comment by damianprzygodzki** [comment]
Fixed by 7bf3793f74c520177ef9d9943008a4121d293768

**Comment by teosarca** [comment]
Hi guys,
If we render it as text, then we need to provide translations...
