### ISSUE TITLE
Quick input's mandatory=false not respected

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#322]
See screenshot.

Also, pls note this task was trigged by https://github.com/metasfresh/metasfresh-webui/issues/129 .
At that task i've changed that packing instructions field (M_HU_PI_Item_Product_ID) shall no longer be mandatory and i've got into this issue.

![image](https://cloud.githubusercontent.com/assets/1244701/23019642/07c68f88-f44c-11e6-9b13-e90193b8b4b2.png)

**Comment by cadavre** [comment]
Sorry, but you described case, provided OK screenshot and doesn't described the issue. :D So what is NOK here?

**Comment by teosarca** [comment]
when i am pressing enter i got a frontend error that some mandatory fields were not filled.
so in my case, the field is the packing instructions which is OK to be null because we defined as not mandatory.

**Comment by metas-rc** [comment]
See: https://github.com/metasfresh/metasfresh-webui/issues/129

**Comment by metas-rc** [comment]
Results of IT1:
Tested on http://w101.metasfresh.com:8090
Same test as for metasfresh/metasfresh-webui#129
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23129.md OK
