### ISSUE TITLE
Provide login credentials in request body

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#323]
See http://w101.metasfresh.com:8081/swagger-ui.html#!/login-rest-controller

Instead of providing them as parameters, POST then in request body as follows:
```
{
  username:"someuser",
  password:"pass"
}

```

Backend task: https://github.com/metasfresh/metasfresh-webui/issues/133

**Comment by teosarca** [comment]
New API available: http://w101.metasfresh.com:8081/swagger-ui.html#!/login-rest-controller/authenticateUsingPOST

don't use the parameters but only the request body.

**Comment by metas-lc** [comment]
IT. OK
