### ISSUE TITLE
HUEditor displays HUs which are destroyed

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#330]
![2017-02-16 16_49_35-metasfresh](https://cloud.githubusercontent.com/assets/18696715/23029900/4e23bf9e-f46c-11e6-900b-bdb137077d88.png)
Found in IT for https://github.com/metasfresh/metasfresh-webui-frontend/issues/263
hint=> HUEditor is not reacting to websocket "fullyChanged" event
### Is this a bug or feature request?
Bug
### What is the current behavior?
After using the reverse action in HU Editor, the HUs are marked as destroyed, but not refreshed accordingly in the HU Editor. They are still displayed, plus the msg about no detail rows; and all quick actions are disabled.
#### Which are the steps to reproduce?
* open Wareneingangdispo (receipt schedules)
* select a receipt schedule and receive an HU
* the HUs grid view is opened showing u that HU
* select the HU and receive it => OK
* select the HU that u just received => now the default action is "Reverse" 
* use "Reverse" => HUs are still displayed, no quick action can be selected
### What is the expected or desired behavior?
the HU vanishes from the grid view (leaving the grid view empty) after "Reverse"

**Comment by damianprzygodzki** [comment]
Backend issue.

**Comment by teosarca** [comment]
note for backend: make sure JSONDocumentViewResult.result:
* contains empty list (and exported to JSON) when there is actually NO data
* is null (and not exported to JSON) when the data was not queried

**Comment by teosarca** [comment]
fixed on backend as discussed. dev tested and it works now.

**Comment by metas-rc** [comment]
Results of IT 1:
Tested on http://w101.metasfresh.com:8090/
https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23330.md OK
