### ISSUE TITLE
Debug/fix: if a PATCH operation fails some wrong calls are performed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#331]
disclaimer: i cannot give u a reproductible case because it happened while developing something, so you will have to mock the "PATCH call" and return HTTP 500 instead.

My case:
* open some process with parameters
* Clicked the IsSaveLUTUConfiguration which failed with 500.
* after that, frontend issued a call to /rest/api/window/<process id here>/... and we are in process panel ?!?

Pls ping me if is not a quick fix.

![image](https://cloud.githubusercontent.com/assets/1244701/23046626/42345fda-f4b3-11e6-8517-8389d1e4651f.png)

**Comment by metas-lc** [comment]
IT. OK. couldn't reproduce anymore
