### ISSUE TITLE
Random quickActions call while in process parameters

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#332]
Case:
* in process parameters
* i clicked on parent container
* a random call to quickActions was issued (i guess was trying to refresh the quick actions of the grid view behind?!).

Pls ping me if is not a quick fix.

![image](https://cloud.githubusercontent.com/assets/1244701/23046793/6c677e1c-f4b4-11e6-86b1-cb6ae2059b1e.png)

**Comment by damianprzygodzki** [comment]
I really tried to reproduce it, but cannot. The same refId + refType + windowType, and clicking outside receive hus modal doesnt change selection, and there is no quick actions call.

It may be related with browser too or environment, so please lets test it on w101 deployed one, or master.metasfresh.jzapp.io. And then provide detailed info about case.

- link
- what was selected before opening modal with Receive HUs
- from where was process triggered (nav menu or quick actions)
- what is the id that quick actions are calling for

**Comment by teosarca** [comment]
Ok, but let's keep this task open and everybody shall have it in their scope.
I am sure the issue is somewhere there hidden and will popup sooner or later.

**Comment by cadavre** [comment]
@teosarca then someone will probably create new issue one way or another. ;)

Cannot reproduce = closed issue. We don't want mess in issues, please.
