### ISSUE TITLE
Grid view layout: honor supportNewRecord and newRecordCaption

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#345]
See screenshot.
If supportNewRecord is set and true render the new record button using "newRecordCaption" property,
else don't show the button.

![image](https://cloud.githubusercontent.com/assets/1244701/23068938/3f55b7ac-f52e-11e6-8cf0-03952da57089.png)

**Comment by teosarca** [comment]
backend task: https://github.com/metasfresh/metasfresh-webui/issues/138

**Comment by cadavre** [comment]
Lovely!

It is provided as well for tabs? Would be great to have it unified.

**Comment by teosarca** [comment]
@cadavre  good point, but atm it's provided only from grid view.

For tabs it's a bit tricky because there the "supportNewRecord" is dynamic and:
* shall be provided on "get data"
* shall be provided along with "PATCH responses" when it's changed.

**Comment by teosarca** [comment]
but btw, atm the flag is not available. Wait to take out the metasfresh-turn and then....

**Comment by teosarca** [comment]
API available.

**Comment by damianprzygodzki** [comment]
Isn't it filling the #14 functionalities?

**Comment by metas-lc** [comment]
IT
OK: 
- "New" button is shown only if supportNewRecord is set and true 
- the button has teh same name as "newRecordCaption" property 
- tested most used windows => works fine, as above
- tested with different languages => buttons have the right language
