### ISSUE TITLE
Advanced Edit isActive Flag 100%

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#35]
In Advanced Edit (example opened from GridView), the isActive Flag is rendered in 100% witdh. Should not be. Must stay small and compact like flags.

**Comment by damianprzygodzki** [comment]
@metas-mk
For which window?

I am trying to recreate this issue, but i can't find any layout with Switch input.

**Comment by teosarca** [comment]
Guys, i think i found something.
Below are 2 screenshots... one when it's wrong and one when it's ok.
I guess the "slider" is wrongly layouted when it's disabled.


![image](https://cloud.githubusercontent.com/assets/1244701/18355673/88f9885e-75f2-11e6-8946-cb24aad1e1d5.png)


![image](https://cloud.githubusercontent.com/assets/1244701/18355697/a0841f5c-75f2-11e6-8269-ab61f8cad2c8.png)

**Comment by damianprzygodzki** [comment]
Oh i see the bug actually. Could you give me uri to that upper one?
