### ISSUE TITLE
Strange pulse effect in Subtab Gridview

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#350]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
When selecting one row in a subtab going back to the main view, the wrong line is pulsed.
#### Which are the steps to reproduce?
Go to Business Partner Window. Subtab Location w/ multiple rows. Select the first line. Advanced edit. Dont't edit anything. Done. The last row is pulsed in the main view.
### What is the expected or desired behavior?
When pulsing, then pulse the correct line. When not changing anything, then in my pov no line shall be pulsed.
![image](https://cloud.githubusercontent.com/assets/13365687/23101721/827ef2ba-f69a-11e6-8abb-1d9a99d77dc8.png)
![image](https://cloud.githubusercontent.com/assets/13365687/23101722/87ea9a4c-f69a-11e6-8442-6255e272e95b.png)

**Comment by metas-lc** [comment]
IT
OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23350.md
