### ISSUE TITLE
New Button action in modal leads to background change

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#351]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
Press the new Button leads to new window underneath modal overlay.
#### Which are the steps to reproduce?
Try in Material Receipt Window. Open Handling Unit Editor (Receive). Press new and watch the background. Close window and you will get back in the unexpected environment.
### What is the expected or desired behavior?
Don't allow New in modal overlay if it has an effect on underlying window.
![image](https://cloud.githubusercontent.com/assets/13365687/23102283/e5085640-f6a6-11e6-9a16-b176c8a16975.png)

**Comment by teosarca** [comment]
NOTE: Even if this issue will be automatically solved as a side effect of #345 (because in this case we are providing supportNewRecord:false), as Mark said, we really shall make sure that nothing from modal affects the underlying window.

**Comment by damianprzygodzki** [comment]
It is because two modals are opened on themselves. It is next next reason that we should refactor RawModal and Modal.

**Comment by damianprzygodzki** [comment]
It has to be solved by #345. It is not "issue". The modal has the same behavior as regular window, there was never implemented any other way of creating new document as a redirection. So it relay 100% on API.

I was proposing in #333 to solve the approach about opening double modals at the same time, and it was just quickfixed.
