### ISSUE TITLE
Wrong sitemap breadcrumb

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#353]
(See screenshot)
Sitemap's breadcrumb shall ALWAYS be /Sitemap

![image](https://cloud.githubusercontent.com/assets/1244701/23103117/55f71578-f6be-11e6-95d2-8b9b987c01d1.png)

**Comment by metas-mk** [comment]
Tested. Bug Fixed. Works nicely now. Add to Release Notes.
