### ISSUE TITLE
view websocket notifications: handle "changedIds"

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#355]
NOTE: this is a follow-up of #211 

We introduced new property to the JSON event called "changedIds". When set, contains an array of document IDs which changed in the grid view.

When frontend gets that array it shall refresh ONLY those rows which are identified by provided IDs.
If the rows are not present in current page, the frontend shall do nothing.

To easily fetch only some rows from backend we introduced following REST API: http://w101.metasfresh.com:8081/swagger-ui.html#!/document-view-rest-controller/getByIdsUsingGET

Test case (where are are already using this feature): https://github.com/metasfresh/metasfresh-webui/issues/150 , i.e.
* open Material Receipt Candidates
* Receive some HUs (create material receipt for those too!)
* back in Material Receipt Candidates, QtyMoved changed shall be updated.

**Comment by teosarca** [comment]
Blocks https://github.com/metasfresh/metasfresh-webui/pull/152

**Comment by damianprzygodzki** [comment]
I can't find out how to fetch data from that endpoint.

This is what say Swagger:

![screen shot 2017-03-24 at 07 25 18](https://cloud.githubusercontent.com/assets/5701744/24282995/40a83c6a-1063-11e7-9023-7749076308ad.png)
![screen shot 2017-03-24 at 07 25 29](https://cloud.githubusercontent.com/assets/5701744/24283000/454ddc02-1063-11e7-9e2d-3b8bbaed3e14.png)
(The ids parameter is lost)
![screen shot 2017-03-24 at 07 25 36](https://cloud.githubusercontent.com/assets/5701744/24283005/4e84efe0-1063-11e7-84a3-8168ff88edfd.png)
And API missing it too.

But, even if i add this parameter:
![screen shot 2017-03-24 at 07 25 44](https://cloud.githubusercontent.com/assets/5701744/24283017/636dbffe-1063-11e7-84a7-ee0e79631ed4.png)
The ids is missing.
![screen shot 2017-03-24 at 07 25 58](https://cloud.githubusercontent.com/assets/5701744/24283019/690cf966-1063-11e7-9288-c572cb88c37d.png)

**Comment by teosarca** [comment]
note: shall be fixed on next rollout

**Comment by teosarca** [comment]
Note to IT: test together with https://github.com/metasfresh/metasfresh-webui-api/issues/151#issuecomment-296625363 . Use the test cases from there.

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-api/issues/151
