### ISSUE TITLE
Error in Report "Revenue business partner

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#358]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* When trying to run the "Revenue business partner" jasper process I get an error page saying: 

> Whitelabel Error Page
> 
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Mon Feb 20 08:43:27 CET 2017
> There was an unexpected error (type=Bad Request, status=400).
> Failed to convert value of type [java.lang.String] to required type [int]; nested exception is java.lang.NumberFormatException: For input string: "null"

#### Which are the steps to reproduce?
* Go to the report "Revenue business partner" 
* Select DateFrom = 01.01.2017
* Select DateTo = 19.02.2017
* Checkbox on true
* Start
(These parameters should lead to a report with existing data)

### What is the expected or desired behavior?
* The report should be opened with no error.

* How the parameters look like: 

![image](https://cloud.githubusercontent.com/assets/16001442/23117226/5dddbcee-f757-11e6-82cd-57b51eec08eb.png)

* After pressing start I get :
http://w101.metasfresh.com:8081/rest/api/process/null/null/print/Umsatzreport+Gesch%C3%A4ftspartner.pdf

**Comment by metas-lc** [comment]
OK: Revenue business partner Report worked fine => new page with the pdf opened
