### ISSUE TITLE
Handling Unit Double click Icon changes data underneath overlay

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#364]
### Is this a bug or feature request?
Bug.
### What is the current behavior?
Doubleclick on overlay loads details data underneath overlay.
#### Which are the steps to reproduce?
Open Material Receipt Candidates. Select a receivable line. Handling Unit Editor opens. Double click the Palette Icon. The Data Record underneath the overlay changes and does not allow to make a receipt anymore.
### What is the expected or desired behavior?
Don't change the data underneath modal overlay.
![image](https://cloud.githubusercontent.com/assets/13365687/23124245/4e3e004a-f76c-11e6-9727-3b04dd31a2ca.png)

**Comment by teosarca** [comment]
i think it's related to #351

**Comment by damianprzygodzki** [comment]
It is not. The case for that issue was never discussed.

The regular behavior after double click is to navigate in main window to item.

What we should do after double click on rows in modal?

**Comment by teosarca** [comment]
> What we should do after double click on rows in modal?

nothing

**Comment by metas-lc** [comment]
IT. OK: nothing happens if you double click in HU modal window
receipt created successfully
