### ISSUE TITLE
List widgets shall not call /dropdown each time when it's clicked

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#37]
... and they shall cache the result of the /dropdown in component's internal state.
Also they shall rely and reset that state based on field's "lookupValuesStale" property (which u get on /commit and /data).

**Comment by teosarca** [comment]
Required by https://github.com/metasfresh/metasfresh-webui/issues/20

**Comment by cadavre** [comment]
Implemented on backend side.
