### ISSUE TITLE
Error when trying to change Partner in Order

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#373]
### Is this a bug or feature request?
* Bug
### What is the current behavior?
* Having the partner, location and user set, try to change the partner by replacing the current name with another.
* NOK:  The value in the partner field is the text you types
* NOK: The invoice partner and the 2 locations remain the same as before
#### Which are the steps to reproduce?
* Create a bestellung for a partner (Metasfresh AG)
* Go to the partner field, select all, type "t"
* You get a dropdown with the partner  "Test ..."
* Select this partner
* NOK: The partner field still contains only the text "t"

* NOK: Invoice partner and the 2 locations remain unchanged (will be done by callouts, if the C_BPartner_Id is set correctly)

* Somehow, the value of the C_BPartner is sent to the C_BPartner_Location. Please check the attachment below: 

![c_bpartner value sent instead of location](https://cloud.githubusercontent.com/assets/16001442/23134081/2203ec6c-f79c-11e6-9e4e-2eb48d7a0643.png)

### What is the expected or desired behavior?
* When C_BPartner is selected, its C_BPartner_ID should be sent accordingly.

**Comment by metas-lc** [comment]
IT. Repeated the steps:
- created new purchase order
- add a bpartner (e.g. Metasfresh AG) 
=> bpartner, location and invoice bpartner + location set OK
- select bpartner's name and start writing t
- on the dropdown select bpartner test
=> bpartner, location and invoice bpartner + location updated to Test's data OK
Repeated the text using x button to remove the bpartner - set another bpartner 
=> works the same OK

- create a new sales invoice, use bpartner metasfreshTest, then change it with quicktest04
=> the user and location does not change NOK!
(for other cases works)

**Comment by cadavre** [comment]
Closing due to revamp in #600 .
