### ISSUE TITLE
Sitemap: don't enforce any limit on how many results to be fetched

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#375]
When in sitemap and querying for menu, don't enforce any limit (not for fetching, nor for searching).
Here we shall see everything.

![image](https://cloud.githubusercontent.com/assets/1244701/23139404/0860a57a-f7b5-11e6-9644-effb817d4ddb.png)

**Comment by Dunkat** [comment]
@teosarca how can I get depth without any limit? If I sent empty depth param I've got only first level.

**Comment by teosarca** [comment]
hmmm.... have to check, but for now u can call it with '100' :)

**Comment by Dunkat** [comment]
thanks :) as I see depth=0 seems working

**Comment by teosarca** [comment]
ahh good point, better, thanks !

**Comment by metas-lc** [comment]
IT: 
root depth is now 0 OK
question: what is the first call for? it says dept 10 and children limit 6. Is that OK? or we want 0 too?

![sitemap](https://cloud.githubusercontent.com/assets/16001666/23303170/33d7b8f4-fa9b-11e6-8dea-f6879aaa6b2d.png)

**Comment by Dunkat** [comment]
it's for navigation menu
