### ISSUE TITLE
grid view: when initially clicking on first row, the second one is first selected

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#377]
Case:
* open Material Receipt Candidates
* click on the first row

Ramark:
* for <1s second row was quickly selected and then first.

![image](https://cloud.githubusercontent.com/assets/1244701/23145536/af16fcbc-f7d7-11e6-925d-604aaa43db69.png)

**Comment by damianprzygodzki** [comment]
It is strictly related to #349. And it is not able to fix without loosing part of functionality.

It happens because when we want to navigate with keyboard, on table focus we need to select first item. I can't differ if it is click or focus. So i see one solution, to change current behavior, and after focusing on table in case of selecting first row, click the arrow down and then select first element.

It will change behavior in single document tabs, document view, document view in modal.

**Comment by metas-rc** [comment]
We decided to always have the first row selected initially ( when a window is opened)  and after any processing.

**Comment by damianprzygodzki** [comment]
that assumption still is not fixing that question. What about when someone deselect item and then wants to get inside table with keyboard? Do we want to change ‘deselecting` to `selecting first row` ?

**Comment by damianprzygodzki** [comment]
So we assumed to **do not select first row on focus**

**Comment by metas-lc** [comment]
IT
when i click on the first row, only that one is selected . OK
question: when we open a window in grid mode, we want the first row selected or not? (currently is not selected)

**Comment by cadavre** [comment]
@metas-lc https://github.com/metasfresh/metasfresh-webui-frontend/issues/377#issuecomment-281668152

**Comment by metas-rc** [comment]
Note: I talked with Mark and he announced me the idea of having the first row selected was dropped. Instead, no ID should be selected.
In case you press Tab and then the arrow down, the first ID should be selected.

**Comment by metas-rc** [comment]
Was the requirement about Pressing tab and then arrow down for selecting the first row implemented in any task?
Otherwise, just let me know and I'll create a new feature request issue.
Thanks

**Comment by damianprzygodzki** [comment]
It is working. There is no need to create issue. Just focus on a table (we assumed to not indicates user about that selection to) and press arrow up or down.

**Comment by metas-mk** [comment]
@damianprzygodzki I assume that ruxi is exactly talking about that. she tried to focus on table w/ [tab] but focus did not happen.

**Comment by metas-rc** [comment]
Right. I didn't know about the part with focusing. 

Tested again and it works like this.

**Comment by damianprzygodzki** [comment]
For gridview (i.e. `/window/143`):
- 5 times clicked tab (there are some focusable elements before like filters, so it depends of amount of buttons over table) and then arrow, let you select first row
For single doc page (i.e. `/window/143/1003929`):
- 8 times pressed tab (through all this fields before) and then arrow let you select first row

**Comment by metas-mk** [comment]
Quick test. Works as described by Damian. Future requirements will be done in other tasks, but not prioritized atm.
