### ISSUE TITLE
Arrow key not working in dropdown

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#382]
### Is this a bug or feature request?
Bug
### What is the current behavior?
When tabbing to a field w/ is the dropdown, the selection via arrow down/ up is not possible anymore.
#### Which are the steps to reproduce?
Try window Purchase Order. Tab to Price System, try arrow.
### What is the expected or desired behavior?
Make the arrows usable again.
![image](https://cloud.githubusercontent.com/assets/13365687/23160822/36acfa82-f828-11e6-8c08-69639473c9c9.png)

**Comment by metas-lc** [comment]
Created new task for the scrollbar. Moving this task to done
https://github.com/metasfresh/metasfresh-webui-frontend/issues/416

**Comment by metas-lc** [comment]
docu https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23382.md
