### ISSUE TITLE
Shortcut for Batch entry space not usable when in input field

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#383]
### Is this a bug or feature request?
Bug/ feature Request.
### What is the current behavior?
Shortcut for Batch entry [ctrl]space not usable when in Business Partner input field. [ctrl]u is possible.
#### Which are the steps to reproduce?
Try in Sales Order Window first field. Select BPartner.
### What is the expected or desired behavior?
Make [ctrl]space usable too.
![image](https://cloud.githubusercontent.com/assets/13365687/23161108/1ccf6f4a-f829-11e6-8bcc-f31408d52042.png)

**Comment by cadavre** [comment]
Please use square brackets for keys, like [ctrl] not < ctrl > because it's converted to HTML!

@metas-mk

**Comment by cadavre** [comment]
@chmieludaniel can we browse through whole project and look for places where we should add `dataShortcuts=true`? Because this issue will be going back and back again.

**Comment by chmieludaniel** [comment]
Not sure, where do we actually need this. I asked @Dunkat if this option might be enabled by default, and disable it if needed. wdyt?

**Comment by cadavre** [comment]
Also thought about it. +1 but need input from @Dunkat about how it will affect project. AFAIK we don't have single-letter shortcuts (like [R]) and only [ctrl]+[...] shortcuts so we won't affect input entering of data.

**Comment by metas-mk** [comment]
> Please use square brackets for keys, like [ctrl] not < ctrl > because it's converted to HTML!

Ah, sry. Yes, will do that in future. Thx.

**Comment by metas-lc** [comment]
IT. OK https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23383.md
