### ISSUE TITLE
User Filter Criteria Bug

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#389]
### Type of issue

Bug 

### Current behavior
* I inserted a new user criteria for Sales Orders, named  "DocumentNo and BPartner" for AD_User_ID = 100. It is visible in webui, but when I click on it nothing happens.

![image](https://cloud.githubusercontent.com/assets/16001442/23165716/2ffb2920-f846-11e6-81f9-6ef3d5cd94cc.png)

* Also, after I click on it, if I click on the other filters afterwards they are not opened.

* If I close the filters and open again, I can access the old ones : "Bpartner and date ordered" and "Default"
### Expected behavior
* It should be opened and usable.
### Steps to reproduce

* Open Sales Orders, Click on "Select other filter", click on the filter "DocumentNo and BPartner".

**Comment by metas-rc** [comment]
Followup for https://github.com/metasfresh/metasfresh-webui/issues/162

**Comment by damianprzygodzki** [comment]
Blocked by #392

**Comment by metas-mk** [comment]
Further Info:
![image](https://cloud.githubusercontent.com/assets/13365687/23172026/ae9e61a8-f854-11e6-9b3a-ffa690bcfcfa.png)

**Comment by metas-rc** [comment]
Results of IT1 

Tested on http://w101.metasfresh.com:8090/

My filter criteria works correctly now. I also can use the other user filter criterias with no problems.
