### ISSUE TITLE
can't use advanced edit

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#391]
### Type of issue

Bug 
### Current behavior
right click on a line in a subtab (e.g. window Preisliste, subtab preislisten version) - nothing happens
### Expected behavior
advanced edit and delete to appear and work as before
### Steps to reproduce
open Preisliste window, select a pricelist that has pricelist verison
right click on pricelist version => nothing happens

**Window:** enter window ID or Navigation menu step-by-step.
(happens everywhere)
**Entity:** enter dockument ID or steps to reproduce environment.

/or/

**Link:** link to w101.

**Pre-filled data:** which inputs shall be filled before?

**Comment by metas-rc** [comment]
Further Info:

![image](https://cloud.githubusercontent.com/assets/1244701/23180102/e70e480e-f878-11e6-9902-2401ed97a3d1.png)

**Comment by Dunkat** [comment]
Fixed by #393

**Comment by damianprzygodzki** [comment]
@Dunkat reverted

**Comment by damianprzygodzki** [comment]
Fixed by a5030e2b948559377bef11bf3baa8703b4f86e3d.

**Comment by metas-lc** [comment]
IT: advanced edit is back. OK
