### ISSUE TITLE
Filters are not respecting mandatory property

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#392]
### Type of issue

Bug

### Current behavior

No error info and allowing to patch filters not filled despite mandatory property.

### Expected behavior

It should be validated.

### Steps to reproduce

Each not filled mandatory field.

**Comment by metas-lc** [comment]
IT
repeated testcase from https://github.com/metasfresh/metasfresh-webui-frontend/issues/389 
didn't add bpartner or document no in filter "DocumentNo and BPartner"
got message: "Mandatory filters are not filled!

**Comment by metas-mk** [comment]
Yes, that's ok. This Task was only to prohibit the usage of empty mandatory fields. Issue closed.
