### ISSUE TITLE
ShipmentSchedule: Cannot read property 'map' undefined 

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#393]
### Type of issue

Bug

### Current behavior
Window opens without data. Browser refresh shows the data.
### Expected behavior
Open window w/ data already visible w/o need to refresh.
### Steps to reproduce
**Window:** 500221
**Entity:** Grid View. Go to Sales Order window. Create a new Sales Order. Complete the sales Order. Open Action menu. Referenced documents, open Lieferdisposition/ Shipment Schedule. The window opens empty.

![image](https://cloud.githubusercontent.com/assets/13365687/23175171/ded913ea-f85e-11e6-9013-f8aefdfc648a.png)

**Comment by damianprzygodzki** [comment]
Reopening due to breaking process modal

**Comment by damianprzygodzki** [comment]
Fixed by a5030e2b948559377bef11bf3baa8703b4f86e3d

**Comment by metas-dh** [comment]
Results of IT 1 

tested on w101
* open Lieferdisposition/ Shipment Schedule from Action button in sales order: shipment schedules are displayed correctly: OK
* open Shipment from Action button in Shipment Schedule: shipment is displayed correctly: OK
