### ISSUE TITLE
grid view: page and sort parameters are not considered

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#399]
Test Case:
* open any view, e.g. http://w101.metasfresh.com:8090/window/143
* so will get something like: http://w101.metasfresh.com:8090/window/143?viewId=364c63f6-2dbd-466f-8178-2a01f1a9acce&page=1
* change URL's page parameters (e.g. from 1 to 5) => NOK, not considered and page=1 is back
* add/change URL's "sort" param (e.g.  &sort=-DocumentNo ) => NOK, not considered

Now a real life example, why this is annoying:
* open any view, sort by some columns, move to some other page than first
* in another browser tab, logout => to simulate the session expired
* on first tab try to refresh
** u are asked to login
** u are back to your view, but on page one and without any sorting

**Comment by metas-dh** [comment]
Results of IT 1

tested on w101
* https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23399.md: OK
