### ISSUE TITLE
grid view: show maximum limit hit indicator

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#401]
When fetching a view data, we introduced 2 new properties in the result:
* queryLimit: <integer, max rows which are allowed to be fetched> // present only if available
* queryLimitHit: true // present if the maximum limit was hit (i.e. view size >= queryLimit)

If the query limit was hit we need to show this information to user.
I would suggest to be displayed as follows: at page bottom, after "Total items 300", we shall write (in red) that the limit was hit, i.e. append "(limited)" text.

![image](https://cloud.githubusercontent.com/assets/1244701/23209984/3d9fc464-f904-11e6-82ef-e452cbfaa878.png)

Backend task: https://github.com/metasfresh/metasfresh-webui/issues/173

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23173.md
