### ISSUE TITLE
Optimum Chrome Browser Window size for 1920x1080

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#402]
### Type of issue
Buf
### Current behavior
w/ Screen resolution 1980x1080 and window/ bottom menu bar, the browser shows a vertical scrollbar.
### Expected behavior
Don't show the scroll bar.
### Steps to reproduce
Open any grid view window.
![image](https://cloud.githubusercontent.com/assets/13365687/23212413/ee0d09f4-f906-11e6-9b4d-07a19f7ffa9c.png)

**Comment by damianprzygodzki** [comment]
From quick research, it looks like checkbox icon pushes height of single rows. Important: **please, check the reason to do not allow the row growing in case that we are going to have one extra row**

**Comment by metas-lc** [comment]
IT: for screen resolution 1920x1080 and windows bottom menu bar, the vertical scroll bar does not appear. OK
