### ISSUE TITLE
Wrong viewId used when running "Create material receipt" using keyboard shotcuts

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#404]
Test case:
* receipt candidates
* select a line and receive some HUs
* while first HU is selected, press CTRL+U
* => ERROR, "No selection". Inspecting the call i saw that the process instance was created with the viewId of the underlying view (i.e. receipt schedules) instead of viewId of HUs view (see screenshots above).

Screenshot: running "Create material receipt" using keyboard CTRL+U shortcut:
![image](https://cloud.githubusercontent.com/assets/1244701/23214375/22798e28-f917-11e6-88a5-b17aa9a55a5d.png)

Screenshot: running "Create material receipt" by clicking the button:
![image](https://cloud.githubusercontent.com/assets/1244701/23214401/3eb8d850-f917-11e6-9f9e-2a0d8770cefc.png)

**Comment by metas-lc** [comment]
IT. OK: https://github.com/metasfresh/metasfresh-documentation/blob/master/_tests_collection/Testcase_%23404.md
