### ISSUE TITLE
Date parametes don't have the right time

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#406]
### Type of issue
* Bug

### Current behavior
* When a date range filter is used (I cannot choose the time , only the date), the left limit is one day before my inserted value. Created backend issue for this: https://github.com/metasfresh/metasfresh-webui/issues/177

* When a date range filter is used (I cannot choose the time , only the date), the timestamps I see in the request are not the right ones

### Expected behavior
* When I insert date range I expect the valueFrom to be the exact date I insert with hour 00:00 and the dateTo to be the exact date I insert with value 23:59.

### Steps to reproduce
* Go to Sales Order, click the filter by Date Ordered
* Select January 3 as dateFrom and February 1 as dateTo
* Check the request: 
https://cloud.githubusercontent.com/assets/16001442/23223190/077e584e-f933-11e6-93d0-bf78ae722f6a.png

* Date from is January 2  22: 00: 00  and dateTO is February 1 21:59:59

*Hint (from Teo): This could be a TimeZone issue

**Comment by damianprzygodzki** [comment]
I believe that it is not a bug, just a expected behavior. We decided to use UTC format with offset applied to time. @teosarca should we change the date format to not relative?

**Comment by teosarca** [comment]
hmmm not sure if i got it right, but:
* if the widget type is Date then the frontend shall send only the date, with H,M,S=0 (maybe TZ too)
* if the widget type is DateTime => send the full date+time as discussed
wdyt?

**Comment by damianprzygodzki** [comment]
AFAIK there is no format like YYYY-MM-DD Z, and i can't parse just part of a date.

>if the widget type is Date then the frontend shall send only the date, with H,M,S=0

But i'm sending that, that's why dates are with UTC offset, because for different time zones 00:00:00 in utc is for example 22:00:00.

**Comment by teosarca** [comment]
i think u are right....
let's see what our testing team will pop out :)

**Comment by teosarca** [comment]
to testing team:
* pls test this together with backend task: https://github.com/metasfresh/metasfresh-webui/issues/177
* pls check how the filter parameters are sent in Request payload
* and also pls check how the parameters are sent back from server, in Response body (preview tab)

**Comment by cadavre** [comment]
I'm just looking at how it works: real today is 23.02.2017.

When I select today: 23.02.2017 – 23.02.2017
When I select yesterday: 22.02.2017 – 22.02.2017

All works as expected.

What can be done?
1) Take care of timezones and finally implement user preferences when he/she can set proper one that will be respected.
2) Backend shall take care of dates and use always timezone same as it is set in database so 0:00 will always mean 0:00.

Both – mf turn.

**Comment by metas-rc** [comment]
The remaining issues will be solved in https://github.com/metasfresh/metasfresh-webui/issues/177

**Comment by teosarca** [comment]
Hi guys,

I've debugged this case. Here are my findings.
NOTE: i am focusing only on "date from".

1. Set date to "2017-01-03"
* frontend sends the request as "2017-01-02T22:00:00.000Z" (note: i am in GMT+2)

![image](https://cloud.githubusercontent.com/assets/1244701/23277132/82dabf04-fa15-11e6-8305-89dc8540a928.png)


2. Backend receives "2017-01-02T22:00:00.000Z"
* it converts to "Mon Jan 02 23:00:00 CET 2017" (note: server is running in GMT+1)
* because it's date (and not date+time) it truncates to "2017-01-02 00:00:00.0"
* sends back to fontend: "2017-01-02T00:00:00.000+01:00"
* and frontend displays it
![image](https://cloud.githubusercontent.com/assets/1244701/23277301/02755954-fa16-11e6-9208-8df9395dfa97.png)



---------
Given that result, it become clear for me that we will need an endpoint which will provide server's timezone.
Frontend shall fetch the timezone on login and it shall use it when sending dates back to server.
I will create a follow-up task for this case.

**Comment by metas-rc** [comment]
Please, check Teo's screen shots. IT failed

**Comment by damianprzygodzki** [comment]
![screen shot 2017-02-27 at 15 23 15](https://cloud.githubusercontent.com/assets/5701744/23364797/c47b8338-fd00-11e6-9316-fec2386270e2.png)

The #419 task has `Integrated` label, the front end is working as expected. @teosarca 's screeshots are outdated.

**Comment by metas-rc** [comment]
Tested again on https://w101.metasfresh.com:8443

Step 1: 

![broken date 1](https://cloud.githubusercontent.com/assets/16001442/23368398/6509c052-fd16-11e6-98f7-9425c0c41099.png)


Step 2: 

![broken date 2](https://cloud.githubusercontent.com/assets/16001442/23368403/69ea5762-fd16-11e6-9769-7ccd0f00141c.png)


And now with February 27: 

![date broken feb 27 1](https://cloud.githubusercontent.com/assets/16001442/23368481/ab5641a2-fd16-11e6-8b13-154ccd5ca398.png)


![date broken feb 27 2](https://cloud.githubusercontent.com/assets/16001442/23368484/af311b3a-fd16-11e6-81f4-ec9e07e8dc8c.png)

**Comment by metas-rc** [comment]
Please, fix.

**Comment by damianprzygodzki** [comment]
![screen shot 2017-02-28 at 10 24 31](https://cloud.githubusercontent.com/assets/5701744/23399324/207a2122-fda0-11e6-9379-035b9ec3ae1b.png)

Should be working as you expected.

**Comment by metas-lc** [comment]
tested together with https://github.com/metasfresh/metasfresh-webui/issues/177
