### ISSUE TITLE
Filters bug. "" sent instead of null

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#409]
### Type of issue

* Bug 

### Current behavior
* When usinf filters, if parameters are not set, the frontend sends "" instead of null
### Expected behavior
* When the parameters was not set, the backend expects null.
### Steps to reproduce
* Go to window Billing Candidates ( for example) open the filter, apply it.
* => NOK:  I get this error: 

> {timestamp: 1487845632422, status: 500, error: "Internal Server Error",…}
> error
> :
> "Internal Server Error"
> exception
> :
> "java.lang.NumberFormatException"
> message
> :
> "For input string: """
> path
> :
> "/rest/api/documentView/540092"
> status
> :
> 500
> timestamp
> :
> 1487845632422

![image](https://cloud.githubusercontent.com/assets/16001442/23255471/5ee9f480-f9c4-11e6-9bda-af30fbdf17f0.png)

**Comment by metas-lc** [comment]
IT. OK: bug for "" instead of null does not appear anymore
