### ISSUE TITLE
moving scrollbar on arrow key in dropdown

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#416]
### Type of issue

Bug

### Current behavior
use arrow key in a dropdown that contains lots of data. The scrollbar dows not move (up/down) so i cannot see what i'm selecting
### Expected behavior
scrollbar shall follow my selection in dropdown
### Steps to reproduce
1. go to Product window and select a product (single view)
2. select Statistics Group field 
3. move in dropdown with arrow keys => the scollbad does not move to allow me to see the selection

**Window:** enter window ID or Navigation menu step-by-step.
140
**Entity:** enter document ID or steps to reproduce environment.
1000001

**Link:** 
http://w101.metasfresh.com:8090/window/140/1000001

**Comment by metas-lc** [comment]
![scroll](https://cloud.githubusercontent.com/assets/16001666/23262306/ee4aa0e8-f9e2-11e6-8267-0ee2742edc3c.png)

**Comment by cadavre** [comment]
@metas-lc please follow issue template and fill required fileds!

Missing: "Window" + "Entity" /or/ "Link" + "Pre-filled data" !

**Comment by metas-lc** [comment]
done

**Comment by metas-mk** [comment]
Tested. Works nicely now. The scrollbar moved together w/ focussed entry now when arriving the boundary. Closed.
