### ISSUE TITLE
Frontend shall always send dates using server's timezone

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#419]
Follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/406#issuecomment-282109062 . Please read there why we ended with this task ;)
Backend will be implemented by https://github.com/metasfresh/metasfresh-webui/issues/183
------

When logging in, frontend shall fetch the server's timezone by calling "GET /userSession". See http://w101.metasfresh.com:8081/swagger-ui.html#!/user-session-rest-controller/getAllUsingGET .

Frontend shall always send dates using that timezone.

**Comment by teosarca** [comment]
Update: changed the endpoint to provide the timezone in ISO8601's format, i.e. +/-hh:mm

**Comment by damianprzygodzki** [comment]
We assume to change data format to:
`2013-02-08 09:30:26.123+07:00  # +-HH:mm`

**Comment by metas-lc** [comment]
IT wait for https://github.com/metasfresh/metasfresh-webui-frontend/issues/406

**Comment by damianprzygodzki** [comment]
> damianprzygodzki commented 4 days ago
We assume to change data format to:
2013-02-08 09:30:26.123+07:00 # +-HH:mm

It should be actually `YYYY-MM-DDTHH:mm:ss.SSSZ`

**Comment by metas-lc** [comment]
tested together with https://github.com/metasfresh/metasfresh-webui/issues/177
