### ISSUE TITLE
Session timeout w/ Modal window opened

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#424]
### Type of issue
Bug or missing Feature ;-)
Not a high priority!
### Current behavior
When the user has an opened modal window and leaves it open and session timeout occurs, then after re-login, the user gets redirected to the modal window which is empty then and receives an error message.

### Expected behavior
Avoid the error message and empty modal window. If easiest for now just open the underlying window w/o the modal window. And the user can start from the beginning.

### Steps to reproduce
Open Material Receipt Candidates window. Receive a line. Wait for session timeout.
**Link:** http://w101.metasfresh.com:8090/window/540196
![image](https://cloud.githubusercontent.com/assets/13365687/23303834/a838b086-fa96-11e6-9fc6-737ab5029bf9.png)

**Comment by teosarca** [comment]
@metas-mk i think that's a backend issue.
* Have u called /rest/api/cacheReset in meantime?
* or was it a server restart in meantime?
Asking because that would explain... see https://github.com/metasfresh/metasfresh-webui/issues/35

**Comment by teosarca** [comment]
note to IT:
* moved to testing again
* if u want to quickly simulate the session expired, just open another webui browser tab and logout from there

**Comment by metas-lc** [comment]
IT
1. open receipt candidates, select a line
2. receive HUs - start
=> HU Editor opens
3. open another webui browser tab and logout from there
4. come back to your tab, click randomly 
=> session expired
5. login back => HU Editor is still there, no errors, you can continue to create receipt
