### ISSUE TITLE
Refresh problem: Quick action still displayed after changing view

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#425]
### Type of issue

Bug

### Current behavior

* If I am in a window and have a line selected and it has quick actions, the actions are still displayed even if I move to another window.
### Expected behavior
* The component should be refreshed
### Steps to reproduce
* Go to Receipt Candidates, select one of them:

![image](https://cloud.githubusercontent.com/assets/16001442/23304749/251f45ee-faa4-11e6-9689-f9d8a3e5fb93.png)

Go to the Home button, open Sales Order. NOK: The action is still displayed:

![image](https://cloud.githubusercontent.com/assets/16001442/23304875/c0e13d2a-faa4-11e6-9187-f3ed191c566e.png)

**Comment by teosarca** [comment]
Suggestion: I think, when opening a grid view, one of the first things u need to do (besides other important things :) ) is to clear the quick actions. Then let the quick actions react on selection changes.

**Comment by metas-rc** [comment]
Results of IT 1

Tested on https://w101.metasfresh.com:8443

The quick actions are now cleared when I move from a window to another. OK
