### ISSUE TITLE
Modal inside modal.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#429]
### Type of issue

Feature request

### Current behavior

Now when we want to open modal (for example after process button click) inside another modal (i.e. Advanced Edit) the content from process is replacing content of advanced edit.

### Expected behavior

After closing one modal (process) we need to go back to another (advanced edit)

.

@cadavre should we just cover one with another?

**Comment by cadavre** [comment]
@damianprzygodzki isn't it already implemented?

**Comment by damianprzygodzki** [comment]
Never was, for crying out loud.

**Comment by cadavre** [comment]
So far all cases while we needed "modal over modal" are covered with "connected" and "not connected" modals. Closing as resolved.
