### ISSUE TITLE
ShipmentSchedule: Only displayed after "No data" showing up

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#433]
### Type of issue
Bug
### Current behavior
"No data" page is shown for a split second, then the actual data is displayed
### Expected behavior
"No data" should only be displayed if there actually is no data; if data exists, show that directly.
### Steps to reproduce
* Go to Sales Order window. Create a new Sales Order. Complete the Sales Order. 
* Open Action menu. Referenced documents, open Lieferdisposition/ Shipment Schedule. 
=> The window shows the "No data" page for a split second, then the shipment schedules are displayed

**Comment by teosarca** [comment]
Suggestion: imho,
* when opening the grid view, instead of no data we shall display nothing or some "Loading..." text
* when the rows were fetched from the endpoint, we shall display the rows or the "no data" message.

**Comment by damianprzygodzki** [comment]
@cadavre what should we do here? Shouldn't we start with #130? Or just quick-fix it?

**Comment by cadavre** [comment]
This is a part of #130 . Postponing since #130 is resolved.

**Comment by teosarca** [comment]
@cadavre  i don't think it's part of #130.  Just DON'T show the "no data" label if nobody tried to load the data yet.
Actually it's pretty similar with https://github.com/metasfresh/metasfresh-webui-frontend/issues/425#issuecomment-282290657 .

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* tested with newly created sales order and already existing sales orders, opening shipment schedules from Actions button:  "No data" is not shown anymore, the shipment schedules are displayed right away
