### ISSUE TITLE
filter in Material Receipt Candidates does not work

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#435]
### Type of issue

Bug 

### Current behavior
 streckengeschaft in Material Receipt Candidates dos not work and gets stuck 
### Expected behavior
streckengeschaft filter shall start when you select apply. Shall not freeze. No errors
### Steps to reproduce
1. go to Material Receipt Candidates window
2. select other filter
3. choose streckengeschaft => see error in console +  you cannot deselect it (only if you refresh the page)

**Window:** 540196

**Link:** http://w101.metasfresh.com:8090/window/540196?viewId=b5bd3af0-b969-413c-b2de-20e49c5aec68&page=1

**Comment by metas-lc** [comment]
![filter](https://cloud.githubusercontent.com/assets/16001666/23317714/3cc365fc-fad8-11e6-93f5-7f897e4ba129.png)

**Comment by metas-mk** [comment]
Tested. Works now. Filter is evaluated and only the filtered data is shown. No error message.
