### ISSUE TITLE
In some cases, when editing String fields a PATCH it's sent after each key press

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#436]
### Type of issue

Bug

### Current behavior
In some cases, did not find a pattern yet, when editing a String field, frontend:
* automatically sends a PATCH request
* field focus it's lost.

So if i have to type some value there, after each letter i have to pick on the field again.

### Expected behavior
Shall behave as normal, PATCH shall be sent on focus lost.
Field focus shall not be lost.

### Steps to reproduce
* open KPIs window
* create a new KPI or better use this one: http://w101.metasfresh.com:8090/window/540326/1000001
* add a new line
* try to edit "Name" or "Elasicsearch field path" fields

![image](https://cloud.githubusercontent.com/assets/1244701/23333920/506814e8-fb9d-11e6-94be-69805ef7e9c5.png)

**Comment by damianprzygodzki** [comment]
Fixed. The case was, if in modal was first Switch widget, than it focused itself, because some old implementation of autofocus first field.

Additionaly, the keyboard support is added.

**Comment by metas-lc** [comment]
IT
used same KPI as in steps to reproduce. Added a new line => editing "Name" or "Elasicsearch field path" fields worked fine. Fields did not lost focus
