### ISSUE TITLE
Not saved indicator for records

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#437]
### Type of issue
Feature request

### Current behavior
The user does not recognize if something she/ he has recorded has been saved in the backend. When saving, then a gray and green line occurs during saving as save indicator. As soon as the save process is finished in the background the indicator disappears.

### Expected behavior
When a user opens a window and the data is not saved yet, then the save indicate shall be shown in red color. As soon as save has happened then the already existing behavior kicks in again.

### Steps to reproduce
As example. Open A Sales Order Window and start recording.  As long as not all mandatory fields are filled, the save process is not possible.

**Comment by metas-mk** [comment]
Raised to high Priority because we need a solution for unsaved/ dangling records.

**Comment by teosarca** [comment]
See:
![image](https://cloud.githubusercontent.com/assets/1244701/23398118/fefab60c-fda3-11e6-9b94-d0d7ab3c9d81.png)

**Comment by metas-mk** [comment]
Tested w/ Product window. Initially saved status: false. Edited 2 mandatory fields (1 remaining untouched). saved status: false. edited the remaining mandatory field, saved status: true.
Works as required. Closed.

**Comment by metas-mk** [comment]
@damianprzygodzki thanks ... but ... no thanks ;-)
![image](https://cloud.githubusercontent.com/assets/13365687/23677978/866ba748-0382-11e7-83e6-602fac2511cd.png)

we have a very beautiful save indicator w/ gray and green movement and for "not saved" it could just look terrific if that's then a static thin red line between first save try until saved.

**Comment by metas-dh** [comment]
Results of IT 2
tested on w101

* when editing a window and the data is not saved yet, a thin static red line is displayed in document header: OK
* when editing was done and the data is saved, the grey/green line movement is displayed in document header: OK
(tested in sales & purchase order, with editing bpartner field & product field in orderline)
