### ISSUE TITLE
Delete popup layout issues

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#438]
![image](https://cloud.githubusercontent.com/assets/1244701/23333956/bb6725fe-fb9d-11e6-8c8d-10c115ccf277.png)

**Comment by metas-dh** [comment]
Results of IT 1

tested on w101

* Delete popup layout, with right click: OK, looks fine
* Delete popup layout, with ctrl+y: OK, looks fine
* Click Delete: line is deleted: OK
* Click Cancel / X: nothing happens: OK
