### ISSUE TITLE
Image Widget from Attachment in User Window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#442]
### Type of issue
Feature request

### Current behavior
No possibility to show Images/ Photos in WebUI.

### Expected behavior
Create an image widget which allows showing Images/ Photos. Widget shall be able to show selected Image from record attachment. In future, we will have requirements that show small images of the responsible/ assigned users instead of their whole name (e.g. the new drag and drop swimlane functionality for opportunities.

**Comment by damianprzygodzki** [comment]
Where can i find some usage example? Do we have that widget type used in doc windows? And what API will return here? Will it be the URL in value of widget or ID of attachment?

**Comment by cadavre** [comment]
@damianprzygodzki we have this already implemented afaik by @chmieludaniel .

**Comment by cadavre** [comment]
#228 plus META-406 in Jira.

**Comment by damianprzygodzki** [comment]
@cadavre we have implemented something another. Input for image files. Here @metas-mk talks, as far as i understood about widget for displaying image, static, without changing it.

**Comment by cadavre** [comment]
So it should be the same (it's still Image type afaik) but if "read-only" don't display buttons next to it.

**Comment by damianprzygodzki** [comment]
For me ok.

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by teosarca** [comment]
Hmm, seems this one was not added to Test lane... so i am not sure if it was tested or not.
Adding it now.

**Comment by metas-lc** [comment]
was already tested with other tasks about the photo panel. OK
