### ISSUE TITLE
KPI Number Indicator w/ comparator

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#444]
### Type of issue
Feature request

### Current behavior
No D3JS Number indicator found, that only compares 2 Numbers w/ each other.

### Expected behavior
Target KPI. Possibility to have a KPI Number Indicator
Example:
Orderlines today
2570 (-27)

Orderlines 7 Days
9720 (-27)

**Comment by teosarca** [comment]
@metas-mk  in case it's only that i think d3js it's not needed at all :)

**Comment by metas-mk** [comment]
Works as required. Closing.
