### ISSUE TITLE
Error indicator for fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#446]
### Type of issue
Feature Request

### Current behavior
Currently, there is no error indicator for fields. There is an indicator in blue that shows if a mandatory field is empty.

### Expected behavior
Have an indicator that shows an error indicator for fields that are mandatory but not filled and for other error situations of fields. The indicator should have the same color as the "not saved indicator for records. see https://github.com/metasfresh/metasfresh-webui-frontend/issues/437
I would suggest a pale red colored line (similar to the density of pulse effect yellow but only as a line similar to mandatory field marker).
As discussed in weekly jour fix. Would be great to have an error message indicator in fields marked as error e.g. a red circled "i" for example when hovering over it then pops up an error description tooltip.

**Comment by teosarca** [comment]
see:
![image](https://cloud.githubusercontent.com/assets/1244701/23398212/4e1f5f4e-fda4-11e6-93db-dca500c1f0a6.png)

**Comment by cadavre** [comment]
Described in #253 .

**Comment by damianprzygodzki** [comment]
@teosarca ive implemented the respecting of valid property, but i see that there is a missing thing.

![screen shot 2017-03-03 at 11 57 47](https://cloud.githubusercontent.com/assets/5701744/23548611/a79d362a-0008-11e7-9c64-c3e2bfaf533c.png)

We assumed that not edited field, should be valid at first sight, but now we are mixing mandatory and valid together, what looks bad. I am waiting for that with merging this PR, in case of avoidance of propagating testing issues.

**Comment by cadavre** [comment]
Looks uber-nice for me.

**Comment by teosarca** [comment]
@damianprzygodzki  @cadavre  

> @teosarca we agreed to provide valid: true as initial value? Or adding another property initialValidation: {bool}? I guess it was 1st option.

Yes, u are right... but i don't have it now.
I would suggest to split this to another task so we can let this task flow... wdyt?

**Comment by damianprzygodzki** [comment]
I think that it is required, and can't be merged without that. It looks at least weird to have mandatory and not valid input at the same time, and that case is occuring really often because the mandatory fields are always empty at the start... I don't want to trigger more issues.

**Comment by teosarca** [comment]
ok, np... on it.

**Comment by teosarca** [comment]
implemented in https://github.com/metasfresh/metasfresh-webui/issues/203 .
waiting for the build and then i will do a rollout.

NOTE: the field is called initialValue

**Comment by teosarca** [comment]
API ready

**Comment by teosarca** [comment]
Did a quick test:
* create new order
* hover bpartner and the "mandatory" error message is displayed
=> NOK because the field has it's initial value

see:
![image](https://cloud.githubusercontent.com/assets/1244701/23633524/c106a966-02ce-11e7-9627-993a91ea4b2d.png)

**Comment by metas-mk** [comment]
Tested Works as required. Closing.
