### ISSUE TITLE
Not saved indicator for Grid view lines

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#447]
### Type of issue
Feature request

### Current behavior
Currently, Grid view lines that are not saved, are shown and cached but not yet in database. The user cannot see that something is wrong.

### Expected behavior
Show unsaved records in a pale red overlay (similar to pulse effect yellow) and when marked with focus and blued out, then show red at least in beginning line/ marker to signal that it's unsaved.

**Comment by metas-mk** [comment]
see https://github.com/metasfresh/metasfresh-webui-frontend/issues/437

**Comment by damianprzygodzki** [comment]
I am afraid that the `saveStatus` is missing for gridview data.
![screen shot 2017-03-06 at 16 53 49](https://cloud.githubusercontent.com/assets/5701744/23617472/80b6643c-028d-11e7-834d-ca4f1474c47c.png)

**Comment by teosarca** [comment]
@damianprzygodzki , yes... because those are always saved... but i can add it.

question: atm, how the frontend is handling the case when the save status does not exist?

**Comment by teosarca** [comment]
also, can u skip it now for views if not exists?

**Comment by damianprzygodzki** [comment]
Of course! I thought that "Not saved indicator for Grid view lines" means grid view lines ;p So we are want to add this in tables in tabs right?

**Comment by metas-mk** [comment]
Tested. The not saved indicator for rows works nearly as required (coloring, setting, selected row). But, when editing the record data so that no errors should appear anymore, the coloring is not reset.
![image](https://cloud.githubusercontent.com/assets/13365687/23707453/b55767fa-0412-11e7-8b4d-b56627a84242.png)

**Comment by metas-dh** [comment]
Results of IT 2
tested on w101

* not saved indicator for rows: row is marked red on the left, and coloured pale red, red line in document header: OK
* resetting of colouring after editing: row is not marked anymore and colour is normal, no more red line in document header: OK
(tested with rows in purchase & sales order, deleting / adding the product)
