### ISSUE TITLE
Query on activate document included tab

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#448]
### Type of issue

Feature request

### Current behavior
When opening a single document all included tabs data is fetched at the beginning.

### Expected behavior
In layout, we introduced a new property called "queryOnActivate".
When that property is present and it's true, frontend shall:
* ALWAYS query for data when user clicks on the Tab to activate it
* when initially fetching the data, if queryOnActivate and it's not the first tab, pls don't query it.

### Steps to reproduce

Check, for example, the Material Receipt Candidates.
There, the Handling Unit Assignment tab is flagged as queryOnActivate.

e.g. https://w101.metasfresh.com:8443/window/540196/1000003
![image](https://cloud.githubusercontent.com/assets/1244701/23398812/aa14a4e2-fda6-11e6-8b9d-0c6e324e50a9.png)

**Comment by teosarca** [comment]
@cadavre i know this could be part of #130 but let's do it here because it's high priority for us.

**Comment by cadavre** [comment]
Yup, I agree it shall be done separately.

**Comment by metas-mk** [comment]
Tested. Works as required. Switched between different subtabs in Material Receipt Schedule window. Every time clicking back on HU Assignment Tab (High Volume) the tab content was loaded.
