### ISSUE TITLE
Do not display "Close Batch Entry" if there was an error with Batch Entry

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#450]
### Type of issue
* Bug

### Current behavior
* If there was an error with batch entry, the "Close batch entry" button is still displayed. You have to click it and then click "Batch entry again " if you want to continue
### Expected behavior
* If there was a problem with batch entry I would expect to be able to directly press Batch Entry again after solving that problem.
### Steps to reproduce
* Create an order, set a partner to it ( => order saved) 
* Create a line with Add new, but to not complete info there. Only press done
* Press "Batch entry"
* => I get "Document /W181/1004002 state is invalid: Cannot create included document because it's not allowed.↵ AllowCreateNewDocument: FALSE{A new document already exists}↵ EntityDescriptor: DocumentEntityDescriptor{tableName=C_OrderLine, fields.count=102}" OK because the line above was not saved.
* Afterwards I have the Close Batch Entry option: NOK

![image](https://cloud.githubusercontent.com/assets/16001442/23406335/1d6ffcf0-fdc7-11e6-8b77-87534d1adb0f.png)

**Comment by cadavre** [comment]
It is already handled by fix in #459. It will also never occur again after @teosarca will implement /discard endpoint to remove "line above (that) was not saved".

**Comment by teosarca** [comment]
not reproductible anymore
