### ISSUE TITLE
Bug in Sales Order Line, Add new

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#451]
### Type of issue

* Bug
### Current behavior
* After I already inserted an orderline using "Add new" and then I want to add a new one using "Add new" again the window to complete the info doesn't open but an empty line is created instead.
### Expected behavior
* I should be able to add as many lines as I want using Add new
### Steps to reproduce
* Create a sales  order, set a partner to it ( =< sales order saved)
* Create a sales order line using Add new : set a product, a TU and qtys
* Press Add new again.
* => NOK: The window doesn't open again
* => NOK: The reposnse has 2 lines, anyways: 

![image](https://cloud.githubusercontent.com/assets/16001442/23406858/bd4fd554-fdc9-11e6-8296-c5215816fbcb.png)

* Refresh ( F5)
* => NOK: There are 2 lines displayed now, one of them is empty: 

![image](https://cloud.githubusercontent.com/assets/16001442/23406881/d7951924-fdc9-11e6-926c-5fd63f8a7ecc.png)

**Comment by damianprzygodzki** [comment]
Cannot reproduce, even with the same values.

**Comment by metas-lc** [comment]
IT
checked sales and purchase order and you can use add new as many times as you like, with no empty lines
