### ISSUE TITLE
Saving Indicator Bar in modal window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#452]
### Type of issue
Feature request

### Current behavior
Currently the saving indicator is not shown in modal overlays. Instead it is shown in the window underneath.

### Expected behavior
Show the saving indicator in the modal overlay window so the user can see it.

### Steps to reproduce
Open any modal overlay window and change data in there.

**Comment by metas-mk** [comment]
Tested. Works as required in modal overlays. closed.

**Comment by teosarca** [comment]
For reference: the save indicator shall be displayed there:
![image](https://cloud.githubusercontent.com/assets/1244701/23579493/4646185c-00f7-11e7-84b1-285b1927a319.png)
