### ISSUE TITLE
Sometimes the webui freezes when receiving HUs from single view

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#454]
### Type of issue

* Bug

### Current behavior
* When I press receive Hus and then done several times from single view receipt candidate the webui freezes and I have to refresh it to work again.
### Expected behavior
* It should work as in gridview
### Steps to reproduce
* Go to a material receipt candidate, open it in single view
* Go to the 3 points from left side to access the available actions 
* Receive HUs
* Set an LU qty
* Start
* Done
* Repeat the steps above 1-6 times (sometimes I got it from the first repetition, sometimes I had to repeat more) 
* => NOK: At a point, everything freezes.  I have to reload the page to be able to use it again.

Notes: 
* There is nothing in the inspection.
* In the console I get this ( but I am not sure it is related): 

>     at Object.unmountComponent (ReactReconciler.js:79)
> SockJS.send @ main.js:158
> r._transmit @ stomp.min.js:8
> r.disconnect @ stomp.min.js:8
> componentWillUnmount @ Device.js:36
> unmountComponent @ ReactCompositeComponent.js:412
> unmountComponent @ ReactReconciler.js:79
> unmountChildren @ ReactChildReconciler.js:146
> unmountChildren @ ReactMultiChild.js:373
> unmountComponent @ ReactDOMComponent.js:980
> unmountComponent @ ReactReconciler.js:79
> unmountComponent @ ReactCompositeComponent.js:418
> unmountComponent @ ReactReconciler.js:79
> unmountChildren @ ReactChildReconciler.js:146
> unmountChildren @ ReactMultiChild.js:373
> unmountComponent @ ReactDOMComponent.js:980
> unmountComponent @ ReactReconciler.js:79
> unmountChildren @ ReactChildReconciler.js:146
> unmountChildren @ ReactMultiChild.js:373
> unmountComponent @ ReactDOMComponent.js:980
> unmountComponent @ ReactReconciler.js:79
> _updateRenderedComponent @ ReactCompositeComponent.js:757
> _performComponentUpdate @ ReactCompositeComponent.js:724
> updateComponent @ ReactCompositeComponent.js:645
> receiveComponent @ ReactCompositeComponent.js:547
> receiveComponent @ ReactReconciler.js:125
> updateChildren @ ReactChildReconciler.js:109
> _reconcilerUpdateChildren @ ReactMultiChild.js:213
> _updateChildren @ ReactMultiChild.js:312
> updateChildren @ ReactMultiChild.js:299
> _updateDOMChildren @ ReactDOMComponent.js:936
> updateComponent @ ReactDOMComponent.js:754
> receiveComponent @ ReactDOMComponent.js:716
> receiveComponent @ ReactReconciler.js:125
> updateChildren @ ReactChildReconciler.js:109
> _reconcilerUpdateChildren @ ReactMultiChild.js:213
> _updateChildren @ ReactMultiChild.js:312
> updateChildren @ ReactMultiChild.js:299
> _updateDOMChildren @ ReactDOMComponent.js:936
> updateComponent @ ReactDOMComponent.js:754
> receiveComponent @ ReactDOMComponent.js:716
> receiveComponent @ ReactReconciler.js:125
> _updateRenderedComponent @ ReactCompositeComponent.js:754
> _performComponentUpdate @ ReactCompositeComponent.js:724
> updateComponent @ ReactCompositeComponent.js:645
> receiveComponent @ ReactCompositeComponent.js:547
> receiveComponent @ ReactReconciler.js:125
> _updateRenderedComponent @ ReactCompositeComponent.js:754
> _performComponentUpdate @ ReactCompositeComponent.js:724
> updateComponent @ ReactCompositeComponent.js:645
> receiveComponent @ ReactCompositeComponent.js:547
> receiveComponent @ ReactReconciler.js:125
> updateChildren @ ReactChildReconciler.js:109
> _reconcilerUpdateChildren @ ReactMultiChild.js:213
> _updateChildren @ ReactMultiChild.js:312
> updateChildren @ ReactMultiChild.js:299
> _updateDOMChildren @ ReactDOMComponent.js:936
> updateComponent @ ReactDOMComponent.js:754
> receiveComponent @ ReactDOMComponent.js:716
> receiveComponent @ ReactReconciler.js:125
> _updateRenderedComponent @ ReactCompositeComponent.js:754
> _performComponentUpdate @ ReactCompositeComponent.js:724
> updateComponent @ ReactCompositeComponent.js:645
> performUpdateIfNecessary @ ReactCompositeComponent.js:561
> performUpdateIfNecessary @ ReactReconciler.js:157
> runBatchedUpdates @ ReactUpdates.js:150
> perform @ Transaction.js:140
> perform @ Transaction.js:140
> perform @ ReactUpdates.js:89
> flushBatchedUpdates @ ReactUpdates.js:172
> close @ ReactUpdates.js:47
> closeAll @ Transaction.js:206
> perform @ Transaction.js:153
> perform @ ReactUpdates.js:89
> flushBatchedUpdates @ ReactUpdates.js:172
> close @ ReactUpdates.js:47
> closeAll @ Transaction.js:206
> perform @ Transaction.js:153
> perform @ ReactUpdates.js:89
> flushBatchedUpdates @ ReactUpdates.js:172
> closeAll @ Transaction.js:206
> perform @ Transaction.js:153
> batchedUpdates @ ReactDefaultBatchingStrategy.js:62
> enqueueUpdate @ ReactUpdates.js:200
> enqueueUpdate @ ReactUpdateQueue.js:24
> enqueueSetState @ ReactUpdateQueue.js:209
> ReactComponent.setState @ ReactComponent.js:63
> __deselectAllProducts__REACT_HOT_LOADER__ @ Table.js:178
> Table._this.deselectAllProducts @ Table.js:31
> __handleClickOutside__REACT_HOT_LOADER__ @ Table.js:204
> Table._this.handleClickOutside @ Table.js:31
> (anonymous) @ index.js:59
> main.js:158 Uncaught Error: InvalidStateError: The connection has not been established yet
>     at SockJS.send (main.js:158)
>     at r._transmit (stomp.min.js:8)
>     at r.disconnect (stomp.min.js:8)
>     at Device.componentWillUnmount (Device.js:36)
>     at ReactCompositeComponentWrapper.unmountComponent (ReactCompositeComponent.js:412)
>     at Object.unmountComponent (ReactReconciler.js:79)
>     at Object.unmountChildren (ReactChildReconciler.js:146)
>     at ReactDOMComponent.unmountChildren (ReactMultiChild.js:373)
>     at ReactDOMComponent.unmountComponent (ReactDOMComponent.js:980)
>     at Object.unmountComponent (ReactReconciler.js:79)

* This is my frozen screen: 
![image](https://cloud.githubusercontent.com/assets/16001442/23413687/189b26c6-fde2-11e6-99bb-94ac1cf93c90.png)

**Comment by damianprzygodzki** [comment]
I cannot reproduce that. Repeated lot more than 6 times, as fast as i can, probably need more info.

Maybe we need to reproduce that on particular set of documents? Maybe it was some API timeout? The network logs looks pretty good. And that error from console log is not realted - also cannot get it again.

**Comment by metas-rc** [comment]
I retested on https://w101.metasfresh.com:8443

The problem seems even more complex.

When I open a material receipt candidate ( or any other document) in single view I cannot start any process for it. After clicking the process in the action list this is what I get in the console: 

> Uncaught TypeError: Cannot read property 'saved' of undefined
>     at MasterWindow.render (MasterWindow.js:190)
>     at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:799)
>     at ReactCompositeComponentWrapper._renderValidatedComponent (ReactCompositeComponent.js:822)
>     at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:746)
>     at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)
>     at ReactCompositeComponentWrapper.updateComponent (ReactCompositeComponent.js:645)
>     at ReactCompositeComponentWrapper.receiveComponent (ReactCompositeComponent.js:547)
>     at Object.receiveComponent (ReactReconciler.js:125)
>     at ReactCompositeComponentWrapper._updateRenderedComponent (ReactCompositeComponent.js:754)
>     at ReactCompositeComponentWrapper._performComponentUpdate (ReactCompositeComponent.js:724)

If I insist, the webui also freezes (doesn't react if I click on home or on the 3 points)

**Comment by damianprzygodzki** [comment]
Sorry, i cannot reproduce anything. 

Every action is working for single material receipt candidate, every response handling, like: modal, redirection, etc is working.

Also no errors in console.

**Comment by cadavre** [comment]
@metas-rc what is your PC hardware? JS is client-side compute language so it might be case just for you i.e. if running older Intel Atom or some Athlon CPU etc.

**Comment by damianprzygodzki** [comment]
I bet the version mismatch.

**Comment by cadavre** [comment]
Tested on 3 machines on http://master.metasfresh.jzapp.io – cannot reproduce. Can you @metas-rc  test on this host?

**Comment by metas-rc** [comment]
I cannot reproduce the bug any more, either.

**Comment by cadavre** [comment]
Close?
