### ISSUE TITLE
HU Editot Attribute editing not possible

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#458]
### Type of issue
Bug

### Current behavior
Attribute editing not possible in HU Editor. Automatically deselects the HU line.

### Expected behavior
Don't deselect the HU line and allow editing the Attributes when not read-only then.

### Steps to reproduce
Open HU Editor via Material Receipt Candidates Window. Click on Attribute to edit. Attributes disappear because HU Line is deselected.

**Window:** window/540196

![image](https://cloud.githubusercontent.com/assets/13365687/23466917/cc7fa97c-fe9c-11e6-9cb1-fe56b77e0228.png)

**Comment by damianprzygodzki** [comment]
@Dunkat the reason here are changes of a #259, i quick fixed it, but please investigate that issue again, the RawModal and Modal especially, to check if the right class are applied (js-unselect isnt here redundant? or rest after development? )

**Comment by metas-mk** [comment]
Tested. Works as required. Closed.
