### ISSUE TITLE
If quick input fails then don't show the quick input fields

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#459]
### Current behavior
User clicks on "Batch entry" button, in an included tab.
If the endpoint fails, 
* the error is displayed => OK
* but the batch input is activated => NOK

### Expected behavior
It shall not be activated

### Steps to reproduce
Pick any window, except Order or Empties.
Go to first tab and press Batch input.
You will get an error.

Remove this part if feature request.

**Link:**  e.g. https://w101.metasfresh.com:8443/window/123/2156481

![image](https://cloud.githubusercontent.com/assets/1244701/23477994/7bf8cef8-fec8-11e6-9a76-4b32cf9e3824.png)

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Closing.
