### ISSUE TITLE
Option to log received web socket messages to console

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#460]
(only if it's a quick fix)

Is there a easy way to log all received websocket packets (including the topic) to console? But it shall be togglable.
It would really help our team.

**Comment by damianprzygodzki** [comment]
In modern browsers you have in the Network Tab under the Inspect option, WS/Sockets or WebSockets filter to see these calls.

**Comment by teosarca** [comment]
yup, u are right.... just that i found that not so friendly because it's mixed with a lot of heartbeat and other protocol choreography along with the actual events...

But i think we can live with that for now.
