### ISSUE TITLE
If tab layout's "supportQuickInput" is false then don't show the "Batch entry" button

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#461]
### Type of issue

Feature request

### Current behavior
Batch entry button is showed all the time even though there are just a few tabs which supports it.

### Expected behavior
Don't show the button, don't make any calls to /quickInput endpoint

### Steps to reproduce
Open BPartner window.
On first tab click Batch entry => Error

![image](https://cloud.githubusercontent.com/assets/1244701/23482463/d918c8ae-fed7-11e6-8684-258938002e93.png)

**Comment by teosarca** [comment]
Backend task: https://github.com/metasfresh/metasfresh-webui/issues/201

**Comment by metas-lc** [comment]
IT
batch entry is visible 
- in sales and purchase window on orderline. And it's not visible on tax tab OK
- it is also visible in empties windows OK
not visible 
- on windows like bpartner, product, pricelist, warehouse and so on
