### ISSUE TITLE
If document was not found forward to documents view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#462]
### Current behavior
Type in some not existing document, e.g. https://w101.metasfresh.com:8443/window/123/99999.
A blank page is displayed which can be confusing for user.

### Expected behavior
Show the error which was received from backend.
Forward to documents view. In the example above, this means: https://w101.metasfresh.com:8443/window/123 .

![image](https://cloud.githubusercontent.com/assets/1244701/23484594/472f1b92-fee0-11e6-968c-d1d98c70d56c.png)

**Comment by metas-lc** [comment]
IT
i don't get an empty page OK
but i don't get an error message , only if i want to leave page. If i select "prevent this..." and press cancel, we get a flood NOK
if i select ok, then i get back to documents view OK

![docu_not_exists](https://cloud.githubusercontent.com/assets/16001666/24392307/f3500ef2-139b-11e7-9baf-13825a35ee44.png)

**Comment by Dunkat** [comment]
It's already fixed in #453

**Comment by metas-lc** [comment]
Thank you. Moving it back to IT
todo: test it again after https://github.com/metasfresh/metasfresh-webui-frontend/issues/453 gets in IT

**Comment by metas-lc** [comment]
IT
- open a window that does not exist (e.g. https://w101.metasfresh.com:8443/window/540196/1)
=> browser is not asking if i want to leave the page OK
=> didn't get any error that is not existing. Might be solved in https://github.com/metasfresh/metasfresh-webui-frontend/issues/253
=> the documents view opened instead (e.g. https://w101.metasfresh.com:8443/window/540196) OK
- create a new order and don't set mandatory fields (copy the link to use it later)
- move on another window
=> browser is asking if i want to leave the page OK
=> if i choose yes i am getting on the next window, if no i remain there OK
- use back button
=> you get back to your unsaved document OK
- paste the link of your docu in a new browser tab 
=> exactly that docu is opening OK
