### ISSUE TITLE
DateTime widget not respected in included tab

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#465]
### Type of issue

Bug

### Current behavior
In included tab, a widget which is DateTime is displayed as Date.

### Expected behavior
DateTime widgets shall always show the Time part too.

### Steps to reproduce
Open requests window, pick one which has something in Updates tab.
e.g. https://w101.metasfresh.com:8443/window/232/1000017

![image](https://cloud.githubusercontent.com/assets/1244701/23505729/9dbeead8-ff4d-11e6-9b75-64f24e899574.png)

![image](https://cloud.githubusercontent.com/assets/1244701/23505757/be8d0632-ff4d-11e6-8596-06ea58f88964.png)

**Comment by metas-mk** [comment]
Tested. Works nicely as required.
![image](https://cloud.githubusercontent.com/assets/13365687/23623499/8e149a80-02a2-11e7-8e13-cb86d4cf5f80.png)
