### ISSUE TITLE
htaccess: always redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#466]
### Type of issue

Feature request

### Current behavior
If you type in some HTTP URL you got an error from apache server.

### Expected behavior
No error shall be displayed because user doesn't know how to react on it.
Automatically rewrite the URL and forward it to HTTPS (using HTTP code 301).

**Comment by cadavre** [comment]
This is pro-environment setting and should be configured by devops team or system administrator. Nothing to do here for front-end (from implementation side or project configuration).
