### ISSUE TITLE
Batch entry dimensions adjustment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#468]
### Type of issue
Feature request

### Current behavior
The fields for Combined Product +Packing and Quantity have the same width. Often the Product name, with important information is cut off from Packing material.

### Expected behavior
We need more space for the combined Product Field especially more for the product (a) itself. The Packing element (b) can be reduced in width. Same the quantity field (c).
Please also add a small separator are between the elements.

### Steps to reproduce
Open any window w/ batch entry possibility, for example, window/143/

![image](https://cloud.githubusercontent.com/assets/13365687/23514180/cbe24af4-ff66-11e6-9860-8e3f046c4838.png)

**Comment by damianprzygodzki** [comment]
Which window types also support batch entry? I want to test other cases.

**Comment by teosarca** [comment]
atm the only windows with batch entries are sales/purchase order, customer/vendor empties.

So basically only Windows.

does this answers your question?

**Comment by damianprzygodzki** [comment]
Yes thank you. Im gonna deliver some achievements soon.

**Comment by damianprzygodzki** [comment]
![screen shot 2017-03-09 at 09 52 40](https://cloud.githubusercontent.com/assets/5701744/23742710/3aa50192-04ae-11e7-8751-fbc21b8eec06.png)
That is what i can propose without much effort, but!

![screen shot 2017-03-09 at 09 52 54](https://cloud.githubusercontent.com/assets/5701744/23742722/47b41472-04ae-11e7-9df0-0dad8c5dff9e.png)
For smaller resolutions, second label is disappearing. It happens because type `secondary` of widgets behave to keep own grid consistent to other fields in window.
What we can do is provide a new type of widgets, that allow display forms only inline with fluid labels.

**Comment by metas-lc** [comment]
IT
created new product "test product with long name for testing purpose 1234567890" and added it in a purchase price list
new purchase order , add this product
both product and quantity fields are bigger OK

![batch](https://cloud.githubusercontent.com/assets/16001666/23958752/c1ed1778-09ab-11e7-8f69-01dc89db91a2.png)


isn't too much space between the product and the packing?

**Comment by metas-mk** [comment]
@metas-lc agree. the reason for making the field bigger is mostly to have more space for the product name. @damianprzygodzki can u please take care?

**Comment by damianprzygodzki** [comment]
Im not sure that changing design here will be good for consistency. I was thinking about solution here, to move packing (or other additional fields) to the left. Do we want to change it in every place for lookup?

**Comment by cadavre** [comment]
So you want more space for long product name OR packaging name closer to product name. You cannot have both because it excludes each other. :)

**Comment by metas-mk** [comment]
@damianprzygodzki @cadavre 
Let's start the discussion about this one again. I'm explaining from user point, not technically. Let's find out together which solution we can get w/ which effort.
![image](https://cloud.githubusercontent.com/assets/13365687/24693039/f13a0758-19db-11e7-8be2-c1c07c19b4eb.png)

**Comment by metas-mk** [comment]
moving it to current milestone

**Comment by cadavre** [comment]
**As a default behaviour:**
Always split widget widths equally, i.e. for two fields – 50% + 50%.

**Optional:**
Additional information from API about how to layout widgets – in what proportion. I.e. percentage or via flex like "1-3-4".

**Comment by damianprzygodzki** [comment]
Shouldn't it be closed? Nothing to fix here and possible discussion should be moved to lookup revamp issue #600

**Comment by teosarca** [comment]
i think we shall implement on of cadavre's suggestions. I just need to get to it.

**Comment by damianprzygodzki** [comment]
Still it is a case of new version of lookup, possible duplicate.

**Comment by teosarca** [comment]
Ok, then i am closing it and the work shall be done on #600.
(for this task, check the "Layouting" chapter)
