### ISSUE TITLE
missing value to for range date-time filter

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#469]
### Type of issue

Bug

### Current behavior

date-time ranged filter is missing value to

### Expected behavior

have date-time range filter like date range filter, with value and value to 

### Steps to reproduce

1. go to sales order window
2. press on "Select Other Filter"
3. choose "PromisedDate"
=> notice you can select only 1 date. We need to be able to select 2

**Link:** https://w101.metasfresh.com:8443/window/143

![2 sales_order_filter2](https://cloud.githubusercontent.com/assets/16001666/23515790/f8600d84-ff73-11e6-96a1-bb9d1542da3e.png)

![2 sales_order_filter3](https://cloud.githubusercontent.com/assets/16001666/23515782/f137bc3c-ff73-11e6-97b8-761cfc7bceac.png)

![2 sales_order_filter4](https://cloud.githubusercontent.com/assets/16001666/23515802/0244abe8-ff74-11e6-84c1-3f59c116a188.png)

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
IT
repeated the steps from above and now works. I could select date and date to and was applied correctly. OK
