### ISSUE TITLE
Home Button shall not be tied to Root Name

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#47]
Seems as if Home Button only appears when Root Node Name is "Menu".
Please change to recognize more reliable e.g. just on the first node. wdyt?

**Comment by Dunkat** [comment]
Yes, ok.  So first node has always nodeId : "0", right?

**Comment by teosarca** [comment]
I would recommend to not do this kind of assumptions. Basically, all endpoints which return path they return the path starting from root (aka Home) so why not putting the Home icon on the first node in the path.

wdyt?

**Comment by Dunkat** [comment]
Yes, you're right, it would be better. Changed
