### ISSUE TITLE
changing AM to PM in Date+Time fields

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#470]
### Type of issue

Bug

### Current behavior

when i want to change AM / PM in a date+time field, the arrow buttons are not working very well

### Expected behavior

when i select the up or down button in date+time field to change AM/PM it shall update 

### Steps to reproduce

1. go to e.g. Sales Order window and create a new one (or open an existing drafted one)
2. change a date+time field (e.g. Promised Date)
3. change it from AM to PM, selecting up and down arrow buttons
=> notice that on the first try , the field updated but on your side no

**Link:** https://w101.metasfresh.com:8443/window/143/1004053

![datepromisedam](https://cloud.githubusercontent.com/assets/16001666/23516212/3fbab214-ff75-11e6-993c-a2e0c67934ef.png)

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
This one is fine. Closing
