### ISSUE TITLE
Date+Time field is not set correctly on new

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#471]
### Type of issue

Bug

### Current behavior

Date+Time field is not set correctly on new document

### Expected behavior

Date+Time field should have the correct date and time

### Steps to reproduce

1. create a new Sales Order (my current date 03/02/2017)
=> notice that date promised is 03/03/2017 12:59 AM
=> date promised should be 03/02/2017 11:59 PM

**Link:** https://w101.metasfresh.com:8443/window/143

![1 sales_order](https://cloud.githubusercontent.com/assets/16001666/23517759/f41feeaa-ff79-11e6-9d6d-18eab0724d6c.png)

**Comment by damianprzygodzki** [comment]
Cannot reproduce. It looks okay.
<img width="874" alt="screen shot 2017-03-27 at 09 19 50" src="https://cloud.githubusercontent.com/assets/5701744/24345047/9114f752-12ce-11e7-8e81-29af0406f9de.png">

**Comment by cadavre** [comment]
@metas-lc can you please check one more time and if all fine – close issue. If not – please provide more info to reproduce.

**Comment by metas-lc** [comment]
@cadavre still the same. 
![1](https://cloud.githubusercontent.com/assets/16001666/25180559/23733a50-2517-11e7-8e2d-9b473f990c4d.png)

i checked to see what i get in headers if i leave the hour and just change the date (in datePromised) and i get this
"2017-04-19T00:59:59.000+03:00"
while in preview is "2017-04-18T23:59:59.000+02:00"

**Comment by cadavre** [comment]
It is the same as in #471 – let's close one of it.

`"2017-04-19T00:59:59.000+03:00"`
`"2017-04-18T23:59:59.000+02:00"`
Are the same.

Does this affect UI somehow displaying wrong value to user?

**Comment by metas-lc** [comment]
Talked with @teosarca and it's not a frontend issue. 
it's just that if i get 11PM for a field, my timezone will change it to 12AM.. that's why my UI looked affected.
Closing the issue
