### ISSUE TITLE
Editing in the middle of a text field makes the cursor jump to the end

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#474]
In grid mode, try to edit some text field. Move your cursor to the middle of the word, try to type something, a letter, even backspace makes the cursor jump at the end.
(but the letter was inserted)

![image](https://cloud.githubusercontent.com/assets/1244701/23526985/c860762c-ff9c-11e6-9e8f-c762f277b6cd.png)

**Comment by damianprzygodzki** [comment]
NOTE: It is related to action `handleChange` in MasterWidget, occurring due to waiting for state persisting (pulse-on effect preserving). DO NOT WORKAROUND.

**Comment by metas-lc** [comment]
IT
- line in kpi: editing fieldpath filed (text field) works fine, the cursor stays where you put it
- line in purchase order: editing description (text field) works fine, the cursor stays where you put it
- line in sales order: editing price (number field) works fine, the cursor stays where you put it
(tested directly in line and in advanced edit)

**Comment by teosarca** [comment]
this issue is the "return of" https://github.com/metasfresh/metasfresh-webui-frontend/issues/436

**Comment by metas-ts** [comment]
i just rolled https://github.com/metasfresh/metasfresh-webui-frontend/issues/967 out for IT, but it's not yet in the `master` branch.
Please IT and ping me

**Comment by metas-ts** [comment]
solved by https://github.com/metasfresh/metasfresh-webui-frontend/issues/964
