### ISSUE TITLE
When editing the text field in grid mode i cannot see selected text

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#475]
In grid mode, try to edit some text field.
Press CTRL+A to select the whole text (or u can do it by mouse if u want, it's same).
You can see what's selected because i guess the selection has the same color as the selected row.

I suggest to change the text selection color in when the row is selected.

(btw, that's selected)
![image](https://cloud.githubusercontent.com/assets/1244701/23527109/41dbffb2-ff9d-11e6-9306-105d1c8a146e.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* selected text in text field, grid mode (w/ mouse / CTRL + A): colour is changed: text is white, with dark blue background: OK
* changing the marked text in text field, grid mode: line is changing colour, becomes yellow: OK
