### ISSUE TITLE
When editing in grid mode pressing enter does nothing

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#476]
Edit a text field in grid mode. Press enter. No patch is sent to server.

![image](https://cloud.githubusercontent.com/assets/1244701/23527875/4ae1e9e8-ffa0-11e6-9a66-61b0c91b6505.png)

**Comment by Dunkat** [comment]
Checked and it seems send patch to server after press enter. It not send in one case - when value is not changed. Checked for the same window. If problem still occure, please ping me.

**Comment by cadavre** [comment]
Same for me – works.

**Comment by teosarca** [comment]
@cadavre not working, just showed to Kasia.

**Comment by cadavre** [comment]
Hmm, I guess we'd need to also report on app version (or commit sha) while creating an issue. Works for `a86934e7` on Chrome Mac OSX.

**Comment by teosarca** [comment]
Tested in KPI fields and in sales order lines. Works nicely.
