### ISSUE TITLE
Right filter button error  if the document was deleted 

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#477]
### Type of issue

* Bug 

### Current behavior

*  If there was a deleted document and I try to enter it with the old url, the white screan is displayed but the right filter button is also displayed. Clicking it leads to floods of errors.
### Expected behavior
* The button should not even be displayed if dealing with a deleted document. If it is displayed, it should not try to open anything.
### Steps to reproduce

First part as in https://github.com/metasfresh/metasfresh-webui/issues/202 :
* Create an order and fill the bpartner, so it will be saved for sure.
* Now, pls copy the current URL to your clipboard.
* Delete the order. You are forwarded to orders view.
* Call the URL you have copied.
*  => You see the white empty screen . This will be fixed in https://github.com/metasfresh/metasfresh-webui-frontend/issues/462.
* => In the inspection you have an error about the document not being found.
* But you also see the right button for the filters. 
* Click that button
* => NOK: The Network is flooded with :

![image](https://cloud.githubusercontent.com/assets/16001442/23548818/f1f442f0-0011-11e7-8c8f-86b6d1963973.png)

* The console: 
![image](https://cloud.githubusercontent.com/assets/16001442/23548834/04ae2564-0012-11e7-9a89-732044e35177.png)

* Also, an error message is displayed in the top-right: 
![image](https://cloud.githubusercontent.com/assets/16001442/23548867/2bd3dae4-0012-11e7-9e17-3b4fbd22a59c.png)

* This is what I tried with: https://w101.metasfresh.com:8443/window/143/1004075

**Comment by Dunkat** [comment]
I think there is no sense to hide this button because there is a list with others document, which can be displayed and it's already fixed by #528. But it still doesn't matter because user will be redirect to document view #462.

**Comment by teosarca** [comment]
agree, the only thing you can do here, if not already fixed, is to make sure the side list component is not going in some endless loop...

**Comment by metas-rc** [comment]
I retested on https://w101.metasfresh.com:8443 .
There is no loop if opening the right filter from an unexising document. Will move the task in done.
