### ISSUE TITLE
Search Results showing Groups instead of Groups/ Leafs

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#48]
Search Results showing Groups instead of Groups/ Leafs.
Pls Fix.
![image](https://cloud.githubusercontent.com/assets/13365687/18758175/43426c08-80f7-11e6-822f-1e6e5b8907cc.png)

**Comment by cadavre** [comment]
This is 95% done. Need to add few changes and we're ready.
