### ISSUE TITLE
Textarea fields shall support the browser native field resize

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#483]
i.e. this one:
![image](https://cloud.githubusercontent.com/assets/1244701/23560530/76746dee-0043-11e7-9d12-818ee3d46aa8.png)

**Comment by cadavre** [comment]
No, we don't want that. :) On Github it's just fine because we have just one column and no another column's height that will be affected. Also front-end would need to recalculate layout and repaint it which might take lots of CPU time. It is useful on single-textarea forms.
