### ISSUE TITLE
Expand batch entry when completed docuement

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#487]
### Type of issue
Bug
### Current behavior
In completed documents, when switching between expanded view and detailed view, an error occurs.
### Expected behavior
Should be possible to switch w/o errors also when completed.
### Steps to reproduce
Open a completed Sales Order. Switch expand (mouse or [ctrl]space) batch entry back and forth.
**Window:** window/181/
![image](https://cloud.githubusercontent.com/assets/13365687/23578192/589b4890-00d1-11e7-95c4-696429a2587e.png)

**Comment by teosarca** [comment]
Fixed on backend side by returning HTTP 404 when quick input is not editable (e.g. document is processed).

But to have the complete solution we also need #459

**Comment by metas-mk** [comment]
Tested. No error is thrown back to the user interface. Works as required. Closed.
