### ISSUE TITLE
Grid view not refreshed on websocket event

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#489]
### Type of issue
Bug

### Steps to reproduce
Test case:
* Material receipt candidate window
* select a row and receive an HU (via HU Editor) and create the material receipt for it
* at that moment, the backend is sending a websocket event to ask the Material receipt candidate view to fresh

=> the frontend is not refreshing the view.
* you can see it in Inspect-Network, no call to view endpoint
* in parallel i was using http://localhost:8080/websocket_test.html connected to that view to see if the websocket were sent and they were.

![image](https://cloud.githubusercontent.com/assets/1244701/23582636/8558647e-0137-11e7-8d59-5486203f4e82.png)

![image](https://cloud.githubusercontent.com/assets/1244701/23582640/93693c0a-0137-11e7-86c3-bd44505390dc.png)

**Comment by damianprzygodzki** [comment]
Can't reproduce. Tested like:

- open material receipt candidates (540196, viewId: d541f7e3-1094-4c7b-a37a-06756acbe87b)
- selected first row, default quick action (1 IFCO 6410 x 8 Stk) triggered, HU editor opened
- selected first row, default quick action (Create mat. rec.) triggered, both views refresh by socket event
```
websocket refresh  2158f79e-f3f8-4839-8684-2cbb34cdd7f4 // this one inside modal
websocket refresh  d541f7e3-1094-4c7b-a37a-06756acbe87b // mat. rec. candidate
```

**Comment by teosarca** [comment]
Hi @damianprzygodzki 

I think the issue is reproductible only if:
* start directly from https://w101.metasfresh.com:8443/window/540196 (don't start it from menu)
* or you are on some Purchase Order and then from Menu you are clicking on Wareneingangdisposition referenced documetns.

I suspect that the frontend simply does not start listening to view's endpoint in that case.

If u cannot reproduce pls ping me ;)

**Comment by metas-mk** [comment]
Tested. Works nicely now.
