### ISSUE TITLE
Line height "jump" when editing mode

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#491]
### Type of issue
Feature request
### Current behavior
When doing doubleclick in Grid view on a field, then the line height jumps (gets larger).
### Expected behavior
Don't change the line height, just because of edit mode.
### Steps to reproduce
Try in Purchase Order window in subtab for Purchase Order lines. Double click on Price field.
/window/181/1004107

![image](https://cloud.githubusercontent.com/assets/13365687/23589696/1102bd2c-01d2-11e7-80ee-d78c03938fbb.png)

**Comment by Dunkat** [comment]
@metas-mk line height is now quite larger to have the same height like in editing mode. It means that whole table is a quite bigger, please check if it's ok for you

**Comment by metas-lc** [comment]
IT
order line height doesn't change when you change the price
also not visibly larger from how it was before

**Comment by metas-mk** [comment]
@Dunkat @metas-lc thanks for the feedback/ test. The line height is perfect now.
