### ISSUE TITLE
Disable quick actions button while running the action.

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#500]
### Current behavior
* press the quick action button (e.g. in receipt candidates)
* the button is not disabled

### Expected behavior
the button shall be disabled.

**Comment by teosarca** [comment]
I am also wondering if we could apply this generally to all buttons?

**Comment by damianprzygodzki** [comment]
@teosarca we can disable all buttons when we have some actions pending (patches, from other fields too). With applying it particularly - if user press one button, this one will be freezed until actions is finished - is more complicated.

**Comment by damianprzygodzki** [comment]
I've integrated a minimal version of that. Disabled are quick actions buttons while process is pending - as a issue said. If you want to extend that functionalities to other widgets is it possible.

**Comment by teosarca** [comment]
thanks.
no problem, i would say it's OK for now and we can create other tasks for each particular case.

**Comment by metas-rc** [comment]
Results of IT1

Tested on https://w101.metasfresh.com:8443


* I tested by calling the quick actions from the window Material Receipt Candidates
* When clicking the suggested action I could easily see that the button was automatically disabled after I pressed on it
* When choosing another quick action from the list, I could briefly see the button being disabled a moment before the actual window of the process was opened.

OK
