### ISSUE TITLE
Lookup field layout issue when it has red border

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#502]
Observe the lookup text field's search indicator. The image it's draw over the border.

Steps to reproduce:
* create an order
* create a line
* edit the line and clear the product field

![image](https://cloud.githubusercontent.com/assets/1244701/23633630/2d5f568a-02cf-11e7-8321-bb91462988a9.png)

**Comment by metas-lc** [comment]
IT
checked, looks nice. The text field's search indicator is inside the border (sales and purchase order)
