### ISSUE TITLE
Rename "Select other filter" to "Filter"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#504]
### Type of issue
Feature request
### Current behavior
The name for Filter is hard coded to "Select other filter"
### Expected behavior
Please rename to "Filter" as Quickfix

![image](https://cloud.githubusercontent.com/assets/13365687/23652598/d3914c52-0329-11e7-8a48-394ac2c6b705.png)

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* "Select other filter" is now just called "Filter": OK
