### ISSUE TITLE
jenkins shall not trigger metasfresh build when metasfresh-webui-frontend is built

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#508]
related to https://github.com/metasfresh/metasfresh-webui/issues/229

**Comment by metas-ts** [comment]
See my comment at https://github.com/metasfresh/metasfresh-webui/issues/229#issuecomment-284996818

**Comment by damianprzygodzki** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/229 Duplicate, can we close this issue?
