### ISSUE TITLE
Navigation menu 1 below Home clickable but not working

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#51]
Navigation menu 1 below Home clickable but not working. You can click on the navigation links -> the url is changed -> but the page is not loaded.

![image](https://cloud.githubusercontent.com/assets/13365687/18861277/71186d40-8484-11e6-86e5-ddaa3d32eeaf.png)

**Comment by cadavre** [comment]
I noticed this error happens when you're trying to use navigation while being on another same-level page. Switching from /window/143/1002304 to /window/143 and from /window/143 to /window/143/1002279 works well, but switching from /window/143 to /window/181 – is not.

@Dunkat

**Comment by Dunkat** [comment]
Should works now :)
