### ISSUE TITLE
Improved Not Saved Indicator design

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#510]
### Type of issue
Feature request
### Current behavior
The "Not saved indicator" is a tiny little bit suboptimal.
### Expected behavior
Have an improved design of the "Not Saved indicator"

**Now it looks like:**
![image](https://cloud.githubusercontent.com/assets/13365687/23678265/b8118a82-0383-11e7-8ff6-09a2008e6dee.png)

**What it should look like:**
![image](https://cloud.githubusercontent.com/assets/13365687/23678363/2210acc4-0384-11e7-8b79-d63cca4cc716.png)
... or something similar to that.

**Comment by metas-mk** [comment]
This is a follow up task for https://github.com/metasfresh/metasfresh-webui-frontend/issues/437

**Comment by metas-mk** [comment]
@damianprzygodzki 
Just checked quickly. Already looks much better. Is it easy possible to make that red line "permanently" visible as soon as not saved and those "error" fields are shown in red color? As soon as the gray-green bar can kick in and vanish the red.

![image](https://cloud.githubusercontent.com/assets/13365687/23698099/8755c842-03ea-11e7-8902-6698a99a791f.png)

**Comment by damianprzygodzki** [comment]
Do You mean, if document has saveStatus false, we are disabling loader and instead of it we are displaying fully filled red bar ?

**Comment by damianprzygodzki** [comment]
Roger

**Comment by cadavre** [comment]
+1 for 1px line coloured if saveStatus=false. BUT I would propose to resign from color **red**. Red suggests error which is NOT the case here. I propose to use "yellow" color which stands for "warning" instead of "error". Wdyt?

**Comment by metas-mk** [comment]
just suggested red because it would only appear when the user also sees the red error fields ... to not be confused w/ 2-3 different colors

**Comment by cadavre** [comment]
Shown after first validation then? Sounds ok.

**Comment by metas-mk** [comment]
yes

**Comment by damianprzygodzki** [comment]
It is unreachable because PATCHes are not updating validStatus.initialValue. So i can't turn indicator red after first patch.

**Comment by teosarca** [comment]
hi @damianprzygodzki 

I think you have all informations.

Take a look at following use case and pls let me know if you still believe something is missing.

1. New sales order
![image](https://cloud.githubusercontent.com/assets/1244701/23703232/93bf3fa6-0407-11e7-93b9-9ba2448b23b7.png)


2. Fill the bpartner field => expect document to be saved
![image](https://cloud.githubusercontent.com/assets/1244701/23703250/b53495aa-0407-11e7-84d4-d525b4650632.png)



3. Clear the BPartner field
![image](https://cloud.githubusercontent.com/assets/1244701/23703267/c3e207fe-0407-11e7-8a1f-bebb766c54ca.png)

**Comment by damianprzygodzki** [comment]
Case:
- new sales order
- checking a checkbox
- initialValue for whole documents not changed
- indicator bar is still green

**Comment by teosarca** [comment]
@damianprzygodzki  Mark and I just checked after your last commit.
Works as expected.

**Comment by teosarca** [comment]
thanks a lot !

**Comment by metas-mk** [comment]
Tested. Works as required. Thanks a lot. Closing.
