### ISSUE TITLE
Chrome is no longer offering to save passwords

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#511]
### Type of issue
Bug

### Current behavior
Try to login on https://w101.metasfresh.com:8443 
Chrome is not offering the saved password.
Fill the user and password and press login.
Chrome is not offering to save the password.
Logout
You are back to login page but Chrome is not offering any password.

### Expected behavior
Chorme shall offer to save the password.
Chrome shall be able to restore the saved password on login page.

This might help: http://stackoverflow.com/questions/2382329/how-can-i-get-browser-to-prompt-to-save-password

**Comment by damianprzygodzki** [comment]
Is it because not secure data encrypting. Localhost offering it without changes.

**Comment by cadavre** [comment]
Not related to project. Also Chrome recently updated their security policy and all input type="password" fields that are not on https:// are marked as unsafe and cannot be saved in password storage.

**Comment by teosarca** [comment]
for the records: Mark, briefly checked this on a server where we have signed certificates and still not working. He also tried from his mobile phone and it worked.
