### ISSUE TITLE
Included Document is not PATCHed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#517]
### Type of issue
Bug
### Current behavior
* Create a new order
* Create a new order line using batch input
* select the order line and "clear" (by pressing the X button) the Product field. You can do that in grid mode or in advanced mode. Will behave the same.
* The patch to set M_Product_ID to null is sent to server => OK

* Now edit the field again and but back the same product you had before
=> NO patch is sent to server => NOK

### Expected behavior
PATCH shall be sent for each change

### Steps to reproduce
See above.

Bellow are the screenshots which are showing the last endpoints called.
Remark there are no PATCH calls after typeaheads.... even though i really picked a product.

![image](https://cloud.githubusercontent.com/assets/1244701/23788412/fdd88bfe-057e-11e7-8985-09a85dedb0cf.png)

![image](https://cloud.githubusercontent.com/assets/1244701/23788420/0481d47e-057f-11e7-852d-2dc2dae343de.png)

**Comment by teosarca** [comment]
Found while testing/debugging for https://github.com/metasfresh/metasfresh-webui/issues/215

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

Repeated testcase from above:
* Patch is sent to server when editing the product field; setting the same product again after deleting it: OK
(=> works fine in both grid and advanced edit)
