### ISSUE TITLE
Document status not updated when line is changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#518]
### Type of issue
Bug

### Current behavior
* create a new order
* create a new order line
* edit the order line and clear the product => document becomes invalid so the red line is shown => OK
* delete the line
* the document red line is still there => NOK

Also you can improvise around "editing the order line".
Edit it in grid, edit it in advanced edit.
You will find that in some cases the header document status was not updated,
and the reason which I suspect is because for some of the endpoint calls, the frontend is not checking each document from response, but only the one which was in scope.

### Expected behavior
When in one of the endpoint responses, the backend is sending an update about the document header (even if the endpoint was called for a included document / tab row) the frontend shall honor it.

![image](https://cloud.githubusercontent.com/assets/1244701/23788763/b0062d08-0580-11e7-8871-33d7cd65e0f6.png)

**Comment by teosarca** [comment]
also, what i found out is, if i clear the product in order line, the line basically becomes invalid but frontend is flagging it (i.e. paint in pale red, red line on left).
Might be related or shall I create a different task for that?

**Comment by damianprzygodzki** [comment]
Related. Im gonna fix that both.

**Comment by damianprzygodzki** [comment]
@teosarca What ive found, after clearing Product from order line, there is no update about save status of order line (so it is for the front end as saved)

![screen shot 2017-03-10 at 10 32 21](https://cloud.githubusercontent.com/assets/5701744/23789863/ebc8e19a-057c-11e7-80d5-b64067c22955.png)

**Comment by teosarca** [comment]
update: as talked verbally with @damianprzygodzki , this issues seems to be induced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/517

**Comment by metas-dh** [comment]
Results of IT 1
tested on w101

* repeated the testcase above: header document status was updated correctly when deleting the orderline: OK
* tested different things with editing the order line, in grid & in advanced edit:  header document status was updated correctly (invalid / valid) after changes made: OK
