### ISSUE TITLE
Location Editor cannot read property bug

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#524]
### Type of issue
Bug
### Current behavior
After recording location and clicking outside the editor, a bug occurs (see screenshot)
### Expected behavior
To be bug free so that location can be saved.
### Steps to reproduce
window/123/

![image](https://cloud.githubusercontent.com/assets/13365687/23802219/eb611796-05b2-11e7-8384-1ab03bec1e38.png)

**Comment by chmieludaniel** [comment]
Most likely related to #294

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Tested w/ Location entries in business partner window and Location quick entries via Sales Order window. Closing.
