### ISSUE TITLE
Running a process from menu does not work

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#526]
### Type of issue
Bug

### Current behavior
* Click on menu
* In "Sales" category, pick "Reports"
* Click on "Revenue Busines Partner"
=> not starting but you get an error in console

NOTE: if you run exactly the same report from Sitemap, it works.

### Expected behavior
Shall work.

### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/1244701/23824902/4b167e58-0688-11e7-9ccf-85d0de7cc974.png)

![image](https://cloud.githubusercontent.com/assets/1244701/23824903/51e74546-0688-11e7-9680-b5f527db4ff7.png)

**Comment by metas-lc** [comment]
IT
ran the process from menu, using path  "Sales" category, pick "Reports" - "Revenue Busines Partner" => no errors OK
ran the process directly by searching after "Revenue Busines Partner" => no errors OK
