### ISSUE TITLE
Dashboard Target KPI "responsive

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#527]
### Type of issue
Feature request
### Current behavior
The Target KPI Line in the new Dashboard is not shown properly in small dimension screens, e.g. smartphone. 
### Expected behavior
Show each KPI in responsive mode.
### Steps to reproduce
Open Dashboard.

**Comment by teosarca** [comment]
Tested using Nexus 5 simulator. Works nicely.

![image](https://cloud.githubusercontent.com/assets/1244701/24009110/96ab0d32-0a7c-11e7-9306-fe46bf78d6b0.png)
