### ISSUE TITLE
Major Sidelist error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#528]
### Is this a bug or feature request?
Bug
### What is the current behavior?
Error when using side-list in Sales Order. Happens when double click selection NaN Exception.
`{timestamp: 1489328395795, status: 400, error: "Bad Request",…}
error
:
"Bad Request"
exception
:
"org.springframework.web.method.annotation.MethodArgumentTypeMismatchException"
message
:
"Failed to convert value of type [java.lang.String] to required type [int]; nested exception is java.lang.NumberFormatException: For input string: "NaN""
path
:
"/rest/api/documentView/NaN/layout"
status
:
400
timestamp
:
1489328395795`
#### Which are the steps to reproduce?
See above.
### What is the expected or desired behavior?
Working Sidelist.

![image](https://cloud.githubusercontent.com/assets/13365687/23848460/aceb71e2-07d7-11e7-95bd-27d6413dd31f.png)

**Comment by teosarca** [comment]
might be related with https://github.com/metasfresh/metasfresh-webui-frontend/issues/496

**Comment by teosarca** [comment]
note: did a quick test on dev-528 branch and seems to work

**Comment by metas-lc** [comment]
IT: 
go to sales order, select the side-list -> no error
double click on selection -> no error
OK

**Comment by metas-lc** [comment]
IT2:
go to sales order, select the side-list -> no error
double click on selection -> no error
(also tried with new sales order)
OK

go to Material Receipt Candidates, create a new one => you'll get a message with "Create not allowed"
after the message is gone, select the side-list => ok, no error
navigate to more Material Receipt Candidates through side list => ok, no errors
