### ISSUE TITLE
Broken drop-downs in combined Filed

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#531]
### Type of issue
Bug
### Current behavior
When typing Business Partner in combined field (Business Partner + Contact + Location), then when found, the field gets populated with all default stuff. This still works.
But, when that happens, the user got dropdowns before to directly select alternative entries for Contact + Location. This does not happen anymore.
### Expected behavior
Alternativ drop-down list automatically or via keyboard selection.
### Steps to reproduce
Try in Sales Order window window/143/

**Comment by Dunkat** [comment]
Please check if still happen, yesterday was fix in lookup behaviour #161 and I think it solved problem. When lookup field is filled automatically, dropdown isn't shown.

**Comment by cadavre** [comment]
Closing due to revamp in #600 .
