### ISSUE TITLE
KPI: maxime/restore when double clicking on title bar

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#533]
Double-clicking on draggable widget shall maximize it.
If it's maximized, it shall be restored.

![image](https://cloud.githubusercontent.com/assets/1244701/23861900/208fbc16-0814-11e7-9228-0c6a64bbee18.png)

**Comment by metas-lc** [comment]
IT:
- checked each KPI => works fine
- Double-click on widget maximizes it, double-click again restores it.
