### ISSUE TITLE
KPI: implement a non intrusive way to display KPI related errors

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#537]
### Current behavior
Case:
* elasticsearch server is down
* frontend is calling /data endpoint for each KPI each 10sec (by default)
* so from 10 to 10sec we get the error popup
That's totally annoying and the user can do nothing about it.

### Expected behavior
Find an non-intrusive way to flag those KPIs (draggable widgets) where an error occurred while fetching the data.
idea: Might be the title bar colored in pale red with some exclamation mark icon near it. When hovering on that exclamation mark the error text shall be displayed.
But if the designer has a better idea, we shall go with that.

![image](https://cloud.githubusercontent.com/assets/1244701/23907655/80ef984e-08da-11e7-9d60-e9b5f0ebd448.png)

**Comment by cadavre** [comment]
Part of #253 .

I would remove error notifications and add widget placeholder with some grayed-out "chart" icon and grayed-out text like "Error loading data".

**Comment by teosarca** [comment]
hi @cadavre ,
sounds good for me...
but i would also show the error message when hovering on it because else there is no way to find out why that KPI failed...

**Comment by cadavre** [comment]
I think we should go with what I described in https://github.com/metasfresh/metasfresh-webui-frontend/issues/253#issuecomment-278047555 .

If you had this `dev` mode we could always display notifications with click possibility (to display popup with detailed info). User doesn't need to read full error description as it doesn't change his life at all – once after all he/she cannot see widget. :)

**Comment by teosarca** [comment]
> If you had this dev mode we could always display notifications with click possibility (to display popup with detailed info). User doesn't need to read full error description as it doesn't change his life at all – once after all he/she cannot see widget. :)

Yes, but behind the "user" it's us all... 1st level support, 2nd level support, 3rd level support etc.
That's the reason why i don't feel the "dev" mode is the way.

On the other hand, i can say it again, i agree with you about the need of #253 .... we just have to gradually get to it :)

**Comment by cadavre** [comment]
@teosarca understood. I think we should use UI error elements to print only human-readable and pretty errors. That's why notification with only generic error is cool, lookup with user-friendly error texts are cool, inputs with validation errors are cool.

I just talked to @Dunkat and suggested to log all errors (that are regularly shown in notifications) to console. This way you (dev) will have always full error info and you'll be able to use apps like https://newrelic.com/browser-monitoring/features in the future.

**Comment by teosarca** [comment]
tested locally, works!
