### ISSUE TITLE
Confirm autocomplete Field entry in grid functionality

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#539]
### Type of issue
Bug
### Current behavior
When deleting and reentering a product in sales order line (grid view), the selected product cannot be confirmed w/ enter and saved in line, The line remains unsaved.
### Expected behavior
Select, confirm, save.
### Steps to reproduce
**Window:** /window/143/

![image](https://cloud.githubusercontent.com/assets/13365687/23916072/4b44cfbe-08eb-11e7-8855-93cdbd22fec4.png)

**Comment by metas-lc** [comment]
IT
1. create a new sales order, add a product
2. check the status of the order - saved OK
3. remove the product's name prom the line
4. check the status of the order - not saved OK (orderline is red)
5. add the product back (start writing the name, select the one you like with keyboard's arrows, press enter)
=> product is set, line saves, order status: saved OK
6. repeated the same case for purchase order
=> works the same OK
