### ISSUE TITLE
Don't use deprecated staleTabIds

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#540]
### Current behavior
All document changes responses were an array called staleTabIds.
That are was used to flag stale tabs on frontend side.
In meantime we refactored and restructured a bit the response....

### Expected behavior
We introduced "includedTabsInfo" which contains an array on "tab changes".
Each change might contain a property called "stale". If that property is set and it's true the tab shall considered stale.

See the screenshot below to picture the change....

![image](https://cloud.githubusercontent.com/assets/1244701/23946465/2d7c546e-0983-11e7-8425-be26efed42af.png)

**Comment by teosarca** [comment]
Blocked by https://github.com/metasfresh/metasfresh-webui-api/issues/252

**Comment by teosarca** [comment]
note: https://github.com/metasfresh/metasfresh-webui-api/issues/252 was integrated.

**Comment by metas-lc** [comment]
for IT: test after https://github.com/metasfresh/metasfresh-webui-api/issues/273 is done

**Comment by metas-dh** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/273 was tested successfully, closing this also.

https://github.com/metasfresh/metasfresh-webui-api/issues/252 & https://github.com/metasfresh/metasfresh-webui-frontend/issues/541 were also tested successfully.
