### ISSUE TITLE
Hide new and delete included documents when they are not available.

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#541]
### Current behavior
Atm, in an included tab
* the "Add new" button is always showed. If the user is not allowed to create a new record, the endpoint will fail when user will press on that button.
* the right click->Delete is always shown. If the user is not allowed to delete the record, the endpoint will fail.

### Expected behavior
Now we are communicating if the included documents can be created or deleted.
That information shall be used and in case it's not allowed the button shall be hidden.

![image](https://cloud.githubusercontent.com/assets/1244701/23946630/cfe351a8-0983-11e7-9c35-ca65afef2088.png)

**Comment by teosarca** [comment]
Blocked by https://github.com/metasfresh/metasfresh-webui-api/issues/252

**Comment by teosarca** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/252 was integrated

**Comment by damianprzygodzki** [comment]
#14

**Comment by cadavre** [comment]
I propose here to DISABLE button instead of HIDDING it. Just a good UX pattern.

**Comment by damianprzygodzki** [comment]
I found one problem. 

When i create the new row by pressing 'Add new' the includedTabsInfo.allowCreate is false, because it creates unsaved row -> OK.

When i fill mandatory fields, and patch to API, the saveStatus and validStatus turns to valid and saved -> OK 

But there is no update of includedTabsInfo even though all children docs are saved and the `add new` is hidden -> NOK.

**Comment by damianprzygodzki** [comment]
The next one.

- I create the new row by `Batch entry`, it appears, `add new` is allowed -> OK
- I toggle the inline editing on product lookup and removing value, the saveStatus turns to false, validStatus is false too, but there is no update for `includedTabsInfo` -> NOK

**Comment by damianprzygodzki** [comment]
And another one:

- I create the not saved new row (without filled mandatory fields), `includedTabsInfo.allowCreate = false` -> OK
- then i toggle the inline editing on product lookup and filling the input, the saveStatus and validStatus are true, but there is no update for `allowCreate`, there is no ability to add new row -> NOK

**Comment by damianprzygodzki** [comment]
I am leaving PR for check from your side. Thanks.

**Comment by teosarca** [comment]
@cadavre 
> I propose here to DISABLE button instead of HIDDING it. Just a good UX pattern.

now i understand what are you talking about.

Have to think because it might be that we need to differentiate between
* tabs where the "add new" or "delete" won't NEVER be available (because it's some data which is created and maintained by business logic ... e.g. Sales order -> Order tax) 
* tabs where "add new" is temporary not available because user has to fulfill some requirements (e.g. fill correctly the header first).

wdyt?

**Comment by cadavre** [comment]
I guess we're getting back to this:
https://github.com/metasfresh/metasfresh-webui-frontend/issues/14#issuecomment-244291614

:)

**Comment by damianprzygodzki** [comment]
Gridview new are described by another property in another call. I agree that is #14 thing, and if that buttons would be generated as regular widget, we will be able to _disabled it_ or _do not display_

**Comment by teosarca** [comment]
Quick tested:
* create a new sales order
* fill the mandatory fields, i.e. bpartner
* create new line button is missing => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/24724870/63f31b30-1a55-11e7-860e-bbcfb419d405.png)

**Comment by damianprzygodzki** [comment]
It is so weird, because i am doing exactly like You, new order, filling mandatory lookup (provisioning date is updating by ownself), and in patch response, there is no `includedTabsInfo` update.

**Comment by damianprzygodzki** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/288 blocks.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* if mandatory fields are not filled yet in e.g. new order or new bpartner, no Add new available for included documents: OK
* if all mandatory fields are filled, Add new for included document becomes available: OK
* if mandatory fields are not set correctly, and document is not saved, no Add new available for included documents: OK
* where it is not allowed to create new included documents, e.g. tab Vorgänge in bpartner, Add new is not available, no matter if mandatory fields in main document are filled or not: OK
* if mandatory fields in included document are not filled yet, e.g. tab address in bpartner,  no Add new is available to create another entry: OK
* where it is not allowed to delete entries, the Delete button is not available, e.g. tab Vorgänge in bpartner or orderlines of completed orders: OK
