### ISSUE TITLE
View's windowId is not matching the expected one

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#545]
### Type of issue
Bug 
### Current behavior
navigate through windows really fast, using back and forward buttons, will throw "View's windowId is not matching the expected one" error
### Expected behavior
navigate fast using back and forward buttons to work well, without errors
### Steps to reproduce

e.g. Select home button, open directly (without using brows the whole tree) the following windows:
- 143 (sales order)
- 540321 (pricelist)
- 139 (warehouse) 
- 140 (product)
now press back 3 times really fast
error:"Internal Server Error"
exception:"java.lang.IllegalArgumentException"
message:"View's windowId is not matching the expected one.↵ Expected windowId: 143↵ View: SqlDocumentViewSelection{viewId=4b3a1c45-6c46-4d9c-981f-09ba9479dcd1, AD_Window_ID=540321, tableName=M_PriceList, defaultSelection=DocumentViewOrderedSelection{uuid=4b3a1c45-6c46-4d9c-981f-09ba9479dcd1, size=11, orderBys=[DocumentQueryOrderBy{fieldName=M_PriceList_ID, ascending=true}]}}"
path:"/rest/api/documentView/143/4b3a1c45-6c46-4d9c-981f-09ba9479dcd1"

means it's expecting sales order but it's pricelist
**Window:** 
143 -> 540321 -> 139 -> 140

**Comment by metas-dh** [comment]
Results of IT1
tested on mf15 WebUI

* navigated through different windows really fast, used back and forward buttons: no error was thrown: OK
