### ISSUE TITLE
Clicking on grid view breadcrumb item does not work

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#550]
### Type of issue
Bug

### Steps to reproduce
* open any grid view, e.g. https://w101.metasfresh.com:8443/window/143
* the view is opened nicely, the viewId is appended to the URL => perfect
* now click again on the "Sales order" breadcrumb item (see screenshot below)
=> fails

![image](https://cloud.githubusercontent.com/assets/1244701/24074339/48e028c8-0c0f-11e7-85bd-195b225ef5c1.png)

![image](https://cloud.githubusercontent.com/assets/1244701/24074345/5ff92a96-0c0f-11e7-9602-878d742f0f63.png)

**Comment by metas-lc** [comment]
IT
for the following hierarchy: Quote-to-Invoice/Sales Orders/Sales Order
- if i press on Sales Order nothing happens OK
- if i press on Sales Orders i get a dropdown. I select Sales order and i get the same error "No view found for viewId=undefined" (first time only) NOK
- if i press on Quote-to-Invoice -> Sales Orders => same error NOK
(todo retest on monday)

**Comment by metas-lc** [comment]
for: /Sales/Sales Order
- select Sales Order => nothing happens OK
- select Sales => is the same problem: 
* select sales -> sales order => "No view found for viewId=undefined"

**Comment by metas-lc** [comment]
IT2
select Sales Order => nothing happens OK
select sales -> sales order =>  nothing happens OK
