### ISSUE TITLE
Not saved indicator although saved

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#553]
### Type of issue
Bug
### Current behavior
Not saved indicator although saved.
### Expected behavior
Saved indicator should be shown.
### Steps to reproduce
Open Window Warehouse. Create a new Warehouse. Then add a new Locator. Then press done in Locator modal overlay. You're back in the Main window of Warehouse the save indicator gets red and remains.

**Window:** /window/139/1000005

![image](https://cloud.githubusercontent.com/assets/13365687/24074882/dc469406-0c11-11e7-9ec0-7f09410265bb.png)

**Comment by damianprzygodzki** [comment]
Cannot reproduce that. My steps are:

- new warehouse
- filling all of mandatory fields: Name, Standort, Value (doc saved)
- adding new locator
- filling all of the mandatory fields (s. key, x,y,z)
- pressing done, locator saved, doc valid

**Comment by metas-mk** [comment]
@damianprzygodzki reproduced. happens when dimensions are identically recorded as one of the existing lines before (unique constraint). we will take care about that. thx for the info.
