### ISSUE TITLE
Respect saveStatus in connected modal.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#558]
### Type of issue
Bug
### Current behavior
Connected modal does not respect saveStatus
### Expected behavior
Should respect.

**Comment by metas-lc** [comment]
@damianprzygodzki Is this task testable? if yes, how can i test it?

**Comment by damianprzygodzki** [comment]
@metas-lc Yes, red bar inside modal, when mandatory fields are removed.

**Comment by metas-lc** [comment]
@damianprzygodzki Thank you!
IT
1. just opened modal: mandatory fields are blue  OK
2. set all mandatory fields
3. remove a mandatory field 
=> red bar appears and your field gets red OK
4. press done
=> "Do you really want to leave?" warning OK
=> if you select cancel you remain in the modal window OK
=> if you select ok, you get in the main window and the unsaved line is added OK

Tested in multiple windows: sales and purchase order, business partner, Product and warehouse
