### ISSUE TITLE
KPI Pie Chart on Start defect

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#561]
### Type of issue
Bug
### Current behavior
Dashboard Pie Chart KPI starts w/ cut off section. At the same time the vertical scroll bar is visible.
### Expected behavior
Start the KPI Pie Chart directly complete.
### Steps to reproduce
Open Dashboard an see.

![image](https://cloud.githubusercontent.com/assets/13365687/24187771/c002b728-0ede-11e7-960a-7ba73be42fa9.png)

**Comment by cadavre** [comment]
@metas-mk we're already in 2017-13 (no. of week needs to fit) milestone.

**Comment by Dunkat** [comment]
Cannot reproduce on my screen. @metas-mk could you describe steps to reproduce or provide your screen size?

**Comment by teosarca** [comment]
@Dunkat  1980x1020

**Comment by Dunkat** [comment]
Still cannot reproduce, checked on different size screen, checked log out and log in, please provide steps to reproduce because normally it seems to look good. Maybe it depends on browser or system. The more details the better.

**Comment by damianprzygodzki** [comment]
I've tried too, trying to crash that with fast changing viewport size, and not natural res (zoom >> and << 1x) and it looks good. Chrome, Firefox, Safari, OSX.

![screen shot 2017-03-23 at 14 55 48](https://cloud.githubusercontent.com/assets/5701744/24251410/6194f514-0fda-11e7-961b-6e934c39ef9e.png)

**Comment by teosarca** [comment]
note: also saw the issue on big screen but then, there was no time to investigate it. happens only sometimes.
let's wait for mark, might be that he knows how to reproduce it quickly.

**Comment by metas-mk** [comment]
moin all. @teosarca @Dunkat doe happen every time when i reload/ refresh the page. is reproducible. is now on windows 10 (100%) and Chrome. happens also on win7 and chrome. every time. after refresh takes about 10 seconds and then the kpi is "magically" repaired.

**Comment by Dunkat** [comment]
ahh ok I see the problem occure on very big screen

**Comment by metas-mk** [comment]
Tested. Works as required. Done. Closing.
