### ISSUE TITLE
Date attribute is not correctly rendered

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#567]
### Type of issue
Bug

### Steps to reproduce
* open receipt candidates
* receive some HUs
* edit the HU_LotNumberDate attribute and set a date
* check the screenshot how it's displayed

NOTE: somehow we have the same behaviour on regular document fields which are dates, but in that case after ~1sec the field is nicely formated.
Also it would be nice to fix that too, and display the date nicely from the beginning.

![image](https://cloud.githubusercontent.com/assets/1244701/24210332/6d2ad0b4-0f31-11e7-8aec-d6dddb8eac4b.png)

**Comment by damianprzygodzki** [comment]
It occured because i see that in data for selection attributes API is not delivering widgetType (as on documents it is needed to parse dates)

**Comment by metas-lc** [comment]
IT
1. open receipt candidates
2. receive some HUs
3. edit the HU_LotNumberDate attribute and set a date
=> date has this format: dd/mm/yyyy OK
4. create a new purchase order, set LotNumberDate
5. go to receipt candidates, receive HUs 
=> LotNumberDate is already set, same format (dd/mm/yyyy) OK
