### ISSUE TITLE
BPartner/Location/Contact widget layout issue

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#568]
### Current behavior
When the Contact is missing the Location is aligned to the right, were usually the contact shall be.

### Expected behavior
Always preserve the location position (i.e. keep it in the middle).

### Steps to reproduce
* createa new sales order
* set the bpartner, so everything will be filled
* take a look at Bill BPartner/Location/Contact field

![image](https://cloud.githubusercontent.com/assets/1244701/24210818/f00e5f9a-0f32-11e7-96e1-28dc9598d336.png)

**Comment by damianprzygodzki** [comment]
Is it okay?
![screen shot 2017-03-23 at 09 31 54](https://cloud.githubusercontent.com/assets/5701744/24238960/54a30338-0fac-11e7-94c1-d0e5d8aa5497.png)

![screen shot 2017-03-23 at 09 32 05](https://cloud.githubusercontent.com/assets/5701744/24238966/5e4b779e-0fac-11e7-98c0-51819d9a2968.png)

![screen shot 2017-03-23 at 09 33 01](https://cloud.githubusercontent.com/assets/5701744/24238970/61930ff2-0fac-11e7-9eed-3f16395b2982.png)

**Comment by metas-mk** [comment]
Hi @damianprzygodzki yes thats fine, thx.
besides the product packing screenshot. the combined product packing field has a larger "product" part 2/3 to 1/3 i would say roughly.

**Comment by teosarca** [comment]
thanks for take care.

i think we need more info in order to decide. Wondering how i are layouting those "composed" widgets?
I mean, how do u distinguish between "partner/location/contact" and "product/packingMaterial"...
Mark was suggesting, in case of "product/packingMaterial" to have have something like 1/3 for product and 2/3 for packingMaterial.
Now i am just wondering if this information shall come from backend or not, i.e. part of the layout response.
Wdyt?

**Comment by damianprzygodzki** [comment]
In my opinion we should define one consistent layout for all lookups. Or some rules, how to resize that.

- the first field, cannot has a ellipsis (it is text input) and be flexible while editing.
- we should remember that layout should be scalable, so it should work for every setup, doesnt matter how many fields you return from API

**Comment by damianprzygodzki** [comment]
> Now i am just wondering if this information shall come from backend or not, i.e. part of the layout response.

It shouldnt be. At all i think. As i said, it should be generic and consistent rule.

> I mean, how do u distinguish between "partner/location/contact" and "product/packingMaterial"...

I do not distinguish. I am dividing it roughly 1:1 (the text input and container for rest fields) but leaving it to be flexible with rules:
- text input should be at least 30% width
- rest fields should be at least 50% width
- each of rest fields should has ratio 1:1 to other fields

**Comment by teosarca** [comment]
I would also ask Mark about this.
But reading this discussion, my feeling is that we won't be able to have a general rule.
I can see following cases (but there might be more!):
1. Bpartner/location/address
2. BPartner/location
3. Product/PackingMaterial 
I somehow have the feeling that 2. and 3. would have a different layout...

**Comment by cadavre** [comment]
I guess that /layout shall define how many fields there will be. I.e. if you have BusinessPartner with 3 fields and InvoicePartner with 2 fields but first two are corresponding to BusinessPartner – if you want them to see identically you should send layout with three fields and always keep 3rd empty. It's kind obvious that in case of Product/PackingMaterial (always 2) we want to have 2nd field maxed to right instead of centered.

Current implementation on front-end is this way PROPER. It's up to API's /layout how to render it.

**Comment by teosarca** [comment]
The API is sending them as you described.
But the "thing" is not there, also have to consult with Mark.
The thing is that we might want the case 2. and 3. (which from frontend's point of view, there is NO difference, 2 fields provided in layout) to be rendered in different proportions just because usually the location is bigger and usually the PackingMaterial is a short text.

**Comment by metas-mk** [comment]
@teosarca @damianprzygodzki @cadavre 
seems to be the similar discussion as this one https://github.com/metasfresh/metasfresh-webui-frontend/issues/468. let's find a combined solution for both.

**Comment by cadavre** [comment]
Closing due to revamp in #600 .
