### ISSUE TITLE
Combined Field Sales Order BPartner drop-downs behavior

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#570]
### Type of issue
Bug
### Current behavior
In Sales Order creation, for a BPartner w/ more than one location or contact, the combined Field does not suggest the location nor contact alternatives automatically, The user cannot select other otopns.
### Expected behavior
Make it work again or provide alternative solution.
### Steps to reproduce
Try and see whats described.
/window/123

**Comment by cadavre** [comment]
Closing due to revamp in #600 .
