### ISSUE TITLE
DocumentNo field is not updated

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#579]
### Type of issue
Bug

### Steps to reproduce
* create a new BPartner
* fill mandatory fields: i.e. Name, CompanyName
* BPartner gets saved but the document no (i.e. the "Value") field is not updated, see screenshot below

![image](https://cloud.githubusercontent.com/assets/1244701/24323002/2a8bcdec-1177-11e7-8071-e7b8cc9b5698.png)

**Comment by metas-lc** [comment]
IT:
- create a new bpartner => value is between < and >
- add a name (note that at this step bpartner is not saved yet) => value is between < and >
- add a company name  (note that at this step bpartner is saved) => value is updated (does not contain < and > anymore)
