### ISSUE TITLE
grid view: Hide page navigation when there is only one page

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#58]
e.g. In the screenshot below, i think the page navigation is not needed:
@metas-mk  wdyt?

![image](https://cloud.githubusercontent.com/assets/1244701/19187994/897843b8-8c97-11e6-99d5-502b9fb6d878.png)

**Comment by damianprzygodzki** [comment]
We can - but imho to keep consistency (for example when you are navigating between different types of gridview, it is solid element of docs lists.

**Comment by cadavre** [comment]
I'm against. Pagination should always be there to keep user aware of records number (it works better than "Total items" which is precise number) and – as Damian mentioned – to keep UI consistent.
