### ISSUE TITLE
Manufacturing UI Planning/ Doing

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#580]
### Type of issue
Feature request
### Current behavior
Currently, there is no Manufacturing UI in metasfresh.
### Expected behavior
We need a Manufacturing UI that provides a nice and comprehensive way for the user at the machine/ manufacturing resource to do the work in a transparent and adjustable way.
### Workflow description
- The starting point is a generic grid view that shows all the Manufacturing Orders for filtered criteria (Warehouse, Date, Manufacturing Ressource, BOM Product ...)
- The user selects a line and presses the main "manufacturing" action button
- A modal overlay opens. The user sees the BOM explosion of the to-be-produced-bom-product selected in first window. The first line is the BOM product itself. all other lines in the indented hierarchy are the bom lines components. Co-Products/ By-Products are not indented but on same level as BOM-Product.
- If the user selects one of those component lines, then on the right side of the screen a HU Editor (similar to the one used in material receipt) is visible that shows all the Handling Units in the same Warehouse that can be used to issue for that selected component. The user can drag the Handling Unit and pull onto the left side (selected component line). A configuration window pops open (similar to stuff in Material Receipt) where the user can define how many units shall be issued.
- If the user selects a BOM-Product/ By-Product/ Co-Product line, drags that one on the Handling Unit editor on the right side, then automatically a default HU/TU/CU Configuration shall be created for the user (similar to receive step in material receipt candidates.

@cadavre Just first ideas for now. Can we talk about the further ideas/ steps to be taken (user experiance, design)?

**Comment by teosarca** [comment]
technically speaking, my idea is to extend the "view" endpoint and for a certain view we shall be able to have a detail view.
i.e. in our case that means
*  our main view will contain the BOM lines, where u will be able to drag and drop HUs you want to issue
* the detail view will actually be the HU editor: when a line from our main view is selected some endpoint shall be called to fetch the data for that selected line. i.e. will fetch the HUs which are eligible for for that BOM line

Ofcourse i have detail/prototype more but wanted to let you know about this idea and i am looking forward for your input.
