### ISSUE TITLE
Language Switcher for WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#587]
### Type of issue
Feature request
### Current behavior
There is no Possibility to switch the frontend language in WebUI
### Expected behavior
Provide a Language switcher for the user.

**Comment by cadavre** [comment]
There's one more "option" I would introduce in metasfresh webUI "settings" – timezone.
@teosarca

**Comment by damianprzygodzki** [comment]
Where we want to add it?

**Comment by cadavre** [comment]
I'd say to add dedicated "Settings" button above "Log out" with dedicated page for settings. For now there might be two but I guess in future it might extend.

<img width="497" alt="zrzut ekranu 2017-03-29 o 09 18 49" src="https://cloud.githubusercontent.com/assets/461796/24442945/c29c7640-1460-11e7-92d6-b9b96e09745d.png">

**Comment by damianprzygodzki** [comment]
I thought that there was already dedicated window for settings. Can we use it? Am i wrong?

**Comment by damianprzygodzki** [comment]
What about creating new endpoint (like /window/***) for pages that have different flow than regular generated windows, but still are windows `/page/***` i.e `/page/settings`.

It would be the same thing as regular window (data & layout provided from API) to allow you fully control it.

**Comment by cadavre** [comment]
/page/dashboard
/page/settings

I'm +1 for this.

Also for generating config from API. Wdyt?

**Comment by teosarca** [comment]
hi guys,

> /page/dashboard
> /page/settings

Are we talking about backend or frontend endpoints?
If we are talking about frontend, why having the "/page" prefix and not directly "/settings" ?
It would be much more easy for an advanced user to remember and use the URL directly...

**Comment by damianprzygodzki** [comment]
Yes, we are talking about /page/*** as about generic way to create pages that have other flow then /window/*** (document list -> single document).

The pages like dashboard and settings, should be generated from API to, in the same way as `windows`. So `page` prefix would be responsible for a bit different component then MasterWindow.

Hardcoding pages like settings would be tough to manage, and slow to development.

**Comment by teosarca** [comment]
good morning Damian,

now i got it.
You are right, but this is extending the concept a lot and on backend side we are not prepared for that :(.
e.g.
* for dashboard we would need to have support for KPI as standard widget/element.
* for settings, we would need to have some facade for all settings, which we don't.

Until then, i would suggest to create a settings page where we have this language dropdown, quick and dirty.
We can keep in mind your nice suggestions and prepare the grounds in nearest future.
wdyt?

**Comment by metas-mk** [comment]
@damianprzygodzki 
is the latest proposal of @teosarca ok for you?
taking out "metasfresh turn"

**Comment by damianprzygodzki** [comment]
Yeah, okay.

**Comment by damianprzygodzki** [comment]
Done and waiting for API adjustment.

**Comment by damianprzygodzki** [comment]
https://github.com/metasfresh/metasfresh-webui-api/issues/286

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* language switcher in Settings, WebUI: OK
* switching language, e.g. from Deutsch (Deutschland) to English (USA): lanugage change in menu: OK (did not check in detail, just if it works in general)
