### ISSUE TITLE
Get rid of intermediare debugging page

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#59]
Case:
* browse records in grid mode (e.g. invoice candidates)
* double-click on one of it to open it
* for a very short time you see following page => we shall get rid of it

![image](https://cloud.githubusercontent.com/assets/1244701/19188097/25cfbc0a-8c98-11e6-9331-7c7396308ea4.png)

**Comment by damianprzygodzki** [comment]
We are still "worki in progress". It is build from our dev server. We are testing lot of case with notifications so If we close task with notifications (it is open now for me, and Kasia also) we are gonna remove it for sure.
