### ISSUE TITLE
Locations not visible in Partner window

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#592]
### Type of issue
* Bug
### Current behavior
* If locations are added to a new partner they are saved in the DB but not displayed.
### Expected behavior
* They should be displayed
### Steps to reproduce
* Create a partner
* Add location to it, press Done
* => NOK: Location not displayed even if it was saved in the db.

Please check https://w101.metasfresh.com:8443/window/123/2156659 . THat partner has 3 locations.

![image pasted at 2017-3-29 16-31](https://cloud.githubusercontent.com/assets/16001442/24457094/d4de122c-149d-11e7-9b64-97170491a822.png)

**Comment by damianprzygodzki** [comment]
Cannot reproduce.

Created new partner (name and company filled)
- switched to tab Location, press add new
- modal showed, filled mandatory country field
- press done
- it appeared as a row

**Comment by damianprzygodzki** [comment]
Whatsmore, when i enter to your example, this 3 rows are displayed normally.

**Comment by metas-rc** [comment]
Now, after a client update, it also works for me. Closing this task.
