### ISSUE TITLE
DocAction bug when opening a document from references of another

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#593]
### Type of issue
* Bug
### Current behavior
* When opening a document that does not suppor docAction (e.g. Invoice candidate, Material Receipt Schedule, Shipment Schedule etc) from the references of a document that supports DocAction (e.g. Sales Order, Purchase Order)  there is an exception in the dropdown Get: 
exception
:
"de.metas.ui.web.window.exceptions.DocumentNotFoundException"

* Somehow it tries to load the docActions for the initial document(Order)  but in the current window (invoice candidate)
### Expected behavior
* DocAction to be loaded only when it's needed
### Steps to reproduce
* Create a Purchase Order with line, complete it
![steps 1 purchase order](https://cloud.githubusercontent.com/assets/16001442/24457930/39a24794-14a0-11e7-9dc3-6502f64242cc.png)

* Go to referenced document, select Material Receipt Candidates. 
![step 2 open material receipt candidate](https://cloud.githubusercontent.com/assets/16001442/24457940/4030c8f6-14a0-11e7-86ae-977c24797d35.png)

* Open the Material Receipt Candidate in single view ( double ckick).

* => NOK: in inspection I see the dropdown GET with DocumentNotFoundException. 

![steps 3 1 open doc single view - network](https://cloud.githubusercontent.com/assets/16001442/24457998/5f1e4324-14a0-11e7-928f-1125b403b596.png)

![step 3 2 console](https://cloud.githubusercontent.com/assets/16001442/24457997/5f1c3714-14a0-11e7-8f2b-ad0c3ae39f1a.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* retested opening a document (single view) from references of another (order => material receipt candidates, order => invoice candidate) : no more dropdown GET with DocumentNotFoundException in inspection, OK
* no other exceptions in inspections: OK
