### ISSUE TITLE
inform users that only Chrome is currently supported on login screen

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#594]
### Type of issue
Feature request

### Current behavior
you can log in with any browser
problem is that most testing is done on chrome at the moment and other browsers might not work

### Expected behavior
if user does not have supported chrome version he gets a message on login screen which informs him about that his browser might not be fully supported

**Comment by damianprzygodzki** [comment]
In my opinion it is not good to inform user that app is working only on chrome. I believe that on the other platforms it is working as well.

All of the dependencies we are using, are supporting most of modern browsers, and while development, im using also firefox and safari, to test things.

This limitation in my opinion is too drastic.

**Comment by cadavre** [comment]
> he gets a message on login screen which informs him about that his browser might not be fully supported

So I believe it's actually only about a small message on login screen.

One way or another, afaik, we're testing not only in Chrome, but also Firefox and Safari. I think it would be better to gather feedback about other browsers and also adapt them, Chrome isn't 100% market.

**Comment by cadavre** [comment]
"Your browser might not be fully supported.\n 
Please try Chrome in case of any errors."

**Comment by metas-dh** [comment]
Results of IT1
tested with w101 on Firefox

* try logging in: msg for user "Your browser might be not fully supported. Please try Chrome in case of any errors." is displayed underneath Login: OK
