### ISSUE TITLE
kpi disappears when minimize 

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#595]
### Type of issue
Bug
### Current behavior
bp group revenue comparison KPI is blank and the other ones a bit messy when you maximize one and minimize back before the data is reloaded
### Expected behavior
KPIs should look the same as before maximize-minimize
### Steps to reproduce
1. login
2. maximize for e.g. the second KPI (order lines / day)
3. wait for the data to be refreshed (i used inspection to see the data)
4. minimize it right away
=> for aprox 10s the first kpi is empty and the other ones look messy

![kpi1](https://cloud.githubusercontent.com/assets/16001666/24501699/4f4e6196-1553-11e7-83d8-ccc36f9c8846.png)

![kpi2](https://cloud.githubusercontent.com/assets/16001666/24501702/53452370-1553-11e7-9dd2-313a3a90a03f.png)

**Comment by teosarca** [comment]
suggestion to fix: preserve ALL KPIs as they are until next refresh.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* retested maximizing / minimizing different KPIs: all KPIs looked fine after minimizing again, nothing was missing or displayed messily; OK
