### ISSUE TITLE
cancel on "Do you really want to leave?" sends you 2 steps back

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#597]
### Type of issue
Bug
### Current behavior
selecting cancel on "Do you really want to leave?" sends you 2 steps back...sometimes
### Expected behavior
to stay on the current page
### Steps to reproduce
1. open a window like purchase order (181)
2. select home and go to business partner (123)
3. create a new one, add all mandatory fields (name and company name)
4. go to location tab and add a new one: add new -> done (don't set any location there)
5. (refresh the page so you have a red line for not saved bpartner)
6. press on "back"
=> "Do you really want to leave?"
7. select Cancel
=> you get in purchase order (or the window you chose at step 1)

**Window:** 181 -> 123

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* repeated testcase in different windows (address in bpartner, new CU-TU Zuordnung in product:  "Do you really want to leave?" & Cancel: remaining in the current window: OK
