### ISSUE TITLE
cu-tu allocation tab freezes

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#598]
### Type of issue
Bug
### Current behavior
- product's cu-tu allocation tab freezes when you want to change the TU
- date gets a wrong format
- after you press done, nothing happens when you want to press add new again (you have to refresh so you can get the not allowed message)
### Expected behavior
- modal in cu-tu allocation should not freeze
- date should have the right format
- if you have an unsaved docu, when pressing add new should get an error message that is not allowed
### Steps to reproduce
1. go to product window (140)
2. select an already existing one or create a new one and add all mandatory fields
3. go to cu-tu allocation subtab (second one)
4. press on add new, add TU, add date
=> notice the date format: 2017-03-23T00:00:00.000+02:00 NOK
5. try to change the TU with another one
=> window freezes  NOK
6. press done, ok on warning
=> line is red OK
7. press on add new 
=> nothing happens NOK

**Window:** 140

![cutu](https://cloud.githubusercontent.com/assets/16001666/24508591/88f74cf0-156c-11e7-878b-862e77cb2760.png)

**Comment by damianprzygodzki** [comment]
4. Date format is right, `03/03/2017`, how did You choose a date? 
5. Window is not freezing. But what is interesting. You are providing from API that validTo is not mandatory, but when it is not filled the document is not saved - thats why line is red. If you fill validFrom and validTo - no problem at all, document saved.
6. Add new working as expected.

**Comment by metas-lc** [comment]
i picked for e.g. this product /window/140/2005620
went to cu-tu allocation ad made the following, in this order:
add packing instruction G1
add valid from 
(then to freeze change the packing instruction)

i noticed that if you do it like this: add G1, add a qty>0, add valid from => works

**Comment by damianprzygodzki** [comment]
So it is backend issue in my opinion. There is nothing i can do.

**Comment by metas-lc** [comment]
checked again and it works
