### ISSUE TITLE
Action button remains gray if the process execution fails

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#599]
### Type of issue
Bug

### Expected behavior
Quick actions button shall be grayed only while processing.
After processing (failure or not) the button shall be green and clickable again.

### Steps to reproduce
NOTE: atm, i don't have precise steps to reproduce because i just got this issue while developing new things.
* have a document view
* click on quick actions button
* suppose the "POST /rest/api/process/<processId>" fails
=> the quick actions button remains gray => NOK
=> the quick actions button is clickable even if is gray => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/24512227/afdbb55e-1576-11e7-9630-8d0c4068dbdb.png)

**Comment by teosarca** [comment]
Here is another case which shall be fixed:
* have a document view
* selected a row so you will have the quick action green
* open another tab and logout
* go back to your first tab and press the action button
* you are forwarded to login screen => OK
* do login
* you are back to your grid view, the selected row was preserved but the action button is gray => NOK
* click on some other rows, click back to your row => still gray
* F5 => OK

**Comment by teosarca** [comment]
quick tested on HU editor, trying to create a material receipt.
The button now turns to gray for a second and then it's back.

NOTE: when fixing, also pls make sure, if the button is grey/disabled it shall not be pressable.


![image](https://cloud.githubusercontent.com/assets/1244701/24719338/09cb365a-1a42-11e7-9160-c4a7580529a6.png)

**Comment by damianprzygodzki** [comment]
I cannot reproduce clickability of greyed out button.

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
IT
i could reproduce Teo's case:
1. open Material Receipt Candidates (540196)
2. select a line => button is grey
3. open another tab and logout 
4. in the first tab select the action button, login => action button is grey NOK
5. click on some other rows, click back to your row => all buttons are still grey NOK
F5 => OK

note: on step 4, if i press the gray button modal window opens (i guess NOK?)

**Comment by damianprzygodzki** [comment]
@metas-lc In reference to 2nd point, after selection row button is grey? (Mistake or NOK?)

**Comment by damianprzygodzki** [comment]
If so, i've added fix for auth problems. Should be okay.

**Comment by metas-lc** [comment]
@damianprzygodzki yes, sry. By mistake. on step 2 the button is green

**Comment by metas-lc** [comment]
IT2
repeated testcase. Works fine: on login the button is green OK
