### ISSUE TITLE
Scan control for manufacturing order action issue/ receipt window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#601]
### Type of issue
Feature request
### Current behavior
The User has no possibility to scan a barcode to open the manufacturing execution window (issue, receipt) in webUI.
#### Which are the steps to reproduce?
Try it.
### What is the expected or desired behavior?
When in window manufacturing order grid view, the user shall be able to press a button/ action and then scan a barcode (i believe it should be a modal overlay that then only allows the scan). The Barcode will be read from the "Bestellkontrolle" report. The Barcode confirmation will automatically open the detail window for action issue/ receipt in webUI. In case the Barcode is not found, the user shall be informed.

belongs to https://github.com/metasfresh/metasfresh-webui-api/issues/280

**Comment by damianprzygodzki** [comment]
Is it a widget? It will be supported in regular way, by layout and data? Or WS like devices? Can we start implementation?

**Comment by damianprzygodzki** [comment]
Closing due to duplicate #655.
