### ISSUE TITLE
Mandatory lookup fields are not marked as error

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#604]
### Current behavior
Consider a lookup field which is mandatory.
Initially is displayed with a blue border around it => OK
Write something random (which could not be resolved) in that field and then move to another field.

Problem:
* the field has an invalid value in it (on backend the value is still null because it's not resolved)
* user has NO idea that there is an issue with that field

### Expected behavior
Field shall be marked with red border.
I am open to any other suggestions which could boot UX.

### Steps to reproduce
* open Receipt candidates window
* call "Receive HUs" quick action
* write something in one of the first 2 fields and move to another field.

![image](https://cloud.githubusercontent.com/assets/1244701/24615407/d415b582-1896-11e7-86a0-8711507cecce.png)

**Comment by metas-mk** [comment]
@Dunkat @damianprzygodzki 
Seems to have got broken. The first quick test looks like this:
![image](https://cloud.githubusercontent.com/assets/13365687/24752658/35e0acba-1acf-11e7-9863-e410f56b1232.png)

**Comment by metasnw** [comment]
found an issue today with this case:
1. sales order => new
2. type a partner name that does not exist
3. click on "Create New Partner"
4. enter the data needed for a new partner
5. done
6. OK: new partner is inserted into field parnter
7. NOK: field remains RED although its OK

![image](https://cloud.githubusercontent.com/assets/16079655/24809251/38cb7680-1bbf-11e7-9ff1-3fc8ab2225a5.png)

**Comment by metas-lc** [comment]
IT
I. red mandatory fields
1. open Receipt candidates window
2. call "Receive HUs" quick action
3. write something in one of the first 2 fields and move to another field 
=> the field is red and if you press on start you get the error "Mandatory field not filled..." OK

II. filling in new data
1. create a new order and start writing a bpartner name which exists => field is not red OK
2. start writing a bpartner name which doesn't exists => field is red OK

III. filling in a new bpartner

1. sales order => new
2. type a partner name that does not exist
3. click on "Create New Partner"
4. enter the data needed for a new partner
5. done
=> OK: new partner is inserted into field parnter
=> OK: field is not RED

**Comment by teosarca** [comment]
This task seems to be broken again.

Test case:
![image](https://cloud.githubusercontent.com/assets/1244701/26188610/e05bd29c-3ba8-11e7-8494-c94df0a9c33c.png)

![image](https://cloud.githubusercontent.com/assets/1244701/26188638/0efa128a-3ba9-11e7-8f86-a06f03e7891d.png)

![image](https://cloud.githubusercontent.com/assets/1244701/26188700/5a8fda22-3ba9-11e7-87d2-64a5d99cd921.png)

**Comment by teosarca** [comment]
Forget about it. On https://github.com/metasfresh/metasfresh-webui-frontend/issues/600 will be solved as follows: when u click outside and the value is not correct/resolved the frontend will put back the old value.
