### ISSUE TITLE
When opening a process panel, the first field shall be focus by default

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#605]
### Current behavior
When opening a process panel, none of the fields are focused by default.
So user has to click on first field and start filling it.

### Expected behavior
As the task summary says, just focus first process panel field.

### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/1244701/24652435/91abc67e-193a-11e7-9d6f-4fe6291f2140.png)

**Comment by metas-lc** [comment]
IT
1. go to Manufacturing Order, select an entry
2. select issue/receipt
3. on the dropdown select Receive HUs
=> Receive HUs process panel opens and the first field is focused OK
