### ISSUE TITLE
Included subtab height 100% broken again.

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#609]
### Type of issue
Urgent Bug
### Current behavior
Height 100% broken again.
### Expected behavior
Make it 100% again.
### Steps to reproduce
Open a window w/ included subtab.

![image](https://cloud.githubusercontent.com/assets/13365687/24673451/afbfd73e-1978-11e7-97d1-26dd845beda8.png)

**Comment by damianprzygodzki** [comment]
For future repetition. The tab height sizing is workarounded and sensitive. Watch out when changing wrapper for app like that now (NotificationsHandler).

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* Included subtab height 100% again (e.g. new order, new bpartner etc.): OK
