### ISSUE TITLE
Detail view not opening w/ doubleclick

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#610]
### Type of issue
Bug
### Current behavior
Sometimes, when opening a window in grid view, then doubleclick on the row. It seems to freeze, and detail view does not open.
### Expected behavior
Fix the Bug and open the Detailed view.
### Steps to reproduce
See current behavior.

![image](https://cloud.githubusercontent.com/assets/13365687/24673715/8b9a3614-1979-11e7-8570-3d3d35208c44.png)

**Comment by metas-mk** [comment]
Here another case just happened.
![image](https://cloud.githubusercontent.com/assets/13365687/24673936/2d3b2da2-197a-11e7-8531-b106ebe8ef8c.png)

**Comment by damianprzygodzki** [comment]
I couldn't reproduce that. Tried with different window types, and throttling.

**Comment by tomaszfryc** [comment]
I can’t reproduce this issue. Tried with different window types, different browsers (on different OS - mac, windows) and throttling.

**Comment by Dunkat** [comment]
I also tested but cannot find this error

**Comment by metas-lc** [comment]
IT OK
cannot reproduce
