### ISSUE TITLE
When the language is switched widgets shall be invalidated/refreshed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#614]
### Current behavior
* go to settings page: https://w101.metasfresh.com:8443/settings
* switch the language
* open the menu => menu is in old language => NOK

### Expected behavior
* menu shall be displayed using current language
* if there are any other widgets which are language dependent, they shall be invalidated or refreshed directly.

Pls ping me if it's not a quick win.

**Comment by teosarca** [comment]
This issue is a follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/587

**Comment by teosarca** [comment]
quick tested:
* before actual test, pls create some material receipts (via HU editor)
* check the Notifications, you shall have some notifications for generated receipts
* go to settings and change the language
* check the notifications, they are NOT translated => NOK

NOTE: pls create material receipts, because for those i know for sure the notification message is translated.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* switch the language in settings: menu is displayed in new language (for most entries, some are missing for EN, same in Swing, e.g. Preisliste or Material Vorgang): OK
* switch the language in settings: notifications are displayed in new language: OK
