### ISSUE TITLE
delete option missing after add new

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#616]
### Type of issue
Bug
### Current behavior
- cannot delete a line right after i added it using add new
- add new is hidden in some cases too
(refresh the page and it will work)
### Expected behavior
be able to delete a line after you added it
don't hide add new
### Steps to reproduce
add a new line in sales order => i cannot delete it. 
refresh the page => then works

also adding a new location in bpartner => add new button + delete are hidden

**Window:**
window/143/1004994
window/123/2156601

**Comment by teosarca** [comment]
NOTE: when loading an existing document the New/Delete is missing because of this issue https://github.com/metasfresh/metasfresh-webui-api/issues/289 .
Just documenting here to make sure you are aware of the other problem which is on backend side.

**Comment by damianprzygodzki** [comment]
I've improved a bit merging of includedTabsInfo. I saw that there are sometimes issues with objects merging - it cant be merged in fully generic way, but more important is to be stick to the assumption that we are communicate only changes in model.

**Comment by metas-lc** [comment]
IT
checked again order and bpartner windows and delete option is visible after you use add new OK
