### ISSUE TITLE
Done button is not responding

### ISSUE THREAD

**Issue by metas-dh** [metasfresh/metasfresh-webui-frontend#618]
### Type of issue
Bug 
### Current behavior
The Done button is not responding when clicking it.
### Expected behavior
Done button should close the window.
### Steps to reproduce
* in bpartner, tab Address, click Add new
* add a new address, set e.g. country and street
* click Done: nothing happens, button seems to be read-only
* when you refresh the page, the new entry for address was created

**Comment by teosarca** [comment]
fixed by
https://github.com/metasfresh/metasfresh-webui-frontend/commit/50b53c18bcd63494ebbd08bf54054efc99c0116b

https://github.com/metasfresh/metasfresh-webui-frontend/commit/774355208238bc1518c10553d90c0ec7f3228ce5

**Comment by metas-lc** [comment]
IT OK
- repeated the testcase 
bpartner, tab Address, click Add new
add a new address, set e.g. country and street
click Done: modal closes, line is added
