### ISSUE TITLE
When deleting a newly created document, frontend shall not ask the user if he/she wants to leave the page

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#620]
### Type of issue
Bug

### Steps to reproduce
* create a new sales order, i.e. https://w101.metasfresh.com:8443/window/143/new
* try to delete it
* frontend asks me if I want to delete it => OK
* i press Delete
* frontend asks me if I want to leave the page => NOK,

### Expected behavior
In that case,  it shall not ask because it's pointless and annoying.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* deleting newly created document: after pressing Delete, no question whether i  want to leave the page: OK
* newly created document is deleted, and i get back to sales orders / bpartners or what i started creating: OK
