### ISSUE TITLE
Implement included view support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#621]
### Type of issue
Feature request

### Expected behavior
From now on, our view rows *might* support an included view (similar to attributes).
If the included view is supported, the row has the "supportIncludedViews" to true. Else the flag won't be set at all.

If a given row has an included view, when user is selecting that row, frontend shall:
* fetch the viewId: http://w101.metasfresh.com:8081/swagger-ui.html#!/document-view-rest-controller/getIncludedViewUsingGET
* using that viewId, it shall display the included view in some right side panel (similar to attributes)

### Steps to reproduce
Our current test case is:
* open manufacturing order view: https://w101.metasfresh.com:8443/window/53009
* select a manufacturing order where u can call "Issue/Receive" quick action
* select a line where you can issue raw products (i.e. BOMType is COmponent)
* that line shall have the supportIncludedViews=true
* at this point, the frontend shall fetch the included viewId and it shall display it to user

**Comment by cadavre** [comment]
How will we differentiate if it should be document (attributes?) or gridview (HUs)?

**Comment by damianprzygodzki** [comment]
Should we think about displaying attributes and gridviews at the same time? There is no place for that, should we display it one below another?

**Comment by cadavre** [comment]
Not the same time, but we might have attributes (for HU editor) and gridview (for Manufacturing).

**Comment by metas-mk** [comment]
@cadavre Yes, pls. We are up-to-date. We will go w/ your last proposal. thx.

**Comment by metas-mk** [comment]
belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/580

**Comment by damianprzygodzki** [comment]
Closing due to deprecation and rest of the case will be proceeded in #630
