### ISSUE TITLE
frontend: refactor /process/start response

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#628]
We refactored the /process/start endpoint's respone as described here: https://github.com/metasfresh/metasfresh-webui-api/issues/294 .

Pls adapt the frontend to it, because more "action"s will come.

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
IT
tested together with https://github.com/metasfresh/metasfresh-webui-api/issues/294
OK
