### ISSUE TITLE
Open docLists side by side in QuickAction response.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#630]
### Type of issue
Feature request

### Expected behavior
New handling of process result. 

After issuing 54009 document there should be opened another docList side by side to current.

**Comment by damianprzygodzki** [comment]
#628 blocks it

**Comment by damianprzygodzki** [comment]
#628 integrated, waiting for the API.

**Comment by teosarca** [comment]
On next rollout we will have another action type called "openIncludedView".

e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/25009538/a5417f80-206f-11e7-8f91-25678ceb5071.png)

**Comment by teosarca** [comment]
@damianprzygodzki  backend is ready

**Comment by damianprzygodzki** [comment]
- `supportIncludedView` property is missing
- `closeIncludedView` action response type is missing

**Comment by metas-lc** [comment]
IT
1. open manufacturing order and select an existing one
2. press on issue/receipt
3. select a component (CO), press on Issue HUs
=> the modal somehow splits and on the right side you can see the HUs you can issue
=> you can select anywhere outside the list from right and it hides
OK
