### ISSUE TITLE
Minor grid view layout tweaks

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#631]
please vertically center,
* the breadcrumb text and home icon
* the button text with it's icon. Currently the icon is a bit up.
* please vertically center the table header text. Now it's a bit under.

PS: i know those might be quite not observable, but after you see it, you cannot unsee it :)

![image](https://cloud.githubusercontent.com/assets/1244701/24924933/3a314f5c-1eff-11e7-819e-deb07173ae6d.png)

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
IT
icons, texts and buttons are aligned and centered OK
