### ISSUE TITLE
Sidelist Fontsize too small

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#636]
### Type of issue
Feature Request
### Current behavior
The Sidelist Font size is too small.
### Expected behavior
Should have the same Font size for CRTL-5/6 as in CTRL-1
![image](https://cloud.githubusercontent.com/assets/13365687/24978097/b6a85000-1fcf-11e7-8fc1-a8e1a39d98a2.png)

**Comment by cadavre** [comment]
@metas-lc can be closed?

**Comment by metas-lc** [comment]
IT
menus from ctrl+1, 5 and 6 have the same font size OK
