### ISSUE TITLE
CTRL+1 and keyboard navigation left-right not working anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#637]
### Type of issue
Bug
### Current behavior
Press CTRL+1. Press arrow down, works. Press arrow right, does not work.
### Expected behavior
Navigation w/ arrows shall work again.

![image](https://cloud.githubusercontent.com/assets/13365687/24978219/2a2bd510-1fd0-11e7-9824-d8f2307b7803.png)

**Comment by metas-lc** [comment]
IT (repeated the testcase above)
Open a window
Press CTRL+1
Press arrow down => works. 
Press arrow right => works.
select something else, press ctrl1 again, directly press arrow right => works.
