### ISSUE TITLE
Navigation shortcut ctrl+2 is broken

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#639]
### Type of issue
Bug
### Current behavior
ctrl+2 is not working anymore to open the navigation
### Expected behavior
shall open the navigation again
### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/13365687/25004851/b1413a14-2056-11e7-98ac-92ed9ebb38b7.png)

**Comment by metas-lc** [comment]
IT: ctrl+2 opens navigation OK
