### ISSUE TITLE
/documentReferences endpoint called when not necessary

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#64]
Case:
* just open any document
* /documentReferences is called

=> NOK - we shall call this endpoint only when it is needed. And it's needed only when the menu is actually shown. More, it shall be called each time the menu is shown.
Reasons:
* this endpoint might be quite expensive so we shall avoid by all means to call it when is really not needed
* the results might change quite frequently (i.e. somebody linked a document to this one) so we shall check it each time before displaying.

![image](https://cloud.githubusercontent.com/assets/1244701/19399614/141364b2-925b-11e6-89d8-72101cc8ca1a.png)

**Comment by damianprzygodzki** [comment]
@teosarca  @cadavre I understand that documentAction should not be downloaded in window creation, am i right?

**Comment by cadavre** [comment]
It should be called when user click on Menu button, not on document creation – true.
