### ISSUE TITLE
HOME/END keys not working in process parameter field when opened from view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#645]
### Type of issue
Bug

### Steps to reproduce
e.g.
* open material receipt candidates
* call a quick action which has parameters (e.g. Receive HUs)
* click inside of any parameter fields which has some text
* press keyboard's HOME or END
** cursor is not moved to the beginning or at the end of the text => NOK
** instead the material receipt candidates view is moved to first/last page => NOK

Same thing happens when you press PageUp/PageDown => view is navigated

![image](https://cloud.githubusercontent.com/assets/1244701/25063622/46b2c242-21f2-11e7-8267-c6f9a6bc7725.png)

### Expected behavior
* when inside a field, all keys shall work naturally (HOME shall move the cursor to the beginning, END to the end etc)
* no matter what, the key press shall not leak to underlying view

**Comment by metas-lc** [comment]
IT
1. go to material receipt, select a line and receive HUs
2. click inside of any parameter fields which has some text
3. press keyboard's HOME 
=> you get to the start of the text OK
=> nothing happens in the view OK
4. press keyboard's END 
=> you get to the end of the text OK
=> nothing happens in the view OK
5. press keyboard's pageUp and pageDown 
=> nothing happens OK
=> nothing happens in the view OK

Regression
1. go to material receipt window 
2. press keyboard's pageDown 
=> you are sent on the next page OK
3. press keyboard's pageUp
=> you are sent on the page before OK
4. press keyboard's End
=> you are sent to the last page OK
5. press keyboard's Home
=> you are sent to the first page OK
