### ISSUE TITLE
windowId shall be handled as a string and not as a number

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#649]
### Current behavior
It seems the frontend code is handling the windowId as a number.

### Expected behavior
The windowId shall be handled as a string and it shall never be parsed to integer.

### Steps to reproduce
NOTE: it cannot be reproduced on current master, i found this issue while developing/experimenting some new approach.

Steps to reproduce were:
* open receipt candidates
* try to receive some HUs, NOTE that the "HU editor"'s windowId is "huEditor".

Bellow are the screenshots:
![image](https://cloud.githubusercontent.com/assets/1244701/25170579/b98f68ac-24f3-11e7-8bfa-e3bdd450aaed.png)

**Comment by metas-lc** [comment]
IT
since we don't have any windowID that is string i just opened a window "aaa" to check how the layout on preview looks like: "...documentView/aaa.." (as you can see in the picture above, before it was NaN) OK
