### ISSUE TITLE
404 errors for non-existing pages

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#651]
### Non-existent doc
`/window/143/9876`

**Current behaviour**

Redirect to windowId gridview.

**Expected behaviour**

?

### Non-existent window type
`/window/98766`

**Current behaviour**

Display blank page.

**Expected behaviour**

?

## Discussion

What are expected behaviours here? We got 1st case (redirect) covered but not 2nd (blank page). We could unify it by:

1. Maybe redirect to `/sitemap` if no page was found? (For me redirects are poor.)
2. Display generic 404 page. (Preferred as for user would know what happened with his URL.)

**Comment by teosarca** [comment]
For me it's fine to have some 404 page.... but that page shall also have a menu or some links to allow the user to navigate to dashboard, sitemap etc.
I would avoid just showing an 404 page and then the user shall edit/change the URL in order to get somewhere back.

wdyt?

**Comment by teosarca** [comment]
Quick test case:

* browse a non existing product, e.g. https://w101.metasfresh.com:8443/window/140/99999999
* you got the 404 error page => OK
* the breadcrumb is empty => ehhh, but let's say we can live with that


* open the actions menu, you got an error because following endpoint failed: https://w101.metasfresh.com:8443/rest/api/window/140/notfound/actions => NOK
![image](https://cloud.githubusercontent.com/assets/1244701/25302604/2fc26670-274a-11e7-8107-bbc956c1b0bd.png)


* open the Menu and from there click on "Product": the breadcrumb is displayed but the 404 page is still there (also the URL) => NOK
![image](https://cloud.githubusercontent.com/assets/1244701/25302603/17d8e3b8-274a-11e7-88dd-d8779763a4fa.png)

**Comment by damianprzygodzki** [comment]
> open the actions menu, you got an error because following endpoint failed: https://w101.metasfresh.com:8443/rest/api/window/140/notfound/actions => NOK

What is expected behavior here? We should fetch actions for not existing document? Will it change something?

**Comment by damianprzygodzki** [comment]
I cannot reproduce that after clicking on product, that is something freezing. After clicking 'Product' from home menu there is redirect to `http://localhost:3000/window/140?viewId=140-f7f157df-11b1-45e2-9d79-31c7eb6d9525&page=1`

**Comment by teosarca** [comment]
question about breadcrumb: how hard is to have the breadcrumb build when possible?
e.g.
![image](https://cloud.githubusercontent.com/assets/1244701/25328147/76223f64-28df-11e7-8c6e-652c48251d85.png)

**Comment by teosarca** [comment]
update: i've also quick checked for the case when the windowId is missing and then i am pressing the Actions Menu => i get the same error => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/25328236/c9477e5c-28df-11e7-8ef9-4e6d23b0151a.png)

**Comment by damianprzygodzki** [comment]
Found an issue, sidelist now has 404 error page.

**Comment by metas-lc** [comment]
IT
1. if i go to a non existing order or product (e.g. /window/140/99999999) i get
- 404 Document not found OK
- action menu, home button and breadcrumb OK
- no error messages OK

2. if i try to navigate somewhere else from there (e.g. home button warehouse, or using back button)
- no errors OK
- the corresponding window opens OK

3. if i try to open a non existing window (e.g. /window/aaa) i see:
- 404 Document not found OK
- action menu and home button (breadcrumb is missing) OK
- no error messages OK

4. if i try to navigate somewhere else from there (e.g. home button pricelist, or using back button)
- no errors OK
- the corresponding window opens OK
