### ISSUE TITLE
Honor openIncludedView's viewType property

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#653]
### Type of issue
Feature request

### Current behavior
When opening an included view, the layout endpoint is always called with viewType=grid

### Expected behavior
the "openIncludedView" action is providing the viewType.
That viewType shall be used when opening the included view.

![image](https://cloud.githubusercontent.com/assets/1244701/25178390/49c817c4-250e-11e7-919d-cf314200dca9.png)

**Comment by metas-lc** [comment]
IT
viewType in layout is includedView OK
