### ISSUE TITLE
Handle process layout type field

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#655]
### Type of issue
Feature request

### Current behavior
At the moment, all process parameters are rendered as a modal panel.

### Expected behavior
on http://w101.metasfresh.com:8081/swagger-ui.html#!/process-rest-controller/getLayoutUsingGET_2 we introduced a new field called "layoutType".
It can take one of the following values
* "panel" => the process parameters shall be rendered as they are now
* "singleOverlayField" => in this case we assume the process has ONLY ONE parameter which shall be rendered like here:
![image](https://cloud.githubusercontent.com/assets/1244701/25181807/65549442-251b-11e7-8a2e-8ed90f92a3d1.png)

### Steps to reproduce
From HU editor, call Barcode quick action. That action shall be "singleOverlayField".

**Comment by metas-lc** [comment]
IT
opened barcode => layoutType:"singleOverlayField" OK
