### ISSUE TITLE
Selected grid row and quick actions not consistent after closing a modal

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#656]
### Type of issue
Bug

### Steps to reproduce
* open a grid view, e.g. manufacturing orders: https://w101.metasfresh.com:8443/window/53009
* press on Issue/Receipt quick action
* a modal is displayed => close it
* back to grid view:
** no row selected
** quick actions button active with "Issue/Receipt" as default
** press on it again => the modal is opened again

![image](https://cloud.githubusercontent.com/assets/1244701/25186138/f35ccf8c-2527-11e7-89cf-4f2e2cc85190.png)

### Expected behavior
It shall preserve the selected rows or it shall refresh the quick actions, which one is easier (for now).

**Comment by metas-lc** [comment]
IT
repeated the testcase above:
1. open a gridview like material receipt candidates or manufacturing and select the green button
2. select done
=> the row is still selected and button still green OK
3. select the green button again
=> it opens for the selected line OK
4. refresh the page
=> no line is selected and button is grey OK
