### ISSUE TITLE
Manufacturing Order Issue/Receipt is not displaying the attributes

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#657]
### Current behavior
Manufacturing Order Issue/Receipt is not displaying the attributes

### Expected behavior
Shall display the attributes on rows where attributes are available

### Steps to reproduce
* open manufacturing order view
* call Issue/Receipt action
* browse some lines (i.e. where u have some HUs issued)
* the attributes shall be displayed (when available)

![image](https://cloud.githubusercontent.com/assets/1244701/25205230/2705be1a-256a-11e7-9589-6f88ff88de1a.png)

**Comment by metas-lc** [comment]
IT
attributes are displayed on LUs and TUs
