### ISSUE TITLE
Double-clicking on included view row shall not open the document

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#659]
### Type of issue
Bug

### Current behavior
When double clicking on an included view row the document is opened under current modal

### Expected behavior
Double clicking on an included view row shall do nothing.

### Steps to reproduce
* open manufacturing order
* click on a COmponent line
* click Issue HUs
* double click on one of the HUs
=> the HU is opened under that modal => NOK

**Comment by metas-lc** [comment]
IT 
repeated steps above:
1. open manufacturing order
2. click on a COmponent line
3. click Issue HUs
4. double click on one of the HUs => nothing happens OK
