### ISSUE TITLE
Service not available not detected on login

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#661]
### Type of issue
Bug

### Expected behavior
Service not available shall be detected and the "server not available" overlay shall be displayed

### Steps to reproduce
![image](https://cloud.githubusercontent.com/assets/1244701/25228597/ab80624c-25d5-11e7-981a-07ca83235f5e.png)

**Comment by teosarca** [comment]
NOTE: the issue was found while Lili was testing https://github.com/metasfresh/metasfresh-webui-frontend/issues/599 and in meantime we were doing a rollout (so server was down)

**Comment by damianprzygodzki** [comment]
I am not sure that is a bug. Connection error screen is to preserve users data, when problems appearing while working on.

If we want to show that API is not working on login screen, we should show it in other way. @cadavre wdyt?

**Comment by teosarca** [comment]
@damianprzygodzki  i think u are right, it shall be displayed as a regular error.
But nevertheless, it shall not remain silent :)

**Comment by damianprzygodzki** [comment]
![screen shot 2017-04-20 at 14 59 14](https://cloud.githubusercontent.com/assets/5701744/25231928/f5dad26a-25d9-11e7-99bf-bceb9d3a857d.png)

**Comment by metas-lc** [comment]
IT 
i don't have the connection problem message

![login](https://cloud.githubusercontent.com/assets/16001666/25239053/aaa52cf0-25f7-11e7-91a3-85508965f32a.png)

**Comment by damianprzygodzki** [comment]
Didn't merge accidentally.

**Comment by teosarca** [comment]
tested on localhost. works nicely
