### ISSUE TITLE
process doesn't open directly

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#664]
### Type of issue
Bug
### Current behavior
while you are on Dashboard, if you select home, write Revenue Busines Partner and select it to open, nothing happens. If you select something else, then the process window opens
### Expected behavior
process shall open when i select it
### Steps to reproduce
1. while you are on the main page with the KPIs, select the home button 
2. start writing Revenue Busines Partner and select it => nothing happens NOK
3. select something else, like browse whole tree => process window opens 

**Window:** dashboard

**Comment by teosarca** [comment]
tested, works nicely

**Comment by metas-mk** [comment]
Closing the issue.
