### ISSUE TITLE
Menu not completely displayed on Android phones

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#665]
### Type of issue
* Bug 
### Current behavior
* Menu not completely displayed on Android phones ( last item not visible, Browse whole tree not visible)
* After getting at the bottom of the menu, the background start moving when I move my finger instead of the menu.
### Expected behavior
* The above should not happen
### Steps to reproduce
* Open webui on an Android phone. I tried both on 
** a Samsung Galaxy S5 Neo with Android version 6.0.1 and Chrome version 56.0.2924.87 
** a Samsung Galaxy s& with Android version 7.0 and Chrome version 57.0.2987.132
* touch the home button to open the menu
* scroll down the menu until the bottom
* => NOK: The last item in the menu is not visible and neither is "Browse whole tree"
* => NOK: When I get to the bottom of the menu list and keep scrolling with my finger, the background is scrolling instead of the menu.

**Comment by metas-rc** [comment]
![metasfresh menu on android 7](https://cloud.githubusercontent.com/assets/16001442/25239144/e8a5ffc0-25f7-11e7-909c-f189bb890b1a.png)

**Comment by damianprzygodzki** [comment]
In my opinion, it is not bug. It is working, as expected, as it working on desktops.

There was no assumption to change scope of scroll when switching between home menu and whole site. So if you are scrolling one container, and there is nothing to scroll it starts scroll the rest of the page. Whole menu is visible, whole menu is accessible.

**Comment by tomaszfryc** [comment]
I checked this on Sony Xperia Z1 compact (Android 5.1), here is short film:
https://drive.google.com/file/d/0B5CX8G6V6eiMRFBSc2VIV1ZjVG8/view

and some screenshots:
![screenshot_2017-04-21-08-53-21](https://cloud.githubusercontent.com/assets/26219501/25266626/16dca2ca-2672-11e7-9976-b922a86398b9.png)
![screenshot_2017-04-21-08-52-50](https://cloud.githubusercontent.com/assets/26219501/25266632/1ba90de8-2672-11e7-9ddc-3968b514bec2.png)

In my opinion everything is ok. You can see parts of menu when you scroll down or scroll up.

**Comment by teosarca** [comment]
Using my phone (nexus 5x, chrome 57.0.2987.132, android 7.1.2), quick checked on
* on w101 where still not working
* on jzapp.io where is working

While testing i've observed:
* on jzapp.io the bottom part of the menu is still not visible but when i am swiping down, the URL bar disappear and the page is scrolling down
* on w101 the URL bar stays no matter what and i suspect it's because of the missing SSL certificate (remark that jzapp.io is on HTTP while w101 it's on HTTPS)... so it might be a chrome bug/feature :)
