### ISSUE TITLE
refresh in attachments side list

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#666]
### Type of issue
Bug
### Current behavior
adding a new attachment doesn't update attachments side list directly. You have to close and open again
### Expected behavior
attachments side list shall update directly with the new attachment
### Steps to reproduce
1. open purchase order 181
2. open an existing and completed order e.g. 1005065
3. open attachments (ctrl+6)
4. drag a new attachment on your order, wait for the message to go away
=> on attachments are still the old ones NOK
5. close attachments and open them again 
=> you can see the new attachment OK

**Window:** 181

**Entity:** 1005065

**Comment by damianprzygodzki** [comment]
There is no support from API to dynamically refresh sidelist so i fixed that by closing all of overlays when draggin starts.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
