### ISSUE TITLE
Change /rest/api/pattribute request message

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#667]
### Type of issue
Feature request

### Current behavior

Current request format is:
```
{
  "templateId": 0,
  "source": {
    "documentType": {},
    "documentId": "string",
    "tabid": "string",
    "rowId": "string",
    "fieldName": "string"
  }
}
```

### Expected behavior
Change to:
```
{
  "templateId": 0,
  "source": {
    "windowId": "THE window id if is called from window/document",
   "processId": "THE process id if is called from a process parameters panel",
    "documentId": "string",
    "tabid": "string",
    "rowId": "string",
    "fieldName": "string"
  }
}
```

### Steps to reproduce
* from menu, run "Revenue Busines Partner" process
* click on ASI button

**Comment by Dunkat** [comment]
Changed, now in process everything working nice, but I noticed error when trying open attributes in Sales Order -> Add new product

**Comment by teosarca** [comment]
let me check on your branch....

**Comment by metas-lc** [comment]
IT
tested together with https://github.com/metasfresh/metasfresh-webui-api/issues/319 OK
