### ISSUE TITLE
Error while changing the BPartner field

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#67]
Test case:
- create a new order
- set BPartner/Address/Contact
- click on BPartner field 
- BPartner suggestions popup is displayed
- click to select a BPartner => ERROR (see screenshot: server sends 500 because the frontend sent the C_BPartner_ID as AD_User_ID and for that id)
- also, try to clear the field => gets partial cleared
- try different other editing to that field => not working.... the field is irreversible corrupted

![image](https://cloud.githubusercontent.com/assets/1244701/19486261/7e0228e6-9566-11e6-8264-4f8754a528bc.png)

**Comment by damianprzygodzki** [comment]
So - i am in the middle of debugging - one conclusion, could You try to check the setting `null` or `""` in the fields like C_BPartner_ID.

Lookup when trying to clear itself calling commit endpoint with `[{op: "replace", path: "C_BPartner_ID", value: null}]`, and after that - nothing happens.

**Comment by cadavre** [comment]
@teosarca can you help here?

**Comment by teosarca** [comment]
Quick tried to reproduce your case, but now i cannot (see below). Do you have some more hints or steps to reproduced?

![image](https://cloud.githubusercontent.com/assets/1244701/20130139/74ca5f48-a65d-11e6-8ed9-1d09d691933f.png)

**Comment by damianprzygodzki** [comment]
@teosarca okay, and after that call, it is saved in API? Because what i see, there is proper commit (with null value after clearing field) and API does still return fulfilled field with old data.

**Comment by cadavre** [comment]
How about this issue? Any progress here? Waiting for @teosarca response?

**Comment by teosarca** [comment]
Cannot reproduce....

**Comment by damianprzygodzki** [comment]
When frontend calls 

```
PATCH /rest/api/window/commit?type=143&id=1002647
[{op: "replace", path: "C_BPartner_ID", value: null}]
```

it returns 200 and:

```
[
    {
        "id":"1002647",
        "save-status":"DocumentSaveStatus{hasChangesToBeSaved=true, error=true, reason=Error: C_BPartner_ID is mandatory.}",
        "fields":[
            {"field":"C_BPartner_ID","value":null},
            {"field":"C_BPartner_Location_ID","lookupValuesStale":true},
            {"field":"AD_User_ID","lookupValuesStale":true},
            {"field":"V$DocumentSummary","value":"0532 22.11.2016 0,00"}
        ]
    }
]
```

after that i do the same with rest of fields in lookup (C_BPartner_Location_ID, AD_User_ID) and nothing happens, after setting NULL it returns old value.

What should i do, to set null for all of these 3 fields?

**Comment by teosarca** [comment]
i have to debug/reproduce the case first....

**Comment by teosarca** [comment]
very very old issue.
