### ISSUE TITLE
Icons for manufacturing components

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#675]
### Type of issue
Feature request
### Current behavior
Currently, the icons for receive/ issue products in manufacturing UI has the "Palette" Symbol as a placeholder.
### Expected behavior
The receive lines shall have one icon, the issue lines shall have another.
Idea: For receive lines have an icon w/ arrow up/ arrow right. For issue lines have arrow down/ arrow left?

**Comment by damianprzygodzki** [comment]
@cadavre waiting for icons.

**Comment by teosarca** [comment]
NOTE: When fetching the lines, the "type" field will be filled as:
* "PP_Order_Receive" - receive line
* "PP_Order_Issue" - issue line
* or any of the HU icons: "LU", "TU", "CU"

**Comment by damianprzygodzki** [comment]
Good morning @metas-mk ,
the new icons for received and issued products were complicating our icon set. They were too rectangular, and we are proposing the new version of them, to keep the icons consistent.
Could You make a review?
<img width="51" alt="screen shot 2017-04-27 at 14 09 14" src="https://cloud.githubusercontent.com/assets/5701744/25482689/23ec66e0-2b53-11e7-8d20-769a64ee5ecd.png">
<img width="53" alt="screen shot 2017-04-27 at 14 09 11" src="https://cloud.githubusercontent.com/assets/5701744/25482690/23efa576-2b53-11e7-84a5-4c499667cef7.png">

**Comment by metas-mk** [comment]
@damianprzygodzki thanks. please integrate those so we can see live in webui. we can check then if it's looking ok in screen.

**Comment by metas-mk** [comment]
@damianprzygodzki checked. does not look%feel good. Icons are too small and feel smaller than the Handling Unit icons. 
If the icons shall be square ratio I suggest to have Icons that show the meaning in square shape.
what about for action_receipt have something like an assembly icon (something in this direction): 
![image](https://cloud.githubusercontent.com/assets/13365687/25523224/28c4fe8a-2c06-11e7-9464-ed33ab740bca.png)
and for action_issue have something like this:
![image](https://cloud.githubusercontent.com/assets/13365687/25523464/0d02384c-2c07-11e7-827f-5f5b5f99b9a6.png)

![image](https://cloud.githubusercontent.com/assets/13365687/25522977/4add0252-2c05-11e7-9c4d-56f2f0605373.png)

**Comment by metas-lc** [comment]
IT
bigger but still not visible enough. NOK

**Comment by damianprzygodzki** [comment]
Are you using the up to date version?

![screen shot 2017-05-08 at 10 40 32](https://cloud.githubusercontent.com/assets/5701744/25796711/eda63814-33da-11e7-8756-5834e5abc66c.png)

**Comment by teosarca** [comment]
quick checked now on w101 and it looks like in the screenshot that i've attached.

@metas-lc  pls check again

![image](https://cloud.githubusercontent.com/assets/1244701/25839528/bc57a0ec-34a0-11e7-8ec3-d5df8e0cc69e.png)

**Comment by teosarca** [comment]
update: as discussed yesterday, pls provide the cogs-ish icons.

**Comment by cadavre** [comment]
In todays worklane for our gfx.

**Comment by teosarca** [comment]
update: for future reference, i am adding here the meaning of those 2 icons, as Mark described them.
* receipt - action : processing action. result of this action is the produced good. people have to do something to achieve this.

* issue - action : adding raw materials to the manufacturing process. it's about consuming raw materials and add them to the manufacturing process.

**Comment by cadavre** [comment]
![icons](https://cloud.githubusercontent.com/assets/461796/25888824/e72a0f2c-3567-11e7-8b9b-064c77e9e6ab.png)

Third and second from last are receipt and issue icons.

Quote from gfx design:

> One and three cogs – to differentiate it from "settings" icon they were made in plane style instead of linear style. There's also no hole in the cogs so it means more "process" than the cog itself.

**Comment by damianprzygodzki** [comment]
Are we waiting for an accept, or integrating this icon set?

**Comment by teosarca** [comment]
please integrate them asap.

**Comment by metas-lc** [comment]
IT
icons are changed OK
