### ISSUE TITLE
Dashboard Screen with KPI Widgets

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#68]
Improve the Dashboard Screen with KPI Widgets.
First Interation would be to have
- possibility to have 6-9 widgets on the dashboard
- each widget shall be able to take 1 url (iframe)
- each widget has switches to maximize, minimize
- possibility to drag&drop (rearrange on bord, will also be used in future to drag&drop kpi from a library of KPI for metasfresh users depending on their roles)

**Comment by teosarca** [comment]
The backend issue tracker is: https://github.com/metasfresh/metasfresh-webui/issues/41

**Comment by damianprzygodzki** [comment]
https://github.com/metasfresh/metasfresh-webui/issues/43
