### ISSUE TITLE
Navigation breadcrumb vs. Navigation Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#680]
### Type of issue
Bug
### Current behavior
The behavior is different between navigation via breadcrumb (window grid view opens initially) and navigation menu (stays in current state).
### Expected behavior
Harmonize the behavior of both navigational elements (bot shall open the selected element initially)
### Steps to reproduce
Open Sales Order window window/143. double click on a record to open the main view. Press on breadcrumb category "Sales Order". The grid view opens initially. OK

Open Sales Order window window/143. double click on a record to open the main view. Press on navigation menu "Sales Order". The main view remains open, instead of initially opening the grid view again. NOK

**Comment by metas-lc** [comment]
IT
repeated testcase 
Open Sales Order window window/143. double click on a record to open the main view. Press on breadcrumb category "Sales Order". The grid view opens initially. OK

Open Sales Order window window/143. double click on a record to open the main view. Press on navigation menu "Sales Order". The grid view opens initially. OK
