### ISSUE TITLE
KPI maximize w/ Data Table

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#681]
### Type of issue
Feature request
### Current behavior
When maximizing the KPI widget on the dashboard, the chart is opened in fullscreen mode and scaled larger.
### Expected behavior
The widget shall be opened same as before, but instead of enlarging the Chart, the widget shall show the data table additionally.

**Comment by cadavre** [comment]
More commits might come for improving RWD.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing/ Done.
