### ISSUE TITLE
Sidelist opening shall automatically have the first line selected

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#682]
### Type of issue
Feature request
### Current behavior
When opening the sidelist (mouse or ctrl+4) then no line is selected. When using the keyboard the user has to press <tab><tab><tab><tab>+arrow down to navigate in the sidelist grid view.
### Expected behavior
When opening the sidelist automatically preselect the first line (w/o changing the underlying main view selection automatically).

**Comment by teosarca** [comment]
Quickly tested:
* open a document
* press on side list button
* side list is opened with first row selected => OK
* but the "Sidelist", "References docs" and "Attachments" buttons are not visible => NOK
** scrolled up to see them but after releasing the mouse button and moving my mouse over the list (not pressing anything) the panel is scrolled back and i cannot see those buttons again => very annoying

NOTE: if u cannot reproduce, pls ping me.

![image](https://cloud.githubusercontent.com/assets/1244701/25480863/5f123d80-2b53-11e7-8acf-a5704625fe97.png)

**Comment by metas-lc** [comment]
IT
open sidelist with ctrl4
=> first entry is selected, you can go up and down with keyboard arrows
open sidelist with mouse
=> works the same
use ctrl4,5,6 and come back to ctrl4 => first still selected
