### ISSUE TITLE
Cannot open manufacturing modal overlay anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#685]
### Type of issue
Bug
### Current behavior
Modal overlay after quickaction opens w/ 404 error.
### Expected behavior
Shall be fixed.
### Steps to reproduce
Open Manufacturing Order Window/ Grid View. Select row. Press Issue quickaction. Modal overlay opens w/ 404 error. Same happens also for material receipt window/ overlay.

![image](https://cloud.githubusercontent.com/assets/13365687/25386489/d36ace00-29c7-11e7-95d2-e0650b9ac31b.png)

**Comment by damianprzygodzki** [comment]
Cannot reproduce. It looks like outdated build.

**Comment by metas-mk** [comment]
Is an overlapping issue w/ IT failed here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/651
Easy IT: This Task can be closed after next rollout and check.
