### ISSUE TITLE
Main page /dashboard is broken

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#688]
![image](https://cloud.githubusercontent.com/assets/1244701/25405389/da401a2a-2a0b-11e7-8345-b66ed98a7856.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* Main page /dashboard looks like before (no misallignments): OK
* KPIs working (max / min): OK
* Menu / Actions button / Notification button working fine: OK
