### ISSUE TITLE
Image widget is missing right border

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#689]
### Type of issue
Bug

### Steps to reproduce
* receipt candidates
* pick a line and call Foto action
![image](https://cloud.githubusercontent.com/assets/1244701/25408573/35898ce4-2a17-11e7-826e-358b4c08c366.png)

**Comment by damianprzygodzki** [comment]
RWD problem - buttons should be moved to bottom

**Comment by metas-lc** [comment]
IT
right border is there (even if you make the window smaller) OK
