### ISSUE TITLE
Larger photo preview screen/ modal overlay

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#695]
### Type of issue
Feature request
### Current behavior
Currently, when capturing a photo via the material receipt window, a small preview screen is shown in the bottom right corner.
### Expected behavior
The user needs to precisely see if everything is captured on the photo (quality reasons). Please enlarge the preview screen to screen wide overlay.

![image](https://cloud.githubusercontent.com/assets/13365687/25480910/3aae5e36-2b4b-11e7-8165-aa748857c9ac.png)

**Comment by metas-mk** [comment]
Why not directly open the webcam preview when opening this already existing overlay. the user can then press on image or start button directly to make the foto.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* webcam preview (as wide as modal overlay screen): smaller than modal overlay screen, see pic, not sure this is big enough?
* user can then press on image or start button directly to make the foto: pressing on the image worked, but pressing the start button doesn't do anything: NOK
* allow escape to get back or press outside: not working, also pressing Cancel does not have any affect, you have to mark the URL and press Enter to get back to Wareneingangsdispo: NOK

@metas-mk: is this webcam preview big enough?
![2017-05-02 10_28_29-metasfresh](https://cloud.githubusercontent.com/assets/18696715/25610234/b6cd9f4c-2f22-11e7-8c4e-dd018305c859.png)

**Comment by metas-dh** [comment]
checked with mk:  webcam preview is big enough: OK

pls fix the other 2 NOKs (see above)

**Comment by teosarca** [comment]
also i think it would look better if you would gray out everything which is behind. wdyt?

**Comment by damianprzygodzki** [comment]
@metas-dh 

> user can then press on image or start button directly to make the foto: pressing on the image worked, but pressing the start button doesn't do anything: NOK

The start button shouldn't take a capture. At least i can't see that it is a case of that issue and has been never discussed.

**Comment by metas-dh** [comment]
@damianprzygodzki: checked again with mk: nothing happening for pressing Start button is OK

BUT: performance is not acceptable, taking picture when clicking on it takes far too long, used to be much faster!

**Comment by damianprzygodzki** [comment]
@metas-dh It is not a performance question. We are waiting for the API calls, to close the camera view when everything will be ready.

I can remove that if you want. But then, we have to still wait for the API to load preview.

**Comment by teosarca** [comment]
Hi guys,

took a quick look on this task...
![image](https://cloud.githubusercontent.com/assets/1244701/25838286/0cdea192-349b-11e7-8193-bbece0a7d162.png)

1. frontend it's uploading the webcam photo (~0.5Mb) => backend it's very slow (851ms) => IMHO that's a thing we need to address on backend side
2. frontend it's querying the image we just uploaded it (took 637ms) => wondering if instead of querying it again, what if frontend would just update directly the image widget:
* set the image ID received on 1.
* set the webcam captured image

wdyt?

**Comment by damianprzygodzki** [comment]
We can, but:
- it is taking less time than upload (so it is minor issue)
- and what if there will be some image processing (size/format unification, validation) on the backend side, and we would be automatically update the view?

**Comment by teosarca** [comment]
TODO: create another issue to handle the speed improvements.
On this task we can accept the work as it is.
