### ISSUE TITLE
New Businesspartner modal overlay cancel

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#697]
### Type of issue
Bug
### Current behavior
It's not possible to leave the "new Business Partner" modal overlay without valid data.
### Expected behavior
Shall be possible to cancel [esc] or just done.
### Steps to reproduce
Open Sales Order window. In Business partner Field, type nonexisting name and select New Business partner. Then try to get out/ cancel.

**Comment by teosarca** [comment]
And more, i think, when user is canceling it it would be nice to have some endpoint called (just to do some cleanup on serverside too).

**Comment by metas-lc** [comment]
IT
Open Sales Order window. In Business partner Field, type nonexisting name and select New Business partner
=> notice there is a Cancel button
Press cancel 
=> OK it gets you out
(regression: set all mandatory fields, select done => ok, bpartner is created)
