### ISSUE TITLE
Optimization: commit back only when a field is really changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#7]
test case:
* click on OfferValidDays which displays "0"
* click on some other field
* NOK: a commit with {op: "replace", path: "OfferValidDays", value: "0"} is issued
* expectation: no commit shall be issued

**Comment by damianprzygodzki** [comment]
It happens because widgets have controlled inputs, and each change of field has impact on store.

Possible solution it would be to cache value on focus, for fields that calls API after other events than onChange (most of the time is onBlur).

**Comment by damianprzygodzki** [comment]
Solved e996bfb7bab2daf90253aa8f742d21f66fe0fc69
