### ISSUE TITLE
Typeahead not working in lookup filter parameters

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#700]
### Type of issue
Bug

### Current behavior
No typeahead dropdown is opened when user types in a filter parameter.

### Expected behavior
Dropdown shall be displayed like everywhere else.

### Steps to reproduce
* open sales orders: https://w101.metasfresh.com:8443/window/143
* press the Filter button and try filtering by "DocumentNo and BPartner"
* start typing something BPartner field (e.g. "mus")
=> no suggestions were displayed

NOTE: remark that the suggestions were fetched correctly from backend.

![image](https://cloud.githubusercontent.com/assets/1244701/25580234/ed7921ba-2e87-11e7-9eee-7124811dfca5.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

sales order, Filter "DocumentNo and BPartner":
* start typing something in BPartner field: suggestions are displayed, narrowed down as you continue writing: OK
* working the same in Filter "Partner and date ordered": OK
