### ISSUE TITLE
"Filter" panel does not disappear

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#701]
### Type of issue
Bug

### Current behavior
Filter panel (when there are mandatory fields not filled, i guess) does not disappear whatever i do.

### Expected behavior
User shall be able to get rid of the filter panel, no matter if the mandatory fields were filled or not.

### Steps to reproduce
* open sales orders: https://w101.metasfresh.com:8443/window/143
* press the Filter button and try filtering by "DocumentNo and BPartner"
* try getting rid of it => you cannot. I've check followings but the panel is still alive
** click Apply
** click near the button
** click on action menu
** click on menu
** try selecting some row
** press "Filter by Date Ordered" => that filter panel is opened additionally !
** press on Filter button

![image](https://cloud.githubusercontent.com/assets/1244701/25580314/b2834f30-2e88-11e7-88ef-b08ce7d754fc.png)

**Comment by Dunkat** [comment]
Fixed by #700

**Comment by teosarca** [comment]
quick tested, works.

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

open sales orders, and press Filter button, select  filtering by "DocumentNo and BPartner":
* click somewhere  in the window: Filter panel is closed, OK
* click Apply: Info: "Mandatory fields are not filled", click somewhere in the window: Filter panel is closed, OK 
* click near the button: info disappears, click somewhere in the window:  Filter panel is closed, OK
* click on action menu: Action menu opens, Filter panel is closed, OK
* click on menu: menu opens, Filter panel is closed, OK
* try selecting some row: row is selected, Filter panel is closed, OK
* press "Filter by Date Ordered": that Filter panel opens, the other Filter panel is closed, OK
* press on Filter button: nothing happens, but when clicking somewhere in the window, the Filter panel  is closed, OK 

* also tried with the other filters in sales order, e.g. "Partner and date ordered": works the same
