### ISSUE TITLE
Running a process from menu does not work, again

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#702]
### Type of issue
Bug

### Current behavior
Try starting "Ersteinrichtung Assistent" process from menu.
Does nothing even though it's a standard process.

### Expected behavior
The process parameters shall be displayed and then process shall be started by user.

### Steps to reproduce
Just start "Ersteinrichtung Assistent" process.

![image](https://cloud.githubusercontent.com/assets/1244701/25605889/b5b99220-2f16-11e7-82b1-434f3a049e12.png)

NOTE: we already had fixed this issue on https://github.com/metasfresh/metasfresh-webui-frontend/issues/526

**Comment by teosarca** [comment]
required for https://github.com/metasfresh/metasfresh-webui-api/issues/337

**Comment by metasnw** [comment]
IT
tested wizard on w101

- OK: uploaded logo
- OK: changed address
- OK: put description

**Comment by metasnw** [comment]
http://docs.metasfresh.org/webui_collection/DE/Ersteinrichtung.html
