### ISSUE TITLE
leave the page message on request modal

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#703]
### Type of issue
Bug
### Current behavior
if i create a request while i am in gridview it asks me if i am sure i want to leave the page (when pressing done in modal)
### Expected behavior
when all mandatory fields are set and oi press done, it shouldn't ask me if i want to leave the page
### Steps to reproduce
1. go to business partner window, select one but stay in grid view
2. on actions select create request
3. set all mandatory fields, press done
=> Do you really want to leave?
**Window:** window/123/

![request1](https://cloud.githubusercontent.com/assets/16001666/25620856/638cb15c-2f58-11e7-8399-9c9231b60e09.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* repeated testcase: Do you really want to leave? did not pop up after pressing Done, but modal window was closed and request created correctly: OK
