### ISSUE TITLE
request modal saving is loading 4 tabs

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#704]
### Type of issue
Bug
### Current behavior
4 tabs are loaded when the request process is saved the first time
### Expected behavior
do not load the tabs
### Steps to reproduce
1. go to business partner window, select one
2. on actions select create request
3. set all mandatory fields 
=> 4 tabs are loaded

**Window:** window/123/

![request_loaded_tabs](https://cloud.githubusercontent.com/assets/16001666/25621648/a1b38be8-2f5a-11e7-826b-f89910de96dd.png)

**Comment by metas-dh** [comment]
Results of IT1
tested on w101

* repeated testcase above:  4 tabs are loaded: not happening anymore: OK
