### ISSUE TITLE
Debug/Fix why /window/540189 shows empty

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#705]
### Type of issue
Bug

### Steps to reproduce
Open https://w101.metasfresh.com:8443/window/540189
=> shows no rows, even though there are a couple of pages => NOK

Navigate pages back and forth => the rows as displayed => OK

![image](https://cloud.githubusercontent.com/assets/1244701/25658742/1e340d02-300d-11e7-8d4b-50cd800ff194.png)

**Comment by metas-lc** [comment]
IT
Open /window/540189
=> rows are shown, you can also navigate through pages and works fine OK
