### ISSUE TITLE
Manufacturing order - Issue HUs - wrong /quickActions call

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#706]
### Type of issue
Bug

### Steps to reproduce
* open manufacturing order: https://w101.metasfresh.com:8443/window/53009
* select a manufacturing order and call "Issue/Receipt" quick action
* select a component line (Type=CO)
* run "Issue HUs" quick action

Check Inspect-Network and you will remark a call to https://w101.metasfresh.com:8443/rest/api/documentView/540189/540189-e9186433-e390-4a08-8d4a-48c6afd1815a/quickActions?selectedIds=PP_Order_BOMLine_1000003

which is wrong because:
* "540189-e9186433-e390-4a08-8d4a-48c6afd1815a" - that's the viewId of the "HUs to issue" included view
* "PP_Order_BOMLine_1000003" - that's the rowId of the manufacturing order component line

![image](https://cloud.githubusercontent.com/assets/1244701/25658960/29f45bf0-300e-11e7-906c-14d11e3ed181.png)

### Expected behavior
Instead of "selectedIds=PP_Order_BOMLine_1000003" the "HUs to issue" current selected rowId shall be used.

**Comment by damianprzygodzki** [comment]
Postponing due to no corruption in visible data. 

The call is occuring because the viewId is changing, and few miliseconds later the selection scope is changing.

Hard to quickfix because we have to keep both of QA fetching conditions.

**Comment by metas-lc** [comment]
IT
repeated the testcase above:

1. open manufacturing order: https://w101.metasfresh.com:8443/window/53009
2. select a manufacturing order and call "Issue/Receipt" quick action
3. select a component line (Type=CO)
4. run "Issue HUs" quick action
=> Check Inspect-Network and you will remark a call to https://w101.metasfresh.com:8443/rest/api/documentView/540189/540189-3b7da625-5588-49f3-b605-4b105a4a6d00/quickActions?selectedIds=1008967
where 1008967 is the HU id OK
