### ISSUE TITLE
Page popup shall be closed when clicking o a page

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#707]
### Current behavior
On page navigation panel, when clicking on "..." the "Go to page" pops.
Now, if you click on a particular page number or on first/last buttons the popup is still active.

### Expected behavior
When clicking on a particular page or on first/last buttons, the popup shall vanish.

### Steps to reproduce
Any view with a lot of pages, e.g. https://w101.metasfresh.com:8443/window/143

![image](https://cloud.githubusercontent.com/assets/1244701/25679229/3d9db416-3055-11e7-8277-a550e46e5c0b.png)

**Comment by metas-lc** [comment]
IT
Go to page popup disappears when you select other page number, or next/back button
