### ISSUE TITLE
KPIs: In case datasets is empty or missing shall show "No data" text

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#713]
### Current behavior
When "/dashboard/kpis/<id>/data" returns empty or missing "datasets" field,
the KPI widget shows "Error loading data..." (red).

### Expected behavior
The KPI widget shall display "No data" text (black).

But only in case the "datasets" is empty or missing.
In case of an endpoint failure, we keep it as it is, "Error loading data..." (red).

### Steps to reproduce
Sorry, but you have to mock it.
Below it's a screenshot using a dev db:
![image](https://cloud.githubusercontent.com/assets/1244701/25713329/0a584546-30fd-11e7-91d4-c76fdada5a4f.png)

**Comment by metas-lc** [comment]
IT
looks the same

![kpis](https://cloud.githubusercontent.com/assets/16001666/26492487/0fbbda76-421d-11e7-86ce-7b7f78549269.png)

**Comment by damianprzygodzki** [comment]
Where can we check this? It was working on mocked data, it will great to have opportunity to see it live.

**Comment by metasnw** [comment]
@damianprzygodzki just get a clean metasfresh via docker compose. Here is how to: http://docs.metasfresh.org/installation_collection/EN/How_do_I_setup_the_metasfresh_stack_using_Docker.html
we are using that a lot to test on clean systems that have not been manually altered

**Comment by cadavre** [comment]
Fixed.

**Comment by metas-mk** [comment]
Tested. (modified Queries and Time ranges to test w101). Works as required. Done.
