### ISSUE TITLE
Included tab shall preserve the retrieve order

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#714]
### Type of issue
Bug

### Current behavior
Data retrieved by "/window/<windowId>/<documentId>/<tabId>" is sorted by ID on frontend side.

### Expected behavior
Frontend shall preserve the precise order of retrieval.

### Steps to reproduce
Open any window with included documents,
e.g. https://w101.metasfresh.com:8443/window/540317/1000001
Check the "Item" tab, and remark that the order is not the one provided by backend.
In this case, internally it was by WidgetType and then by SeqNo.

![image](https://cloud.githubusercontent.com/assets/1244701/25714334/510180d6-3100-11e7-824d-bba241d18875.png)

**Comment by damianprzygodzki** [comment]
No, we can't.

**Comment by Dunkat** [comment]
the problem occure because we use rowId in object keys (thats why table is always sorted by ids - because key in objects are automaticly sorted), which is very useful e.g  delete row - we searching rows by keys. Changing structure of this object needs a lot of changes in application.

**Comment by teosarca** [comment]
Hi guys,

Don't we use the (kind-of-)same component like we use in the grid view?
Nevertheless, this can be a big issue, because in some cases the business logic needs to re-order some document lines by some criterias which simply does not match the ID order.
In future we would also like to introduce sorting by clicking on the columns of included grid.

But for now we need to address this issue in way... so i am wondering if it would help if the backend would provide some virtual field where i can generate a sequence and u just sort by that sequence
(ofc that sequence would and should have nothing to do with line identity).

**Comment by Dunkat** [comment]
It's not exactly the same component  like in the grid view, but we will unify this.  We can use just simply index instead of id to generate a sequence. It will need small refactor.

**Comment by metas-mk** [comment]
Tested on w101. Works as required. Closing.
