### ISSUE TITLE
Sidelist's scrollbar is on wrong container.

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#717]
### Type of issue
Bug
### Current behavior
Sidelist's scrollbar upper arrow is not visible:

![image](https://cloud.githubusercontent.com/assets/1244701/25723497/e2019bdc-3120-11e7-9176-e774d43000dd.png)

### Expected behavior
Shall be visible.

### Steps to reproduce
e.g. https://w101.metasfresh.com:8443/window/143/1005142

**Comment by metas-lc** [comment]
IT
checked multiple windows, reference documents: 
=> Sidelist's scrollbar upper and lower arrow are visible OK
