### ISSUE TITLE
Document references: group them by their top level menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#719]
### Is this a bug or feature request?
Feature

### What is the current behavior?
The document references are just displayed as a plain list.
If there are more, it's quite hard to figure out at a glance what's created and what's not.

#### Which are the steps to reproduce?
Select a sales order and browse document references.
Pls make sure you selected one with a lot of document references.

### What is the expected or desired behavior?
The document references shall be grouped by their top level menu.
Also pls stop using the top level "references" property because it will be deleted.

![image](https://cloud.githubusercontent.com/assets/1244701/25739863/73376bde-318c-11e7-86eb-fc89a1f0f0dd.png)

**Comment by teosarca** [comment]
Hi guys,

Quick checked this task and it's starts to look very nice.
Now, we just need to have the same style like we have on the Menu.
I would also consider having that underline that i've drawn. @Sew wdyt?


Menu design: remark how the menu groups are rendered
![image](https://cloud.githubusercontent.com/assets/1244701/25839268/a9a6d3ce-349f-11e7-91f8-edb03beb51db.png)


Document references: remark how the groups are rendered now (i.e. no style)
![image](https://cloud.githubusercontent.com/assets/1244701/25839304/c7ee0794-349f-11e7-9e71-d5a50d1450b7.png)


My suggestion to have the groups with underline: @Sew wdyt?
![image](https://cloud.githubusercontent.com/assets/1244701/25739863/73376bde-318c-11e7-86eb-fc89a1f0f0dd.png)

**Comment by damianprzygodzki** [comment]
Can we next time start with the design and do not iterate with such a small things?

**Comment by teosarca** [comment]
Pls capitalize the group text and also use the same color as on menu groups.

**Comment by metas-lc** [comment]
IT
tested with sales and purchase order windows, created inouts and invoices
check references
=> they are grouped by billing, material receipt/shipment and others
