### ISSUE TITLE
Harmonization of Date-Widget and Date-Range-Picker

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#72]
Harmonization of Date-Widget and Date-Range-Picker
- Should look the same or be the same component (but considering date 1 cal vs. date-range case 2 cal)

**Comment by cadavre** [comment]
https://s3-eu-west-1.amazonaws.com/uploads-eu.hipchat.com/108112/797371/29bKaQBvfJSji32/harmonization.png
