### ISSUE TITLE
Login role selection keyboard down does not scroll automatically

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#724]
### Type of issue
Bug
### Current behavior
Currently, when using the keyboard [arrow-down] in role selection, then the cursor/ selected row "disappears" at the bottom. It's not automatically scrolling down.
### Expected behavior
Scroll down in longer lists so the user can see where she/ he is.
### Steps to reproduce
Open the login 2nd screen w/ more than 12 roles available.

![image](https://cloud.githubusercontent.com/assets/13365687/25884471/041cf848-3553-11e7-9509-f6c96649004d.png)

**Comment by metas-lc** [comment]
IT
logged in with a user which has 15 roles available
used up an down arrows to select the role
=> scroll is going down and up accordingly OK
