### ISSUE TITLE
Sidelist closes when doubleclick

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#725]
### Type of issue
Bug
### Current behavior
Currently, when opening side list [ctrl]+4 the list opens. When double-clicking a record, the record main view opens AND the side list closes.
### Expected behavior
The side list shall remain opened and only close when the user clicks outside (works already) or clicks on menu button or [ctrl]+4 again (toggle, works too).
### Steps to reproduce
Try in window sales order.

**Comment by metas-lc** [comment]
IT
1. open sales order, select an order and press ctrl+4
2. select a record
=> the record main view opens OK
=> the side list is still open OK
3. select other records
=> each time the sidelist remains open OK
4. press ctrl+4 , or select outside the sidelist
=> sidelist closes OK
