### ISSUE TITLE
Action Issue & Receipt Window wrong action

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#726]
### Type of issue
Bug
### Current behavior
When selecting Issue line and pressing outside and then receive line to close HU overlay, the issue quick actions remain, which is wrong. Should be the receive actions then.
### Expected behavior
When clicking the receive line the receive actions shall appear.
### Steps to reproduce
a) Click on issue line (here the 2nd w/ CO) --> HU Editor opens
b) click outside HU editor underneath issue line. --> nothing happens
c) click outside HU editor and select the receipt line (here MP) --> the Issue actions remain NOK

![image](https://cloud.githubusercontent.com/assets/13365687/25910250/0283830a-35b0-11e7-9220-2da40cda56ec.png)

**Comment by Dunkat** [comment]
Checked

a) Click on issue line --> HU Editor opens
b) click outside HU editor (you need to click outside table area) --> HU Editor close
c) select the receipt line (first one) -->there is Receive HUs action

**Comment by Dunkat** [comment]
Checked

a) Click on issue line --> HU Editor opens
b) click outside HU editor (you need to click outside table area to close HU editor)
c) select the receipt line (first one) -->there is Receive HUs action (which action should be displayed?)

**Comment by teosarca** [comment]
Update: it seems it was fixed in some commits, somewhere between yesterday and today.

Postponing it for now.

**Comment by metas-lc** [comment]
IT
1. go to material receipt and select one, press on issue/receipt
2. select the CO product and press issue
3. select outside so the hu editor closes
4. select the main product
=> actions: Receive HUs OK
