### ISSUE TITLE
Grid view: reset current page to 1 when filtering

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#727]
### Type of issue
Bug

### Steps to reproduce
* open product window: https://w101.metasfresh.com:8443/window/140
* navigate to page 3 
* pick a product name from that list and search for it
=> no results

Reason: frontend queries on page for page 3.

### Expected behaviour
When filtering, frontend shall query first page.

![image](https://cloud.githubusercontent.com/assets/1244701/25920942/42e01e0a-35dc-11e7-8672-723aa7f829cf.png)

![image](https://cloud.githubusercontent.com/assets/1244701/25921008/83683fca-35dc-11e7-9333-3cc9bf674e58.png)

![image](https://cloud.githubusercontent.com/assets/1244701/25921044/a27af7f4-35dc-11e7-9597-22040f5475ca.png)

**Comment by metas-lc** [comment]
IT
repeated the testcase:
1. open product window: https://w101.metasfresh.com:8443/window/140
2. navigate to page 3
3. pick a product name from that list and search for it
=> works fine: product is shown OK
4. pick a product name from another page
=> product is filtered OK
