### ISSUE TITLE
ERP notification system

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#73]
Social-ERP-Notification chat (bell with red-pill). Example stuff:
- shall inform user about system messages "Inout <link> is created for (at)martin". Date-Time
- Notification is referenced to that inout (notification history)
- Notification history can be viewed in each record (if available)
- Possibility to mention a user and communicate about specific stuff (records or links) (at)martin can u please check this <individual-link-to-record> and let me know if its ok? thanks."
- Possibility to mention a user and communicate about something
- Possibility to mention (at)support" can u please help me with this document. why does it have an error?
- Possibility to mention (at)picking pls add a free chocolate-bar when shipping this -> shall popup when picked

What about joining already expert open source messengers for this (loud thinking)? For example:
https://www.mattermost.org/
https://rocket.chat/

**Comment by metas-mk** [comment]
As discussed in todays WebUI Jour Fix. We'll start this implementation with first initial step as described here:
#97

**Comment by cadavre** [comment]
I renamed this task to have it completed in phase 1 while working with inbox.
