### ISSUE TITLE
included view: don't reset when closing an error notification

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#734]
### Type of issue
Bug

### Steps to reproduce
* manufacturing order: https://w101.metasfresh.com:8443/window/53009
* select a row and call "Issue /Receipt"
* select a "CO" line and call "Issue HUs"  => the included view is opened with the HUs to be issued.
* select a row and call "Issue TUs (partial)
* on QtyCU parameter type "0" or "-1" to trigger an error and click Start
* the process fails and a notification is displayed => OK
* **IMPORTANT: please close the notification. When you will click on notification close button (X) remark that frontend performs two "quickActions" calls. I think you can debug in that area because i think the bug is somewhere around. Why when closing a notification the "quickActions" are called? I think notifications shall not interfere with anything.**
* click on "Cancel" to discard the process panel.
* the included view (from the right side) is closed => NOK - please don't close it

![image](https://cloud.githubusercontent.com/assets/1244701/25962785/c5591a02-3687-11e7-94f7-f83513f17572.png)

![image](https://cloud.githubusercontent.com/assets/1244701/25962825/e28ff4ce-3687-11e7-8311-f42d270923c9.png)

![image](https://cloud.githubusercontent.com/assets/1244701/25962938/3f58ab10-3688-11e7-9fed-46e8e0dac2c0.png)

![image](https://cloud.githubusercontent.com/assets/1244701/25962990/75073f88-3688-11e7-9aa1-9864ababc44a.png)

**Comment by metas-lc** [comment]
IT

1. manufacturing order window/53009
2.  select a row and call "Issue /Receipt"
3.  select a "CO" line and call "Issue HUs" 
=> the included view is opened with the HUs to be issued.
4. select a row and call "Issue TUs (partial)
5. on QtyCU parameter type "0" or "-1" to trigger an error and click Start
=> the process fails and a notification is displayed => OK
6. click on "Cancel" to discard the process panel.
=> the included view (from the right side) is still open OK
