### ISSUE TITLE
When included view is displayed add an alpha layer over the main view

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#739]
### Type of issue
Feature request

### Steps to reproduce
* goto manufacturing orders view: https://w101.metasfresh.com:8443/window/53009
* select one and click Issue/Receipt
* select a "CO"mponent line and click "Issue HUs"

now, 
* on the left side you have the main view (the manufacturing order lines with their HUs)
* on the right side you have the included view (the HUs to be issued)

![image](https://cloud.githubusercontent.com/assets/1244701/26023306/97694c8a-37c1-11e7-969a-a0e599c36b27.png)

### Expected behavior
When the included view is opened, we shall add an alpha layer over the main view.
In the screenshot below, i've added an white layer with opacity of %35.
This would help the user (a lot) to focus.

![image](https://cloud.githubusercontent.com/assets/1244701/26023325/d81ccaa4-37c1-11e7-8e79-3ce0762c0c04.png)

**Comment by teosarca** [comment]
IMPORTANT Update about the white alpha layer: it shall fade out the view but not so much. It's important that the user can easily read what's there (in case he/she wants to figure out where he/she it is).

For example, as it is now on Barcode scanning it's too much!
![image](https://cloud.githubusercontent.com/assets/1244701/26025344/1a9b6e2c-37ee-11e7-8d78-ec7cf1b6b3a0.png)

**Comment by damianprzygodzki** [comment]
Fade out just the table.

**Comment by metas-lc** [comment]
IT
1. open manufacturing orders, select one, click on issue/receipt
2. select the co product and press on issue hu
=> right panel opens
=> left side becomes faded and you can read what's in there
3. select outside the right panel
=> right panel closes
=> right panel is visible (not faded)
