### ISSUE TITLE
When filtering a view please use the newly introduced "/documentView/{windowId}/{viewId}/filter" endpoint

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#740]
### Type of issue
Feature request

### Current behavior
When filtering a view, frontend is using http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/createViewUsingPOST .

### Expected behavior
When filtering a view, frontend shall use http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/filterViewUsingPOST .

### Steps to reproduce
* open any view, e.g. https://w101.metasfresh.com:8443/window/143
* apply some filters

**Comment by teosarca** [comment]
Required for https://github.com/metasfresh/metasfresh-webui-api/issues/364

**Comment by metas-lc** [comment]
IT
filters working fine + using /documentView/{windowId}/{viewId}/filter OK
