### ISSUE TITLE
Filter singleOverlayField support

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#742]
### Type of issue
Feature request

### Expected behavior
When fetching the view layout, so the filter layouts too, if a filter has "parametersLayoutType":"singleOverlayField" then when user clicks on that filter it shall be rendered like the process parameters with "parametersLayoutType":"singleOverlayField" (see task https://github.com/metasfresh/metasfresh-webui-frontend/issues/655 ).
It shall look like:
![image](https://cloud.githubusercontent.com/assets/1244701/26025902/46dbb198-37fa-11e7-9f68-2969dbf05c97.png)

When the user presses enter, the filter shall be applied.
When the user cancels (e.g. presses ESC) the filter shall be cleared.

### Steps to reproduce
* open https://w101.metasfresh.com:8443/window/540189
* Click Filters ->  Barcode

![image](https://cloud.githubusercontent.com/assets/1244701/26025914/6681ca8c-37fa-11e7-8dbb-61a0e8c140fa.png)

Required for https://github.com/metasfresh/metasfresh-webui-api/issues/364

**Comment by Dunkat** [comment]
for clearing filter used 'delete'. For closing overlay used 'Esc'

**Comment by teosarca** [comment]
As talked on skype
* when user clears the Barcode field => frontend shall automatically remove the Barcode filter
* when the Barcode is opened, automatically select the text

**Comment by cadavre** [comment]
To be precise:

> when user clears the Barcode field => frontend shall automatically remove the Barcode filter

when user clears the Barcode field **and press [Enter]** => frontend shall automatically remove the Barcode filter

**Comment by Dunkat** [comment]
should I leave clearing filter on 'delete' key or remove it?

**Comment by cadavre** [comment]
I would say no, because someone might want to change single digit with [Del] as same as with [Backspace].

**Comment by metas-lc** [comment]
IT
1. open window/540189
2. Click Filters -> Barcode
2.1 write something then press esc => filter NOT applied OK
2.2 write something , remove what you wrote and press enter =>  filter NOT applied OK
2.3 press enter directly => filter NOT applied OK
2.4 write something and press delete => nothing happens, but you can use delete to remove what you wrote OK
2.5 write the value of an existing TU (from that page or another) => your HU is filtered OK
2.6 write something that doesn't exists => no results OK
