### ISSUE TITLE
modal panel: background looks a bit ugly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#743]
### Current behavior
Remark that gray lane which is marked in following screenshot:
![image](https://cloud.githubusercontent.com/assets/1244701/26026018/40d09a82-37fc-11e7-8bed-09f820637c46.png)

### Expected behavior
* it shall be white
* or the entire modal background shall be white

Pls advice.

**Comment by damianprzygodzki** [comment]
Please, remember that we have this background colour to differentiate between primary element groups (can't be white).

The gap is for tooltips in widgets. Eventually we can move that inside element group (to always have place for widgets absolute tooltips for errors.

**Comment by metas-lc** [comment]
IT
grey lane was taken out OK
