### ISSUE TITLE
Debug why tab crashes when changing window permissions on automatic role

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#745]
### Current behavior
See https://github.com/metasfresh/metasfresh-webui-api/issues/365

### Steps to reproduce
* open roles view and pick a role, e.g. https://w101.metasfresh.com:8443/window/111/1000055
* go to Window Access tab
* try setting the Active flag to false for one of the records. Please do it in grid mode and not in advanced edit mode
=> Chrome freezes

![image](https://cloud.githubusercontent.com/assets/1244701/26037598/59ab5502-38ff-11e7-92a6-1cc35545373e.png)

**Comment by damianprzygodzki** [comment]
I'm going to research it too, what is actual moment of corruption.

**Comment by damianprzygodzki** [comment]
When it cames to process 1000 row updates at once in response to `PATCH`, we have to for each update run N times update of single row (document), it means that in that case we are dispatch around: 1000 * ~5 (single properties update) ~= 5000 actions dispatched at once.

Additionally there is a lot of other things to update around, like parsing dates or nulls to empty strings or another tab update processing.

I don't think so, that we can do anything with that without changing assumptions about protocol of updating fields (there was no assumption to handle that amount of store update).

**Comment by teosarca** [comment]
Thanks Damian, i will have to think about...
Also there is some work to do on backend too.
I would avoid changing the protocol, but I would not exclude changing it :)

**Comment by damianprzygodzki** [comment]
Can we close this issue, because the debug was made, the case now is to provide updates on backend xor enhancement in protocol on frontend.

**Comment by teosarca** [comment]
yup, thanks
