### ISSUE TITLE
singleOverlayField: pressing ESC shall close the popup

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#749]
### Type of issue
Bug

### Steps to reproduce
* open manufacturing order: https://w101.metasfresh.com:8443/window/53009
* run "Issue/Receipt (barcode)" quick action
* IMPORTANT: click somewhere outside the input field
* press ESC => nothing happens => NOK
* click inside the input field
* press ESC => works

![image](https://cloud.githubusercontent.com/assets/1244701/26105183/a1c8b9f6-3a49-11e7-8b19-6cd4bb0cd0fb.png)

### Expected behavior
ESC shall work no matter where you are.

**Comment by metas-lc** [comment]
IT
repeated testcase above

1. open manufacturing order: https://w101.metasfresh.com:8443/window/53009
2. run "Issue/Receipt (barcode)" quick action
3. IMPORTANT: click somewhere outside the input field
4. press ESC => works OK
5. run "Issue/Receipt (barcode)" quick action, click inside the input field
6. press ESC => works OK
