### ISSUE TITLE
Initial Setup Wizard does not open after switching language

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#751]
### Type of issue
Bug 

### Current behavior
process does not open after switching language

### Expected behavior
should be opened 

### Steps to reproduce

1. log on and have german language
1. switch language to English
1. go to menu and search for "wiz"
1. click on "Initial Setup Wizard"
1. NOK: nothing happens
1. click on Sales Order
1. NOK: Initial Setup Wizard opens

Also works the other way round:
1. log on and have english US language
1. switch language to German 
1. go to menu and search for "erst"
1. click on "Ersteinrichtung"
1. NOK: nothing happens
1. click on Sales Order
1. NOK: Initial Setup Wizard opens

### Priority
According to the quickstart procedure its the first thing users do (this is how I found it) so they might hit the problem right away:
http://docs.metasfresh.org/webui_collection/EN/Quickstart.html

**Comment by metasnw** [comment]
tested just now on w101 and could reproduce

**Comment by metas-lc** [comment]
IT
1. log on and have english US language
2. switch language to German
3. go to menu and search for "erst"
4. click on "Ersteinrichtung" => process opens OK
5. logout, login
6. search for "wiz"
7. click on Initial "Setup Wizard" => process opens OK
