### ISSUE TITLE
Location dropdown missing in Order windows

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#753]
### Type of issue
Bug
### Current behavior
The location dropdown is not shown anymore in Purchase Order/ Sales Order for Business Partner selection.
### Expected behavior
Allow the user to select via dropdown again.

![image](https://cloud.githubusercontent.com/assets/13365687/26128747/c06ef110-3a8d-11e7-80e3-ba46e1d8412c.png)

**Comment by metas-mk** [comment]
Does this one belong to this issue? https://github.com/metasfresh/metasfresh-webui-frontend/issues/744

**Comment by damianprzygodzki** [comment]
The purpose, why the dropdown is not displayed is because defaultValue is set #161 . The same here as in #744 we are close to integrate new widget. Will be fixed soon.

**Comment by teosarca** [comment]
> Will be fixed soon.

thanks

**Comment by Dunkat** [comment]
fixed (but not merged yet)

**Comment by cadavre** [comment]
@metas-lc tested with new lookups?

**Comment by teosarca** [comment]
to be tested after #600

**Comment by metas-mk** [comment]
Tested. Works as required. Moving to done & closing.
