### ISSUE TITLE
Action button remains gray if the process execution fails with error 404

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#759]
See https://github.com/metasfresh/metasfresh-webui-frontend/issues/599

Please make sure the button unlocked no matter what kind of exception/error was thrown.

## Test case
* manufacturing order
* Issue/Receipt
* try to reverse one of the "HU issuing" => FAILED (ok, that's a backend thing)
* the "Reverse" button is still gray => NOK
* close the Issue/Receipt panel, so you are back to manufacturing orders view
* the quick action button is gray => NOK
* NOTE: refresh the page => the quick action button is green again
* MORE, even if the buttons are gray they are still pressable and frontend is calling backend endpoints => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/26193578/682c879c-3bbe-11e7-97f6-c28853023b4c.png)

**Comment by cadavre** [comment]
So simple answer for implementation is: always enable button back after response came, no matter what was response code. Is this correct?

**Comment by teosarca** [comment]
@cadavre exactly.
And of course, i assume the frontend disabled the button before starting the process.
So that's the reason it shall enable it (i.e. restore the enabled state) no matter what.

**Comment by teosarca** [comment]
Quickly tested on local:
* Issue/Receipt panel
* select a COmponent line
* press Issue HUs => the included view is opened
* click away
* select the COomponent line again
* press Issue HUs => nothing happens, no calls to backend => NOK

![image](https://cloud.githubusercontent.com/assets/1244701/26198040/2f89b5c2-3bcd-11e7-8f06-dbc42777a3b1.png)

**Comment by metas-lc** [comment]
IT
repeated testcase above:
* Issue/Receipt panel
* select a COmponent line
* press Issue HUs => the included view is opened
* click away
* select the COomponent line again
* press Issue HUs => the included view is opened OK

- couldn't reproduce the error with grey button
