### ISSUE TITLE
Fix the texts displayed while loading

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#760]
#### 1. Menu actions:
* click on menu
* frontend shows "There is no action" until the actions are loaded

Expectation: it shall show a loading indicator/text or nothing, but NOT "There is no action" because induces FUD

![image](https://cloud.githubusercontent.com/assets/1244701/26200650/cbdfc0ba-3bd7-11e7-86db-5f5edaeb9765.png)

#### 2. Window / single document
* go to sales orders for example
* click on a sales order
* while loading the "status indicator line" is red => NOK
* sometimes, until it's loaded, the "404 not found" text is shown => NOK

Expectation: while loading the document
* the "status indicator line" shall not be red.
* the "404 not found" text shall never be shown because it's not right and induces FUD

![image](https://cloud.githubusercontent.com/assets/1244701/26200783/81546b26-3bd8-11e7-9ab9-264852895a9e.png)

**Comment by cadavre** [comment]
BTW "There ARE no actions" ;)

**Comment by teosarca** [comment]
Here is the 404 issue, but to be honest i don't know how to reproduce. Might be when we have slow response time from backend....

![image](https://cloud.githubusercontent.com/assets/1244701/26278155/cbece4cc-3d9c-11e7-82fb-0289f2ad478a.png)

**Comment by teosarca** [comment]
Quick tested by opening the Menu while in dashboard: stays like this forever:
![image](https://cloud.githubusercontent.com/assets/1244701/26351553/cd9e6d74-3fc0-11e7-9af8-dec283c41c46.png)

**Comment by metas-lc** [comment]
IT
1. go to a place where are a lt of actions. E.g. Material receipt candidates, open one and select the 3 dots
=> actions are loaded really fast, but you can slightly see that there's a gear before they appear
OK
2. opened multiple windows that contains lots of entries, like order,receipt candidates ,invoice candidates
- selected documents, used back from grid view to document 
=> 404 not found is not appearing OK  

3. press the 3 dots while you are in dashboard
=> Actions - There is no actions appears instantly OK

**Comment by teosarca** [comment]
Tested:
* open sales order
* go to batch entry and write some product name which does not exist, e.g. zzzzzzzzz
=> the gear/loading icon is shown even if the typehead was performed and there were no results => NOK => it shall show the "no results" text.

![image](https://cloud.githubusercontent.com/assets/1244701/26438708/384a8758-412d-11e7-8231-b6d92a9bb821.png)

**Comment by metas-lc** [comment]
IT
repeated steps 1-3 from IT1 => works the same OK

1. open sales order
2. go to batch entry and write some product name which does not exist, e.g. zzzzzzzzz
    => "no results" text (the gear appears just a bit)
    => works the same if you use add new instead of batch entry
