### ISSUE TITLE
grid: right click on a cell and zoom into

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#763]
### Type of issue
Feature request

### Current behavior

![image](https://cloud.githubusercontent.com/assets/16079655/26211051/cd1949d2-3bf1-11e7-9cf6-e1a4f7554fb7.png)

### Expected behavior
If the field supports zoom into,
when right clicking on it, the "Zoom into" option shall be available.
It shall work exactly like the zoom into from single row layout.

![image](https://cloud.githubusercontent.com/assets/16079655/26211579/0f0b3c5a-3bf3-11e7-9c66-274f38de0112.png)

**Comment by teosarca** [comment]
we need to provide the backend first, https://github.com/metasfresh/metasfresh/issues/1597

**Comment by teosarca** [comment]
Introduced /documentView/{windowId}/{viewId}/{rowId}/fields/{fieldName}/zoomInfo endpoint to be used.

backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/410

**Comment by damianprzygodzki** [comment]
As discussed on skype, waiting here for the update of endpoints.

**Comment by teosarca** [comment]
Created task https://github.com/metasfresh/metasfresh-webui-frontend/issues/787 .

**Comment by metas-mk** [comment]
Tested. Works as required and expected. Very nice functionality!
