### ISSUE TITLE
Date + Time Info in Notification window

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#765]
### Type of issue
Feature request
### Current behavior
Currently, the notifications time is shown with something similar to "Created 4 minutes ago."
### Expected behavior
It would be nice for the user to hover over that time notification and a tooltip would show the real date+time when the notification was created.

![image](https://cloud.githubusercontent.com/assets/13365687/26234097/596c0d6e-3c62-11e7-9aa0-82f3a03cae1a.png)

![image](https://cloud.githubusercontent.com/assets/13365687/26234092/5274f430-3c62-11e7-8e80-1f86e6505832.png)

**Comment by metas-lc** [comment]
IT
made an inout to have a notification, hovered on the time of that notification
=> tooltip appeared with dd.MM.YYYY HH:mm:ss (my time, hour format 24) OK
