### ISSUE TITLE
Got same notification several times

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#767]
### Type of issue
Bug

### Current behavior / Steps to reproduce
* you need to freshly login, so if u are already logged it pls logout and login. Pls do logout/login several times!

* on another tab please open: http://w101.metasfresh.com:8081/websocket_test.html
** connect to topic: /notifications/<userId>.
*** if you logged in with SuperUser, the topic shall be /notifications/100
*** if you logged in with "it", the topic shall be /notifications/2188223

* on another tab please call: http://w101.metasfresh.com:8181/test/ping/notifications => that call will create a notification on metasfresh server which will be forwarded to metasfresh-webui-server which will forward it to frontend (view websockets)
** you will need to authenticate with SuperUser and it's password

Result:
* frontend displays the notification 2 or 3 times
* websocket_test.html : got the notification only once => webui server is sending it once

Now, if you would refresh the frontend page you will see that each notification is displayed once.

So, i suspect the issue is on frontend when it gets the notifications via websocket. Might be that frontend (for some reason) have the multiple websocket listeners for same /notifications/userId endpoint and that's why the notifications are added several times?

![image](https://cloud.githubusercontent.com/assets/1244701/26240364/74449cce-3c89-11e7-97dc-4862ba91dac1.png)

![image](https://cloud.githubusercontent.com/assets/1244701/26240371/7c0409a4-3c89-11e7-8adc-fafe56898859.png)

**Comment by teosarca** [comment]
update: check again. you need to logout and login several times (without doing browser refresh).
Each time would grow the number of notifications "received" from websocket.

**Comment by cadavre** [comment]
Might it be we're not disconnecting socket on logout?

**Comment by metas-lc** [comment]
IT
- used test notifications and also normal ones from creating receipts
=> each notification appeared once OK
- logout-login several times
=> each notification appeared once OK
