### ISSUE TITLE
frontend: JSON documents: always use "fieldsByName" instead of "fields"

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#773]
### Type of issue
Feature request

### Expected behavior
We changed following API responses:
* getting a single document data
* getting view data
* responses to document PATCHing

In all those cases we are now providing "fieldsByName" which is a map of fields indexed by their field name.
Atm we are still providing the old "fields" property, but it's deprecated. Please make sure you are not using it.

Backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/405

**Comment by damianprzygodzki** [comment]
Process parameters left not changed. It is also needed, because Processes use the same Window component as other entities.

```"parameters":[{"field":"AD_Image_ID",...```

They should be also `fieldsByName`.

**Comment by metas-mk** [comment]
Checked. Cannot be tested at, w/o taking out the "fields" property from the backend. waiting for that.

**Comment by teosarca** [comment]
Note to IT: now this one is testable

**Comment by metas-mk** [comment]
Tested. Checked 
a) New and existing Sales Oder: OK
b) New and existing ASI in Sales Order Line: OK
c) New and existing Location: OK

Done. Closing.
