### ISSUE TITLE
Fix invalid "GET /window/{windowId}/{tabId} call

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#774]
### Type of issue
Bug / Feature request
### Expected behavior
After creating a new sales order the frontend is issuing an invalid GET.

### Steps to reproduce
* go to sales orders view first: https://w101.metasfresh.com:8443/window/143
* press New to create a new sales order
* frontend calls "GET https://w101.metasfresh.com:8443/rest/api/window/143/1" => NOK
it shall be https://w101.metasfresh.com:8443/rest/api/window/143/1005226/1 (remark the document ID).

![image](https://cloud.githubusercontent.com/assets/1244701/26305842/9c63148e-3ef9-11e7-9037-d96dcb861d7e.png)

**Comment by damianprzygodzki** [comment]
Cannot reproduce that case.

- going to docList (/window/143)
- three dot menu -> new
- everything as should be, one call for new document, then fetching data for created id, then the layout, and tabs.

**Comment by teosarca** [comment]
Another test case:
Also try opening sales orders grid view.
Open an order from there then hit back (to view).
Open another one then hit back (to view).
....

**Comment by metas-lc** [comment]
IT
created new order => document_id appears in get request method OK
Open an order from there then hit back (to view) several times => document_id appears in get request method OK
