### ISSUE TITLE
Sorting of Included Tab columns

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#781]
### Type of issue
Feature request
### Current behavior
Currently, it is not possible to sort in included tabs. Some included Tabs can have many rows, so that it makes sense to be able to sort them.
### Expected behavior
Allow the sorting in included Tabs, same as in Grid View of Main windows.

![image](https://cloud.githubusercontent.com/assets/13365687/26352041/53ffc4b4-3fba-11e7-8cf8-3046cbbe165d.png)

**Comment by teosarca** [comment]
API provided: https://github.com/metasfresh/metasfresh-webui-api/issues/412

**Comment by metas-mk** [comment]
Tested. Works as required. Initial Sorting also works nicely (e.g. Pricelist Window). Closing.
