### ISSUE TITLE
window endpoint: change "attribute" to "field"

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#787]
### Type of issue
Feature request

Follow-up to https://github.com/metasfresh/metasfresh-webui-frontend/issues/763#issuecomment-303738134

Basically you shall not use the deprecated methods from http://w101.metasfresh.com:8081/swagger-ui.html#/window-rest-controller

**Comment by teosarca** [comment]
Quick tested on view attributes,
There the "attribute" shall be used and not "field" because those are really attributes.

![image](https://cloud.githubusercontent.com/assets/1244701/26439162/914a125e-412f-11e7-9ecf-9510b7c5c967.png)

**Comment by metas-lc** [comment]
IT
checked attributes from hu editor, orderline and product price => dropdowns work fine
