### ISSUE TITLE
viewId shall be preserved if possible

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#79]
Test case:
- navigate to http://w101.metasfresh.com:8090/window/143
- suppose we get following URL with viewId: http://w101.metasfresh.com:8090/window/143/?viewId=164b149e-268a-423a-a7a4-feed0190733e
- press refresh or try opening that URL in other browser window or other browser or other computer
- instead of preserving the viewId=164b149e-268a-423a-a7a4-feed0190733e a new viewId is created => NOK

How it shall work:
- if there is an ?viewId URL parameter, the frontend shall try to BROWSE that viewId
- if the backend fails to browse that viewId (i.e. because for some reason the viewId does not exist)
  *\* the frontend shall inform the user (i.e. display the error)
  *\* the fontend shall create a new viewId and browse it (like it is doing now)

**Comment by teosarca** [comment]
NOTE: to restore the current active filters, please check https://github.com/metasfresh/metasfresh-webui/issues/39

**Comment by cadavre** [comment]
Reference: https://github.com/metasfresh/metasfresh-webui-frontend/issues/61

@teosarca shall we then implement checking if viewId exists and if not – generate new etc? According to #61 you were up to improving viewId functionality so it is saved "forever". Does it make sense to implement checking/regenerating if you're about to make viewIds "forever"?

PS Right now viewId is *not* used due to waiting for future changes.

**Comment by teosarca** [comment]
@cadavre basically you are right, but nevertheless we shall cover the case when for some reason the viewId is missing (because it was too old and cleaned up or something).

**Comment by teosarca** [comment]
Got this issue again and it's very simple to reproduce:
* open a particular sales order
* menu -> pick some document references => so you got the view and URL has the viewId param
* refresh in browser
* the frontend is asking the API to create a new view even the one from there is perfectly OK

See:
![image](https://cloud.githubusercontent.com/assets/1244701/20570828/c80910ae-b1ad-11e6-8063-e9daaa494de2.png)

**Comment by teosarca** [comment]
I think this issue is much more important than it looks because the standard use case which could annoy the user is using the Back & Forward browser buttons.

**Comment by metas-mk** [comment]
agree. we should priotize this for next iteration.

**Comment by cadavre** [comment]
To summarize things to be done in next iteration:
Create method checking if provided in URL viewId is valid – if yes: reuse it, of not: recreate viewId based on selected params (if any) or create new default view.

**Comment by teosarca** [comment]
Status update: the viewId is preserved but in case it's not present, frontend is not creating a new one.

**Comment by teosarca** [comment]
@cadavre in case the viewId is not present, is frontend requesting a new viewId?

**Comment by cadavre** [comment]
TODO: handle 404
