### ISSUE TITLE
Advanced edit section header for better structuring

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#790]
### Type of issue
Feature request
### Current behavior
Currently, the functional grouping in Advanced Edit modal overlay is only done via own sections. This is shown with a wider gap between the section groups. The group elements are chosen because or their fitting functional relations or meanings.
### Expected behavior
It could be a good idea to be able to define section names, that could be visible splitting the advanced edit screen into multiple section groups. This could allow the User to scroll faster but still to have a visual indicator where she/ he is during scrolling.
### Steps to reproduce
Open the prototype  Sales Order window and see.

@cadavre WDYT?

![image](https://cloud.githubusercontent.com/assets/13365687/26444102/45a5e150-413b-11e7-9203-2ae008755802.png)

**Comment by metas-mk** [comment]
Info for backend: The Section Group Names must me translatable in the cases described above. Introduce Value Fields to Section Names.

**Comment by cadavre** [comment]
Sounds good to me!

**Comment by damianprzygodzki** [comment]
Please provide from API property for section: `title`.

**Comment by metas-mk** [comment]
@damianprzygodzki Can u pls check the Layout. The lines shall not be split onto multiple lines.
![image](https://cloud.githubusercontent.com/assets/13365687/26508124/b756e07e-4253-11e7-8bce-2214edbc74b3.png)

**Comment by metas-mk** [comment]
Tested on w101. Works as required. Closing.
