### ISSUE TITLE
Zoom-To for empty "null value" fields error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#793]
### Type of issue
Feature request
### Current behavior
Currently, when using Zoom-To for empty Fields (null value) the user gets an error message.
### Expected behavior
Instead of providing an error message for the user, we could open the window in grid view in such cases or even better in case "New" is allowed in the opened window then open the window and automatically start "New" action.
The solution shall work w/ label Zoom-To and Grid.

![image](https://cloud.githubusercontent.com/assets/13365687/26448831/8bcd3df4-414f-11e7-9972-dfe44e55b4dc.png)

**Comment by damianprzygodzki** [comment]
As i understand the zoomInto generating process, this case is impossible. The backend is not delivering `windowId`.

**Comment by cadavre** [comment]
Waiting for API.

**Comment by teosarca** [comment]
Solved on backend side: https://github.com/metasfresh/metasfresh-webui-api/issues/401#issuecomment-312315842

**Comment by metas-mk** [comment]
Will be solved only on API side. No frontend change needed. Closing this one.
