### ISSUE TITLE
Action/ Quickaction Layout wrong

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#797]
### Type of issue
Bug
### Current behavior
The Included View Action/ Quick action/ Filter possibilities were implemented but it was forgotten to move the Action/ Quick action for the main view.
### Expected behavior
The Action/ Quick action for the main view shall be shown aligned right over the main view (e.g. not over attribute element). See attached image.

![image](https://cloud.githubusercontent.com/assets/13365687/26484000/48ce14dc-41f0-11e7-9014-885fb9b3bf9f.png)

**Comment by cadavre** [comment]
I think it's not really needed, because "Selection attributes" – as name points it – are attributes for selection made in what you called "main view". From my perspective – keeping quick actions on the right:
1. Is correct in UX view.
2. It doesn't leave pointless gap on the right.
3. It is how it was already implemented and used for few months plus and there were no objections about usability of it.

Any arguments for this change?

**Comment by metas-mk** [comment]
@cadavre 
> Any arguments for this change @metas-mk ?
We discussed the argument in jour fix 2 weeks ago when talking about the included view for handling unit selection, which has its own action context. In this scenario it may work to keep the actions where they are atm, but imagine screens where we don't want to hide the main actions after opening the included view, then you have 2 actions overlaying each other or in those cases then start moving the main action to the left into the"middle". 
Another argument: As discussed w/ Damian in nextgen chat, the actions don't belong to the "selection attributes" they belong to the handling unit selections, and the user has to understand that.

If you have time, let's talk again about this issue quickly.

**Comment by metas-mk** [comment]
btw.
> 2. It doesn't leave pointless gap on the right.

This one would annoy me too ;-)

**Comment by teosarca** [comment]
IMHO, this issue is clarified and development can start.

**Comment by cadavre** [comment]
@teosarca would talk first to Mark if you have any other idea of solving this.

This issue goes nonsense because it has nothing to do with "improving" anything. Just pure time-hole filler for me.

**Comment by metas-mk** [comment]
@cadavre ?!? I have a strong feeling that you haven't understood the issue. 

That's why I proposed here https://github.com/metasfresh/metasfresh-webui-frontend/issues/797#issuecomment-305500337 to have a quick talk.

> If you have time, let's talk again about this issue quickly.

Again, I would propose to talk about this issue to not waste further time and effort.

**Comment by cadavre** [comment]
As discussed and thought:
1. For single view visible on screen (gridview + selection attributes) – we keep as it is now: quickactions button to the right. The only thing we would change a little bit is margin between gridview and selection attributes to LESS. I would propose to fit it with @Dunkat live on screen.
2. For double views opened (table-by-table) we KEEP "old" actions button (belonging to that table) above this table to right but make it disabled and with same opacity lowered as gridview. Also increase margin a little between tables and make separator more visible and also in pagination area.

**Comment by cadavre** [comment]
For future notice: while creating usability-driven issues – please write down usability issue to discuss, not immediately propose its solution. :)

**Comment by metas-mk** [comment]
@cadavre 

> please write down usability issue to discuss, not immediately propose its solution. :)

agree +1 :-)

**Comment by cadavre** [comment]
Just to explain why I changes labels:

Due to previous agreements made in https://github.com/metasfresh/metasfresh-webui-frontend/issues/741#issuecomment-302053902 this issue is not a bug, but enhancement to previous assumptions.

**Comment by cadavre** [comment]
UPDATE: We also have filters that may be visible for gridview – and I think it's the same case as for quickactions: disable click and add opacity. It would work nice when user actually selected some filters and it is this filtered data that he can see in gridview.

**Comment by metas-mk** [comment]
@cadavre +1

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
