### ISSUE TITLE
Included row: show row's references in context menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#801]
### Type of issue
Feature request

### Expected behavior
When user is right clicking on an included row, below "Zoom into" and "Advanced edit" please also render row's referenced documents.
To fetch them pls call [/rest/api/window/{windowId}/{documentId}/{tabId}/{rowId}/references](http://w101.metasfresh.com:8081/swagger-ui.html#!/window-rest-controller/getDocumentReferencesUsingGET_1) endpoint.

I would suggest to not wait for "/references" endpoint and then show the popup but the popup shall be displayed ASAP and at the place where the references will be (if it will be!) show something like "(gear) finding references...".
As soon as the endpoint responds, the "(gear) finding references..." shall vanish and in place the actual references shall be shown.
If there were no references then show nothing.

It shall look something like this:
![image](https://cloud.githubusercontent.com/assets/1244701/26496731/5dafb40a-4231-11e7-8391-31102c8eb35a.png)

Backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/414

**Comment by metas-mk** [comment]
@Dunkat 
Works nicely, but can you please open the window in a new Tab (same as zoom-to). Not a Bug but additional/ forgotten requirement. Thx. ;-)

**Comment by cadavre** [comment]
We are calling additional endpoint `/references` and waiting for its response. With following statement:

> I would suggest to not wait for "/references" endpoint and then show the popup but the popup shall be displayed ASAP and at the place where the references will be (if it will be!) show something like "(gear) finding references...".

It causes UI to blink. Imagine if user wants quickly click Delete but, POP!, in moment he moved mouse to "Delete" references loaded up and "Delete" moved few hundred pixels away.

Small UX suggestion: show references in submenu, call API for /references after user hovers above "Referenced documents". Submenu will show up immediately with spinning loader and load up after API call is done. This will also decrease number of unnecessary API calls.

What I'm talking about ("New" -> "References documents"):
https://upload.wikimedia.org/wikipedia/en/thumb/5/50/Context_menu_windows.png/233px-Context_menu_windows.png

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
