### ISSUE TITLE
User/ Session Settings w/ Avatar and Logout

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#802]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the user settings are available the action menu. Same for Logout possibility. The current possibility for the settings is only the language.
#### Which are the steps to reproduce?
Check it out.
### What is the expected or desired behavior?
It is not perfect, to have the settings or other general actions (like logout) in the action menu. All other actions there are belonging to the underlying selected data.
The settings shall be a user changeable and persistable setting. 
It shall be shown in the top-right corner of the metasfresh application as an avatar of the user. The user can change and persist his/ her own settings. The user shall be able to press on his/ her avatar and change the settings like language, name, birthdate, image/ photo (could also be the email address to Gravatar), also a nickname, first name, last name. What about persisting these settings into ad_user? In future here will also be the possibility to authorize metasfresh to use the users GitHub account.
These are first rough ideas.
@cadavre WDYT?

**Comment by cadavre** [comment]
TODO:

1. Stack in single `/api/userSession/me` information about: language, avatar URL, username and user ID. Avatar URL shall be generated by backend based on avatar/gravatar selection (complete url for uploaded avatar /or/ complete url for gravatar image).
2. Add link to avatar topbar context menu to open user profile preferences (via /53100). We need user ID from `/api/userSession/me` to open right `/53100/userId`.

> In future here will also be the possibility to authorize metasfresh to use the users GitHub account.

Let's talk about this in dedicated issue #837 and not bother here anymore.

**Comment by teosarca** [comment]
API provided and documented here: https://github.com/metasfresh/metasfresh-webui-api/issues/434#issuecomment-306557238

**Comment by teosarca** [comment]
Edit 2: also very important, don't forget to connect/disconnect to user session websocket endpoint

**Comment by damianprzygodzki** [comment]
Add layout refresh after new language value.

**Comment by teosarca** [comment]
Quick tested:
* suppose your session expired (or you logged on from another tab)
* click on Avatar -> Settings
* => Login page is displayed => OK, pls log in
* instead of user profile window, frontend shows:
![image](https://user-images.githubusercontent.com/1244701/27080729-d444642c-5045-11e7-85d9-73e398304682.png)

**Comment by damianprzygodzki** [comment]
It looks like solved in meantime. Cannot reproduce.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Also, Language switch in my Profile window leads to immediate refresh. Close/ Done.
