### ISSUE TITLE
Clicking on a menu item shall open the view without any filter

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#804]
### Type of issue
Bug

### Steps to reproduce / Expected behavior 
* open a sales order, e.g. https://w101.metasfresh.com:8443/window/143/1004514
* go to referenced documents and click on Shipments so the view with the shipments related to that sales order are shown => OK
![image](https://cloud.githubusercontent.com/assets/1244701/26548773/7864f234-447e-11e7-9522-22fad4beb1a6.png)

* click on any of those "Shipment" breadcrumb items => NOK nothing happens, i.e. preserves the current filtered shipments => Expectation: it shall display ALL shipments like when we would open a new Shipments window
![image](https://cloud.githubusercontent.com/assets/1244701/26548844/c684093c-447e-11e7-911b-1474d53d15d3.png)

* click on menu and then on Shipment => NOK, nothing happens (same as above)
![image](https://cloud.githubusercontent.com/assets/1244701/26548892/f246b8da-447e-11e7-8434-8fa70cfea32a.png)

* open the sitemap from there click on Shipment => all shipments are displayed => OK - this is how all others shall work
![image](https://cloud.githubusercontent.com/assets/1244701/26548940/23caeea8-447f-11e7-8e2d-dfd1312715ed.png)

**Comment by teosarca** [comment]
Quick tested: everything works fine but when u press the browser back button nothing happens (beside the URL that is changed).

![image](https://cloud.githubusercontent.com/assets/1244701/26580128/736c7132-453f-11e7-8b8c-cbbb8c80d467.png)

![image](https://cloud.githubusercontent.com/assets/1244701/26580145/8d77d238-453f-11e7-8a70-9b57d0db78d9.png)

![image](https://cloud.githubusercontent.com/assets/1244701/26580166/a68ddd30-453f-11e7-9e08-871b35128880.png)

**Comment by metas-mk** [comment]
Tested. Works as required. Closed.
