### ISSUE TITLE
Kickstart Avatar button

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#809]
This issue it's a split off https://github.com/metasfresh/metasfresh-webui-frontend/issues/802 which shall deliver only the minimal functionaly.

### Type of issue
Feature request

### Expected behavior
* have a Avatar button on the top right side of the browser window
* for now, the avatar shall be just a "no name" picture.
* when clicked, it shall show following options (which basically shall be moved from Action menu)
** Settings
** Logout

**Comment by cadavre** [comment]
Assigned graphic designer for work tomorrow – will provide exemplary design.

**Comment by cadavre** [comment]
The idea for placement is to "always keep avatar as first element on right side of notifications".

If no "Side list":
![avat1](https://cloud.githubusercontent.com/assets/461796/26630916/11d9461e-4609-11e7-9fe9-1273783a4b0f.png)

If "Side list" is shown:
![avat2](https://cloud.githubusercontent.com/assets/461796/26630922/15fa09d6-4609-11e7-86f4-c93f58ceb660.png)

With shortcut we can do one of:
1. Not add shortcut for avatar menu to not override already learned [Ctrl]+[4].
2. Set [Ctrl]+[4] as shortcut for avatar menu and assign [Ctrl]+[5] to Side list.
Please choose ^.

Finally nice placeholder for "no avatar" 😉:
![av3](https://cloud.githubusercontent.com/assets/461796/26631288/9dbf26a2-460a-11e7-9c2e-577dbbe6d573.png)

**Comment by metas-mk** [comment]
Shortcut: Pls take option Set [Ctrl]+[4] as shortcut for avatar menu and assign [Ctrl]+[5] to Side list.

**Comment by metas-lc** [comment]
IT
1. Dashboard
=> Avatar is on right (last button)
- ctrl+4
=> avatar dropdown opens and you have settings and logout (both working)
- navigate with keyboard
=> works

2. Sales order, doc view
=> Avatar is on right, next to last button (between notifications and sidelist)
=> last button is the sidelist
=> ctrl+4 opens the avatar, ctrl 5,6 and 7 are for sidelist and keyboards navigation works
=> you have settings and logout (both working)

3. Sales order, grid view
=> Avatar is the last button on right (near notifications)
=> ctrl+4 and keyboards navigation works
=> you have settings and logout (both working)
