### ISSUE TITLE
quickInput endpoints are wrongly called

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#810]
### Type of issue
Bug

### Current behavior
quick input not working

### Expected behavior
shall work

### Steps to reproduce
* create a new sales order
* click on 'Batch entry' and start typing into Product field.
* server throws exception: "For input string: "quickInput""

#### Reason:
The call is: /rest/api/window/143/1003639/quickInput/1/field/M_Product_ID/typeahead?query=to
It shall be: /rest/api/window/143/1003639/1/quickInput/1/field/M_Product_ID/typeahead?query=to
Remark: the tabId is missing between "documentId" and "quickInput" string.

Also please make sure all the quickInput endpoints are correctly called: http://w101.metasfresh.com:8081/swagger-ui.html#/window-quick-input-rest-controller

**Comment by metas-lc** [comment]
IT
sales and purchase order:
- batch entry - works OK
- add new - does not work NOK
- editing directly on the line or changing the product with advance edit does not work NOK

![changeproduct](https://cloud.githubusercontent.com/assets/16001666/26620025/c20cb004-45e9-11e7-8faf-f3c5114c0153.png)


- (not sure if related) if you have 2 lines with product, removing 1 line will remove both (on refresh 1 comes back) NOK

**Comment by teosarca** [comment]
for future reference, this issue was introduced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/787

**Comment by teosarca** [comment]
note: i will create several tasks for reported issues because they are not related with this task.
