### ISSUE TITLE
Deleting a row in included tab makes the included tab empty

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#814]
### Type of issue
Bug

### Steps to reproduce
* create a new sales order
* create more then one lines
* right click and delete one of those lines
* the tab becomes empty => NOK
![image](https://cloud.githubusercontent.com/assets/1244701/26621690/3eee7192-45f0-11e7-9c38-0f7515d331df.png)

* after browser refresh, the tab gets the correct data
![image](https://cloud.githubusercontent.com/assets/1244701/26621706/5209e694-45f0-11e7-83c3-e5c604d83d3c.png)

**Comment by metas-mk** [comment]
Tested. Works as required. Closing.
