### ISSUE TITLE
attributes are missing

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#815]
### Type of issue
Bug 
### Current behavior
hu editor, select a TU or a LU => attributes are not displayed 
sales order, select a line, advance edit, try to set attributes => nothing happens
### Expected behavior
attributes should be displayed
### Steps to reproduce
1. go to Material Receipt Candidates, select a line, receive HUs (green button)
2. select a line => the attributes are missing NOK

![missing_attributes](https://cloud.githubusercontent.com/assets/16001666/26622174/30abc128-45f2-11e7-8630-999caab790a7.png)

1. go to sales order, pick a product that has attributes (e.g. see order https://w101.metasfresh.com:8443/window/143/1005337)
2. go to advance edit and try to set attributes (or try to set them directly on the line)
=> nothing happens NOK
(also happens if you go in other places where it's used, e.g. product price https://w101.metasfresh.com:8443/window/540325/2767129)

![attributes_notdesplayed](https://cloud.githubusercontent.com/assets/16001666/26622527/6364264a-45f3-11e7-8903-7a24643c96dc.png)

**Window:** 540196

**Comment by metas-mk** [comment]
Tested. Works as required (Sales Order Grid View, Material Receipt, Action Issue and Receipt, Sales Order Advanced Edit.). Done.
