### ISSUE TITLE
Double arrow-down for Dropdown selection

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#816]
### Type of issue
Bug
### Current behavior
After the new Lookup revamp, the dropdown opens and the user has to press 2 times arrow down to start navigating selection.
### Expected behavior
1 Arrow down should be enough to move the first step.It should be 
### Steps to reproduce
Open a new Sales Order. Focus is on Business partner field. Type a few Chars to the dropdown appears. Press arrow-down once. Nothing happens. Press a second time, moved down.

belongs to https://github.com/metasfresh/metasfresh-webui-frontend/issues/600

**Comment by cadavre** [comment]
For me one arrow down is working (branch:master, master doc window). One way or another we shall automatically select first element in suggestions to be able to press [Enter] even without pressing arrow keys. Wdyt?

**Comment by teosarca** [comment]
note: not sure but it might overlap with https://github.com/metasfresh/metasfresh-webui-frontend/issues/820

**Comment by cadavre** [comment]
### Expected behaviour

When suggestion window pops-up it shall have 1st element selected by default to just press [Enter] to accept.

**Comment by metas-mk** [comment]
@Dunkat 
Tested quickly. 
Hard to explain but will try. Please open the sales order window window/143/ press "new". The focus is not in combined business Partner Field. Type there directly "test". A dropdown appears. Now go with arrow down to the middle of the dropdown. Press [esc]. The cursor is back in combined field. Please press backspace to delete that "test", now type "krake". Dropdown appears but no auto selection of first entry, and it is not possible to go down w/ arrow for further selection.

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
