### ISSUE TITLE
Sometimes i get "Connection lost" after login

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#817]
### Type of issue
Bug

### Current behavior
Sometimes after i enter my credentials and i log in i get the "Connection lost" overlay.
I think the pattern is something like this:
* i the frontend opened in browser showing the dashboard (main screen). I think this is important because on dashboard screen frontend continuously issues queries to backend.
* interrupt the connection, remove the cookies - i.e. usually i am stopping the server
* after a while i am starting the server
* when i am looking at the browser tab I see i am on login screen (not sure how i got there)
* i am entering the credentials and then i log in
* frontend shows the dashboard screen but on top of that the "Connection lost" overlay is shown.

It happens to me several times, but not very often.
I am opening this task to gather more infos from everyone and to keep an eye on this issue.

**Comment by damianprzygodzki** [comment]
It is issue with a backend - check console. Sometimes, when you change the host (localhost -> w101 -> jzapp.io) it has recent settings. Nothing to do on front end with it.

**Comment by teosarca** [comment]
Hi @damianprzygodzki 

>  Sometimes, when you change the host (localhost -> w101 -> jzapp.io) it has recent settings

Can you give me more details about that. What kind of settings you observed?

**Comment by damianprzygodzki** [comment]
CORS. I believe that you are checking from which host request are comming, and saving it.

**Comment by damianprzygodzki** [comment]
XMLHttpRequest cannot load http://w101.metasfresh.com:8081/rest/api/documentView/143/layout?viewType=grid&supportTree=true. The 'Access-Control-Allow-Origin' header has a value 'http://master.metasfresh.jzapp.io' that is not equal to the supplied origin. Origin 'http://localhost:3000' is therefore not allowed access.

**Comment by damianprzygodzki** [comment]
Did i resolve the issue? Can be closed?

**Comment by teosarca** [comment]
10x.
moved to backend.
