### ISSUE TITLE
HTTP header "Accept-Language" shall be correctly set

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#819]
### Current behavior
None of the API calls have the "Accept-Language" header set.

### Expected behavior
All API calls shall have the "Accept-Language" header set to session language.
The "Accept-Language" shall respect the [RFC5646](https://tools.ietf.org/html/rfc5646#section-2.1).
e.g.
* if user session language is "en_US" => Accept-Language: en-US
* if user session language is "de_DE" => Accept-Language: de-DE
* if user session language is "de_CH" => Accept-Language: de-CH

NOTE: this feature is uber important for browser level caching of language dependent data (e.g. window layouts).

**Comment by cadavre** [comment]
I would also suggest to add "Content-Type: application/json" everywhere where there is communication in JSON and this header is not set. Didn't check if it is already sent so might be deprecated info. :)

**Comment by teosarca** [comment]
Quick tested:
* login on w101 (NOTE: by default i was logged in with en_US)
* open sales order grid view: https://w101.metasfresh.com:8443/window/143
* check the https://w101.metasfresh.com:8443/rest/api/documentView/143/layout?viewType=grid&supportTree=true endpoint's Accept-Language request header = > OK
![image](https://cloud.githubusercontent.com/assets/1244701/26714030/1f89591e-4778-11e7-887a-f6f1fc0d8d1c.png)


* in another browser tab, go to Settings and switch the language to de_DE: https://w101.metasfresh.com:8443/settings

* go back to your order grid view browser tab and hit refresh
* check the https://w101.metasfresh.com:8443/rest/api/documentView/143/layout?viewType=grid&supportTree=true endpoint's Accept-Language request header => NOK: it shall be de-DE
![image](https://cloud.githubusercontent.com/assets/1244701/26713981/e6148e06-4777-11e7-9b9e-95a7443ac2ae.png)

Also, when the "Disable cache" checkout is unticked (which is the normal use case) the Accept-Language header is missing even though backend provided "Vary: Accept-Language" response header...
Can you please also check that?

![image](https://cloud.githubusercontent.com/assets/1244701/26714151/e40ecad0-4778-11e7-8257-9999ae8dca0b.png)

**Comment by damianprzygodzki** [comment]
I have no ability to refresh one tab from another. If you want to have updated other instance, we have to connect WS to settings.

**Comment by teosarca** [comment]
Hi, i think u commented on the wrong task :) Isn't it?

**Comment by damianprzygodzki** [comment]
But thats the issue you've mentioned. To update request headers, in another tab, without refreshing. Or am i wrong?

**Comment by teosarca** [comment]
> But thats the issue you've mentioned. To update request headers, in another tab, without refreshing. Or am i wrong?

In my test case, i've refreshed the browser page (like F5 or CTRL+R) and in that case i would expect the right Accept-Language to be set...
Isn't that not doable?

**Comment by damianprzygodzki** [comment]
The language of user is fetched from API. So rendering (and fetching other stuff) is faster then setting language after local login. Check that quickActions request has header with proper language.

**Comment by teosarca** [comment]
ok thanks,

> EDIT: My solution for it, is creating localStorage variable with language.

btw, what would be the downside of it?

**Comment by damianprzygodzki** [comment]
1st issue fixed, now we have localStorage variable, can't see downside, when is not set, will be used default value from browser. 2nd issue i believe is a case of self signed certificate @cadavre ?

**Comment by cadavre** [comment]
@teosarca about 
> Also, when the "Disable cache" checkout is unticked (which is the normal use case) the Accept-Language header is missing even though backend provided "Vary: Accept-Language" response header...

Please re-check this one, because the headers you got back and just provisional (emulated by browser because of [200 Read from disk cache]). Clear whole browser cache and start from 0 point. It might happened that it loaded this API call from cache from time before it was even implemented. :)

Clear cache, re-check, waiting for feedback.

**Comment by teosarca** [comment]
Hi guys, quick checked and it seems to work nice!
Will move it to Testing for future testing.
Thanks.

> Clear cache, re-check, waiting for feedback.

nop, wasn't that case. The actual issue was the one that Damian fixed in last commit.

**Comment by teosarca** [comment]
@damianprzygodzki  @cadavre 

> 2nd issue i believe is a case of self signed certificate @cadavre ?

Nop. We are using real certificates, for a while.
Remark that it's green:
![image](https://cloud.githubusercontent.com/assets/1244701/26728763/0127faca-47b4-11e7-9a0d-768362fc8554.png)

**Comment by metas-lc** [comment]
IT
checked content language and accept language after changing it several times + refreshing the page. => language was updated OK
