### ISSUE TITLE
Combobox's current value shall be selected by default in dropdown

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#820]
### Current behavior
When the combobox's dropdown list is open, the previous value is selected, no matter which is the current value.

### Expected behavior
The current value (if any and if present in combobox list) shall be selected.

### Steps to reproduce
* open settings https://w101.metasfresh.com:8443/settings
* change language to en_US
* click on dropdown
* change language to de_DE
* click on dropdown
=> the selected language is en_US (the previous one) => NOK
The de_DE shall be selected.

![image](https://cloud.githubusercontent.com/assets/1244701/26671617/ca2cb2ea-46be-11e7-942c-8e650957842d.png)

**Comment by cadavre** [comment]
### Expected behaviour

When suggestion window pops-up for already filled field it shall be selected.

**Comment by metas-lc** [comment]
IT
1. go to settings, change language multiple times
=> each time you select the dropdown, the language you have is the one selected
