### ISSUE TITLE
Filter criteria not shown when typing error

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#829]
### Type of issue
Bug
### Current behavior
In the case of Filtering in Lookup Field, selecting and then clearing the filter w/ crossed-circle and then writing, the Filter typeahead does not work properly. The Characters are not shown and the number of characters in the filter is wrong ) only 1, not a string)
### Expected behavior
Shall be fixed
### Steps to reproduce
Open Window window/540189

![image](https://cloud.githubusercontent.com/assets/13365687/26719309/4f0c0cf2-4784-11e7-9936-299aae3befcf.png)

**Comment by metas-lc** [comment]
IT
1. open Handling Unit window, filter for warehouse
=> typehead is a string OK
2. clear the filter with (x) and start writing again
=> typehead is a string OK
3. clear the filter using "clear filter" and then filter again 
=> typehead is a string OK
