### ISSUE TITLE
Create new bpartner (from lookup) not working

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#832]
### Type of issue
Bug

### Steps to reproduce
* new sales order
* type something that does not exists in bpartner field
* click on "New Business Partner"
=> ERROR => the API calls are not correct

![image](https://cloud.githubusercontent.com/assets/1244701/26734469/cdbde588-47c6-11e7-9c43-d703e96a5de4.png)

And more, from now how wherever you navigate it seems those 2 wrong API calls are called again and again (NOTE: i am not in the sales order window anymore).
It seems that after that error the state is corrupted.

e.g. i opened the BPartner window from main menu and i was navigating around:
![image](https://cloud.githubusercontent.com/assets/1244701/26734686/a3b3fba0-47c7-11e7-97a8-cf515f50ed75.png)

**Comment by metas-lc** [comment]
IT
1. create new order and write a bpartner's name that does not exists.
2. create the new bpartner directly from order
=> works, no errors OK
3. add a product, complete
=> no errors
