### ISSUE TITLE
Collapse functionality in Grid View included rows

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#835]
### Type of issue
Feature request
### Current behavior
Currently, we don't have the possibility to fold/ unfold groups for large data sets in Grid Views included rows. Something like a collapse functionality w/ group (top node/ root) and detailed data.
### Expected behavior
Have the functionality to provide the Grid View Tree with top lines in collapsed mode (not seeing the detail lines) and via icon/ button to expand the view for that or all groups.

Backend task: https://github.com/metasfresh/metasfresh-webui-api/issues/424

**Comment by cadavre** [comment]
Additionally, as talked: add flag in API which will define if gridview shall be initially expanded or collapsed. In `/layout` of document view let's introduce flag called `expanded=true|false`.

To think about: introduce in UI a link-button to "Expand all" or "Collapse all".

**Comment by cadavre** [comment]
@metas-mk @teosarca proposal of design and functionality of collapse/expand:

![collapse functionality 2x](https://user-images.githubusercontent.com/461796/26932419-b83d402c-4c63-11e7-9509-2a272984c3a7.png)

@metas-mk what was the decision about "Expand all" and "Collapse all" buttons?

**Comment by teosarca** [comment]
> Additionally, as talked: add flag in API which will define if gridview shall be initially expanded or collapsed. In /layout of document view let's introduce flag called expanded=true|false.

update: API ready

**Comment by cadavre** [comment]
@teosarca and how about API flag to define which view actually should have possibility to use expand/collapse function? I can see only flag for initial `expanded=true|false`, but as @metas-mk stated:

> what you mean is to have collapse/expand only on root elements? **yes**
but, if **the api decides what shall be collapsible** and what not, then we can leave the design like it is

we need additional flag like `collapsible=true|false` which will turns on/off this function.

Also additional assumption here: we make collapse/expand only on root elements.

**Comment by teosarca** [comment]
> we need additional flag like collapsible=true|false which will turns on/off this function.

will talk with Mark and will provide. For now, pls consider missing "collapsible" as collapsible=true.

**Comment by teosarca** [comment]
@damianprzygodzki @cadavre  some test cases to check:

Case 1: window will expanded=false
https://w101.metasfresh.com:8443/window/540345
![image](https://user-images.githubusercontent.com/1244701/26965510-ba1d13d6-4cfe-11e7-8e26-ada8e2de2611.png)


Case 2: window with expanded=true
* https://w101.metasfresh.com:8443/window/540189
* any HU Editor
* Issue/Receipt

**Comment by metas-mk** [comment]
@damianprzygodzki @cadavre 
After talk w/ damian/ teo we decided to drop intial "row level" definition of expanded=true/false and instead gon in direction of expanded_depth = 0, 1, ..., 999 on layout level (or something similar)

to be decided/ agreed

**Comment by damianprzygodzki** [comment]
Case of changing `expanded` property to `expandedDepth`:

-for `collapsedDepth: 0` - all rows should be collapsed __initially__
-for `collapsedDepth: n` - all rows that have indentation on  __level `n` and deeper__ should be collapsed __initially__

**Comment by damianprzygodzki** [comment]
Waiting for `collapsible` and `expandedDepth` properties from API.

**Comment by teosarca** [comment]
IMHO they are already provided. Pls check out if it fits.
I would suggest to check with following windows:
* https://w101.metasfresh.com:8443/window/540345
* modal HU Editor
* modal PP Order Issue / Receipt
* regular HU window: https://w101.metasfresh.com:8443/window/540189

**Comment by damianprzygodzki** [comment]
@teosarca I've encountered one problem. 

The key value for table component is `id` or `rowId` (depends on if we are in gridview or in tabs for document).

On that value relays thing such as selection, quickActions, selectionAttributes, collapsing and so on. I wonder if we should relay on that properties further, because for one window that has collapsing enabled (540345) the documents have the same id.

Could API provide unique key (maybe some additional, straight from database) for docs in tables?

**Comment by metas-mk** [comment]
Tested.
a) Open the window
b) Press on Table Header Column to sort by.
c) Press on the first line [+] to expand. Nothing happens. NOK

![image](https://user-images.githubusercontent.com/13365687/27089667-5e0af170-505b-11e7-84d3-b927635a9cf3.png)

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
