### ISSUE TITLE
Outbound eMail functionality

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#836]
### Type of issue
Feature request
### Current behavior
Currently, we don't have the possibility to send eMails out with an attached document. In Swing client, we have the possibility to press on Mail Icon/ Button, the mail window is opened and if possible the eMail-Adress is automatically added together with existing PDF.
### Expected behavior
We need such a Mail functionality also for metasfresh WebUI. If this is possible to achieve also with external mail clients it would be perfect (something like a mailto functionality, add mail address and attachment). If not then with an incorporated eMail client window with these functionalities.

First rough ideas.

**Comment by cadavre** [comment]
Not to accomplish with "mailto:" and front-end WebUI.

How it can be done:
1. In "Attachments" we add "mail" icon-button.
2. On click we open modal with fields: "to", "subject" and "message" to fill. Selected attachment is automatically added to this email.
3. Backend API is utilized to send email with SMTP client.

^ Only way to accomplish it as automatic function.

**Comment by damianprzygodzki** [comment]
I am adding `mf-turn` because of planning work and not resolved questions here.

**Comment by metas-mk** [comment]
@damianprzygodzki 

> In "Attachments" we add "mail" icon-button.
Nope, that's the wrong place. It's not intuitive for the user to have to go to attachments to send an email. 

Proposal instead:
There should be an eMail Action in action menu. When the user presses that, a modal overlay eMail editor opens, and the document is attached as PDF ( the same document that is rendered and opened in new Tab when pressing "print" action). Additionally, the to MailTo Field of the eMail editor automatically has the eMail address from the Business partner contact.

> On click we open modal with fields: "to", "subject" and "message" to fill. Selected attachment is automatically added to this email.

Agree, but ... the Subject can also be initially set with "DocType Name, Document No" and can be overwritten by the user.

> Backend API is utilized to send email with SMTP client.

Agree.

**Comment by damianprzygodzki** [comment]
Do i understand it correctly that it all will be done on backend side just as another action with parameters?

Do we need here new widget to display attached file?

**Comment by metas-mk** [comment]
@damianprzygodzki 
I believe in the backend it will be similar to what we already know w/ actions, BUT er need an eMail editor. Something that the user will recognize as such. Fields with Mailto, cc, bcc, Text Field that allows some kind of basic formatting (bold, italic, ...) Possibility to add Text Snippets (currently done with a Dropdown). New Field that allows taking the Attachment (possibility to add other attachments?).

**Comment by damianprzygodzki** [comment]
Okay, thanks.

As discussed on skype, waiting here for technical decision to let Mirek design something integrated with our components.

**Comment by teosarca** [comment]
Hi.

Here it's the first **non working** API prototype: http://w101.metasfresh.com:8081/swagger-ui.html#/mail-rest-controller

Basically, would work like ASI endpoint or similars, but there are also some differences.
Remark that the "To" field is an array of LookupValues which shall be somehow rendered by the frontend in a way that:
* user can add a new "To" email address provided by backend (by using the typeahead endpoint)
* user can add a (one time only) email address (i.e. frontend would add an { -1 : "john@doe.com" } to the To array.
* user can remove an address from the To list
Pretty much the same way as GMail's "To" field behaves would be gold.

Another difference is about adding a new attachment. We have a dedicated endpoint for that which would take the file, store it in some temporary storge and adding a look value to the "attachments" array., Something like { someId :  "TheFile.pdf" } .
Btw, attachments it's also a lookup array :)

We also have an endpoint for changing (PATCHing) the email user is composing.

And at the end, the "send" endpoint shall be called to send the email.

**Comment by damianprzygodzki** [comment]
@teosarca And the most important one, where it is available? Is it action? Is it new process response type?

**Comment by teosarca** [comment]
it will be available on several places, e.g. on single document page. We still have to define that.

**Comment by damianprzygodzki** [comment]
Design is in progress. Still waiting here with implementation for the infos about trigger action.

**Comment by metas-mk** [comment]
Places where available first:
* Sales Order window
* Purchase Order window
next step
* all other document windows

**Comment by teosarca** [comment]
@metas-mk  @damianprzygodzki  the frontend does not know it's a sales or purchase window. So i would suggest to have it in each window.

Another thing which shall be decided (i.e. the designer shall suggest) is how to visually open the EMail component. From where, precisely?

**Comment by teosarca** [comment]
API changes (please check swagger for details)
* /mail/templates endpoint which returns a list of key/value templates which user can pick from a dropdown and apply them to current email
* to apply a given template you shall use the regular PATCH operation with path="templateId", value={ templateId : templateName }

API is ready for frontend implementation.
Will be available on next rollout.

**Comment by metas-mk** [comment]
@damianprzygodzki 

> @teosarca And the most important one, where it is available?

Just to be sure that we all talk about the same. The eMail Action will be available here:

![image](https://user-images.githubusercontent.com/13365687/27171626-77dc325a-51b2-11e7-8bf9-51504ade4963.png)

**Comment by damianprzygodzki** [comment]
![send mail 2x](https://user-images.githubusercontent.com/5701744/27290329-28b570ac-550d-11e7-8978-b17285d92dae.png)
![email 2x](https://user-images.githubusercontent.com/5701744/27290348-35665960-550d-11e7-8892-06c09df3fb19.png)

Mirek proposed something like that. @metas-mk do we have acceptance with proceeding with that design?

**Comment by teosarca** [comment]
Thanks, looks nice.

For "To" field, I am wondering if we can have somelike tike that...  wdyt?

![image](https://user-images.githubusercontent.com/1244701/27294214-779452f6-5521-11e7-8c66-fff83e5af8f1.png)

**Comment by damianprzygodzki** [comment]
Do you want to typeahead in that field or just regex to group e-mails?

**Comment by teosarca** [comment]
both, similar with gmail.

**Comment by damianprzygodzki** [comment]
ok, then typeahead endpoint will be needed.

**Comment by teosarca** [comment]
> ok, then typeahead endpoint will be needed.

yup, it's available: [GET /rest/api/mail/{emailId}/field/to/typeahead](http://w101.metasfresh.com:8081/swagger-ui.html#!/mail-rest-controller/getToTypeaheadUsingGET).

**Comment by damianprzygodzki** [comment]
- add dropdown for email templates to modal
- get rid of risky styling features (leave b/i/u)
- give more place for "to" input

**Comment by Dunkat** [comment]
Email translation added:

``{"window.email.caption": "Email"}``

**Comment by Dunkat** [comment]
@teosarca how I can get email template? because response from http://w101.metasfresh.com:8081/swagger-ui.html#!/mail-rest-controller/getTemplatesUsingGET is always empty

**Comment by teosarca** [comment]
i've added some dummy text templates.

**Comment by cadavre** [comment]
Reopened due to wrong commit action.

**Comment by cadavre** [comment]
Please change template selector to "click to use" model:
1. Display placeholder for selector: "Templates".
2. On click show list of templates.
3. On template selected – use its text and display template selector back with placeholder "Templates".

**Comment by teosarca** [comment]
rolled to w101

**Comment by teosarca** [comment]
note to IT: to check the emails which were sent, use mail hog: http://w101.metasfresh.com:8025/

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* I attached pdf and png documents to the email and sent it. The e-mail was correctly sent ( verified via mail hog)
