### ISSUE TITLE
Combined Fields/ Lookup adjustment

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#839]
### Type of issue
Feature request
### Current behavior
In Issue https://github.com/metasfresh/metasfresh-webui-frontend/issues/600 we made the assumption, that default fields shall be directly selected when available and the user shall use the mouse to change if needed.
### Expected behavior
After receiving the feedback and to make the dropdown behavior more predictable for the user the behavior shall be adjusted to the following.

Always show the dropdown, also when there is a default property. Although default property is set, the frontend shall open the dropdown and select the default entry. The user just as to press [enter] to confirm. In case she/ he needs another selection different from default in those case just has to do the selection with arrow keys.
It's just important that the default shall be first in Dropdown and be selected initially when opening.

**Comment by cadavre** [comment]
Just popped on my mind: what if there is just one suggestion available. I would say to also display it even if it's only possibility to select. To be unified.

**Comment by metas-mk** [comment]
Tested. I like it :-)
Works nicely as required. Closing.
