### ISSUE TITLE
Open Sitemap shall focus on Search Field initially and more

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#840]
### Type of issue
Feature request
### Current behavior
Currently, when opening the sitemap, the navigational behavior is not optimized. The cursor is not initially placed in search Field. The navigation with arrows is not possible after the first navigation tree. Working w/ Tab sometimes leads to scrolling down.
### Expected behavior
Optimize the navigation via keyboard in Sitemap window.

**Comment by cadavre** [comment]
Shall work same as in Navigation menu?

[Tab] would then switch between menu tree and search input. Navigation on tree would happen with arrow keys.

Difference: on sitemap – after initially opened – focus first on search input.

_Eventually (if not happy with [Tab]) we could introduce this button to jump between main groups in tree._

**Comment by metas-mk** [comment]
@Dunkat 
Tested,
a) Focus and Arrow Keys navigation work nicely. OK
b) Selection of menu entry w/ [enter/ cr] does not work. NOK

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Done/ Closing.
