### ISSUE TITLE
Manufacuting Order Issue not possible after barcode filtering

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#845]
### Type of issue
Bug 

### Current behavior
cant issue after filtering

### Expected behavior
I should see the same actions as if I am not filtering and just selected one HU

### Steps to reproduce
1. open https://w101.metasfresh.com:8443/window/53009
1. search for pp order 630004 
1. click on issue/receive
1. click on p002735 and then issue
1. click on filter and select barcode
1. enter 1008965
1. NOK: issue is missing
![image](https://user-images.githubusercontent.com/16079655/26869058-55cab5d0-4b6b-11e7-8d8b-8599aeee49ac.png)

**Comment by metas-mk** [comment]
checked for HU Nr. 1008965 also in HU Editor. The HU is active.

**Comment by metas-mk** [comment]
Closing this issue. Belong to backend. Created there: https://github.com/metasfresh/metasfresh-webui-api/issues/436
