### ISSUE TITLE
Dashboard Button in Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#85]
Dashboard Button in Menu
- possibility to call the dashboard from home menu (without manually stripping the url)

**Comment by cadavre** [comment]
+1
Logo works as "back home" but I was thinking about the same thing today.

**Comment by metas-mk** [comment]
ah, right. thx for the reminder. so we have a workaround for right now. but agree that we should have an own button/ link in 'home menu' too.
