### ISSUE TITLE
After login to account, go to sitemap page, open develooper tab and start using scroll. 

### ISSUE THREAD

**Issue by Dunkat** [metasfresh/metasfresh-webui-frontend#854]
### Type of issue
Feature request

### Current behavior
Error in console
Browser: firefox, version 53.0.3 (64 bits)

### Expected behavior
No error in console

http://master.metasfresh.jzapp.io/sitemap

This issue is a part of #838

**Comment by metas-mk** [comment]
Tested in Firefox. Works as required. Done.
