### ISSUE TITLE
Missing shadow under top menu.

### ISSUE THREAD

**Issue by Dunkat** [metasfresh/metasfresh-webui-frontend#855]
### Type of issue
Feature request

### Current behavior
Missing shadow under top menu
Browser: firefox, version 53.0.3 (64 bity)

### Expected behavior
No missing shadow

### Steps to reproduce

**Link:** http://master.metasfresh.jzapp.io/sitemap

This issue is part of #838

**Comment by metas-mk** [comment]
Tested. When Screen is scrollable then the shadow is now shown underneath the top navigation in Firefox. Done/ Closing.
