### ISSUE TITLE
Change Placeholder name "Marcus Gronholm" to "Profile"

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#860]
### Type of issue
Bug
### Current behavior
Currently, the fixed name "Marcus Gronholm" is added to avatar dropdown.
### Expected behavior
Until the name is resolved correctly from frontend just write "Profile" instead.
### Steps to reproduce
Open the avatar button and see.

**Comment by metas-ts** [comment]
cherry-picked into the `release` branch

**Comment by metas-lc** [comment]
IT
name is now Profile. OK
