### ISSUE TITLE
Make remaining UI components translatable

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#861]
### Is this a bug or feature request?
feature

backend issue: https://github.com/metasfresh/metasfresh-webui-api/issues/443

## What is the current behavior?
lot of components not be translated and therefore remain static if you change the language

### grid buttons
- add new
- batch entry
![image](https://user-images.githubusercontent.com/16079655/26980899-c71e52c2-4d33-11e7-870a-f76487adcd07.png)

### context menu
- actions
- actions text if there are no actions
- settings
- logout

![image](https://user-images.githubusercontent.com/16079655/26981095-63d5a8fe-4d34-11e7-87a7-fc7a176715d9.png)

### menu search
![image](https://user-images.githubusercontent.com/16079655/26981148-84ec62f8-4d34-11e7-9ae8-234aa4ebe3a7.png)

### Tooltips
![image](https://user-images.githubusercontent.com/16079655/26981167-8f51bd24-4d34-11e7-8801-d09420a74d97.png)

### Page Record Navigation
![image](https://user-images.githubusercontent.com/16079655/26981181-a089014c-4d34-11e7-8e88-bb6ddfc1e8f3.png)

### attachment note
![image](https://user-images.githubusercontent.com/16079655/26981192-aa313a84-4d34-11e7-8a46-ef8451b4483c.png)

### Filter labels
![image](https://user-images.githubusercontent.com/16079655/26981217-b53b87e0-4d34-11e7-81b4-b2816f8d6746.png)_

#### Which are the steps to reproduce?
1. set language to de_DE
1. open sales order window
1. NOK: buttons are "add new"

### What is the expected or desired behavior?
buttons shall be translatable in one way

**Comment by metas-mk** [comment]
**Avatar Profile**: Settings and Logout
![image](https://user-images.githubusercontent.com/13365687/26981427-6a6e9efe-4d35-11e7-9229-6a51f3e8cfe9.png)

**Comment by teosarca** [comment]
I would suggest to proceed as follows:

1. Gather all those messages and organize them in a key/value map.
e.g. something like this but i am really open to other suggestions...
```
window.addNew.caption=Add new
window.batchEntry.caption=Batch entry
window.sideList.tooltip=Document list
...
```

2. We will define all those on server side.

3. The frontend shall call the /i18n/messages endpoint which will provide that key/value map.
See https://github.com/metasfresh/metasfresh-webui-api/issues/443#issuecomment-307522439

**Comment by teosarca** [comment]
If agree, guys, can u extract that list and feel free to define/organize them?

**Comment by metas-mk** [comment]
@teosarca I like the idea. Proposal for No. 1

> 1. Gather all those messages and organize them in a key/value map.
e.g. something like this but i am really open to other suggestions...

What about adding all those key/ values to ad_message table. We can also add a flag in there that defines "isWebUI" messages if needed. The value Field in messages can take the value key part like "window.sideList.tooltip" and the message Text will have the value part like "Document list". This way we could also easily use the translations in ad_message_trl.

**Comment by teosarca** [comment]
@metas-mk  basically that's what we do :) (without IsWebui flag)
see my comment here: https://github.com/metasfresh/metasfresh-webui-api/issues/443#issuecomment-307522439
mainly the second part.

**Comment by cadavre** [comment]
Before I even read @teosarca proposition – I had the same so +1 for me for https://github.com/metasfresh/metasfresh-webui-frontend/issues/861#issuecomment-307523247 .

**Comment by teosarca** [comment]
just to be sure, the [/rest/api/i18n/messages](http://w101.metasfresh.com:8081/rest/api/i18n/messages) endpoint is ready.

**Comment by cadavre** [comment]
Summarizing – for frontend this issue's TODO is:

- extract hardcoded strings into `translatable.identifiers`
- change hardcoded strings into `translatable.identifiers` in view templates
- implement API call to GET `/rest/api/i18n/messages`
- implement translation engine to swap `translatable.identifiers` into real strings from above API call

**Comment by teosarca** [comment]
Yes, and pls one that you can use as many dots you want, e.g.
```
window.batchEntry.caption=Batch entry
```

More, we can do this as an iterative process because on server side everything is ready and adding a new translation entry is an Admin/config job (i.e. no more development is required).
So basically, we can also implement this task in more then one working increments.

**Comment by Dunkat** [comment]
I prepared map of translations, please take a look if it's ok and if key naming is correct

{
    "window.dropZone.caption": "Drop files here",
    "window.advancedEdit.caption":	"Advanced Edit",
    "window.Print.caption":	"Print",
    "window.Delete.caption":	"Delete",
    "window.New.caption":	"New",
    "window.settings.caption":	"Settings",
    "window.logOut.caption":	"Log Out",
    "window.zoomInto.caption":	"Zoom into",
    "window.newTab.caption":	"Open in new tab",
    "window.delete.caption":	"Delete",
    "window.batchEntry.caption":	"Batch entry",
    "window.batchEntryClose.caption":	"Close batch entry",
    "window.addNew.caption":	"Add new",
    "window.sideList.documentList.tooltip":	"Document list",
    "window.sideList.referencedDocuments.tooltip":	"Referenced documents",
    "window.sideList.attachments.tooltip":	"Attachments",
    "window.sideList.attachments.empty":	"There is no attachment",
    "window.sideList.referenced.empty":	"There is no referenced document",
    "window.actionMenu.tooltip":	"Action menu",
    "window.navigation.tooltip":	"Navigation",
    "window.docStatus.tooltip":	"Doc status",
    "window.inbox.tooltip":	"Inbox",
    "window.userMenu.tooltip":	"User menu",
    "window.sideList.tooltip":	"Side list",
    "window.actions.caption":	"Actions",
    "window.elementToDisplay.caption":	"Select element to display its attributes",
    "window.errorLoadingData.caption":	"Error loading data...",
    "window.noData.caption":	"No data",
    "window.error.caption":	"Connection lost",
    "window.error.description":	"There are some connection issues. Check connection and try to refresh the page.",
    "window.connectionProblem.caption":	"Connection problem",
    "window.filters.caption":	"Filters",
    "window.activeFilter.caption":	"Active Filter",
    "window.noMandatory.caption":	"Mandatory filters are not filled!",
    "window.apply.caption":	"Apply",
    "window.type.placeholder":	"Type phrase here",
    "window.noResults.caption":	"There are no results",
    "window.browseTree.caption":	"Browse whole tree",
    "window.back.caption":	"Back",
    "window.inbox.caption":	"Inbox",
    "window.markAsRead.caption":	"Mark all as read",
    "window.inbox.empty":	"Inbox is empty",
    "window.allInbox.caption":	"Show all",
    "window.notification.caption":	"Notification",
    "window.goTo.caption":	"Go to page",
    "window.totalItems.caption":	"Total items",
    "window.selectAll.caption":	"Select all",
    "window.selectAllOnPage.caption":	"Select all on this page",
    "window.itemsSelected.caption":	"items selected",
    "window.noItemSelected.caption":	"No item selected",
    "window.login.caption":	"Login",
    "window.password.caption":	"Password",
    "window.selectRole.caption":	"Select role",
    "window.send.caption":	"Send",
    "window.browserError.description":	"Your browser might be not fully supported. Please try Chrome in case of any errors.",
    "window.uploadPhoto.caption":	"Upload a photo",
    "window.clearPhoto.caption":	"Clear",
    "window.takeFromCamera.caption":	"Take from camera"
}

**Comment by teosarca** [comment]
Hi Kasia,

took a quick look and i would suggest to use the "window" prefix for those which are about window.
For rest of them, i think we shall organize them to some other prefixes.

e.g. (just picked some random examples)
* window.password.caption => login.password.caption
* window.browserError.description => login.browserError.description?
* window.selectAll.caption => view.selectAll.caption
* window.takeFromCamera.caption => widget.takeFromCamera.caption
* window.inbox.tooltip => have no idea, something like "mainScreen.inbox.tooltip"
etc etc

wdyt?

**Comment by Dunkat** [comment]
yes seems be better, feel free to improve/change this key naming

**Comment by Dunkat** [comment]
and one small note: can we change dots with ' _ ' e.g login_password_caption ?

**Comment by Dunkat** [comment]
one question: do you want group this key map?  e.g 
```
window: {
    new: {
        caption: "New"
    },
    delete: {
        caption: "Delete"
    }
},
login: {
    password: {
        caption: "Password"
    },
    login: {
        caption: "Login"
    }
}
```

because if not, for single key it will be better to use '_' instead of dot e.g
login_password_caption

**Comment by teosarca** [comment]
I believe you are suggesting to use "_" instead of dot because you want to map them to javascript variables.

If that's the case, i can change the [/i18n/messages](http://w101.metasfresh.com:8081/swagger-ui.html#!/i-18-n-rest-controller/getMessagesUsingGET) endpoint to return as you suggested in the post above, i.e.
```
{
	window: {
		new: {
			caption: "New"
		},
		delete: {
			caption: "Delete"
		}
	},
	login: {
		password: {
			caption: "Password"
		},
		login: {
			caption: "Login"
		}
	},
	.....
}
```

But nevertheless, pls provide those in the format i've recommended (e.g. window.newButton.caption) because that's how we are storing them internally.

**Comment by Dunkat** [comment]
if endpoint could return something like this would be great, and we can easily extract translations e.g just for the window
```
{
	window: {
		new: {
			caption: "New"
		},
		delete: {
			caption: "Delete"
		}
	},
	login: {
		password: {
			caption: "Password"
		},
		login: {
			caption: "Login"
		}
	},
	.....
}
```

actually translations are implemented, we are waiting for endpoint response, because now is empty

**Comment by Dunkat** [comment]
here is updated key map 
```
{
    "window.dropZone.caption": "Drop files here",
    "window.advancedEdit.caption":	"Advanced Edit",
    "window.Print.caption":	"Print",
    "window.Delete.caption":	"Delete",
    "window.new.caption":	"New",
    "window.settings.caption":	"Settings",
    "window.logOut.caption":	"Log Out",
    "window.zoomInto.caption":	"Zoom into",
    "window.newTab.caption":	"Open in new tab",
    "window.delete.caption":	"Delete",
    "window.batchEntry.caption":	"Batch entry",
    "window.batchEntryClose.caption":	"Close batch entry",
    "window.addNew.caption":	"Add new",
    "window.sideList.attachments.empty":	"There is no attachment",
    "window.sideList.referenced.empty":	"There is no referenced document",
    "window.actions.caption":	"Actions",
    "window.elementToDisplay.caption":	"Select element to display its attributes",
    "window.errorLoadingData.caption":	"Error loading data...",
    "window.noData.caption":	"No data",
    "window.error.caption":	"Connection lost",
    "window.error.description":	"There are some connection issues. Check connection and try to refresh the page.",
    "window.connectionProblem.caption":	"Connection problem",
    "window.filters.caption":	"Filters",
    "window.activeFilter.caption":	"Active Filter",
    "window.noMandatory.caption":	"Mandatory filters are not filled!",
    "window.apply.caption":	"Apply",
    "window.type.placeholder":	"Type phrase here",
    "window.noResults.caption":	"There are no results",
    "window.browseTree.caption":	"Browse whole tree",
    "window.back.caption":	"Back",
    "window.inbox.caption":	"Inbox",
    "window.markAsRead.caption":	"Mark all as read",
    "window.inbox.empty":	"Inbox is empty",
    "window.allInbox.caption":	"Show all",
    "window.notification.caption":	"Notification",

    "view.goTo.caption":	"Go to page",
    "view.totalItems.caption":	"Total items",
    "view.selectAll.caption":	"Select all",
    "view.selectAllOnPage.caption":	"Select all on this page",
    "view.itemsSelected.caption":	"items selected",
    "view.noItemSelected.caption":	"No item selected",

    "login.login.caption":	"Login",
    "login.password.caption":	"Password",
    "login.selectRole.caption":	"Select role",
    "login.send.caption":	"Send",
    "login.browserError.description":	"Your browser might be not fully supported. Please try Chrome in case of any errors.",
    
    "widget.uploadPhoto.caption":	"Upload a photo",
    "widget.clearPhoto.caption":	"Clear",
    "widget.takeFromCamera.caption":	"Take from camera"
}
```

**Comment by teosarca** [comment]
FYI: added a comment to the pull request: https://github.com/metasfresh/metasfresh-webui-frontend/pull/892/files#r122495158

**Comment by teosarca** [comment]
Hi guys,
I've exported all webui messages to migration scripts so they will be replicated on all our systems.
From now on, when you have to add new messages on a given task, pls document what messages you have added.
We need to know that because we need to create migration scripts for those.

**Comment by Dunkat** [comment]
Hi @teosarca  I tried to change "view.selectAllItems.caption": "Select all %(size)s items" but seems changed only in "de_DE"

**Comment by teosarca** [comment]
@Dunkat  yup, that's true. that endpoint is updating only the base language (which is german).
But don't bother, we will translate/fix all of them.
Pls use the webui in german to check if you get the right message.

**Comment by damianprzygodzki** [comment]
Check the influence of translation constants on icon spacing.

**Comment by metas-mk** [comment]
![image](https://user-images.githubusercontent.com/13365687/27382112-c32e70e2-5685-11e7-9da0-3b34692a7739.png)

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
