### ISSUE TITLE
Modal view: show view description if available

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#862]
### Type of issue
Feature request

### Current behavior
Modal view (e.g. PP Order Issue/Receipt or HU editor) is showing the view title but not the description.

### Expected behavior
If the "description" field is provided as part as the create view response then the description shall be displayed beneath the view title.

I cannot provide it on layout because it depends on how the view was created and what data is inside.
Usually it will contain things like "Your are receiving for manufacturing order number 1234567".

![image](https://user-images.githubusercontent.com/1244701/27002536-62272b18-4ded-11e7-909f-e40d1b6c1c44.png)

Required for: https://github.com/metasfresh/metasfresh-webui-api/issues/433

**Comment by teosarca** [comment]
Update: now, API provides the "description" in view result:

![image](https://user-images.githubusercontent.com/1244701/27010170-0ad4cc2a-4ea7-11e7-90a1-4eef3c0da60d.png)

**Comment by cadavre** [comment]
Sound resonable. :) What I would propose is to keep this "title bar" (of modal) height as it is (do not increase). In case of description available – probably move a little bit higher title and try to fit description.

**Comment by teosarca** [comment]
@cadavre  fully agree. We shall not increase title bar's height.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Done/ Closing.
