### ISSUE TITLE
Show password option for Password widget

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#863]
### Type of issue
Feature request

### Current behavior
The password widgets are rendered as password input fields and there is no way to see the password even if you want and even if in some cases this is OK.

### Expected behavior
In case of Password widget types, along with the "widgetType" the API shall also provide the "allowShowPassword" flag.
Alternatively we could introduce another widgetType, e.g. PasswordDisplayable for this case. Not sure if it's better, wdyt?

If that flag is set, the frontend shall show a nice button or icon (with an eye?) to allow the user seeing the password.
How the button/icon shall look like and behave shall be proposed by the UX/designer.

![image](https://user-images.githubusercontent.com/1244701/27002577-086f9cc6-4dee-11e7-9acf-6484abeb5d61.png)

**Comment by cadavre** [comment]
+1 for the button which will display the password when mouse is over, click button is presses and HOLD. On click button release password shall be hidden again. (So no toggle button, but press-and-hold to show.)

**Comment by damianprzygodzki** [comment]
> In case of Password widget types, along with the "widgetType" the API shall also provide the "allowShowPassword" flag.

Definitely we should attach flag in widget layout.

**Comment by teosarca** [comment]
NOTE: atm the widgetType is provided in data and not in layout.
I hope it's OK if we will provide the "allowShowPassword" in layout.

**Comment by damianprzygodzki** [comment]
> NOTE: atm the widgetType is provided in data and not in layout.
> I hope it's OK if we will provide the "allowShowPassword" in layout.

If API won't be changing it during widget lifecycle, than ok.

**Comment by teosarca** [comment]
nop, it won't change it.

**Comment by teosarca** [comment]
Update: quick tested this on localhost but it seems the "show password" button is not displayed

![image](https://user-images.githubusercontent.com/1244701/27032533-f1189c80-4f7d-11e7-9ce0-3e307a8a2174.png)

**Comment by metas-mk** [comment]
Tested. Works as required/ needed for this iteration. Closing/ Done
