### ISSUE TITLE
Clickable URL in Fields

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#865]
### Type of issue
Feature request
### Current behavior
Currently, the URL Fields in metasfresh are not represented as a link. If the user wants to visit the website from the URL she/he must copy the URL manually to visit it.
### Expected behavior
Allow the User to hover over theses Fields/ URL and show that it's a clickable link. When the user presses on it a new browser tab is opened with the URL.

![image](https://user-images.githubusercontent.com/13365687/27020669-855301be-4f43-11e7-944e-f95c83529b41.png)

**Comment by teosarca** [comment]
I think we shall introduce the URL widget type. wdyt?

**Comment by cadavre** [comment]
I suggest to add similar button on the right as in #863 which clicked will follow the link. We cannot click on input because we need to edit it somehow. ;)

**Comment by damianprzygodzki** [comment]
URL widget typ +1. But might be better to call it `Hyperlink`, `Link`, `Href`, or something like that.

**Comment by teosarca** [comment]
Update: quick tested on localhost but it seems the widget is not rendered.
Do you know why?

(btw, the feature will be available on w101 on next rollout)

![image](https://user-images.githubusercontent.com/1244701/27032093-d871304a-4f7b-11e7-953e-064960105512.png)


![image](https://user-images.githubusercontent.com/1244701/27032100-dded2498-4f7b-11e7-8229-345e553fca27.png)

**Comment by damianprzygodzki** [comment]
Did you provided value for the link?

**Comment by teosarca** [comment]
Hmm, it shall not be readonly because if it's readonly, then the user cannot set it.

**Comment by teosarca** [comment]
it shall be just like a regular text field, but the URL is displayed as an URL and it's clickable.

**Comment by damianprzygodzki** [comment]
Okay, so we are proceeding with that:

> I suggest to add similar button on the right as in #863 which clicked will follow the link. We cannot click on input because we need to edit it somehow. ;)

**Comment by teosarca** [comment]
yes please :)

**Comment by metas-mk** [comment]
@damianprzygodzki 
Tested. Added URL in an existing Field. 
a) Pressed on Button (eye) and expected that the URL is opened in new Browser. Did not happen. NOK
b) Instead of that the Field just switched from editable Text Field to a Link. After editing, the user must press the Button again to go in "Link-Mode". NOK

Please implement as discussed, having a field which allows editing the URL and a small button to open that link.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Done/ Closing.
