### ISSUE TITLE
Breadcrumb: separate the document summary and last breadcrumb node with a slash

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#872]
### Type of issue
Feature request

### Expected behavior
![image](https://user-images.githubusercontent.com/1244701/27031678-dfea261c-4f79-11e7-9c76-d4386c9b99d5.png)

NOTE: at the time when i am writing this, on w101 we still have the slash there because the backend introduced in document summary.
But on task https://github.com/metasfresh/metasfresh-webui-api/issues/451 we took it out because that's part of the "layout" and not part of the data.... and on that task we needed the document summary too.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Done/ Closing.
