### ISSUE TITLE
Research about resolution for heavy 5000 rows gridviews (window/540345)

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#875]
### Type of issue
Feature request
### Current behavior
The gridview with >5000 rows is slow.
### Expected behavior
Optimize it / refactor it.
### Steps to reproduce
/window/540345

**Comment by cadavre** [comment]
Cannot reproduce anymore. Probably fixed with some other issue. If it is going to happen again – please reopen or create new issue with more info about issue itself.
