### ISSUE TITLE
Clean and unify the two-column structure in MenuOverlay.

### ISSUE THREAD

**Issue by damianprzygodzki** [metasfresh/metasfresh-webui-frontend#876]
### Type of issue
Bug
### Current behavior
Different interpreted `column` property.
### Expected behavior
To have one column field firstly.
### Steps to reproduce
Just open the MenuOverlay (Home button)

**Comment by teosarca** [comment]
This task is a follow-of this comment: https://github.com/metasfresh/metasfresh-webui-frontend/issues/803#issuecomment-307827594

**Comment by damianprzygodzki** [comment]
I am reverting that change.

For the moment it is unreachable to provide column layout not autobalanced. It is not fully supported by browsers.

The current implementation is 'polyfill' for that - but still not so ux efficient - the navigation with arrows flow in wrong direction and we can't do anything with that.

**Comment by metas-mk** [comment]
@damian
thx for the info
can u then provide a 1 column solution for now instead
like it looks like in firefox currently
this would look tidy and won't let the user feel that it's "broken"

![image](https://user-images.githubusercontent.com/13365687/27130190-94a1a260-5105-11e7-9b16-4c08eaae21a7.png)

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
