### ISSUE TITLE
n instead of none in dropdowns

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#877]
### Type of issue
Bug
### Current behavior
n instead of non in dropdowns. e.g. see https://w101.metasfresh.com:8443/window/144/2001590
### Expected behavior
should see none, not only the first letter
### Steps to reproduce
go to https://w101.metasfresh.com:8443/window/144/2001590

![nnn](https://user-images.githubusercontent.com/16001666/27077800-00296d6e-503a-11e7-86c9-db271ac0f90c.png)

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing,
