### ISSUE TITLE
Error firework when logout

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#878]
### Type of issue
Bug
### Current behavior
When Logging out you get an error firework and the user does not see the login screen.
### Expected behavior
Logout shall not have Errors and shall lead to first Login Window.
### Steps to reproduce
Login. Open My Profile Avatar Settings. Logout.

![image](https://user-images.githubusercontent.com/13365687/27081068-0d6661da-503f-11e7-9613-364f1620bf69.png)

**Comment by teosarca** [comment]
Found another one and i think it's related,
* i was logged in sometime
* in meantime i also restarted the server (rollout) and might be that the session also expired
* when i am calling https://w101.metasfresh.com:8443/window/143 the Login page is not prompted.

![image](https://user-images.githubusercontent.com/1244701/27122927-e199326a-50f4-11e7-9656-f8c2c193c289.png)

**Comment by teosarca** [comment]
NOTE: i didn't test it after your last commit. Cannot confirm that the issue above is also fixed?

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
