### ISSUE TITLE
Avatar Picture not deleted from Header when cleared in Profile Settings

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#879]
### Type of issue
Bug
### Current behavior
When User Adds a Profile Picture in Avatar Settings the Picture is also updated in Application Header. When the user clears the picture in Settings, the Application Header is not updated. The picture is still visible there.
### Expected behavior
In the case of deleting/ clearing the picture in Settings, it shall be deleted/ cleared in Application header too.
![image](https://user-images.githubusercontent.com/13365687/27081209-9be48a4a-503f-11e7-8018-2b0307587601.png)

**Comment by damianprzygodzki** [comment]
It is backend issue. Backend should send WS event with empty avatarId.

**Comment by teosarca** [comment]
10x, will check it.

**Comment by metas-lc** [comment]
IT
upload photo => app pic is updted OK
clear photo => app pic is cleared OK

if i upload the pic again nothing happens NOK (but not sure if it's related with this task)
if i refresh the page and upload again then it works

**Comment by damianprzygodzki** [comment]
> if i upload the pic again nothing happens NOK (but not sure if it's related with this task)

Issue of native file input cache. Worked-around.

**Comment by damianprzygodzki** [comment]
@metas-lc do we have some other issues or just race condition with flags?

**Comment by metas-lc** [comment]
no other issues. Just to remember it needs rollout. Also , just checked and works fine. So i'll close it
