### ISSUE TITLE
Change Icon for URL Link

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#880]
### Type of issue
Feature request
### Current behavior
Currently, the Icon for the URL Link is the same as used for "make password readable" (eye).
### Expected behavior
The Icon for the URL Widget shall be a link Symbol (like a chain link). Can be tested in window/123/

![image](https://user-images.githubusercontent.com/13365687/27086198-bb8b0a4c-5051-11e7-9417-f9b754a1573b.png)

**Comment by damianprzygodzki** [comment]
moved to graphic designer

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
