### ISSUE TITLE
hu editor doesn't update

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#883]
### Type of issue
Bug
### Current behavior
modal window doesn't update

### Expected behavior
HUs should update accordingly to what action you used

### Steps to reproduce
CASE 1
1. go to material receipt candidates (540196 ) and select a product line
2. receive HUs and create material receipt
=> the HUs should become readonly and status Active BUT they remain Planning and editable NOK
=> button to create material receipt it's still there NOK
=> inout was created fine and the TU is active if you check HU window - OK (so i guess it's just a refresh issue)

CASE 2
1. go to manufacturing order (53009) and select a line, then press on issue /receipt
2.  select the co product and issue 1 TU
=> noticed that the TU is still in issue (right side) and there is nothing new on the left side, on the co-product NOK
=> notice that if you close the modal and open it again the HU is updated, on the product side (left)..so again some refresh issue

OTHER
It also happens if you do stuff like vendor return or dispose.. anything in hu editor

**Window:** 540196 OR 53009

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

I repeated the cases described in the issue and now the HUs are always correctly updated in the modal window.
