### ISSUE TITLE
Blocked cells

### ISSUE THREAD

**Issue by Dunkat** [metasfresh/metasfresh-webui-frontend#891]
### Type of issue
Bug
### Current behavior
When you tring edit blocked cell on edge browser, then will blocked all cells.

### Expected behavior
no block all cells.

### Steps to reproduce
go to included tabs and try edit readonly cell

This issue is a part of #838

**Comment by cadavre** [comment]
@tomaszfryc could you provide more info about environment? @Dunkat stated that cannot reproduce.

**Comment by teosarca** [comment]
rolled to w101

**Comment by metas-rc** [comment]
Results of IT

Tested on webui, on Microsoft Edge browser.

Trying to edit blocked cells does not lead to blocking other cells. => OK
