### ISSUE TITLE
Modal view: when user presses Done the server shall be notified

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#895]
### Type of issue
Feature request

### Current behavior / Steps to reproduce
Test case:
* open the receipt candidates view: https://w101.metasfresh.com:8443/window/540196
* select a row and call one of the receive HUs action
* a modal popup is opened showing the HUs view (aka HU editor)
* now click Done
=> modal popup is closed => OK

### Expected behavior
Before closing the modal popup, frontend shall call [DELETE /rest/api/documentView/{windowId}/{viewId}](http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/deleteViewUsingDELETE).

**Comment by metas-rc** [comment]
Results of IT

Tested on Webui

* Open material receipt candidates, select  an entry
* Go to actin menu and select Receive HUs ( or something similar)
* after the modal window is opened, press done
* => OK: The DELETE method is called
Note: This is visible in Inspections, Network, Headers (Request Method:DELETE)
