### ISSUE TITLE
KPIs: show Loading indicator instead of No data

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#896]
### Type of issue
Feature request

### Current behavior
When the dashboard (main page) is displayed, until the KPIs are loaded, the KPIs are showing "No data".

![image](https://user-images.githubusercontent.com/1244701/27177631-a6cac492-51cf-11e7-972f-56b2a95c263f.png)

### Expected behavior
In that case the KPIs shall display a loading indicator.

When fetching KPI's data (after the first load) the "Loading" indicator shall not be shown.
The current graph shall be kept until new data is available.

**Comment by teosarca** [comment]
NOTE: this is a low prio task

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
