### ISSUE TITLE
Clicking the search icon should open partner list

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#897]
### Type of issue
Feature request

### Current behavior
if you click the icon nothing happens

![image](https://user-images.githubusercontent.com/16079655/27179108-76552480-51cd-11e7-8898-658eda777f77.png)

### Expected behavior
should open the partner liste as if I pressed SPACE Key

![image](https://user-images.githubusercontent.com/16079655/27179128-8969f44c-51cd-11e7-8b68-0a796b4bbb02.png)

### Steps to reproduce
1. open https://w101.metasfresh.com:8443/window/143/1005608
1. click on search icon of field "Business Partner"

**Comment by teosarca** [comment]
In that case, i think you shall call the typeahead endpoint with empty query, e.g.
http://w101.metasfresh.com:8081/rest/api/window/143/1005620/field/C_BPartner_ID/typeahead?query=

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* Go to purchase order, click on the icon for finding partners
* => OK: List of partners displayed
* In the same field, use Space
* => Ok: The lame list of partners displayed

* GO to orderline, click on the icon for finding products
* => OK: List or prodducts displayed
* Now use the Space in the products field
* => OK: Same list of products displayed

Regression: Type ahead still works correctly.
