### ISSUE TITLE
Lookup Field Dropdowns automatism

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#898]
### Type of issue
Feature request
### Current behavior
Currently, the drop down lists in lookup field appear every time. Also for list entries with 0 or 1 selection item.
### Expected behavior
In case the dropdown entries only have 0 or 1 entry, select automatically, but only if it is not the initial search field.
### Steps to reproduce
Open Sales Order window. Take e2TestPartner as Testcase. This partner has a 1:1:1: configuration. The Workflow in that case then should be:
a) write "e2", the dropdown appears and the only entry is selected. The user confirms w/ [enter]
b) the second field for location is automatically filled and no initial dropdown appears, because only 1 entry available
c) the third field for user contact is automatically filled and no initial dropdown appears, because only 1 entry

![image](https://user-images.githubusercontent.com/13365687/27213620-5e621a0e-5268-11e7-8aca-3057623b4c44.png)

**Comment by Dunkat** [comment]
As we discussed on skype some time ago, dropdown should be always displaying. Should I revert what was before?

**Comment by metas-mk** [comment]
@Dunkat no. don't revert, just adjust/ extend to what's described. pls ping me for a quick talk. I can explain what's needed in a few mins w/ the example above and show you where the difference is to the other default cases.

**Comment by Dunkat** [comment]
I think I know what you mean. When is only one item in dropdown will be automatic selected. It's already fixed, please check here: http://dev-898.metasfresh.jzapp.io/window/143/1005643

**Comment by metas-mk** [comment]
@Dunkat
Checked. Thx. Yes, that's what I meant, thx. :-)
One minor wish (also ok if we put this wish to a follow-up task): Is is possible to avoid seeing the superfast flickering dropdowns in the automatic workflow? Example: After entering the "e2" testcase the location and contact are set automatically, because of only 1 entry. BUT even though it's done fast, the user can see the dropdown for location and contact flickering.

**Comment by metas-mk** [comment]
@Dunkat 
Seems as if the case entry = 0 is missing. Please check in Batch entry for the test case "Futterkarotten". The Packing instruction is not automatically selected w/ "empty".

![image](https://user-images.githubusercontent.com/13365687/27286708-6957fec4-5501-11e7-9ef2-a3b9ba22a71a.png)

**Comment by metas-rc** [comment]
Resulta of IT

Tested on webui

1. The dropdown does not appear any more if there is only one possible selection available: OK
2. 
> " One minor wish (also ok if we put this wish to a follow-up task): Is is possible to avoid seeing the superfast flickering dropdowns in the automatic workflow? Example: After entering the "e2" testcase the location and contact are set automatically, because of only 1 entry. BUT even though it's done fast, the user can see the dropdown for location and contact flickering." 
*  This was still not fixed. Was it decided what's to be done to not have the flickering any more? Please, link the followup or fix.

3. 
>Seems as if the case entry = 0 is missing. Please check in Batch entry for the test case "Futterkarotten". The Packing instruction is not automatically selected w/ "empty".
* This is still happening. Please, fix.

**Comment by metas-mk** [comment]
Extracted the remaining issues into the new issue (see reference above). Moving this one to done/ closing.
