### ISSUE TITLE
Barcode Filter does not let you escape

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#899]
### Type of issue
Bug
### Current behavior
once filtered by barcode you can not turn off the barcode filter anymore

### Expected behavior
I can select another filter even though I have filtered with barcode before

### Steps to reproduce
1. open https://w101.metasfresh.com:8443/window/540189
1. select filter for barcode
1. put any number and press enter
1. click on filter to filter not by barcode
1. NOK: barcode opens again

workaround:
open window again

**Comment by Dunkat** [comment]
to remove filter you need to clear number and press enter. When barcode field is empty, filter will be remove.

**Comment by damianprzygodzki** [comment]
> to remove filter you need to clear number and press enter. When barcode field is empty, filter will be remove.

Yes, that was discussed on skype.

**Comment by teosarca** [comment]
wondering if we shall have a "clear" button/link something which would make it obvious?
wdyt?

**Comment by metas-mk** [comment]
Checked. Current Solution is fine for now. The user just has to press backspace to clear/ initialize.
Closing this issue.
