### ISSUE TITLE
Advanced edit

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#9]
Advanced Edit Functionality
Button as seen in the Layouts (with additional Popup for detail fields)

ToDo
a) talk about layout/ design/ concept
b) implement

**Comment by cadavre** [comment]
As discussed on Skype:

`/api/layout?id=143` – regular call
`/api/layout?id=143&advanced=true` – for advanced editing

This rule is also followed in `/api/data` and `/api/commit`.

**Comment by cadavre** [comment]
Implemented.
