### ISSUE TITLE
Navigation Menu vs. Sitemap entries w/ linebreak

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#904]
### Type of issue
Bug
### Current behavior
Currently, the Sitemap has longer entries that stretch over 2 lines, although there is enough space to show on 1 line.
### Expected behavior
Show the entries on 1 line when enough space (like in navigation menu)
### Steps to reproduce
Open the navigation menu und sitemap at the same time and look for longer 2-3 word entries and compare.

**Comment by metas-mk** [comment]
@Dunkat 
Tested. Don't see any improvement in Sitemap yet. I'll add a screenshot done in Chrome, what it looks like. Still a lot of 2-3 row linebreaks and added dots behind some of the menu entries:

![image](https://user-images.githubusercontent.com/13365687/27383709-77520b96-568c-11e7-8ea1-f044466bfd23.png)

**Comment by Dunkat** [comment]
looks like something not merge properly

**Comment by metas-mk** [comment]
Tested. Works as required. Closing/ Done.
