### ISSUE TITLE
Margin missing in Advanced Edit when Scrollbar visible

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#907]
### Type of issue
Feature request
### Current behavior
Currently, in modal overlays w/ scrollbar visible, the bottom margin is too small for primary layouts.
### Expected behavior
Add a small bottom margin to modal overlay windows so the primary layouts don't look squeezed to the bottom.

![image](https://user-images.githubusercontent.com/13365687/27251626-2d0fd106-534b-11e7-9b46-2ce4d5dee7be.png)

**Comment by metas-rc** [comment]
Results of IT

Tested on webui

* Go to My Profile, Action Menu button, click on Advanced Edit
* Scroll down the advanced edit window
* => OK: The bottom margin looks good, there is no feeling abrupt  end.
