### ISSUE TITLE
URL widget: disable the link button if the URL is not valid

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#908]
### Current behavior
The link button is always active.

### Expected behavior
THe link button shall be disabled if:
* field is null/empty (trim whitespaces)
* nice to have: field is not a valid url according to some regex

### Steps to reproduce
Just open a window where you have an URL which is empty.
e.g. search in bpartner window, https://w101.metasfresh.com:8443/window/123

![image](https://user-images.githubusercontent.com/1244701/27258976-f901aaa8-5410-11e7-9a0e-cc1f05c0d006.png)

**Comment by damianprzygodzki** [comment]
We have valid object in widgets, due to assumption that frontend is stateless and API is taking care about validation and error generating (error message and input style (if not valid button is disabled)).

**Comment by teosarca** [comment]
Ok, but in case the field is empty/null the frontend shall disable the button anyways because from backend point of view the view is valid.
wdyt?

**Comment by damianprzygodzki** [comment]
Yes, agree. To add.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Empty = Disable. Filled w/o protocol http:// then opened with current URL and additional path.
Done/ Closing.
