### ISSUE TITLE
Login page shall allow browser to save password

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#91]
The login user and password fields shall  be developed in a way that browsers like chrome shall ask if user wants to save the password.

**Comment by metas-mk** [comment]
good point. +1

**Comment by damianprzygodzki** [comment]
I tested it and it actually does. Check if you maybe select the metasfresh login as "Never save" / "Never ask" login form (the key icon on address bar)

![screen shot 2016-11-14 at 09 37 32](https://cloud.githubusercontent.com/assets/5701744/20258064/fac0231e-aa4d-11e6-81d0-863eae7a04ec.png)
