### ISSUE TITLE
Keyboard Shortcuts for Done, Apply, Start and Cancel

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#918]
### Type of issue
Feature request
### Current behavior
Currently, there are no general keyboard shortcuts for the actions "Done", "Start" and "Cancel" in modal overlays and process windows. Same for Apply in Filters.
### Expected behavior
Allow the User to confirm the following actions with general keyboard shortcuts.

Done: [ctrl] + [cr/ enter]
Apply: [ctrl] + [cr/ enter]
Start: [ctrl] + [cr/ enter]
Cancel: [esc]

Please also add a tooltip (when hover) for them which shows the shortcuts similar to the tooltips when hovering a field label.

Examples:
![image](https://user-images.githubusercontent.com/13365687/27371771-5dcc59a8-5662-11e7-875c-ee12cb4aba67.png)

![image](https://user-images.githubusercontent.com/13365687/27371920-ed4dde76-5662-11e7-935b-9ca41776ee88.png)

**Comment by metas-lc** [comment]
IT
go to receipt candidates, select a line, receive cu with qty. Directly press ctrl+s to start => save as it's opening (that is because you are in the menge cu field) nok

**Comment by Dunkat** [comment]
it's fixed. Now you can fire shortcuts even if you are in the menge cu field

**Comment by metas-lc** [comment]
IT
talked with @metas-mk and the shortcuts should be like in description.
Done: ctrl + enter
Apply: ctrl + enter
Start: ctrl + enter
Cancel: esc

**Comment by Dunkat** [comment]
ahh yes, shortcuts are already renamed

**Comment by metas-lc** [comment]
IT
Done: ctrl + enter
Start: ctrl + enter
Cancel: esc 
OK, works fine

i found Apply only in filters. There we don't have ctrl + enter or hover (and it's also not modal). Will probably create another task if it's needed. Need to check
