### ISSUE TITLE
Improvement of Breadcrumb Navigation Dropdown entries

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#920]
### Type of issue
Feature request
### Current behavior
Currently, the Breadcrumb Navigation in Frontend shows all nodes and leafs underneath the breadcrumb node. It also shows the Breadcrumb node itself as a header.
### Expected behavior
The Navigation shall only show the Leafs of the selected Breadcrumb node (no header repeating, no nodes)

Proposal: API shall provide Endpoint for this Breadcrumb selection. Here is the API Issue: https://github.com/metasfresh/metasfresh-webui-api/issues/465

![image](https://user-images.githubusercontent.com/13365687/27383200-2a2e584e-568a-11e7-8085-43159583c01a.png)

![image](https://user-images.githubusercontent.com/13365687/27383201-2f721106-568a-11e7-91f2-c54a55bb122d.png)

**Comment by teosarca** [comment]
API available: http://w101.metasfresh.com:8081/swagger-ui.html#!/menu-rest-controller/getNodeBreadcrumbMenuUsingGET

**Comment by metas-mk** [comment]
Tested. Works as required. Closing/ Done.
