### ISSUE TITLE
Browser issue: Window Bookmark Header

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#921]
### Type of issue
Bug
### Current behavior
Currently, in Browser Chrome, the Window Bookmark Header has a linebreak when too long. Hovering over the window Header it jumps between linebreak and not. The Same behavior is seen in Sitemap sometimes.
### Expected behavior
Have the Header in 1 Line w/o linebreak and don't "jump"
### Steps to reproduce
Open a Window with a long Name and open the Action Menu, here "KPI Feld Übersetzungen".

![image](https://user-images.githubusercontent.com/13365687/27384186-41507e22-568e-11e7-8e5d-44697339743b.png)

**Comment by metas-mk** [comment]
Tested. Is not as required (please check the attached image in requirements w/o linebreak, see the star and not dots). NOK

![image](https://user-images.githubusercontent.com/13365687/27643994-d6a3bbf8-5c22-11e7-8e08-29bf871cae5a.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
