### ISSUE TITLE
Packageables window: up/down arrows are working weird

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#923]
### Steps to reproduce
* open packageables window: https://w101.metasfresh.com:8443/window/540345
* click on first row; you might also consider expanding some of them
* move down and up with the arrows

=> NOK 1: working weird. selection is lost when switching from one root row to another one

=> NOK 2: moving is quite slow even though the API endpoint calls take ~50ms.

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest webui

* The problem with arrows in Packageables seems to be fixed but I found 2 other related issues for which I created followups: 	
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/968
* https://github.com/metasfresh/metasfresh-webui-frontend/issues/971
