### ISSUE TITLE
Remaining untranslated static elements in WebUI

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#924]
### Type of issue
Feature request
### Current behavior
After the first round of making the static elements translatable in WebUI, there are a few remaining elements which were not covered yet.
### Expected behavior
Make these also translatable. Some already have their ad_messages.

Sitemap "Type phrase here":
![image](https://user-images.githubusercontent.com/13365687/27393547-e6e9f1e0-56a9-11e7-9f32-9c367b46e1de.png)
![image](https://user-images.githubusercontent.com/13365687/27393443-a0321886-56a9-11e7-88d0-9377e8157c46.png)

Browse whole Tree:
![image](https://user-images.githubusercontent.com/13365687/27393417-8c0ca588-56a9-11e7-9118-a3286a0ced1d.png)

Expand:
![image](https://user-images.githubusercontent.com/13365687/27392590-57c6445c-56a7-11e7-96d2-4830dd202068.png)

Filters:
![image](https://user-images.githubusercontent.com/13365687/27391055-2dc38894-56a3-11e7-8064-f8516f5ddba0.png)

x Items selected:
![image](https://user-images.githubusercontent.com/13365687/27391421-39bbf414-56a4-11e7-8ddd-31b61c512f62.png)

Filter by:
![image](https://user-images.githubusercontent.com/13365687/27391509-6cf8f61a-56a4-11e7-8aaa-458e71203ff1.png)

Actions/ Selection attributes/ Select element to ...
![image](https://user-images.githubusercontent.com/13365687/27391587-9aecd58c-56a4-11e7-983f-dc2c2e3128fe.png)

Actions here too:
![image](https://user-images.githubusercontent.com/13365687/27392443-fc213472-56a6-11e7-96d9-ba7f0f8457bb.png)

Belongs to this main Issue: https://github.com/metasfresh/metasfresh-webui-frontend/issues/861

**Comment by damianprzygodzki** [comment]
window.actions.emptyText: "There is no actions",
window.quickActions.caption: "Actions",
window.selectionAttributes.caption: "Selection attributes",
window.selectionAttributes.callToAction: "Select element to display its attributes.",
window.filters.caption2: 'Filter by',
window.table.expand: 'Expand',
window.table.collapse: 'Collapse',
window.sitemap.callToAction: 'Browse whole tree'

**Comment by teosarca** [comment]
> window.filters.caption2: 'Filter by',

Here i would make it 'Filter by %(name)s' because sentence ordering in different languages.
And in general, we shall apply this rule everywhere where you see that you have to concatenate strings.

**Comment by damianprzygodzki** [comment]
> Here i would make it 'Filter by %(name)s' because sentence ordering in different languages.
> And in general, we shall apply this rule everywhere where you see that you have to concatenate strings.

I wouldn't because it isn't full sentence, just enumeration, and i would like avoid including punctuation in translations. We have buttons with:

```
Filter: 1, 2, 3
```
Or
```
Filter by: 1, 2, 3
```

**Comment by metas-mk** [comment]
Tested. Opened Follow Up Issue for remaining Bug/ missing Translation. Closing this one. Done.
