### ISSUE TITLE
Select all does not count the items anymore

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#925]
### Type of issue
Bug
### Current behavior
When in grid view, press "Select all items". After selecting all the counter shows "No Items selected".
### Expected behavior
The Counter shall be set properly.

![image](https://user-images.githubusercontent.com/13365687/27391291-dce7a0da-56a3-11e7-8cd9-37432473a456.png)

**Comment by teosarca** [comment]
More, after clicking on "Select all on this page" the link shall be changed to "Select XXXXX items" (i.e. select all on all pages).

NOTE: original feature was developed on https://github.com/metasfresh/metasfresh-webui-frontend/issues/752

**Comment by Dunkat** [comment]
it's because translations not updated properly. See my comment https://github.com/metasfresh/metasfresh-webui-frontend/issues/861#issuecomment-309672576

should be "view.selectAllItems.caption": "Select all %(size)s items" not "Select all %(size) items"

**Comment by teosarca** [comment]
Did a quick check on w101 and found 3 messages which are somehow about "view" and "select".
i.e.
"view.selectAll.caption"
"view.selectAllItems.caption"
"view.selectAllOnPage.caption"

![image](https://user-images.githubusercontent.com/1244701/27537094-eeebdbae-5a7a-11e7-87d3-9c8867cbfedc.png)

NOTE: ignore the "webui." prefix. 

Can you please let me know where they are used?
THanks

**Comment by cadavre** [comment]
@teosarca have you read @Dunkat comment above yours? You asked about already answered thing. Up to you – wrong translation loaded into API. :)

**Comment by teosarca** [comment]
Also pls remark that it's not a translation issue.

There are 3 different messages with 3 different translations.
But in frontend, when i am clicking on "Select all on this page" the link is not changed to "select all XXXX items".

**Comment by teosarca** [comment]
You are right :)

We fixed the message and now it works.

Btw, can you point us where we can read about the message parameter syntax. Where can we put there, what the trailing "s" means etc?

**Comment by cadavre** [comment]
Closing issue due to no other work to be done.

@Dunkat could you provide link to params syntax?

**Comment by metas-mk** [comment]
The bug described above will be solved in issue mentioned above. Closing this issue.

**Comment by Dunkat** [comment]
it's library which we using https://github.com/martinandert/react-translate-component you will find there example of params translations

**Comment by cadavre** [comment]
Looks like `%(param)s` is the only syntax available there. It's simply named `%s`. Wondering if another `%` types are working too... One way or another in JS you can cast anything to string afaik.
