### ISSUE TITLE
Notifications are not refreshed when the language is changed

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#931]
### Type of issue
Bug

### Current behavior / Steps to reproduce
* login, have some notifications
* go to user profile and change the language
* click on notifications icon => NOK the notifications are displayed in previous language
* refresh the page => OK: notifications are displayed in the right language

NOTE: also checked the Network Inspector and the frontend did not call the notifications endpoint to fetch them again.

![image](https://user-images.githubusercontent.com/1244701/27435167-fbd06174-5763-11e7-9355-8f3f02d2bdf4.png)

### Expected behavior
When clicking on notifications icon I ALWAYS shall get the notifications in current language.

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Done/ Closing.
