### ISSUE TITLE
question: can we resize the target indicator's text to make it fit?

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#932]
Take a look at:
![image](https://user-images.githubusercontent.com/1244701/27440055-3ce76f28-5772-11e7-9960-b79301cea440.png)

In that case it would be nice to auto-magically make the text smaller (but still as big as possible) in order to fix it's box.

wdyt?

**Comment by damianprzygodzki** [comment]
No. There is no option to set text size dependent on parent width.

What's more, imagine, when someone put there 10 TA widgets. The biggest string will be unreadable because of font-size around 3px. 

Readable text = constant styling.

**Comment by teosarca** [comment]
Ok, thanks. Closing it for now.
