### ISSUE TITLE
Disable quick actions button while running the action (v2)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#933]
### Type of issue
Bug

### Current behavior
When pressing a quick action the process is started right away.
But the quick action button is green even though the process did not finish.

![image](https://user-images.githubusercontent.com/1244701/27447493-ce2bf000-5789-11e7-96fc-0eb9c39b7e7f.png)

### Expected behavior
The quick action button shall always be disabled while the process is running.
After the process was executed, successfully or with ANY error/exception the quick action button shall be unlocked and it's state shall be reevaluated (i.e. ask API about quick actions).

This is just a shade of this cinquecento https://github.com/metasfresh/metasfresh-webui-frontend/issues/500 :)

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest webui

The quick actions are disabled while the process is running: OK
State is reevaluated after the process is finished and the right quickaction, disabled/enabled is displayed: OK

I found a detail problem for which I created a followup:  https://github.com/metasfresh/metasfresh-webui-frontend/issues/973

**Comment by teosarca** [comment]
reopened because @metas-ts  reverted it

**Comment by wiadev** [comment]
My observations not directly related to changes made for this story:

1. Too much (really heavily overloaded) re-renders of components on input properties change. Probably need to review input parameter bindings and/or split into few components to optimize re-renders. There are lot of components with some 10-20 input parameters which are changed often and thus causing frequent component redraws. The only reason why it still works considerably well - thanks to React's optimized DOM manipulation.

2. Progress indication had animation of 1s length on success, regardless of actual time spent on request. Thus you seen progress animation even while actually nothing happened at this time. I've reduced this completion animation to 0.1 second. Please confirm if this is acceptable.

3. Progress tracking seems to be a bit overloaded. It has many of unclear parameters, like refresh, processState, indicator. They're changed asynchronously, causing too much component redraws (see item # 1 above)

**Comment by metas-ts** [comment]
rollout out on our IT server for checking prior to integration

**Comment by metas-ts** [comment]
cherry-picked to the `release` branch

**Comment by wiadev** [comment]
@metas-ts is this still open?

**Comment by metas-ts** [comment]
Hi @wiadev,
yes, still open,
but your and my part is probably done :-)
Our QA will also take a look at it and then probably close it

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
