### ISSUE TITLE
Image widget: show uploading idicator

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#935]
### Type of issue
Feature request

### Current behavior
When uploading a picture there is no indicator. User don't know if it's uploaded or she/he shall wait.

### Expected behavior
Show upload indicator
![image](https://user-images.githubusercontent.com/1244701/27452521-79ba4bd6-579b-11e7-95f8-373a7256a362.png)

**Comment by metas-mk** [comment]
Tested. Works nicely as required. Done/ Closing.
