### ISSUE TITLE
Lookup Fields improvements

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#938]
### Type of issue
Feature request
### Current behavior
These 2 remaining topics are taken out from this issue
https://github.com/metasfresh/metasfresh-webui-frontend/issues/898
* One minor wish (also ok if we put this wish to a follow-up task): Is is possible to avoid seeing the superfast flickering dropdowns in the automatic workflow? Example: After entering the "e2" testcase the location and contact are set automatically, because of only 1 entry. BUT even though it's done fast, the user can see the dropdown for location and contact flickering.
* Seems as if the case entry = 0 is missing. Please check in Batch entry for the test case "Futterkarotten". The Packing instruction is not automatically selected w/ "empty"" .
### Expected behavior
Please fix/ provide.

**Comment by metas-mk** [comment]
Tested. Open Sales Order window/143

a) Testcase Business Partner Lookup "e2". Typed "e2" [enter]. Both following fields are filled because of only 1 selection available. OK

b) Testcase Business Partner Lookup "krake". Typed "krake" [enter]. Location Field is filled initially although it has more than 1 selection entry. NOK - shall be empty and user shall select in dropdown list.
![image](https://user-images.githubusercontent.com/13365687/27590112-e204c0c6-5b4d-11e7-9e98-1b4014c672b0.png)

c) Testcase Batch Entry for Sales Order w/ Business Partner "krake". Product Field "Convenience" [enter]. Package Config is automatically selected because of only 1 entry. [tab] jumps to qty field. OK

d) Testcase Batch Entry for Sales Order w/ Business Partner "krake". Product Field "Futterkarotten" [enter]. Package Config is empty because there is 0 entry available. [tab] does not jump to qty field. NOK

**Comment by Dunkat** [comment]
b)  Field is filled initially because of default value. It's working like always was. Should we not respected default value?

![location](https://user-images.githubusercontent.com/21196151/27621882-11ec93f0-5bd4-11e7-99d5-d46f7c652327.jpg)

**Comment by metas-mk** [comment]
@Dunkat thanks. Yes, the default entry **must be respected**.

> b) Field is filled initially because of default value. It's working like always was. Should we not respected default value?


My expectation was that it repects the default value, therfor automatically selects the entry in the dropdown list and the user must then [enter] to select the default entry to be put in lookup field, and not before.
Let's leave this like it is now and see what the feedback is.

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
