### ISSUE TITLE
grid view: show one text for top level rows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#941]
### Type of issue
Feature request

### Expected behavior
In this feature is communicated in layout (as a flag) then the frontend shall render the top level rows are one line (i.e. joining together all columns).
This feature shall not affect existing functionalities and it shall be 'activated' only when we provide the information in layout/data.

e.g.
![image](https://user-images.githubusercontent.com/1244701/27530608-180841d0-5a62-11e7-814c-8b65b17d8eab.png)

If you have a suggestion about how to change the protocol, it would be very nice.
If not, i will come with a proposal very soon.

**Comment by cadavre** [comment]
In attached screenshot you pixelized row beneath "One line text here". What shall happen with this pixelized data? Be overwritten by "One line text here"?

**Comment by teosarca** [comment]
yup, exactly.... i pixelized just to vanish it from there :)

**Comment by cadavre** [comment]
For the beginning:

1. Add colspan.
2. Keep font same as for row data.

**Comment by cadavre** [comment]
@damianprzygodzki please provide API response example snippet to implement on backend to work with frontend.

**Comment by damianprzygodzki** [comment]
GET /rest/api/documentView/{windowId}/{viewId}
```
{
  ...,
  results: [
    {
      ...,
      colspan: true,
      caption: ""
    }
  ]
}
```

**Comment by teosarca** [comment]
I've started to implement it on backend side. The protocol would look exactly as you described, i.e.
![image](https://user-images.githubusercontent.com/1244701/27632177-9f8f2496-5c03-11e7-8c1b-a091bc781c89.png)


Pls start implementing it.

**Comment by teosarca** [comment]
IMPORTANT: it shall also work together with "tree support"

**Comment by Dunkat** [comment]
done in frontend side, waiting for backend

**Comment by teosarca** [comment]
the backend is already available, see https://github.com/metasfresh/metasfresh-webui-frontend/issues/941#issuecomment-311617799 (2 comments above).
Is there anything that is missing?

**Comment by Dunkat** [comment]
@Teo nope, everything is ok

**Comment by metas-lc** [comment]
IT
1. open picking window 540345
2. select a line, pick
3. select the line in picking => window splits so you can select the picking slots
4. select a picking slot, press on pick HU, select an HU -> start
=> you can see the normal layout for LU-> TU and CU OK + the picking slot is still the top level row OK
