### ISSUE TITLE
grid view: automatically open the included view when clicking on a row

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#942]
### Type of issue
Feature request

### Expected behavior
If configured (e.g. provided in layout),
when clicking a grid view row
then automatically open the included view in the right panel (where it's normally opened).

If you have a suggestion about how to change the protocol, it would be very nice.
If not, i will come with a proposal very soon.

**Comment by cadavre** [comment]
Could you provide live example of how it works now and basically what to change?

**Comment by teosarca** [comment]
Yup.

At the moment, the only way to open an included view is by calling a quick action which returns "instructions" about opening the included view (which one, etc)

What we need (for a new functionality we are developing) is a way to instantly open the included view when user clicks on a row from left side view (the main view).

**Comment by cadavre** [comment]
@damianprzygodzki please provide API response example snippet to implement on backend to work with frontend.

**Comment by damianprzygodzki** [comment]
Firstly i want to highly underline, that we are talking about __functionality in modal__ because only there includedViews are available.

GET /rest/api/documentView/{windowId}/layout
```
{
  ...,
  supportIncludedViewOnSelect: true
}
```

GET /rest/api/documentView/{windowId}/{viewId}
```
{
  ...,
  results: [
    {
      ...,
      includedView: {
        windowId: "",
        viewId: ""
      }
    },...
  ]
}
```

**Comment by teosarca** [comment]
UPDATE: implemented as suggested, API available on w101.

To test it, open https://w101.metasfresh.com:8443/window/540345 ,
select a line and then call "Pick" quick actions.
A modal it's displayed and that's the modal we are talking about.
That view has "supportIncludedViewOnSelect".

**Comment by Dunkat** [comment]
to open includedView I using viewId from 
```
{
  ...,
  results: [
    {
      ...,
      includedView: {
        windowId: "",
        viewId: ""
      }
    }
  ]
}
```

but always I am getting error "No view found for viewId=...". Should I use different viewId?

![image](https://user-images.githubusercontent.com/21196151/27826495-809c375e-60b3-11e7-901e-355a4d714a63.png)

**Comment by teosarca** [comment]
rolled to w101

**Comment by teosarca** [comment]
found following issue, and i think it's a side effect of this task:

* open manufacturing orders: https://w101.metasfresh.com:8443/window/53009
* select a mfg order and call "Issue/Receipt" quick action
* select a "CO"mponent line
=> at that moment, on the right side, some empty panel is shown but it shall not

I think, the issue was introduced in this task. If not, pls let me know and we can create a new issue.

![image](https://user-images.githubusercontent.com/1244701/28123156-df0b8814-6728-11e7-93a2-b7807c8959d5.png)

**Comment by Dunkat** [comment]
it was because of this task, already fixed and pushed to master

**Comment by metas-lc** [comment]
IT
1. picking -> select a line -> pick -> select a line => right panel opens OK
2. manufacturing order, issue/receipt -> select the product -> select the co-product => each time the right side panel looks fine OK
