### ISSUE TITLE
Show the metasfresh logo centered when there are no KPIs

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#944]
![image](https://user-images.githubusercontent.com/1244701/27541901-544b05f2-5a8e-11e7-8f14-8f81cc1e5e66.png)

This is a follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/905

**Comment by damianprzygodzki** [comment]
<img width="1440" alt="screen shot 2017-06-26 at 15 46 56" src="https://user-images.githubusercontent.com/5701744/27542167-b88c5154-5a86-11e7-8bc1-915278142296.png">

**Comment by damianprzygodzki** [comment]
Looks like master out of date. But anyway additional fix provided.

**Comment by metas-mk** [comment]
Tested. The Logo is centered at the top but not as required in the center of the screen as before.

![image](https://user-images.githubusercontent.com/13365687/27599739-00e468c2-5b6a-11e7-9a6a-377a23c2b138.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works now as required. Done/ Closing.
