### ISSUE TITLE
dashboard: react to websocket notifications

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#945]
### Type of issue
Feature request

### Current behavior
Modify the dashboard in one browser tab.
No other browser tabs which are showing the same dashboard are updated.

As a side effect, when you are removing a KPI, in the other browser tab you will see "error loading data" for that KPI (because backend returned "no item found").

### Expected behavior
Frontend shall listen to dashboard's websocket endpoint and shall update the dashboard instantly.

The websocket endpoint is provided by one of the following endpoints:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/getKPIsDashboardUsingGET
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/getTargetIndicatorsDashboardUsingGET

They will contain the same "websocketEndpoint" because underthehood, on server side there is only one dashboard which defines the KPIs and Target Indicators.

The websocket events types are:
* changeType="dashboardChanged" - fired when the dashboad was changed (item added, removed or item order changed).
* changeType="itemChanged" - fired when a dashboard item was changed (e.g. caption, interval, when changed).

This is a follow-up of https://github.com/metasfresh/metasfresh-webui-frontend/issues/905

**Comment by metas-rc** [comment]
Results of IT

Tested on mf15releasetest webui

* Deactivating a kpi leads to "No loading data"  in the second tab => NOK
* Followup created in backend: https://github.com/metasfresh/metasfresh-webui-api/issues/489
