### ISSUE TITLE
Define refactoring plan for filters model

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#948]
### Current behavior
Reading the comment from https://github.com/metasfresh/metasfresh-webui-frontend/issues/864#issuecomment-311264001 it seems the filters model is broken.

### Expected behavior
Define precisely what's broken and elaborate a plan to refactor/fix that.

For now, this task is about identifying the "filters model" issues and gaps and finding a plan to fix it.

**Comment by damianprzygodzki** [comment]
1. Static filters are delivered without layout. At least type of filter is part of layouting, not the data. For now method for rendering and sortin the filters uses data also to render filters. NOK.
2. Filters used to be allowed to be active one at a time. If there are static filters, they are served like mixed types in one array. NOK. View flickering, the static filters disappear.
3. Sometimes when using the filters with static filters applied, the active filter model seems corrupted.
<img width="750" alt="screen shot 2017-06-27 at 09 32 48" src="https://user-images.githubusercontent.com/5701744/27576386-1a29bd48-5b1d-11e7-80f7-94324b7a0246.png">

**Comment by cadavre** [comment]
Plan:
1. Move away `static=true` filters from `filters` array in data response.
2. Bring "static filters" as separate component and move its info into data response array property called `?`. @damianprzygodzki please provide a name. ;)
3. On clearing "static filter" – call API endpoint to recreate view disconnected from "static filter".

**Comment by damianprzygodzki** [comment]
GET /rest/api/documentView/{windowId}/{viewId}
```
{
  filters: [],
  firstRow: 0,
  ...,
  staticFilters: [
    {
      caption: "",
      id: ""
    },...
  ]
}
```

DELETE /rest/api/documentView/{windowId}/{viewId}/staticFilter/{staticFilterId}
```
{
  windowId: "",
  viewId: ""
}
```

**Comment by teosarca** [comment]
NOTE, i've changed the backend as described in the post above. It will be available on next rollout.

IMPORTANT: For the time being i am also providing the static filter as I did before (i.e. in the "filters" list, flagged with static:true). That part will be removed completely after this task will be implemented.

**Comment by teosarca** [comment]
API ready and rolled out on w101, see
* http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/getViewDataUsingGET
* http://w101.metasfresh.com:8081/swagger-ui.html#!/view-rest-controller/deleteStickyFilterUsingDELETE

**Comment by Dunkat** [comment]
@teosarca when I'm trying delete static filter, I am getting in respone two static filters, please have a look:

![image](https://user-images.githubusercontent.com/21196151/27856497-a22742d6-616e-11e7-93dc-9ab282bdfb42.png)

**Comment by teosarca** [comment]
will check

**Comment by teosarca** [comment]
rolled to w101

**Comment by metas-lc** [comment]
IT
1. go to a document which has referenced documents. E.g. Sales order
2. select a document and go to referenced documents, Open one e.g. Invoice candidates
=> notice the sticky filter (in my case for order) - the docs are filtered
3. use back and forward buttons 
=> filter is still there - the docs are still filtered OK
4. select the filter
=> filter disappears and all the documents are shown (no filter is applied) OK
5. press back to have the filter again, then select the "go to default documents list" breadcrumb
=> filter disappears and all the documents are shown (no filter is applied) OK

**Comment by teosarca** [comment]
removed legacy code: https://github.com/metasfresh/metasfresh-webui-api/commit/f5ca02525710a8634985e40b2231e8c702d4492d
