### ISSUE TITLE
Board: adding a card as last is not user friendly

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#949]
### Current behavior
Atm, if you want to add a card as last, you need to get very closer to the last added card and drop your card there.
That's not user friendly at all.

### Expected behavior
We shall be able to drop the card anywhere in the remaining space between last card and the bottom of the lane.

![image](https://user-images.githubusercontent.com/1244701/27579190-6544d1ca-5b2f-11e7-99e5-456958148277.png)

This is a followup of https://github.com/metasfresh/metasfresh-webui-frontend/issues/833

**Comment by metas-mk** [comment]
Testing. Dropping Cards at the bottom of a stack does not work. Already reported here: https://github.com/metasfresh/metasfresh-webui-frontend/issues/833#issuecomment-311761825

![image](https://user-images.githubusercontent.com/13365687/27656505-7c49060a-5c49-11e7-9080-d919ae03e264.png)

![image](https://user-images.githubusercontent.com/13365687/27656512-8692c01a-5c49-11e7-94df-5fef2bce5481.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
