### ISSUE TITLE
Dashboard: move the "Open edit mode" button to Actions menu

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#950]
### Type of issue
Feature request

### Expected behavior
* the "Open edit mode" button shall be in Actions menu
* pls introduce an translatable message key for the caption. Also pls communicate it.

![image](https://user-images.githubusercontent.com/1244701/27579605-ca548078-5b30-11e7-9957-2c933b974773.png)

This is a followup of https://github.com/metasfresh/metasfresh-webui-frontend/issues/833

**Comment by cadavre** [comment]
As described, but keep "Add card" for swimlanes where they are now.

**Comment by metas-mk** [comment]
Tested. Works as required besides Message Translations. Queried the Database to find out if a message was created and found 
a) webui.window.closeEditMode
b) webui.window.openEditMode
Translated them in Issue mentioned above. Closing/ Done.
