### ISSUE TITLE
Frontend is broken (showstopper)

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#951]
### Current behavior
1. open the login screen and remark that the trls are not in place

![image](https://user-images.githubusercontent.com/1244701/27588622-7d9ef79c-5b51-11e7-9afb-414c19a6abcc.png)

2. After you login, press on Actions menu(ctrl+1) => the whole page seems to be broken and not reacting.

![image](https://user-images.githubusercontent.com/1244701/27588676-a1dfd34c-5b51-11e7-930f-3bd749394d5c.png)

### Expected behavior
Shall work :)

**Comment by damianprzygodzki** [comment]
Ad.2 Please update from master.

**Comment by damianprzygodzki** [comment]
Should be now okay.

**Comment by metas-mk** [comment]
Tested. Works as required. Closing/ Done.
