### ISSUE TITLE
Notifications message Translations

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#953]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, the Notification messages are not translated when the language is switched.
#### Which are the steps to reproduce?
Switch the Language to en_US for your User and create Shipments from Shipment Candidates. You receive a Notification when that's done. The message is in Language de_DE.
### What is the expected or desired behavior?
What about defining message captions that could look like this (just loud thinking)

"%(doctypename)s  %(docno)s für Partner %(bpvalue)s %(bpname)s wurde erstellt."

For en_US we can then translate to

"%(doctypename)s  %(docno)s for Partner %(bpvalue)s %(bpname)s has been created."

![image](https://user-images.githubusercontent.com/13365687/27622117-603726aa-5bd5-11e7-973e-2fae802d0643.png)

**Comment by damianprzygodzki** [comment]
Notifications are coming totally from API. Nothing to translate on frontend site. 

Whats more - checked - after changing langauge notifications also are changing, so everything is working as expected.

Wrong repo.

**Comment by teosarca** [comment]
yup, you are right.
