### ISSUE TITLE
Caption Translation not working for Sidelist Menu

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#956]
### Type of issue
Bug
### Current behavior
Currently, the caption Translation does not work for Sidelist Menu mainScreen.Sidelist.tooltip.
### Expected behavior
Shall work.
### Steps to reproduce
Open any window in metasfresh as MainView and hover over the Sidelist menu.

![image](https://user-images.githubusercontent.com/13365687/27639497-aaeaf01e-5c16-11e7-9bbb-9de42fe1667e.png)

**Comment by metas-lc** [comment]
tested in https://github.com/metasfresh/metasfresh-webui-frontend/issues/957
