### ISSUE TITLE
Sidelist toolips: Remaining translations for static messages not in Frontend

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#957]
### Type of issue
Bug
### Current behavior
Currently, the Sidelist tooltips static elements are not translated although API is sending them translated.
### Expected behavior
Shall be translated.
### Steps to reproduce
Open window/143 in main view. Open the sidelist. Hover over the Sidelist elements to see the tooltip.

![image](https://user-images.githubusercontent.com/13365687/27645228-e43775cc-5c25-11e7-8324-10549dad8253.png)

**Comment by metas-lc** [comment]
IT
change your language to EN
open any window in main view. Open the sidelist. Hover over the Sidelist elements to see the tooltip.
=> the elements are translated in EN OK

change your language to DE
open any window in main view. Open the sidelist. Hover over the Sidelist elements to see the tooltip.
=> the elements are translated in DE OK
