### ISSUE TITLE
Modal Overlay not translated although captions exists

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#959]
### Type of issue
Bug
### Current behavior
"Done" is not translated in modal overlays. Is translated w/  "Bestätigen" in the message. Same for "x items selected"
### Expected behavior
Shall be shown translated.
### Steps to reproduce
Open window/540196, select a row and quickaction to open the HU Editor.

webui.modal.actions.done

![image](https://user-images.githubusercontent.com/13365687/27646538-2a179916-5c29-11e7-8f24-0215c8f703a8.png)

webui.view.itemsSelected.caption

![image](https://user-images.githubusercontent.com/13365687/27646913-3bebaa1e-5c2a-11e7-9e4e-af3cc8dc9932.png)

**Comment by metas-mk** [comment]
Partially taken out of issue https://github.com/metasfresh/metasfresh-webui-frontend/issues/924 as follow up.

**Comment by teosarca** [comment]
TODO for backend: handle the "view.itemsSelected.caption"

**Comment by metas-lc** [comment]
IT
"items selected" and "done" are translated. 
the number of selected items is missing. task: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1005
