### ISSUE TITLE
Actions overlay menu cleanup

### ISSUE THREAD

**Issue by cadavre** [metasfresh/metasfresh-webui-frontend#96]
- Remove usused Action menu elements.

Overlay actions menu:
- Clone: implement from API.
- Delete: add prompt.

**Comment by damianprzygodzki** [comment]
We are waiting here for clone.

**Comment by cadavre** [comment]
Waiting for Clone. Are we implementing this or shall we remove it from menu for now?

**Comment by metas-mk** [comment]
We will address this issue after other prioritized issues in aprox. 2 weeks. Please leave the "clone" action in menu until then.

**Comment by cadavre** [comment]
@Dunkat please remove "Clone" from actions menu if it still exists. We can simply add it again if necessary.

**Comment by teosarca** [comment]
fine for me.

NOTE: in future we shall come up with some API similar with grid view quick actions, so the frontend would provide what's possible and what's not possible (e.g. print, clone, delete etc).

**Comment by cadavre** [comment]
Definitely +1 @teosarca for generating from API. For now – just remove and another issue can be made.

**Comment by damianprzygodzki** [comment]
I've allowed myself to quick fix that.

**Comment by damianprzygodzki** [comment]
Can we close it? I think here is nothing to test.

**Comment by teosarca** [comment]
quick checked, the Clone action item is no longer there => OK
