### ISSUE TITLE
again: Editing in the middle of a text field makes the cursor jump to the end

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#964]
### Type of issue
Bug
### Current behavior
see #474 #544 

### Expected behavior
behaves like a text field

### Steps to reproduce
1. use chrome as browser
1. log in 
1. open https://w101.metasfresh.com:8443/window/123/2156481
1. click on tab "contact"
1. click in the middle of field "firstname"
1. enter text
1. NOK: after one character cursor jumps to end of line

![image](https://user-images.githubusercontent.com/16079655/27803551-563466dc-602a-11e7-972e-d4db9b37a81a.png)

**Comment by wiadev** [comment]
We were getting InputValue from props from textfield value but we were actually updating state's data field in MastWindow widget

I've sent a PR for this fix.

**Comment by metas-ts** [comment]
Hi, @metas-mk @metas-lc 
Just rolled it out on the IT server. Please test and ping me for merge.

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
