### ISSUE TITLE
Error after re-login try after timeout

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#965]
### Type of issue
Bug
### Current behavior
When a user is logged out automatically because of timeout, and then just logs in again, without refresh, this leads to error and does not login.
### Expected behavior
Shall have no errors and shall login properly.
### Steps to reproduce
As described above.

![image](https://user-images.githubusercontent.com/13365687/27762747-2076965e-5e78-11e7-8dc2-1b994e8e8ff5.png)

**Comment by metas-mk** [comment]
Tried to reproduce w/ 2 different browser tab, logged in. then logout in one. go to the initial tab and press home button. automatic logout happens but the error doesn't occur. perhaps it's a combination of timeout and new rollout that leads to that error.
discussed w/ @Dunkat to postpone this one until we have better info how to reproduce.

**Comment by teosarca** [comment]
yup, i also believe so.... I've also observed weird frontend behavior when doing a rollout in meantime, but unfortunately i don't have a pattern.
In my case of was showing the "no connection" overlay of which i could not get rid sometimes, even if i refresh the page. In that case the workaround was to open the frontend in a new browser tab.

**Comment by metas-mk** [comment]
@teosarca @Dunkat I observed the described behavior during the last 2 days in different combinations, including Timeout & Rollout. The described issue did not occur anymore. I will close this issue and we can open a new one again if it pops up again.
