### ISSUE TITLE
Navigation with arrows in modal windows gets to the background lines

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#968]
### Type of issue
* Bug
### Current behavior
* Open a window with rows, select a row, open modal window which also contains rows. Navigate with arrows up and down in the modal window. Sometimes, the navigations stops in the modal window and you see the lines selected one by one in the background window.
### Expected behavior
* Modal window shall not allow any action on any other window while it is open.
### Steps to reproduce
* Create sales orders and complete them => There will be some entries in shipment candidates
* Go to Packageables window (540345)
* Select one line and click on the action "Pick" => a modal window opens
* Navigate with the arrows up and down this window
* First arrow down:
![image](https://user-images.githubusercontent.com/16001442/27789451-529aa9d0-5ff5-11e7-895e-67e5e5ee75a7.png)

* Second arrow down (NOK):
 
![image](https://user-images.githubusercontent.com/16001442/27789534-b110fea6-5ff5-11e7-82a0-ace7621277af.png)

* Arrow up (NOK)
![image](https://user-images.githubusercontent.com/16001442/27789713-3edfc94c-5ff6-11e7-893b-781129422e47.png)

Remove this part if feature request.

**Window:** enter window ID or Navigation menu step-by-step.
 https://mf15releasetest/window/540345?viewId=540345 (shall be similar in w101)
**Entity:** enter document ID or steps to reproduce environment.

/or/

**Link:** link to w101.

**Pre-filled data:** which inputs shall be filled before?

**Comment by metas-rc** [comment]
The same thing happens in Receipt candidates, if I open the HUEditor for one line.

**Comment by teosarca** [comment]
Seems this one was introduced (or not fixed?) on https://github.com/metasfresh/metasfresh-webui-frontend/issues/968

**Comment by metasnw** [comment]
very important. Problem is only reproducable when you click on the second column of the grid:
![image](https://user-images.githubusercontent.com/16079655/27873671-39ddeae2-61ad-11e7-8e4c-d45249228fd8.png)

**Comment by metas-lc** [comment]
IT
navigating with up and down arrows in modal doesn't affect the window behind (no matter which field you select. Tried in both picking and receipt candidates)
found a small issue while testing this task. When you open picking, sometimes the first row is not selected, but a random one. Created task https://github.com/metasfresh/metasfresh-webui-frontend/issues/1006
