### ISSUE TITLE
Page Up and Page Down load all data even if there is only one page

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#971]
### Type of issue
* Bug
### Current behavior
* If there ar elines in a window that are all included in 1 page, ,pressing the PgUp and PgDn keys load all the data nevertheless
### Expected behavior
* In such case, the data shall not be reloaded 
### Steps to reproduce
* Go to a window with few lines. I tried with Lieferung but it happend everywhere
* GO to a line then start pressing PgUp and PgDn
* => NOK: On each key pressing the data is loaded

![image](https://user-images.githubusercontent.com/16001442/27791075-f9b28368-5ffb-11e7-892d-7437a80753fc.png)

**Comment by metas-ts** [comment]
We rolled out the PR to our IT instance.
@metas-mk can you please take a look?
