### ISSUE TITLE
Disable/ Enable on quick actions do not happen smoothly

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#973]
### Type of issue
* Bug/ Enhancement
### Current behavior
* Sometimes, when starting a quick action, there are several quick action names  displayed for fractions of a second between the point when the action is clicked and a new action in displayed as default.
### Expected behavior
* The transition shall happen smoothly, without any useless processing.
### Steps to reproduce

* Always keep an eye on the quick action default button ( when it turns grey/ green and what name it contains). Pay attention because the transition is very quick if you have a good internet connection.

 *Start by clicking this button in receipt candidates:
![actions1](https://user-images.githubusercontent.com/16001442/27793653-937ef28c-6007-11e7-9ac5-c752aa7731be.png)

*Then, click this button after the HU is received: 

![action4](https://user-images.githubusercontent.com/16001442/27793690-b380c1be-6007-11e7-9006-06fdffef5a54.png)

**Comment by metas-mk** [comment]
could belong to https://github.com/metasfresh/metasfresh-webui-frontend/issues/933

**Comment by cadavre** [comment]
Need tests after integration of #933 .

**Comment by metas-mk** [comment]
Tested. Works as required. Done/ Closing.
