### ISSUE TITLE
create material receipt button is grey

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#974]
### Type of issue
Bug 
### Current behavior
create material receipt button gets grey when you use, for e.g. transform on an HU
(you don't really have to use transform, you can cancel it) 
### Expected behavior
create material receipt button shouldn't become grey if the HUs are still ok to receive
### Steps to reproduce
1. go to material receipt candidates (window 540196) and select one with a product
2. press on the receive hu button
3. select the LU and press on transform, then press cancel
=>  "create material receipt" button is grey and looks readonly, when in fact is not.. you can create inout and if you are fast enough you can create 2 inouts NOK
(also, see the HU lines. They are not readonly => "create material receipt" button should be editable and green as well)

**Window:** 
540196 

![grey_button](https://user-images.githubusercontent.com/16001666/27801063-b944caba-6024-11e7-8912-73ddcc1cdb91.png)

**Comment by teosarca** [comment]
got it randomly in other views too.

**Comment by teosarca** [comment]
I think this issue was introduced by https://github.com/metasfresh/metasfresh-webui-frontend/issues/933 .
I would suggest a hotfix if possible, if not let's revert #933.

**Comment by metas-ts** [comment]
just created branch `20170628-release-157-br` for today's customer rollout with #933 being reverted.
i would like to also revert it in `master` and `release` for now. The commit https://github.com/metasfresh/metasfresh-webui-frontend/commit/2e474fb802995ec26d51c4c2cb78905484df0d98 looks a bit hard to maintain anyways.
There is probably a different solution..

WDYT @metas-mk @metasnw ?

**Comment by metas-mk** [comment]
Solution proposal fine for me.

**Comment by cadavre** [comment]
Please recheck after #933 is integrated now.

**Comment by metas-mk** [comment]
Will try to reproduce first.

**Comment by teosarca** [comment]
pls test it again. might be that it's solved.

**Comment by metas-rc** [comment]
Results of IT

Retested and it works fine now. The button is green as soon as I cancel the Transform process.
