### ISSUE TITLE
Add frontend support for modifying the KPI config (caption, offset, etc)

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#977]
### Type of issue
Feature request
### Current behavior
Currently, if a user wants to modify the caption(name)  or offset of a KPI, they have to go to "Elastic Search KPI"  and change in the table.
### Expected behavior
The caption, offset , etc shall be editable in the KPI widget itself. 
### Steps to reproduce
Try and see

Note: Talked with Teo and this is supported by the backend.

**Comment by teosarca** [comment]
API endpoints:
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeKPIItemUsingPATCH
* http://w101.metasfresh.com:8081/swagger-ui.html#!/dashboard-rest-controller/changeTargetIndicatorItemUsingPATCH

**Comment by cadavre** [comment]
Waiting for more docs from @teosarca about how to use API.

**Comment by teosarca** [comment]
Those 2 API endpoints (which  work basically in the same way, just that one is about KPIs while the other is about Target Indicators) accepts the standard PATCH format, i.e.
```
[
  {
    "op": "replace",
    "path": "caption",
    "value": {}
  }
]
```
The op (operation) shall be "replace".

The "path" and "value" can be:

1. "path":"caption" => the value shall be the new caption
2. "path":"interval" => the value can be "week" (yes, there is one value supported atm)
3. "path":"when" => the value can be "now", "lastWeek"

NOTE: in future we will support more values, we might even introduce an endpoint for fetching available values but for now we stick with what we have :)

**Comment by metas-lc** [comment]
IT
1. dashboard -> actions menu -> open edit mode
=> each kpi has a gear and if you select it you can change: caption , interval and when 

2. set them all 
=> noticed that the numbers and name change OK
=> question: i notice that once you set interval or when , you can't set them back to null. Wanted?
=> question: notice that the KPI you updated changes it's place. Is that wanted?

3. get back in gear
=> name is as you last set it
=> interval and when are empty. OK? Wanted? if you press ok it won't return to initial value..
