### ISSUE TITLE
Make Avatar and Notifications accessible in Edit mode

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#978]
### Type of issue
Bug
### Current behavior
Avatar and Notifications are not  accessible in Edit mode, because they are behind the Target indicator/Add KPI widget.

![image](https://user-images.githubusercontent.com/16001442/27834915-7fe2b2b0-60e1-11e7-857b-f804cfe66912.png)

### Expected behavior
The Avatar and Nofications shall be brought over this Target indicator/Add KPI widget.
### Steps to reproduce
* Open Edit mode
* Try to logout

**Comment by cadavre** [comment]
Please display avatar/notifications menus on top.

**Comment by teosarca** [comment]
rolled to w101

**Comment by metas-lc** [comment]
IT
open settings => i can see notifications and i can use user profile. ok
