### ISSUE TITLE
Use the Provided Endpoint w/ entry selections for given Breadcrumb

### ISSUE THREAD

**Issue by metas-rc** [metasfresh/metasfresh-webui-frontend#979]
### Type of issue
Bug
### Current behavior
Endpoint provided by the API is not used.
### Expected behavior
It shall be used so we don't have to modify the frontend in future, if we want to modify the breadcrumb logic.
### Steps to reproduce
* Inspect the breadcrumb while clicking on nodes in menu
* NOK: The whole tree is provided instead of the node you selected.

* Backend counterpart: https://github.com/metasfresh/metasfresh-webui-api/issues/465
* It should have been fixed in : https://github.com/metasfresh/metasfresh-webui-frontend/issues/920

**Comment by teosarca** [comment]
i.e. use http://w101.metasfresh.com:8081/swagger-ui.html#!/menu-rest-controller/getNodeBreadcrumbMenuUsingGET

**Comment by metas-ts** [comment]
it's now rolled out on our IT isntance, but *not* yet integrated into `master`

**Comment by metas-lc** [comment]
IT (not master)
go to a window (e.g. Product) and select the breadcrumb. See inspection => only the nodes from the breadcrumb menu are shown OK

**Comment by metas-lc** [comment]
![breadcrumb](https://user-images.githubusercontent.com/16001666/28059678-99e53394-662d-11e7-89c2-ab1329e3d344.png)


found this issue. That breadcrumb should only go back to sales orders

**Comment by metas-mk** [comment]
error belongs to this issue https://github.com/metasfresh/metasfresh-webui-frontend/issues/1008
task chat started there. please move both when solved.

**Comment by teosarca** [comment]
and more, when the grid view is loaded the breadcrumb endpoint is called for each menu item.
That's not efficient at all because might be that user will never click on those items.

![image](https://user-images.githubusercontent.com/1244701/28106473-a0029c84-66ec-11e7-916e-f8d491eb4238.png)

**Comment by cadavre** [comment]
Also #1009 is caused by this change.

**Comment by wiadev** [comment]
getWindowBreadcrumb called twice in two different components. These calls are chronologically very close each to other and simply first requests are not resolved at a moment, thus results not cached. And after this is fires second time. This doesn't happens every single refresh, but happens pretty often. 
fixes are in dev-979

**Comment by metas-rc** [comment]
Results of IT

Tested on webui.


Opened the window Product from the Whole Tree.

When I opened it, the breadcrumb for Product Management was already loaded, and displayed in the inspection. => NOK

![image pasted at 2017-7-14 17-02](https://user-images.githubusercontent.com/16001442/28215654-6792bf38-68b7-11e7-8c2a-6b110c3bdeae.png)


When I clicked on the Product Management, nothing appeared in inspection => NOK

![image](https://user-images.githubusercontent.com/16001442/28215697-8ba9607a-68b7-11e7-8b7c-2b683941bc02.png)


Please, check Teo's comment above:
> and more, when the grid view is loaded the breadcrumb endpoint is called for each menu item.
That's not efficient at all because might be that user will never click on those items.

**Comment by wiadev** [comment]
Probably this could be optimized even further.

We have type=group for breacrumb path request. Which means that those items have dropdown, while type=window means that no dropdown items are defined, so no need even to try to load empty list of sub-items.

But for dropdowns (e.g. type=group) we must send request to get sub-items.
Yes, it could be attached to click event, but obviously it will add some small delay (for me now it shows some 75-150 msecs) and then rendering of menu.

**Comment by metas-ts** [comment]
cherry-picked commit 668efa2a1b12bbc74dd90c3e3416769868e91b5b into the `release` branch

**Comment by metas-lc** [comment]
IT
1. breadcrumbMenu appears only when you select the breadcrumb for menu (e.g. Product management) OK
2. breadcrumb for "go to default document list" goes back to gridview (or if you are already there only refresh) OK
3. when you select the breadcrumb for menu (e.g. Product management) you can see a small delay until it gets populated. Have to check if i shall create a new task and how it should work
