### ISSUE TITLE
New Widget for Date Range

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#981]
### Type of issue
Feature request
### Current behavior
Currently, there is no Widget for Date-Range in WebUI
### Expected behavior
Have a Date Range Widget, similar to what we already have in Filter Widget.

**Comment by wiadev** [comment]
How values of this widget should be persisted in database?

We have single value for each property updated using PATCH request.
My question how to represent date range if we need to store two values (start and end dates).

This could be array of dates, e.g. [start, end]
Or JSON serialized representation, like {"start": 1234, "end": 2345}

Please let me know how to store those values.

**Comment by cadavre** [comment]
Take a look at datetimerange widget used in **filters**. I guess it would be nice to keep same data structure.

**Comment by metas-mk** [comment]
@wiadev you can find an example to see the date-range wiget in action in window/143
press on the first filter "date ordered"
![image](https://user-images.githubusercontent.com/13365687/28104455-5d66c1cc-66db-11e7-8e9b-f2c655110e8f.png)

**Comment by teosarca** [comment]
hi guys,

I think we cannot use the JSON format that we are using for filtering because there we have something like this:
![image](https://user-images.githubusercontent.com/1244701/28108291-a650456c-66f3-11e7-8fe2-7e3d6cf4f6b4.png)


In case of date range process parameter we can agree to something similar to "filters" and also to what @wiadev  proposed, i.e.
```
{ "value":"...", "valueTo":"..." }
```
note: "parameterName" is not needed.

wdyt?

**Comment by teosarca** [comment]
and more, in future we will need support for other "range" types like 
* string range
* integer/amount/quantity etc 

For those cases i would suggest to use the same format (i.e. {"value":"..", "valueTo":".."} ).

But that's for the future.
I am writing it here to have an overview about where we are heading too.

**Comment by teosarca** [comment]
Moving it to backlog, until the API is ready.
But nevertheless, pls feel free to comment and give more input or suggestions.

**Comment by wiadev** [comment]
@teosarca backend api is ready for this issue?

**Comment by teosarca** [comment]
@wiadev  not yet

**Comment by teosarca** [comment]
@wiadev  ready to be developed, see https://github.com/metasfresh/metasfresh-webui-api/issues/491#issuecomment-329758752

**Comment by teosarca** [comment]
for testing you can use https://w101.metasfresh.com:8443/window/540112/1000001
![image](https://user-images.githubusercontent.com/1244701/30480911-d8832e0a-9a24-11e7-9915-6e80eb55976d.png)

**Comment by metas-dh** [comment]
Results of IT1
tested in mf15

* date range widget, e.g. in window 540112: OK
* date range is set as selected, e.g. today, this month, or custom range: OK
