### ISSUE TITLE
Blue Border in modal overlay when Button pressed

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh-webui-frontend#987]
### Type of issue
Bug
### Current behavior
Currently, the Button in modal overlay (process, advanced edit and others) have a blue border when pressed.
### Expected behavior
Shall be like before, w/o a blue border.

![image](https://user-images.githubusercontent.com/13365687/27884957-73590a44-61d6-11e7-9e56-3f92b7342a58.png)

**Comment by teosarca** [comment]
rolled to w101

**Comment by metas-mk** [comment]
Tested. Works as required. Done.
