### ISSUE TITLE
When menu node is not found, at least, render the home icon

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#99]
![image](https://cloud.githubusercontent.com/assets/1244701/20392018/b61e5e72-acde-11e6-9343-28c24f7f4347.png)

**Comment by damianprzygodzki** [comment]
It is not possible til we are creating breadcrumb from elementPath. Now after elementPath request API returining a tree with nodes ("home" node too). And next step is to call for each of them nodePath or rootPath request.

So if you will returning me a breadcrumb without "home" node, i will extract root node definition outside of elementPath rendering.

**Comment by cadavre** [comment]
Basically home icon (and navigation menu) should be displayed everywhere (but login page). We need then to extract root from elementPath. @teosarca your move.

**Comment by teosarca** [comment]
hi,

> home icon (and navigation menu) should be displayed everywhere (but login page).

agree!

> We need then to extract root from elementPath. 

yup, but this is a think u can do on frontend side.
Also, backend API provides nothing special about the root.

> @teosarca your move.

I guess i had to answer if i agree or not.
So, i agree: always render the home (as said above)

**Comment by cadavre** [comment]
> yup, but this is a think u can do on frontend side.
AFAIR we can't. Because calling endpoint may cause an error instead of giving us root info. We can assume to always display 'home' and always trim it from `elementPath` – this way if elementPath API call will fail – we will still be able to display home. @damianprzygodzki ?

**Comment by teosarca** [comment]
Guys,

A call to http://w101.metasfresh.com:8081/rest/api/menu/elementPath?type=window&elementId=143&inclusive=false

would return:

```
{
  "nodeId": "0",
  "caption": "Menu",
  "captionBreadcrumb": "Menu",
  "type": "group",
  "children": [
    {
      "nodeId": "1000010",
      "caption": "Sales",
      "captionBreadcrumb": "Sales",
      "type": "group"
    }
  ]
}

```

so, about the root we would get following info:

```
  "nodeId": "0",
  "caption": "Menu",
  "captionBreadcrumb": "Menu",
  "type": "group",
```

Now, if the endpoint would fail you will not get that info.

Question: what's the crucial information that's needed from there and could not be implemented in frontend exclusively?

**Comment by damianprzygodzki** [comment]
Of course, we can always start rendering without first element but we assumed, that front end is stateless, so it work is to render everything you return from the API.

In case of future changes on the API side, the best option is to do not "hardcode" any rules in process of rendering (for example here, to do not remove always first root node in rendering).

But as i said at the beginning, if you don't want to change API, i can set this value as fixed.
