### ISSUE TITLE
Rename Kandidaten Windows in Dispo Windows in de_DE 

### ISSUE THREAD

**Issue by metasnw** [metasfresh/metasfresh-webui-frontend#990]
### Type of issue
Feature request
### Current behavior
some windows like Lieferdispo are called dispo
and others like Rechnungskandidaten are called kandidaten although there are dispo window

### Expected behavior
have it one way or the other. preferrably all -dispo

### Steps to reproduce
login with DE and see

**Comment by metas-mk** [comment]
wrong repo
