### ISSUE TITLE
hu lines are not visible on the first document

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh-webui-frontend#994]
### Type of issue
Bug
### Current behavior
the first time you create a document, like an order, and you add a product with HU, when you complete you won't see the lines for HUs. If you refresh then you can see it
### Expected behavior
HU lines should be visible from start
### Steps to reproduce
1. you will need a new database. Else i don't know if you can reproduce. It only happens for the first created document of that kind 
2. open purchase order (window 181), create a new one and ad a product with HU
3. complete the order
=> hu line is not added 
4. refresh
=> hu line appears
NOK: it should be visible right after complete (step 3)

5. i also reproduced this issue after creating a manual customer return (window 53097, doctype kundenwareruckgabe). Same steps as above
=> only after complete i saw the HU lines. NOK

**Window:** 
e.g. 181, 53097 (doctype kundenwareruckgabe only)

**Comment by teosarca** [comment]
hmm, that sounds like backend issue

**Comment by metas-lc** [comment]
i'm closing this task because nok it happens all the time (not only on new database) https://github.com/metasfresh/metasfresh-webui-frontend/issues/1216
