### ISSUE TITLE
Picking: quick actions button not shown

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#998]
### Type of issue
Bug

### Steps to reproduce
* open picking window: https://w101.metasfresh.com:8443/window/540345
* select a line and press the "Pick" quick actions button
=> the picking modal is opened but the "quick actions" button is not displayed because the quick actions endpoint was not called 

![image](https://user-images.githubusercontent.com/1244701/28024868-854b65cc-659a-11e7-9478-1fa321eefed1.png)

### Expected behavior
The first row is selected so the quick actions shall be fetched for that row.

The workaround would be to select another row and select back that row, but in case there is only one row i cannot apply this workaround.

Remove this part if feature request.

**Window:** enter window ID or Navigation menu step-by-step.

**Entity:** enter document ID or steps to reproduce environment.

/or/

**Link:** link to w101.

**Pre-filled data:** which inputs shall be filled before?

**Comment by metas-rc** [comment]
Results of IT:

Tested on webui

When opening the modal for the picking editor, the actions are not directly displayed for the selected row ( followup created: https://github.com/metasfresh/metasfresh-webui-frontend/issues/1030) 

But they are displayed after clicking on "Picking slot" or after clicking on the selected line => OK
