### ISSUE TITLE
grid view: use keyboard + and - to expand/collapse included rows

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#999]
### Type of issue
Feature request

### Steps to reproduce / Expected behaviour
* open picking view: https://w101.metasfresh.com:8443/window/540345
* navigate with arrow up/down => OK, works
* press + or - to expand/collapse the included rows for currently selected row => not working but this is what needs to be implemented here :)

![image](https://user-images.githubusercontent.com/1244701/28025635-9e6d737c-659c-11e7-94aa-f69f51440bcf.png)

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. go to picking window, use up and down arrow to navigate. Select a line
2. use + and - buttons to expand/collapse the included rows for currently selected row
=> works fine OK
